Repository RocketChat/Rocket.Chat, pull requests merged in 2018-06, with the labels that each got.

#10974 [FIX] Setup wizard info panel width
  packages/rocketchat-theme/client/imports/components/setup-wizard.css
Labels: subj: ui/ux

#10914 [FIX] Directory search field labelling
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-theme/client/imports/components/modal/directory.css
  packages/rocketchat-ui/client/views/app/directory.html
Labels: subj: ui/ux

#10367 [FIX] Display vertical scrollbar on demand
  packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
Labels: subj: ui/ux

#9705 [FIX] Fix the capital letters issue in username on accountProfile page
  packages/rocketchat-ui-account/client/accountProfile.js
Labels: subj: ui/ux

#10091 [NEW] Send LiveChat visitor navigation history as messages
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-lib/server/models/Messages.js
  packages/rocketchat-livechat/.app/client/lib/hooks.js
  packages/rocketchat-livechat/.app/client/views/messages.js
  packages/rocketchat-livechat/.app/imports/client/visitor.js
  packages/rocketchat-livechat/client/views/app/tabbar/visitorNavigation.html
  packages/rocketchat-livechat/client/views/app/tabbar/visitorNavigation.js
  packages/rocketchat-livechat/config.js
  packages/rocketchat-livechat/messageTypes.js
  packages/rocketchat-livechat/package.js
  packages/rocketchat-livechat/server/hooks/sendToCRM.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/methods/pageVisited.js
  packages/rocketchat-livechat/server/methods/registerGuest.js
  packages/rocketchat-livechat/server/methods/sendTranscript.js
  packages/rocketchat-livechat/server/methods/setDepartmentForVisitor.js
  packages/rocketchat-livechat/server/models/Messages.js
  packages/rocketchat-livechat/server/models/Rooms.js
  packages/rocketchat-livechat/server/publications/visitorPageVisited.js
  packages/rocketchat-theme/client/imports/general/base_old.css
  server/startup/migrations/v123.js
Labels: stat: board-postponed

#10134 [FIX] Fix spelling of "collaborative"
  packages/rocketchat-channel-settings/client/views/channelSettings.html
Labels: stat: waiting response

#9959 [FIX] Rooms list sorting by activity multiple re-renders and case sensitive sorting alphabetically
  packages/rocketchat-api/server/v1/users.js
  packages/rocketchat-authorization/client/lib/models/Users.js
  packages/rocketchat-authorization/server/models/Base.js
  packages/rocketchat-lib/client/lib/cachedCollection.js
  packages/rocketchat-lib/lib/getUserPreference.js
  packages/rocketchat-lib/lib/roomTypes/conversation.js
  packages/rocketchat-lib/lib/roomTypes/direct.js
  packages/rocketchat-lib/lib/roomTypes/favorite.js
  packages/rocketchat-lib/lib/roomTypes/private.js
  packages/rocketchat-lib/lib/roomTypes/public.js
  packages/rocketchat-lib/lib/roomTypes/unread.js
  packages/rocketchat-lib/server/startup/settings.js
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-tokenpass/client/roomType.js
  packages/rocketchat-ui-master/client/main.js
  packages/rocketchat-ui-sidenav/client/chatRoomItem.js
  packages/rocketchat-ui-sidenav/client/roomList.js
  packages/rocketchat-ui-sidenav/client/sideNav.js
  packages/rocketchat-ui-sidenav/client/sidebarHeader.js
  packages/rocketchat-ui-sidenav/client/sidebarItem.html
  packages/rocketchat-ui-sidenav/client/sidebarItem.js
  packages/rocketchat-ui-sidenav/client/sortlist.html
  packages/rocketchat-ui-sidenav/client/sortlist.js
  packages/rocketchat-ui-sidenav/client/toolbar.js
  server/methods/channelsList.js
  server/methods/saveUserPreferences.js
  server/startup/migrations/v125.js
  tests/data/user.js
  tests/end-to-end/api/00-miscellaneous.js
  tests/end-to-end/ui/11-admin.js
  tests/pageobjects/administration.page.js
Labels: subj: ui/ux

#10727 [NEW] Command /hide to hide channels
  .meteor/packages
  .meteor/versions
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-slashcommands-hide/client/hide.js
  packages/rocketchat-slashcommands-hide/package.js
  packages/rocketchat-slashcommands-hide/server/hide.js
Labels: subj: ui/ux

#10958 [NEW] Add input to set time for avatar cache control
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/startup/settings.js
  server/startup/avatar.js
Labels: feat: api, feat: rest, type: improvement

#10973 [NEW] Don't ask me again checkbox on hide room modal
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/client/lib/ChannelActions.js
  packages/rocketchat-theme/client/imports/forms/checkbox.css
  packages/rocketchat-theme/client/imports/general/forms.css
  packages/rocketchat-theme/client/imports/general/typography.css
  packages/rocketchat-theme/client/main.css
  packages/rocketchat-ui-account/client/accountPreferences.html
  packages/rocketchat-ui-account/client/accountPreferences.js
  packages/rocketchat-ui/client/views/app/modal.html
  packages/rocketchat-ui/client/views/app/modal.js
Labels: subj: ui/ux

#11027 [NEW] WebDAV(Nextcloud/ownCloud) Storage Server Option
  package.json
  packages/rocketchat-file-upload/server/config/Webdav.js
  packages/rocketchat-file-upload/server/config/_configUploadStorage.js
  packages/rocketchat-file-upload/server/startup/settings.js
  packages/rocketchat-file-upload/ufs/Webdav/client.js
  packages/rocketchat-file-upload/ufs/Webdav/server.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: gsoc-project

#10431 [FIX] Message_AllowedMaxSize fails for emoji sequences
  package.json
  packages/rocketchat-lib/lib/MessageProperties.js
  packages/rocketchat-lib/package.js
  packages/rocketchat-lib/server/methods/sendMessage.js
  packages/rocketchat-lib/tests/server.tests.js
  packages/rocketchat-ui/client/lib/chatMessages.js
Labels: stat: board-postponed

#11095 [FIX] Confirm password on set new password user profile
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-ui-account/client/accountProfile.html
  packages/rocketchat-ui-account/client/accountProfile.js
Labels: subj: ui/ux

#11096 [FIX] Generated random password visible to the user
  packages/rocketchat-ui-flextab/client/tabs/userEdit.js
Labels: subj: ui/ux

#11113 [FIX] Popover position
  packages/rocketchat-ui/client/views/app/popover.html
  packages/rocketchat-ui/client/views/app/popover.js
Labels: subj: ui/ux

#10301 [NEW] Button to remove closed LiveChat rooms
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-i18n/i18n/pt.i18n.json
  packages/rocketchat-livechat/client/views/app/livechatCurrentChats.html
  packages/rocketchat-livechat/client/views/app/livechatCurrentChats.js
  packages/rocketchat-livechat/package.js
  packages/rocketchat-livechat/server/methods/removeRoom.js
  server/startup/migrations/v127.js
Labels: stat: board-postponed

#11021 [FIX] title and value attachments are optionals on sendMessage method
  packages/rocketchat-lib/server/functions/sendMessage.js
Labels: feat: api, type: regression

#10095 [FIX] Various lang fixes [RU]
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/ru.i18n.json
  packages/rocketchat-ui-sidenav/client/sortlist.html
Labels: subj: ui/ux

#11010 [FIX] /groups.invite not allow a user to invite even with permission
  packages/rocketchat-api/server/v1/groups.js
Labels: feat: api, feat: rest, type: bug

#11132 [FIX] Remove failed upload messages when switching rooms
  packages/rocketchat-ui/client/lib/fileUpload.js
  packages/rocketchat-ui/client/views/app/room.js
Labels: subj: ui/ux

#11178 [FIX] Room creation error due absence of subscriptions
  packages/rocketchat-ui-sidenav/client/roomList.js
Labels: subj: ui/ux

#11183 [FIX] remove sidebar on embedded view
  packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-ui-master/client/main.html
  packages/rocketchat-ui-master/client/main.js
Labels: subj: ui/ux, type: bug

#11177 [FIX] Livechat icon with status
  packages/rocketchat-livechat/roomType.js
  packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
  packages/rocketchat-ui-sidenav/client/sidebarItem.html
  packages/rocketchat-ui-sidenav/client/sidebarItem.js
Labels: subj: ui/ux

#11165 [FIX] Rendering of emails and mentions in messages
  packages/rocketchat-autolinker/client/client.js
  packages/rocketchat-colors/client/client.js
  packages/rocketchat-issuelinks/client.js
  packages/rocketchat-mapview/client/mapview.js
  packages/rocketchat-mentions/Mentions.js
  packages/rocketchat-mentions/tests/client.tests.js
Labels: subj: ui/ux

#11026 [IMPROVE] UI design for Tables and tabs component on Directory
  packages/rocketchat-theme/client/imports/components/header.css
  packages/rocketchat-theme/client/imports/components/modal/directory.css
  packages/rocketchat-theme/client/imports/components/table.css
  packages/rocketchat-theme/client/imports/components/tabs.css
  packages/rocketchat-theme/client/main.css
  packages/rocketchat-ui-master/public/icons.svg
  packages/rocketchat-ui/client/components/table.html
  packages/rocketchat-ui/client/components/table.js
  packages/rocketchat-ui/client/components/tabs.html
  packages/rocketchat-ui/client/components/tabs.js
  packages/rocketchat-ui/client/views/app/directory.html
  packages/rocketchat-ui/client/views/app/directory.js
  packages/rocketchat-ui/package.js
  server/methods/browseChannels.js
Labels: subj: ui/ux

#11150 [FIX] Default selected language
  client/startup/startup.js
  packages/rocketchat-ui-account/client/accountPreferences.html
  packages/rocketchat-ui-account/client/accountPreferences.js
  packages/rocketchat-ui-admin/client/admin.html
  packages/rocketchat-ui-admin/client/admin.js
Labels: subj: ui/ux

#11200 Regression: Directory user table infinite scroll doesn't working
  packages/rocketchat-ui/client/components/table.js
  packages/rocketchat-ui/client/views/app/directory.js
Labels: subj: ui/ux

#10447 [FIX] Add parameter to REST chat.react endpoint, to make it work like a setter
  package-lock.json
  packages/rocketchat-api/server/v1/chat.js
  packages/rocketchat-reactions/setReaction.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, feat: api, feat: rest, stat: board-postponed

#11204 [FIX] REST endpoint `users.updateOwnBasicInfo` was not returning errors for invalid names and trying to save custom fields when empty
  server/methods/saveUserProfile.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest, type: bug

#10799 [BREAK] Always remove the field `services` from user data responses in REST API
  packages/rocketchat-api/server/api.js
  packages/rocketchat-api/server/helpers/parseJsonQuery.js
Labels: feat: api, feat: rest

#11008 Add verification to make sure the user exists in REST insert object helper
  packages/rocketchat-api/server/helpers/insertUserObject.js
Labels: feat: api, feat: rest

#10999 [FIX] REST API: Add more test cases for `/login`
  packages/rocketchat-api/server/api.js
  tests/end-to-end/api/00-miscellaneous.js
Labels: feat: api, type: improvement

#10113 IRC Federation: RFC2813 implementation (ngIRCd)
  .meteor/versions
  package.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-irc/.npm/package/.gitignore
  packages/rocketchat-irc/.npm/package/README
  packages/rocketchat-irc/.npm/package/npm-shrinkwrap.json
  packages/rocketchat-irc/package.js
  packages/rocketchat-irc/server/irc-bridge/index.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/index.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/onCreateRoom.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/onCreateUser.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/onJoinRoom.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/onLeaveRoom.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/onLogin.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/onLogout.js
  packages/rocketchat-irc/server/irc-bridge/localHandlers/onSaveMessage.js
  packages/rocketchat-irc/server/irc-bridge/peerHandlers/disconnected.js
  packages/rocketchat-irc/server/irc-bridge/peerHandlers/index.js
  packages/rocketchat-irc/server/irc-bridge/peerHandlers/joinedChannel.js
  packages/rocketchat-irc/server/irc-bridge/peerHandlers/leftChannel.js
  packages/rocketchat-irc/server/irc-bridge/peerHandlers/nickChanged.js
  packages/rocketchat-irc/server/irc-bridge/peerHandlers/sentMessage.js
  packages/rocketchat-irc/server/irc-bridge/peerHandlers/userRegistered.js
  packages/rocketchat-irc/server/irc-settings.js
  packages/rocketchat-irc/server/irc.js
  packages/rocketchat-irc/server/methods/resetIrcConnection.js
  packages/rocketchat-irc/server/server.js
  packages/rocketchat-irc/server/servers/RFC2813/codes.js
  packages/rocketchat-irc/server/servers/RFC2813/index.js
  packages/rocketchat-irc/server/servers/RFC2813/localCommandHandlers.js
  packages/rocketchat-irc/server/servers/RFC2813/parseMessage.js
  packages/rocketchat-irc/server/servers/RFC2813/peerCommandHandlers.js
  packages/rocketchat-irc/server/servers/index.js
  packages/rocketchat-irc/server/settings.js
  packages/rocketchat-lib/server/functions/createRoom.js
  packages/rocketchat-lib/server/models/Rooms.js
  packages/rocketchat-livechat/.app/package-lock.json
Labels: feat: irc

#10941 [NEW] REST API endpoint `channels.setDefault`
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  tests/end-to-end/api/02-channels.js
Labels: Contain documentation PR, feat: api, feat: rest

#11206 Regression: Directory css
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-theme/client/imports/components/modal/directory.css
  packages/rocketchat-theme/client/imports/components/table.css
  packages/rocketchat-theme/client/imports/components/tabs.css
  packages/rocketchat-ui/client/views/app/directory.html
  packages/rocketchat-ui/client/views/app/directory.js
  server/methods/browseChannels.js
Labels: subj: ui/ux

#11211 Regression: Sending message with a mention is not showing to sender
  packages/rocketchat-mentions/Mentions.js
Labels: type: release candidate bug

#11232 Regression: Skip operations if no actions on livechat migration
  server/startup/migrations/v123.js
Labels: type: release candidate bug
