Repository RocketChat/Rocket.Chat, pull requests merged in 2018-02, with the labels that each got.

#9640 [FIX] Facebook integration in livechat not working on version 0.61.0
  packages/rocketchat-livechat/imports/server/rest/facebook.js
  packages/rocketchat-livechat/server/sendMessageBySMS.js
Labels: Ready to Merge

#9546 Update to meteor 1.6.1
  .meteor/packages
  .meteor/release
  .meteor/versions
  package-lock.json
  package.json
  packages/autoupdate/autoupdate_client.js
  packages/autoupdate/package.js
  packages/rocketchat-katex/package-lock.json
  packages/rocketchat-livechat/.app/.meteor/packages
  packages/rocketchat-livechat/.app/.meteor/release
  packages/rocketchat-livechat/.app/.meteor/versions
  packages/rocketchat-livechat/.app/package.json
  packages/rocketchat-livechat/app/i18n/af.i18n.json
  packages/rocketchat-livechat/app/i18n/mn.i18n.json
  packages/rocketchat-livechat/app/i18n/sl-SI.i18n.json
  packages/rocketchat-livechat/app/i18n/th-TH.i18n.json
  packages/rocketchat-livechat/app/i18n/vi-VN.i18n.json
  packages/rocketchat-livechat/app/package-lock.json
Labels: Ready to Merge

#9509 [NEW] REST API to use Spotlight
  packages/rocketchat-api/package.js
  packages/rocketchat-api/server/v1/spotlight.js
  tests/end-to-end/api/11-spotlight.js
Labels: feat: api, feat: rest

#9519 [NEW] API to fetch permissions & user roles
  packages/rocketchat-api/package.js
  packages/rocketchat-api/server/v1/permissions.js
  packages/rocketchat-api/server/v1/users.js
  tests/end-to-end/api/01-users.js
  tests/end-to-end/api/11-permissions.js
Labels: Contain documentation PR, Ready to Merge, feat: api, feat: rest

#9312 [NEW] Allow sounds when conversation is focused
  client/notifications/notification.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/startup/settings.js
  packages/rocketchat-ui-account/client/accountPreferences.html
  packages/rocketchat-ui-account/client/accountPreferences.js
  server/methods/saveUserPreferences.js
  tests/pageobjects/administration.page.js
Labels: Ready to Merge

#9298 [NEW] Improved default welcome message
  packages/rocketchat-lib/server/startup/settings.js
Labels: Ready to Merge

#9424 [FIX] 'Query' support for channels.list.joined, groups.list, groups.listAll, im.list
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-api/server/v1/groups.js
  packages/rocketchat-api/server/v1/im.js
  packages/rocketchat-lib/server/functions/saveCustomFieldsWithoutValidation.js
  packages/rocketchat-lib/server/models/Subscriptions.js
  server/methods/createDirectMessage.js
Labels: Ready to Merge

#8933 [NEW] Internal hubot support for Direct Messages and Private Groups
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-internal-hubot/hubot.js
  packages/rocketchat-internal-hubot/settings.js
Labels: Ready to Merge

#9658 [NEW] Add documentation requirement to PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation
