Repository RocketChat/Rocket.Chat, pull requests merged in 2018-05, with the labels that each got.

#10665 [FIX] Channel owner was being set as muted when creating a read-only channel
  packages/rocketchat-lib/server/functions/createRoom.js
  tests/end-to-end/api/05-chat.js
Labels: feat: api

#10674 Correct links in README file
  README.md
Labels: Ready to Merge

#10678 [FIX] Message box emoji icon was flickering when typing a text
  packages/rocketchat-theme/client/imports/components/message-box.css
Labels: Ready to Merge

#10445 [FIX] Improve desktop notification formatting
  packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
Labels: feat: notification, type: improvement

#10523 [NEW] Setup Wizard
  .eslintrc
  .meteor/packages
  .meteor/versions
  client/routes/router.js
  client/startup/userSetUtcOffset.js
  packages/rocketchat-assets/server/assets.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/models/Settings.js
  packages/rocketchat-lib/server/startup/settings.js
  packages/rocketchat-setup-wizard/client/setupWizard.html
  packages/rocketchat-setup-wizard/client/setupWizard.js
  packages/rocketchat-setup-wizard/package.js
  packages/rocketchat-setup-wizard/server/lib/getWizardSettings.js
  packages/rocketchat-statistics/server/functions/get.js
  packages/rocketchat-theme/client/imports/components/setup-wizard.css
  packages/rocketchat-theme/client/imports/forms/input.css
  packages/rocketchat-theme/client/imports/forms/select.css
  packages/rocketchat-theme/client/main.css
  packages/rocketchat-ui-admin/client/admin.js
  packages/rocketchat-ui-master/client/main.html
  packages/rocketchat-ui-master/client/main.js
  public/images/logo/logo-black.svg
  public/images/setup-wizard-intro.png
  server/startup/migrations/v117.js
  tests/end-to-end/ui/00-login.js
  tests/pageobjects/setup-wizard.page.js
Labels: subj: ui/ux

#10720 [FIX] Send a message when muted returns inconsistent result in chat.sendMessage
  packages/rocketchat-lib/server/methods/sendMessage.js
Labels: feat: api, feat: rest, type: bug

#9733 [NEW] Add REST API endpoints `channels.setCustomFields` and `groups.setCustomFields`
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-api/server/v1/groups.js
  packages/rocketchat-channel-settings/package.js
  packages/rocketchat-channel-settings/server/functions/saveRoomCustomFields.js
  packages/rocketchat-channel-settings/server/methods/saveRoomSettings.js
  packages/rocketchat-lib/server/models/Rooms.js
  packages/rocketchat-lib/server/models/Subscriptions.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/03-groups.js
Labels: Contain documentation PR

#10564 [FIX] UI was not disabling the actions when users has had no permissions to create channels or add users to rooms
  packages/rocketchat-lib/client/defaultTabBars.js
  packages/rocketchat-ui-flextab/client/flexTabBar.html
  packages/rocketchat-ui-flextab/client/flexTabBar.js
  packages/rocketchat-ui/client/views/app/createChannel.html
  packages/rocketchat-ui/client/views/app/createChannel.js
  packages/rocketchat-ui/client/views/app/directory.html
  packages/rocketchat-ui/client/views/app/directory.js
  tests/end-to-end/ui/04-main-elements-render.js
  tests/pageobjects/flex-tab.page.js
Labels: Ready to Merge, type: release candidate bug

#10741 [NEW] Now is possible to access files using header authorization (`x-user-id` and `x-auth-token`)
  packages/rocketchat-file-upload/server/lib/FileUpload.js
Labels: feat: api, feat: rest

#10662 [NEW] REST API endpoint `/me` now returns all the settings, including the default values
  packages/rocketchat-api/server/v1/misc.js
  tests/end-to-end/api/00-miscellaneous.js
Labels: Contain documentation PR, feat: api, feat: rest

#10778 [NEW] Add REST endpoint `subscriptions.unread` to mark messages as unread
  packages/rocketchat-api/server/v1/subscriptions.js
  tests/end-to-end/api/10-subscriptions.js
Labels: Contain documentation PR, feat: api, feat: rest

#10488 [NEW] REST API endpoint `settings` now allow set colors and trigger actions
  packages/rocketchat-api/server/v1/settings.js
Labels: Contain documentation PR, feat: api, feat: rest

#10702 [NEW] Add REST API endpoint `users.getUsernameSuggestion` to get username suggestion
  packages/rocketchat-api/server/v1/users.js
  tests/end-to-end/api/01-users.js
Labels: Contain documentation PR, feat: api, feat: rest

#10704 [FIX] Missing option to disable/enable System Messages
  packages/rocketchat-channel-settings/client/views/channelSettings.html
  packages/rocketchat-channel-settings/client/views/channelSettings.js
  packages/rocketchat-lib/lib/RoomTypeConfig.js
  packages/rocketchat-lib/lib/roomTypes/direct.js
  packages/rocketchat-lib/lib/roomTypes/private.js
  packages/rocketchat-lib/lib/roomTypes/public.js
  packages/rocketchat-theme/client/imports/components/userInfo.css
  server/publications/room.js
Labels: subj: ui/ux

#10214 [NEW] View pinned message's attachment
  packages/rocketchat-message-pin/server/pinMessage.js
Labels: subj: ui/ux

#10427 [FIX] Enabling `Collapse Embedded Media by Default` was hiding replies and quotes
  packages/rocketchat-message-attachments/client/messageAttachment.html
  packages/rocketchat-message-attachments/client/messageAttachment.js
Labels: subj: ui/ux

#10608 [NEW] Lazy load image attachments
  .meteor/packages
  .meteor/versions
  packages/rocketchat-lazy-load/client/index.js
  packages/rocketchat-lazy-load/client/lazyloadImage.html
  packages/rocketchat-lazy-load/client/lazyloadImage.js
  packages/rocketchat-lazy-load/package.js
  packages/rocketchat-message-attachments/client/messageAttachment.html
  packages/rocketchat-message-attachments/client/messageAttachment.js
  packages/rocketchat-message-attachments/package.js
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-ui-account/client/avatar/avatar.html
  packages/rocketchat-ui-account/client/avatar/avatar.js
  packages/rocketchat-ui-account/package.js
  packages/rocketchat-ui-sidenav/client/sideNav.js
  packages/rocketchat-ui-sidenav/client/sidebarItem.html
  packages/rocketchat-ui-sidenav/package.js
  packages/rocketchat-ui/client/views/app/room.js
  packages/rocketchat-ui/package.js
Labels: subj: ui/ux

#10677 [NEW] Return the result of the `/me` endpoint within the result of the `/login` endpoint
  packages/rocketchat-api/package.js
  packages/rocketchat-api/server/api.js
  packages/rocketchat-api/server/helpers/getUserInfo.js
  packages/rocketchat-api/server/v1/misc.js
  tests/end-to-end/api/00-miscellaneous.js
Labels: Contain documentation PR, feat: api, feat: rest, type: improvement

#10612 [FIX] Livechat settings not appearing correctly
  packages/rocketchat-livechat/config.js
Labels: Ready to Merge, feat: livechat, type: bug

#10584 [NEW] Options to enable/disable each Livechat registration form field
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt.i18n.json
  packages/rocketchat-livechat/.app/client/lib/_livechat.js
  packages/rocketchat-livechat/.app/client/lib/commands.js
  packages/rocketchat-livechat/.app/client/views/livechatWindow.js
  packages/rocketchat-livechat/.app/client/views/register.html
  packages/rocketchat-livechat/.app/client/views/register.js
  packages/rocketchat-livechat/client/views/app/livechatAppearance.html
  packages/rocketchat-livechat/client/views/app/livechatAppearance.js
  packages/rocketchat-livechat/config.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/methods/getInitialData.js
  packages/rocketchat-livechat/server/methods/saveAppearance.js
  packages/rocketchat-livechat/server/publications/livechatAppearance.js
Labels: Ready to Merge

#10833 Fix: Regression in REST API endpoint `/me`
  packages/rocketchat-api/server/helpers/getUserInfo.js
Labels: feat: api, type: regression

#10835 [FIX] Broadcast channels were showing reply button for deleted messages and generating wrong reply links some times
  packages/rocketchat-lib/client/MessageAction.js
  packages/rocketchat-message-pin/client/actionButton.js
  packages/rocketchat-message-star/client/actionButton.js
  packages/rocketchat-ui-message/client/message.js
  packages/rocketchat-ui/client/lib/chatMessages.js
Labels: subj: ui/ux

#10840 [FIX] Missing pagination fields in the response of REST /directory endpoint
  packages/rocketchat-api/server/v1/misc.js
  packages/rocketchat-ui/client/views/app/directory.js
  server/methods/browseChannels.js
  tests/end-to-end/api/00-miscellaneous.js
Labels: Contain documentation PR, feat: api, feat: rest, type: bug

#10857 Fix: typo on error message for push token API
  packages/rocketchat-api/server/v1/push.js
Labels: subj: wording

#10851 [FIX] Leave room wasn't working as expected
  client/methods/leaveRoom.js
  packages/rocketchat-lib/client/lib/ChannelActions.js
Labels: subj: ui/ux

#10151 [NEW] Continuous sound notifications for new LiveChat rooms
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt.i18n.json
  packages/rocketchat-livechat/client/startup/notifyUnreadRooms.js
  packages/rocketchat-livechat/config.js
  packages/rocketchat-livechat/package.js
  packages/rocketchat-ui/client/lib/notification.js
Labels: stat: board-postponed
