Repository RocketChat/Rocket.Chat, pull requests merged in 2018-07, with the labels that each got.

#11267 [FIX] Livestream muted when audio only option was enabled
  packages/rocketchat-livestream/client/views/liveStreamView.html
  packages/rocketchat-theme/client/imports/components/popout.css
Labels: subj: ui/ux

#11254 [IMPROVE] Setup Wizard username validation, step progress and optin/optout
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/startup/settings.js
  packages/rocketchat-setup-wizard/client/final.html
  packages/rocketchat-setup-wizard/client/final.js
  packages/rocketchat-setup-wizard/client/setupWizard.html
  packages/rocketchat-setup-wizard/client/setupWizard.js
  packages/rocketchat-setup-wizard/package.js
  packages/rocketchat-setup-wizard/server/getSetupWizardParameters.js
  packages/rocketchat-setup-wizard/server/lib/getWizardSettings.js
  packages/rocketchat-theme/client/imports/components/setup-wizard.css
  tests/end-to-end/ui/00-login.js
  tests/pageobjects/setup-wizard.page.js
Labels: subj: ui/ux

#9978 [FIX] Loading avatar suggestions with no internet connection
  packages/rocketchat-ui-account/client/accountProfile.html
Labels: subj: ui/ux

#9754 [FIX] Parse inline code without space before initial backtick
  packages/rocketchat-markdown/parser/original/code.js
  packages/rocketchat-markdown/tests/client.tests.js
Labels: subj: ui/ux

#11342 [FIX] Message attachment's fields with different sizes
  packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
Labels: subj: ui/ux

#9991 [FIX] web app manifest errors as reported by Chrome DevTools
  public/images/manifest.json
Labels: subj: ui/ux

#11313 [FIX] Message popup responsiveness in slash commands
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-ui-message/client/popup/messagePopup.js
  packages/rocketchat-ui-message/client/popup/messagePopupChannel.html
  packages/rocketchat-ui-message/client/popup/messagePopupChannel.js
  packages/rocketchat-ui-message/client/popup/messagePopupSlashCommand.html
Labels: subj: ui/ux

#11319 [FIX] SVG icons code
  packages/rocketchat-ui-master/public/icons.svg
Labels: subj: ui/ux, type: improvement

#11358 [FIX] sort fname sidenav
  packages/rocketchat-ui-sidenav/client/roomList.js
Labels: subj: ui/ux

#11349 [FIX] Record popup
  packages/rocketchat-ui-vrecord/client/VRecDialog.js
  packages/rocketchat-ui-vrecord/client/vrecord.css
  packages/rocketchat-ui-vrecord/client/vrecord.html
Labels: subj: ui/ux

#10119 [FIX] Wrap custom fields in user profile to new line
  packages/rocketchat-theme/client/imports/general/forms.css
Labels: subj: ui/ux

#11462 [FIX] broadcast channel reply
  packages/rocketchat-ui-message/client/message.js
Labels: subj: ui/ux

#9972 [NEW] Sorting channels by number of users in directory
  server/methods/browseChannels.js
Labels: subj: ui/ux

#11450 [FIX] Decrease room leader bar z-index
  packages/rocketchat-theme/client/imports/general/base_old.css
Labels: subj: ui/ux, type: bug

#11486 [IMPROVE] [FIX] Room uploaded files gallery fixes and search form
  client/helpers/escapeCssUrl.js
  client/helpers/log.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/models/Uploads.js
  packages/rocketchat-theme/client/imports/components/contextual-bar.css
  packages/rocketchat-theme/client/imports/components/file-list.css
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-theme/client/imports/general/rtl.css
  packages/rocketchat-theme/client/main.css
  packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.html
  packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.js
  packages/rocketchat-ui/client/components/contextualBar.html
  packages/rocketchat-ui/client/views/app/photoswipe.js
  server/lib/roomFiles.js
  server/publications/roomFiles.js
  server/publications/roomFilesWithSearchText.js
Labels: subj: ui/ux, type: bug, type: improvement

#11303 [NEW] Send user status to client
  client/notifications/updateUserState.js
Labels: subj: ui/ux

#11430 [BREAK] Update GraphQL dependencies
  .meteor/versions
  packages/rocketchat-graphql/.npm/package/npm-shrinkwrap.json
  packages/rocketchat-graphql/package.js
  tests/end-to-end/api/11-graphql.js
Labels: feat: api

#11164 [IMPROVE] Typing indicators now use Real Names
  packages/rocketchat-lib/server/functions/Notifications.js
  packages/rocketchat-ui/client/lib/msgTyping.js
Labels: subj: ui/ux

#11236 [NEW] Message retention policy and pruning
  .meteor/packages
  .meteor/versions
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-api/server/v1/rooms.js
  packages/rocketchat-authorization/server/startup.js
  packages/rocketchat-channel-settings/client/views/channelSettings.html
  packages/rocketchat-channel-settings/client/views/channelSettings.js
  packages/rocketchat-channel-settings/server/methods/saveRoomSettings.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/client/UserDeleted.js
  packages/rocketchat-lib/package.js
  packages/rocketchat-lib/server/functions/cleanRoomHistory.js
  packages/rocketchat-lib/server/functions/deleteUser.js
  packages/rocketchat-lib/server/methods/cleanChannelHistory.js
  packages/rocketchat-lib/server/methods/cleanRoomHistory.js
  packages/rocketchat-lib/server/models/Messages.js
  packages/rocketchat-lib/server/models/Rooms.js
  packages/rocketchat-retention-policy/README.md
  packages/rocketchat-retention-policy/package.js
  packages/rocketchat-retention-policy/server/cronPruneMessages.js
  packages/rocketchat-retention-policy/server/startup/settings.js
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-ui-clean-history/README.md
  packages/rocketchat-ui-clean-history/client/lib/startup.js
  packages/rocketchat-ui-clean-history/client/views/cleanHistory.html
  packages/rocketchat-ui-clean-history/client/views/cleanHistory.js
  packages/rocketchat-ui-clean-history/client/views/stylesheets/cleanHistory.css
  packages/rocketchat-ui-clean-history/package.js
  packages/rocketchat-ui-master/public/icons.svg
  packages/rocketchat-ui/client/lib/RoomManager.js
  packages/rocketchat-ui/client/lib/tapi18n.js
  packages/rocketchat-ui/client/views/app/room.html
  packages/rocketchat-ui/client/views/app/room.js
  server/methods/eraseRoom.js
  server/publications/room.js
  tests/end-to-end/api/02-channels.js
Labels: blogpost, subj: ui/ux

#11526 [FIX] empty blockquote
  packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
  packages/rocketchat-theme/client/imports/general/base_old.css
Labels: subj: ui/ux

#11527 [FIX] Check for channels property on message object before parsing mentions
  packages/rocketchat-mentions/Mentions.js
Labels: subj: ui/ux, type: bug

#11363 [FIX] Loading and setting fixes for i18n and RTL
  client/startup/i18n.js
  client/startup/startup.js
  packages/rocketchat-ui-account/client/accountPreferences.js
  packages/rocketchat-ui-admin/client/admin.js
  packages/rocketchat-ui-login/client/login/footer.html
  packages/rocketchat-ui-login/client/login/footer.js
  packages/rocketchat-ui-master/client/main.js
Labels: feat: i18n, subj: ui/ux

#9449 [FIX] Mixed case channel slugs
  packages/rocketchat-lib/lib/getValidRoomName.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/03-groups.js
Labels: subj: ui/ux

#11496 [FIX] Add customFields property to /me REST endpoint response
  packages/rocketchat-api/server/helpers/getUserInfo.js
Labels: Contain documentation PR, feat: api, feat: rest

#10731 [FIX] Send Livechat back to Guest Pool
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/methods/returnAsInquiry.js
  packages/rocketchat-livechat/server/methods/takeInquiry.js
  packages/rocketchat-livechat/server/models/LivechatInquiry.js
Labels: stat: board-postponed

#11488 [NEW] Add /users.deleteOwnAccount REST endpoint to an user delete his own account
  packages/rocketchat-api/server/v1/users.js
  tests/end-to-end/api/01-users.js
Labels: Contain documentation PR, feat: api, feat: rest

#11531 [FIX] Unreads counter for new rooms on /channels.counters REST endpoin
  packages/rocketchat-api/server/v1/channels.js
Labels: feat: api, feat: rest

#11340 [FIX] Change pagination field to `count` on /chat.search REST endpoint
  packages/rocketchat-api/server/v1/chat.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, feat: api, feat: rest, type: bug

#11534 [FIX] Render reply preview with message as a common message
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-ui-message/client/messageBox.html
Labels: subj: ui/ux, type: bug

#11550 Regression: nonReactive to nonreactive
  packages/rocketchat-ui-message/client/popup/messagePopupConfig.js
Labels: subj: ui/ux

#11567 Regression: Make message popup user mentions reactive again
  packages/rocketchat-ui-message/client/popup/messagePopupConfig.js
  tests/end-to-end/ui/14-message-popup.js
Labels: subj: ui/ux, type: regression
