Repository RocketChat/Rocket.Chat, pull requests merged in 2018-12, with the labels that each got.

#12805 [FIX] Emoji as avatar
  package-lock.json
  packages/rocketchat-emoji/client/emojiButton.js
  packages/rocketchat-emoji/client/index.js
  packages/rocketchat-emoji/package.js
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-ui-message/client/index.js
  packages/rocketchat-ui-message/client/message.js
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui-message/client/renderMessageBody.js
  packages/rocketchat-ui-message/package.js
  packages/rocketchat-ui-sidenav/client/sidebarItem.js
Labels: subj: ui/ux, type: bug

#12727 [FIX] API users.info returns caller rooms and not requested user ones
  packages/rocketchat-api/server/v1/users.js
Labels: feat: rest, type: release candidate bug

#12818 [FIX] Change spread operator to Array.from for Edge browser
  packages/rocketchat-lazy-load/client/index.js
  packages/rocketchat-lib/client/lib/roomExit.js
  packages/rocketchat-ui/client/lib/sideNav.js
Labels: subj: ui/ux, type: bug

#12851 [FIX] Incorrect parameter name in Livechat stream
  packages/rocketchat-livechat/.app/client/lib/_livechat.js
Labels: feat: livechat

#12597 [NEW] Livechat registration form message
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-livechat/.app/client/lib/_livechat.js
  packages/rocketchat-livechat/.app/client/views/livechatWindow.js
  packages/rocketchat-livechat/.app/client/views/register.js
  packages/rocketchat-livechat/client/views/app/livechatAppearance.html
  packages/rocketchat-livechat/client/views/app/livechatAppearance.js
  packages/rocketchat-livechat/config.js
  packages/rocketchat-livechat/server/api/lib/livechat.js
  packages/rocketchat-livechat/server/api/v1/message.js
  packages/rocketchat-livechat/server/api/v1/visitor.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/methods/getInitialData.js
  packages/rocketchat-livechat/server/methods/saveAppearance.js
  packages/rocketchat-livechat/server/publications/livechatAppearance.js
Labels: feat: livechat, type: improvement

#12351 [NEW] Config hooks for snap
  .snapcraft/resources/Caddyfile
  .snapcraft/resources/initcaddy
  .snapcraft/resources/startRocketChat
  .snapcraft/snap/hooks/configure
  .snapcraft/snap/hooks/install
  .snapcraft/snap/snapcraft.yaml
Labels: stat: in progress

#12865 [IMPROVE] Returning an open room object in the Livechat config endpoint
  package-lock.json
  packages/rocketchat-livechat/.app/i18n/en.i18n.json
  packages/rocketchat-livechat/.app/i18n/pt.i18n.json
  packages/rocketchat-livechat/server/api/lib/livechat.js
  packages/rocketchat-livechat/server/api/v1/agent.js
  packages/rocketchat-livechat/server/api/v1/config.js
Labels: feat: livechat, type: improvement

#12882 [FIX] PDF view loading indicator
  packages/rocketchat-message-attachments/client/index.js
  packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
  packages/rocketchat-message-attachments/package.js
  packages/rocketchat-ui-message/client/message.js
Labels: feat: attachments, subj: ui/ux, type: bug

#12900 [FIX] line-height for unread bar buttons (jump to first and mark as read)
  packages/rocketchat_theme/client/imports/general/base_old.css
Labels: subj: ui/ux, type: bug

#12913 [FIX] Some icons were missing
  packages/rocketchat-ui-master/public/icons.svg
Labels: subj: ui/ux, type: bug

#12556 [FIX] Padding for message box in embedded layout
  packages/rocketchat_theme/client/imports/components/message-box.css
Labels: subj: ui/ux, type: bug

#12949 changed maxRoomsOpen
  packages/rocketchat-ui/client/lib/RoomManager.js
Labels: subj: ui/ux

#12983 [FIX] Stop click event propagation on mention link or user card
  packages/rocketchat-ui/client/views/app/room.js
Labels: subj: ui/ux, type: bug

#12948 [FIX] Some deprecation issues for media recording
  .eslintrc
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui-message/client/startup/messageBoxActions.js
  packages/rocketchat-ui/client/lib/recorderjs/audioRecorder.js
  packages/rocketchat-ui/client/lib/recorderjs/recorder.js
  packages/rocketchat-ui/client/lib/recorderjs/videoRecorder.js
Labels: subj: ui/ux, type: bug

#13004 [FIX] Inherit font family in message user card
  packages/rocketchat_theme/client/imports/general/base_old.css
Labels: feat: message, subj: ui/ux, type: bug

#12706 [FIX] Change JSON to EJSON.parse query to support type Date
  packages/rocketchat-api/server/helpers/parseJsonQuery.js
Labels: Contain documentation PR, feat: api, feat: rest, type: bug

#13008 [IMPROVE] Allow transfer Livechats to online agents only
  packages/rocketchat-livechat/client/views/app/tabbar/visitorForward.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/models/Users.js
Labels: feat: livechat, type: improvement

#12998 [FIX] Nested Markdown blocks not parsed properly
  packages/rocketchat-markdown/lib/markdown.js
  packages/rocketchat-markdown/lib/parser/original/code.js
  packages/rocketchat-markdown/tests/client.mocks.js
  packages/rocketchat-markdown/tests/client.tests.js
Labels: feat: message, subj: ui/ux, type: bug

#12874 [NEW] Download button for each file in fileslist
  packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.html
  packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.js
  packages/rocketchat_theme/client/imports/components/contextual-bar.css
Labels: feat: file sharing, subj: ui/ux, type: improvement

#12795 [FIX] E2E`s password reaveal text is always `>%S` when language is zh
  packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: feat: e2e, feat: i18n, type: bug

#12792 [FIX] Provide better Dutch translations 🇳🇱
  packages/rocketchat-livechat/.app/i18n/nl.i18n.json
Labels: feat: i18n, feat: livechat, type: bug

#12722 [IMPROVE] Add missing translation keys.
  packages/rocketchat-apps/client/admin/appManage.html
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-integrations/client/views/integrationsIncoming.html
  packages/rocketchat-integrations/client/views/integrationsOutgoing.html
  packages/rocketchat-ui-admin/client/admin.html
Labels: feat: i18n, subj: ui/ux, type: improvement

#12569 [FIX] Webdav integration account settings were being shown even when Webdav was disabled
  packages/rocketchat-ui-account/client/accountFlex.html
  packages/rocketchat-ui-account/client/accountFlex.js
Labels: subj: ui/ux, type: bug

#13010 [NEW] Added chat.getDeletedMessages since specific date
  packages/rocketchat-api/server/v1/chat.js
  packages/rocketchat-lib/server/models/_Base.js
  packages/rocketchat-lib/server/models/_BaseDb.js
  tests/data/chat.helper.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, feat: api, feat: rest

#12856 [NEW] Added a link to contributing.md
  README.md
Labels: type: documentation

#12790 [FIX] Fix set avatar http call, to avoid SSL errors
  packages/rocketchat-lib/server/functions/setUserAvatar.js
Labels: feat: api, feat: rest

#12754 [NEW] Add query parameter support to emoji-custom endpoint
  packages/rocketchat-api/server/v1/emoji-custom.js
  packages/rocketchat-emoji-custom/server/methods/listEmojiCustom.js
  tests/end-to-end/api/12-emoji-custom.js
Labels: Contain documentation PR, feat: api, feat: rest

#12734 [FIX] Fix users.setPreferences endpoint, set language correctly
  packages/rocketchat-api/server/v1/users.js
  packages/rocketchat-lib/server/functions/saveUser.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest, type: bug

#9748 [NEW] Mandatory 2fa for role
  packages/rocketchat-authorization/client/views/permissionsRole.html
  packages/rocketchat-authorization/client/views/permissionsRole.js
  packages/rocketchat-authorization/server/methods/saveRole.js
  packages/rocketchat-authorization/server/models/Roles.js
  packages/rocketchat-authorization/server/startup.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-ui-master/client/main.html
  packages/rocketchat-ui-master/client/main.js
Labels: design, feat: 2fa, stat: board-postponed, subj: ui/ux

#12748 [NEW] Create new permission.listAll endpoint to be able to use updatedSince parameter
  packages/rocketchat-api/server/v1/permissions.js
  tests/end-to-end/api/11-permissions.js
Labels: Contain documentation PR, feat: api, feat: rest

#12123 [FIX] Avoiding links with highlighted words
  packages/rocketchat-highlight-words/client/client.js
  packages/rocketchat-highlight-words/client/helper.js
  packages/rocketchat-highlight-words/tests/helper.test.js
Labels: subj: ui/ux

#13021 Change `chat.getDeletedMessages` to get messages after informed date and return only message's _id
  packages/rocketchat-api/server/v1/chat.js
  packages/rocketchat-lib/server/models/_Base.js
  packages/rocketchat-lib/server/models/_BaseDb.js
Labels: feat: api, feat: rest

#13033 [FIX] Download files without extension wasn't possible
  packages/rocketchat-file-upload/server/config/GridFS.js
Labels: feat: file sharing, type: bug

#13031 Regression: List of custom emojis wasn't working
  packages/rocketchat-emoji-custom/server/methods/listEmojiCustom.js
Labels: type: release candidate bug
