Repository RocketChat/Rocket.Chat, pull requests merged in 2018-03, with the labels that each got.

#10009 [FIX] REST API: Can't list all public channels when user has permission `view-joined-room`
  packages/rocketchat-api/server/v1/channels.js
Labels: type: bug

#9719 [FIX] Verified property of user is always set to false if not supplied
  packages/rocketchat-api/server/v1/users.js
  packages/rocketchat-lib/server/functions/saveUser.js
  packages/rocketchat-lib/server/functions/setEmail.js
  tests/end-to-end/api/01-users.js
Labels: type: improvement

#9726 [NEW] Audio recording as mp3 and better ui for recording
  .eslintignore
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/startup/settings.js
  packages/rocketchat-theme/client/imports/components/message-box.css
  packages/rocketchat-ui-message/client/messageBox.html
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui-message/startup/messageBoxActions.js
  packages/rocketchat-ui/client/lib/recorderjs/audioRecorder.js
  packages/rocketchat-ui/client/lib/recorderjs/recorder.js
  public/images/circle-check.svg
  public/images/circle-cross.svg
  public/images/loading.svg
  public/lame.min.js
  public/mp3-realtime-worker.js
  public/recorderWorker.js
Labels: subj: ui/ux

#8667 [FIX] Able to react with invalid emoji
  packages/rocketchat-emoji-custom/client/models/EmojiCustom.js
  packages/rocketchat-reactions/client/methods/setReaction.js
  packages/rocketchat-reactions/setReaction.js
  tests/end-to-end/api/05-chat.js
Labels: Ready to Merge

#10144 [NEW] Added endpoint to get the list of available oauth services
  packages/rocketchat-api/server/v1/misc.js
  tests/end-to-end/api/00-miscellaneous.js
Labels: feat: api, feat: rest

#10104 [FIX] Reactions not working on mobile
  packages/rocketchat-reactions/client/init.js
Labels: Ready to Merge

#9860 [FIX] Popover divs don't scroll if they overflow the viewport
  packages/rocketchat-theme/client/imports/components/popover.css
  packages/rocketchat-ui/client/views/app/popover.js
Labels: Ready to Merge

#9739 [FIX] Apostrophe-containing URL misparsed
  packages/rocketchat-autolinker/client/client.js
Labels: Ready to Merge

#9783 [FIX] No pattern for user's status text capitalization
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-ui-sidenav/client/sidebarHeader.js
  packages/rocketchat-ui-sidenav/client/userStatus.html
  packages/rocketchat-ui/client/components/header/header.js
Labels: Ready to Merge

#9672 [FIX] Name of files in file upload list cuts down at bottom due to overflow
  packages/rocketchat-theme/client/imports/components/file-list.css
  packages/rocketchat-theme/client/main.css
Labels: Ready to Merge, subj: ui/ux

#9866 [FIX] User status missing on user info
  packages/rocketchat-ui-flextab/client/tabs/userInfo.html
  packages/rocketchat-ui-flextab/client/tabs/userInfo.js
Labels: Ready to Merge

#10103 [BREAK] Removed Private History Route
  client/routes/router.js
  packages/rocketchat-ui-sidenav/client/sideNav.html
  packages/rocketchat-ui/client/views/app/privateHistory.html
  packages/rocketchat-ui/client/views/app/privateHistory.js
  packages/rocketchat-ui/package.js
  server/publications/privateHistory.js
Labels: Ready to Merge

#10128 [NEW] Added GET/POST channels.notifications
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-lib/server/models/Subscriptions.js
  packages/rocketchat-push-notifications/server/methods/saveNotificationSettings.js
  tests/end-to-end/api/02-channels.js
Labels: feat: api, feat: rest

#9584 [NEW] Add leave public channel & leave private channel permissions
  packages/rocketchat-authorization/server/startup.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/methods/leaveRoom.js
  packages/rocketchat-ui-sidenav/client/sidebarItem.js
  server/startup/migrations/v108.js
Labels: Ready to Merge

#10105 [NEW] Added endpoint to retrieve mentions of a channel
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-mentions/package.js
  packages/rocketchat-mentions/server/methods/getUserMentionsByChannel.js
  tests/end-to-end/api/02-channels.js
Labels: feat: api, feat: rest

#9629 [NEW] Add REST endpoint to get the list of custom emojis
  packages/rocketchat-api/package.js
  packages/rocketchat-api/server/v1/emoji-custom.js
  tests/end-to-end/api/12-emoji-custom.js
Labels: feat: api, feat: rest

#9816 [NEW] Add option to login via REST using Facebook and Twitter tokens
  package-lock.json
  package.json
  packages/rocketchat-lib/package.js
  packages/rocketchat-lib/server/oauth/facebook.js
  packages/rocketchat-lib/server/oauth/twitter.js
Labels: Contain documentation PR, feat: api, feat: rest

#9907 [NEW] Endpoint to retrieve message read receipts
  imports/message-read-receipt/server/api/methods/getReadReceipts.js
  packages/rocketchat-api/server/v1/chat.js
  tests/end-to-end/api/05-chat.js
Labels: feat: api, feat: rest

#10252 Fix: possible errors on rocket.chat side of the apps
  packages/rocketchat-apps/server/converters/rooms.js
  packages/rocketchat-apps/server/converters/users.js
Labels: type: release candidate bug

#10240 [FIX] /me REST endpoint was missing user roles and preferences
  packages/rocketchat-api/package.js
  packages/rocketchat-api/server/helpers/deprecationWarning.js
  packages/rocketchat-api/server/v1/misc.js
  packages/rocketchat-api/server/v1/users.js
  tests/end-to-end/api/00-miscellaneous.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest

#10257 Fix: Renaming channels.notifications Get/Post endpoints
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-api/server/v1/rooms.js
  packages/rocketchat-api/server/v1/subscriptions.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/09-rooms.js
  tests/end-to-end/api/10-subscriptions.js
Labels: feat: api, feat: rest
