Repository RocketChat/Rocket.Chat, pull requests merged in 2018-09, with the labels that each got.

#11849 [FIX] Missing `fname` property in Livechat rooms
  server/startup/migrations/v132.js
Labels: type: bug

#11855 [NEW] REST endpoints to create roles and assign roles to users
  packages/rocketchat-api/server/v1/roles.js
  packages/rocketchat-authorization/server/models/Roles.js
  tests/data/api-data.js
  tests/data/role.js
  tests/end-to-end/api/13-roles.js
Labels: Contain documentation PR, feat: api, feat: rest, feat: roles / permissions

#11967 [FIX] Message reaction in GraphQL API
  packages/rocketchat-graphql/server/resolvers/messages/addReactionToMessage.js
  packages/rocketchat-graphql/server/schemas/messages/addReactionToMessage.graphqls
Labels: feat: api, type: bug

#11953 [FIX] Internal error when cross-origin with CORS is disabled
  packages/rocketchat-api/server/api.js
Labels: feat: api, feat: rest, type: bug

#11905 [NEW] REST endpoint to set groups' announcement
  packages/rocketchat-api/server/v1/groups.js
  tests/end-to-end/api/03-groups.js
Labels: Contain documentation PR, feat: api, feat: rest

#11999 [FIX] Prevent form submission in Files List search
  packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.js
Labels: subj: ui/ux

#12018 [FIX] Fixing spacement between tags and words on some labels
  packages/rocketchat-i18n/i18n/pl.i18n.json
Labels: subj: ui/ux

#11946 [FIX] Fixing translation on 'yesterday' word when calling timeAgo function
  packages/rocketchat-ui/client/views/app/directory.js
  packages/rocketchat-ui/client/views/app/helpers.js
  packages/rocketchat-ui/client/views/app/tests/helpers.tests.js
Labels: subj: ui/ux

#11919 [FIX] Adding scroll bar to read receipts modal
  packages/rocketchat-theme/client/imports/components/modal.css
Labels: subj: ui/ux

#11169 [NEW] User preference for 24- or 12-hour clock
  packages/chatpal-search/client/template/result.js
  packages/rocketchat-api/server/v1/users.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/client/lib/formatDate.js
  packages/rocketchat-lib/client/lib/index.js
  packages/rocketchat-lib/server/models/Users.js
  packages/rocketchat-message-attachments/client/messageAttachment.js
  packages/rocketchat-message-snippet/client/page/snippetPage.js
  packages/rocketchat-ui-account/client/accountPreferences.html
  packages/rocketchat-ui-account/client/accountPreferences.js
  packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.js
  packages/rocketchat-ui-flextab/client/tabs/userInfo.js
  packages/rocketchat-ui-message/client/message.js
  server/methods/saveUserPreferences.js
  tests/data/user.js
Labels: subj: ui/ux

#11909 [NEW] REST endpoints to get moderators from groups and channels
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-api/server/v1/groups.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/03-groups.js
Labels: Contain documentation PR, feat: api, feat: rest

#12043 [FIX] Changing Mentions.userMentionRegex pattern to include <br> tag
  packages/rocketchat-mentions/Mentions.js
  packages/rocketchat-mentions/tests/client.tests.js
Labels: subj: ui/ux

#11900 [NEW] Livechat REST endpoints
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-katex/package-lock.json
  packages/rocketchat-livechat/.app/i18n/en.i18n.json
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-livechat/imports/server/rest/messages.js
  packages/rocketchat-livechat/imports/server/rest/upload.js
  packages/rocketchat-livechat/imports/server/rest/visitors.js
  packages/rocketchat-livechat/package.js
  packages/rocketchat-livechat/server/api.js
  packages/rocketchat-livechat/server/api/lib/livechat.js
  packages/rocketchat-livechat/server/api/rest.js
  packages/rocketchat-livechat/server/api/v1/agent.js
  packages/rocketchat-livechat/server/api/v1/config.js
  packages/rocketchat-livechat/server/api/v1/customField.js
  packages/rocketchat-livechat/server/api/v1/message.js
  packages/rocketchat-livechat/server/api/v1/offlineMessage.js
  packages/rocketchat-livechat/server/api/v1/pageVisited.js
  packages/rocketchat-livechat/server/api/v1/room.js
  packages/rocketchat-livechat/server/api/v1/transcript.js
  packages/rocketchat-livechat/server/api/v1/videoCall.js
  packages/rocketchat-livechat/server/api/v1/visitor.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/methods/closeByVisitor.js
  packages/rocketchat-livechat/server/methods/sendFileLivechatMessage.js
  packages/rocketchat-livechat/server/methods/sendOfflineMessage.js
  packages/rocketchat-livechat/server/methods/sendTranscript.js
  packages/rocketchat-livechat/server/models/Rooms.js
  packages/rocketchat-livechat/server/roomType.js
Labels: documentation: needed, feat: livechat

#11238 [NEW] Livechat Analytics and Reports
  .eslintrc
  package-lock.json
  package.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-livechat/client/collections/LivechatMonitoring.js
  packages/rocketchat-livechat/client/lib/chartHandler.js
  packages/rocketchat-livechat/client/lib/dataHandler.js
  packages/rocketchat-livechat/client/lib/dateHandler.js
  packages/rocketchat-livechat/client/route.js
  packages/rocketchat-livechat/client/stylesheets/livechat.less
  packages/rocketchat-livechat/client/views/app/analytics/livechatAnalytics.html
  packages/rocketchat-livechat/client/views/app/analytics/livechatAnalytics.js
  packages/rocketchat-livechat/client/views/app/analytics/livechatAnalyticsCustomDaterange.html
  packages/rocketchat-livechat/client/views/app/analytics/livechatAnalyticsCustomDaterange.js
  packages/rocketchat-livechat/client/views/app/analytics/livechatAnalyticsDaterange.html
  packages/rocketchat-livechat/client/views/app/analytics/livechatAnalyticsDaterange.js
  packages/rocketchat-livechat/client/views/app/analytics/livechatRealTimeMonitoring.html
  packages/rocketchat-livechat/client/views/app/analytics/livechatRealTimeMonitoring.js
  packages/rocketchat-livechat/client/views/sideNav/livechatFlex.html
  packages/rocketchat-livechat/package.js
  packages/rocketchat-livechat/server/hooks/markRoomResponded.js
  packages/rocketchat-livechat/server/hooks/saveAnalyticsData.js
  packages/rocketchat-livechat/server/lib/Analytics.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/lib/QueueMethods.js
  packages/rocketchat-livechat/server/methods/getAgentOverviewData.js
  packages/rocketchat-livechat/server/methods/getAnalyticsChartData.js
  packages/rocketchat-livechat/server/methods/getAnalyticsOverviewData.js
  packages/rocketchat-livechat/server/methods/takeInquiry.js
  packages/rocketchat-livechat/server/models/LivechatInquiry.js
  packages/rocketchat-livechat/server/models/LivechatVisitors.js
  packages/rocketchat-livechat/server/models/Rooms.js
  packages/rocketchat-livechat/server/publications/livechatMonitoring.js
  packages/rocketchat-livechat/server/publications/livechatVisitors.js
  packages/rocketchat-statistics/server/functions/get.js
Labels: feat: livechat

#12107 [IMPROVE] BigBlueButton joinViaHtml5 and video icon on sidebar
  packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
  packages/rocketchat-ui-sidenav/client/sidebarItem.html
  packages/rocketchat-ui-sidenav/client/sidebarItem.js
  packages/rocketchat-videobridge/server/methods/bbb.js
Labels: subj: ui/ux

#10094 [NEW] Support for end to end encryption
  .meteor/packages
  .meteor/versions
  package.json
  packages/rocketchat-api/server/v1/e2e.js
  packages/rocketchat-channel-settings/client/views/channelSettings.html
  packages/rocketchat-channel-settings/client/views/channelSettings.js
  packages/rocketchat-channel-settings/server/methods/saveRoomSettings.js
  packages/rocketchat-e2e/.eslintrc
  packages/rocketchat-e2e/client/helper.js
  packages/rocketchat-e2e/client/rocketchat.e2e.js
  packages/rocketchat-e2e/client/rocketchat.e2e.room.js
  packages/rocketchat-e2e/client/stylesheets/e2e.less
  packages/rocketchat-e2e/package.js
  packages/rocketchat-e2e/server/index.js
  packages/rocketchat-e2e/server/methods/addKeyToChain.js
  packages/rocketchat-e2e/server/methods/fetchKeychain.js
  packages/rocketchat-e2e/server/methods/fetchMyKeys.js
  packages/rocketchat-e2e/server/methods/getUsersOfRoomWithoutKey.js
  packages/rocketchat-e2e/server/methods/setRoomKeyID.js
  packages/rocketchat-e2e/server/methods/updateGroupE2EKey.js
  packages/rocketchat-e2e/server/models/Rooms.js
  packages/rocketchat-e2e/server/models/Subscriptions.js
  packages/rocketchat-e2e/server/models/Users.js
  packages/rocketchat-e2e/server/settings.js
  packages/rocketchat-file-upload/package.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/lib/RoomTypeConfig.js
  packages/rocketchat-lib/lib/roomTypes/direct.js
  packages/rocketchat-lib/lib/roomTypes/private.js
  packages/rocketchat-lib/server/functions/notifications/email.js
  packages/rocketchat-lib/server/functions/notifications/index.js
  packages/rocketchat-lib/server/models/Rooms.js
  packages/rocketchat-message-attachments/package.js
  packages/rocketchat-ui-message/client/message.html
  packages/rocketchat-ui-message/client/message.js
  packages/rocketchat-ui/client/components/header/header.html
  packages/rocketchat-ui/client/components/header/header.js
  packages/rocketchat-ui/client/lib/RoomHistoryManager.js
  packages/rocketchat-ui/client/lib/notification.js
  packages/rocketchat-ui/client/views/app/createChannel.html
  packages/rocketchat-ui/client/views/app/createChannel.js
  packages/rocketchat-ui/package.js
  server/publications/room.js
  server/publications/subscription.js
Labels: stat: board-postponed

#12122 Regression: Modal height
  packages/rocketchat-theme/client/imports/components/modal.css
Labels: subj: ui/ux

#12138 Regression: fix message box autogrow
  packages/rocketchat-ui/client/lib/textarea-autogrow.js
Labels: subj: ui/ux

#12112 [FIX] Allow user with "bulk-register-user" permission to send invitations
  packages/rocketchat-lib/server/methods/sendInvitationEmail.js
  packages/rocketchat-ui-admin/client/users/adminInviteUser.html
  packages/rocketchat-ui-admin/client/users/adminInviteUser.js
Labels: type: bug

#12140 [FIX] Markdown ampersand escape on links
  packages/rocketchat-markdown/parser/original/markdown.js
  packages/rocketchat-markdown/tests/client.tests.js
Labels: subj: ui/ux

#12102 [FIX] Horizontal scroll on user info tab
  packages/rocketchat-theme/client/imports/components/modal.css
  packages/rocketchat-theme/client/imports/components/userInfo.css
Labels: subj: ui/ux

#12038 [FIX] Position of popover component on mobile
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-theme/client/imports/components/popover.css
  packages/rocketchat-theme/client/imports/general/base.css
Labels: subj: ui/ux

#11565 [FIX] Files list missing from popover menu when owner of room
  packages/rocketchat-ui-flextab/client/app.js
  packages/rocketchat-ui-flextab/client/flexTabBar.js
Labels: subj: ui/ux, type: bug

#11679 [NEW] WebDAV Integration (User file provider)
  .meteor/packages
  .meteor/versions
  packages/rocketchat-file-upload/ufs/Webdav/server.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/lib/messageBox.js
  packages/rocketchat-ui-account/client/accountFlex.html
  packages/rocketchat-ui-account/client/accountIntegrations.html
  packages/rocketchat-ui-account/client/accountIntegrations.js
  packages/rocketchat-ui-account/package.js
  packages/rocketchat-ui-master/public/icons.svg
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui/client/views/app/modal.js
  packages/rocketchat-webdav/README.md
  packages/rocketchat-webdav/client/actionButton.js
  packages/rocketchat-webdav/client/addWebdavAccount.html
  packages/rocketchat-webdav/client/addWebdavAccount.js
  packages/rocketchat-webdav/client/collections/WebdavAccounts.js
  packages/rocketchat-webdav/client/selectWebdavAccount.html
  packages/rocketchat-webdav/client/selectWebdavAccount.js
  packages/rocketchat-webdav/client/webdavFilePicker.html
  packages/rocketchat-webdav/client/webdavFilePicker.js
  packages/rocketchat-webdav/package.js
  packages/rocketchat-webdav/server/methods/addWebdavAccount.js
  packages/rocketchat-webdav/server/methods/getFileFromWebdav.js
  packages/rocketchat-webdav/server/methods/getWebdavFileList.js
  packages/rocketchat-webdav/server/methods/removeWebdavAccount.js
  packages/rocketchat-webdav/server/methods/uploadFileToWebdav.js
  packages/rocketchat-webdav/server/models/WebdavAccounts.js
  packages/rocketchat-webdav/server/publications/webdavAccounts.js
  packages/rocketchat-webdav/startup/messageBoxActions.js
  packages/rocketchat-webdav/startup/settings.js
  packages/rocketchat-webdav/startup/subscription.js
Labels: subj: ui/ux

#12184 [NEW] Add Livechat Analytics permission
  packages/rocketchat-livechat/client/views/app/analytics/livechatAnalytics.html
  packages/rocketchat-livechat/client/views/app/analytics/livechatRealTimeMonitoring.html
  packages/rocketchat-livechat/permissions.js
Labels: feat: livechat

#12009 [BREAK][IMPROVE] New emails design
  .meteor/packages
  .meteor/versions
  package-lock.json
  package.json
  packages/rocketchat-channel-settings-mail-messages/server/methods/mailMessages.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-katex/package-lock.json
  packages/rocketchat-lib/package.js
  packages/rocketchat-lib/server/functions/notifications/email.js
  packages/rocketchat-lib/server/functions/saveUser.js
  packages/rocketchat-lib/server/methods/sendInvitationEmail.js
  packages/rocketchat-lib/server/methods/sendSMTPTestEmail.js
  packages/rocketchat-lib/server/startup/email.js
  packages/rocketchat-lib/server/startup/settings.js
  packages/rocketchat-lib/startup/index.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-mail-messages/client/router.js
  packages/rocketchat-mail-messages/client/startup.js
  packages/rocketchat-mail-messages/client/views/mailer.html
  packages/rocketchat-mail-messages/client/views/mailer.js
  packages/rocketchat-mail-messages/client/views/mailerUnsubscribe.html
  packages/rocketchat-mail-messages/client/views/mailerUnsubscribe.js
  packages/rocketchat-mail-messages/lib/Mailer.js
  packages/rocketchat-mail-messages/package.js
  packages/rocketchat-mail-messages/server/functions/sendMail.js
  packages/rocketchat-mail-messages/server/functions/unsubscribe.js
  packages/rocketchat-mail-messages/server/methods/sendMail.js
  packages/rocketchat-mail-messages/server/methods/unsubscribe.js
  packages/rocketchat-mail-messages/server/models/Users.js
  packages/rocketchat-mail-messages/server/startup.js
  packages/rocketchat-mailer/package.js
  packages/rocketchat-mailer/server/api.js
  packages/rocketchat-mailer/server/functions/sendMail.js
  packages/rocketchat-smarsh-connector/server/functions/sendEmail.js
  packages/rocketchat-user-data-download/server/cronProcessDownloads.js
  server/lib/accounts.js
  server/methods/registerUser.js
  server/methods/sendConfirmationEmail.js
  server/methods/sendForgotPasswordEmail.js
  server/methods/setUserActiveStatus.js
  server/startup/migrations/v134.js
Labels: subj: ui/ux
