Repository RocketChat/Rocket.Chat, pull requests merged in 2018-04, with the labels that each got.

#10274 Fix: inputs for rocketchat apps
  packages/rocketchat-apps/client/admin/appManage.html
  packages/rocketchat-apps/client/admin/appManage.js
  packages/rocketchat-apps/server/converters/users.js
Labels: Ready to Merge

#10270 [FIX] Missing Translation Key on Reactions
  packages/rocketchat-channel-settings/client/views/channelSettings.html
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: Ready to Merge

#10444 [NEW] Shows user's real name on autocomplete popup
  packages/rocketchat-ui/client/components/popupList.html
  packages/rocketchat-ui/client/components/popupList.js
Labels: subj: ui/ux

#10439 [NEW] Prevent the browser to autocomplete some setting fields
  packages/rocketchat-lib/server/functions/settings.js
  packages/rocketchat-lib/server/startup/settings.js
  packages/rocketchat-ui-admin/client/admin.html
  packages/rocketchat-ui-admin/client/admin.js
Labels: subj: ui/ux

#10438 [FIX] Button to delete rooms by the owners wasn't appearing
  packages/rocketchat-channel-settings/client/views/channelSettings.html
  packages/rocketchat-channel-settings/client/views/channelSettings.js
  packages/rocketchat-theme/client/imports/forms/button.css
Labels: subj: ui/ux

#10437 [NEW] Add message preview when quoting another message
  packages/rocketchat-lib/client/MessageAction.js
Labels: subj: ui/ux

#10435 Add some missing translations
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-i18n/i18n/sv.i18n.json
  packages/rocketchat-ui-flextab/client/tabs/membersList.html
  packages/rocketchat-ui/client/views/app/directory.html
  packages/rocketchat-ui/client/views/app/home.html
  packages/rocketchat-ui/client/views/app/popover.html
Labels: subj: ui/ux

#10430 [FIX] Room's name was cutting instead of having ellipses on sidebar
  packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
  packages/rocketchat-ui-sidenav/client/sidebarItem.html
Labels: subj: ui/ux

#10423 [FIX] Remove a user from the user's list when creating a new channel removes the wrong user
  packages/rocketchat-channel-settings-mail-messages/client/views/mailMessagesInstructions.js
  packages/rocketchat-theme/client/imports/forms/tags.css
  packages/rocketchat-ui/client/views/app/createChannel.js
Labels: subj: ui/ux

#10409 [FIX] Autocomplete list when inviting a user was partial hidden
  packages/rocketchat-theme/client/imports/components/contextual-bar.css
  packages/rocketchat-theme/client/imports/forms/popup-list.css
Labels: subj: ui/ux

#10396 [NEW] Add internal API to handle room announcements
  package-lock.json
  packages/rocketchat-channel-settings/client/views/channelSettings.js
  packages/rocketchat-channel-settings/server/functions/saveRoomAnnouncement.js
  packages/rocketchat-lib/client/lib/RocketChatAnnouncement.js
  packages/rocketchat-lib/client/lib/index.js
  packages/rocketchat-lib/package.js
  packages/rocketchat-theme/server/colors.less
  packages/rocketchat-ui/client/views/app/room.html
  packages/rocketchat-ui/client/views/app/room.js
Labels: subj: ui/ux

#10394 [FIX] Missing RocketApps input types
  package-lock.json
  packages/rocketchat-apps/client/admin/appManage.html
  packages/rocketchat-apps/client/admin/appManage.js
  packages/rocketchat-theme/client/imports/forms/input.css
  packages/rocketchat-theme/client/imports/forms/select.css
  packages/rocketchat-theme/client/imports/general/apps.css
  packages/rocketchat-ui-master/public/icons.svg
  packages/rocketchat-ui/client/views/app/directory.html
  packages/rocketchat-ui/client/views/app/directory.js
Labels: subj: ui/ux

#10472 [FIX] Messages was grouping wrong some times when server is slow
  packages/rocketchat-ui-message/client/message.js
  packages/rocketchat-ui/client/lib/RoomManager.js
Labels: subj: ui/ux

#10428 [FIX] Wrong positioning of popover when using RTL languages
  packages/rocketchat-emoji/client/lib/EmojiPicker.js
  packages/rocketchat-push-notifications/client/views/pushNotificationsFlexTab.js
  packages/rocketchat-theme/client/imports/components/sidebar/sidebar-header.css
  packages/rocketchat-ui-flextab/client/flexTabBar.js
  packages/rocketchat-ui-flextab/client/tabs/membersList.js
  packages/rocketchat-ui-flextab/client/tabs/userInfo.js
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui-sidenav/client/sidebarHeader.js
  packages/rocketchat-ui-sidenav/client/sidebarItem.js
  packages/rocketchat-ui/client/views/app/popover.js
  packages/rocketchat-ui/client/views/app/room.js
Labels: subj: ui/ux

#10342 [NEW] REST API endpoint `rooms.favorite` to favorite and unfavorite rooms
  packages/rocketchat-api/server/v1/rooms.js
  server/methods/toogleFavorite.js
  tests/end-to-end/api/09-rooms.js
Labels: feat: api, feat: rest

#10399 [FIX] Profile image was not being shown in user's directory search
  packages/rocketchat-ui/client/views/app/directory.html
Labels: subj: ui/ux

#10083 [FIX] "Highlight Words" wasn't working with more than one word
  packages/rocketchat-highlight-words/client/client.js
  packages/rocketchat-ui-account/client/accountPreferences.js
Labels: Ready to Merge

#6673 [FIX] Missing page "not found"
  client/routes/pageNotFound.html
  client/routes/router.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux

#10354 [NEW] REST endpoint to report messages
  packages/rocketchat-api/server/v1/chat.js
  tests/end-to-end/api/05-chat.js
Labels: feat: api, feat: rest

#10371 [NEW] REST endpoint to recover forgotten password
  packages/rocketchat-api/server/v1/users.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest

#10358 [FIX] Button on user info contextual bar scrolling with the content
  packages/rocketchat-theme/client/imports/components/contextual-bar.css
  packages/rocketchat-ui-flextab/client/tabs/userInfo.html
Labels: subj: ui/ux

#10485 [FIX] The 'channel.messages' REST API Endpoint error
  packages/rocketchat-api/server/v1/channels.js
Labels: feat: api, feat: rest, type: bug

#10496 [FIX] Links being embedded inside of blockquotes
  packages/rocketchat-lib/server/functions/sendMessage.js
Labels: subj: ui/ux

#10404 [FIX] Empty panel after changing a user's username
  packages/rocketchat-ui-flextab/client/tabs/userInfo.js
Labels: subj: ui/ux

#10454 [FIX] Wrong column positions in the directory search for users
  packages/rocketchat-ui/client/views/app/directory.html
Labels: subj: ui/ux

#10446 [FIX] Error messages weren't been displayed when email verification fails
  packages/rocketchat-ui/client/lib/accounts.js
Labels: subj: ui/ux

#10299 [FIX] REST API OAuth services endpoint were missing fields and flag to indicate custom services
  packages/rocketchat-api/server/v1/misc.js
  packages/rocketchat-api/server/v1/settings.js
  tests/end-to-end/api/00-miscellaneous.js
  tests/end-to-end/api/08-settings.js
Labels: feat: api, feat: rest

#10403 [FIX] Directory sort and column sizes were wrong
  packages/rocketchat-theme/client/imports/components/modal/directory.css
  packages/rocketchat-theme/client/imports/components/table.css
  packages/rocketchat-ui/client/views/app/directory.html
  packages/rocketchat-ui/client/views/app/directory.js
Labels: subj: ui/ux

#10513 Fix: Remove "secret" from REST endpoint /settings.oauth response
  packages/rocketchat-api/server/v1/settings.js
Labels: feat: api, type: bug

#10482 [FIX] Dropdown elements were using old styles
  packages/rocketchat-theme/client/imports/forms/select.css
  packages/rocketchat-ui-account/client/accountPreferences.html
  packages/rocketchat-ui-admin/client/admin.html
Labels: subj: ui/ux

#10442 [NEW] REST API endpoint `/directory`
  packages/rocketchat-api/server/v1/misc.js
  tests/end-to-end/api/00-miscellaneous.js
Labels: feat: api, feat: rest

#10498 [FIX] Rename method to clean history of messages
  packages/rocketchat-api/server/helpers/deprecationWarning.js
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-api/server/v1/rooms.js
  packages/rocketchat-lib/package.js
  packages/rocketchat-lib/server/methods/cleanChannelHistory.js
  packages/rocketchat-lib/server/methods/cleanRoomHistory.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/09-rooms.js
Labels: feat: api, feat: rest

#10517 [NEW] Option to ignore users on channels
  packages/rocketchat-api/server/v1/chat.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/client/MessageAction.js
  packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
  packages/rocketchat-lib/server/models/Subscriptions.js
  packages/rocketchat-theme/client/imports/components/messages.css
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-ui-flextab/client/tabs/membersList.html
  packages/rocketchat-ui-flextab/client/tabs/membersList.js
  packages/rocketchat-ui-flextab/client/tabs/userActions.js
  packages/rocketchat-ui-master/public/icons.svg
  packages/rocketchat-ui-message/client/message.html
  packages/rocketchat-ui-message/client/message.js
  packages/rocketchat-ui/client/lib/RoomHistoryManager.js
  packages/rocketchat-ui/client/lib/RoomManager.js
  packages/rocketchat-ui/client/views/app/room.js
  server/methods/ignoreUser.js
  server/publications/subscription.js
Labels: subj: ui/ux

#10480 [FIX] Add user object to responses in /*.files Rest endpoints
  packages/rocketchat-api/package.js
  packages/rocketchat-api/server/helpers/insertUserObject.js
  packages/rocketchat-api/server/v1/channels.js
  packages/rocketchat-api/server/v1/groups.js
  packages/rocketchat-api/server/v1/im.js
Labels: feat: api, feat: rest

#9922 [BREAK] Validate incoming message schema
  packages/rocketchat-api/server/v1/chat.js
  packages/rocketchat-lib/server/functions/sendMessage.js
  packages/rocketchat-lib/server/methods/sendMessage.js
  tests/end-to-end/api/05-chat.js
  tests/end-to-end/api/07-incoming-integrations.js
Labels: feat: api, feat: rest, type: bug, type: improvement

#10573 Regression: Attachments and fields incorrectly failing on validation
  packages/rocketchat-lib/server/functions/sendMessage.js
Labels: type: release candidate bug

#10571 Regression: Remove added mentions on quote/reply
  packages/rocketchat-lib/client/MessageAction.js
  packages/rocketchat-ui/client/lib/chatMessages.js
Labels: subj: ui/ux, type: regression, type: release candidate bug

#10553 Regression: Inconsistent response of settings.oauth endpoint
  packages/rocketchat-api/server/v1/settings.js
Labels: feat: api, type: regression, type: release candidate bug

#10550 [FIX] Wordpress oAuth authentication wasn't behaving correctly
  packages/rocketchat-wordpress/common.js
Labels: type: release candidate bug

#10575 Regression: Rocket.Chat App author link opens in same window
  packages/rocketchat-apps/client/admin/appManage.html
Labels: Ready to Merge, type: release candidate bug

#10558 [FIX] Switch buttons were cutting in RTL mode
  packages/rocketchat-theme/client/imports/components/modal/create-channel.css
  packages/rocketchat-theme/client/imports/components/modal/full-modal.css
  packages/rocketchat-theme/client/imports/forms/switch.css
Labels: type: release candidate bug

#10576 [FIX] Integrations with room data not having the usernames filled in
  packages/rocketchat-integrations/server/lib/triggerHandler.js
Labels: type: release candidate bug

#10599 [FIX] Member list search with no results
  packages/rocketchat-ui-flextab/client/tabs/membersList.js
Labels: type: release candidate bug
