Repository RocketChat/Rocket.Chat, pull requests merged in 2018-08, with the labels that each got.

#11625 [FIX] User info APIs not returning customFields correctly
  packages/rocketchat-lib/server/functions/getFullUserData.js
Labels: feat: api, feat: rest, type: regression

#11626 [FIX] Login logo now centered on small screens
  packages/rocketchat-theme/client/imports/general/base_old.css
Labels: subj: ui/ux

#11646 [FIX] Regression in prune by user, and update lastMessage
  packages/rocketchat-lib/server/functions/cleanRoomHistory.js
  packages/rocketchat-lib/server/functions/deleteMessage.js
  packages/rocketchat-lib/server/models/Rooms.js
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-ui-clean-history/client/views/cleanHistory.js
Labels: subj: ui/ux

#11708 [FIX] Broken logo on setup wizard
  packages/rocketchat-setup-wizard/client/setupWizard.html
  packages/rocketchat-theme/client/imports/components/setup-wizard.css
Labels: subj: ui/ux

#11740 [FIX] Message attachments was not respecting sort and lost spacing
  packages/rocketchat-message-attachments/client/messageAttachment.html
  packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
Labels: subj: ui/ux

#11728 [FIX] Fixing timeAgo function on directory
  packages/rocketchat-ui/client/views/app/directory.js
  packages/rocketchat-ui/client/views/app/helpers.js
  packages/rocketchat-ui/client/views/app/tests/helpers.tests.js
Labels: subj: ui/ux

#11730 [FIX] Escape meta data before inject in head tag
  packages/rocketchat-ui-master/server/inject.js
Labels: subj: ui/ux, type: bug

#11674 [IMPROVE] Role tag UI
  packages/rocketchat-theme/client/imports/general/base_old.css
  packages/rocketchat-theme/server/colors.less
  packages/rocketchat-ui-message/client/message.html
Labels: subj: ui/ux

#11687 [FIX] Missing twitter:image and og:image tags
  packages/rocketchat-ui-master/client/main.html
Labels: subj: ui/ux

#11784 [IMPROVE] Warn about push settings that need server restart
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/startup/settings.js
  server/lib/cordova.js
Labels: subj: ui/ux

#11644 [IMPROVE] Escape parameters before send them to email template
  packages/rocketchat-lib/server/functions/saveUser.js
  packages/rocketchat-lib/server/methods/sendInvitationEmail.js
  packages/rocketchat-mailer/server/functions/sendMail.js
  server/lib/accounts.js
  server/methods/sendForgotPasswordEmail.js
Labels: subj: ui/ux

#11775 [FIX] Cannot set property 'input' of undefined
  packages/rocketchat-ui-message/client/messageBox.js
Labels: subj: ui/ux

#8602 [NEW] Make font of unread items bolder for better contrast
  packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
  packages/rocketchat-theme/client/imports/general/variables.css
Labels: subj: ui/ux

#11807 [FIX] Apply Cordova fix in lazy-loaded images sources
  packages/rocketchat-lazy-load/client/lazyloadImage.html
  packages/rocketchat-lazy-load/client/lazyloadImage.js
Labels: subj: ui/ux, type: bug

#11474 [FIX] REST endpoints to update user not respecting some settings
  packages/rocketchat-api/server/v1/users.js
  packages/rocketchat-lib/server/functions/saveUser.js
  server/methods/saveUserProfile.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest, type: bug

#11809 [FIX] Mark some items of directory search table as not clickable
  packages/rocketchat-theme/client/imports/components/table.css
  packages/rocketchat-ui/client/components/table.js
  packages/rocketchat-ui/client/views/app/directory.html
Labels: subj: ui/ux, type: bug

#11473 Rich message text and image buttons
  .meteor/packages
  .meteor/versions
  packages/rocketchat-lib/server/functions/sendMessage.js
  packages/rocketchat-message-action/client/messageAction.html
  packages/rocketchat-message-action/client/messageAction.js
  packages/rocketchat-message-action/client/stylesheets/messageAction.css
  packages/rocketchat-message-action/package.js
  packages/rocketchat-message-attachments/client/messageAttachment.html
  packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
  packages/rocketchat-ui/client/views/app/room.js
Labels: subj: Bots

#11830 [FIX] Livechat open room method
  packages/rocketchat-livechat/server/models/Rooms.js
  packages/rocketchat-livechat/server/startup.js
Labels: type: bug

#11543 [FIX] Fix links in `onTableItemClick` of the directroy page
  packages/rocketchat-ui/client/views/app/directory.js
Labels: subj: ui/ux

#11657 [FIX] Searching by `undefined` via REST when using `query` param
  packages/rocketchat-api/server/helpers/parseJsonQuery.js
Labels: feat: api, feat: rest, type: bug

#11797 [FIX] minor fixes in hungarian i18n
  packages/rocketchat-i18n/i18n/hu.i18n.json
Labels: feat: i18n

#11778 [FIX] re-adding margin to menu icon on header
  packages/rocketchat-theme/client/imports/components/header.css
Labels: subj: ui/ux

#11697 [NEW] REST endpoint to manage server assets
  packages/rocketchat-api/package.js
  packages/rocketchat-api/server/v1/assets.js
  tests/end-to-end/api/14-assets.js
Labels: Contain documentation PR, feat: api, feat: rest

#11821 [FIX] REST `im.members` endpoint not working without sort parameter
  packages/rocketchat-api/server/v1/im.js
  tests/end-to-end/api/04-direct-message.js
Labels: feat: api, feat: rest

#11522 [FIX] Revoked `view-d-room` permission logics
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/client/lib/openRoom.js
  packages/rocketchat-lib/lib/roomTypes/direct.js
  packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
  packages/rocketchat-ui/client/views/404/roomNotFound.html
  packages/rocketchat-ui/client/views/404/roomNotFound.js
  server/methods/createDirectMessage.js
Labels: Contain documentation PR

#11638 [NEW] Personal access tokens for users to create API tokens
  imports/personal-access-tokens/client/index.js
  imports/personal-access-tokens/client/personalAccessTokens.html
  imports/personal-access-tokens/client/personalAccessTokens.js
  imports/personal-access-tokens/server/api/methods/generateToken.js
  imports/personal-access-tokens/server/api/methods/index.js
  imports/personal-access-tokens/server/api/methods/regenerateToken.js
  imports/personal-access-tokens/server/api/methods/removeToken.js
  imports/personal-access-tokens/server/index.js
  imports/personal-access-tokens/server/models/Users.js
  imports/personal-access-tokens/server/models/index.js
  imports/personal-access-tokens/server/publications/index.js
  imports/personal-access-tokens/server/publications/personalAccessTokens.js
  imports/personal-access-tokens/server/settings.js
  imports/startup/client/index.js
  imports/startup/server/index.js
  packages/rocketchat-2fa/client/accountSecurity.html
  packages/rocketchat-api/server/v1/users.js
  packages/rocketchat-apps/client/admin/appInstall.html
  packages/rocketchat-apps/client/admin/appManage.html
  packages/rocketchat-apps/client/admin/apps.html
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-theme/client/imports/components/header.css
  packages/rocketchat-theme/client/imports/components/modal/directory.css
  packages/rocketchat-theme/client/imports/forms/button.css
  packages/rocketchat-theme/client/imports/general/forms.css
  packages/rocketchat-ui-account/client/accountFlex.html
  packages/rocketchat-ui-account/client/accountFlex.js
  packages/rocketchat-ui-account/client/accountPreferences.html
  packages/rocketchat-ui-account/client/accountProfile.html
  packages/rocketchat-ui/client/components/header/header.html
  packages/rocketchat-ui/client/components/header/header.js
  packages/rocketchat-ui/client/views/app/directory.html
  tests/end-to-end/api/01-users.js
Labels: Contain documentation PR, feat: api, feat: rest

#11733 [IMPROVE] Start storing Livechat department within rooms
  packages/rocketchat-livechat/.app/client/lib/hooks.js
  packages/rocketchat-livechat/.app/client/views/livechatWindow.js
  packages/rocketchat-livechat/.app/client/views/register.js
  packages/rocketchat-livechat/.app/imports/client/visitor.js
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/lib/QueueMethods.js
  packages/rocketchat-livechat/server/methods/getInitialData.js
  packages/rocketchat-livechat/server/methods/registerGuest.js
  packages/rocketchat-livechat/server/models/Rooms.js
  packages/rocketchat-livechat/server/models/indexes.js
Labels: documentation: needed, feat: livechat, type: improvement

#11011 [FIX] LiveChat switch department not working
  packages/rocketchat-livechat/.app/client/views/livechatWindow.js
  packages/rocketchat-livechat/.app/client/views/switchDepartment.js
  packages/rocketchat-livechat/.app/i18n/en.i18n.json
  packages/rocketchat-livechat/.app/i18n/pt-BR.i18n.json
  packages/rocketchat-livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/server/methods/getAgentData.js
  packages/rocketchat-livechat/server/methods/setDepartmentForVisitor.js
Labels: feat: livechat, type: bug
