Repository RocketChat/Rocket.Chat, pull requests merged in 2019-08, with the labels that each got.

#15077 Regression: uninstall subscribed app modal
  app/apps/client/admin/helpers.js
  app/ui-utils/client/lib/modal.html
Labels: feat: apps, type: regression

#15076 Regression: Marketplace app pricing plan description
  app/apps/client/admin/helpers.js
Labels: feat: apps, type: regression

#15075 Regression: displaying errors for apps not installed from Marketplace
  app/apps/client/admin/appManage.js
  app/apps/server/communication/rest.js
Labels: feat: apps, type: regression

#15104 [FIX] cachedcollection calling multiple times SYNC
  app/models/server/models/Settings.js
  app/settings/client/lib/settings.js
  app/ui-cached-collection/client/models/CachedCollection.js
  server/publications/settings/index.js
Labels: subj: ui/ux

#15114 [FIX] Direct Message names not visible on Admin panel
  app/lib/lib/roomTypes/direct.js
  app/ui-admin/client/rooms/adminRooms.js
  app/utils/lib/RoomTypeConfig.js
Labels: subj: ui/ux

#15119 [FIX] Custom emoji limit table scroll
  app/emoji-custom/client/admin/adminEmoji.js
Labels: subj: ui/ux

#15135 [IMPROVE] Message tooltips as everyone else
  app/reactions/client/init.js
  app/reactions/client/stylesheets/reaction.css
  app/tooltip/README.md
  app/tooltip/client/index.js
  app/tooltip/client/rocketchat-tooltip.js
  app/tooltip/client/tooltip.css
  app/tooltip/index.js
  app/ui-master/client/main.js
  app/ui/client/components/tooltip.css
  app/ui/client/components/tooltip.html
  app/ui/client/components/tooltip.js
  app/ui/client/index.js
  client/importPackages.js
  client/importsCss.js
  package-lock.json
Labels: subj: ui/ux, type: improvement

#15136 Regression: cachedCollection wrong callback parameters
  app/ui-cached-collection/client/models/CachedCollection.js
Labels: subj: ui/ux

#14507 [FIX] Prevent to create discussion with empty name
  app/discussion/client/views/creationDialog/CreateDiscussion.js
Labels: type: bug

#14956 [FIX] Threads contextual bar button visible even with threads disabled
  app/ui-flextab/client/flexTabBar.js
Labels: subj: ui/ux

#12259 [NEW] Jitsi meet room access via a token
  app/videobridge/client/views/videoFlexTab.js
  app/videobridge/server/index.js
  app/videobridge/server/methods/jitsiGenerateToken.js
  app/videobridge/server/settings.js
  package-lock.json
  package.json
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/ru.i18n.json
  public/packages/rocketchat_videobridge/client/public/external_api.js
Labels: feat: video conferencing, type: improvement

#12174 [NEW] Integrate DEEPL translation service to RC core
  app/autotranslate/client/lib/autotranslate.js
  app/autotranslate/client/stylesheets/autotranslate.css
  app/autotranslate/server/autotranslate.js
  app/autotranslate/server/deeplTranslate.js
  app/autotranslate/server/googleTranslate.js
  app/autotranslate/server/index.js
  app/autotranslate/server/methods/getProviderUiMetadata.js
  app/autotranslate/server/methods/getSupportedLanguages.js
  app/autotranslate/server/methods/translateMessage.js
  app/autotranslate/server/settings.js
  app/models/server/models/Settings.js
  package-lock.json
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: i18n, feat: message

#15154 Update latest Livechat widget version(1.1.3)
  packages/rocketchat-livechat/plugin/build.sh
Labels: feat: livechat

#15157 [FIX] IE11 - callback createTreeWalker doesnt accept acceptNode
  app/emoji/client/emojiParser.js
  app/markdown/lib/parser/original/markdown.js
  app/ui-utils/client/lib/isIE11.js
  imports/client/@rocket.chat/apps-engine
Labels: subj: ui/ux

#15175 [FIX] Messages search scroll
  app/search/client/provider/result.js
  app/search/client/style/style.css
Labels: subj: ui/ux

#15172 [FIX] Attachment download button behavior
  app/file-upload/server/config/AmazonS3.js
  app/file-upload/server/config/GoogleStorage.js
  app/file-upload/server/lib/FileUpload.js
  app/file-upload/ufs/AmazonS3/server.js
  app/file-upload/ufs/GoogleStorage/server.js
  app/message-attachments/client/messageAttachment.html
  package-lock.json
Labels: subj: ui/ux, type: bug

#15177 [FIX] TabBar not loading template titles
  app/ui-flextab/client/flexTabBar.js
Labels: subj: ui/ux, type: bug

#15155 [NEW] Endpoint to fetch livechat rooms with several filters
  app/livechat/imports/server/rest/rooms.js
  app/livechat/server/api.js
  app/livechat/server/api/lib/livechat.js
  tests/data/livechat/rooms.js
  tests/end-to-end/api/livechat/00-rooms.js
Labels: Contain documentation PR, feat: api, feat: livechat, feat: rest

#15053 [NEW] Option to hide the button of Custom OAuth on login screen
  app/lib/server/methods/addOAuthService.js
  app/lib/server/startup/oAuthServicesUpdate.js
  app/ui-login/client/login/services.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux

#15201 [FIX] IE11 modal, menu action and edit user page
  app/theme/client/imports/components/modal.css
  app/theme/client/imports/components/sidebar/sidebar-item.css
  app/theme/client/imports/general/base_old.css
Labels: subj: ui/ux

#15162 [FIX] Typo in 'access-permissions_description' ja translation
  packages/rocketchat-i18n/i18n/ja.i18n.json
Labels: feat: i18n, type: bug

#14885 [NEW] Add autotranslate Rest endpoints
  app/api/server/index.js
  app/api/server/v1/autotranslate.js
  app/autotranslate/server/autotranslate.js
  tests/end-to-end/api/00-autotranslate.js
Labels: Contain documentation PR, feat: api, feat: rest

#15167 [IMPROVE] Add possibility to use commands inside threads through Rest API
  app/api/server/v1/commands.js
  tests/end-to-end/api/16-commands.js
Labels: Contain documentation PR, feat: api, feat: rest

#14682 [FIX] "Discussion" label in Sidebar not hidden, when Discussions are disabled (#14660)
  app/discussion/client/views/DiscussionList.html
  app/discussion/client/views/DiscussionList.js
Labels: subj: ui/ux

#8942 [NEW] #8771 - fine granular settings permissions
  app/authorization/client/startup.js
  app/authorization/client/views/permissions.html
  app/authorization/client/views/permissions.js
  app/authorization/lib.js
  app/authorization/server/methods/addPermissionToRole.js
  app/authorization/server/methods/removeRoleFromPermission.js
  app/authorization/server/publications/permissions/emitter.js
  app/authorization/server/publications/permissions/index.js
  app/authorization/server/startup.js
  app/lib/server/methods/saveSetting.js
  app/lib/server/methods/saveSettings.js
  app/ui-admin/client/SettingsCachedCollection.js
  app/ui-admin/client/admin.html
  app/ui-admin/client/admin.js
  app/ui-admin/client/adminFlex.html
  app/ui-admin/client/adminFlex.js
  app/ui-sidenav/client/sidebarHeader.js
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/publications/settings/index.js
  tests/end-to-end/ui/11-admin.js
  tests/end-to-end/ui/13a-setting-permissions.js
  tests/pageobjects/administration.page.js
Labels: subj: Auth - LDAP

#15094 [FIX] Search message grouping messages
  app/discussion/client/views/DiscussionTabbar.html
  app/mentions-flextab/client/views/mentionsFlexTab.html
  app/message-pin/client/views/pinnedMessages.html
  app/message-star/client/views/starredMessages.html
  app/ui-message/client/message.js
Labels: subj: ui/ux

#15205 [FIX] Forget user session on window close
  app/channel-settings-mail-messages/client/views/mailMessagesInstructions.js
  app/e2e/client/accountEncryption.js
  app/e2e/client/rocketchat.e2e.js
  app/emoji/client/lib/EmojiPicker.js
  app/oauth2-server-config/client/oauth/oauth2-client.js
  app/setup-wizard/client/final.js
  app/setup-wizard/client/setupWizard.js
  app/ui-account/client/accountPreferences.js
  app/ui-login/client/login/footer.js
  app/ui-master/server/inject.js
  app/ui-utils/client/config.js
  app/ui-utils/client/lib/menu.js
  app/ui-utils/lib/Message.js
  app/ui/client/lib/chatMessages.js
  app/utils/client/lib/RestApiClient.js
  app/utils/lib/tapi18n.js
  client/startup/i18n.js
Labels: subj: ui/ux

#13864 [NEW] Rest API Endpoint to get pinned messages from a room
  app/api/server/v1/chat.js
  tests/data/chat.helper.js
  tests/end-to-end/api/05-chat.js
Labels: feat: api, feat: rest

#15174 [FIX] Mark room as read logic
  app/logger/client/views/viewLogs.js
  app/theme/client/imports/general/base.css
  app/ui-utils/client/lib/RoomHistoryManager.js
  app/ui-utils/client/lib/openRoom.js
  app/ui-utils/client/lib/readMessages.js
  app/ui/client/lib/chatMessages.js
  app/ui/client/views/app/room.js
  client/startup/unread.js
Labels: subj: ui/ux

#15217 Regression: fix typo permisson to permission
  app/authorization/client/views/permissions.js
Labels: subj: ui/ux

#15003 [IMPROVE] Refactoring the queuing and routing processes of new livechats
  app/livechat/client/index.js
  app/livechat/client/views/app/customTemplates/register.js
  app/livechat/client/views/app/livechatDepartmentForm.html
  app/livechat/client/views/app/livechatDepartmentForm.js
  app/livechat/client/views/app/livechatReadOnly.html
  app/livechat/client/views/app/livechatReadOnly.js
  app/livechat/client/views/app/tabbar/visitorInfo.html
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/client/views/app/triggers/livechatTriggerAction.html
  app/livechat/client/views/app/triggers/livechatTriggerAction.js
  app/livechat/client/views/sideNav/livechat.html
  app/livechat/client/views/sideNav/livechat.js
  app/livechat/imports/server/rest/inquiries.js
  app/livechat/lib/LivechatInquiry.js
  app/livechat/lib/LivechatRoomType.js
  app/livechat/server/api/lib/livechat.js
  app/livechat/server/api/v1/config.js
  app/livechat/server/api/v1/room.js
  app/livechat/server/config.js
  app/livechat/server/index.js
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/QueueManager.js
  app/livechat/server/lib/QueueMethods.js
  app/livechat/server/lib/RoutingManager.js
  app/livechat/server/lib/routing/External.js
  app/livechat/server/lib/routing/GuestPool.js
  app/livechat/server/lib/routing/LeastAmount.js
  app/livechat/server/methods/changeLivechatStatus.js
  app/livechat/server/methods/getRoutingConfig.js
  app/livechat/server/methods/startVideoCall.js
  app/livechat/server/methods/takeInquiry.js
  app/livechat/server/publications/livechatInquiries.js
  app/livechat/server/startup.js
  app/models/server/models/LivechatDepartment.js
  app/models/server/models/Rooms.js
  app/models/server/models/Users.js
  app/models/server/raw/Rooms.js
  app/models/server/raw/Users.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v153.js
Labels: feat: livechat

#14278 [NEW] LDAP User Groups, Roles, and Channel Synchronization
  app/ldap/server/loginHandler.js
  app/ldap/server/settings.js
  app/ldap/server/sync.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: Auth - LDAP

#14275 [NEW] Options for SAML auth for individual organizations needs
  app/meteor-accounts-saml/server/saml_rocketchat.js
  app/meteor-accounts-saml/server/saml_server.js
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: oauth / sso

#15231 Regression: Fix assets extension detection
  app/assets/server/assets.js
Labels: type: release candidate bug

#15234 Federation improvements
  app/federation/client/admin/dashboard.js
  app/federation/client/admin/visualizer.js
  app/federation/server/_client/callbacks/afterAddedToRoom.js
  app/federation/server/_client/callbacks/afterCreateDirectRoom.js
  app/federation/server/_client/callbacks/afterCreateRoom.js
  app/federation/server/_client/callbacks/afterDeleteMessage.js
  app/federation/server/_client/callbacks/afterMuteUser.js
  app/federation/server/_client/callbacks/afterRemoveFromRoom.js
  app/federation/server/_client/callbacks/afterSaveMessage.js
  app/federation/server/_client/callbacks/afterSetReaction.js
  app/federation/server/_client/callbacks/afterUnmuteUser.js
  app/federation/server/_client/callbacks/afterUnsetReaction.js
  app/federation/server/_client/callbacks/beforeDeleteRoom.js
  app/federation/server/_client/callbacks/helpers/federatedResources.js
  app/federation/server/_client/client.js
  app/federation/server/_server/index.js
  app/federation/server/_server/server.js
  app/federation/server/errors.js
  app/federation/server/federation.js
  app/federation/server/methods/loadContextEvents.js
  app/federation/server/normalizers/helpers/federatedResources.js
  app/federation/server/normalizers/message.js
  app/federation/server/normalizers/room.js
  app/federation/server/normalizers/subscription.js
  app/federation/server/normalizers/user.js
  app/logger/server/server.js
  server/methods/browseChannels.js
Labels: feat: federation, type: release candidate bug
