Repository RocketChat/Rocket.Chat, pull requests merged in 2019-05, with the labels that each got.

#14351 Improve German translations
  app/discussion/client/views/DiscussionList.html
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
Labels: feat: i18n, type: improvement

#14391 Fix: subscription-changed updating all messages
  app/ui-utils/client/lib/RoomManager.js
Labels: subj: ui/ux

#14390 Fix: Message body was not being updated when user disabled nrr message
  app/ui-message/client/message.js
Labels: subj: ui/ux

#14389 [NEW] Allow change Discussion's properties
  app/channel-settings/client/views/channelSettings.js
  app/channel-settings/server/functions/saveRoomName.js
  app/discussion/server/hooks/propagateDiscussionMetadata.js
Labels: subj: ui/ux

#14039 fix discussions: remove restriction for editing room info, server side
  app/channel-settings/server/methods/saveRoomSettings.js
Labels: feat: threads / discussions, type: improvement

#14388 [FIX] Pressing Enter in User Search field at channel causes reload
  app/ui-flextab/client/tabs/membersList.html
  app/ui-flextab/client/tabs/membersList.js
Labels: subj: ui/ux

#14400 [FIX] Users actions in administration were returning error
  app/ui-flextab/client/tabs/userActions.js
  app/ui-flextab/client/tabs/userInfo.js
Labels: subj: ui/ux, type: bug

#14402 [FIX] Error 400 on send a reply to an old thread
  app/threads/client/flextab/thread.js
  app/threads/client/flextab/threads.js
  app/ui-message/client/message.js
  app/ui-message/client/messageBox/messageBox.js
  app/ui-message/client/messageBox/messageBoxNotSubscribed.js
  app/ui-utils/client/lib/RoomHistoryManager.js
  app/ui-utils/client/lib/RoomManager.js
  app/ui/client/views/app/room.js
Labels: feat: threads / discussions, subj: ui/ux, type: bug

#14432 [FIX] Escape unrecognized slash command message
  app/ui/client/lib/chatMessages.js
Labels: subj: security, type: bug

#14386 Add missing german translations
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
Labels: feat: i18n

#14443 [FIX] Channel Leader Bar is in the way of Thread Header
  app/theme/client/imports/components/contextual-bar.css
  app/theme/client/imports/general/base_old.css
Labels: subj: ui/ux

#14461 [FIX] You must join to view messages in this channel
  app/ui/client/views/app/room.js
Labels: subj: ui/ux

#14464 [FIX] Allow data URLs in isURL/getURL helpers
  app/utils/lib/isURL.js
Labels: subj: ui/ux, type: bug

#14465 [FIX] Ignored messages
  app/theme/client/imports/components/messages.css
  app/threads/client/flextab/thread.html
  app/threads/client/flextab/thread.js
  app/threads/client/flextab/threads.html
  app/ui-message/client/message.js
Labels: feat: message, subj: ui/ux, type: bug

#14460 [IMPROVE] jump to selected message on open thread
  app/threads/client/flextab/thread.html
  app/threads/client/flextab/thread.js
  app/threads/client/flextab/threads.html
  app/threads/client/flextab/threads.js
  app/ui/client/views/app/room.js
Labels: subj: ui/ux

#14257 [IMPROVEMENT] Don't group messages with different alias
  app/ui-message/client/message.html
  app/ui-message/client/message.js
Labels: subj: ui/ux, type: improvement

#14496 [FIX] RocketChat client sending out video call requests unnecessarily
  app/videobridge/client/views/videoFlexTab.js
Labels: subj: ui/ux

#13615 [NEW] Add pause and reset button when adding custom sound
  app/custom-sounds/client/admin/adminSounds.html
  app/custom-sounds/client/admin/adminSounds.js
Labels: subj: ui/ux, type: improvement

#14381 [NEW] Custom user name field from Custom OAuth
  app/custom-oauth/server/custom_oauth_server.js
  app/lib/server/methods/addOAuthService.js
  app/lib/server/methods/removeOAuthService.js
  app/lib/server/startup/oAuthServicesUpdate.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: oauth / sso

#13682 Allow removing description, topic and annoucement of rooms(set as empty string)
  app/api/server/v1/channels.js
  app/api/server/v1/groups.js
  app/api/server/v1/im.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/03-groups.js
  tests/end-to-end/api/04-direct-message.js
Labels: feat: api, feat: rest

#14242 [FIX] Verify if the user is requesting your own information in users.info
  app/api/server/v1/users.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest

#14509 [FIX] Remove Livechat guest data was removing more rooms than expected
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/QueueMethods.js
  app/livechat/server/methods/takeInquiry.js
  app/models/server/models/LivechatVisitors.js
Labels: feat: livechat, type: bug

#14022 [IMPROVE] Livechat CRM secret token optional
  app/livechat/server/config.js
  app/livechat/server/hooks/sendToCRM.js
  app/livechat/server/lib/Livechat.js
  server/startup/migrations/index.js
  server/startup/migrations/v145.js
Labels: feat: livechat

#12971 [IMPROVE] Don't show unread count badge in burger menu if it is from the opened room
  app/ui/client/views/app/burger.js
  client/startup/unread.js
Labels: subj: ui/ux, type: improvement

#13328 [FIX] Channel settings form to textarea for Topic and Description
  app/channel-settings/client/stylesheets/channel-settings.css
  app/channel-settings/client/views/channelSettings.html
  app/ui/client/components/header/headerRoom.js
Labels: subj: ui/ux, type: improvement

#14263 [FIX] Fix after verify email, verify if it needs changes in user roles
  server/methods/afterVerifyEmail.js
Labels: type: bug

#13919 [FIX] Unread property of the room's lastMessage object was being wrong some times
  app/models/server/models/Rooms.js
  imports/message-read-receipt/server/lib/ReadReceipt.js
Labels: feat: message, type: bug

#14369 [FIX] Edit Message when down arrow is pressed.
  app/ui/client/lib/chatMessages.js
Labels: subj: ui/ux, type: bug

#14505 [FIX] Duplicated link to jump to message
  app/message-star/client/actionButton.js
Labels: type: bug

#14542 [FIX] Channel names on Directory got cut on small screens
  app/ui/client/views/app/directory.css
Labels: subj: ui/ux

#14567 [FIX] Broken layout when sidebar is open on IE/Edge
  app/theme/client/imports/components/header.css
  app/theme/client/imports/components/main-content.css
  app/theme/client/imports/components/sidebar/sidebar.css
Labels: subj: ui/ux

#14565 [REGRESSION] Fix Slack bridge channel owner on channel creation
  app/slackbridge/server/RocketAdapter.js
Labels: type: regression

#14595 Federation i18n message changes
  app/federation/server/federation-settings.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: federation

#14568 [FIX] Send replyTo for livechat offline messages
  app/mailer/server/api.js
Labels: type: improvement

#14580 [FIX] E2E messages not decrypting in message threads
  app/e2e/client/rocketchat.e2e.js
  app/theme/client/imports/components/messages.css
  app/threads/client/flextab/thread.js
  app/threads/client/flextab/threads.js
  app/ui-message/client/message.js
  app/ui-utils/client/lib/RoomHistoryManager.js
  app/ui-utils/client/lib/RoomManager.js
  app/ui-utils/client/lib/openRoom.js
Labels: subj: ui/ux

#14623 [FIX] Inject code at the end of <head> tag
  app/chatpal-search/server/asset/config.js
  app/theme/server/server.js
  app/ui-master/server/index.js
  app/ui-master/server/inject.js
  package-lock.json
Labels: subj: ui/ux, type: bug

#14625 [FIX] Role name spacing on Permissions page
  app/authorization/client/stylesheets/permissions.css
Labels: subj: ui/ux, type: bug

#14651 [FIX] "Blank page" on safari 10.x
  app/theme/client/imports/general/base.css
  app/theme/client/imports/general/base_old.css
Labels: subj: ui/ux

#14646 Improvement: Permissions table
  app/authorization/client/stylesheets/permissions.css
  app/authorization/client/views/permissions.html
  app/ui-message/client/messageBox/messageBox.js
  app/ui/client/lib/chatMessages.js
Labels: subj: ui/ux

#14668 [FIX] Load messages after disconnect and message box scroll missing
  app/ui-message/client/messageBox/messageBoxAutogrow.js
  app/ui-utils/client/lib/RoomManager.js
Labels: subj: ui/ux

#14674 Removing unnecesary federation configs
  server/startup/migrations/index.js
  server/startup/migrations/v147.js
Labels: feat: federation

#14624 [IMPROVE] Use configurable colors on sidebar items
  app/theme/client/imports/general/variables.css
  private/client/imports/general/variables.css
Labels: subj: ui/ux, type: improvement

#14589 [IMPROVE] Add an optional rocketchat-protocol DNS entry for Federation
  app/federation/server/PeerDNS.js
Labels: feat: federation

#14569 [FIX] Wrong filter field when filtering current Livechats
  app/livechat/server/publications/livechatRooms.js
Labels: type: bug

#14690 [NEW] Configuration to limit amount of livechat inquiries displayed
  app/livechat/server/config.js
  app/livechat/server/publications/livechatInquiries.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: livechat, type: improvement
