Repository RocketChat/Rocket.Chat, pull requests merged in 2019-02, with the labels that each got.

#13308 [NEW] REST endpoint to forward livechat rooms
  packages/rocketchat-livechat/server/api/v1/room.js
  packages/rocketchat-livechat/server/methods/transfer.js
Labels: feat: livechat, type: improvement

#11673 [IMPROVE] Line height on static content pages
  packages/rocketchat_theme/client/imports/general/base_old.css
Labels: subj: ui/ux, type: improvement

#11558 [FIX] Fixed text for "bulk-register-user"
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux

#13369 [FIX] Notify private settings changes even on public settings changed
  packages/rocketchat-lib/server/publications/settings.js
  packages/rocketchat-models/server/models/Settings.js
Labels: type: bug

#13393 [IMPROVE] Admin ui
  packages/rocketchat-authorization/client/route.js
  packages/rocketchat-authorization/client/stylesheets/permissions.css
  packages/rocketchat-authorization/client/views/permissions.html
  packages/rocketchat-custom-sounds/client/admin/adminSounds.html
  packages/rocketchat-custom-sounds/client/admin/adminSounds.js
  packages/rocketchat-emoji-custom/client/admin/adminEmoji.html
  packages/rocketchat-emoji-custom/client/admin/adminEmoji.js
  packages/rocketchat-importer/client/admin/adminImport.html
  packages/rocketchat-importer/client/admin/adminImportHistory.html
  packages/rocketchat-importer/client/admin/adminImportPrepare.html
  packages/rocketchat-integrations/client/stylesheets/integrations.css
  packages/rocketchat-oauth2-server-config/client/admin/route.js
  packages/rocketchat-oauth2-server-config/client/admin/views/oauthApps.html
  packages/rocketchat-ui-admin/client/rooms/adminRooms.html
  packages/rocketchat-ui-admin/client/rooms/adminRooms.js
  packages/rocketchat-ui-admin/client/users/adminUsers.html
  packages/rocketchat-ui-admin/client/users/adminUsers.js
  packages/rocketchat-ui-admin/server/publications/adminRooms.js
  packages/rocketchat-ui/client/components/header/header.html
  packages/rocketchat-ui/client/components/header/header.js
  packages/rocketchat-ui/client/components/header/headerRoom.html
  packages/rocketchat-ui/client/components/header/headerRoom.js
  packages/rocketchat-ui/client/index.js
  packages/rocketchat-ui/client/views/app/room.html
  packages/rocketchat-ui/client/views/app/room.js
  packages/rocketchat_theme/client/imports/components/contextual-bar.css
  packages/rocketchat_theme/client/imports/components/header.css
  packages/rocketchat_theme/client/imports/components/modal/directory.css
  packages/rocketchat_theme/client/imports/components/setup-wizard.css
  packages/rocketchat_theme/client/imports/components/tabs.css
  packages/rocketchat_theme/client/imports/general/base.css
  packages/rocketchat_theme/client/imports/general/base_old.css
  packages/rocketchat_theme/client/imports/general/variables.css
  packages/rocketchat_theme/server/colors.less
  tests/pageobjects/administration.page.js
Labels: subj: ui/ux

#13406 Removed old templates
  packages/rocketchat-ui-sidenav/client/createCombinedFlex.html
  packages/rocketchat-ui-sidenav/client/createCombinedFlex.js
  packages/rocketchat-ui-sidenav/client/index.js
  packages/rocketchat-ui-sidenav/client/listChannelsFlex.html
  packages/rocketchat-ui-sidenav/client/listChannelsFlex.js
  packages/rocketchat-ui-sidenav/client/listCombinedFlex.html
  packages/rocketchat-ui-sidenav/client/listCombinedFlex.js
  packages/rocketchat-ui-sidenav/client/listPrivateGroupsFlex.html
  packages/rocketchat-ui-sidenav/client/listPrivateGroupsFlex.js
Labels: subj: ui/ux

#13407 [FIX] Misaligned upload progress bar "cancel" button
  packages/rocketchat_theme/client/imports/general/base_old.css
Labels: subj: ui/ux, type: bug

#13410 Regression: Template error
  package-lock.json
  package.json
  packages/rocketchat-ui/client/components/header/headerRoom.js
  packages/rocketchat-ui/client/views/app/room.js
  packages/rocketchat_theme/client/imports/components/table.css
Labels: subj: ui/ux, type: bug

#13244 [FIX] Update Russian localization
  packages/rocketchat-i18n/i18n/ru.i18n.json
Labels: feat: i18n, type: bug

#11698 [IMPROVE] KaTeX and Autolinker message rendering
  packages/rocketchat-autolinker/client/client.js
  packages/rocketchat-katex/client/index.js
  packages/rocketchat-katex/lib/katex.js
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui-utils/client/lib/renderMessageBody.js
Labels: feat: message, subj: ui/ux, type: bug

#13444 [FIX] Small improvements on message box
  package-lock.json
  packages/rocketchat-ui-message/client/index.js
  packages/rocketchat-ui-message/client/messageBox.html
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui-message/client/messageBoxAudioMessage.html
  packages/rocketchat-ui-message/client/messageBoxAudioMessage.js
  packages/rocketchat-ui-message/client/messageBoxNotSubscribed.html
  packages/rocketchat-ui-message/client/messageBoxNotSubscribed.js
  packages/rocketchat-ui-message/client/messageBoxReplyPreview.html
  packages/rocketchat-ui-message/client/messageBoxReplyPreview.js
  packages/rocketchat-ui-message/client/messageBoxTyping.html
  packages/rocketchat-ui-message/client/messageBoxTyping.js
  packages/rocketchat-ui-message/client/startup/index.js
  packages/rocketchat-ui-message/client/startup/messageBoxActions.js
  packages/rocketchat-ui-message/client/startup/restoreText.js
  packages/rocketchat-ui/client/lib/chatMessages.js
  packages/rocketchat-ui/client/lib/textarea-autogrow.js
  packages/rocketchat_theme/client/imports/components/message-box.css
  packages/rocketchat_theme/client/imports/general/base_old.css
  packages/rocketchat_theme/client/imports/general/rtl.css
Labels: subj: ui/ux, type: improvement

#13408 [FIX] Properly escape custom emoji names for pattern matching
  package-lock.json
  packages/rocketchat-emoji-custom/client/lib/emojiCustom.js
Labels: subj: ui/ux, type: bug

#13457 [FIX] "Test Desktop Notifications" not triggering a notification
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-ui-account/client/accountPreferences.html
  packages/rocketchat-ui-account/client/accountPreferences.js
  packages/rocketchat-ui/client/lib/notification.js
Labels: feat: notification, subj: ui/ux, type: bug

#13360 [FIX] Invalid condition on getting next livechat agent over REST API endpoint
  packages/rocketchat-livechat/server/api/v1/agent.js
Labels: feat: livechat, type: bug

#13447 [FIX] Emoji detection at line breaks
  packages/rocketchat-emoji/client/emojiParser.js
Labels: subj: ui/ux, type: bug

#13496 Regression: Message box geolocation was throwing error
  packages/rocketchat-ui-message/client/startup/messageBoxActions.js
Labels: subj: ui/ux, type: regression

#13443 [NEW] users.setActiveStatus endpoint in rest api
  packages/rocketchat-api/server/v1/users.js
  tests/end-to-end/api/01-users.js
Labels: Contain documentation PR, feat: api, feat: rest

#13315 [NEW] Add missing remove add leader channel
  packages/rocketchat-api/server/v1/channels.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/03-groups.js
Labels: feat: api, feat: rest

#13497 [FIX] Fix autolinker that was not parsing urls correctly
  packages/rocketchat-autolinker/client/client.js
Labels: subj: ui/ux, type: regression

#13516 Regression: Fix wrong imports in rc-models
  packages/rocketchat-models/server/models/LivechatDepartment.js
  packages/rocketchat-models/server/models/LivechatDepartmentAgents.js
  packages/rocketchat-models/server/models/LivechatVisitors.js
Labels: type: regression

#13491 [IMPROVE] Add department field on find guest method
  packages/rocketchat-livechat/server/api/lib/livechat.js
Labels: type: improvement

#13485 [FIX] Get next Livechat agent endpoint
  packages/rocketchat-livechat/server/api/v1/agent.js
Labels: feat: livechat

#13520 Convert rc-nrr and slashcommands open to main module structure
  packages/rocketchat-nrr/client/index.js
  packages/rocketchat-nrr/client/nrr.js
  packages/rocketchat-nrr/package.js
  packages/rocketchat-slashcommands-open/package.js
Labels: type: improvement

#13515 [FIX]Fix wrong this scope in Notifications
  packages/rocketchat-notifications/server/lib/Notifications.js
Labels: type: regression

#13529 Regression: Add debounce on admin users search to avoid blocking by DDP Rate Limiter
  packages/rocketchat-ui-admin/client/users/adminUsers.js
Labels: type: bug

#13564 [FIX] Handle showing/hiding input in messageBox
  package-lock.json
  packages/rocketchat-ui-message/client/messageBox.js
  packages/rocketchat-ui-message/client/messageBoxNotSubscribed.js
Labels: subj: ui/ux, type: bug

#13553 [FIX] Error when recording data into the connection object
  packages/rocketchat-statistics/server/lib/SAUMonitor.js
Labels: type: bug

#13584 [IMPROVE] Remove dangling side-nav styles
  packages/rocketchat_theme/client/imports/general/base_old.css
  packages/rocketchat_theme/client/imports/general/rtl.css
  packages/rocketchat_theme/server/colors.less
Labels: subj: ui/ux, type: improvement
