Repository RocketChat/Rocket.Chat, pull requests merged in 2019-10, with the labels that each got.

#15478 [IMPROVE] Replace `livechat:departments` publication by REST Calls
  app/livechat/client/views/app/livechatCurrentChats.js
  app/livechat/client/views/app/livechatDepartmentForm.js
  app/livechat/client/views/app/livechatDepartments.js
  app/livechat/client/views/app/livechatQueue.js
  app/livechat/client/views/app/tabbar/visitorForward.js
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/imports/server/rest/departments.js
  app/livechat/server/api/lib/departments.js
  app/models/server/raw/BaseRaw.js
  app/models/server/raw/LivechatDepartment.js
  app/models/server/raw/LivechatDepartmentAgents.js
  app/models/server/raw/index.js
  tests/data/livechat/department.js
  tests/end-to-end/api/livechat/01-department.js
Labels: Contain documentation PR, feat: api, feat: rest

#15482 [IMPROVE] Detach React components from Meteor API
  .storybook/.babelrc
  .storybook/addons.js
  .storybook/config.js
  .storybook/helpers.js
  .storybook/webpack.config.js
  app/theme/client/imports/general/base_old.css
  client/components/admin/info/BuildEnvironmentSection.js
  client/components/admin/info/CommitSection.js
  client/components/admin/info/InformationPage.js
  client/components/admin/info/InstancesSection.js
  client/components/admin/info/RocketChatSection.js
  client/components/admin/info/RuntimeEnvironmentSection.js
  client/components/admin/info/UsageSection.js
  client/components/admin/info/formatters.js
  client/components/basic/Button.stories.js
  client/components/basic/ErrorAlert.stories.js
  client/components/basic/Input.stories.js
  client/components/basic/Link.stories.js
  client/components/connectionStatus/ConnectionStatusAlert.js
  client/components/connectionStatus/ConnectionStatusAlert.stories.js
  client/components/contexts/ConnectionStatusContext.js
  client/components/contexts/RouterContext.js
  client/components/contexts/TranslationContext.js
  client/components/header/BurgerMenuButton.js
  client/components/header/Header.js
  client/components/pageNotFound/PageNotFound.js
  client/components/providers/ConnectionStatusProvider.js
  client/components/providers/ConnectionStatusProvider.mock.js
  client/components/providers/MeteorProvider.js
  client/components/providers/RouterProvider.js
  client/components/providers/TranslationProvider.js
  client/components/providers/TranslationProvider.mock.js
  client/components/setupWizard/Epilogue.js
  client/components/setupWizard/Pager.js
  client/components/setupWizard/SideBar.js
  client/components/setupWizard/StateChecker.js
  client/components/setupWizard/StepHeader.css
  client/components/setupWizard/StepHeader.js
  client/components/setupWizard/Steps.js
  client/components/setupWizard/StepsState.js
  client/components/setupWizard/steps/AdminUserInformationStep.js
  client/components/setupWizard/steps/RegisterServerStep.js
  client/components/setupWizard/steps/SettingsBasedStep.js
  client/hooks/useEmbeddedLayout.js
  client/hooks/useFormatters.js
  client/hooks/useTranslation.js
  client/routes.js
  package-lock.json
  package.json
  public/images/onepassword-button.png
  public/images/setup-wizard-intro.png
Labels: subj: ui/ux, type: improvement

#15460 [FIX] Promise await for sendMessage in livechat/messages endpoint
  app/livechat/server/api/v1/message.js
Labels: feat: livechat

#15444 [FIX] Reset password was allowing empty values leading to an impossibility to login
  app/ui-login/client/reset-password/resetPassword.html
  app/ui-login/client/reset-password/resetPassword.js
Labels: subj: ui/ux

#15541 [FIX] Adding "Promise.await" in "livechat/message" endpoint
  app/livechat/server/api/v1/message.js
Labels: feat: livechat

#15540 [IMPROVE] Replace mentionedMessages publication to REST
  app/api/server/lib/messages.js
  app/api/server/v1/chat.js
  app/file-upload/server/lib/FileUpload.js
  app/lib/server/functions/deleteRoom.js
  app/lib/server/functions/deleteUser.js
  app/livechat/server/lib/Livechat.js
  app/mentions-flextab/client/lib/MentionedMessage.js
  app/mentions-flextab/client/views/mentionsFlexTab.js
  app/mentions-flextab/server/publications/mentionedMessages.js
  app/models/server/models/Messages.js
  app/models/server/raw/Messages.js
  app/models/server/raw/index.js
  server/startup/migrations/v131.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, feat: api, type: improvement

#15544 [IMPROVE] Replace pinned messages subscription
  app/mentions-flextab/server/publications/mentionedMessages.js
  app/message-pin/client/lib/PinnedMessage.js
  app/message-pin/client/views/pinnedMessages.js
  app/message-pin/server/publications/pinnedMessages.js
Labels: type: improvement

#15532 [IMPROVE] Replace some livechat:rooms subscriptions
  app/livechat/client/views/app/tabbar/visitorEdit.js
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/methods/closeRoom.js
  app/livechat/server/methods/returnAsInquiry.js
  app/livechat/server/methods/transfer.js
  app/models/server/raw/LivechatRooms.js
  app/models/server/raw/index.js
Labels: feat: api, type: improvement

#15548 [IMPROVE] Replace starred messages subscription
  app/api/server/lib/messages.js
  app/api/server/v1/chat.js
  app/message-star/client/lib/StarredMessage.js
  app/message-star/client/views/starredMessages.js
  app/message-star/server/publications/starredMessages.js
  app/models/server/raw/Messages.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, feat: api, type: improvement

#15550 [IMPROVE] Replace roomFilesWithSearchText subscription
  app/ui-flextab/client/tabs/uploadedFilesList.js
  server/publications/roomFilesWithSearchText.js
Labels: type: improvement

#15556 [FIX] Add a header for the createAt column in the Directory
  app/ui/client/views/app/directory.html
Labels: subj: ui/ux

#15515 [FIX] Japanese translation for run import
  packages/rocketchat-i18n/i18n/ja.i18n.json
Labels: hacktoberfest

#15507 [IMPROVE] Replace `livechat:triggers` publication by REST calls
  app/livechat/client/views/app/livechatTriggers.js
  app/livechat/client/views/app/livechatTriggersForm.js
  app/livechat/imports/server/rest/triggers.js
  app/livechat/server/api.js
  app/livechat/server/api/lib/triggers.js
  app/livechat/server/publications/livechatTriggers.js
  app/models/server/raw/LivechatTrigger.js
  app/models/server/raw/index.js
  tests/end-to-end/api/livechat/triggers.js
Labels: Contain documentation PR, feat: api, type: improvement

#15520 [FIX] Registration/login page now mobile friendly (#15422)
  app/theme/client/imports/general/base_old.css
  package-lock.json
Labels: subj: ui/ux

#15564 [FIX] Self-XSS in validation functionality
  app/ui-admin/client/rooms/adminRoomInfo.js
Labels: subj: ui/ux

#15534 [NEW] Import DMs from CSV files
  app/importer-csv/server/importer.js
  app/importer/server/classes/ImporterSelectionChannel.js
Labels: Contain documentation PR

#15592 [CHORE] Update latest Livechat widget version to 1.2.2
  package.json
Labels: feat: livechat

#15596 [CHORE] Update latest Livechat widget version to 1.2.4
  package.json
Labels: feat: livechat

#15594 [FIX] Incorrect display of the button "Invite users"
  app/theme/client/imports/forms/button.css
Labels: subj: ui/ux

#15599 Regression: Fix broken message formatting box
  app/ui-message/client/messageBox/messageBoxFormatting.js
Labels: subj: ui/ux

#15600 [CHORE] Update livechat widget version to 1.2.5
  package.json
Labels: feat: livechat

#15593 [IMPROVE] Disable edit visitor's phone number in SMS conversations
  app/livechat/client/views/app/tabbar/visitorEdit.html
  app/livechat/client/views/app/tabbar/visitorEdit.js
  app/livechat/server/methods/saveInfo.js
Labels: feat: livechat, type: improvement

#15602 [FIX] Deny editing visitor's phone number in SMS conversations
  app/livechat/client/views/app/tabbar/visitorEdit.js
Labels: feat: livechat

#15598 [FIX] dynamic import
  app/utils/client/lib/baseuri.js
  client/routes.js
Labels: subj: ui/ux

#13956 [NEW] close emoji box using Keyboard Escape key
  app/emoji/client/emojiPicker.html
  app/emoji/client/emojiPicker.js
  app/emoji/client/lib/EmojiPicker.js
  app/ui-message/client/messageBox/messageBox.js
Labels: subj: ui/ux, type: improvement

#15603 [FIX] Read Recepts was not working
  server/methods/readMessages.js
  tests/end-to-end/api/10-subscriptions.js
Labels: type: bug

#14635 [FIX] Link in Announcement popup
  app/ui/client/views/app/room.html
  app/ui/client/views/app/room.js
Labels: subj: ui/ux, type: bug

#15289 [NEW]Added file type filter to RoomFiles
  app/models/server/models/Uploads.js
  app/theme/client/imports/forms/select.css
  app/ui-flextab/client/tabs/uploadedFilesList.html
  app/ui-flextab/client/tabs/uploadedFilesList.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/lib/roomFiles.js
  server/startup/migrations/index.js
  server/startup/migrations/v163.js
Labels: subj: ui/ux

#15317 [NEW] Assign new Livechat conversations to bot agents first
  app/livechat/server/config.js
  app/livechat/server/hooks/beforeGetNextAgent.js
  app/livechat/server/index.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/QueueManager.js
  app/livechat/server/lib/RoutingManager.js
  app/models/server/models/LivechatDepartmentAgents.js
  app/models/server/models/Users.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: livechat

#14698 [NEW] Add option to enable X-Frame-options header to avoid loading inside any Iframe
  app/cors/server/cors.js
  app/lib/server/startup/settings.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v164.js
Labels: subj: security

#14203 [NEW] Import SAML language and auto join SAML channels
  app/meteor-accounts-saml/server/saml_server.js
Labels: feat: oauth / sso

#15451 [NEW] Check if agent can receive new livechat conversations when its status is away/idle
  app/livechat/server/config.js
  app/models/server/models/Users.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: livechat

#14428 [NEW] Add users.requestDataDownload API endpoint
  app/api/server/v1/users.js
  tests/end-to-end/api/01-users.js
Labels: Contain documentation PR, feat: api, feat: rest

#15428 [FIX] Issues saving audio notifications
  app/push-notifications/client/views/pushNotificationsFlexTab.js
  app/ui/client/lib/notification.js
Labels: feat: notification, subj: ui/ux, type: bug

#13902 [NEW] Separate integration roles
  app/api/server/v1/channels.js
  app/api/server/v1/groups.js
  app/api/server/v1/integrations.js
  app/authorization/server/startup.js
  app/integrations/client/startup.js
  app/integrations/client/views/additional/zapier.html
  app/integrations/client/views/integrations.js
  app/integrations/client/views/integrationsIncoming.html
  app/integrations/client/views/integrationsIncoming.js
  app/integrations/client/views/integrationsNew.html
  app/integrations/client/views/integrationsNew.js
  app/integrations/client/views/integrationsOutgoing.html
  app/integrations/client/views/integrationsOutgoing.js
  app/integrations/client/views/integrationsOutgoingHistory.js
  app/integrations/server/index.js
  app/integrations/server/lib/mountQueriesBasedOnPermission.js
  app/integrations/server/lib/validation.js
  app/integrations/server/methods/clearIntegrationHistory.js
  app/integrations/server/methods/incoming/addIncomingIntegration.js
  app/integrations/server/methods/incoming/deleteIncomingIntegration.js
  app/integrations/server/methods/incoming/updateIncomingIntegration.js
  app/integrations/server/methods/outgoing/addOutgoingIntegration.js
  app/integrations/server/methods/outgoing/deleteOutgoingIntegration.js
  app/integrations/server/methods/outgoing/replayOutgoingIntegration.js
  app/integrations/server/methods/outgoing/updateOutgoingIntegration.js
  app/integrations/server/publications/integrationHistory.js
  app/integrations/server/publications/integrations.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v164.js
  server/startup/migrations/v165.js
  tests/data/integration.helper.js
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/03-groups.js
  tests/end-to-end/api/06-outgoing-integrations.js
  tests/end-to-end/api/07-incoming-integrations.js
  yarn.lock
Labels: Contain documentation PR, feat: roles / permissions

#13991 [NEW] Remove all closed Livechat chats
  app/livechat/client/stylesheets/livechat.less
  app/livechat/client/views/app/livechatCurrentChats.html
  app/livechat/client/views/app/livechatCurrentChats.js
  app/livechat/server/index.js
  app/livechat/server/methods/removeAllClosedRooms.js
  app/models/server/models/LivechatRooms.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: livechat

#15510 [IMPROVE] Replace livechat:appearance pub to REST
  app/livechat/client/views/app/livechatAppearance.js
  app/livechat/imports/server/rest/appearance.js
  app/livechat/server/api.js
  app/livechat/server/api/lib/appearance.js
  app/livechat/server/publications/livechatAppearance.js
  tests/end-to-end/api/livechat/appearance.js
Labels: Contain documentation PR, feat: api, type: improvement

#15607 [IMPROVE] Replace livechat:integration publication by REST
  app/livechat/client/collections/LivechatIntegration.js
  app/livechat/client/views/app/integrations/livechatIntegrationWebhook.js
  app/livechat/imports/server/rest/integrations.js
  app/livechat/server/api.js
  app/livechat/server/api/lib/integrations.js
  app/livechat/server/publications/livechatIntegration.js
  app/models/server/raw/Settings.js
  tests/end-to-end/api/livechat/integrations.js
Labels: Contain documentation PR, type: improvement

#14596 [NEW] Nextcloud WebDAV auto-insertion & seamless login; WebDAV file picker improvements
  app/custom-oauth/server/custom_oauth_server.js
  app/file-upload/ufs/Webdav/server.js
  app/lib/server/startup/oAuthServicesUpdate.js
  app/models/server/models/WebdavAccounts.js
  app/nextcloud/client/index.js
  app/nextcloud/lib/common.js
  app/nextcloud/server/addWebdavServer.js
  app/nextcloud/server/index.js
  app/nextcloud/server/startup.js
  app/ui-login/client/login/services.js
  app/webdav/client/addWebdavAccount.js
  app/webdav/client/index.js
  app/webdav/client/webdavFilePicker.css
  app/webdav/client/webdavFilePicker.html
  app/webdav/client/webdavFilePicker.js
  app/webdav/server/index.js
  app/webdav/server/lib/webdavClientAdapter.js
  app/webdav/server/methods/addWebdavAccount.js
  app/webdav/server/methods/getFileFromWebdav.js
  app/webdav/server/methods/getWebdavCredentials.js
  app/webdav/server/methods/getWebdavFileList.js
  app/webdav/server/methods/getWebdavFilePreview.js
  app/webdav/server/methods/removeWebdavAccount.js
  app/webdav/server/methods/uploadFileToWebdav.js
  client/importPackages.js
  package-lock.json
  package.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/importPackages.js
  server/startup/migrations/index.js
  server/startup/migrations/v166.js
Labels: feat: file sharing, feat: oauth / sso

#11385 [NEW] Accept GIFs and SVGs for Avatars converting them to PNG and keep transparency of PNGs
  app/file-upload/server/lib/FileUpload.js
  app/theme/client/imports/forms/select-avatar.css
  app/ui-account/client/accountProfile.html
Labels: subj: ui/ux

#15646 Regression: AppRoomsConverter on Livechat rooms
  app/apps/server/converters/rooms.js
Labels: type: bug

#15675 Regression: Remove reference to obsolete template helper
  app/integrations/client/views/integrationsIncoming.html
Labels: subj: ui/ux, type: bug

#15658 [IMPROVE] Remove "EmojiCustom" unused subscription
  app/emoji-custom/client/admin/route.js
Labels: type: improvement

#15640 [FIX] Edit in thread
  app/threads/client/flextab/thread.js
  app/ui-utils/client/lib/MessageAction.js
Labels: feat: threads / discussions, subj: ui/ux, type: bug

#15638 [FIX] Null value at Notifications Preferences tab
  app/push-notifications/client/views/pushNotificationsFlexTab.js
Labels: feat: notification, subj: ui/ux, type: bug

#15645 [FIX] typo on PT-BR translation
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: subj: ui/ux

#15631 [FIX] Ignore file uploads from message box if text/plain content is being pasted
  app/ui-message/client/messageBox/messageBox.js
Labels: subj: ui/ux, type: bug

#15636 [FIX] Use Media Devices API to guess if a microphone is not available
  app/ui-message/client/messageBox/messageBoxAudioMessage.js
Labels: subj: ui/ux, type: bug

#15678 [IMPROVE] Replace snipptedMessages publication by REST
  app/api/server/lib/messages.js
  app/api/server/v1/chat.js
  app/message-snippet/client/tabBar/views/snippetedMessages.js
  app/message-snippet/server/publications/snippetedMessagesByRoom.js
  app/models/server/raw/Messages.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, type: improvement

#15679 [IMPROVE] Replace snippetedMessage publication by REST
  app/api/server/lib/messages.js
  app/api/server/v1/chat.js
  app/message-snippet/client/page/snippetPage.js
  app/message-snippet/server/publications/snippetedMessage.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, type: improvement
