Repository RocketChat/Rocket.Chat, pull requests merged in 2019-04, with the labels that each got.

#13896 [FIX] Display first message when taking Livechat inquiry
  app/livechat/client/views/sideNav/livechat.js
  app/livechat/server/index.js
  app/livechat/server/methods/getFirstRoomMessage.js
Labels: feat: livechat

#13521 [FIX] Minor issues detected after testing the new Livechat client
  app/livechat/server/api/lib/livechat.js
  app/livechat/server/api/v1/config.js
  app/livechat/server/lib/Livechat.js
  app/models/server/models/LivechatDepartmentAgents.js
Labels: feat: livechat

#13938 [FIX] Directory and Apps logs page
  app/apps/assets/stylesheets/apps.css
  app/apps/client/admin/apps.html
  app/apps/client/admin/apps.js
  app/theme/client/imports/components/modal/directory.css
  app/theme/client/imports/components/table.css
  app/theme/client/imports/general/apps.css
  app/theme/client/main.css
  app/ui-admin/client/rooms/adminRooms.html
  app/ui/client/index.js
  app/ui/client/views/app/directory.css
  app/ui/client/views/app/directory.html
  app/ui/client/views/app/directory.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: subj: ui/ux, type: bug

#13951 [FIX] Opening a Livechat room from another agent
  app/livechat/server/startup.js
  app/models/server/models/Rooms.js
Labels: feat: livechat, type: bug

#13757 [IMPROVE] UI of page not found
  client/main.js
  client/routes/pageNotFound.html
  client/routes/pageNotFound.js
  client/routes/stylesheets/pageNotFound.css
  packages/rocketchat-i18n/i18n/en.i18n.json
  public/images/404.svg
Labels: subj: ui/ux

#13968 [FIX] Change localStorage keys to work when server is running in a subdir
  app/oauth2-server-config/client/oauth/oauth2-client.js
  app/utils/client/lib/RestApiClient.js
Labels: type: bug

#13746 [FIX] Wrong permalink when running in subdir
  app/utils/lib/RoomTypesCommon.js
Labels: type: bug

#13824 [FIX] Auto hide Livechat room from sidebar on close
  app/livechat/server/lib/Livechat.js
  imports/message-read-receipt/server/hooks.js
Labels: feat: livechat

#13983 [NEW] - Add setting to request a comment when closing Livechat room
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/server/config.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: livechat

#13994 [FIX] Groups endpoints permission validations
  app/api/server/v1/groups.js
Labels: feat: api, feat: rest

#13969 [FIX] Add custom MIME types for *.ico extension
  app/assets/server/assets.js
Labels: type: bug

#13250 [FIX] Fix rendering of links in the announcement modal
  app/ui/client/views/app/room.js
Labels: subj: ui/ux, type: improvement

#13776 Change dynamic dependency of FileUpload in Messages models
  app/authorization/server/functions/canAccessRoom.js
  app/authorization/server/functions/hasPermission.js
  app/file-upload/client/lib/fileUploadHandler.js
  app/file-upload/lib/FileUpload.js
  app/file-upload/lib/FileUploadBase.js
  app/file-upload/server/lib/FileUpload.js
  app/models/server/models/Messages.js
  app/settings/server/functions/settings.js
  app/utils/lib/RoomTypeConfig.js
Labels: type: improvement

#13798 Deprecate /api/v1/info in favor of /api/info
  app/api/server/helpers/deprecationWarning.js
  app/api/server/v1/misc.js
  app/api/server/v1/permissions.js
Labels: Contain documentation PR, feat: api, feat: rest

#13495 [FIX] Real names were not displayed in the reactions (API/UI)
  app/ui-message/client/message.html
  app/ui-message/client/message.js
  app/utils/server/lib/composeMessageObjectWithUser.js
Labels: feat: api, feat: rest, subj: ui/ux, type: bug

#13982 [FIX] Links and upload paths when running in a subdir
  app/chatpal-search/client/template/result.html
  app/chatpal-search/client/template/result.js
  app/message-attachments/client/messageAttachment.html
  app/message-attachments/client/messageAttachment.js
  app/ui-flextab/client/tabs/uploadedFilesList.js
  app/ui-message/client/message.js
Labels: type: bug

#13842 [FIX] Closing sidebar when room menu is clicked.
  app/ui-sidenav/client/sidebarItem.js
  tests/end-to-end/ui/08-resolutions.js
  tests/pageobjects/side-nav.page.js
Labels: subj: ui/ux

#13732 [IMPROVE] UI of Permissions page
  app/authorization/client/stylesheets/permissions.css
  app/authorization/client/views/permissions.html
Labels: subj: ui/ux

#13510 [NEW] Add support to updatedSince parameter in emoji-custom.list and deprecated old endpoint
  app/api/server/v1/emoji-custom.js
  tests/end-to-end/api/12-emoji-custom.js
Labels: Contain documentation PR, feat: api, feat: rest

#14025 Settings: hiding reset button for readonly fields
  app/ui-admin/client/admin.js
Labels: feat: app settings

#14026 Settings: disable reset button
  app/federation/server/federation-settings.js
  app/ui-admin/client/admin.js
Labels: feat: app settings

#14018 Fix discussions issues after room deletion and translation actions not being shown
  app/autotranslate/client/lib/actionButton.js
  app/autotranslate/client/lib/autotranslate.js
  app/autotranslate/client/lib/tabBar.js
  app/channel-settings/server/functions/saveRoomName.js
  app/discussion/server/hooks/propagateDiscussionMetadata.js
  app/theme/client/imports/forms/input.css
  app/ui-message/client/message.js
  server/startup/migrations/index.js
  server/startup/migrations/v140.js
Labels: subj: ui/ux

#14049 Proper thread quote, clear message box on send, and other nice things to have
  app/oembed/client/oembedAudioWidget.html
  app/oembed/client/oembedFrameWidget.html
  app/oembed/client/oembedUrlWidget.html
  app/oembed/client/oembedVideoWidget.html
  app/oembed/client/oembedYoutubeWidget.html
  app/spotify/lib/client/oembedSpotifyWidget.html
  app/theme/client/imports/components/message-box.css
  app/theme/client/imports/components/messages.css
  app/theme/client/imports/components/sidebar/sidebar-item.css
  app/threads/client/threads.css
  app/threads/server/functions.js
  app/ui-message/client/message.html
  app/ui-message/client/messageBox.html
  app/ui-message/client/messageBox.js
  app/ui-sidenav/client/sidebarItem.html
  app/ui-utils/client/lib/RoomHistoryManager.js
  app/ui/client/lib/chatMessages.js
Labels: subj: ui/ux

#14057 Prioritize user-mentions badge
  app/ui-sidenav/client/sidebarItem.js
Labels: subj: ui/ux

#14031 [FIX] Livechat office hours
  app/models/server/models/Users.js
Labels: feat: livechat

#10695 [FIX] Livechat user registration in another department
  app/livechat/server/lib/Livechat.js
  packages/rocketchat-livechat/.app/client/lib/chatMessages.js
  packages/rocketchat-livechat/.app/client/views/messages.js
  packages/rocketchat-livechat/.app/client/views/register.js
  packages/rocketchat-livechat/.app/imports/client/visitor.js
Labels: stat: board-postponed

#13987 [NEW] Rest endpoints of discussions
  app/api/server/v1/rooms.js
  app/discussion/server/methods/createDiscussion.js
  tests/end-to-end/api/09-rooms.js
Labels: Contain documentation PR, feat: api, feat: rest

#14103 [FIX] Receiving agent for new livechats from REST API
  app/livechat/server/api/lib/livechat.js
  app/livechat/server/api/v1/room.js
  app/livechat/server/api/v1/videoCall.js
  app/livechat/server/lib/QueueMethods.js
Labels: feat: livechat, type: improvement

#14111 [Regression] Fix integrations message example
  app/integrations/client/views/integrationsIncoming.html
  app/integrations/client/views/integrationsIncoming.js
  app/integrations/client/views/integrationsOutgoing.html
  app/integrations/client/views/integrationsOutgoing.js
  app/integrations/client/views/messageExample.js
Labels: type: regression

#14130 [FIX] Missing connection headers on Livechat REST API
  app/livechat/server/api/lib/livechat.js
  app/livechat/server/api/v1/message.js
  app/livechat/server/api/v1/visitor.js
  app/livechat/server/lib/Livechat.js
Labels: feat: livechat

#13697 [NEW] Add Voxtelesys to list of SMS providers
  app/apps/server/bridges/settings.js
  app/sms/server/index.js
  app/sms/server/services/voxtelesys.js
  app/sms/server/settings.js
Labels: feat: livechat, type: improvement

#14113 [FIX] Custom Oauth login not working with accessToken
  app/custom-oauth/server/custom_oauth_server.js
  app/dolphin/lib/common.js
  app/drupal/lib/common.js
  app/gitlab/lib/common.js
  app/lib/server/methods/addOAuthService.js
  app/lib/server/methods/removeOAuthService.js
  app/lib/server/oauth/oauth.js
  app/lib/server/publications/settings.js
  app/lib/server/startup/oAuthServicesUpdate.js
  app/tokenpass/lib/common.js
  app/wordpress/lib/common.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/configuration/accounts_meld.js
Labels: feat: oauth / sso

#13761 [IMPROVE] OAuth Role Sync
  app/custom-oauth/server/custom_oauth_server.js
  app/custom-oauth/server/oauth_helpers.js
  app/lib/server/methods/addOAuthService.js
  app/lib/server/methods/removeOAuthService.js
  app/lib/server/startup/oAuthServicesUpdate.js
  packages/rocketchat-i18n/i18n/af.i18n.json
  packages/rocketchat-i18n/i18n/ar.i18n.json
  packages/rocketchat-i18n/i18n/az.i18n.json
  packages/rocketchat-i18n/i18n/be-BY.i18n.json
  packages/rocketchat-i18n/i18n/bg.i18n.json
  packages/rocketchat-i18n/i18n/bs.i18n.json
  packages/rocketchat-i18n/i18n/ca.i18n.json
  packages/rocketchat-i18n/i18n/cs.i18n.json
  packages/rocketchat-i18n/i18n/cy.i18n.json
  packages/rocketchat-i18n/i18n/da.i18n.json
  packages/rocketchat-i18n/i18n/de-AT.i18n.json
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/el.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/eo.i18n.json
  packages/rocketchat-i18n/i18n/es.i18n.json
  packages/rocketchat-i18n/i18n/fa.i18n.json
  packages/rocketchat-i18n/i18n/fi.i18n.json
  packages/rocketchat-i18n/i18n/fr.i18n.json
  packages/rocketchat-i18n/i18n/he.i18n.json
  packages/rocketchat-i18n/i18n/hr.i18n.json
  packages/rocketchat-i18n/i18n/hu.i18n.json
  packages/rocketchat-i18n/i18n/id.i18n.json
  packages/rocketchat-i18n/i18n/it.i18n.json
  packages/rocketchat-i18n/i18n/ja.i18n.json
  packages/rocketchat-i18n/i18n/km.i18n.json
  packages/rocketchat-i18n/i18n/ko.i18n.json
  packages/rocketchat-i18n/i18n/ku.i18n.json
  packages/rocketchat-i18n/i18n/lo.i18n.json
  packages/rocketchat-i18n/i18n/lt.i18n.json
  packages/rocketchat-i18n/i18n/lv.i18n.json
  packages/rocketchat-i18n/i18n/mn.i18n.json
  packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  packages/rocketchat-i18n/i18n/nl.i18n.json
  packages/rocketchat-i18n/i18n/no.i18n.json
  packages/rocketchat-i18n/i18n/pl.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-i18n/i18n/pt.i18n.json
  packages/rocketchat-i18n/i18n/ro.i18n.json
  packages/rocketchat-i18n/i18n/ru.i18n.json
  packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  packages/rocketchat-i18n/i18n/sq.i18n.json
  packages/rocketchat-i18n/i18n/sr.i18n.json
  packages/rocketchat-i18n/i18n/sv.i18n.json
  packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  packages/rocketchat-i18n/i18n/th-TH.i18n.json
  packages/rocketchat-i18n/i18n/tr.i18n.json
  packages/rocketchat-i18n/i18n/uk.i18n.json
  packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  packages/rocketchat-i18n/i18n/zh-HK.i18n.json
  packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: feat: oauth / sso

#14131 [IMPROVE] Get avatar from oauth
  app/api/server/helpers/getUserInfo.js
  app/custom-oauth/server/custom_oauth_server.js
  app/lib/server/functions/getAvatarSuggestionForUser.js
  app/lib/server/methods/addOAuthService.js
  app/lib/server/methods/removeOAuthService.js
  app/lib/server/startup/oAuthServicesUpdate.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/lib/accounts.js
Labels: feat: oauth / sso

#14071 Update badges and mention links colors
  app/mentions/client/mentionLink.css
  app/mentions/lib/MentionsParser.js
  app/mentions/tests/client.tests.js
  app/theme/client/imports/general/variables.css
  app/ui-flextab/client/tabs/membersList.html
  app/ui-flextab/client/tabs/membersList.js
  app/ui-utils/client/lib/RoomManager.js
  app/ui/client/views/app/room.js
  private/client/imports/general/variables.css
Labels: subj: ui/ux, type: bug

#14121 [FIX] Custom Oauth store refresh and id tokens with expiresIn
  app/custom-oauth/server/custom_oauth_server.js
Labels: feat: oauth / sso

#14147 [NEW] Add GET method to fetch Livechat message through REST API
  app/livechat/server/api/v1/message.js
Labels: feat: livechat, type: improvement

#14170 Prevent error on normalize thread message for preview
  app/ui-utils/client/lib/RoomHistoryManager.js
Labels: feat: threads / discussions, subj: ui/ux, type: bug

#14045 [NEW] Rest threads
  app/api/server/v1/chat.js
  tests/data/chat.helper.js
  tests/data/users.helper.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, feat: api, feat: rest

#14192 Regression: wrong expression at messageBox.actions.remove()
  app/ui-utils/client/lib/messageBox.js
Labels: subj: ui/ux, type: regression

#14210 Use own logic to get thread infos via REST
  app/api/server/v1/chat.js
  tests/end-to-end/api/05-chat.js
Labels: Contain documentation PR, feat: api, feat: rest

#14213 Use main message as thread tab title
  app/theme/client/imports/components/contextual-bar.css
  app/threads/client/flextab/thread.html
  app/threads/client/flextab/thread.js
Labels: feat: threads / discussions, subj: ui/ux

#14215 Prevent click on reply thread to trigger flex tab closing
  app/ui/client/views/app/room.js
Labels: feat: threads / discussions, subj: ui/ux

#14189 Regression: System messages styling
  app/theme/client/imports/general/base_old.css
  app/theme/client/imports/general/rtl.css
  app/ui-message/client/message.html
  app/ui-message/client/message.js
  package-lock.json
Labels: feat: message, subj: ui/ux, type: regression

#14219 Regression: Prevent startup errors for mentions parsing
  app/mentions/client/client.js
Labels: subj: ui/ux, type: regression

#14217 Unify mime-type package configuration
  app/assets/server/assets.js
  app/file-upload/server/lib/FileUpload.js
  app/ui-account/client/avatar/prompt.js
  app/ui-message/client/startup/messageBoxActions.js
  app/ui/client/lib/fileUpload.js
  app/ui/client/views/app/room.js
  app/utils/client/index.js
  app/utils/lib/mimeTypes.js
  app/utils/server/index.js
  package-lock.json
  package.json
Labels: feat: file sharing, type: bug

#14223 Regression: Broken UI for messages
  app/emoji/client/emojiParser.js
  app/theme/client/imports/general/base_old.css
  app/threads/client/flextab/thread.html
Labels: feat: message, feat: threads / discussions, subj: ui/ux, type: regression

#14222 Broken styles in Administration's contextual bar
  app/theme/client/imports/components/contextual-bar.css
  app/theme/client/imports/general/base_old.css
  app/ui-admin/client/rooms/adminRoomInfo.html
  app/ui-admin/client/users/adminUserInfo.html
  app/ui-flextab/client/flexTabBar.html
  app/ui-flextab/client/tabs/userEdit.html
  package-lock.json
Labels: subj: ui/ux, type: regression

#14216 [Regression] Personal Access Token list fixed
  imports/personal-access-tokens/client/personalAccessTokens.html
Labels: subj: ui/ux, type: regression

#14235 Regression: Remove border from unstyled message body
  app/theme/client/imports/components/messages.css
Labels: subj: ui/ux, type: bug

#14236 [NEW]Set up livechat connections created from new client
  app/livechat/server/index.js
  app/livechat/server/methods/setUpConnection.js
Labels: feat: livechat, type: improvement

#14244 [FIX] Empty result when getting badge count notification
  app/lib/server/functions/notifications/mobile.js
Labels: type: bug

#14163 [FIX] Autogrow not working properly for many message boxes
  app/theme/client/imports/general/base_old.css
  app/theme/client/imports/general/rtl.css
  app/ui-message/client/index.js
  app/ui-message/client/message.js
  app/ui-message/client/messageBox/messageBox.html
  app/ui-message/client/messageBox/messageBox.js
  app/ui-message/client/messageBox/messageBoxActions.js
  app/ui-message/client/messageBox/messageBoxAudioMessage.html
  app/ui-message/client/messageBox/messageBoxAudioMessage.js
  app/ui-message/client/messageBox/messageBoxAutogrow.js
  app/ui-message/client/messageBox/messageBoxFormatting.js
  app/ui-message/client/messageBox/messageBoxNotSubscribed.html
  app/ui-message/client/messageBox/messageBoxNotSubscribed.js
  app/ui-message/client/messageBox/messageBoxReplyPreview.html
  app/ui-message/client/messageBox/messageBoxReplyPreview.js
  app/ui-message/client/messageBox/messageBoxTyping.html
  app/ui-message/client/messageBox/messageBoxTyping.js
  app/ui-message/client/messageDropdown.html
  app/ui-message/client/popup/messagePopup.js
  app/ui-message/client/popup/messagePopupChannel.js
  app/ui-message/client/popup/messagePopupConfig.js
  app/ui-message/client/popup/messagePopupEmoji.js
  app/ui-message/client/popup/messagePopupSlashCommandPreview.js
  app/ui-message/client/startup/index.js
  app/ui/client/index.js
  app/ui/client/lib/textarea-autogrow.js
  private/server/colors.less
Labels: subj: ui/ux, type: bug

#14012 [FIX] Normalize TAPi18n language string on Livechat widget
  packages/rocketchat-livechat/.app/client/views/livechatWindow.js
Labels: feat: livechat, type: bug

#14253 Regression: invite user autocomplete loading forever
  app/channel-settings-mail-messages/client/views/mailMessagesInstructions.html
  app/channel-settings-mail-messages/client/views/mailMessagesInstructions.js
  app/ui-clean-history/client/views/cleanHistory.html
  app/ui-flextab/client/tabs/inviteUsers.html
  app/ui-flextab/client/tabs/inviteUsers.js
  app/ui/client/components/popupList.js
Labels: subj: ui/ux

#14007 Added federation ping, loopback and dashboard
  app/federation/client/admin/dashboard.css
  app/federation/client/admin/dashboard.html
  app/federation/client/admin/dashboard.js
  app/federation/client/index.js
  app/federation/client/messageTypes.js
  app/federation/server/PeerClient.js
  app/federation/server/PeerDNS.js
  app/federation/server/PeerHTTP/PeerHTTP.js
  app/federation/server/PeerHTTP/utils.js
  app/federation/server/PeerPinger.js
  app/federation/server/PeerServer/PeerServer.js
  app/federation/server/PeerServer/routes/events.js
  app/federation/server/federatedResources/FederatedRoom.js
  app/federation/server/federation-settings.js
  app/federation/server/index.js
  app/federation/server/logger.js
  app/federation/server/methods/addUser.js
  app/federation/server/methods/dashboard.js
  app/federation/server/methods/ping.js
  app/lib/server/functions/deleteUser.js
  app/models/server/index.js
  app/models/server/models/FederationEvents.js
  app/models/server/models/FederationPeers.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v143.js
Labels: feat: federation

#14265 [FIX] Align burger menu in header with content matching room header
  app/theme/client/imports/components/header.css
  app/theme/client/imports/general/base_old.css
Labels: subj: ui/ux, type: improvement

#14268 [NEW] Update message actions
  app/autotranslate/client/lib/actionButton.js
  app/message-mark-as-unread/client/actionButton.js
  app/message-pin/client/actionButton.js
  app/message-snippet/client/actionButton.js
  app/message-star/client/actionButton.js
  app/threads/client/index.js
  app/threads/client/messageAction/follow.js
  app/threads/client/messageAction/replyInThread.js
  app/threads/client/messageAction/unfollow.js
  app/ui-master/public/icons/discussion.svg
  app/ui-master/public/icons/reply-directly.svg
  app/ui-master/public/icons/report.svg
  app/ui-message/client/messageBox/messageBox.js
  app/ui-sidenav/client/sidebarItem.js
  app/ui-utils/client/lib/MessageAction.js
  app/ui-utils/client/lib/popover.js
  app/ui/client/views/app/room.js
  imports/message-read-receipt/client/room.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  private/public/icons.svg
  public/public/icons.html
  tests/pageobjects/main-content.page.js
Labels: subj: ui/ux

#14274 Force unstyling of blockquote under .message-body--unstyled
  app/theme/client/imports/components/messages.css
Labels: subj: ui/ux, type: bug

#14050 Regression: Discussions were not showing on Tab Bar
  app/discussion/client/views/DiscussionTabbar.html
  app/discussion/client/views/DiscussionTabbar.js
Labels: feat: threads / discussions, type: regression

#13986 [IMPROVE] Replace livechat inquiry dialog with preview room
  app/livechat/client/index.js
  app/livechat/client/route.js
  app/livechat/client/views/app/analytics/livechatAnalytics.js
  app/livechat/client/views/app/analytics/livechatAnalyticsCustomDaterange.js
  app/livechat/client/views/app/analytics/livechatAnalyticsDaterange.js
  app/livechat/client/views/app/analytics/livechatRealTimeMonitoring.js
  app/livechat/client/views/app/integrations/livechatIntegrationFacebook.js
  app/livechat/client/views/app/integrations/livechatIntegrationWebhook.js
  app/livechat/client/views/app/livechatAppearance.js
  app/livechat/client/views/app/livechatCurrentChats.js
  app/livechat/client/views/app/livechatCustomFieldForm.js
  app/livechat/client/views/app/livechatCustomFields.js
  app/livechat/client/views/app/livechatDepartmentForm.js
  app/livechat/client/views/app/livechatDepartments.js
  app/livechat/client/views/app/livechatInstallation.js
  app/livechat/client/views/app/livechatIntegrations.html
  app/livechat/client/views/app/livechatOfficeHours.js
  app/livechat/client/views/app/livechatQueue.js
  app/livechat/client/views/app/livechatReadOnly.html
  app/livechat/client/views/app/livechatReadOnly.js
  app/livechat/client/views/app/livechatTriggers.js
  app/livechat/client/views/app/livechatTriggersForm.js
  app/livechat/client/views/app/livechatUsers.js
  app/livechat/client/views/app/tabbar/externalSearch.js
  app/livechat/client/views/app/tabbar/visitorEdit.js
  app/livechat/client/views/app/tabbar/visitorForward.js
  app/livechat/client/views/app/tabbar/visitorHistory.js
  app/livechat/client/views/app/tabbar/visitorInfo.html
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/client/views/app/tabbar/visitorNavigation.js
  app/livechat/client/views/app/triggers/livechatTriggerAction.js
  app/livechat/client/views/app/triggers/livechatTriggerCondition.js
  app/livechat/client/views/sideNav/livechat.js
  app/livechat/client/views/sideNav/livechatFlex.js
  app/livechat/lib/LivechatRoomType.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/publications/livechatInquiries.js
  app/livechat/server/startup.js
  app/theme/client/imports/components/message-box.css
  app/ui-message/client/messageBox/messageBox.html
  app/ui-message/client/messageBox/messageBox.js
  app/ui-message/client/messageBox/messageBoxNotSubscribed.html
  app/ui-message/client/messageBox/messageBoxReadOnly.html
  app/ui-message/client/messageBox/messageBoxReadOnly.js
  app/ui/client/views/app/room.js
  app/utils/client/lib/roomTypes.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/publications/room.js
Labels: feat: livechat, type: improvement

#14311 [FIX] Remove reference to inexistent field when deleting message in thread
  app/threads/client/flextab/threads.js
Labels: feat: threads / discussions, subj: ui/ux, type: bug

#14313 [FIX] show roles on message
  app/theme/client/imports/general/base_old.css
  app/ui-message/client/message.js
Labels: subj: ui/ux

#14301 [Regression] Anonymous user fix
  app/lib/server/functions/getAvatarSuggestionForUser.js
Labels: subj: ui/ux, type: bug

#14316 [FIX] View Logs admin page was broken and not rendering color logs
  app/logger/client/ansispan.js
  app/logger/client/index.js
  app/logger/client/views/viewLogs.css
  app/logger/client/views/viewLogs.html
  app/logger/client/views/viewLogs.js
  app/theme/client/imports/general/base_old.css
  app/theme/client/imports/general/rtl.css
Labels: subj: ui/ux, type: bug

#14011 [FIX] Missing i18n for some new Permissions
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: i18n, type: improvement

#14182 i18n: Update German strings
  packages/rocketchat-i18n/i18n/de.i18n.json
Labels: feat: i18n, type: improvement

#14318 Add cross-browser select arrow positioning
  app/theme/client/imports/forms/select.css
Labels: subj: ui/ux, type: bug

#14330 [FIX] Duplicate thread message after editing
  app/models/server/models/Messages.js
  app/threads/client/flextab/thread.js
  app/threads/client/flextab/threads.js
  app/threads/server/methods/getThreadMessages.js
Labels: subj: ui/ux

#14334 [IMPROVE] i18n of threads and discussion buttons
  app/ui-message/client/message.html
  app/ui-message/client/message.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: i18n, feat: threads / discussions, type: improvement

#14338 [FIX] Unread line and new day separator was not aligned
  app/theme/client/imports/general/base.css
Labels: subj: ui/ux
