Repository RocketChat/Rocket.Chat, pull requests merged in 2019-09, with the labels that each got.

#15258 Fix apps list error
  app/apps/client/admin/apps.js
Labels: type: release candidate bug

#15319 [FIX] IE11 baseURI
  app/ui/client/components/icon.js
  app/utils/client/lib/RestApiClient.js
  app/utils/client/lib/baseuri.js
Labels: subj: ui/ux

#15242 Regression: New Livechat methods and processes
  app/livechat/client/views/app/tabbar/visitorEdit.js
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/lib/LivechatInquiry.js
  app/livechat/server/api/v1/room.js
  app/livechat/server/config.js
  app/livechat/server/index.js
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/RoutingManager.js
  app/livechat/server/lib/routing/AutoSelection.js
  app/livechat/server/lib/routing/ManualSelection.js
  app/livechat/server/publications/livechatAgents.js
  app/livechat/server/publications/livechatManagers.js
  app/livechat/server/publications/livechatRooms.js
  app/livechat/server/startup.js
  app/models/server/models/LivechatRooms.js
  app/models/server/models/Settings.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v155.js
Labels: feat: livechat

#15329 Regression: last message doesn't update after reconnect
  app/ui-cached-collection/client/models/CachedCollection.js
Labels: subj: ui/ux

#15257 [CHORE] Remove obsolete modal template
  app/theme/client/imports/general/base_old.css
  app/ui/client/index.js
  app/ui/client/views/modal.html
  app/ui/client/views/modal.js
Labels: subj: ui/ux

#15295 [FIX] Reduce Message cache time to 500ms
  app/ui-utils/client/lib/renderMessageBody.js
Labels: subj: ui/ux

#15256 [IMPROVE] Add CustomSounds.play() helper
  app/custom-sounds/client/admin/adminSounds.js
  app/custom-sounds/client/lib/CustomSounds.js
  app/livechat/client/startup/notifyUnreadRooms.js
  app/push-notifications/client/views/pushNotificationsFlexTab.js
  app/ui-account/client/accountPreferences.js
  app/ui/client/lib/notification.js
Labels: subj: ui/ux, type: improvement

#15056 [FIX] Duplicate Channels in Search-bar
  app/ui-sidenav/client/toolbar.js
Labels: subj: ui/ux

#15351 [NEW] Only Load CodeMirror code when it is needed
  app/ui-admin/client/admin.html
  app/ui-admin/client/admin.js
  app/ui/client/index.js
  app/ui/client/lib/codeMirror/codeMirror.js
  app/ui/client/lib/codeMirror/codeMirrorComponent.js
  app/ui/client/lib/codeMirror/index.js
Labels: subj: ui/ux

#15340 [IMPROVE] improve autolinker flow
  app/autolinker/client/client.js
Labels: subj: ui/ux

#15238 [NEW] Provide site-url to outgoing integrations
  app/integrations/server/lib/triggerHandler.js
Labels: feat: integration / plugin

#15260 [IMPROVE] Replace LESS autoprefixer plugin
  .postcssrc
  app/theme/client/imports/general/base_old.css
  app/theme/server/server.js
  package-lock.json
  package.json
Labels: type: improvement

#15382 [FIX] Grammatical error in Not Found page
  client/components/pageNotFound/PageNotFound.js
  packages/rocketchat-i18n/i18n/af.i18n.json
  packages/rocketchat-i18n/i18n/ar.i18n.json
  packages/rocketchat-i18n/i18n/az.i18n.json
  packages/rocketchat-i18n/i18n/be-BY.i18n.json
  packages/rocketchat-i18n/i18n/bg.i18n.json
  packages/rocketchat-i18n/i18n/bs.i18n.json
  packages/rocketchat-i18n/i18n/ca.i18n.json
  packages/rocketchat-i18n/i18n/cs.i18n.json
  packages/rocketchat-i18n/i18n/cy.i18n.json
  packages/rocketchat-i18n/i18n/da.i18n.json
  packages/rocketchat-i18n/i18n/de-AT.i18n.json
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/el.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/eo.i18n.json
  packages/rocketchat-i18n/i18n/es.i18n.json
  packages/rocketchat-i18n/i18n/fa.i18n.json
  packages/rocketchat-i18n/i18n/fi.i18n.json
  packages/rocketchat-i18n/i18n/fr.i18n.json
  packages/rocketchat-i18n/i18n/he.i18n.json
  packages/rocketchat-i18n/i18n/hr.i18n.json
  packages/rocketchat-i18n/i18n/hu.i18n.json
  packages/rocketchat-i18n/i18n/id.i18n.json
  packages/rocketchat-i18n/i18n/it.i18n.json
  packages/rocketchat-i18n/i18n/ja.i18n.json
  packages/rocketchat-i18n/i18n/km.i18n.json
  packages/rocketchat-i18n/i18n/ko.i18n.json
  packages/rocketchat-i18n/i18n/ku.i18n.json
  packages/rocketchat-i18n/i18n/lo.i18n.json
  packages/rocketchat-i18n/i18n/lt.i18n.json
  packages/rocketchat-i18n/i18n/lv.i18n.json
  packages/rocketchat-i18n/i18n/mn.i18n.json
  packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  packages/rocketchat-i18n/i18n/nl.i18n.json
  packages/rocketchat-i18n/i18n/no.i18n.json
  packages/rocketchat-i18n/i18n/pl.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-i18n/i18n/pt.i18n.json
  packages/rocketchat-i18n/i18n/ro.i18n.json
  packages/rocketchat-i18n/i18n/ru.i18n.json
  packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  packages/rocketchat-i18n/i18n/sq.i18n.json
  packages/rocketchat-i18n/i18n/sr.i18n.json
  packages/rocketchat-i18n/i18n/sv.i18n.json
  packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  packages/rocketchat-i18n/i18n/th-TH.i18n.json
  packages/rocketchat-i18n/i18n/tr.i18n.json
  packages/rocketchat-i18n/i18n/uk.i18n.json
  packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  packages/rocketchat-i18n/i18n/zh-HK.i18n.json
  packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: feat: i18n, type: bug

#15385 [FIX] User Profile Time Format
  app/ui-flextab/client/tabs/userInfo.js
Labels: subj: ui/ux

#15384 [Fix] Missing space between last username & 'and' word in react notification
  app/ui-message/client/message.js
Labels: subj: ui/ux

#15297 [NEW] Add JWT to uploaded files urls
  app/file-upload/server/lib/FileUpload.js
  app/file-upload/server/startup/settings.js
  app/livechat/server/api/v1/message.js
  app/livechat/server/hooks/externalMessage.js
  app/livechat/server/hooks/saveAnalyticsData.js
  app/livechat/server/hooks/sendToCRM.js
  app/livechat/server/hooks/sendToFacebook.js
  app/livechat/server/methods/sendMessageLivechat.js
  app/livechat/server/sendMessageBySMS.js
  app/utils/server/functions/normalizeMessageAttachments.js
  app/utils/server/lib/JWTHelper.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v157.js
Labels: feat: livechat

#15392 [FIX] Empty custom emojis on emoji picker
  app/emoji-custom/client/lib/emojiCustom.js
Labels: subj: ui/ux

#15356 Remove GraphQL dependencies left
  graphql.config.json
  package-lock.json
  package.json
Labels: Contain documentation PR

#15327 [FIX] Limit exposed fields on some users. endpoints
  app/api/server/v1/users.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest

#14644 [FIX] LDAP usernames get additional '.' if they contain numbers
  app/ldap/server/sync.js
  app/lib/server/functions/getUsernameSuggestion.js
Labels: subj: Auth - LDAP

#15288 [FIX] REST endpoint `users.setPreferences` to not override all user's preferences
  app/api/server/v1/users.js
  tests/data/user.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest

#15400 [IMPROVE] Make the agents field optional when updating Livechat departments
  app/livechat/imports/server/rest/departments.js
  app/livechat/server/lib/Livechat.js
  app/models/server/models/LivechatDepartment.js
Labels: feat: livechat

#15292 [FIX] REST API to return only public custom fields
  app/api/server/api.js
Labels: feat: api, feat: rest

#15334 [FIX] Add ENV VAR to enable users create token feature
  app/lib/server/methods/createToken.js
  tests/end-to-end/api/01-users.js
Labels: feat: api, feat: rest

#14544 [FIX] Subscription record not having the `ls` field
  server/methods/readMessages.js
Labels: type: bug

#15409 [FIX] Double send bug on message box
  app/ui-message/client/messageBox/messageBox.js
  app/ui/client/lib/chatMessages.js
Labels: subj: ui/ux, type: bug

#15405 [IMPROVE] A11y: Buttons, Images, Popups
  app/apps/client/admin/appManage.html
  app/lazy-load/client/lazyloadImage.html
  app/lib/server/startup/settings.js
  app/search/client/search/search.html
  app/threads/client/flextab/thread.html
  app/ui-account/client/avatar/avatar.html
  app/ui-account/client/avatar/avatar.js
  app/ui-flextab/client/flexTabBar.html
  app/ui-flextab/client/tabs/membersList.html
  app/ui-flextab/client/tabs/userInfo.html
  app/ui-message/client/message.html
  app/ui-message/client/messageBox/messageBox.html
  app/ui-message/client/messageThread.html
  app/ui-sidenav/client/sidebarHeader.html
  app/ui-sidenav/client/sidebarHeader.js
  app/ui-sidenav/client/sidebarItem.html
  app/ui-utils/client/lib/alerts.html
  app/ui-utils/client/lib/popout.html
  app/ui/client/components/contextualBar.html
  app/ui/client/components/header/headerRoom.html
  app/ui/client/components/header/headerRoom.js
  package-lock.json
  tests/pageobjects/main-content.page.js
Labels: feat: accessibility, subj: ui/ux, type: bug

#15412 [FIX] Fix file uploads JWT
  app/livechat/server/api/v1/message.js
  app/livechat/server/hooks/externalMessage.js
  app/livechat/server/hooks/saveAnalyticsData.js
  app/livechat/server/hooks/sendToCRM.js
  app/livechat/server/hooks/sendToFacebook.js
  app/livechat/server/sendMessageBySMS.js
  app/utils/server/functions/normalizeMessageAttachments.js
  app/utils/server/functions/normalizeMessageFileUpload.js
Labels: feat: livechat

#15294 [IMPROVE] User data export
  app/file-upload/server/config/GridFS.js
  app/models/server/models/ExportOperations.js
  app/user-data-download/server/cronProcessDownloads.js
  app/user-data-download/server/startup/settings.js
  server/methods/requestDataDownload.js
  server/startup/migrations/index.js
  server/startup/migrations/v159.js
Labels: subj: GDPR

#15216 [NEW] Livechat setting to show/hide Agent Information on the widget
  app/livechat/client/views/app/livechatAppearance.html
  app/livechat/client/views/app/livechatAppearance.js
  app/livechat/server/api/lib/livechat.js
  app/livechat/server/api/v1/config.js
  app/livechat/server/config.js
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/methods/saveAppearance.js
  app/livechat/server/publications/livechatAppearance.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: livechat

#15426 Regression: Favorite room button
  app/theme/client/imports/components/header.css
  app/theme/client/imports/components/tooltip.css
  app/ui/client/components/header/header.js
  app/ui/client/components/header/headerRoom.html
  app/ui/client/components/header/headerRoom.js
  app/ui/client/index.js
Labels: subj: ui/ux, type: bug

#15432 Regression: setup wizard dynamic import using relative url
  client/routes.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux

#15415 [NEW] Allow file sharing through Twilio(WhatsApp) integration
  app/livechat/server/sendMessageBySMS.js
  app/sms/server/services/twilio.js
  app/sms/server/settings.js
  package.json
Labels: feat: livechat

#15457 [IMPROVE] Update Fuselage components on SetupWizard
  client/components/setupWizard/StepHeader.js
  client/components/setupWizard/steps/AdminUserInformationStep.js
  client/components/setupWizard/steps/RegisterServerStep.css
  client/components/setupWizard/steps/RegisterServerStep.js
  client/components/setupWizard/steps/SettingsBasedStep.js
  package-lock.json
  package.json
Labels: subj: ui/ux, type: improvement
