Repository RocketChat/Rocket.Chat, pull requests merged in 2020-06, with the labels that each got.

#17818 [IMPROVE][Federation] Add support for _tcp and protocol DNS entries
  app/federation/server/lib/dns.js
  app/federation/server/lib/http.js
Labels: feat: federation

#17853 [FIX] Logic for room type was inverted in edit panel (#17851)
  client/admin/rooms/EditRoom.js
Labels: sponsored

#17854 [FIX] Reorder hljs
  app/markdown/lib/hljs.js
  app/markdown/tests/client.tests.js
Labels: subj: ui/ux, type: bug

#17893 Change some components' location
  app/ui-message/client/index.js
  app/ui-sidenav/client/sidebarHeader.js
  app/ui/client/index.js
  client/admin/customEmoji/CustomEmoji.js
  client/admin/customSounds/AdminSounds.js
  client/admin/customUserStatus/CustomUserStatus.js
  client/admin/integrations/IntegrationsTable.js
  client/admin/invites/InvitesPage.js
  client/admin/oauthApps/OAuthAppsTable.js
  client/admin/rooms/RoomsTable.js
  client/admin/users/UsersTable.js
  client/components/GenericTable.js
  client/components/GenericTable.stories.js
  client/components/RoomForeword.js
  client/components/SortList.js
  client/routes.js
  client/views/blocks/MessageBlock.js
  client/views/blocks/ModalBlock.js
  client/views/blocks/index.js
  client/views/directory/ChannelsTab.js
  client/views/directory/DirectoryPage.js
  client/views/directory/UserTab.js
  client/views/directory/hooks.js
Labels: subj: ui/ux

#17900 [IMPROVE] Rewrite Federation Dashboard
  app/federation/client/admin/dashboard.css
  app/federation/client/admin/dashboard.html
  app/federation/client/admin/dashboard.js
  app/federation/client/index.js
  client/admin/federationDashboard/FederationDashboardPage.js
  client/admin/federationDashboard/FederationDashboardPage.stories.js
  client/admin/federationDashboard/FederationDashboardRoute.tsx
  client/admin/federationDashboard/OverviewSection.js
  client/admin/federationDashboard/OverviewSection.stories.js
  client/admin/federationDashboard/ServersSection.js
  client/admin/federationDashboard/ServersSection.stories.js
  client/admin/routes.js
  client/admin/sidebarItems.js
  client/components/data/Counter.js
  client/components/data/Counter.stories.js
  client/components/data/CounterSet.js
  client/components/data/CounterSet.stories.js
  client/components/data/Growth.js
  client/components/data/Growth.stories.js
  client/components/data/NegativeGrowthSymbol.js
  client/components/data/NegativeGrowthSymbol.stories.js
  client/components/data/PositiveGrowthSymbol.js
  client/components/data/PositiveGrowthSymbol.stories.js
  client/contexts/ServerContext.js
  client/contexts/ServerContext.ts
  client/importPackages.js
  client/providers/ServerProvider.js
  ee/app/engagement-dashboard/client/components/ChannelsTab/TableSection.js
  ee/app/engagement-dashboard/client/components/MessagesTab/MessagesSentSection.js
  ee/app/engagement-dashboard/client/components/UsersTab/ActiveUsersSection.js
  ee/app/engagement-dashboard/client/components/UsersTab/NewUsersSection.js
  ee/app/engagement-dashboard/client/components/data/Counter.stories.js
  ee/app/engagement-dashboard/client/components/data/Growth.stories.js
  ee/app/engagement-dashboard/client/components/data/NegativeGrowthSymbol.stories.js
  ee/app/engagement-dashboard/client/components/data/PositiveGrowthSymbol.stories.js
Labels: subj: ui/ux, type: improvement

#17916 [IMPROVE] Performance editing Admin settings
  app/settings/client/lib/settings.ts
  client/admin/AdministrationRouter.js
  client/admin/PrivilegedSettingsProvider.js
  client/admin/settings/GroupPage.js
  client/admin/settings/GroupPage.stories.js
  client/admin/settings/GroupSelector.js
  client/admin/settings/GroupSelector.stories.js
  client/admin/settings/GroupSelector.tsx
  client/admin/settings/Section.js
  client/admin/settings/Setting.js
  client/admin/settings/SettingsRoute.js
  client/admin/settings/groups/AssetsGroupPage.js
  client/admin/settings/groups/GenericGroupPage.js
  client/admin/settings/groups/OAuthGroupPage.js
  client/admin/sidebar/AdminSidebar.js
  client/admin/users/UserInfo.js
  client/contexts/EditableSettingsContext.ts
  client/contexts/PrivilegedSettingsContext.ts
  client/contexts/SettingsContext.js
  client/contexts/SettingsContext.ts
  client/fuselage-hooks.d.ts
  client/hooks/useQuery.ts
  client/hooks/useReactiveSubscriptionFactory.ts
  client/lib/settings/PrivateSettingsCachedCollection.ts
  client/lib/settings/PublicSettingsCachedCollection.ts
  client/meteor.d.ts
  client/providers/EditableSettingsProvider.tsx
  client/providers/MeteorProvider.js
  client/providers/SettingsProvider.js
  client/providers/SettingsProvider.tsx
  client/views/setupWizard/steps/FinalStep.js
  client/views/setupWizard/steps/RegisterServerStep.js
  client/views/setupWizard/steps/SettingsBasedStep.js
  definition/ISetting.ts
Labels: subj: performance, subj: ui/ux, type: improvement

#17872 [NEW] Prune messages support for new events architecture
  app/events/definitions/IEvent.ts
  app/events/definitions/data/IEDataMessage.ts
  app/lib/server/functions/cleanRoomHistory.js
  app/lib/server/methods/cleanRoomHistory.js
  app/models/server/models/RoomEvents.ts
Labels: backend

#17949 Regression: Infinite loop in CodeSettingInput
  client/admin/settings/inputs/CodeSettingInput.js
Labels: subj: ui/ux, type: bug

#17948 [FIX] Video conferences being started by users without permission
  app/api/server/v1/video-conference.js
  app/videobridge/client/views/videoFlexTab.js
  app/videobridge/server/methods/jitsiSetTimeout.js
Labels: documentation: needed

#17346 [IMPROVE] Refactor Omnichannel Past Chats List
  app/livechat/client/stylesheets/livechat.css
  app/livechat/client/ui.js
  app/livechat/client/views/app/tabbar/contactChatHistory.html
  app/livechat/client/views/app/tabbar/contactChatHistory.js
  app/livechat/client/views/app/tabbar/contactChatHistoryItem.html
  app/livechat/client/views/app/tabbar/contactChatHistoryItem.js
  app/livechat/client/views/app/tabbar/contactChatHistoryMessages.html
  app/livechat/client/views/app/tabbar/contactChatHistoryMessages.js
  app/livechat/client/views/app/tabbar/visitorHistory.html
  app/livechat/client/views/app/tabbar/visitorHistory.js
  app/livechat/client/views/regular.js
  app/livechat/imports/server/rest/visitors.js
  app/livechat/server/api/lib/visitors.js
  app/livechat/server/api/v1/message.js
  app/models/server/models/LivechatRooms.js
  app/models/server/models/Messages.js
  app/models/server/raw/LivechatRooms.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: omnichannel

#17918 [FIX] Missing User when forwarding Omnichannel conversations via Apps-Engine
  app/apps/server/bridges/livechat.js
Labels: feat: apps, feat: omnichannel, type: bug

#17970 [FIX] Autocomplete component is not working property when searching channels in the Livechat Departments form
  app/livechat/client/views/app/livechatDepartmentForm.html
  app/livechat/client/views/app/livechatDepartmentForm.js
Labels: feat: omnichannel

#12958 [NEW] Make ldap avatar source field customizable
  app/ldap/server/settings.js
  app/ldap/server/sync.js
  packages/rocketchat-i18n/i18n/de-AT.i18n.json
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: Auth - LDAP

#17906 [NEW] Rewrite Apps
  app/apps/client/admin/appInstall.html
  app/apps/client/admin/appInstall.js
  app/apps/client/admin/appLogs.html
  app/apps/client/admin/appLogs.js
  app/apps/client/admin/appManage.css
  app/apps/client/admin/appManage.html
  app/apps/client/admin/appManage.js
  app/apps/client/admin/appWhatIsIt.html
  app/apps/client/admin/appWhatIsIt.js
  app/apps/client/admin/apps.html
  app/apps/client/admin/apps.js
  app/apps/client/admin/helpers.js
  app/apps/client/admin/marketplace.html
  app/apps/client/admin/marketplace.js
  app/apps/client/admin/modalTemplates/iframeModal.html
  app/apps/client/admin/modalTemplates/iframeModal.js
  app/apps/client/admin/views.js
  app/apps/client/index.js
  app/apps/client/orchestrator.js
  app/apps/client/routes.js
  client/admin/apps/AppDetailsPage.js
  client/admin/apps/AppInstallPage.js
  client/admin/apps/AppLogsPage.js
  client/admin/apps/AppMenu.js
  client/admin/apps/AppProvider.tsx
  client/admin/apps/AppSettings.js
  client/admin/apps/AppStatus.js
  client/admin/apps/AppsPage.js
  client/admin/apps/AppsRoute.js
  client/admin/apps/AppsTable.js
  client/admin/apps/AppsWhatIsIt.js
  client/admin/apps/CloudLoginModal.js
  client/admin/apps/IframeModal.js
  client/admin/apps/MarketplacePage.js
  client/admin/apps/MarketplaceTable.js
  client/admin/apps/PriceDisplay.js
  client/admin/apps/WarningModal.js
  client/admin/apps/helpers.js
  client/admin/apps/hooks/useAppInfo.js
  client/admin/apps/hooks/useFilteredApps.js
  client/admin/routes.js
  client/admin/sidebarItems.js
  client/components/GenericTable.js
  client/components/ModalPortal.tsx
  client/components/basic/ExternalLink.js
  client/components/basic/Modal.js
  client/components/basic/avatar/AppAvatar.js
  client/contexts/ModalContext.ts
  client/hooks/useFileInput.js
  client/hooks/useResizeInlineBreakpoint.js
  client/providers/ModalProvider.js
  client/providers/ServerProvider.js
  package-lock.json
  package.json
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux, type: improvement

#17783 [NEW] Add ability to block failed login attempts by user and IP
  app/authentication/server/ILoginAttempt.ts
  app/authentication/server/hooks/login.ts
  app/authentication/server/index.ts
  app/authentication/server/lib/logLoginAttempts.ts
  app/authentication/server/lib/restrictLoginAttempts.ts
  app/authentication/server/startup/index.js
  app/authentication/server/startup/settings.ts
  app/models/server/models/ServerEvents.ts
  app/models/server/models/Sessions.js
  app/models/server/raw/ServerEvents.ts
  app/models/server/raw/Sessions.js
  app/models/server/raw/Users.js
  app/models/server/raw/index.ts
  app/ui-login/client/login/form.js
  app/utils/lib/date.helper.ts
  definition/IServerEvent.ts
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/importPackages.js
  server/main.js
  server/startup/migrations/v152.js
Labels: feat: accounts

#17774 [NEW] Allows agents to send chat transcript to omnichannel end-users
  app/authorization/server/startup.js
  app/livechat/client/views/app/tabbar/visitorInfo.html
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/client/views/app/tabbar/visitorTranscript.html
  app/livechat/client/views/app/tabbar/visitorTranscript.js
  app/livechat/client/views/regular.js
  app/livechat/lib/messageTypes.js
  app/livechat/server/hooks/sendTranscriptOnClose.js
  app/livechat/server/index.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/methods/discardTranscript.js
  app/livechat/server/methods/requestTranscript.js
  app/livechat/server/methods/sendTranscript.js
  app/models/server/models/LivechatRooms.js
  app/models/server/models/Messages.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/publications/room/index.js
Labels: feat: omnichannel

#17824 [IMPROVE] Refactor Omnichannel Office Hours feature
  app/authorization/server/startup.js
  app/livechat/client/collections/livechatOfficeHour.js
  app/livechat/client/route.js
  app/livechat/client/views/admin.js
  app/livechat/client/views/app/business-hours/BusinessHours.ts
  app/livechat/client/views/app/business-hours/IBusinessHour.ts
  app/livechat/client/views/app/business-hours/Single.ts
  app/livechat/client/views/app/business-hours/livechatBusinessHoursForm.html
  app/livechat/client/views/app/business-hours/livechatBusinessHoursForm.js
  app/livechat/client/views/app/business-hours/livechatMainBusinessHours.html
  app/livechat/client/views/app/business-hours/livechatMainBusinessHours.js
  app/livechat/client/views/app/livechatOfficeHours.html
  app/livechat/client/views/app/livechatOfficeHours.js
  app/livechat/client/views/sideNav/livechatSideNavItems.js
  app/livechat/imports/server/rest/businessHours.js
  app/livechat/imports/server/rest/officeHour.js
  app/livechat/server/api.js
  app/livechat/server/api/lib/businessHours.ts
  app/livechat/server/api/lib/officeHour.js
  app/livechat/server/business-hour/AbstractBusinessHour.ts
  app/livechat/server/business-hour/BusinessHourManager.ts
  app/livechat/server/business-hour/Single.ts
  app/livechat/server/business-hour/index.ts
  app/livechat/server/config.js
  app/livechat/server/hooks/processRoomAbandonment.js
  app/livechat/server/index.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/OfficeClock.js
  app/livechat/server/methods/changeLivechatStatus.js
  app/livechat/server/methods/saveBusinessHour.ts
  app/livechat/server/methods/saveOfficeHours.js
  app/livechat/server/startup.js
  app/models/server/index.js
  app/models/server/models/LivechatBusinessHours.ts
  app/models/server/models/LivechatOfficeHour.js
  app/models/server/raw/LivechatBusinessHours.ts
  app/models/server/raw/LivechatOfficeHour.js
  app/models/server/raw/Users.js
  app/models/server/raw/index.ts
  app/settings/server/functions/settings.ts
  app/utils/server/lib/cron/Cronjobs.ts
  definition/ILivechatBusinessHour.ts
  ee/app/livechat-enterprise/server/permissions.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v195.js
  tests/end-to-end/api/livechat/office-hour.js
  tsconfig.json
Labels: type: improvement

#17947 [NEW][ENTERPRISE] Omnichannel multiple business hours
  app/livechat/client/route.js
  app/livechat/client/views/app/business-hours/BusinessHours.ts
  app/livechat/client/views/app/business-hours/IBusinessHour.ts
  app/livechat/client/views/app/business-hours/Single.ts
  app/livechat/client/views/app/business-hours/livechatBusinessHoursForm.html
  app/livechat/client/views/app/business-hours/livechatBusinessHoursForm.js
  app/livechat/client/views/app/business-hours/livechatMainBusinessHours.html
  app/livechat/client/views/app/customTemplates/register.js
  app/livechat/server/business-hour/AbstractBusinessHour.ts
  app/livechat/server/business-hour/BusinessHourManager.ts
  app/livechat/server/business-hour/Single.ts
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/startup.js
  app/models/server/models/LivechatBusinessHours.ts
  app/models/server/models/LivechatDepartment.js
  app/models/server/models/LivechatDepartmentAgents.js
  app/models/server/raw/BaseRaw.js
  app/models/server/raw/LivechatBusinessHours.ts
  app/models/server/raw/LivechatDepartment.js
  app/models/server/raw/LivechatDepartmentAgents.js
  app/models/server/raw/Users.js
  definition/ILivechatBusinessHour.ts
  definition/ILivechatDepartment.ts
  ee/app/livechat-enterprise/client/index.js
  ee/app/livechat-enterprise/client/route.js
  ee/app/livechat-enterprise/client/startup.ts
  ee/app/livechat-enterprise/client/views/app/customTemplates/businessHoursCustomFieldsForm.html
  ee/app/livechat-enterprise/client/views/app/customTemplates/businessHoursCustomFieldsForm.js
  ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.html
  ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.js
  ee/app/livechat-enterprise/client/views/app/registerCustomTemplates.js
  ee/app/livechat-enterprise/client/views/business-hours/Multiple.ts
  ee/app/livechat-enterprise/client/views/business-hours/livechatBusinessHours.html
  ee/app/livechat-enterprise/client/views/business-hours/livechatBusinessHours.js
  ee/app/livechat-enterprise/server/api/business-hours.ts
  ee/app/livechat-enterprise/server/api/index.js
  ee/app/livechat-enterprise/server/api/lib/definition.ts
  ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  ee/app/livechat-enterprise/server/business-hour/lib/business-hour.ts
  ee/app/livechat-enterprise/server/hooks/afterRemoveDepartment.js
  ee/app/livechat-enterprise/server/hooks/index.js
  ee/app/livechat-enterprise/server/hooks/onBusinessHourStart.ts
  ee/app/livechat-enterprise/server/hooks/onChangeAgentDepartment.ts
  ee/app/livechat-enterprise/server/index.js
  ee/app/livechat-enterprise/server/methods/removeBusinessHour.ts
  ee/app/livechat-enterprise/server/settings.js
  ee/app/livechat-enterprise/server/startup.js
  ee/app/models/server/raw/LivechatDepartmentAgents.ts
  ee/i18n/en.i18n.json
  ee/i18n/pt-BR.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v196.js
Labels: feat: enterprise, feat: omnichannel

#18003 Remove useLazyRef hook usage
  client/fuselage-hooks.d.ts
  client/providers/EditableSettingsProvider.tsx
Labels: subj: ui/ux, type: improvement

#18037 Regression: Repair CodeMirror component reactivity
  client/admin/settings/inputs/CodeSettingInput.js
Labels: subj: ui/ux, type: bug

#18007 Regression: Reset section button
  client/admin/settings/Section.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux

#18050 Regression: Improve Omnichannel Business Hours
  app/livechat/client/views/app/business-hours/BusinessHours.ts
  app/livechat/client/views/app/business-hours/IBusinessHour.ts
  app/livechat/client/views/app/business-hours/IBusinessHourBehavior.ts
  app/livechat/client/views/app/business-hours/Single.ts
  app/livechat/client/views/app/business-hours/livechatBusinessHoursForm.html
  app/livechat/client/views/app/business-hours/livechatBusinessHoursForm.js
  app/livechat/imports/server/rest/businessHours.js
  app/livechat/server/api/lib/businessHours.ts
  app/livechat/server/business-hour/AbstractBusinessHour.ts
  app/livechat/server/business-hour/BusinessHourManager.ts
  app/livechat/server/business-hour/Default.ts
  app/livechat/server/business-hour/Helper.ts
  app/livechat/server/business-hour/Single.ts
  app/livechat/server/business-hour/index.ts
  app/livechat/server/hooks/processRoomAbandonment.js
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/startup.js
  app/models/server/models/LivechatBusinessHours.ts
  app/models/server/models/LivechatDepartment.js
  app/models/server/models/Users.js
  app/models/server/raw/LivechatBusinessHours.ts
  app/models/server/raw/LivechatDepartment.js
  app/models/server/raw/Users.js
  definition/ILivechatBusinessHour.ts
  ee/app/livechat-enterprise/client/SingleBusinessHour.ts
  ee/app/livechat-enterprise/client/route.js
  ee/app/livechat-enterprise/client/startup.ts
  ee/app/livechat-enterprise/client/views/app/customTemplates/businessHoursCustomFieldsForm.html
  ee/app/livechat-enterprise/client/views/app/customTemplates/businessHoursCustomFieldsForm.js
  ee/app/livechat-enterprise/client/views/app/customTemplates/businessHoursFormField.js
  ee/app/livechat-enterprise/client/views/app/customTemplates/businessHoursTimezoneFormField.html
  ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.js
  ee/app/livechat-enterprise/client/views/app/registerCustomTemplates.js
  ee/app/livechat-enterprise/client/views/business-hours/Multiple.ts
  ee/app/livechat-enterprise/client/views/business-hours/livechatBusinessHours.js
  ee/app/livechat-enterprise/server/api/business-hours.ts
  ee/app/livechat-enterprise/server/business-hour/Custom.ts
  ee/app/livechat-enterprise/server/business-hour/Helper.ts
  ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  ee/app/livechat-enterprise/server/business-hour/index.ts
  ee/app/livechat-enterprise/server/hooks/afterRemoveDepartment.js
  ee/app/livechat-enterprise/server/hooks/index.js
  ee/app/livechat-enterprise/server/hooks/onBusinessHourStart.ts
  ee/app/livechat-enterprise/server/hooks/onChangeAgentDepartment.ts
  ee/app/livechat-enterprise/server/index.js
  ee/app/livechat-enterprise/server/methods/removeBusinessHour.ts
  ee/app/livechat-enterprise/server/startup.js
  ee/app/models/server/raw/LivechatDepartmentAgents.ts
  package-lock.json
  package.json
  server/main.d.ts
  server/startup/migrations/index.js
  server/startup/migrations/v195.js
  server/startup/migrations/v197.js
  typings.d.ts
Labels: feat: omnichannel

#18074 Regression: Infinite render loop on Setup Wizard
  client/views/setupWizard/steps/SettingsBasedStep.js
Labels: subj: ui/ux, type: bug

#18070 Upgrade Livechat Widget version to 1.6.0
  package-lock.json
  package.json
Labels: feat: livechat
