Repository RocketChat/Rocket.Chat, pull requests merged in 2020-05, with the labels that each got.

#17419 [FIX] Replace obsolete X-FRAME-OPTIONS header on Livechat route
  app/livechat/server/livechat.js
Labels: feat: livechat, feat: omnichannel

#17429 [NEW] Add Livechat website URL to the offline message e-mail
  app/livechat/server/api/v1/offlineMessage.js
  app/livechat/server/lib/Livechat.js
Labels: feat: livechat, feat: omnichannel

#17442 [NEW] Add the ability to send Livechat offline messages to a channel
  app/livechat/client/views/app/livechatDepartmentForm.html
  app/livechat/client/views/app/livechatDepartmentForm.js
  app/livechat/server/config.js
  app/livechat/server/hooks/offlineMessageToChannel.js
  app/livechat/server/index.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: omnichannel

#17463 [NEW] Allow filtering Omnichannel analytics dashboards by department
  app/livechat/client/stylesheets/livechat.css
  app/livechat/client/views/app/analytics/livechatAnalytics.html
  app/livechat/client/views/app/analytics/livechatAnalytics.js
  app/livechat/client/views/app/analytics/livechatRealTimeMonitoring.html
  app/livechat/client/views/app/analytics/livechatRealTimeMonitoring.js
  app/livechat/imports/server/rest/dashboards.js
  app/livechat/server/lib/Analytics.js
  app/livechat/server/lib/analytics/dashboards.js
  app/models/server/models/LivechatRooms.js
  app/models/server/raw/LivechatAgentActivity.js
  app/models/server/raw/LivechatRooms.js
  app/models/server/raw/LivechatVisitors.js
  app/models/server/raw/Users.js
Labels: feat: omnichannel

#17387 [BREAK] Remove deprecated Omnichannel Knowledge Base feature
  app/livechat/client/ui.js
  app/livechat/client/views/app/tabbar/externalSearch.html
  app/livechat/client/views/app/tabbar/externalSearch.js
  app/livechat/client/views/regular.js
  app/livechat/server/config.js
  app/livechat/server/hooks/externalMessage.js
  app/livechat/server/index.js
  server/startup/migrations/index.js
  server/startup/migrations/v189.js
Labels: documentation: needed, feat: omnichannel

#17503 [IMPROVE] Add new webhooks to the Omnichannel integration feature
  app/livechat/client/views/app/integrations/livechatIntegrationWebhook.html
  app/livechat/client/views/app/integrations/livechatIntegrationWebhook.js
  app/livechat/server/api/lib/integrations.js
  app/livechat/server/config.js
  app/livechat/server/hooks/sendToCRM.js
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/QueueManager.js
  app/livechat/server/methods/saveIntegration.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: type: improvement

#15929 [FIX] Replace postcss Meteor package
  .meteor/packages
  .meteor/versions
  package-lock.json
  package.json
  packages/rocketchat-postcss/.gitignore
  packages/rocketchat-postcss/build.js
  packages/rocketchat-postcss/package.js
Labels: subj: ui/ux, type: bug

#17541 [FIX] Invalid CSS syntax
  app/theme/client/imports/general/forms.css
  package-lock.json
Labels: type: bug

#17553 [FIX] Omnichannel departments are not saved when the offline channel name is not defined
  app/livechat/client/views/app/livechatDepartmentForm.js
Labels: type: bug

#17577 [FIX] Error during data export for DMs
  app/user-data-download/server/cronProcessDownloads.js
Labels: type: bug

#16862 [FIX] Unread bottom, top bars on sidebar (#16853)
  app/theme/client/imports/components/sidebar/sidebar.css
  app/ui-utils/client/lib/RoomManager.js
  app/ui-utils/client/lib/menu.js
Labels: subj: ui/ux

#15642 [FIX] Do not allow passwords on private channels
  app/channel-settings/client/views/channelSettings.html
Labels: subj: ui/ux

#17567 [NEW] Add permissions to deal with Omnichannel custom fields
  app/authorization/server/startup.js
  app/livechat/client/views/app/tabbar/visitorEdit.html
  app/livechat/client/views/app/tabbar/visitorEdit.js
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/methods/saveInfo.js
  ee/app/livechat-enterprise/server/permissions.js
Labels: feat: omnichannel

#17580 [NEW] Add Permissions to deal with Omnichannel visitor past chats history
  app/authorization/server/startup.js
  app/livechat/server/startup.js
  app/models/server/models/LivechatDepartmentAgents.js
  ee/app/livechat-enterprise/server/permissions.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: omnichannel

#16480 Use Users.findOneByAppId instead of querying directly
  app/apps/server/bridges/users.js
Labels: feat: apps

#17554 [IMPROVE] Unused styles
  .postcssrc
  .storybook/mocks/decorators.js
  app/apps/client/admin/appManage.html
  app/autotranslate/client/views/autoTranslateFlexTab.html
  app/chatpal-search/client/template/admin.html
  app/integrations/client/views/integrationsIncoming.html
  app/integrations/client/views/integrationsOutgoing.html
  app/integrations/client/views/integrationsOutgoingHistory.html
  app/livechat/client/views/app/integrations/livechatIntegrationFacebook.html
  app/livechat/client/views/app/livechatAgents.html
  app/livechat/client/views/app/livechatManagers.html
  app/livechat/client/views/app/livechatQueue.html
  app/livechat/client/views/app/tabbar/visitorInfo.html
  app/models/server/models/Settings.js
  app/oauth2-server-config/client/admin/views/oauthApp.html
  app/oauth2-server-config/client/oauth/oauth2-client.html
  app/otr/client/rocketchat.otr.room.js
  app/otr/client/stylesheets/otr.css
  app/otr/client/views/otrFlexTab.html
  app/theme/client/imports/general/base.css
  app/theme/client/imports/general/base_old.css
  app/theme/client/imports/general/forms.css
  app/theme/client/imports/general/rtl.css
  app/theme/client/imports/general/theme_old.css
  app/theme/client/imports/general/variables.css
  app/theme/client/main.css
  app/theme/server/server.js
  app/theme/server/variables.js
  app/tokenpass/client/tokenpassChannelSettings.html
  app/ui-account/client/accountProfile.html
  app/ui-account/client/avatar/prompt.html
  app/ui-flextab/client/tabs/userInfo.html
  app/ui-login/client/login/services.html
  app/ui-login/client/login/social.html
  app/ui-login/client/reset-password/resetPassword.html
  app/ui-master/.eslintrc
  app/ui-master/client/main.html
  app/ui-master/client/main.js
  app/ui-master/server/inject.js
  app/ui-message/client/message.html
  app/ui-sidenav/client/index.js
  app/ui-sidenav/client/toolbar.js
  app/ui-sidenav/client/userStatus.html
  app/ui/client/views/app/room.js
  app/ui/client/views/app/videoCall/videoButtons.html
  client/main.js
  client/polyfills/cssVars.js
  client/polyfills/index.js
  client/startup/theme.js
  ee/app/livechat-enterprise/client/views/livechatMonitors.html
  ee/app/livechat-enterprise/client/views/livechatUnitForm.html
  imports/client/mimic-fn
  imports/client/mimic-fn/index.js
  package-lock.json
  private/client/imports/general/variables.css
  private/server/colors.less
  private/server/dynamic-css.js
  tests/cypress/integration/04-main-elements-render.js
  tests/cypress/integration/12-settings.js
  tests/cypress/pageobjects/main-content.page.js
Labels: subj: ui/ux, type: improvement

#17640 [FIX] Agent's custom fields being leaked through the Livechat configuration endpoint
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
Labels: subj: security

#17610 Remove index files from api, bigbluebutton and bot-helpers
  app/api/index.js
  app/bigbluebutton/index.js
  app/bigbluebutton/server/index.js
  app/bot-helpers/index.js
  app/integrations/server/api/api.js
  app/livechat/imports/server/rest/agent.js
  app/livechat/imports/server/rest/appearance.js
  app/livechat/imports/server/rest/dashboards.js
  app/livechat/imports/server/rest/departments.js
  app/livechat/imports/server/rest/facebook.js
  app/livechat/imports/server/rest/inquiries.js
  app/livechat/imports/server/rest/integrations.js
  app/livechat/imports/server/rest/messages.js
  app/livechat/imports/server/rest/officeHour.js
  app/livechat/imports/server/rest/queue.js
  app/livechat/imports/server/rest/rooms.js
  app/livechat/imports/server/rest/sms.js
  app/livechat/imports/server/rest/triggers.js
  app/livechat/imports/server/rest/upload.js
  app/livechat/imports/server/rest/users.js
  app/livechat/imports/server/rest/visitors.js
  app/livechat/server/api/v1/agent.js
  app/livechat/server/api/v1/config.js
  app/livechat/server/api/v1/customField.js
  app/livechat/server/api/v1/message.js
  app/livechat/server/api/v1/offlineMessage.js
  app/livechat/server/api/v1/pageVisited.js
  app/livechat/server/api/v1/room.js
  app/livechat/server/api/v1/transcript.js
  app/livechat/server/api/v1/videoCall.js
  app/livechat/server/api/v1/visitor.js
  app/livestream/server/routes.js
  app/oauth2-server-config/server/oauth/oauth2-server.js
  app/videobridge/server/methods/bbb.js
  ee/app/api-enterprise/server/canned-responses.js
  ee/app/engagement-dashboard/server/api/channels.js
  ee/app/engagement-dashboard/server/api/messages.js
  ee/app/engagement-dashboard/server/api/users.js
  ee/app/livechat/imports/server/rest/departments.js
  ee/app/livechat/imports/server/rest/inquiries.js
  ee/app/livechat/imports/server/rest/rooms.js
  ee/app/livechat/imports/server/rest/sms.js
  ee/app/livechat/imports/server/rest/upload.js
  server/importPackages.js
Labels: type: improvement

#17522 [FIX] Default filters on Omnichannel Current Chats screen not showing on first load
  app/livechat/client/views/app/livechatCurrentChats.js
Labels: type: bug

#17701 [IMPROVE] Display status information in the Omnichannel Agents list
  app/livechat/client/views/app/livechatAgents.html
  app/livechat/client/views/app/livechatAgents.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: feat: omnichannel

#17694 [NEW] API endpoint to fetch Omnichannel's room transfer history
  app/livechat/server/api/lib/transfer.js
  app/livechat/server/api/rest.js
  app/livechat/server/api/v1/transfer.js
Labels: feat: omnichannel

#17666 [NEW][ENTERPRISE] Omnichannel Last-Chatted Agent Preferred option
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/RoutingManager.js
  app/models/server/models/LivechatInquiry.js
  app/models/server/models/LivechatRooms.js
  app/models/server/models/LivechatVisitors.js
  app/models/server/models/Rooms.js
  app/models/server/models/Users.js
  ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.js
  ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.js
  ee/app/livechat-enterprise/server/hooks/handleLastChattedAgentPreferredEvents.js
  ee/app/livechat-enterprise/server/index.js
  ee/app/livechat-enterprise/server/lib/Helper.js
  ee/app/livechat-enterprise/server/settings.js
  ee/i18n/en.i18n.json
  ee/i18n/pt-BR.i18n.json
Labels: feat: omnichannel
