Repository RocketChat/Rocket.Chat, pull requests merged in 2020-01, with the labels that each got.

#16085 [FIX] Login change language button
  app/ui-login/client/login/footer.js
Labels: subj: ui/ux

#16083 [FIX] Thread message icon overlapping text
  app/theme/client/imports/general/base_old.css
  app/ui-message/client/messageThread.html
Labels: subj: ui/ux

#16064 [NEW] Setting Top navbar in embedded mode
  app/lib/server/startup/settings.js
  app/ui/client/views/app/room.html
  app/ui/client/views/app/room.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: Contain documentation PR, subj: ui/ux

#16051 [FIX] Embedded style when using 'go' command
  app/ui/client/lib/iframeCommands.js
Labels: subj: ui/ux

#16047 [FIX] "User not found" for direct messages
  app/ui/client/views/404/roomNotFound.html
  app/ui/client/views/404/roomNotFound.js
Labels: subj: ui/ux

#16113 [FIX] Video message sent to wrong room
  app/ui-vrecord/client/VRecDialog.js
  app/ui-vrecord/client/vrecord.js
Labels: subj: ui/ux

#16049 [FIX] Drag and drop disabled when file upload is disabled
  app/theme/client/imports/general/base_old.css
  app/threads/client/flextab/thread.html
  app/threads/client/flextab/thread.js
  app/ui/client/views/app/room.html
  app/ui/client/views/app/room.js
Labels: subj: ui/ux

#16139 [FIX] Resolving console errors Administration
  client/components/admin/settings/GroupPage.js
Labels: subj: ui/ux, type: bug

#16071 [IMPROVE] Remove NRR
  app/discussion/client/views/DiscussionTabbar.html
  app/discussion/client/views/DiscussionTabbar.js
  app/integrations/client/views/integrationsIncoming.html
  app/integrations/client/views/integrationsOutgoing.html
  app/lazy-load/client/index.js
  app/mentions-flextab/client/views/mentionsFlexTab.html
  app/message-attachments/client/messageAttachment.html
  app/message-attachments/client/messageAttachment.js
  app/message-pin/client/views/pinnedMessages.html
  app/message-pin/client/views/pinnedMessages.js
  app/message-snippet/client/tabBar/views/snippetedMessages.html
  app/message-snippet/client/tabBar/views/snippetedMessages.js
  app/message-star/client/views/starredMessages.html
  app/message-star/client/views/starredMessages.js
  app/nrr/client/nrr.js
  app/search/client/provider/result.html
  app/search/client/provider/result.js
  app/theme/client/imports/general/base_old.css
  app/threads/client/flextab/thread.js
  app/threads/client/flextab/threads.js
  app/ui-account/client/avatar/avatar.html
  app/ui-message/client/message.html
  app/ui-message/client/message.js
  app/ui-message/client/popup/messagePopup.js
  app/ui-sidenav/client/sideNav.js
  app/ui-utils/client/lib/RoomHistoryManager.js
  app/ui-utils/client/lib/RoomManager.js
  app/ui-utils/client/lib/menu.js
  app/ui/client/views/app/room.html
  app/ui/client/views/app/room.js
  package-lock.json
  tests/pageobjects/main-content.page.js
Labels: subj: ui/ux

#15913 [IMPROVE] Set the color of the cancel button on modals to #bdbebf for enhanced visibiity
  app/theme/client/imports/components/modal.css
  app/ui-utils/client/lib/modal.html
Labels: design, subj: ui/ux, type: improvement

#15840 [NEW] Add GUI for customFields in Omnichannel conversations
  app/livechat/client/views/app/livechatCustomFieldForm.html
  app/livechat/client/views/app/livechatCustomFieldForm.js
  app/livechat/client/views/app/tabbar/visitorEdit.html
  app/livechat/client/views/app/tabbar/visitorEdit.js
  app/livechat/client/views/app/tabbar/visitorInfo.html
  app/livechat/client/views/app/tabbar/visitorInfo.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/methods/saveCustomField.js
  app/livechat/server/methods/saveInfo.js
  app/models/server/models/LivechatRooms.js
  app/models/server/models/LivechatVisitors.js
  app/theme/client/imports/general/base_old.css
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: livechat, type: improvement

#16181 [IMPROVE] Improve function to check if setting has changed
  client/components/admin/settings/Setting.js
  client/components/admin/settings/SettingsState.js
Labels: subj: ui/ux

#16234 [FIX] FileUpload.getBuffer was not working through the Apps-Engine
  app/apps/server/bridges/uploads.js
Labels: type: bug

#16147 [FIX] Setup Wizard inputs and Admin Settings
  client/components/admin/info/DescriptionList.stories.js
  client/components/admin/info/InformationPage.js
  client/components/admin/settings/GroupPage.js
  client/components/admin/settings/GroupPage.stories.js
  client/components/admin/settings/GroupSelector.js
  client/components/admin/settings/NotAuthorizedPage.js
  client/components/admin/settings/ResetSettingButton.js
  client/components/admin/settings/Section.js
  client/components/admin/settings/Setting.js
  client/components/admin/settings/Setting.stories.js
  client/components/admin/settings/SettingsState.js
  client/components/admin/settings/groups/AssetsGroupPage.js
  client/components/admin/settings/groups/GenericGroupPage.js
  client/components/admin/settings/groups/OAuthGroupPage.js
  client/components/admin/settings/inputs/ActionSettingInput.js
  client/components/admin/settings/inputs/AssetSettingInput.js
  client/components/admin/settings/inputs/AssetSettingInput.stories.js
  client/components/admin/settings/inputs/BooleanSettingInput.js
  client/components/admin/settings/inputs/CodeSettingInput.js
  client/components/admin/settings/inputs/CodeSettingInput.stories.js
  client/components/admin/settings/inputs/ColorSettingInput.js
  client/components/admin/settings/inputs/FontSettingInput.js
  client/components/admin/settings/inputs/GenericSettingInput.js
  client/components/admin/settings/inputs/IntSettingInput.js
  client/components/admin/settings/inputs/LanguageSettingInput.js
  client/components/admin/settings/inputs/PasswordSettingInput.js
  client/components/admin/settings/inputs/RelativeUrlSettingInput.js
  client/components/admin/settings/inputs/RoomPickSettingInput.js
  client/components/admin/settings/inputs/SelectSettingInput.js
  client/components/admin/settings/inputs/StringSettingInput.js
  client/components/basic/BurgerMenuButton.css
  client/components/basic/BurgerMenuButton.js
  client/components/basic/BurgerMenuButton.stories.js
  client/components/basic/Page.js
  client/components/basic/Page.stories.js
  client/components/header/Header.js
  client/components/header/Header.stories.js
  client/components/pageNotFound/PageNotFound.js
  client/components/setupWizard/SetupWizardPage.js
  client/components/setupWizard/SideBar.js
  client/components/setupWizard/steps/AdminUserInformationStep.js
  client/components/setupWizard/steps/FinalStep.js
  client/components/setupWizard/steps/RegisterServerStep.js
  client/components/setupWizard/steps/SettingsBasedStep.js
  package-lock.json
  package.json
  tests/end-to-end/ui/11-admin.js
Labels: subj: ui/ux, type: bug

#16233 [FIX] Integrations list without pagination and outgoing integration creation
  app/integrations/client/views/integrations.js
  app/integrations/client/views/integrationsOutgoing.js
Labels: type: improvement

#15896 [NEW] Create a user for the Apps during installation
  app/apps/client/admin/appInstall.js
  app/apps/server/bridges/users.js
  app/apps/server/communication/rest.js
  app/apps/server/converters/users.js
  app/authorization/server/startup.js
  app/lib/server/functions/deleteUser.js
  app/models/server/models/Users.js
  app/models/server/raw/BaseRaw.js
  app/ui-login/client/login/form.js
  app/ui/client/views/app/directory.js
  package-lock.json
  package.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/zh.i18n.json
  server/lib/accounts.js
Labels: feat: apps

#16356 [FIX] Role tags missing - Description field explanation
  app/authorization/client/views/permissionsRole.html
  app/theme/client/imports/general/base_old.css
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux

#16373 [IMPROVE] Prevent "App user" from being deleted by the admin
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/zh.i18n.json
  server/methods/deleteUser.js
Labels: feat: apps

#16388 [FIX] Container heights
  app/theme/client/imports/general/base.css
Labels: subj: ui/ux

#16397 [FIX] Rooms not being marked as read sometimes
  app/ui-utils/client/lib/readMessages.js
  app/ui/client/lib/chatMessages.js
  app/ui/client/views/app/room.js
  client/startup/startup.js
Labels: subj: ui/ux

#16395 Revert message properties validation
  app/apps/server/bridges/messages.js
  app/lib/server/functions/sendMessage.js
  app/lib/server/methods/sendMessage.js
  tests/end-to-end/api/05-chat.js
Labels: type: regression
