Repository RocketChat/Rocket.Chat, pull requests merged in 2020-07, with the labels that each got.

#18102 [FIX] Omnichannel close room callback returning promise
  app/livechat/server/lib/Livechat.js
Labels: type: bug

#18080 [FIX] App details returns to apps table, instead of previous page.
  client/admin/apps/AppDetailsPage.js
Labels: feat: apps, subj: ui/ux, type: bug

#18226 Update the API of React Hooks using Meteor's reactive system
  .eslintrc
  app/threads/client/components/hooks/useUserRoom.js
  app/threads/client/components/hooks/useUserSubscription.js
  client/admin/integrations/IntegrationsRoute.js
  client/admin/sidebar/AdminSidebar.js
  client/components/RoomForeword.js
  client/contexts/AuthorizationContext.js
  client/contexts/AuthorizationContext.ts
  client/contexts/SessionContext.js
  client/contexts/SessionContext.ts
  client/contexts/UserContext.js
  client/contexts/UserContext.ts
  client/hooks/useForm.js
  client/hooks/useForm.ts
  client/hooks/useObservableValue.js
  client/hooks/useQuery.ts
  client/hooks/useReactiveSubscriptionFactory.ts
  client/hooks/useReactiveValue.js
  client/hooks/useReactiveValue.ts
  client/providers/AuthorizationProvider.js
  client/providers/AuthorizationProvider.tsx
  client/providers/ConnectionStatusProvider.js
  client/providers/EditableSettingsProvider.tsx
  client/providers/MeteorProvider.js
  client/providers/SessionProvider.js
  client/providers/SessionProvider.tsx
  client/providers/SettingsProvider.tsx
  client/providers/SidebarProvider.js
  client/providers/TranslationProvider.js
  client/providers/UserProvider.js
  client/providers/UserProvider.tsx
  client/providers/createObservableFromReactive.js
  client/providers/createReactiveSubscriptionFactory.ts
Labels: subj: ui/ux, type: improvement

#18240 [FIX]Update link URL at AppsWhatIsIt
  client/admin/apps/AppsWhatIsIt.js
Labels: feat: apps, subj: ui/ux, type: documentation

#18244 Regression: Remove calls to Console API in useForm hook
  client/hooks/useForm.ts
Labels: subj: ui/ux, type: regression

#18076 Account Profile rewritten
  app/threads/client/components/ThreadListMessage.js
  app/ui-account/client/account.html
  app/ui-account/client/account.js
  app/ui-account/client/accountProfile.html
  app/ui-account/client/accountProfile.js
  app/ui-account/client/index.js
  client/account/AccountProfileForm.js
  client/account/AccountProfilePage.js
  client/account/AccountRoute.js
  client/admin/users/EditUser.js
  client/admin/users/UserForm.js
  client/admin/users/UserInfo.js
  client/admin/users/UserInfoActions.js
  client/admin/users/UsersTable.js
  client/components/ConfirmOwnerChangeWarningModal.js
  client/components/CustomFieldsForm.js
  client/components/basic/avatar/UserAvatar.js
  client/components/basic/avatar/UserAvatarEditor.js
  client/components/basic/userStatus/UserStatus.js
  client/components/basic/userStatus/UserStatusMenu.js
  client/helpers/getUserEmailAddress.js
  client/helpers/statusColors.js
  client/hooks/useUpdateAvatar.js
  client/routes.js
  client/views/directory/UserTab.js
Labels: subj: ui/ux, type: improvement

#18151 [NEW] Account Preferences rewritten
  app/ui-account/client/accountPreferences.html
  app/ui-account/client/accountPreferences.js
  app/ui-account/client/index.js
  client/account/AccountRoute.js
  client/account/preferences/AccountPreferencesPage.js
  client/account/preferences/PreferencesGlobalSection.js
  client/account/preferences/PreferencesHighlightsSection.js
  client/account/preferences/PreferencesLocalizationSection.js
  client/account/preferences/PreferencesMessagesSection.js
  client/account/preferences/PreferencesMyDataSection.js
  client/account/preferences/PreferencesNotificationsSection.js
  client/account/preferences/PreferencesSoundSection.js
  client/account/preferences/PreferencesUserPresenceSection.js
Labels: subj: ui/ux, type: improvement

#18277 [NEW] External MP3 encoder worker for audio recording
  .eslintignore
  app/ui/client/lib/recorderjs/audioEncoder.js
  package-lock.json
  package.json
  public/lame.min.js
  public/mp3-realtime-worker.js
  public/workers/mp3-encoder/index.js
  public/workers/mp3-encoder/index.js.map
Labels: subj: ui/ux, type: improvement

#18206 [NEW] Personal Access Tokens rewritten
  client/account/AccountProfilePage.js
  client/account/AccountRoute.js
  client/account/preferences/PreferencesMyDataSection.js
  client/account/tokens/AccountTokensPage.js
  client/account/tokens/AccountTokensTable.js
  client/account/tokens/AddToken.js
  client/account/tokens/InfoModal.js
  client/hooks/useEndpointDataExperimental.js
Labels: subj: ui/ux, type: improvement

#18290 Rewrite: My Account > Integrations rewritten
  app/ui-account/client/accountIntegrations.html
  app/ui-account/client/accountIntegrations.js
  app/ui-account/client/index.js
  client/account/AccountIntegrationsPage.js
  client/account/AccountRoute.js
Labels: subj: ui/ux, type: improvement

#18044 [FIX] Don't show agent info in the transcript if the setting is disabled
  app/livechat/server/lib/Livechat.js
Labels: feat: omnichannel

#18313 [FIX][ENTERPRISE] Canned Responses not available to agents after they are added to departments
  app/livechat/server/lib/Helper.js
  ee/app/canned-responses/client/startup/responses.js
  ee/app/canned-responses/server/hooks/onRemoveAgentDepartment.ts
  ee/app/canned-responses/server/hooks/onSaveAgentDepartment.ts
  ee/app/canned-responses/server/index.js
  ee/app/models/server/models/CannedResponse.js
Labels: feat: omnichannel, type: bug

#18315 [FIX] Error when fetching a nonexistent business hour from the server
  app/models/server/raw/BaseRaw.js
  app/models/server/raw/LivechatDepartment.js
  ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.html
  ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.js
  ee/app/livechat-enterprise/server/business-hour/Custom.ts
Labels: feat: omnichannel, type: bug

#17049 [IMPROVE] Improve performance and remove agents when the department is removed
  app/livechat/client/views/app/livechatDepartmentForm.html
  app/livechat/client/views/app/livechatDepartmentForm.js
  app/livechat/imports/server/rest/departments.js
  app/livechat/server/api/lib/agents.js
  app/livechat/server/api/lib/departments.js
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/methods/saveDepartment.js
  app/livechat/server/methods/saveDepartmentAgents.js
  app/models/server/models/LivechatDepartment.js
  app/models/server/models/LivechatDepartmentAgents.js
  app/models/server/raw/LivechatDepartmentAgents.js
  ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.js
  server/startup/migrations/index.js
  server/startup/migrations/v200.js
Labels: type: improvement

#18371 Regression: MP3 worker
  package-lock.json
  package.json
Labels: feat: message, type: regression

#18372 Regression: Wrong background in disabled inputs
  app/theme/client/imports/general/theme_old.css
Labels: subj: ui/ux, type: regression

#18375 Regression: Edit messages after opening thread
  app/threads/client/flextab/thread.js
Labels: feat: threads / discussions, subj: ui/ux, type: regression

#18369 Regression: Mentions in thread title
  app/threads/client/components/ThreadComponent.js
  app/threads/client/lib/normalizeThreadTitle.js
Labels: feat: threads / discussions, subj: ui/ux, type: bug, type: regression

#18378 Regression: Fix useUserSubscription usage
  client/channel/Discussions/ContextualBar/List.js
  client/channel/Threads/ContextualBar/List.js
  client/channel/hooks/useUserInfoActions.js
  client/contexts/SubscriptionContext.ts
  client/contexts/UserContext.ts
  client/providers/MeteorProvider.js
  client/providers/SubscriptionProvider.tsx
  client/providers/UserProvider.tsx
Labels: subj: ui/ux, type: regression

#18355 [FIX] Can't send long messages as attachment
  app/ui/client/lib/chatMessages.js
Labels: subj: ui/ux, type: bug

#18446 [FIX] Omnichannel Take Inquiry endpoint checking wrong permission
  app/livechat/imports/server/rest/inquiries.js
Labels: type: bug

#18428 [FIX] Error when updating omnichannel department without agents parameter
  app/livechat/server/lib/Helper.js
  app/livechat/server/lib/Livechat.js
Labels: type: bug

#18412 [FIX] Omnichannel session monitor is not starting
  app/livechat/server/lib/stream/agentStatus.ts
Labels: type: bug
