Repository RocketChat/Rocket.Chat, pull requests merged in 2020-10, with the labels that each got.

#19166 [FIX] Missing "Bio" in user's profile view (#18821)
  app/lib/server/functions/getFullUserData.js
Labels: subj: ui/ux, type: bug

#19134 [FIX] Omnichannel: triggers page not rendering.
  client/omnichannel/triggers/TriggersTable.js
Labels: subj: ui/ux, type: bug

#19101 [FIX] Admin Sidebar overflowing
  client/account/sidebarItems.js
  client/admin/sidebarItems.js
  client/components/basic/Sidebar.js
  client/omnichannel/routes.js
Labels: subj: ui/ux, type: bug

#19179 [FIX] Adding missing custom fields translation in my account's profile
  client/components/CustomFieldsForm.js
Labels: subj: ui/ux

#18929 [FIX] Wrong avatar urls when using providers
  app/lib/server/startup/settings.js
  app/utils/lib/getRoomAvatarURL.js
  client/components/basic/avatar/UserAvatar.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: user settings

#18272 [NEW] Reaction view
  app/ui-utils/client/lib/MessageAction.js
  app/ui-utils/client/lib/ReactionListContent.js
  app/ui/client/views/app/room.js
  client/components/basic/Emoji.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux, type: improvement

#19249 Reassessment of client helpers
  app/autolinker/client/client.js
  app/emoji-custom/client/lib/emojiCustom.js
  app/emoji/client/emojiPicker.js
  app/theme/client/index.js
  app/ui-flextab/client/tabs/uploadedFilesList.js
  app/ui-message/client/popup/messagePopupConfig.js
  app/ui-sidenav/client/toolbar.js
  client/account/AccountProfileForm.js
  client/account/AccountProfilePage.js
  client/account/sidebarItems.js
  client/admin/apps/AppSettings.js
  client/admin/info/InformationRoute.js
  client/admin/routes.js
  client/admin/sidebarItems.js
  client/admin/users/UsersTable.js
  client/components/CustomFieldsForm.js
  client/components/basic/userStatus/UserStatus.js
  client/helpers/capitalize.js
  client/helpers/createSidebarItems.js
  client/helpers/download.js
  client/helpers/getDateRange.js
  client/helpers/getUserEmailAddress.js
  client/hooks/useForm.ts
  client/lib/capitalize.spec.ts
  client/lib/capitalize.ts
  client/lib/createRouteGroup.ts
  client/lib/createSidebarItems.ts
  client/lib/download.spec.ts
  client/lib/download.ts
  client/lib/escapeRegExp.spec.ts
  client/lib/escapeRegExp.ts
  client/lib/getDateRange.ts
  client/lib/getUserEmailAddress.ts
  client/lib/saveFile.js
  client/lib/statusColors.ts
  client/lib/toastr.js
  client/lib/userData.js
  client/lib/userData.ts
  client/main.js
  client/omnichannel/agents/AgentEdit.js
  client/omnichannel/realTimeMonitoring/RealTimeMonitoringPage.js
  client/omnichannel/routes.js
  client/omnichannel/sidebarItems.js
  client/startup/startup.js
  ee/app/engagement-dashboard/client/components/ChannelsTab/TableSection.js
  ee/app/engagement-dashboard/client/components/MessagesTab/MessagesPerChannelSection.js
  ee/app/engagement-dashboard/client/components/MessagesTab/MessagesSentSection.js
  ee/app/engagement-dashboard/client/components/UsersTab/ActiveUsersSection.js
  ee/app/engagement-dashboard/client/components/UsersTab/NewUsersSection.js
  ee/app/engagement-dashboard/client/components/UsersTab/UsersByTimeOfTheDaySection.js
  mocha.opts.js
  package-lock.json
  package.json
Labels: subj: ui/ux, type: improvement

#19276 Remove legacy modal template
  app/theme/client/imports/components/modal/full-modal.css
  app/theme/client/imports/general/variables.css
  app/theme/client/main.css
  app/ui/client/index.js
  app/ui/client/views/app/fullModal.html
  app/ui/client/views/app/fullModal.js
Labels: subj: ui/ux, type: improvement

#19303 Non-idiomatic React code
  .eslintrc
  app/threads/client/components/ThreadComponent.js
  app/threads/client/components/ThreadSkeleton.tsx
  app/threads/client/components/ThreadView.tsx
  client/admin/apps/AppsContext.tsx
  client/admin/apps/AppsProvider.tsx
  client/admin/apps/AppsRoute.js
  client/admin/apps/AppsTable.js
  client/admin/apps/MarketplaceTable.js
  client/admin/apps/hooks/useAppInfo.js
  client/admin/apps/hooks/useAppInfo.ts
  client/admin/apps/hooks/useFilteredApps.js
  client/admin/apps/hooks/useFilteredApps.ts
  client/admin/customEmoji/CustomEmoji.js
  client/admin/customEmoji/CustomEmojiRoute.js
  client/admin/customEmoji/EditCustomEmoji.tsx
  client/admin/customEmoji/EditCustomEmojiWithData.tsx
  client/admin/customSounds/AdminSounds.js
  client/admin/customSounds/AdminSoundsRoute.js
  client/admin/customSounds/EditCustomSound.js
  client/admin/customUserStatus/CustomUserStatus.js
  client/admin/customUserStatus/CustomUserStatusRoute.js
  client/admin/customUserStatus/EditCustomUserStatus.js
  client/admin/customUserStatus/EditCustomUserStatusWithData.tsx
  client/admin/integrations/edit/EditIncomingWebhook.js
  client/admin/integrations/edit/EditOutgoingWebhook.js
  client/admin/integrations/new/NewIncomingWebhook.js
  client/admin/integrations/new/NewOutgoingWebhook.js
  client/admin/oauthApps/OAuthEditApp.js
  client/admin/users/AddUser.js
  client/admin/users/EditUser.js
  client/admin/users/UserInfoActions.js
  client/channel/Discussions/ContextualBar/List.js
  client/channel/Threads/ContextualBar/List.js
  client/channel/UserCard/index.js
  client/channel/UserInfo/actions/UserActions.js
  client/channel/hooks/useUserInfoActions.js
  client/components/CustomFieldsForm.js
  client/components/GenericTable/HeaderCell.tsx
  client/components/basic/PlanTag.js
  client/hooks/useComponentDidUpdate.js
  client/hooks/useFileInput.js
  client/hooks/useResizeInlineBreakpoint.js
  client/omnichannel/departments/DepartmentEdit.js
  client/types/fuselage.d.ts
  client/views/blocks/ModalBlock.js
  client/views/setupWizard/SetupWizardState.js
  ee/app/engagement-dashboard/client/components/MessagesTab/MessagesPerChannelSection.js
Labels: subj: ui/ux

#19316 [FIX] Message actions on top of text
  app/theme/client/imports/components/messages.css
Labels: subj: ui/ux

#19348 [FIX] Admin not working on IE11
  client/polyfills/index.js
Labels: subj: IE11

#19228 [NEW] [Apps] Add new typing bridge method (Typing-Indicator)
  app/apps/server/bridges/messages.js
Labels: feat: apps

#19379 [FIX] Omnichannel - typo error label at current chats page
  client/omnichannel/currentChats/CurrentChatsPage.js
Labels: type: bug

#19380 Regression: Pass `unset` parameter of updated `userData` notification
  client/lib/userData.ts
  definition/IUser.ts
Labels: type: regression

#19368 [NEW] Replace client-side event emitters
  app/apps/client/communication/websockets.js
  app/ui-cached-collection/client/models/CachedCollection.js
  app/ui-message/client/ActionManager.js
  app/ui-utils/client/lib/menu.js
  app/ui-utils/client/lib/readMessages.js
  app/ui/client/lib/menu.js
  app/ui/client/lib/recorderjs/audioEncoder.js
  app/webrtc/client/WebRTCClass.js
  client/contexts/AuthorizationContext.ts
  client/lib/presence.js
  client/sidebar/RoomList.js
  package-lock.json
  package.json
Labels: feat: apps

#19390 Regression: Thread component not updating its message list
  app/threads/client/components/ThreadComponent.tsx
  app/threads/client/components/ThreadView.tsx
  definition/IMessage.ts
  package-lock.json
Labels: feat: threads / discussions, type: regression

#19401 Regression: Room item menu display delay
  client/sidebar/Item/Condensed.js
  client/sidebar/Item/Extended.js
  client/sidebar/Item/Medium.js
  client/sidebar/RoomList.js
  client/sidebar/RoomMenu.js
  package-lock.json
  package.json
Labels: subj: ui/ux, type: regression

#19402 Regression: Thread not showing for unloaded message
  app/threads/client/components/ThreadComponent.tsx
Labels: subj: ui/ux, type: regression
