Repository RocketChat/Rocket.Chat, pull requests merged in 2020-09, with the labels that each got.

#18834 [FIX] e.sendToBottomIfNecessaryDebounced is not a function
  app/ui/client/views/app/room.js
Labels: type: bug

#18836 [FIX] Can't change password
  client/account/AccountProfilePage.js
Labels: type: bug

#18835 [FIX][ENTERPRISE] Omnichannel service status switching to unavailable
  ee/app/livechat-enterprise/server/startup.js
Labels: type: bug

#18852 [FIX] User can't invite or join other Omnichannel rooms
  app/lib/server/functions/addUserToRoom.js
  app/livechat/lib/LivechatRoomType.js
  app/livechat/server/startup.js
  app/tokenpass/server/startup.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: type: bug

#18795 [FIX] Omnichannel Current Chats open status filter not working
  client/omnichannel/currentChats/CurrentChatsRoute.js
Labels: type: bug

#18864 [FIX] Deactivate users that are the last owner of a room using REST API
  app/api/server/v1/users.js
  tests/data/rooms.helper.js
  tests/end-to-end/api/01-users.js
Labels: documentation: needed

#18956 [FIX] PDF not rendering
  app/message-attachments/client/messageAttachment.js
Labels: subj: ui/ux, type: bug

#18832 [FIX] Reaction buttons not behaving properly
  app/reactions/client/init.js
  app/ui-message/client/message.html
  app/ui-message/client/message.js
Labels: subj: ui/ux, type: bug

#18928 [IMPROVE] Move jump to message outside menu
  app/mentions-flextab/client/actionButton.js
  app/message-pin/client/actionButton.js
  app/message-star/client/actionButton.js
Labels: feat: message

#18943 [FIX] Users not being able to activate/deactivate E2E in DMs
  app/channel-settings/server/methods/saveRoomSettings.js
  app/e2e/client/tabbar.js
  app/ui/client/components/header/headerRoom.js
Labels: feat: e2e

#19002 [NEW][Apps] Add support to the "encoding" option in http requests from Apps
  app/apps/server/bridges/http.js
  package-lock.json
  package.json
Labels: feat: apps

#18995 Regression: File upload via apps not working in some scenarios
  app/apps/server/bridges/uploads.js
  app/file-upload/server/lib/FileUpload.js
  app/file-upload/server/methods/sendFileMessage.js
  package-lock.json
  package.json
Labels: feat: apps

#19005 Regression: Elements select & multiSelect not rendered correctly in the App Settings
  client/admin/apps/AppSettings.js
Labels: feat: apps
