Repository RocketChat/Rocket.Chat, pull requests merged in 2020-08, with the labels that each got.

#18261 [NEW] Add the ability to set the character message limit on Livechat widget
  app/livechat/client/views/app/livechatAppearance.html
  app/livechat/client/views/app/livechatAppearance.js
  app/livechat/server/api/lib/appearance.js
  app/livechat/server/api/lib/livechat.js
  app/livechat/server/config.js
  app/livechat/server/lib/Livechat.js
  app/livechat/server/methods/saveAppearance.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-i18n/i18n/pt.i18n.json
Labels: feat: livechat

#18474 [FIX] Error when reading uploads from Livechat Visitor through the Apps Engine
  app/apps/server/converters/uploads.js
Labels: type: bug

#18408 [IMPROVE] Info page requires permission
  client/admin/info/InformationRoute.js
  client/admin/sidebarItems.js
  client/components/NotAuthorizedPage.js
Labels: feat: roles / permissions

#18473 [FIX] 2FA by Email setting showing for the user even when disabled by the admin
  client/account/security/AccountSecurityPage.js
Labels: subj: ui/ux, type: bug

#18407 [FIX] Emojis on thread replies
  app/emoji/client/emojiParser.js
  app/threads/client/lib/normalizeThreadTitle.js
Labels: subj: message rendering

#18374 [FIX] Custom fields title when no custom fields
  client/admin/users/UserForm.js
  client/components/CustomFieldsForm.js
Labels: subj: ui/ux, type: bug

#18437 [FIX] Auto complete user suggestions
  app/theme/client/imports/general/base_old.css
  app/ui-message/client/popup/messagePopupUser.html
Labels: subj: ui/ux

#17427 [FIX] Anonymous users were created as inactive if the manual approval setting was enabled
  app/authentication/server/startup/index.js
  server/methods/registerUser.js
Labels: type: bug

#18705 Regression: Omnichannel Tags and Units issues
  ee/client/omnichannel/tags/EditTag.js
  ee/client/omnichannel/tags/TagsRoute.js
  ee/client/omnichannel/units/EditUnit.js
  ee/client/omnichannel/units/UnitsRoute.js
Labels: subj: ui/ux, type: bug

#18715 Regression: Bundle the package `hepburn`
  imports/client/hepburn
Labels: subj: IE11, type: bug
