Repository RocketChat/Rocket.Chat, pull requests merged in 2021-12, with the labels that each got.

#23690 [FIX] error after properly deleting user from admin panel
  client/views/admin/users/UserInfo.js
  client/views/admin/users/UserInfoActions.js
Labels: stat: ready to merge, communityPR

#23712 [FIX] No hover effect for items in kebab menu.
  app/theme/client/imports/components/popover.css
Labels: subj: ui/ux, communityPR

#23347 [FIX] creating room with federated member
  app/federation/server/normalizers/user.js
Labels: communityPR

#23798 Trigger new UI button interactions
  app/apps/server/communication/uikit.js
  app/ui-message/client/ActionManager.js
  app/ui-message/client/actionButtons/messageAction.ts
  app/ui-message/client/actionButtons/messageBox.ts
  app/ui-message/client/actionButtons/tabbar.ts
Labels: Invalid PR Title

#23724 Show buttons in contexts
  app/apps/server/communication/uikit.js
  app/ui-message/client/ActionButtonSyncer.ts
  app/ui-message/client/ActionManager.js
  app/ui-message/client/actionButtons/lib/applyButtonFilters.ts
  app/ui-message/client/actionButtons/messageAction.ts
  app/ui-message/client/actionButtons/messageBox.ts
  app/ui-message/client/actionButtons/tabbar.ts
  definition/IRoom.ts
Labels: Invalid PR Title

#23882 [FIX] Custom emoji route in admin
  client/components/Page/Page.tsx
  client/views/admin/customEmoji/AddCustomEmoji.tsx
  client/views/admin/customEmoji/CustomEmoji.js
  client/views/admin/customEmoji/CustomEmojiRoute.tsx
  client/views/admin/customEmoji/EditCustomEmoji.tsx
  client/views/admin/customEmoji/EditCustomEmojiWithData.tsx
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: communityPR

#23975 Handle translation of the buttons names
  app/ui-message/client/actionButtons/messageAction.ts
  app/ui-message/client/actionButtons/messageBox.ts
  app/ui-message/client/actionButtons/tabbar.ts
Labels: Invalid PR Title

#23901 [FIX] broken `Word Placement Anywhere` and `Run on edits` toggles in integration page
  client/views/admin/integrations/OutgoiongWebhookForm.js
  client/views/admin/integrations/edit/EditOutgoingWebhook.js
Labels: communityPR

#23987 [FIX] Broken links present in some languages
  packages/rocketchat-i18n/i18n/af.i18n.json
  packages/rocketchat-i18n/i18n/ar.i18n.json
  packages/rocketchat-i18n/i18n/az.i18n.json
  packages/rocketchat-i18n/i18n/bg.i18n.json
  packages/rocketchat-i18n/i18n/bs.i18n.json
  packages/rocketchat-i18n/i18n/cy.i18n.json
  packages/rocketchat-i18n/i18n/da.i18n.json
  packages/rocketchat-i18n/i18n/de-AT.i18n.json
  packages/rocketchat-i18n/i18n/de-IN.i18n.json
  packages/rocketchat-i18n/i18n/el.i18n.json
  packages/rocketchat-i18n/i18n/eo.i18n.json
  packages/rocketchat-i18n/i18n/fi.i18n.json
  packages/rocketchat-i18n/i18n/id.i18n.json
  packages/rocketchat-i18n/i18n/ku.i18n.json
  packages/rocketchat-i18n/i18n/lo.i18n.json
  packages/rocketchat-i18n/i18n/mn.i18n.json
  packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  packages/rocketchat-i18n/i18n/ro.i18n.json
  packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  packages/rocketchat-i18n/i18n/sq.i18n.json
  packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  packages/rocketchat-i18n/i18n/th-TH.i18n.json
  packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  packages/rocketchat-i18n/i18n/zh-HK.i18n.json
Labels: communityPR

#23995 [FIX] Prevent the app from crashing when you look at the notification preferences of a room in which you are not a member
  app/push-notifications/client/tabBar.ts
  client/contexts/UserContext.ts
  client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.js
Labels: communityPR

#23904 [FIX] Jitsi call already ended
  client/views/room/contextualBar/Call/Jitsi/CallJitsiWithData.js
Labels: communityPR

#19640 [FIX] Changes on department agents should mark form as dirty
  client/views/omnichannel/departments/AddAgent.js
  client/views/omnichannel/departments/AgentRow.js
  client/views/omnichannel/departments/DepartmentsAgentsTable.js
  client/views/omnichannel/departments/EditDepartment.js
  client/views/omnichannel/departments/RemoveAgentButton.js
Labels: feat: omnichannel, communityPR

#24024 [FIX] Message Erasure Type "Keep" Messages not working
  app/lib/server/functions/deleteUser.js
Labels: communityPR

#23970 [FIX] filter ability for admin room checkboxes
  client/components/GenericTable/GenericTable.tsx
Labels: subj: ui/ux, communityPR

#24051 [FIX] wrong new userInfo during user creation
  client/views/admin/users/UsersPage.js
Labels: communityPR
