Repository RocketChat/Rocket.Chat, pull requests merged in 2021-06, with the labels that each got.

#22127 Chore: Update delete team modal to new design
  client/views/teams/contextualBar/info/Delete/DeleteTeamModal.js
  client/views/teams/contextualBar/info/Delete/DeleteTeamModal.stories.js
  client/views/teams/contextualBar/info/Delete/StepOne.js
  client/views/teams/contextualBar/info/Delete/StepThree.js
  client/views/teams/contextualBar/info/Delete/StepTwo.js
  client/views/teams/contextualBar/info/Delete/index.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge

#22141 Chore: Change modals for remove user from team && leave team
  client/components/GenericModal.tsx
  client/views/teams/contextualBar/info/Leave/LeaveTeamModal.js
  client/views/teams/contextualBar/info/Leave/LeaveTeamModal.stories.js
  client/views/teams/contextualBar/info/Leave/StepOne.js
  client/views/teams/contextualBar/info/Leave/StepTwo.js
  client/views/teams/contextualBar/info/Leave/index.js
  client/views/teams/contextualBar/members/RemoveUsersModal/BaseRemoveUsersModal.js
  client/views/teams/contextualBar/members/RemoveUsersModal/RemoveUsersSecondStep.js
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge

#21983 [FIX] Web navigation breaks after visiting integrations admin page
  client/views/admin/integrations/IntegrationsPage.js
Labels: stat: ready to merge

#22191 [FIX] Can't delete file from Room's file list
  client/views/room/contextualBar/RoomFiles/Row.js
  client/views/room/contextualBar/RoomFiles/components/FileItem.js
Labels: stat: ready to merge

#21019 [FIX] Removed follow button from message box in threads.
  app/threads/client/flextab/thread.js
Labels: stat: ready to merge

#22290 [FIX] Attachments not rendered if deployed on subfolder
  app/utils/lib/getURL.js
  client/components/Message/Attachments/Files/ImageAttachment.tsx
  client/providers/AvatarUrlProvider.tsx
Labels: stat: ready to merge

#22367 [IMPROVE] Add new indexes for omnichannel-related collections
  app/models/server/models/LivechatDepartment.js
  app/models/server/models/LivechatTrigger.js
  ee/app/models/server/models/LivechatUnitMonitors.js
Labels: Invalid PR Title

#22315 [IMPROVE] Paginated multiselect for EE tags
  client/components/Omnichannel/Tags.js
  client/contexts/ServerContext/endpoints.ts
  client/contexts/ServerContext/endpoints/v1/livechat/tagsList.ts
  client/views/omnichannel/currentChats/FilterByText.js
  definition/ILivechatTag.ts
  definition/ILivechatTagRecord.ts
  ee/client/hooks/useTagsList.ts
  ee/client/omnichannel/tags/CurrentChatTags.js
Labels: feat: enterprise, feat: omnichannel

#22435 Revert: [IMPROVE] Update system messages' behavior in rooms
  app/channel-settings/server/methods/saveRoomSettings.js
  app/lib/lib/MessageTypes.js
  app/message-pin/client/index.js
  app/message-pin/client/messageType.js
  app/models/server/models/Messages.js
  app/models/server/models/Rooms.js
  client/sidebar/RoomList/normalizeSidebarMessage.js
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rocketchat-i18n/i18n/pt.i18n.json
  tests/end-to-end/api/02-channels.js
  tests/end-to-end/api/03-groups.js
Labels: Invalid PR Title, [ignore-title], ignore-title

#22461 Update README.md
  README.md
Labels: Invalid PR Title

#22493 Merge master into develop & Set version to 3.17.0-develop
  .docker/Dockerfile.rhel
  .github/history.json
  .snapcraft/resources/prepareRocketChat
  .snapcraft/snap/snapcraft.yaml
  HISTORY.md
  app/utils/rocketchat.info
  package-lock.json
  package.json
Labels: Invalid PR Title
