Repository RocketChat/Rocket.Chat, pull requests merged in 2021-04, with the labels that each got.

#21508 [FIX] Allows more than 25 threads to be loaded, fixes #21507
  client/views/room/contextualBar/Threads/useThreadsList.ts
Labels: stat: ready to merge

#21509 [FIX] Remove all agent subscriptions when an Omnichannel chat is closed
  app/livechat/server/lib/Livechat.js
  server/startup/migrations/index.js
  server/startup/migrations/v222.js
Labels: type: bug

#21652 [Fix] Add support for ignoreDiscussion param on room.cleanHistory endpoint
  app/api/server/v1/rooms.js
Labels: backend

#21565 [NEW][APPS] onInstall and onUninstall events
  app/apps/server/communication/rest.js
  package-lock.json
  package.json
Labels: feat: apps

#21746 [FIX] Attachment files are not rendered properly on SMS channels
  app/livechat/imports/server/rest/sms.js
Labels: type: bug
