Repository RocketChat/Rocket.Chat, pull requests merged in 2021-01, with the labels that each got.

#20073 [FIX] Actions from User Info panel
  client/views/room/contextualBar/UserInfo/index.js
Labels: type: bug

#20083 [IMPROVE] Title for user avatar buttons
  client/components/avatar/UserAvatarEditor.js
Labels: type: improvement

#20285 [NEW] [Apps] IPreFileUpload event
  app/apps/server/bridges/listeners.js
  app/file-upload/server/lib/FileUpload.js
  app/ui/client/lib/fileUpload.js
  package-lock.json
  package.json
Labels: feat: apps
