Repository RocketChat/Rocket.Chat, pull requests merged in 2021-09, with the labels that each got.

#16050 [BREAK] Remove patch info from endpoint /api/info for non-logged in users
  app/api/server/default/info.js
  app/api/server/lib/getServerInfo.ts
  tests/end-to-end/api/00-miscellaneous.js
Labels: type: improvement

#23209 [FIX] Save department agents
  client/views/omnichannel/departments/EditDepartment.js
Labels: Omnichannel

#23190 [IMPROVE] Canned response admin settings
  client/views/admin/info/LicenseCard.js
  ee/app/canned-responses/server/settings.js
  ee/client/omnichannel/components/contextualBar/CannedResponse/CannedResponseList.tsx
  packages/rocketchat-i18n/i18n/en.i18n.json
  server/startup/migrations/index.js
  server/startup/migrations/v236.ts
Labels: Omnichannel

#23134 [NEW] Voip: Permissions
  app/authorization/server/startup.js
  ee/app/livechat-enterprise/server/permissions.js
Labels: Omnichannel, feat: voip

#23185 [FIX] Omnichannel On hold chats being forwarded to offline agents
  ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
  ee/app/livechat-enterprise/server/hooks/onAgentAssignmentFailed.ts
Labels: Omnichannel

#23203 [NEW] Sidebar section with VOIP call-available icon
  client/contexts/OmnichannelContext.ts
  client/providers/OmnichannelProvider.tsx
  client/sidebar/sections/Omnichannel.tsx
  package-lock.json
  package.json
Labels: Omnichannel, feat: voip

#23199 [IMPROVE] Change occurences of Livechat to Omnichannel in ES translations were applicable
  packages/rocketchat-i18n/i18n/es.i18n.json
Labels: Omnichannel

#23261 [FIX] Stop queue when Omnichannel is disabled or the routing method does not support it
  app/livechat/server/lib/Livechat.js
  app/livechat/server/lib/QueueManager.js
  app/livechat/server/lib/RoutingManager.js
  app/models/server/models/Users.js
  ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
Labels: Omnichannel

#23262 [FIX] Avoid bots to be marked as unavailable when log off/login
  app/livechat/server/business-hour/index.ts
  app/livechat/server/startup.js
Labels: Omnichannel

#23090 [NEW] Omnichannel source identification fields
  app/api/server/helpers/deprecationWarning.js
  app/api/server/helpers/deprecationWarning.ts
  app/api/server/helpers/isWidget.ts
  app/api/server/index.js
  app/apps/server/bridges/livechat.ts
  app/lib/server/lib/deprecationWarningLogger.ts
  app/livechat/imports/server/rest/sms.js
  app/livechat/imports/server/rest/upload.js
  app/livechat/server/api/v1/message.js
  app/livechat/server/api/v1/room.js
  app/livechat/server/api/v1/videoCall.js
  app/livechat/server/lib/Helper.js
  app/livechat/server/methods/sendMessageLivechat.js
  app/livechat/server/methods/startFileUploadRoom.js
  app/livechat/server/methods/startVideoCall.js
  app/ui-sidenav/client/roomList.js
  client/hooks/useRoomIcon.tsx
  client/views/admin/emailInbox/EmailInboxForm.js
  client/views/omnichannel/components/Info.tsx
  client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
  client/views/omnichannel/directory/chats/contextualBar/SourceField.tsx
  client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.js
  definition/IRoom.ts
  package-lock.json
  package.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-i18n/i18n/es.i18n.json
  server/features/EmailInbox/EmailInbox_Incoming.ts
  server/modules/watchers/publishFields.ts
Labels: feat: apps, Omnichannel
