Repository RocketChat/Rocket.Chat, pull requests merged in 2022-07, with the labels that each got.

#26087 [FIX] Remove duplicated property _USERNAMES from createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25491 [IMPROVE] Avoid using omnichannel-queue collection
  apps/meteor/app/models/server/index.js
  apps/meteor/app/models/server/models/LivechatInquiry.ts
  apps/meteor/app/models/server/models/OmnichannelQueue.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
  apps/meteor/server/models/OmnichannelQueue.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/models/raw/OmnichannelQueue.ts
  apps/meteor/server/models/startup.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v274.ts
  packages/core-typings/src/IInquiry.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
  packages/model-typings/src/models/IOmnichannelQueueModel.ts
  packages/models/src/index.ts
Labels: stat: ready to merge, eng day, stat: QA tested

#26086 Chore: Room access validation may be called without user information
  apps/meteor/app/livechat/server/roomAccessValidator.internalService.ts
  apps/meteor/server/sdk/types/IAuthorization.ts
  apps/meteor/server/sdk/types/IAuthorizationLivechat.ts
  apps/meteor/server/services/authorization/canAccessRoom.ts
Labels: stat: ready to merge, stat: QA skipped, feat: team-collab

#26057 [FIX] Unable to close chats when comments is disabled
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26084 Chore: Allow endpoints to optionally require authentication
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/api.js
  apps/meteor/ee/server/api/licenses.ts
Labels: stat: ready to merge, stat: QA skipped, feat: team-collab

#26067 Regression: Add Error boundary to katex render component
  packages/gazzodown/package.json
  packages/gazzodown/src/Markup.tsx
  packages/gazzodown/src/PreviewMarkup.tsx
  packages/gazzodown/src/elements/InlineElements.tsx
  packages/gazzodown/src/elements/PreviewInlineElements.tsx
  packages/gazzodown/src/katex/KatexErrorBoundary.tsx
  packages/ui-client/src/components/ErrorBoundary.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26083 [FIX] Undefined headers on API Client
  packages/api-client/src/index.ts
Labels: stat: ready to merge, stat: QA skipped, feat: data-protection

#24534 [FIX] Validate room access
  apps/meteor/client/lib/rooms/roomTypes/direct.ts
  apps/meteor/server/services/authorization/canAccessRoom.ts
Labels: stat: ready to merge, stat: QA skipped, feat: data-protection

#26095 Chore: fix watermark condition
  apps/meteor/client/sidebar/footer/SidebarFooterWatermark.tsx
Labels: stat: ready to merge, stat: QA skipped

#26094 Chore: Handle errors on index creation
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/startup/migrations/v203.ts
  apps/meteor/server/startup/migrations/v218.ts
  apps/meteor/server/startup/migrations/v263.ts
  apps/meteor/server/startup/migrations/v264.ts
  apps/meteor/server/startup/migrations/v273.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26099 Regression: [VideoConference] If the caller loses connection, direct calls are never canceled
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: ready to merge, stat: QA skipped, feat: team-collab

#26064 Chore: Adding default message parser template
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/app/markdown/server/settings.ts
  apps/meteor/app/ui-utils/client/lib/messageContext.js
  apps/meteor/app/ui/client/views/app/room.html
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentDescription.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentTitleLink.tsx
  apps/meteor/client/views/account/preferences/PreferencesGlobalSection.js
  apps/meteor/client/views/room/MessageList/components/MessageHeader.tsx
  apps/meteor/client/views/room/MessageList/components/MessageSystem.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v276.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/07-emoji.spec.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/pageobjects/MainContent.ts
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26053 Chore: Settings UI issue
  apps/meteor/client/components/UserCard/UserCard.tsx
  apps/meteor/client/views/admin/settings/SettingsGroupCard.tsx
  apps/meteor/client/views/admin/settings/SettingsPage.tsx
  apps/meteor/package.json
  apps/meteor/tests/e2e/pageobjects/SetupWizard.ts
  packages/gazzodown/package.json
  packages/livechat/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped, feat: team-collab

#26081 [NEW][ENTERPRISE] Introducing dial pad component into sidebar, calls table, contextual bar
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/components/GenericTable/GenericTable.tsx
  apps/meteor/client/contexts/CallContext.ts
  apps/meteor/client/contexts/VoIPAgentContext.ts
  apps/meteor/client/hooks/useDialModal.tsx
  apps/meteor/client/lib/voip/VoIPUser.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/providers/VoIPAgentProvider.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.stories.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/client/sidebar/sections/OmnichannelSection.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallDialPad.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggle.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleError.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleLoading.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleReady.tsx
  apps/meteor/client/sidebar/sections/hooks/useVoipAgent.ts
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/CallsContextualBarRoom.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfoCallButton.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.js
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTableDialpadButton.tsx
  apps/meteor/ee/client/hooks/useOutboundDialer.ts
  apps/meteor/ee/client/hooks/useVoipClient.ts
  apps/meteor/ee/client/lib/voip/EEVoipClient.ts
  apps/meteor/ee/client/voip/modal/DialPad/DialInput.tsx
  apps/meteor/ee/client/voip/modal/DialPad/DialPadModal.stories.tsx
  apps/meteor/ee/client/voip/modal/DialPad/DialPadModal.tsx
  apps/meteor/ee/client/voip/modal/DialPad/Pad.tsx
  apps/meteor/ee/client/voip/modal/DialPad/PadButton.tsx
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useDialPad.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rest-typings/src/v1/omnichannel.ts
  packages/ui-contexts/src/TranslationContext.ts
  yarn.lock
Labels: feat: omnichannel, stat: ready to merge, stat: QA skipped

#26098 [BREAK] Remove support to old MongoDB versions
  .github/workflows/build_and_test.yml
  apps/meteor/server/startup/serverRunning.js
Labels: stat: ready to merge, stat: QA skipped, feat: chat-engine

#26100 [BREAK] Upgrade to version 5.0 can be done only from version 4.x
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v174.ts
  apps/meteor/server/startup/migrations/v175.js
  apps/meteor/server/startup/migrations/v176.ts
  apps/meteor/server/startup/migrations/v177.ts
  apps/meteor/server/startup/migrations/v178.ts
  apps/meteor/server/startup/migrations/v179.js
  apps/meteor/server/startup/migrations/v180.js
  apps/meteor/server/startup/migrations/v182.js
  apps/meteor/server/startup/migrations/v183.js
  apps/meteor/server/startup/migrations/v184.ts
  apps/meteor/server/startup/migrations/v185.ts
  apps/meteor/server/startup/migrations/v186.js
  apps/meteor/server/startup/migrations/v187.js
  apps/meteor/server/startup/migrations/v188.ts
  apps/meteor/server/startup/migrations/v189.ts
  apps/meteor/server/startup/migrations/v190.js
  apps/meteor/server/startup/migrations/v191.ts
  apps/meteor/server/startup/migrations/v192.js
  apps/meteor/server/startup/migrations/v193.js
  apps/meteor/server/startup/migrations/v194.js
  apps/meteor/server/startup/migrations/v195.ts
  apps/meteor/server/startup/migrations/v196.js
  apps/meteor/server/startup/migrations/v197.js
  apps/meteor/server/startup/migrations/v198.ts
  apps/meteor/server/startup/migrations/v199.js
  apps/meteor/server/startup/migrations/v200.js
  apps/meteor/server/startup/migrations/v201.js
  apps/meteor/server/startup/migrations/v202.js
  apps/meteor/server/startup/migrations/v203.ts
  apps/meteor/server/startup/migrations/v204.js
  apps/meteor/server/startup/migrations/v205.js
  apps/meteor/server/startup/migrations/v206.js
  apps/meteor/server/startup/migrations/v207.ts
  apps/meteor/server/startup/migrations/v208.js
  apps/meteor/server/startup/migrations/v209.js
  apps/meteor/server/startup/migrations/v210.js
  apps/meteor/server/startup/migrations/v211.js
  apps/meteor/server/startup/migrations/v212.js
  apps/meteor/server/startup/migrations/v213.js
  apps/meteor/server/startup/migrations/v214.ts
  apps/meteor/server/startup/migrations/v215.ts
  apps/meteor/server/startup/migrations/v216.js
  apps/meteor/server/startup/migrations/v217.ts
  apps/meteor/server/startup/migrations/v218.ts
  apps/meteor/server/startup/migrations/v219.ts
  apps/meteor/server/startup/migrations/v220.ts
  apps/meteor/server/startup/migrations/v221.js
  apps/meteor/server/startup/migrations/v222.js
  apps/meteor/server/startup/migrations/v223.ts
  apps/meteor/server/startup/migrations/v224.ts
  apps/meteor/server/startup/migrations/v225.ts
  apps/meteor/server/startup/migrations/v226.ts
  apps/meteor/server/startup/migrations/v227.js
  apps/meteor/server/startup/migrations/v228.ts
  apps/meteor/server/startup/migrations/v229.ts
  apps/meteor/server/startup/migrations/v230.ts
  apps/meteor/server/startup/migrations/v231.ts
  apps/meteor/server/startup/migrations/v232.ts
  apps/meteor/server/startup/migrations/v233.ts
Labels: stat: ready to merge, stat: QA skipped, feat: chat-engine

#25624 Chore: Bump deps
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/app/livechat/server/business-hour/Default.ts
  apps/meteor/app/livechat/server/lib/Analytics.js
  apps/meteor/app/livestream/server/functions/livestream.js
  apps/meteor/app/livestream/server/routes.js
  apps/meteor/app/markdown/lib/parser/marked/marked.js
  apps/meteor/app/meteor-accounts-saml/server/lib/parsers/LogoutRequest.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/parsers/LogoutResponse.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/parsers/Response.ts
  apps/meteor/app/smarsh-connector/server/settings.js
  apps/meteor/client/components/MarkdownText.tsx
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/tsconfig.json
  apps/meteor/tsconfig.typecheck.json
  ee/apps/ddp-streamer/package.json
  package.json
  packages/api-client/package.json
  packages/core-typings/package.json
  packages/eslint-config/package.json
  packages/favicon/package.json
  packages/livechat/package.json
  packages/model-typings/package.json
  packages/models/package.json
  packages/rest-typings/package.json
  packages/ui-contexts/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25681 Chore: Add Agenda fork to the monorepo
  apps/meteor/app/apps/server/bridges/scheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoCloseOnHoldScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  packages/agenda/.eslintrc
  packages/agenda/package.json
  packages/agenda/src/Agenda.ts
  packages/agenda/src/Job.ts
  packages/agenda/src/JobProcessingQueue.ts
  packages/agenda/src/createJob.ts
  packages/agenda/src/definition/IJob.ts
  packages/agenda/src/definition/JobDefinition.ts
  packages/agenda/src/definition/cron.d.ts
  packages/agenda/src/definition/date.js.d.ts
  packages/agenda/src/index.ts
  packages/agenda/src/lib/hasMongoProtocol.ts
  packages/agenda/src/lib/noCallback.ts
  packages/agenda/src/lib/parsePriority.ts
  packages/agenda/tsconfig.json
  yarn.lock
Labels: stat: needs QA

#26107 Chore: move fork of cas module to the monorepo
  apps/meteor/app/cas/server/cas_server.js
  apps/meteor/package.json
  packages/cas-validate/package.json
  packages/cas-validate/src/index.ts
  packages/cas-validate/src/validate.ts
  packages/cas-validate/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26113 Chore: Change stats to daily
  apps/meteor/server/cron/statistics.js
Labels: stat: ready to merge, stat: QA skipped

#26101 Regression: [VideoConference] Callee client behaves improperly when accepting a call from someone who lost the connection
  apps/meteor/client/lib/VideoConfManager.ts
Labels: stat: ready to merge, stat: QA skipped

#26116 Regression: Changing isEnterprise useQuery name to prevent conflict of queries
  apps/meteor/client/sidebar/footer/SidebarFooterWatermark.tsx
Labels: stat: ready to merge, stat: QA skipped

#26080 Regression: Fix marketplace app apis visibility problem
  apps/meteor/client/views/admin/apps/AppDetails.tsx
Labels: stat: ready to merge, stat: QA skipped

#26117 Regression: Users on new sessions are forced to re-configure 2fa
  apps/meteor/client/lib/userData.ts
Labels: stat: ready to merge, stat: QA skipped

#25939 [NEW] Message Forwarding Init
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/views/room/modals/ShareMessageModal/ShareMessageModal.tsx
  apps/meteor/client/views/room/modals/ShareMessageModal/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: QA skipped

#26115 Regression: Do not show federated tooltip on non-federated rooms
  apps/meteor/app/discussion/client/tabBar.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/slash-commands/index.ts
  apps/meteor/app/livestream/client/tabBar.tsx
  apps/meteor/app/message-pin/client/tabBar.ts
  apps/meteor/app/threads/client/flextab/threadlist.tsx
  apps/meteor/app/ui-clean-history/client/lib/tabBar.ts
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/app/webrtc/client/tabBar.tsx
  apps/meteor/client/views/room/lib/Toolbox/defaultActions.ts
Labels: feat: federation, stat: ready to merge, stat: QA skipped

#26129 Regression: All users in members list showing as federated
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/components/MemberItem.tsx
Labels: stat: ready to merge, stat: QA skipped

#26062 [FIX] Update error message on `useEndpointActionExperimental`
  apps/meteor/client/hooks/useEndpointActionExperimental.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26140 Regression: Fix assets format
  apps/meteor/app/assets/server/assets.ts
Labels: stat: ready to merge, stat: QA skipped

#26125 Regression: Unable to click on UiKit buttons provided by apps
  apps/meteor/app/api/server/middlewares/authentication.ts
Labels: stat: ready to merge, stat: QA skipped

#26127 Regression: Close button on modals created via apps not working
  apps/meteor/app/apps/server/communication/uikit.ts
Labels: stat: ready to merge, stat: QA skipped

#26128 Regression: Broken emoji picker on Livechat
  packages/livechat/src/routes/Chat/component.js
Labels: stat: ready to merge, stat: QA tested

#26134 Regression: Add better error messages when call fails
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#26097 Regression: Update message reaction text
  apps/meteor/client/views/room/MessageList/components/MessageReaction.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#26111 Regression: Correct call ringtones
  apps/meteor/app/custom-sounds/client/lib/CustomSounds.js
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/public/sounds/call-ended.mp3
  apps/meteor/public/sounds/outbound-call-ringing.mp3
Labels: stat: ready to merge, stat: QA skipped

#26141 Regression: Emojis displaying as `:undefined:`
  packages/gazzodown/src/emoji/Emoji.tsx
Labels: stat: needs QA

#26135 Regression: Added missing call button in the contact info contextual bar
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfoCallButton.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.js
Labels: stat: ready to merge, stat: QA skipped

#26156 [IMPROVE] [VideoConf] Validate and respond to client notifications on the server
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/modules/notifications/notifications.module.ts
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#26151 [NEW] When ending a call, add a message saying that it has ended.
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#26180 [NEW] Add "Ring other users when calling" permission
  apps/meteor/app/api/server/v1/videoConference.ts
  apps/meteor/app/authorization/server/functions/upsertPermissions.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v278.ts
Labels: stat: needs QA

#26184 Regression: Align TypeScript version across workspaces
  _templates/package/new/package.json.ejs.t
  packages/agenda/package.json
  packages/cas-validate/package.json
  yarn.lock
Labels: stat: needs QA

#26136 Regression: Send files with `enter` key
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26186 Chore: Remove setUserStatus method call
  apps/meteor/client/sidebar/header/EditStatusModal.tsx
Labels: stat: needs QA, methods removal

#26191 Chore: Remove custom user status method calls
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
Labels: stat: needs QA, methods removal

#26161 [IMPROVE] Use the provider app's user to send videoconf messages
  apps/meteor/app/apps/server/bridges/videoConferences.ts
  apps/meteor/app/models/server/models/Users.js
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/lib/videoConfProviders.ts
  apps/meteor/server/models/raw/Users.js
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/model-typings/src/models/IUsersModel.ts
  yarn.lock
Labels: stat: needs QA

#26202 Chore: Remove meteor call on AccountBox
  apps/meteor/app/ui-utils/client/lib/AccountBox.ts
  apps/meteor/client/sidebar/header/UserDropdown.tsx
Labels: eng day, stat: needs QA, methods removal

#26148 Regression: moving Community Watermark to `ee` folder
  apps/meteor/client/sidebar/footer/SidebarFooterDefault.tsx
  apps/meteor/client/sidebar/footer/voip/index.tsx
  apps/meteor/ee/client/sidebar/footer/SidebarFooterWatermark.tsx
  packages/ui-client/package.json
Labels: stat: ready to merge, stat: QA tested

#26205 Chore: Change Apps-Engine version source for info
  apps/meteor/packages/rocketchat-version/plugin/compile-version.js
Labels: stat: ready to merge, stat: QA skipped

#26199 Regression: Fix command previews
  apps/meteor/app/apps/client/communication/websockets.js
  apps/meteor/client/startup/slashCommands.ts
Labels: stat: ready to merge, stat: QA skipped

#26201 Chore: Info page
  apps/meteor/client/components/Card/Col.tsx
  apps/meteor/client/views/admin/info/FederationCard/FederationCard.tsx
  apps/meteor/client/views/admin/info/InformationPage.tsx
Labels: stat: needs QA

#26198 Chore: useMethod remove - AssetSettingInput
  apps/meteor/app/api/server/v1/assets.ts
  apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
  apps/meteor/tests/end-to-end/api/14-assets.js
  packages/rest-typings/src/v1/assets.ts
Labels: stat: needs QA, methods removal

#26173 Regression: Inline code and copyonly tag styles
  apps/meteor/app/theme/client/imports/general/base_old.css
Labels: stat: ready to merge, stat: QA tested

#26159 Regression: Change Audio settings for device settings as modal title
  apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#26171 Regression: UIKit buttons auth user validation
  apps/meteor/app/api/server/middlewares/authentication.ts
  apps/meteor/app/apps/server/communication/uikit.ts
Labels: stat: ready to merge, stat: QA skipped

#26219 Chore: Check for env var values and not just if they are set
  apps/meteor/app/models/server/models/_oplogHandle.ts
  apps/meteor/packages/rocketchat-mongo-config/server/index.js
  apps/meteor/server/services/meteor/service.ts
Labels: stat: ready to merge, stat: QA skipped

#26163 Chore: Do not log integrations using `name` key
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/app/integrations/server/lib/triggerHandler.js
Labels: stat: needs QA

#26222 [BREAK] Remove webRTC for channels/dm/groups
  apps/meteor/app/ui/client/views/app/room.js
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoWithData.js
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTC.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCButtons.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCRemote.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCVideo.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCWithData.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/index.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useAudioCallAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useCallAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useVideoCallAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/useUserInfoActions.ts
Labels: stat: needs QA

#26223 Regression: Meteor uses `projection` for its observes
  apps/meteor/server/services/meteor/service.ts
Labels: stat: needs QA

#26225 [BREAK] Remove webRTC for channels/dm/groups
  apps/meteor/app/ui/client/views/app/room.js
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoWithData.js
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTC.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCButtons.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCRemote.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCVideo.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/UserWebRTCWithData.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserWebRTC/index.ts
Labels: stat: ready to merge, stat: QA skipped

#26093 Regression: Fix rendered markdown styling on app info page details section
  apps/meteor/client/views/admin/apps/AppDetails.tsx
Labels: stat: ready to merge, stat: QA skipped

#26216 Regression: Replace contact center icon
  apps/meteor/client/sidebar/sections/OmnichannelSection.tsx
Labels: stat: needs QA

#26179 Regression: OTR with new React Messages
  apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
  apps/meteor/client/views/room/MessageList/components/MessageIndicators.tsx
  apps/meteor/lib/isE2EEMessage.ts
  apps/meteor/server/hooks/messages/markdownParser.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/pageobjects/MainContent.ts
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: needs QA

#26160 Regression: Empty URL previews in messages.
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedHtmlPreview.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedPreviewContent.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/PreviewList.tsx
Labels: stat: ready to merge, stat: QA tested

#26194 Regression: Fix Omnichannel not working after meteor update
  apps/meteor/app/importer/server/startup/setImportsToInvalid.js
  apps/meteor/app/livechat/server/lib/QueueManager.js
  apps/meteor/app/models/server/models/LivechatDepartmentAgents.js
  apps/meteor/app/models/server/models/LivechatRooms.js
  apps/meteor/app/models/server/models/Settings.js
  apps/meteor/app/models/server/models/Users.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/server/methods/browseChannels.js
  apps/meteor/server/models/raw/LivechatRooms.js
  apps/meteor/server/models/raw/Users.js
  apps/meteor/server/services/banner/service.ts
Labels: stat: ready to merge, stat: QA tested

#26226 Regression: Fix files list endpoints
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/helpers/addUserToFileObj.ts
  apps/meteor/app/api/server/helpers/insertUserObject.ts
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/v1/channels.js
  apps/meteor/app/api/server/v1/groups.js
  apps/meteor/app/api/server/v1/im.ts
Labels: stat: needs QA

#26102 Chore: Remove unused migrations
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/minimumVersion.ts
  apps/meteor/server/startup/migrations/v234.ts
  apps/meteor/server/startup/migrations/v235.ts
  apps/meteor/server/startup/migrations/v236.ts
  apps/meteor/server/startup/migrations/v237.ts
  apps/meteor/server/startup/migrations/v238.ts
  apps/meteor/server/startup/migrations/v239.ts
  apps/meteor/server/startup/migrations/v240.ts
Labels: stat: ready to merge, stat: QA skipped

#26174 Regression: Unavailable devices in unsupported browsers
  apps/meteor/client/providers/DeviceProvider/DeviceProvider.tsx
  apps/meteor/client/providers/DeviceProvider/lib/isSetSinkIdAvailable.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA tested

#26238 Regression: Revert replace contact center icon
  apps/meteor/client/sidebar/sections/OmnichannelSection.tsx
  apps/meteor/client/views/room/MessageList/components/MessageHeader.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#26234 Regression: Don't open mdm feature modal on registration page
  apps/meteor/client/startup/banners.ts
Labels: stat: needs QA

#26232 Regression: Admin Avatar Edit endpoint fix
  apps/meteor/client/views/admin/users/EditUser.js
Labels: stat: ready to merge, stat: QA tested

#26209 Regression: Livechat rooms not opening due to route desync
  apps/meteor/client/lib/rooms/roomTypes/livechat.ts
Labels: stat: ready to merge, stat: QA tested

#26203 Regression: Last_login translation key
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfo.js
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoWithData.js
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountTable.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfo.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#26170 Regression: Burger menu showing arrow instead of burguer
  apps/meteor/client/components/BurgerMenu/BurgerMenu.tsx
  apps/meteor/client/providers/LayoutProvider.tsx
  apps/meteor/client/templates.ts
  packages/ui-contexts/src/LayoutContext.ts
Labels: stat: ready to merge, stat: QA tested

#26253 Chore: Avoid unneeded permission updates when EE license is applied
  apps/meteor/app/authorization/server/functions/upsertPermissions.ts
  apps/meteor/ee/app/authorization/server/resetEnterprisePermissions.ts
Labels: stat: ready to merge, stat: QA skipped

#26256 Regression: get user from `req` on `ui.interaction` endpoints
  apps/meteor/app/apps/server/communication/uikit.ts
Labels: stat: needs QA

#26257 Chore: Disabled icon colors on sidebar
  apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts
Labels: stat: ready to merge, stat: QA skipped

#26162 Regression: Fix marketplace releases tab crash bug
  apps/meteor/client/views/admin/apps/AppDetailsPage.tsx
  apps/meteor/client/views/admin/apps/AppReleases.tsx
  apps/meteor/client/views/admin/apps/AppSecurity.tsx
  apps/meteor/client/views/admin/apps/ReleaseItem.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, stat: QA skipped

#26139 Regression: Sidebar icons spacing
  apps/meteor/client/sidebar/Item/Condensed.tsx
  apps/meteor/client/sidebar/Item/Extended.tsx
  apps/meteor/client/sidebar/Item/Medium.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoom.tsx
  apps/meteor/client/sidebar/header/actions/Sort.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallDialPad.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggle.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleError.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleLoading.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleReady.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx
  apps/meteor/client/views/admin/customSounds/AdminSoundsRoute.tsx
  apps/meteor/client/views/omnichannel/currentChats/RemoveAllClosed.tsx
  apps/meteor/client/views/omnichannel/directory/CallDialpadButton.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/TextEditor/IconButton.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/ContentForDays.tsx
  apps/meteor/ee/client/voip/modal/DialPad/DialInput.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#26270 Chore: Avoid set useless set UTC Offset
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/startup.ts
  apps/meteor/client/startup/userSetUtcOffset.ts
Labels: stat: needs QA

#26258 Chore: Update Apps-Engine version
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26237 Regression: Call toggle missing network disconnection state
  apps/meteor/client/contexts/CallContext.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleReady.tsx
Labels: stat: ready to merge, stat: QA tested

#26235 Regression: REST API calls at Engagement Dashboard
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/useChannelsList.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessageOrigins.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessagesSent.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useTopFivePopularChannels.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useActiveUsers.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useHourlyChatActivity.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useNewUsers.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useUsersByTimeOfTheDay.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useWeeklyChatActivity.ts
  apps/meteor/ee/definition/rest/v1/engagementDashboard.ts
Labels: stat: ready to merge, stat: QA tested

#26172 Regression: Cannot open Menu in searched message.
  apps/meteor/app/ui/client/views/app/lib/getCommonRoomEvents.js
Labels: stat: ready to merge, stat: QA tested

#26267 Regression: Omni-chats not getting routed automatically to bots
  apps/meteor/app/livechat/server/hooks/beforeDelegateAgent.js
  apps/meteor/app/models/server/models/LivechatDepartmentAgents.js
  apps/meteor/app/models/server/models/Users.js
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA tested

#26273 Regression: Search on Member List
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/server/lib/findUsersOfRoom.ts
  apps/meteor/server/methods/browseChannels.js
  apps/meteor/tests/end-to-end/api/02-channels.js
Labels: stat: ready to merge, stat: QA skipped

#26249 Regression: Federated users not showing as federated in Room Members
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/federation-v2/server/application/RoomServiceReceiver.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/adapters/User.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/DefaultRow.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/DefaultRow.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/components/MemberItem.tsx
  apps/meteor/server/lib/findUsersOfRoom.ts
Labels: stat: needs QA

#26252 Regression: UserInfo/RoomInfo Menu
  apps/meteor/client/views/admin/users/UserInfoActions.js
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfo.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/components/UserActions.js
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfo.js
  apps/meteor/client/views/room/contextualBar/UserInfo/actions/UserActions.js
Labels: stat: ready to merge, stat: QA skipped

#26248 Regression: Remove alpha tag and fix initialization process
  apps/meteor/app/federation-v2/server/index.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/adapters/Settings.ts
  apps/meteor/ee/app/federation-v2/server/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: federation, type: regression, stat: ready to merge, stat: QA skipped

#26254 Regression: Do not allow to remove users from federated DMs
  apps/meteor/app/federation-v2/client/Federation.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/Federation.ts
  apps/meteor/client/lib/rooms/roomTypes/direct.ts
  apps/meteor/client/lib/rooms/roomTypes/private.ts
  apps/meteor/client/lib/rooms/roomTypes/public.ts
  apps/meteor/server/lib/rooms/roomTypes/direct.ts
  apps/meteor/server/lib/rooms/roomTypes/private.ts
  apps/meteor/server/lib/rooms/roomTypes/public.ts
  apps/meteor/tests/unit/app/federation-v2/client/unit/Federation.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/Federation.spec.ts
Labels: feat: federation, type: regression, stat: ready to merge, stat: QA skipped

#26217 Regression: disable readonly on channel fed creation
  apps/meteor/client/sidebar/header/CreateChannelWithData.tsx
Labels: feat: federation, type: regression, stat: needs QA

#26212 Regression: Do not show mentions on federated rooms
  apps/meteor/app/mentions-flextab/client/tabBar.ts
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: federation, type: regression, stat: needs QA

#26240 Regression: Federated username detection failing every other time
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
Labels: stat: needs QA

#26049 Regression: AutoTranslate on new message template
  apps/meteor/app/autotranslate/client/lib/actionButton.ts
  apps/meteor/app/autotranslate/client/lib/autotranslate.ts
  apps/meteor/app/autotranslate/server/autotranslate.ts
  apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
  apps/meteor/client/views/room/MessageList/components/MessageIndicators.tsx
  apps/meteor/client/views/room/MessageList/contexts/MessageListContext.tsx
  apps/meteor/client/views/room/MessageList/hooks/useParsedMessage.ts
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: ready to merge, stat: QA tested

#26263 Regression: Do not allow non-owners edit rooms or add/remove users on federated rooms
  apps/meteor/app/federation-v2/client/Federation.ts
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfoWithData.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/RoomMembersWithData.js
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useRemoveUserAction.tsx
  apps/meteor/tests/unit/app/federation-v2/client/unit/Federation.spec.ts
Labels: feat: federation, type: regression, stat: needs QA

#26281 Regression: Do not prevent external users from being added in channels on CE
  apps/meteor/app/federation-v2/server/application/RoomServiceSender.ts
  apps/meteor/app/federation-v2/server/domain/IFederationBridge.ts
  apps/meteor/app/federation-v2/server/infrastructure/Factory.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
Labels: feat: federation, type: regression, stat: needs QA

#26167 Chore: Sug on PR #26155 - Unable to un-assign Contact manager
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/client/components/AutoCompleteAgent.js
  apps/meteor/client/components/Omnichannel/hooks/useAgentsList.ts
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.js
  apps/meteor/ee/client/omnichannel/additionalForms/ContactManager.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#26274 Chore: Upgrade Fuselage packages to `next` dist-tag
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  packages/core-typings/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/ui-video-conf/src/VideoConfController.tsx
  yarn.lock
Labels: stat: needs QA

#26050 [FIX] Users without the `view-other-user-info` permission can't use the `users.list` endpoint
  apps/meteor/app/api/server/lib/users.ts
  apps/meteor/app/api/server/v1/users.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26298 Regression: Adjusted priority to run canned responses replace before new parser
  apps/meteor/ee/app/canned-responses/server/hooks/onMessageSentParsePlaceholder.ts
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26155 Regression: Contact manager edit/view not working
  apps/meteor/app/livechat/server/api/lib/users.js
  apps/meteor/app/livechat/server/api/rest.js
  apps/meteor/app/livechat/server/api/v1/contact.js
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/client/components/AutoCompleteAgent.js
  apps/meteor/client/components/Omnichannel/hooks/useAgentsList.ts
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.js
  apps/meteor/ee/client/omnichannel/additionalForms/ContactManager.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26294 Chore: Remove TimeSync usage
  apps/meteor/.eslintignore
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/app/e2e/client/rocketchat.e2e.room.js
  apps/meteor/app/lib/client/methods/sendMessage.js
  apps/meteor/app/otr/client/rocketchat.otr.room.js
  apps/meteor/client/methods/updateMessage.ts
  apps/meteor/client/startup/startup.ts
  apps/meteor/definition/externals/meteor/mizzao-timesync.d.ts
  apps/meteor/packages/meteor-timesync/.gitignore
  apps/meteor/packages/meteor-timesync/.travis.yml
  apps/meteor/packages/meteor-timesync/History.md
  apps/meteor/packages/meteor-timesync/LICENSE
  apps/meteor/packages/meteor-timesync/README.md
  apps/meteor/packages/meteor-timesync/client/index.js
  apps/meteor/packages/meteor-timesync/client/timesync-client.js
  apps/meteor/packages/meteor-timesync/package.js
  apps/meteor/packages/meteor-timesync/server/index.js
  apps/meteor/packages/meteor-timesync/server/timesync-server.js
  apps/meteor/packages/meteor-timesync/tests/client.js
  apps/meteor/server/main.ts
  apps/meteor/server/routes/timesync.ts
Labels: stat: ready to merge, stat: QA skipped

#26251 Regression: Remove 4.0 version banner
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v278.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26305 Regression: Fix breaking omnichannel tests
  apps/meteor/tests/end-to-end/api/livechat/agents.js
Labels: stat: needs QA

#26304 Regression: Fix permissions page pagination
  apps/meteor/client/views/admin/permissions/hooks/usePermissionsAndRoles.ts
Labels: stat: needs QA

#26295 Regression: Clear user selection filter after selecting desired user.
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26183 Chore: VideoConference UX/UI Refactor 1st Interaction
  apps/meteor/app/api/server/v1/videoConference.ts
  apps/meteor/app/apps/server/bridges/videoConferences.ts
  apps/meteor/app/authorization/server/functions/upsertPermissions.ts
  apps/meteor/app/custom-sounds/client/lib/CustomSounds.js
  apps/meteor/app/models/server/models/Users.js
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/CallingPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/IncomingPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/OutgoingPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/StartCallPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/StartCallPopup/StartCallPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/StartCallPopup/StartDirectCallPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/StartCallPopup/StartOmnichannelCallPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/StartCallPopup/index.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/TimedVideoConfPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/VideoConfPopupRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useAudioCallAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useCallAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useVideoCallAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/useUserInfoActions.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/sounds/dialtone.mp3
  apps/meteor/public/sounds/ringtone.mp3
  apps/meteor/server/lib/videoConfProviders.ts
  apps/meteor/server/models/raw/Users.js
  apps/meteor/server/modules/notifications/notifications.module.ts
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v279.ts
  packages/model-typings/src/models/IUsersModel.ts
  packages/ui-video-conf/.eslintrc
  packages/ui-video-conf/package.json
  packages/ui-video-conf/src/VideoConfButton.tsx
  packages/ui-video-conf/src/VideoConfController.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupBackdrop.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupClose.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupContent.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupControllers.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooter.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooterButtons.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupHeader.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupIcon.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupIndicators.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupInfo.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupTitle.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupUsername.tsx
  packages/ui-video-conf/src/VideoConfPopup/index.ts
  packages/ui-video-conf/src/hooks/useVideoConfControllers.ts
  packages/ui-video-conf/src/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26311 Regression: Add v1 to licenses.add endpoint
  apps/meteor/client/views/admin/info/OfflineLicenseModal.js
Labels: feat: omnichannel, stat: ready to merge, stat: QA skipped

#26241 Regression: Special characters on phone number
  apps/meteor/client/components/voip/room/VoipRoomForeword.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/ee/client/lib/voip/EEVoipClient.ts
  apps/meteor/ee/client/voip/modal/DialPad/DialInput.tsx
  apps/meteor/ee/client/voip/modal/DialPad/DialPadModal.tsx
  apps/meteor/ee/client/voip/modal/DialPad/Pad.tsx
  apps/meteor/ee/client/voip/modal/DialPad/PadButton.tsx
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useDialPad.tsx
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useLongPress.tsx
  apps/meteor/package.json
  apps/meteor/server/services/omnichannel-voip/service.ts
  yarn.lock
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26315 Regression: Fix job Id not returned by agenda
  packages/agenda/src/Agenda.ts
Labels: stat: ready to merge, stat: QA skipped, feat: chat-engine

#26269 Regression: Channel `type` icon on Engagement Dashboard
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/ChannelsTab.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/MessagesPerChannelSection.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26319 Regression: Use fname instead real unique name for Voip
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.js
  apps/meteor/client/views/room/Header/Omnichannel/VoipRoomHeader.tsx
  apps/meteor/ee/client/lib/voip/parseOutboundPhoneNumber.ts
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26309 Regression: Options overlapping input in Users Autocomplete
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleOptions.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26310 Regression: fix `directory` endpoint not listing teams
  apps/meteor/server/methods/browseChannels.js
Labels: stat: ready to merge, stat: QA skipped, feat: team-collab

#26328 Regression: Fix get myself user data
  apps/meteor/app/lib/server/functions/getFullUserData.ts
Labels: stat: ready to merge, stat: QA skipped

#26322 Chore: Update useSidebarPalette selectors
  apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts
  yarn.lock
Labels: stat: needs QA, feat: chat-engine

#26325 Chore: bump fuselage packages
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  packages/core-typings/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped, feat: chat-engine

#26327 Regression: Livechat not rendering UiKit messages with action buttons
  packages/livechat/src/lib/room.js
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#25953 Chore: convert autotranslate to ts
  apps/meteor/app/api/server/v1/autotranslate.ts
  apps/meteor/tests/end-to-end/api/00-autotranslate.js
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/autoTranslate.ts
  packages/rest-typings/src/v1/autotranslate/AutotranslateGetSupportedLanguagesParamsGET.ts
  packages/rest-typings/src/v1/autotranslate/AutotranslateSaveSettingsParamsPOST.ts
  packages/rest-typings/src/v1/autotranslate/AutotranslateTranslateMessageParamsPOST.ts
Labels: stat: ready to merge, stat: QA skipped

#26342 Chore: Replace direct multiple icon
  apps/meteor/client/views/room/lib/Toolbox/defaultActions.ts
Labels: stat: ready to merge, stat: QA skipped

#26277 Chore: Rewrite VerticalBarOldActions to TS
  apps/meteor/app/ui-message/client/actionButtons/tabbar.ts
  apps/meteor/client/views/room/components/VerticalBarOldActions.js
  apps/meteor/client/views/room/components/VerticalBarOldActions.tsx
  apps/meteor/client/views/room/lib/Toolbox/index.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#26343 Chore: Remove square prop from IconButton
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.js
  apps/meteor/client/views/room/contextualBar/Threads/components/Message.js
Labels: stat: ready to merge, stat: QA skipped

#26345 [FIX] Missing bio field UI validation
  apps/meteor/client/components/UserStatus/index.ts
  apps/meteor/client/lib/constants.ts
  apps/meteor/client/sidebar/header/EditStatusModal.tsx
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/index.ts
Labels: stat: ready to merge, stat: QA skipped

#26096 Chore: Convert AccountPreferencesPage to ts
  apps/meteor/client/views/account/preferences/AccountPreferencesPage.tsx
Labels: stat: ready to merge, stat: QA skipped

#26306 Chore: cleanup startup of test and put wizard in setup function
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/00-wizard.spec.ts
  apps/meteor/tests/e2e/configs/setup.ts
  apps/meteor/tests/e2e/configs/teardown.ts
  apps/meteor/tests/e2e/page-objects/auth.ts
  apps/meteor/tests/e2e/utils/MongoHelper.ts
Labels: stat: ready to merge, stat: QA skipped

#26192 Chore: Convert UserCardWithData to ts
  apps/meteor/client/components/UserCard/UserCard.tsx
  apps/meteor/client/components/UserCard/UserCardAction.tsx
  apps/meteor/client/views/hooks/useActionSpread.ts
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
  apps/meteor/client/views/room/UserCard/index.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26276 [FIX] Unable to send voice recording to Whatsapp
  apps/meteor/app/ui-message/client/messageBox/messageBoxAudioMessage.js
  apps/meteor/app/ui/client/lib/recorderjs/audioEncoder.js
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26335 Chore: fix tests with beforeEach
  apps/meteor/tests/e2e/01-forgot-password.spec.ts
  apps/meteor/tests/e2e/02-register.spec.ts
  apps/meteor/tests/e2e/03-login.spec.ts
  apps/meteor/tests/e2e/05-channel-creation.spec.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/07-emoji.spec.ts
  apps/meteor/tests/e2e/09-channel.spec.ts
  apps/meteor/tests/e2e/10-user-preferences.spec.ts
  apps/meteor/tests/e2e/11-admin.spec.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/14-setting-permissions.spec.ts
  apps/meteor/tests/e2e/15-message-popup.spec.ts
  apps/meteor/tests/e2e/16-discussion.spec.ts
  apps/meteor/tests/e2e/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#26368 Regression: Fix app privacy links opening in desktop client instead of browser
  apps/meteor/client/views/admin/apps/AppSecurity.tsx
Labels: stat: ready to merge, stat: QA skipped

#26293 Chore: add playwright ee coverage
  .github/workflows/build_and_test.yml
  apps/meteor/.babelrc
  apps/meteor/package.json
  apps/meteor/tests/e2e/01-forgot-password.spec.ts
  apps/meteor/tests/e2e/02-register.spec.ts
  apps/meteor/tests/e2e/03-login.spec.ts
  apps/meteor/tests/e2e/05-channel-creation.spec.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/07-emoji.spec.ts
  apps/meteor/tests/e2e/09-channel.spec.ts
  apps/meteor/tests/e2e/10-user-preferences.spec.ts
  apps/meteor/tests/e2e/11-admin.spec.ts
  apps/meteor/tests/e2e/12-settings.spec.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/14-setting-permissions.spec.ts
  apps/meteor/tests/e2e/15-message-popup.spec.ts
  apps/meteor/tests/e2e/16-discussion.spec.ts
  apps/meteor/tests/e2e/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/page-objects/administration.ts
  apps/meteor/tests/e2e/page-objects/home-discussion.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
  apps/meteor/tests/e2e/utils/test.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26363 [FIX] Onhold auto chat resume feature not working for email channel
  apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.js
  apps/meteor/server/email/IMAPInterceptor.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
Labels: stat: ready to merge, stat: QA skipped

#26336 [IMPROVE] Use single change stream to watch DB changes
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/models/index.ts
  apps/meteor/app/models/server/index.ts
  apps/meteor/app/models/server/lib/watchModels.ts
  apps/meteor/app/models/server/models/_Base.js
  apps/meteor/app/models/server/models/_BaseDb.js
  apps/meteor/app/models/server/models/_oplogHandle.ts
  apps/meteor/app/utils/server/functions/getMongoInfo.js
  apps/meteor/app/utils/server/index.js
  apps/meteor/ee/server/lib/registerServiceModels.ts
  apps/meteor/ee/server/services/mongo.ts
  apps/meteor/ee/server/services/stream-hub/StreamHub.ts
  apps/meteor/ee/server/services/stream-hub/service.ts
  apps/meteor/server/database/DatabaseWatcher.ts
  apps/meteor/server/database/convertChangeStreamPayload.ts
  apps/meteor/server/database/convertOplogPayload.ts
  apps/meteor/server/database/watchCollections.ts
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  apps/meteor/server/startup/index.ts
  apps/meteor/server/startup/watchDb.ts
  packages/model-typings/src/models/IBaseModel.ts
Labels: stat: ready to merge, stat: QA skipped

#26395 Chore: Options in BaseRaw model could possibly be undefined
  apps/meteor/server/models/raw/BaseRaw.ts
Labels: stat: ready to merge, bug, stat: QA skipped

#26397 i18n: Manual sync from LingoHub
  apps/meteor/packages/rocketchat-i18n/i18n/af.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/az.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/be-BY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bg.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bn-BD.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cy.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-AT.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/el.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/eo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/et.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/eu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/he.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hi-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/id.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ku.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/mn.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ro.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sq.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/th-TH.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ug.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-HK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#26204 Chore: Rewrite custom OAuth Modals to react
  apps/meteor/client/views/admin/settings/groups/CreateOAuthModal.tsx
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, eng day, stat: QA skipped

#26410 Chore: Sugggestions on PR #26357
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/api/lib/departments.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: needs QA

#26412 Chore: Suggestions on PR #26376
  apps/meteor/app/livechat/imports/server/rest/inquiries.js
  apps/meteor/app/livechat/server/api/lib/inquiries.js
  apps/meteor/server/models/raw/LivechatRooms.js
Labels: stat: needs QA

#26181 [NEW] Marketplace apps page new list view layout
  apps/meteor/app/apps/client/orchestrator.ts
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/components/avatar/AppAvatar.tsx
  apps/meteor/client/views/admin/apps/AppDetailsHeader.tsx
  apps/meteor/client/views/admin/apps/AppMenu.js
  apps/meteor/client/views/admin/apps/AppRow.tsx
  apps/meteor/client/views/admin/apps/AppStatus.js
  apps/meteor/client/views/admin/apps/AppsFilters.tsx
  apps/meteor/client/views/admin/apps/AppsList.tsx
  apps/meteor/client/views/admin/apps/AppsListMain.tsx
  apps/meteor/client/views/admin/apps/AppsPage.tsx
  apps/meteor/client/views/admin/apps/BundleChips.tsx
  apps/meteor/client/views/admin/apps/MarketplaceRow.tsx
  apps/meteor/client/views/admin/apps/components/CategoryFilter/CategoryDropDown.tsx
  apps/meteor/client/views/admin/apps/components/CategoryFilter/CategoryDropDownAnchor.tsx
  apps/meteor/client/views/admin/apps/components/RadioDropDown/RadioDropDown.tsx
  apps/meteor/client/views/admin/apps/definitions/CategoryDropdownDefinitions.ts
  apps/meteor/client/views/admin/apps/helpers/filterAppsByDisabled.ts
  apps/meteor/client/views/admin/apps/helpers/filterAppsByEnabled.ts
  apps/meteor/client/views/admin/apps/hooks/useCategories.ts
  apps/meteor/client/views/admin/apps/hooks/useFilteredApps.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped, feat: marketplace

#26399 Chore: Exclude private/public folders from typecheck
  apps/meteor/package.json
  apps/meteor/tsconfig.typecheck.json
Labels: stat: ready to merge, stat: QA skipped

#20131 Chore: Missing some English translation keywords
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: communityPR

#20895 Chore: Makes the text less ambiguous
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: communityPR

#26208 Chore: Replace `useMethodData`
  apps/meteor/client/hooks/useMethodData.ts
  apps/meteor/client/hooks/usePolledMethodData.ts
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/views/admin/cloud/CloudPage.tsx
  apps/meteor/client/views/admin/federationDashboard/OverviewSection.tsx
  apps/meteor/client/views/admin/federationDashboard/ServersSection.tsx
  apps/meteor/client/views/login/ResetPassword/ResetPassword.tsx
  apps/meteor/client/views/omnichannel/facebook/FacebookPageContainer.tsx
  apps/meteor/client/views/room/modals/ReadReceiptsModal/ReadReceiptsModal.tsx
  apps/meteor/definition/methods/federation.ts
  apps/meteor/ee/client/audit/AuditLogPage.tsx
  apps/meteor/ee/client/audit/DateRangePicker.tsx
  apps/meteor/ee/definition/methods.ts
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26413 Chore: Convert client/views/account/security folder to ts
  apps/meteor/client/views/account/security/AccountSecurityPage.tsx
  apps/meteor/client/views/account/security/EndToEnd.tsx
  apps/meteor/client/views/account/security/TwoFactorEmail.tsx
  apps/meteor/client/views/account/security/TwoFactorTOTP.tsx
  apps/meteor/definition/externals/yaqrcode.d.ts
Labels: stat: ready to merge, eng day, stat: QA skipped
