Repository RocketChat/Rocket.Chat, pull requests merged in 2022-08, with the labels that each got.

#26421 Regression: Fix spacing problem on AppStatus component
  apps/meteor/client/views/admin/apps/AppRow.tsx
  apps/meteor/client/views/admin/apps/AppStatus.js
Labels: stat: ready to merge, stat: QA skipped

#26357 [IMPROVE] validateParams to accept different validators per request method
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/api.js
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/api/lib/departments.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/tests/data/livechat/rooms.js
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.js
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.js
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.js
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.js
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.js
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.js
  apps/meteor/tests/end-to-end/api/livechat/07-queue.js
  apps/meteor/tests/end-to-end/api/livechat/08-triggers.js
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA skipped

#26196 Chore: Rewrite Location modal to React
  apps/meteor/app/ui-message/client/messageBox/messageBoxActions.js
  apps/meteor/client/views/admin/settings/inputs/ActionSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/ColorSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/MultiSelectSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/SelectSettingInput.tsx
  apps/meteor/client/views/location/MapView.tsx
  apps/meteor/client/views/room/ShareLocation/ShareLocationModal.tsx
  apps/meteor/client/views/room/ShareLocation/getGeolocationPermission.ts
  apps/meteor/client/views/room/ShareLocation/getGeolocationPosition.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/IMessage/IMessage.ts
  packages/rest-typings/src/v1/chat.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26435 Chore: Upgrade Fuselage packages to next dist-tag
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  packages/core-typings/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26338 [IMPROVE] Upgrade nivo and React Query
  apps/meteor/client/components/GenericTable/GenericTable.stories.tsx
  apps/meteor/client/components/GenericTable/GenericTable.tsx
  apps/meteor/client/components/PlanTag.tsx
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
  apps/meteor/client/lib/queryClient.ts
  apps/meteor/client/sidebar/RoomList/ScrollerWithCustomProps.tsx
  apps/meteor/client/sidebar/search/ScrollerWithCustomProps.tsx
  apps/meteor/client/stories/contexts/QueryClientProviderMock.tsx
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/client/views/admin/settings/groups/voip/VoipExtensionsPage.tsx
  apps/meteor/client/views/hooks/useUpgradeTabParams.ts
  apps/meteor/client/views/invite/InvitePage.tsx
  apps/meteor/client/views/invite/SecretURLPage.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTable.tsx
  apps/meteor/client/views/omnichannel/queueList/QueueListPage.tsx
  apps/meteor/client/views/omnichannel/queueList/index.tsx
  apps/meteor/client/views/room/ShareLocation/ShareLocationModal.tsx
  apps/meteor/client/views/root/AppRoot.tsx
  apps/meteor/client/views/setupWizard/hooks/useParameters.ts
  apps/meteor/client/views/teams/ChannelDesertionTable.tsx
  apps/meteor/ee/client/lib/onToggledFeature.ts
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesPage.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx
  apps/meteor/ee/client/sidebar/footer/SidebarFooterWatermark.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/useChannelsList.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessageOrigins.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessagesSent.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useTopFivePopularChannels.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/ActiveUsersSection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/UsersByTimeOfTheDaySection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useActiveUsers.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useHourlyChatActivity.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useNewUsers.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useUsersByTimeOfTheDay.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useWeeklyChatActivity.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26438 [FIX] Empty results on `im.list` endpoint
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/tests/end-to-end/api/04-direct-message.js
Labels: stat: ready to merge, stat: QA skipped

#26432 Chore: Cache playwright
  .github/workflows/build_and_test.yml
Labels: stat: ready to merge, stat: QA skipped

#26347 Chore: Add end-to-end tests to teams listing in the `directory` endpoint
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
Labels: stat: ready to merge, stat: QA skipped

#26447 Chore: Purge some unused modules
  apps/meteor/client/components/GenericTable/LoadingRow.tsx
  apps/meteor/client/components/Logo.stories.tsx
  apps/meteor/client/components/Logo.tsx
  apps/meteor/client/components/Page/PageHeaderWithBorder.tsx
  apps/meteor/client/components/message/MessageEmoji.tsx
  apps/meteor/client/components/message/Oembed/definitions.ts
  apps/meteor/client/components/message/StatusMessage.tsx
  apps/meteor/client/definitions/SubscriptionAndRoom.ts
  apps/meteor/client/hooks/useDir.ts
  apps/meteor/client/lib/voip/PhoneNumberParser.ts
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/sidebar/Item/ExtendedSkeleton.tsx
  apps/meteor/client/sidebar/Item/skeletons/CondensedSkeleton.tsx
  apps/meteor/client/sidebar/Item/skeletons/MediumSkeleton.tsx
  apps/meteor/client/sidebar/Item/skeletons/Skeleton.stories.tsx
  apps/meteor/client/views/admin/apps/helpers/filterAppsByCategory.ts
  apps/meteor/client/views/admin/permissions/PermissionsRouter.tsx
  apps/meteor/client/views/omnichannel/DepartmentAutoComplete.js
  apps/meteor/client/views/room/MessageList/components/Avatar.tsx
  apps/meteor/client/views/room/components/MessageTemplate/BodyClamp.js
  apps/meteor/client/views/room/components/MessageTemplate/Container.js
  apps/meteor/client/views/room/components/MessageTemplate/Header.js
  apps/meteor/client/views/room/components/MessageTemplate/Message.js
  apps/meteor/client/views/room/components/MessageTemplate/Timestamp.js
  apps/meteor/client/views/room/components/MessageTemplate/Username.js
  apps/meteor/client/views/room/components/MessageTemplate/index.ts
  apps/meteor/client/views/room/components/MessageTemplate/isIterable.js
  apps/meteor/client/views/room/contextualBar/hooks/useDataWithLoadMore.ts
  apps/meteor/client/views/room/hooks/useWebRTC.ts
  apps/meteor/client/views/root/DomNode.tsx
  apps/meteor/tests/unit/client/views/admin/apps/helpers/filterAppsByCategory.test.ts
Labels: stat: ready to merge, stat: QA skipped

#26454 [IMPROVE] use enter key to call using DialPad
  apps/meteor/ee/client/voip/modal/DialPad/DialPadModal.tsx
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useDialPad.tsx
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useEnterKey.tsx
Labels: stat: ready to merge, stat: QA tested

#26459 [FIX] DialPad call button from end to center
  apps/meteor/ee/client/voip/modal/DialPad/DialPadModal.tsx
Labels: stat: ready to merge, stat: QA tested

#26437 Chore: Use Docker compose on CI
  .github/actions/build-docker-image-service/action.yml
  .github/workflows/build_and_test.yml
  apps/meteor/tests/end-to-end/api/01-users.js
  docker-compose-ci.yml
Labels: stat: ready to merge, stat: QA skipped

#26373 [FIX] Don't give errors on outbound voip call Request Terminated
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#26464 Chore: Tests intermitences
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/file-upload.spec.ts
Labels: stat: needs QA

#26477 Chore: Codecov threshold
  codecov.yml
Labels: stat: needs QA

#26396 [FIX] Undefined MediaDevices error on HTTP
  apps/meteor/client/providers/DeviceProvider/DeviceProvider.tsx
  apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/ui-contexts/src/DeviceContext.ts
  packages/ui-contexts/src/hooks/useAvailableDevices.ts
  packages/ui-contexts/src/hooks/useDeviceConstraints.ts
  packages/ui-contexts/src/hooks/useIsDeviceManagementEnabled.ts
  packages/ui-contexts/src/hooks/useSelectedDevices.ts
  packages/ui-contexts/src/hooks/useSetInputMediaDevice.ts
  packages/ui-contexts/src/hooks/useSetOutputMediaDevice.ts
  packages/ui-contexts/src/index.ts
Labels: stat: ready to merge, stat: QA tested

#26466 [FIX] Clear push token on save user password
  apps/meteor/server/models/raw/PushToken.ts
  apps/meteor/server/services/meteor/service.ts
  apps/meteor/server/services/push/service.ts
  apps/meteor/tests/end-to-end/api/01-users.js
  packages/model-typings/src/models/IPushTokenModel.ts
Labels: stat: ready to merge, stat: QA skipped

#26467 Chore: Exit process on `unhandledRejection` on CI
  apps/meteor/app/settings/server/CachedSettings.ts
  apps/meteor/app/voip/server/startup.ts
  apps/meteor/server/services/voip/connector/asterisk/CommandHandler.ts
  apps/meteor/server/services/voip/lib/Helper.ts
  docker-compose-ci.yml
Labels: stat: ready to merge, stat: QA skipped

#26490 [FIX] Request at least one field in the payload of `/v1/users.setStatus`
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/tests/end-to-end/api/01-users.js
Labels: stat: ready to merge, stat: QA skipped

#26416 [NEW] Surface featured apps endpoint
  apps/meteor/app/apps/server/communication/rest.js
  packages/core-typings/src/FeaturedApps.ts
  packages/core-typings/src/index.ts
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, automerge, stat: QA skipped, feat: marketplace

#26494 Chore: useEndpointData deprecation
  apps/meteor/client/hooks/useEndpointData.ts
Labels: stat: ready to merge, stat: QA skipped

#26493 Chore: Refactor create-target-channel util
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/emojis.spec.ts
  apps/meteor/tests/e2e/file-upload.spec.ts
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/permissions.spec.ts
  apps/meteor/tests/e2e/utils/create-target-channel.ts
  apps/meteor/tests/e2e/utils/test.ts
Labels: subj: Testing, stat: ready to merge, stat: QA skipped

#26507 Release 5.0.2
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/client/providers/DeviceProvider/DeviceProvider.tsx
  apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/tests/end-to-end/api/04-direct-message.js
  package.json
  packages/ui-contexts/src/DeviceContext.ts
  packages/ui-contexts/src/hooks/useAvailableDevices.ts
  packages/ui-contexts/src/hooks/useDeviceConstraints.ts
  packages/ui-contexts/src/hooks/useIsDeviceManagementEnabled.ts
  packages/ui-contexts/src/hooks/useSelectedDevices.ts
  packages/ui-contexts/src/hooks/useSetInputMediaDevice.ts
  packages/ui-contexts/src/hooks/useSetOutputMediaDevice.ts
  packages/ui-contexts/src/index.ts
Labels: stat: needs QA

#26496 Chore: Convert `client/views/account/preferences` folder to ts
  apps/meteor/client/views/account/preferences/AccountPreferencesPage.tsx
  apps/meteor/client/views/account/preferences/MyDataModal.tsx
  apps/meteor/client/views/account/preferences/PreferencesGlobalSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesHighlightsSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesLocalizationSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesMessagesSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesMyDataSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesNotificationsSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesSoundSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesUserPresenceSection.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#26498 Chore: Migrate AppPermissionsReviewModal from JS to TS
  apps/meteor/client/views/admin/apps/AppInstallPage.js
  apps/meteor/client/views/admin/apps/AppPermissionsReviewModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#26133 [FIX] Decrypt E2EE messages on thread list
  apps/meteor/client/hooks/useDecryptedMessage.ts
  apps/meteor/client/views/room/contextualBar/Threads/Row.tsx
Labels: stat: ready to merge, stat: QA skipped

#26425 [FIX] Chats holds to load history for some time
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.js
  apps/meteor/app/ui-utils/client/lib/waitUntilWrapperExists.ts
  apps/meteor/tests/unit/app/ui-utils/client.tests.ts
Labels: stat: needs QA

#26422 Chore: Refactor WebdavFilePicker Modal to React Component
  apps/meteor/app/webdav/client/index.js
  apps/meteor/app/webdav/client/startup/messageBoxActions.js
  apps/meteor/app/webdav/client/webdavFilePicker.css
  apps/meteor/app/webdav/client/webdavFilePicker.html
  apps/meteor/app/webdav/client/webdavFilePicker.js
  apps/meteor/app/webdav/server/methods/getWebdavFilePreview.ts
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/FilePickerBreadcrumbs.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerGrid/WebdavFilePickerGrid.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerGrid/WebdavFilePickerGridItem.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerGrid/index.ts
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerModal.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerTable.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/index.ts
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/lib/getNodeFileSize.ts
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/lib/getNodeIconType.ts
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/lib/sortWebdavNodes.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/IWebdavAccount.ts
  packages/ui-contexts/src/ServerContext/methods.ts
  packages/ui-contexts/src/ServerContext/methods/addWebdavAccount.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/addWebdavAccount.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/getFileFromWebdav.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/getWebdavFileList.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/getWebdavFilePreview.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/index.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/removeWebdavAccount.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/uploadFileToWebdav.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26526 Chore: Bypass turbo cache on `ui-contexts`
  turbo.json
Labels: stat: ready to merge, stat: QA skipped

#26321 [FIX] Prevent VoIP issues during disconnection when network failed
  apps/meteor/server/services/voip/connector/asterisk/ami/AMIConnection.ts
Labels: stat: ready to merge, stat: QA tested

#24757 [IMPROVE] OTR refactoring
  apps/meteor/app/otr/client/OTR.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/otr/client/index.js
  apps/meteor/app/otr/client/index.ts
  apps/meteor/app/otr/client/rocketchat.otr.js
  apps/meteor/app/otr/client/rocketchat.otr.room.js
  apps/meteor/app/otr/client/tabBar.ts
  apps/meteor/app/otr/lib/IOTR.ts
  apps/meteor/app/otr/lib/OtrRoomState.ts
  apps/meteor/app/otr/lib/functions.ts
  apps/meteor/app/otr/server/index.ts
  apps/meteor/app/otr/server/methods/deleteOldOTRMessages.ts
  apps/meteor/app/otr/server/methods/updateOTRAck.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/otr.ts
  apps/meteor/client/views/room/contextualBar/OTR/OTR.stories.tsx
  apps/meteor/client/views/room/contextualBar/OTR/OTR.tsx
  apps/meteor/client/views/room/contextualBar/OTR/OTRWithData.tsx
  apps/meteor/definition/externals/meteor/ejson.d.ts
  apps/meteor/server/stream/stdout.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/rest-typings/src/v1/statistics.ts
Labels: feat: OTR, stat: ready to merge, stat: QA skipped

#26375 [FIX] Don't wrap wrap up notes
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
Labels: stat: ready to merge, stat: QA tested

#26531 Chore: Fix lint issues
  apps/meteor/app/otr/client/OTR.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/otr/lib/IOTR.ts
  apps/meteor/app/otr/lib/functions.ts
  apps/meteor/app/otr/server/methods/updateOTRAck.ts
Labels: stat: ready to merge, stat: QA skipped

#26478 Chore: Refactor ReportMessage Modal to React Component
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/views/room/modals/ReportMessageModal/ReportMessageModal.tsx
  apps/meteor/client/views/room/modals/ReportMessageModal/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/ui-contexts/src/ServerContext/methods.ts
  packages/ui-contexts/src/ServerContext/methods/message/reportMessage.ts
  packages/ui-contexts/src/ServerContext/methods/message/unfollowMessage.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26264 [FIX] Open team after room not found page
  apps/meteor/app/ui-utils/client/lib/openRoom.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26446 Chore: Convert `LivechatCustomField` model to raw model
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/getCustomFields.js
  apps/meteor/app/livechat/server/methods/registerGuest.js
  apps/meteor/app/livechat/server/methods/removeCustomField.js
  apps/meteor/app/livechat/server/methods/saveCustomField.js
  apps/meteor/app/livechat/server/methods/saveInfo.js
  apps/meteor/app/livechat/server/methods/setCustomField.js
  apps/meteor/app/models/server/index.ts
  apps/meteor/app/models/server/models/LivechatCustomField.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadConfigApi.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/server/models/raw/LivechatCustomField.ts
  packages/model-typings/src/models/ILivechatCustomFieldModel.ts
Labels: stat: ready to merge, stat: QA skipped

#26513 Chore: Mocha handling multiple React instances
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.2.2.cjs
  .yarnrc.yml
  apps/meteor/.mocharc.client.js
  apps/meteor/package.json
  apps/meteor/tests/setup/hoistedReact.ts
  apps/meteor/tests/unit/client/views/notFound/NotFoundPage.spec.tsx
  package.json
  packages/gazzodown/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26330 [FIX] Too many REST API requests
  apps/meteor/app/apps/client/gameCenter/tabBar.ts
  apps/meteor/app/ui/client/views/app/room.js
  apps/meteor/ee/client/lib/onToggledFeature.ts
Labels: stat: ready to merge, stat: QA skipped

#26534 Chore: Fix UiKit dependency issue for Livechat
  packages/livechat/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26525 [FIX] Do not count Matrix federated users as a valid EE seat
  apps/meteor/app/models/server/models/Users.js
Labels: type: bug, feat: federation, stat: needs QA

#26528 [FIX] Do not allow admin users edit other federated users
  apps/meteor/app/lib/server/functions/getFullUserData.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/client/views/admin/users/AdminUserInfoActions.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoWithData.tsx
  apps/meteor/client/views/admin/users/EditUserWithData.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#26529 [FIX] Do not allow add external users(string) to regular rooms
  apps/meteor/app/federation-v2/server/application/sender/RoomInternalHooksValidator.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsersWithData.tsx
  apps/meteor/tests/unit/app/federation-v2/server/unit/application/sender/RoomInternalHooksValidator.spec.ts
Labels: feat: federation, bug, stat: needs QA

#26527 Chore: Improve test for livechat
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  apps/meteor/tests/e2e/utils/create-aux-context.ts
  apps/meteor/tests/e2e/utils/index.ts
Labels: stat: ready to merge, stat: QA skipped

#26386 Chore: create roomNameExists endpoint
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/client/sidebar/header/CreateChannel.tsx
  apps/meteor/client/views/teams/CreateTeamModal/useCreateTeamModalState.ts
  apps/meteor/server/methods/roomNameExists.js
  apps/meteor/server/methods/roomNameExists.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA skipped

#26445 Chore: ModalFooterControllers adoption
  apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx
  apps/meteor/client/components/GenericModal.tsx
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ReturnChatQueueModal.tsx
  apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx
  apps/meteor/client/components/modal/ModalBackdrop.tsx
  apps/meteor/client/sidebar/header/CreateChannel.tsx
  apps/meteor/client/sidebar/header/CreateDirectMessage.tsx
  apps/meteor/client/sidebar/header/EditStatusModal.tsx
  apps/meteor/client/views/account/preferences/MyDataModal.tsx
  apps/meteor/client/views/account/security/BackupCodesModal.tsx
  apps/meteor/client/views/admin/apps/AppPermissionsReviewModal.tsx
  apps/meteor/client/views/admin/apps/AppUpdateModal.tsx
  apps/meteor/client/views/admin/apps/WarningModal.js
  apps/meteor/client/views/admin/cloud/CopyStep.tsx
  apps/meteor/client/views/admin/cloud/PasteStep.tsx
  apps/meteor/client/views/admin/info/FederationCard/components/FederationModal/FederationModal.tsx
  apps/meteor/client/views/admin/info/InstancesModal.js
  apps/meteor/client/views/admin/info/OfflineLicenseModal.js
  apps/meteor/client/views/admin/settings/groups/voip/AssignAgentModal.tsx
  apps/meteor/client/views/blocks/ModalBlock.js
  apps/meteor/client/views/login/ResetPassword/ResetPassword.js
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
  apps/meteor/client/views/room/webdav/AddWebdavAccountModal.tsx
  apps/meteor/client/views/room/webdav/SaveToWebdavModal.tsx
  apps/meteor/client/views/teams/CreateTeamModal/CreateTeamModal.tsx
  apps/meteor/client/views/teams/contextualBar/channels/AddExistingModal/AddExistingModal.tsx
  apps/meteor/client/views/teams/contextualBar/channels/ConfirmationModal/ConfirmationModal.tsx
  apps/meteor/ee/app/livechat-enterprise/client/components/modals/PlaceChatOnHoldModal.tsx
  apps/meteor/ee/client/deviceManagement/components/featureModal/DeviceManagementFeatureModal.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/CreateCannedResponseModal.tsx
  apps/meteor/ee/client/views/admin/users/CloseToSeatsCapModal.tsx
  apps/meteor/ee/client/views/admin/users/ReachedSeatsCapModal.tsx
  apps/meteor/ee/client/voip/components/modals/WrapUpCallModal.tsx
  apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
Labels: stat: ready to merge, stat: QA skipped

#25734 [NEW] `Home` page
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/app/theme/client/imports/components/header.css
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/rtl.css
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/ui/client/components/header/header.html
  apps/meteor/app/ui/client/components/header/header.js
  apps/meteor/app/ui/client/index.ts
  apps/meteor/app/ui/client/views/app/burger.html
  apps/meteor/app/ui/client/views/app/burger.js
  apps/meteor/app/ui/client/views/app/home.html
  apps/meteor/app/ui/client/views/app/home.js
  apps/meteor/app/ui/client/views/app/notAuthorized.html
  apps/meteor/client/components/Card/CardFooterWrapper.tsx
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/components/Page/PageScrollableContent.tsx
  apps/meteor/client/sidebar/header/CreateChannel.tsx
  apps/meteor/client/sidebar/header/CreateChannelWithData.tsx
  apps/meteor/client/startup/routes.tsx
  apps/meteor/client/templates.ts
  apps/meteor/client/views/home/CustomHomePage.tsx
  apps/meteor/client/views/home/DefaultHomePage.tsx
  apps/meteor/client/views/home/HomePage.tsx
  apps/meteor/client/views/home/HomePageHeader.tsx
  apps/meteor/client/views/home/HomepageGridItem.tsx
  apps/meteor/client/views/home/cards/AddUsersCard.tsx
  apps/meteor/client/views/home/cards/CreateChannelsCard.tsx
  apps/meteor/client/views/home/cards/DesktopAppsCard.tsx
  apps/meteor/client/views/home/cards/DocumentationCard.tsx
  apps/meteor/client/views/home/cards/JoinRoomsCard.tsx
  apps/meteor/client/views/home/cards/MobileAppsCard.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v280.ts
  apps/meteor/tests/e2e/config/global-setup.ts
  apps/meteor/tests/e2e/homepage.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  turbo.json
Labels: stat: ready to merge, stat: QA tested

#26530 [FIX] Endpoints not working when using "Use Real Name" setting
  apps/meteor/app/api/server/v1/channels.js
  apps/meteor/app/api/server/v1/groups.js
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/server/startup/serverRunning.js
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
  apps/meteor/tests/end-to-end/api/04-direct-message.js
Labels: stat: ready to merge, stat: QA skipped

#26537 Chore: restrict `.only`
  packages/eslint-config/best-practices/index.js
Labels: stat: ready to merge, stat: QA skipped

#26495 [FIX] Allow normal user to open apps contextual bar
  apps/meteor/client/views/room/Room/Room.tsx
  apps/meteor/client/views/room/contextualBar/Apps/Apps.tsx
  apps/meteor/client/views/room/contextualBar/Apps/AppsWithData.tsx
  apps/meteor/client/views/room/hooks/useAppsContextualBar.ts
  apps/meteor/tests/e2e/apps.spec.ts
  apps/meteor/tests/e2e/config/constants.ts
  apps/meteor/tests/e2e/page-objects/across-page.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/utils/apps/apps-data.ts
  apps/meteor/tests/e2e/utils/apps/cleanup-app.ts
  apps/meteor/tests/e2e/utils/apps/index.ts
  apps/meteor/tests/e2e/utils/apps/install-test-app.ts
  apps/meteor/tests/e2e/utils/apps/remove-app.ts
  apps/meteor/tests/e2e/utils/index.ts
  apps/meteor/tests/e2e/utils/test.ts
Labels: stat: ready to merge, stat: QA skipped

#26535 [FIX] LDAP fails to sync teams when the user DN has escaped characters.
  apps/meteor/ee/server/lib/ldap/Manager.ts
Labels: stat: ready to merge, stat: QA tested

#26551 Release 5.0.3
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/api.js
  apps/meteor/app/api/server/v1/channels.js
  apps/meteor/app/api/server/v1/groups.js
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/api/lib/departments.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.js
  apps/meteor/app/ui-utils/client/lib/waitUntilWrapperExists.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/package.json
  apps/meteor/server/startup/serverRunning.js
  apps/meteor/tests/data/livechat/rooms.js
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
  apps/meteor/tests/end-to-end/api/04-direct-message.js
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.js
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.js
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.js
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.js
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.js
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.js
  apps/meteor/tests/end-to-end/api/livechat/07-queue.js
  apps/meteor/tests/end-to-end/api/livechat/08-triggers.js
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  apps/meteor/tests/unit/app/ui-utils/client.tests.ts
  package.json
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: needs QA

#26540 Chore: update fuselage rounded edition
  apps/meteor/app/theme/client/imports/general/variables.css
  apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts
  apps/meteor/client/views/setupWizard/SetupWizardRoute.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26554 Chore: Some suggestions on PR #26544
  apps/meteor/ee/server/models/raw/CannedResponse.ts
  apps/meteor/ee/server/models/raw/LivechatInquiry.ts
  apps/meteor/ee/server/models/raw/LivechatPriority.ts
  apps/meteor/ee/server/models/raw/LivechatTag.ts
  apps/meteor/ee/server/models/raw/LivechatUnitMonitors.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  packages/model-typings/src/models/ICannedResponseModel.ts
Labels: stat: needs QA

#25771 Chore: update codeowners for omnichannel
  .github/CODEOWNERS
Labels: stat: ready to merge, stat: QA skipped

#26560 Chore: Add translations code owner
  .github/CODEOWNERS
Labels: stat: needs QA

#26543 Chore: test for change avatar
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.js
  apps/meteor/tests/e2e/fixtures/files/test-image.jpeg
  apps/meteor/tests/e2e/page-objects/account-profile.ts
  apps/meteor/tests/e2e/settings-account-profile.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#26307 [FIX] - Incoming SMSs no longer clash with ongoing livechat conversations by the same visitor
  apps/meteor/app/livechat/imports/server/rest/sms.js
  apps/meteor/app/models/server/models/LivechatRooms.js
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26564 Chore: Replace timeAgo on WebdavFilePickerTable
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerTable.tsx
Labels: stat: ready to merge, stat: QA skipped

#26149 Chore: Remove method calls - Stage 1
  apps/meteor/app/api/server/v1/assets.ts
  apps/meteor/app/e2e/client/tabbar.ts
  apps/meteor/app/ui-utils/client/lib/AccountBox.ts
  apps/meteor/client/hooks/useMethodData.ts
  apps/meteor/client/hooks/usePolledMethodData.ts
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/sidebar/header/EditStatusModal.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/views/admin/cloud/CloudPage.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
  apps/meteor/client/views/admin/federationDashboard/OverviewSection.tsx
  apps/meteor/client/views/admin/federationDashboard/ServersSection.tsx
  apps/meteor/client/views/admin/info/InformationRoute.tsx
  apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
  apps/meteor/client/views/login/ResetPassword/ResetPassword.tsx
  apps/meteor/client/views/omnichannel/facebook/FacebookPageContainer.tsx
  apps/meteor/client/views/room/modals/ReadReceiptsModal/ReadReceiptsModal.tsx
  apps/meteor/definition/methods/federation.ts
  apps/meteor/ee/client/audit/AuditLogPage.tsx
  apps/meteor/ee/client/audit/DateRangePicker.tsx
  apps/meteor/ee/definition/methods.ts
  apps/meteor/tests/end-to-end/api/14-assets.js
  packages/rest-typings/src/v1/assets.ts
  packages/rest-typings/src/v1/misc.ts
  packages/rest-typings/src/v1/rooms.ts
  packages/rest-typings/src/v1/subscriptionsEndpoints.ts
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: stat: ready to merge, stat: QA skipped, methods removal

#26545 Chore: transfer to another agent
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/components/UserAutoComplete/UserAutoComplete.tsx
  apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA skipped

#26552 Chore: Suggestions on PR #26419
  apps/meteor/app/api/server/api.helpers.ts
  apps/meteor/app/api/server/api.js
  apps/meteor/app/livechat/imports/server/rest/appearance.js
  apps/meteor/app/livechat/imports/server/rest/businessHours.js
  apps/meteor/app/livechat/imports/server/rest/queue.js
  apps/meteor/app/livechat/imports/server/rest/rooms.js
  apps/meteor/app/livechat/imports/server/rest/triggers.js
  apps/meteor/app/livechat/imports/server/rest/users.js
  apps/meteor/app/livechat/imports/server/rest/visitors.js
  apps/meteor/app/livechat/server/api/lib/departments.ts
  apps/meteor/app/livechat/server/api/lib/users.js
  apps/meteor/app/livechat/server/api/v1/customField.js
  apps/meteor/app/livechat/server/api/v1/transfer.js
  apps/meteor/tests/unit/app/api/server/v1/lib/checkPermissionsForInvocation.spec.ts
Labels: stat: needs QA

#26147 [FIX] Chats not getting assigned to offline agents even when "Accept with No Online agents" setting is turned on
  apps/meteor/app/models/server/models/Users.js
Labels: stat: ready to merge, stat: QA tested

#26377 Chore: Migrate omni-chat forwarding to use API instead of meteor method
  apps/meteor/app/livechat/server/api/v1/room.js
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/transfer.js
  apps/meteor/app/models/server/models/Messages.js
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/livechat/utils.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested

#26574 Regression: Team name validation failing always.
  apps/meteor/client/views/teams/CreateTeamModal/useCreateTeamModalState.ts
Labels: stat: ready to merge, stat: QA skipped

#26372 [FIX] Slash commands description as undefined
  apps/meteor/app/utils/lib/slashCommand.ts
Labels: stat: ready to merge, stat: QA tested

#26218 [FIX] Unable to remove a user who joined a public team with a mention
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/server/services/team/service.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26280 Chore: Separating user edit form to prevent browser autocomplete
  apps/meteor/client/views/admin/users/UserForm.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26558 [FIX] SMS service check
  apps/meteor/app/livechat/server/lib/callbackLogger.ts
  apps/meteor/app/livechat/server/sendMessageBySMS.js
  apps/meteor/app/sms/server/SMS.js
Labels: stat: ready to merge, stat: QA tested

#26542 [FIX] Katex is not respecting the 'Katex_Enabled' setting
  apps/meteor/app/settings/server/functions/settings.mocks.ts
  apps/meteor/client/views/room/MessageList/hooks/useParsedMessage.spec.tsx
  apps/meteor/client/views/room/MessageList/hooks/useParsedMessage.ts
  apps/meteor/package.json
  apps/meteor/server/hooks/messages/markdownParser.ts
  apps/meteor/tests/unit/app/apps/server/messages.tests.js
  apps/meteor/tests/unit/app/federation-v2/server/unit/application/RoomServiceReceiver.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/queue/InMemoryQueue.spec.ts
  apps/meteor/tests/unit/app/lib/server.mocks.js
  apps/meteor/tests/unit/app/lib/server.tests.js
  apps/meteor/tests/unit/app/markdown/client.mocks.js
  apps/meteor/tests/unit/app/markdown/client.tests.js
  apps/meteor/tests/unit/app/meteor-accounts-saml/server.tests.ts
  apps/meteor/tests/unit/app/ui-utils/server.mocks.js
  apps/meteor/tests/unit/app/ui-utils/server.tests.js
  apps/meteor/tests/unit/app/utils/lib/getURL.tests.js
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#26598 Chore: Remove translation owners
  .github/CODEOWNERS
Labels: stat: needs QA

#26114 Chore: Fix some settings with incompatible default value types
  apps/meteor/app/cas/server/cas_rocketchat.js
  apps/meteor/app/meteor-accounts-saml/server/lib/settings.ts
  apps/meteor/server/settings/ldap.ts
Labels: stat: ready to merge, stat: QA skipped

#26579 [FIX][ENTERPRISE] User not marked as offline on log out when using micro services
  ee/apps/ddp-streamer/src/configureServer.ts
Labels: stat: ready to merge, stat: QA skipped

#26443 [FIX] Prune messages not removing thumbnails
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26471 [FIX] Default BH not getting applied in-case any other BH is disabled
  apps/meteor/app/livechat/server/business-hour/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/server/models/raw/LivechatBusinessHours.ts
  packages/model-typings/src/models/ILivechatBusinessHoursModel.ts
Labels: stat: ready to merge, stat: QA tested

#26600 Chore: Wait subscription to expose message composer
  apps/meteor/app/ui-utils/client/lib/RoomManager.js
  apps/meteor/app/ui/client/views/app/room.html
  apps/meteor/app/ui/client/views/app/room.js
  apps/meteor/client/templates.ts
  apps/meteor/client/views/room/Room/ComposerSkeleton.tsx
  apps/meteor/client/views/room/Room/RoomSkeleton.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/homepage.spec.ts
Labels: stat: needs QA, stat: QA skipped

#26597 [FIX] Reset password errors
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/client/views/login/ResetPassword/ResetPassword.tsx
  apps/meteor/server/methods/getPasswordPolicy.js
  apps/meteor/server/models/raw/Users.js
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  packages/model-typings/src/models/IUsersModel.ts
  packages/rest-typings/src/v1/misc.ts
Labels: stat: ready to merge, stat: QA skipped

#26461 [FIX] Notification preferences not updated on save
  apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/components/NotificationByDevice.tsx
  apps/meteor/server/modules/watchers/publishFields.ts
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-notificationPreferences.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
Labels: stat: ready to merge, stat: QA skipped

#25841 [FIX] Permission `view-all-teams` is not checked in the `teams.info` endpoint
  apps/meteor/app/api/server/v1/teams.ts
  apps/meteor/tests/end-to-end/api/25-teams.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26441 [NEW] Fallback Error component for Engagement Dashboard widgets
  apps/meteor/client/views/room/MessageList/MessageListErrorBoundary.tsx
  apps/meteor/client/views/room/Room/Room.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardCard.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardCardErrorBoundary.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardCardFilter.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardPage.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/Section.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/ChannelsOverview.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/ChannelsTab.stories.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/ChannelsTab.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/useChannelsList.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/MessagesPerChannelSection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/MessagesSentSection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/MessagesTab.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessageOrigins.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessagesSent.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/useTopFivePopularChannels.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/ActiveUsersSection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/BusiestChatTimesSection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/NewUsersSection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/UsersByTimeOfTheDaySection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/UsersTab.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useActiveUsers.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useHourlyChatActivity.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useNewUsers.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useUsersByTimeOfTheDay.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useWeeklyChatActivity.ts
  apps/meteor/package.json
  packages/gazzodown/package.json
  packages/gazzodown/src/katex/KatexErrorBoundary.tsx
  packages/ui-client/src/components/ErrorBoundary.tsx
  packages/ui-client/src/components/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#26195 Chore: remove useMethod calls
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useIgnoreUserAction.ts
  apps/meteor/client/views/room/threads/ThreadComponent.tsx
Labels: stat: ready to merge, stat: QA skipped, methods removal

#26571 Regression: Update custom homepage content behavior
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/client/components/PlanTag.tsx
  apps/meteor/client/hooks/useIsEnterprise.ts
  apps/meteor/client/views/admin/EditableSettingsContext.ts
  apps/meteor/client/views/admin/settings/EditableSettingsProvider.tsx
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
  apps/meteor/client/views/admin/settings/Setting.tsx
  apps/meteor/client/views/home/CustomHomePage.tsx
  apps/meteor/client/views/home/CustomHomePageContent.tsx
  apps/meteor/client/views/home/DefaultHomePage.tsx
  apps/meteor/client/views/home/HomePage.tsx
  apps/meteor/ee/app/settings/server/settings.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/v280.ts
  apps/meteor/tests/e2e/homepage.spec.ts
Labels: stat: ready to merge, stat: QA tested

#26604 Chore: Review proposal
  apps/meteor/client/views/omnichannel/departments/EditDepartment.js
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
Labels: stat: needs QA

#25981 [FIX] Users can access public discussions inside private channels they are not members of
  apps/meteor/app/lib/server/methods/getMessages.ts
  apps/meteor/server/methods/loadHistory.js
  apps/meteor/server/methods/loadSurroundingMessages.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26481 [FIX] Save edited tags for omnichannel departments
  .vscode/settings.json
  apps/meteor/client/views/omnichannel/departments/EditDepartment.js
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
Labels: stat: ready to merge, stat: QA tested

#25912 [FIX] add image format validation
  apps/meteor/client/components/avatar/RoomAvatarEditor.tsx
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.tsx
  apps/meteor/client/lib/utils/isValidImageFormat.ts
  packages/api-client/src/index.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26608 Chore: Fix services image publish do DockerHub
  .github/workflows/build_and_test.yml
Labels: stat: ready to merge, stat: QA skipped

#26318 [FIX] UI fixes on dropdown titles
  apps/meteor/app/theme/client/imports/components/popover.css
  apps/meteor/client/components/Sidebar/ListItem.tsx
  apps/meteor/client/components/SortList/GroupingList.tsx
  apps/meteor/client/components/SortList/SortList.tsx
  apps/meteor/client/components/SortList/SortModeList.tsx
  apps/meteor/client/components/SortList/ViewModeList.tsx
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/components/MemberItem.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannelItem.js
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26607 Chore: omnichannel-departments tests
  apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#26612 Chore: Prevent tooltip from opening after click
  apps/meteor/client/providers/TooltipProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#26282 [FIX] Add Offline License Endpoint
  apps/meteor/client/views/admin/info/LicenseCard.tsx
  apps/meteor/client/views/admin/info/OfflineLicenseModal.tsx
Labels: stat: ready to merge, stat: QA skipped, feat: team-collab

#25793 [FIX] Slackbridge Connect Error
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/slackbridge/server/slackbridge.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26616 Chore: skipping tests that are based on kebab menu
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-notificationPreferences.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
Labels: stat: ready to merge, stat: QA skipped

#26617 Chore: Fix services Docker build
  .github/workflows/build_and_test.yml
Labels: stat: needs QA

#26452 [IMPROVE] New 'not found page' design
  apps/meteor/client/views/notFound/NotFoundPage.tsx
  apps/meteor/client/views/room/Room/RoomNotFound/RoomNotFound.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/unit/client/views/notFound/NotFoundPage.spec.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26618 Chore: Remove console.log
  apps/meteor/client/sidebar/search/SearchList.tsx
Labels: stat: ready to merge, stat: QA skipped

#26619 Revert: [FIX] Users can access public discussions inside private channels they are not members of
  apps/meteor/app/lib/server/methods/getMessages.ts
  apps/meteor/server/methods/loadHistory.js
  apps/meteor/server/methods/loadSurroundingMessages.js
Labels: stat: ready to merge, stat: QA skipped

#26546 Chore: Missing permissions translations
  apps/meteor/client/views/admin/permissions/PermissionsContextBar.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#26620 Release 5.0.4
  .github/history.json
  .github/workflows/build_and_test.yml
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  ee/apps/ddp-streamer/src/configureServer.ts
  package.json
Labels: stat: needs QA

#26627 Chore: Remove Livechat Dashboard Templates
  apps/meteor/app/livechat/client/views/admin.js
  apps/meteor/app/livechat/client/views/app/livechatDashboard.html
Labels: stat: ready to merge, eng day, stat: QA skipped

#26628 Chore: Remove trash collection from models when not used
  apps/meteor/server/models/Avatars.ts
  apps/meteor/server/models/Banners.ts
  apps/meteor/server/models/BannersDismiss.ts
  apps/meteor/server/models/CredentialTokens.ts
  apps/meteor/server/models/CustomSounds.ts
  apps/meteor/server/models/CustomUserStatus.ts
  apps/meteor/server/models/EmailInbox.ts
  apps/meteor/server/models/EmailMessageHistory.ts
  apps/meteor/server/models/ExportOperations.ts
  apps/meteor/server/models/FederationKeys.ts
  apps/meteor/server/models/FederationServers.ts
  apps/meteor/server/models/ImportData.ts
  apps/meteor/server/models/Integrations.ts
  apps/meteor/server/models/Invites.ts
  apps/meteor/server/models/LivechatAgentActivity.ts
  apps/meteor/server/models/LivechatBusinessHours.ts
  apps/meteor/server/models/LivechatCustomField.ts
  apps/meteor/server/models/LivechatTrigger.ts
  apps/meteor/server/models/LivechatVisitors.ts
  apps/meteor/server/models/LoginServiceConfiguration.ts
  apps/meteor/server/models/NotificationQueue.ts
  apps/meteor/server/models/Nps.ts
  apps/meteor/server/models/NpsVote.ts
  apps/meteor/server/models/OAuthApps.ts
  apps/meteor/server/models/OEmbedCache.ts
  apps/meteor/server/models/PbxEvents.ts
  apps/meteor/server/models/ReadReceipts.ts
  apps/meteor/server/models/Reports.ts
  apps/meteor/server/models/ServerEvents.ts
  apps/meteor/server/models/Sessions.ts
  apps/meteor/server/models/SmarshHistory.ts
  apps/meteor/server/models/Statistics.ts
  apps/meteor/server/models/Team.ts
  apps/meteor/server/models/TeamMember.ts
  apps/meteor/server/models/Uploads.ts
  apps/meteor/server/models/UserDataFiles.ts
  apps/meteor/server/models/Users.ts
  apps/meteor/server/models/UsersSessions.ts
  apps/meteor/server/models/VideoConference.ts
  apps/meteor/server/models/WebdavAccounts.ts
  apps/meteor/server/models/raw/Statistics.ts
Labels: stat: ready to merge, stat: QA skipped

#26393 Chore: create removeWebdavAccount endpoint
  apps/meteor/app/api/server/v1/webdav.ts
  apps/meteor/app/webdav/server/methods/removeWebdavAccount.ts
  apps/meteor/client/views/account/integrations/AccountIntegrationsPage.tsx
  apps/meteor/tests/end-to-end/api/17-webdav.js
  packages/rest-typings/src/v1/webdav.ts
Labels: stat: ready to merge, stat: QA skipped

#26572 Chore: Fail-fast on callbacks
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.js
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
  apps/meteor/app/livechat/server/hooks/leadCapture.js
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.js
  apps/meteor/app/livechat/server/hooks/saveLastVisitorMessageTs.js
  apps/meteor/app/livechat/server/hooks/sendToCRM.js
  apps/meteor/app/livechat/server/hooks/sendToFacebook.js
  apps/meteor/app/livechat/server/methods/takeInquiry.js
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/metrics/server/lib/metrics.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.js
  apps/meteor/server/models/raw/Subscriptions.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA skipped, feat: chat-engine

#26635 Regression: Modal footer alignment
  apps/meteor/client/components/GenericModal.tsx
  apps/meteor/client/views/admin/info/FederationCard/components/FederationModal/FederationModal.tsx
  apps/meteor/ee/client/deviceManagement/components/featureModal/DeviceManagementFeatureModal.tsx
Labels: stat: ready to merge, stat: QA skipped

#26610 Regression: Home cards UI tweaks
  apps/meteor/client/components/Card/Card.tsx
  apps/meteor/client/components/Card/CardBody.tsx
  apps/meteor/client/components/Card/CardCol.tsx
  apps/meteor/client/components/Card/CardColSection.tsx
  apps/meteor/client/components/Card/CardColTitle.tsx
  apps/meteor/client/components/Card/CardFooter.tsx
  apps/meteor/client/components/Card/CardFooterWrapper.tsx
  apps/meteor/client/components/Card/CardTitle.tsx
  apps/meteor/client/components/Card/ColSection.tsx
  apps/meteor/client/components/Card/Footer.tsx
  apps/meteor/client/components/Card/index.ts
  apps/meteor/client/views/admin/settings/SettingsGroupCard.tsx
  apps/meteor/client/views/home/DefaultHomePage.tsx
  apps/meteor/client/views/home/cards/AddUsersCard.tsx
  apps/meteor/client/views/home/cards/CreateChannelsCard.tsx
  apps/meteor/client/views/home/cards/DesktopAppsCard.tsx
  apps/meteor/client/views/home/cards/DocumentationCard.tsx
  apps/meteor/client/views/home/cards/JoinRoomsCard.tsx
  apps/meteor/client/views/home/cards/MobileAppsCard.tsx
Labels: stat: ready to merge, stat: QA skipped

#26559 Chore: Refactor RoomMembers to Typescript
  apps/meteor/client/templates.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsersWithData.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/EditInvite/EditInvite.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/EditInvite/EditInvite.stories.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/EditInvite/EditInviteWithData.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/EditInvite/index.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/EditInviteLink.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteLink.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.stories.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsersWithData.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/WrappedInviteUsers.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/index.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/RoomMembersWithData.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/components/UserActions.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.stories.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersActions.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersItem.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersRow.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/index.ts
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoWithData.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
  packages/core-typings/src/IInvite.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26626 Chore: Convert AppSettingsAssembler to tsx
  apps/meteor/client/views/admin/apps/AppSettingsAssembler.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#26649 Chore: Fix CI intermittent
  apps/meteor/app/ui-utils/client/lib/RoomManager.js
Labels: stat: ready to merge, stat: QA skipped

#26578 Chore: Create teams management tests
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-channels.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
  apps/meteor/tests/e2e/page-objects/home-team.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/team-management.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#26200 [FIX] Current Chat Custom Field Filter
  apps/meteor/client/components/AutoCompleteAgent.js
  apps/meteor/client/components/AutoCompleteDepartment.js
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/client/views/omnichannel/currentChats/CustomFieldsVerticalBar.tsx
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/currentChats/RemoveAllClosed.tsx
  apps/meteor/client/views/omnichannel/currentChats/RemoveChatButton.tsx
  apps/meteor/client/views/omnichannel/currentChats/useAllCustomFields.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/tests/e2e/omnichannel-currentChats.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-current-chats.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26656 Regression: Custom status loading forever in Usercard
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
Labels: stat: ready to merge, stat: QA skipped

#26653 Chore: Move `Card` and related components to `@rocket.chat/ui-client`
  apps/meteor/client/components/UserStatus/Away.tsx
  apps/meteor/client/components/UserStatus/Busy.tsx
  apps/meteor/client/components/UserStatus/Loading.tsx
  apps/meteor/client/components/UserStatus/Offline.tsx
  apps/meteor/client/components/UserStatus/Online.tsx
  apps/meteor/client/components/UserStatus/ReactiveUserStatus.tsx
  apps/meteor/client/components/UserStatus/index.ts
  apps/meteor/client/views/admin/info/DeploymentCard.tsx
  apps/meteor/client/views/admin/info/FederationCard/FederationCard.tsx
  apps/meteor/client/views/admin/info/FederationCard/components/Section.tsx
  apps/meteor/client/views/admin/info/LicenseCard.tsx
  apps/meteor/client/views/admin/info/UsageCard.tsx
  apps/meteor/client/views/admin/settings/SettingsGroupCard.tsx
  apps/meteor/client/views/home/cards/AddUsersCard.tsx
  apps/meteor/client/views/home/cards/CreateChannelsCard.tsx
  apps/meteor/client/views/home/cards/DesktopAppsCard.tsx
  apps/meteor/client/views/home/cards/DocumentationCard.tsx
  apps/meteor/client/views/home/cards/JoinRoomsCard.tsx
  apps/meteor/client/views/home/cards/MobileAppsCard.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardCard.tsx
  apps/meteor/ee/client/views/admin/info/SeatsCard.tsx
  apps/meteor/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/ui-client/.eslintrc.json
  packages/ui-client/.storybook/main.js
  packages/ui-client/.storybook/preview.js
  packages/ui-client/package.json
  packages/ui-client/src/components/Card/Card.stories.tsx
  packages/ui-client/src/components/Card/Card.tsx
  packages/ui-client/src/components/Card/CardBody.tsx
  packages/ui-client/src/components/Card/CardCol.tsx
  packages/ui-client/src/components/Card/CardColSection.tsx
  packages/ui-client/src/components/Card/CardColTitle.tsx
  packages/ui-client/src/components/Card/CardDivider.tsx
  packages/ui-client/src/components/Card/CardFooter.tsx
  packages/ui-client/src/components/Card/CardFooterWrapper.tsx
  packages/ui-client/src/components/Card/CardIcon.tsx
  packages/ui-client/src/components/Card/CardTitle.tsx
  packages/ui-client/src/components/Card/index.ts
  packages/ui-client/src/components/DotLeader.stories.tsx
  packages/ui-client/src/components/DotLeader.tsx
  packages/ui-client/src/components/ExternalLink.tsx
  packages/ui-client/src/components/TextSeparator.stories.tsx
  packages/ui-client/src/components/TextSeparator.tsx
  packages/ui-client/src/components/TooltipComponent.tsx
  packages/ui-client/src/components/UserStatus/Away.tsx
  packages/ui-client/src/components/UserStatus/Busy.tsx
  packages/ui-client/src/components/UserStatus/Loading.tsx
  packages/ui-client/src/components/UserStatus/Offline.tsx
  packages/ui-client/src/components/UserStatus/Online.tsx
  packages/ui-client/src/components/UserStatus/UserStatus.stories.tsx
  packages/ui-client/src/components/UserStatus/UserStatus.tsx
  packages/ui-client/src/components/UserStatus/index.ts
  packages/ui-client/src/components/index.ts
  packages/ui-client/src/stories/hooks/useAutoSequence.ts
  packages/ui-client/tsconfig-build.json
  packages/ui-client/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26650 Chore: Add license env var to ee tests
  .github/workflows/build_and_test.yml
  apps/meteor/tests/e2e/homepage.spec.ts
  docker-compose-ci.yml
Labels: stat: ready to merge, stat: QA skipped

#26575 [FIX] Agents (with user status offline & omni-status as available) not able to take or forward chat
  apps/meteor/app/livechat/server/config.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/methods/takeInquiry.js
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/tests/e2e/omnichannel-takeChat.spec.ts
  apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/utils/apps/remove-app.ts
  apps/meteor/tests/e2e/utils/test.ts
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#21902 Chore: Fix grammatical typo when only one message is pruned
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#26394 [FIX] Not allowed error in discussion room with a private parent channel
  apps/meteor/client/hooks/useRoomInfoEndpoint.ts
  apps/meteor/client/views/room/Header/ParentRoomWithEndpointData.tsx
Labels: stat: ready to merge, stat: QA tested

#26658 Regression: CI
  .github/workflows/build_and_test.yml
  apps/meteor/app/models/client/models/ChatMessage.ts
  apps/meteor/app/threads/client/flextab/thread.ts
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/client/startup/banners.ts
  apps/meteor/ee/app/license/server/settings.js
  apps/meteor/tests/end-to-end/api/20-licenses.js
  apps/meteor/tests/end-to-end/api/26-LDAP.ts
Labels: stat: ready to merge, stat: QA skipped

#26419 Chore: Permissions check per endpoint/method
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/api.helpers.ts
  apps/meteor/app/api/server/api.js
  apps/meteor/app/livechat/imports/server/rest/agent.js
  apps/meteor/app/livechat/imports/server/rest/appearance.js
  apps/meteor/app/livechat/imports/server/rest/businessHours.js
  apps/meteor/app/livechat/imports/server/rest/dashboards.js
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/imports/server/rest/inquiries.js
  apps/meteor/app/livechat/imports/server/rest/integrations.js
  apps/meteor/app/livechat/imports/server/rest/queue.js
  apps/meteor/app/livechat/imports/server/rest/rooms.js
  apps/meteor/app/livechat/imports/server/rest/triggers.js
  apps/meteor/app/livechat/imports/server/rest/users.js
  apps/meteor/app/livechat/imports/server/rest/visitors.js
  apps/meteor/app/livechat/server/api/lib/agents.js
  apps/meteor/app/livechat/server/api/lib/appearance.js
  apps/meteor/app/livechat/server/api/lib/businessHours.ts
  apps/meteor/app/livechat/server/api/lib/customFields.js
  apps/meteor/app/livechat/server/api/lib/departments.ts
  apps/meteor/app/livechat/server/api/lib/integrations.js
  apps/meteor/app/livechat/server/api/lib/queue.js
  apps/meteor/app/livechat/server/api/lib/transfer.js
  apps/meteor/app/livechat/server/api/lib/triggers.js
  apps/meteor/app/livechat/server/api/lib/users.js
  apps/meteor/app/livechat/server/api/lib/visitors.js
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/api/v1/customField.js
  apps/meteor/app/livechat/server/api/v1/message.js
  apps/meteor/app/livechat/server/api/v1/room.js
  apps/meteor/app/livechat/server/api/v1/transfer.js
  apps/meteor/app/livechat/server/api/v1/videoCall.js
  apps/meteor/app/livechat/server/lib/RoutingManager.js
  apps/meteor/app/livechat/server/methods/takeInquiry.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterOnHoldChatResumed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTakeInquiry.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onAgentAssignmentFailed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadConfigApi.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts
  apps/meteor/server/models/raw/Users.js
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
  apps/meteor/tests/end-to-end/api/livechat/07-queue.ts
  apps/meteor/tests/end-to-end/api/livechat/08-triggers.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/unit/app/api/server/v1/lib/checkPermissions.spec.ts
  apps/meteor/tests/unit/app/api/server/v1/lib/checkPermissionsForInvocation.spec.ts
Labels: stat: ready to merge, stat: QA skipped, feat: chat-engine

#26665 [FIX] MDM content alignment
  apps/meteor/ee/client/deviceManagement/components/featureModal/FeatureModalBullets.tsx
Labels: stat: ready to merge, stat: QA skipped

#26118 [NEW] allow ephemeral messages to receive a specific id
  apps/meteor/server/modules/listeners/listeners.module.ts
Labels: feat: apps, stat: ready to merge, stat: QA skipped

#26220 [NEW] Adding oauth crud on the rocket.chat side
  apps/meteor/app/apps/server/bridges/bridges.js
  apps/meteor/app/apps/server/bridges/index.js
  apps/meteor/app/apps/server/bridges/oauthApps.ts
  apps/meteor/package.json
  apps/meteor/tests/data/apps/apps-data.js
  packages/core-typings/src/IOAuthApps.ts
  yarn.lock
Labels: feat: apps, stat: ready to merge, stat: QA skipped

#26629 [FIX] Slack User CSV importer not working
  apps/meteor/app/importer-slack-users/server/importer.js
Labels: stat: ready to merge, stat: QA skipped, feat: chat-engine

#26599 [IMPROVE] Spotlight search user results
  apps/meteor/server/lib/spotlight.js
  apps/meteor/server/models/raw/Subscriptions.ts
  packages/core-typings/src/SpotlightUser.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26663 Regression: Add alsoSendThreadToChannel to user settings api
  packages/rest-typings/src/v1/users/UsersSetPreferenceParamsPOST.ts
Labels: stat: ready to merge, stat: QA skipped

#26670 Chore: Suggestions on PR #26334
  .github/workflows/build_and_test.yml
  apps/meteor/tests/e2e/omnichannel-voip-footer.spec.ts
  docker-compose-ci.yml
Labels: stat: needs QA

#26668 Regression: Prevent message from being temp forever
  apps/meteor/app/models/client/models/ChatMessage.ts
  apps/meteor/app/threads/client/flextab/thread.ts
  apps/meteor/app/ui/client/lib/ChatMessages.ts
Labels: stat: ready to merge, stat: QA skipped

#26667 [NEW] Warn admins about running multiple instances of the monolith
  apps/meteor/client/views/admin/info/InformationPage.tsx
  apps/meteor/definition/externals/meteor/konecty-multiple-instances-status.d.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/InstanceStatus.ts
  apps/meteor/server/startup/instance.ts
  apps/meteor/server/stream/streamBroadcast.js
  packages/model-typings/src/models/IInstanceStatusModel.ts
Labels: stat: ready to merge, stat: QA skipped, feat: team-collab

#26631 Chore: Remove & Test old closeChat templates
  apps/meteor/app/livechat/client/index.js
  apps/meteor/app/livechat/client/views/app/dialog/closeRoom.html
  apps/meteor/app/livechat/client/views/app/dialog/closeRoom.js
  apps/meteor/app/livechat/client/views/app/livechatRoomTagSelector.html
  apps/meteor/app/livechat/client/views/app/livechatRoomTagSelector.js
  apps/meteor/app/livechat/client/views/regular.js
  apps/meteor/tests/e2e/omnichannel-close-chat.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26625 Chore: Convert AppSetting to tsx
  apps/meteor/client/views/admin/apps/AppSetting.js
  apps/meteor/client/views/admin/apps/AppSetting.tsx
  apps/meteor/client/views/admin/apps/AppSettingsAssembler.tsx
  apps/meteor/client/views/admin/apps/SettingsDisplay.tsx
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
Labels: eng day, stat: needs QA

#26655 Chore: Remove italic/bold font-style from system messages
  apps/meteor/packages/rocketchat-i18n/i18n/af.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/az.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/be-BY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bg.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cy.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-AT.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/el.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/eo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/eu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/he.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/id.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ku.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/mn.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ro.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sq.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/th-TH.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ug.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-HK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: needs QA

#26549 [FIX] Autotranslate method should respect setting
  apps/meteor/app/autotranslate/client/lib/autotranslate.ts
  apps/meteor/app/autotranslate/server/methods/getSupportedLanguages.ts
Labels: stat: needs QA

#25957 [FIX] Active users count on `@all` and `@here`
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
  apps/meteor/app/models/server/models/Users.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26683 Regression: "Cache size is not a function" error when booting
  apps/meteor/server/stream/streamBroadcast.js
Labels: stat: ready to merge, stat: QA skipped

#26684 Regression: invalid statistics format
  apps/meteor/app/statistics/server/lib/statistics.ts
Labels: stat: ready to merge, stat: QA skipped

#26334 [IMPROVE] Added identification on calls to/from existing contacts
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.stories.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/client/sidebar/footer/voip/hooks/useOmnichannelContactLabel.ts
  apps/meteor/client/sidebar/footer/voip/index.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallDialPad.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleLoading.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleReady.tsx
  apps/meteor/client/views/omnichannel/directory/CallDialpadButton.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTable.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTableRow.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/ee/client/hooks/useVoipClient.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/playwright.config.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/services/voip/connector/asterisk/ami/ContinuousMonitor.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26689 [FIX] Avatars of other chats disappear when they located near chat with broken avatar
  apps/meteor/client/sidebar/RoomList/RoomList.tsx
Labels: stat: ready to merge, stat: QA skipped

#26609 Chore: Create tests for Omnichannel admin add a custom fields
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsPage.js
  apps/meteor/client/views/omnichannel/customFields/EditCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/customFields/NewCustomFieldsPage.js
  apps/meteor/tests/e2e/omnichannel-custom-fields.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-custom-fields.ts
Labels: stat: ready to merge, stat: QA skipped

#26312 [NEW] Capability to search visitors by custom fields
  apps/meteor/app/livechat/imports/server/rest/visitors.js
  apps/meteor/app/livechat/server/api/lib/rooms.js
  apps/meteor/app/livechat/server/api/lib/visitors.js
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/methods/saveCustomField.js
  apps/meteor/app/models/server/models/LivechatRooms.js
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsForm.js
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsRoute.js
  apps/meteor/client/views/omnichannel/customFields/EditCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/customFields/NewCustomFieldsPage.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/models/raw/LivechatCustomField.ts
  apps/meteor/server/models/raw/LivechatVisitors.ts
  apps/meteor/tests/data/livechat/custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  packages/core-typings/src/ILivechatCustomField.ts
  packages/model-typings/src/models/ILivechatCustomFieldModel.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26693 Regression: Banner - Room not found - Omnichannel room
  apps/meteor/app/ui-utils/client/lib/RoomManager.ts
  apps/meteor/app/ui-utils/client/lib/openRoom.tsx
  apps/meteor/client/startup/banners.ts
Labels: stat: needs QA

#26691 Chore: More Omnichannel tests
  apps/meteor/app/lib/server/functions/loadMessageHistory.ts
  apps/meteor/app/livechat/server/api/v1/config.js
  apps/meteor/app/livechat/server/api/v1/message.js
  apps/meteor/app/livechat/server/api/v1/pageVisited.js
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
Labels: stat: ready to merge, stat: QA skipped

#26694 Chore: Upgrade dependencies
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26699 Regression: Remove log from banners.ts
  apps/meteor/client/startup/banners.ts
Labels: stat: ready to merge, stat: QA skipped

#26702 Chore: Engagement Dashboard end to end tests
  apps/meteor/tests/e2e/engagement-dashboard.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/admin-sidenav.ts
  yarn.lock
Labels: stat: ready to merge, eng day, stat: QA skipped

#26700 Chore: Remove visitor, agent and customTemplate meteor templates
  apps/meteor/app/livechat/client/views/app/customTemplates/register.js
  apps/meteor/app/livechat/client/views/app/tabbar/agentEdit.html
  apps/meteor/app/livechat/client/views/app/tabbar/agentEdit.js
  apps/meteor/app/livechat/client/views/app/tabbar/agentInfo.html
  apps/meteor/app/livechat/client/views/app/tabbar/agentInfo.js
  apps/meteor/app/livechat/client/views/app/tabbar/visitorEdit.html
  apps/meteor/app/livechat/client/views/app/tabbar/visitorEdit.js
  apps/meteor/app/livechat/client/views/app/tabbar/visitorEditCustomField.html
  apps/meteor/app/livechat/client/views/app/tabbar/visitorEditCustomField.js
  apps/meteor/app/livechat/client/views/app/tabbar/visitorForward.html
  apps/meteor/app/livechat/client/views/app/tabbar/visitorForward.js
  apps/meteor/app/livechat/client/views/app/tabbar/visitorInfo.html
  apps/meteor/app/livechat/client/views/app/tabbar/visitorInfo.js
  apps/meteor/app/livechat/client/views/app/tabbar/visitorNavigation.html
  apps/meteor/app/livechat/client/views/app/tabbar/visitorNavigation.js
  apps/meteor/app/livechat/client/views/app/tabbar/visitorTranscript.html
  apps/meteor/app/livechat/client/views/app/tabbar/visitorTranscript.js
  apps/meteor/app/livechat/client/views/regular.js
  apps/meteor/ee/app/livechat-enterprise/client/index.js
  apps/meteor/ee/app/livechat-enterprise/client/views/app/customTemplates/visitorEditCustomFieldsForm.html
  apps/meteor/ee/app/livechat-enterprise/client/views/app/customTemplates/visitorEditCustomFieldsForm.js
  apps/meteor/ee/app/livechat-enterprise/client/views/app/customTemplates/visitorInfoCustomForm.html
  apps/meteor/ee/app/livechat-enterprise/client/views/app/customTemplates/visitorInfoCustomForm.js
  apps/meteor/ee/app/livechat-enterprise/client/views/app/registerCustomTemplates.js
  apps/meteor/tests/e2e/omnichannel-contact-info.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26581 Chore: create a test for managers screen
  apps/meteor/client/views/omnichannel/managers/ManagersRoute.tsx
  apps/meteor/tests/e2e/homepage.spec.ts
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/omnichannel-manager.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-manager.ts
Labels: stat: needs QA

#26706 Chore: Remove & Test cannedResponse meteor templates
  apps/meteor/ee/app/canned-responses/client/index.js
  apps/meteor/ee/app/canned-responses/client/views/tabbar/cannedResponses.html
  apps/meteor/ee/app/canned-responses/client/views/tabbar/cannedResponses.js
  apps/meteor/ee/app/canned-responses/client/views/tabbar/departmentCannedResponses.html
  apps/meteor/ee/app/canned-responses/client/views/tabbar/departmentCannedResponses.js
  apps/meteor/tests/e2e/omnichannel-canned-responses-sidebar.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26704 Chore: Convert AutoCompleteAgent to tsx
  apps/meteor/client/components/AutoCompleteAgent.tsx
  apps/meteor/client/components/Omnichannel/hooks/useAgentsList.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26692 [FIX] Omnichannel inquiries being updated even if not needed
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
Labels: stat: needs QA

#26703 [FIX][ENTERPRISE] Omnichannel real time data on micro services
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/ee/server/lib/registerServiceModels.ts
  apps/meteor/ee/server/services/authorization/service.ts
  apps/meteor/ee/server/services/mongo.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/ee/server/services/stream-hub/service.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/sdk/lib/Events.ts
  ee/apps/ddp-streamer/src/streams.ts
Labels: stat: needs QA

#26713 [FIX] Business Units endpoints not filtering by Unit type
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.js
  apps/meteor/ee/app/license/server/getStatistics.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/units.ts
  apps/meteor/ee/app/models/server/raw/LivechatRooms.js
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  packages/model-typings/src/models/ILivechatUnitModel.ts
Labels: stat: ready to merge, stat: QA tested

#26718 Release 5.0.5
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.js
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/ee/app/license/server/getStatistics.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/ee/app/models/server/raw/LivechatRooms.js
  apps/meteor/ee/server/lib/registerServiceModels.ts
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  apps/meteor/ee/server/services/authorization/service.ts
  apps/meteor/ee/server/services/mongo.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/ee/server/services/stream-hub/service.ts
  apps/meteor/package.json
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/sdk/lib/Events.ts
  ee/apps/ddp-streamer/src/streams.ts
  package.json
  packages/model-typings/src/models/ILivechatUnitModel.ts
Labels: stat: needs QA
