Repository RocketChat/Rocket.Chat, pull requests merged in 2022-06, with the labels that each got.

#25429 Chore: Convert components/sidebar to TS
  apps/meteor/client/components/Sidebar/Content.tsx
  apps/meteor/client/components/Sidebar/Header.tsx
  apps/meteor/client/components/Sidebar/ItemsAssembler.js
  apps/meteor/client/components/Sidebar/NavigationItem.js
  apps/meteor/client/components/Sidebar/Sidebar.tsx
  apps/meteor/client/components/Sidebar/SidebarGenericItem.tsx
  apps/meteor/client/components/Sidebar/SidebarItemsAssembler.tsx
  apps/meteor/client/components/Sidebar/SidebarNavigationItem.tsx
  apps/meteor/client/components/Sidebar/index.ts
  apps/meteor/client/lib/createSidebarItems.ts
  apps/meteor/client/views/account/sidebarItems.ts
  apps/meteor/client/views/admin/sidebar/AdminSidebarPages.tsx
  apps/meteor/client/views/omnichannel/sidebar/OmnichannelSidebar.tsx
  apps/meteor/client/views/omnichannel/sidebarItems.ts
Labels: eng day

#25511 Chore: Convert to TS omnichannel/agent
  apps/meteor/client/components/GenericModal.tsx
  apps/meteor/client/components/RoomAutoComplete/RoomAutoComplete.tsx
  apps/meteor/client/components/UserAutoComplete/UserAutoComplete.tsx
  apps/meteor/client/components/avatar/UserAvatar.tsx
  apps/meteor/client/views/admin/permissions/UsersInRole/UsersInRolePage.tsx
  apps/meteor/client/views/omnichannel/agents/AddAgent.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEditWithData.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoAction.js
  apps/meteor/client/views/omnichannel/agents/AgentInfoAction.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoActions.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsPage.js
  apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsRoute.tsx
  apps/meteor/client/views/omnichannel/agents/RemoveAgentButton.tsx
  apps/meteor/client/views/omnichannel/managers/RemoveManagerButton.tsx
  apps/meteor/definition/methods/omnichannel.ts
  apps/meteor/lib/getUserEmailAddress.ts
  packages/rest-typings/src/v1/omnichannel.ts
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: eng day

#25581 Chore: Convert sidebar/header/actions
  apps/meteor/client/sidebar/header/actions/CreateRoom.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
  apps/meteor/client/sidebar/header/actions/Directory.tsx
  apps/meteor/client/sidebar/header/actions/Home.tsx
  apps/meteor/client/sidebar/header/actions/Login.tsx
  apps/meteor/client/sidebar/header/actions/Search.tsx
  apps/meteor/client/sidebar/header/actions/Sort.tsx
Labels: eng day

#25587 Chore: Convert UserAutoCompleteMultiple
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx
  apps/meteor/client/sidebar/header/CreateDirectMessage.tsx
Labels: eng day

#25564 Chore: Remove all cypress tests, configs and references
  .github/workflows/build_and_test.yml
  .yarnrc.yml
  apps/meteor/.gitignore
  apps/meteor/cypress.json
  apps/meteor/package.json
  apps/meteor/tests/.eslintrc
  apps/meteor/tests/cypress/fixtures/example.json
  apps/meteor/tests/cypress/integration/00-login.spec.js
  apps/meteor/tests/cypress/integration/01-register.spec.js
  apps/meteor/tests/cypress/integration/02-forgot-password.spec.js
  apps/meteor/tests/cypress/integration/03-user-creation.spec.js
  apps/meteor/tests/cypress/integration/04-main-elements-render.spec.js
  apps/meteor/tests/cypress/integration/05-channel-creation.spec.js
  apps/meteor/tests/cypress/integration/06-messaging.spec.js
  apps/meteor/tests/cypress/integration/07-emoji.spec.js
  apps/meteor/tests/cypress/integration/08-resolutions.spec.js
  apps/meteor/tests/cypress/integration/09-channel.spec.js
  apps/meteor/tests/cypress/integration/10-user-preferences.spec.js
  apps/meteor/tests/cypress/integration/11-admin.spec.js
  apps/meteor/tests/cypress/integration/12-settings.spec.js
  apps/meteor/tests/cypress/integration/13-permissions.spec.js
  apps/meteor/tests/cypress/integration/14-setting-permissions.spec.js
  apps/meteor/tests/cypress/integration/15-message-popup.spec.js
  apps/meteor/tests/cypress/integration/16-discussion.spec.js
  apps/meteor/tests/cypress/pageobjects/Page.js
  apps/meteor/tests/cypress/pageobjects/administration.page.js
  apps/meteor/tests/cypress/pageobjects/discussion.page.js
  apps/meteor/tests/cypress/pageobjects/flex-tab.page.js
  apps/meteor/tests/cypress/pageobjects/global.js
  apps/meteor/tests/cypress/pageobjects/keyboard.js
  apps/meteor/tests/cypress/pageobjects/login.page.js
  apps/meteor/tests/cypress/pageobjects/main-content.page.js
  apps/meteor/tests/cypress/pageobjects/preferences-main-content.page.js
  apps/meteor/tests/cypress/pageobjects/settings.js
  apps/meteor/tests/cypress/pageobjects/setup-wizard.page.js
  apps/meteor/tests/cypress/pageobjects/side-nav.page.js
  apps/meteor/tests/cypress/plugins/index.js
  apps/meteor/tests/cypress/support/commands.js
  apps/meteor/tests/cypress/support/index.js
  apps/meteor/tests/data/api-data.js
  apps/meteor/tests/data/checks.js
  apps/meteor/tests/e2e/utils/pageobjects/Global.ts
  apps/meteor/tests/mocks/client/jsdom.ts
  yarn.lock
Labels: subj: Testing

#25696 Chore: Test for department screen
  .yarnrc.yml
  apps/meteor/client/views/omnichannel/departments/DepartmentsAgentsTable.js
  apps/meteor/client/views/omnichannel/departments/EditDepartment.js
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/utils/pageobjects/Administration.ts
  apps/meteor/tests/e2e/utils/pageobjects/BasePage.ts
  apps/meteor/tests/e2e/utils/pageobjects/Departments.ts
  apps/meteor/tests/e2e/utils/pageobjects/MainContent.ts
  apps/meteor/tests/e2e/utils/pageobjects/SideNav.ts
Labels: subj: Testing

#25630 Chore: command's endpoints
  .vscode/settings.json
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/v1/commands.ts
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/slashcommand-asciiarts/lib/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/lib/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/lib/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/lib/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/lib/unflip.ts
  apps/meteor/app/slashcommands-archiveroom/server/server.ts
  apps/meteor/app/slashcommands-bridge/server/index.ts
  apps/meteor/app/slashcommands-create/server/server.ts
  apps/meteor/app/slashcommands-help/server/server.ts
  apps/meteor/app/slashcommands-hide/server/hide.ts
  apps/meteor/app/slashcommands-invite/server/server.ts
  apps/meteor/app/slashcommands-inviteall/server/server.ts
  apps/meteor/app/slashcommands-join/server/server.ts
  apps/meteor/app/slashcommands-kick/server/server.ts
  apps/meteor/app/slashcommands-leave/server/leave.ts
  apps/meteor/app/slashcommands-me/server/me.ts
  apps/meteor/app/slashcommands-msg/server/server.ts
  apps/meteor/app/slashcommands-mute/server/mute.ts
  apps/meteor/app/slashcommands-mute/server/unmute.ts
  apps/meteor/app/slashcommands-open/client/client.ts
  apps/meteor/app/slashcommands-status/client/status.ts
  apps/meteor/app/slashcommands-status/server/status.ts
  apps/meteor/app/slashcommands-topic/client/topic.ts
  apps/meteor/app/slashcommands-topic/server/topic.ts
  apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/package.json
  packages/core-typings/src/SlashCommands/index.ts
  packages/core-typings/src/index.ts
  packages/core-typings/src/utils.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/commands.ts
  yarn.lock
Labels: eng day

#25757 Chore: Prune Messages contextualBar rewrite
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessages.stories.tsx
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessages.tsx
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesDateTimeRow.tsx
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.tsx
  packages/rest-typings/src/v1/rooms.ts
Labels: eng day

#25753 Chore: Keyboard shortcuts contextualBar rewrite
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/KeyboardShortcutSection.tsx
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/KeyboardShortcuts.js
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/KeyboardShortcuts.stories.tsx
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/KeyboardShortcuts.tsx
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/KeyboardShortcutsWithClose.js
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/KeyboardShortcutsWithData.tsx
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/ShortcutSection.js
  apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/index.ts
Labels: eng day

#25752 Chore: Replace AnnouncementModal in favor of GenericModal
  apps/meteor/client/templates.ts
  apps/meteor/client/views/room/Announcement/Announcement.tsx
  apps/meteor/client/views/room/Announcement/AnnouncementModal.tsx
Labels: eng day

#25751 Chore: AutoTranslate contextualBar rewrite
  apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslate.tsx
  apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslateWithData.tsx
  packages/core-typings/src/ISubscription.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/autoTranslate.ts
Labels: eng day

#25501 Chore: migrate katex to ts
  apps/meteor/app/katex/client/index.ts
  apps/meteor/app/katex/server/index.ts
  apps/meteor/client/components/Katex.tsx
  apps/meteor/client/startup/renderMessage/katex.ts
  apps/meteor/package.json
  yarn.lock
Labels: eng day

#25583 [NEW] Fuselage ToastBar
  .yarnrc.yml
  apps/meteor/client/lib/utils/handleError.ts
  apps/meteor/client/providers/ToastMessagesProvider.tsx
  apps/meteor/package.json
  apps/meteor/tests/e2e/01-forgot-password.spec.ts
  apps/meteor/tests/e2e/03-login.spec.ts
  apps/meteor/tests/e2e/09-channel.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/utils/pageobjects/BasePage.ts
  apps/meteor/tests/e2e/utils/pageobjects/Global.ts
  apps/meteor/tests/e2e/utils/pageobjects/LoginPage.ts
  apps/meteor/tests/e2e/utils/pageobjects/MainContent.ts
  yarn.lock
Labels: eng day

#25748 [FIX] getUserMentionsByChannel method room permission
  apps/meteor/app/mentions/server/methods/getUserMentionsByChannel.js
Labels: eng day

#25350 Chore: convert invites, misc and subscriptions to TS and create definitions
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/v1/invites.ts
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/api/server/v1/subscriptions.js
  apps/meteor/app/api/server/v1/subscriptions.ts
  apps/meteor/app/invites/server/functions/validateInviteToken.js
  apps/meteor/client/views/invite/InvitePage.tsx
  apps/meteor/definition/externals/meteor/ddp-rate-limiter.d.ts
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  apps/meteor/tests/end-to-end/api/04-direct-message.js
  apps/meteor/tests/end-to-end/api/23-invites.js
  apps/meteor/tests/end-to-end/api/24-methods.js
  apps/meteor/tests/end-to-end/api/25-teams.js
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/invites.ts
  packages/rest-typings/src/v1/misc.ts
  packages/rest-typings/src/v1/subscriptionsEndpoints.ts
Labels: eng day, endpoints rewrite

#25794 Chore: Testing Kodiak feature
  .kodiak.toml
Labels: stat: ready to merge

#25788 [FIX] Discussion alphabetical ordering
  apps/meteor/app/ui-sidenav/client/roomList.js
  apps/meteor/client/sidebar/hooks/useQueryOptions.js
Labels: automerge

#25781 [FIX] Fix prom-client new promise usage
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/definition/externals/meteor/facts-base.d.ts
  apps/meteor/definition/externals/meteor/mongo.d.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge

#25723 [FIX] Wrong argument name preventing Omnichannel Chat Forward to User
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  packages/rest-typings/src/v1/users.ts
Labels: automerge

#25774 [BREAK] Remove RDStation integration
  apps/meteor/app/livechat/server/config.ts
  apps/meteor/app/livechat/server/hooks/RDStation.js
  apps/meteor/app/livechat/server/index.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v268.ts
Labels: stat: ready to merge

#25809 Regression: fix apps path
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/apps/client/@types/IOrchestrator.ts
  apps/meteor/app/apps/client/orchestrator.ts
  apps/meteor/client/lib/meteorCallWrapper.ts
  apps/meteor/client/lib/userData.ts
  apps/meteor/client/providers/ServerProvider.tsx
  apps/meteor/client/views/admin/apps/AppDetailsPage.tsx
  apps/meteor/client/views/admin/apps/hooks/useCategories.ts
  packages/core-typings/src/IUser.ts
  packages/rest-typings/src/apps/index.ts
  packages/rest-typings/src/v1/me.ts
  packages/rest-typings/src/v1/misc.ts
Labels: stat: ready to merge

#25810 Chore: use params instead of URL building on livechat endpoints
  apps/meteor/app/livechat/client/lib/stream/queueManager.js
  apps/meteor/app/livechat/client/views/app/dialog/closeRoom.js
  apps/meteor/app/livechat/client/views/app/livechatReadOnly.js
  apps/meteor/app/livechat/client/views/app/tabbar/contactChatHistory.js
  apps/meteor/app/oauth2-server-config/client/oauth/oauth2-client.js
Labels: stat: ready to merge

#25451 [FIX] allow only livechat-agents to be contact manager for any omnichannel contact
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/app/livechat/server/api/v1/contact.js
  apps/meteor/app/livechat/server/lib/Contacts.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/models/server/models/LivechatVisitors.js
  apps/meteor/app/models/server/raw/LivechatVisitors.ts
  apps/meteor/ee/client/omnichannel/additionalForms/ContactManager.js
  packages/core-typings/src/ILivechatVisitor.ts
Labels: stat: ready to merge

#25819 Chore: Remove snap files from Houston config
  package.json
Labels: stat: ready to merge

#25160 Chore: Move voip's Wrap-up and On-hold functionality to EE (Backend)
  apps/meteor/app/api/server/v1/voip/rooms.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/ee/app/voip-enterprise/server/index.ts
  apps/meteor/ee/app/voip-enterprise/server/lib/calculateOnHoldTimeForRoom.ts
  apps/meteor/ee/app/voip-enterprise/server/services/voipService.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/server/sdk/types/IOmnichannelVoipService.ts
  apps/meteor/server/services/omnichannel-voip/internalTypes.ts
  apps/meteor/server/services/omnichannel-voip/service.ts
  packages/rest-typings/src/v1/voip.ts
Labels: stat: ready to merge

#25820 [FIX] AgentsPage pagination
  apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx
Labels: stat: ready to merge

#25733 [FIX] `You and @yourUsername reacted with`title on reactions
  apps/meteor/client/views/room/MessageList/components/MessageReaction.tsx
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
Labels: stat: ready to merge

#23426 Chore: Remove compose from main repo
  apps/meteor/docker-compose.yml
Labels: stat: ready to merge

#25834 Regression: Fix users.create call
  apps/meteor/client/views/admin/users/AddUser.js
Labels: stat: ready to merge, stat: QA skipped

#25572 Chore: Convert MemoizedSetting, Setting, Section
  apps/meteor/client/components/Sidebar/Header.tsx
  apps/meteor/client/stories/contexts/TranslationContextMock.tsx
  apps/meteor/client/views/admin/EditableSettingsContext.ts
  apps/meteor/client/views/admin/settings/EditableSettingsProvider.tsx
  apps/meteor/client/views/admin/settings/GroupPage.tsx
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
  apps/meteor/client/views/admin/settings/Section.tsx
  apps/meteor/client/views/admin/settings/Setting.tsx
  apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
  packages/ui-contexts/src/TranslationContext.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#25637 Chore: Add tests for agents screens
  apps/meteor/client/components/VerticalBar/VerticalBarClose.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoAction.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/utils/mocks/userAndPasswordMock.ts
  apps/meteor/tests/e2e/utils/pageobjects/Agents.ts
  apps/meteor/tests/e2e/utils/pageobjects/BasePage.ts
  apps/meteor/tests/e2e/utils/pageobjects/Global.ts
  apps/meteor/tests/e2e/utils/pageobjects/SideNav.ts
Labels: subj: Testing, stat: ready to merge, automerge, stat: QA skipped

#25768 [FIX] Client-generated sort parameters in channel directory
  apps/meteor/client/views/directory/hooks.js
Labels: stat: ready to merge, stat: QA skipped

#25713 [FIX] Attachments and OEmbed margins
  apps/meteor/client/components/message/Attachments/Attachment/Action.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentAction.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentAuthor.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentAuthorAvatar.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentAuthorName.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentBlock.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentCollapse.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentContent.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentDescription.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentDetails.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentDownload.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentInner.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentRow.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentSize.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentText.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentThumb.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentTitle.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentTitleLink.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AuthorAvatar.tsx
  apps/meteor/client/components/message/Attachments/Attachment/AuthorName.tsx
  apps/meteor/client/components/message/Attachments/Attachment/Content.tsx
  apps/meteor/client/components/message/Attachments/Attachment/Inner.tsx
  apps/meteor/client/components/message/Attachments/Attachment/Text.tsx
  apps/meteor/client/components/message/Attachments/Attachment/Title.tsx
  apps/meteor/client/components/message/Attachments/Attachment/index.tsx
  apps/meteor/client/components/message/Attachments/DefaultAttachment.tsx
  apps/meteor/client/components/message/Attachments/Files/AudioAttachment.tsx
  apps/meteor/client/components/message/Attachments/Files/GenericFileAttachment.tsx
  apps/meteor/client/components/message/Attachments/Files/ImageAttachment.tsx
  apps/meteor/client/components/message/Attachments/Files/PDFAttachment.tsx
  apps/meteor/client/components/message/Attachments/Files/VideoAttachment.tsx
  apps/meteor/client/components/message/Attachments/QuoteAttachment.tsx
  apps/meteor/client/components/message/Attachments/hooks/useCollapse.tsx
  apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/PreviewList.tsx
Labels: stat: ready to merge, automerge

#25632 Chore: RouteGroup for My Account sidebar
  apps/meteor/app/ui/client/views/app/burger.html
  apps/meteor/client/components/BurgerMenu/BurgerMenu.tsx
  apps/meteor/client/components/BurgerMenu/BurgerMenuButton.tsx
  apps/meteor/client/main.ts
  apps/meteor/client/providers/LayoutProvider.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/startup/routes.tsx
  apps/meteor/client/views/account/AccountRoute.js
  apps/meteor/client/views/account/AccountRouter.tsx
  apps/meteor/client/views/account/AccountSidebar.tsx
  apps/meteor/client/views/account/index.ts
  apps/meteor/client/views/account/integrations/AccountIntegrationsPage.tsx
  apps/meteor/client/views/account/integrations/AccountIntegrationsRoute.tsx
  apps/meteor/client/views/account/profile/AccountProfileForm.js
  apps/meteor/client/views/account/profile/AccountProfilePage.js
  apps/meteor/client/views/account/profile/AccountProfileRoute.tsx
  apps/meteor/client/views/account/profile/ActionConfirmModal.tsx
  apps/meteor/client/views/account/routes.tsx
  apps/meteor/client/views/account/security/AccountSecurityRoute.tsx
  apps/meteor/client/views/account/sidebarItems.ts
  apps/meteor/client/views/account/tokens/AccountTokensRoute.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/08-resolutions.spec.ts
  apps/meteor/tests/e2e/utils/pageobjects/Administration.ts
  apps/meteor/tests/e2e/utils/pageobjects/Global.ts
  apps/meteor/tests/e2e/utils/pageobjects/SideNav.ts
  packages/ui-contexts/src/LayoutContext.ts
Labels: stat: ready to merge, stat: QA skipped

#25842 Chore: Fix version on develop branch
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
Labels: stat: ready to merge, stat: QA skipped

#25831 Chore: Remove unused tokenpass integration code
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/authorization/server/functions/canAccessRoom.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomTokens.js
  apps/meteor/app/channel-settings/server/methods/saveRoomSettings.js
  apps/meteor/app/lib/server/methods/createPrivateGroup.js
  apps/meteor/app/lib/server/methods/joinRoom.ts
  apps/meteor/app/models/server/models/Rooms.js
  apps/meteor/app/models/server/models/Users.js
  apps/meteor/app/tokenpass/README.md
  apps/meteor/app/tokenpass/client/channelSettings.css
  apps/meteor/app/tokenpass/client/index.js
  apps/meteor/app/tokenpass/client/login-button.css
  apps/meteor/app/tokenpass/client/startup.js
  apps/meteor/app/tokenpass/client/styles.css
  apps/meteor/app/tokenpass/client/tokenChannelsList.html
  apps/meteor/app/tokenpass/client/tokenChannelsList.js
  apps/meteor/app/tokenpass/client/tokenpassChannelSettings.html
  apps/meteor/app/tokenpass/client/tokenpassChannelSettings.js
  apps/meteor/app/tokenpass/lib/common.js
  apps/meteor/app/tokenpass/server/Tokenpass.js
  apps/meteor/app/tokenpass/server/cronRemoveUsers.js
  apps/meteor/app/tokenpass/server/functions/getProtectedTokenpassBalances.js
  apps/meteor/app/tokenpass/server/functions/getPublicTokenpassBalances.js
  apps/meteor/app/tokenpass/server/functions/saveRoomTokensMinimumBalance.js
  apps/meteor/app/tokenpass/server/functions/updateUserTokenpassBalances.js
  apps/meteor/app/tokenpass/server/index.js
  apps/meteor/app/tokenpass/server/methods/findTokenChannels.js
  apps/meteor/app/tokenpass/server/methods/getChannelTokenpass.js
  apps/meteor/app/tokenpass/server/roomAccessValidator.compatibility.js
  apps/meteor/app/tokenpass/server/roomAccessValidator.internalService.ts
  apps/meteor/app/tokenpass/server/startup.js
  apps/meteor/app/ui-sidenav/client/roomList.js
  apps/meteor/app/utils/server/functions/getDefaultUserFields.ts
  apps/meteor/lib/rooms/adminFields.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/modules/watchers/publishFields.ts
  apps/meteor/server/sdk/types/IAuthorization.ts
  apps/meteor/server/sdk/types/IAuthorizationTokenpass.ts
  apps/meteor/server/services/authorization/canAccessRoom.ts
  apps/meteor/server/services/authorization/canAccessRoomTokenpass.ts
  apps/meteor/server/services/authorization/service.ts
  apps/meteor/server/services/startup.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v269.ts
  packages/core-typings/src/IRoom.ts
  packages/rest-typings/src/v1/rooms.ts
  packages/ui-contexts/src/ServerContext/methods/saveRoomSettings.ts
Labels: stat: ready to merge, stat: QA skipped

#25813 Chore: add _id and name options to JSON Schemas
  apps/meteor/app/api/server/v1/channels.ts
  packages/rest-typings/src/v1/channels/ChannelsGetAllUserMentionsByChannelProps.ts
  packages/rest-typings/src/v1/channels/ChannelsHistoryProps.ts
  packages/rest-typings/src/v1/channels/ChannelsJoinProps.ts
  packages/rest-typings/src/v1/channels/ChannelsKickProps.ts
  packages/rest-typings/src/v1/channels/ChannelsLeaveProps.ts
  packages/rest-typings/src/v1/channels/ChannelsMessagesProps.ts
  packages/rest-typings/src/v1/channels/ChannelsModeratorsProps.ts
  packages/rest-typings/src/v1/channels/ChannelsOpenProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetAnnouncementProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetReadOnlyProps.ts
  packages/rest-typings/src/v1/channels/channels.ts
  packages/rest-typings/src/v1/dm/DmCloseProps.ts
  packages/rest-typings/src/v1/dm/DmCreateProps.ts
  packages/rest-typings/src/v1/dm/DmDeleteProps.ts
  packages/rest-typings/src/v1/dm/DmHistoryProps.ts
  packages/rest-typings/src/v1/dm/DmKickProps.ts
  packages/rest-typings/src/v1/dm/DmLeaveProps.ts
Labels: stat: ready to merge, stat: QA skipped

#25698 Chore: Rewrite Admin UsersTable to Typescript
  apps/meteor/client/views/admin/users/AddUser.js
  apps/meteor/client/views/admin/users/AdminUserInfoWithData.js
  apps/meteor/client/views/admin/users/EditUserWithData.tsx
  apps/meteor/client/views/admin/users/InviteUsers.tsx
  apps/meteor/client/views/admin/users/UserPageHeaderContent.tsx
  apps/meteor/client/views/admin/users/UserRow.js
  apps/meteor/client/views/admin/users/UsersPage.js
  apps/meteor/client/views/admin/users/UsersPage.tsx
  apps/meteor/client/views/admin/users/UsersRoute.tsx
  apps/meteor/client/views/admin/users/UsersTable.js
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTableRow.tsx
  apps/meteor/client/views/admin/users/UsersTable/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/11-admin.spec.ts
  apps/meteor/tests/e2e/utils/pageobjects/Administration.ts
  packages/rest-typings/src/v1/users.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#25410 [FIX] fixes HTML sanitizing error.
  packages/livechat/src/lib/room.js
  packages/livechat/src/lib/threads.js
  packages/livechat/src/routes/Chat/container.js
Labels: stat: ready to merge, stat: QA tested

#25858 Chore: Rewrite RoomWithData
  apps/meteor/client/components/Sidebar/SidebarItemsAssembler.tsx
  apps/meteor/client/views/room/Room/Aside.js
  apps/meteor/client/views/room/Room/Body.js
  apps/meteor/client/views/room/Room/Footer.js
  apps/meteor/client/views/room/Room/RoomWithData.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#25634 Chore: Convert sidebar/item
  apps/meteor/client/sidebar/Item/Condensed.tsx
  apps/meteor/client/sidebar/Item/Extended.tsx
  apps/meteor/client/sidebar/Item/ExtendedSkeleton.tsx
  apps/meteor/client/sidebar/Item/Medium.tsx
  apps/meteor/client/sidebar/Item/skeletons/CondensedSkeleton.tsx
  apps/meteor/client/sidebar/Item/skeletons/MediumSkeleton.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#25863 Chore: Remove old rest api code
  apps/meteor/app/utils/client/lib/_RestApiClient.d.ts
  apps/meteor/app/utils/client/lib/_RestApiClient.js
Labels: stat: ready to merge, stat: QA skipped

#25714 Chore: Broken Storybook
  apps/meteor/.storybook/main.js
  apps/meteor/client/definitions/css.d.ts
  apps/meteor/client/views/admin/settings/inputs/CodeMirror.tsx
  apps/meteor/package.json
  packages/livechat/.storybook/main.js
  packages/livechat/.storybook/preview.js
  packages/livechat/.storybook/webpack.config.js
  packages/livechat/package.json
  packages/livechat/src/components/Footer/index.js
  packages/livechat/src/components/Messages/AudioAttachment/stories.js
  packages/livechat/src/components/Messages/Message/stories.js
  packages/livechat/src/components/Messages/VideoAttachment/stories.js
  packages/livechat/src/components/Sound/stories.js
  packages/livechat/src/components/uiKit/message/actions.stories.js
  packages/livechat/tsconfig.json
  packages/livechat/webpack.config.js
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25711 Chore: Update text from `Layout_Home_Body`
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v269.ts
Labels: stat: needs QA

#25016 [BREAK] Deactivated team members are added to auto-join rooms
  apps/meteor/app/models/server/raw/Users.js
  apps/meteor/server/services/team/service.ts
Labels: stat: ready to merge, stat: QA tested

#25859 [NEW] Homepage cards
  apps/meteor/client/components/Card/CardFooterWrapper.tsx
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/sidebar/header/CreateChannel.tsx
  apps/meteor/client/sidebar/header/CreateChannelWithData.tsx
  apps/meteor/client/views/home/CustomHomePage.tsx
  apps/meteor/client/views/home/DefaultHomePage.tsx
  apps/meteor/client/views/home/HomePage.tsx
  apps/meteor/client/views/home/HomePageHeader.tsx
  apps/meteor/client/views/home/cards/AddUsersCard.tsx
  apps/meteor/client/views/home/cards/CreateChannelsCard.tsx
  apps/meteor/client/views/home/cards/DesktopAppsCard.tsx
  apps/meteor/client/views/home/cards/DocumentationCard.tsx
  apps/meteor/client/views/home/cards/JoinRoomsCard.tsx
  apps/meteor/client/views/home/cards/MobileAppsCard.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/utils/pageobjects/ChannelCreation.ts
Labels: stat: needs QA

#25503 Chore: convert communication methods to Typescript
  apps/meteor/app/apps/server/communication/index.ts
  apps/meteor/app/apps/server/communication/methods.ts
  apps/meteor/app/apps/server/communication/uikit.js
  apps/meteor/app/apps/server/communication/uikit.ts
  apps/meteor/app/apps/server/communication/websockets.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, eng day, stat: QA skipped

#25690 Chore: Translate admin helpers to TS
  apps/meteor/app/apps/client/@types/IOrchestrator.ts
  apps/meteor/app/apps/client/orchestrator.ts
  apps/meteor/client/views/admin/apps/PriceDisplay.tsx
  apps/meteor/client/views/admin/apps/helpers.ts
  apps/meteor/client/views/admin/apps/hooks/useAppInfo.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/Apps.ts
Labels: stat: ready to merge, stat: QA skipped

#25869 [FIX] Kebab menu clicking issue
  apps/meteor/package.json
  apps/meteor/tests/e2e/04-main-elements-render.spec.ts
  apps/meteor/tests/e2e/pageobjects/FlexTab.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#25840 Chore: convert apps/meteor/app/api/server/lib/ files to TS
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/helpers/parseJsonQuery.ts
  apps/meteor/app/api/server/lib/emoji-custom.js
  apps/meteor/app/api/server/lib/emoji-custom.ts
  apps/meteor/app/api/server/lib/getUploadFormData.js
  apps/meteor/app/api/server/lib/getUploadFormData.ts
  apps/meteor/app/api/server/lib/messages.ts
  apps/meteor/app/api/server/lib/rooms.ts
  apps/meteor/app/api/server/lib/users.ts
  apps/meteor/app/api/server/v1/assets.js
  apps/meteor/app/api/server/v1/emoji-custom.ts
  apps/meteor/app/api/server/v1/rooms.js
  apps/meteor/app/api/server/v1/users.js
  apps/meteor/app/apps/server/bridges/listeners.js
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/authorization/client/index.ts
  apps/meteor/app/authorization/client/lib/streamer.ts
  apps/meteor/app/authorization/index.js
  apps/meteor/app/authorization/server/functions/canDeleteMessage.ts
  apps/meteor/app/livechat/imports/server/rest/upload.js
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25870 Chore: Fix correct unit test to api files
  apps/meteor/.mocharc.api.js
Labels: stat: ready to merge, stat: QA skipped

#25879 Chore: create Ajv schemas for some users.js endpoints
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/lib/users.ts
  apps/meteor/app/api/server/v1/users.js
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/lib/server/functions/setUserAvatar.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/users/UsersSetAvatarParamsPOST.ts
  packages/rest-typings/src/v1/users/UsersSetPreferenceParamsPOST.ts
  packages/rest-typings/src/v1/users/UsersUpdateOwnBasicInfoParamsPOST.ts
  packages/rest-typings/src/v1/users/UsersUpdateParamsPOST.ts
Labels: stat: needs QA

#25893 Regression: TOTP Modal with new rest api package
  apps/meteor/app/utils/client/lib/RestApiClient.ts
  packages/api-client/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#25880 [NEW] [VideoConference] Allow apps to create new video conferences
  apps/meteor/app/apps/server/bridges/videoConferences.ts
  apps/meteor/package.json
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
  yarn.lock
Labels: stat: needs QA

#25878 [NEW] [VideoConference] Allow apps to end calls and add users
  apps/meteor/app/apps/server/bridges/videoConferences.ts
  apps/meteor/app/apps/server/converters/videoConferences.ts
  apps/meteor/app/models/server/raw/VideoConference.ts
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#25872 [FIX] Update import from `csv-parse`
  apps/meteor/app/importer-csv/server/importer.js
  apps/meteor/app/importer-slack-users/server/importer.js
Labels: stat: ready to merge, stat: QA tested

#25826 [NEW] [VideoConference] Livechat Support
  apps/meteor/app/livechat/client/index.js
  apps/meteor/app/livechat/client/lib/messageTypes.js
  apps/meteor/app/livechat/server/api/lib/livechat.js
  apps/meteor/app/livechat/server/index.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/messageTypes.js
  apps/meteor/app/models/server/raw/VideoConference.ts
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/client/startup/messageTypes.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartOmnichannelVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartVideoConfModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/core-typings/src/IVideoConference.ts
  packages/livechat/src/components/Calls/CallNotification.js
  packages/livechat/src/components/Calls/JoinCallButton.js
  packages/livechat/src/components/Messages/MessageList/index.js
  packages/livechat/src/components/Messages/constants.js
  packages/livechat/src/lib/constants.js
  packages/livechat/src/lib/room.js
Labels: stat: needs QA

#25899 [NEW] [VideoConference] Split EE and CE features
  apps/meteor/ee/app/license/server/bundles.ts
  apps/meteor/ee/server/configuration/index.ts
  apps/meteor/ee/server/configuration/videoConference.ts
  apps/meteor/server/lib/videoConfTypes.ts
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#25891 [FIX] Settings not being overwritten to their default values
  apps/meteor/app/settings/server/SettingsRegistry.ts
Labels: stat: ready to merge, stat: QA skipped

#25358 Chore: Convert assets endpoint to Typescript
  apps/meteor/app/api/server/v1/assets.ts
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/assets/server/index.ts
  apps/meteor/app/utils/lib/mimeTypes.js
  apps/meteor/app/utils/lib/mimeTypes.ts
  apps/meteor/definition/externals/meteor/webapp-hashing.d.ts
  apps/meteor/tests/unit/lib/mimeTypes.tests.ts
  packages/core-typings/src/IRocketChatAssets.ts
  packages/core-typings/src/ISetting.ts
  packages/core-typings/src/index.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/assets.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#25910 Chore: Watch for package changes
  _templates/package/new/package.json.ejs.t
  package.json
  packages/api-client/package.json
  packages/core-typings/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-contexts/package.json
  turbo.json
Labels: stat: ready to merge, eng day, stat: QA skipped

#25747 Chore: Split useUserInfoActions into small hooks
  apps/meteor/client/views/hooks/useActionSpread.ts
  apps/meteor/client/views/room/hooks/useUserHasRoomRole.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions.js
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useAudioCallAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useBlockUserAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeLeaderAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeModeratorAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeOwnerAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useDirectMessageAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useIgnoreUserAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useMuteUserAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useRemoveUserAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useVideoCallAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/index.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/useUserInfoActions.ts
  apps/meteor/client/views/room/lib/getRoomDirectives.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/ISubscription.ts
  packages/rest-typings/src/v1/groups.ts
  packages/ui-contexts/src/hooks/useUserSubscriptionByName.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#25754 Chore: Convert apps/meteor/client/sidebar/search
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
  apps/meteor/client/sidebar/search/Row.tsx
  apps/meteor/client/sidebar/search/ScrollerWithCustomProps.js
  apps/meteor/client/sidebar/search/ScrollerWithCustomProps.tsx
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/sidebar/search/UserItem.tsx
  apps/meteor/definition/externals/meteor/meteor.d.ts
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#25868 [NEW] Create Team with a member list of usernames
  apps/meteor/app/models/server/raw/Users.js
  apps/meteor/server/services/team/service.ts
  apps/meteor/tests/end-to-end/api/25-teams.js
Labels: stat: ready to merge, stat: QA skipped

#25914 Chore: Convert RoomMenu
  apps/meteor/client/sidebar/RoomMenu.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#25556 Chore: Run tests on docker
  .github/actions/build-docker-image-service/action.yml
  .github/actions/build-docker-image/action.yml
  .github/workflows/build_and_test.yml
  apps/meteor/.docker/Dockerfile.alpine
  apps/meteor/.scripts/start.js
  apps/meteor/app/api/server/v1/teams.ts
  apps/meteor/package.json
  apps/meteor/server/services/team/service.ts
  apps/meteor/tests/e2e/utils/configs/verifyTestBaseUrl.ts
Labels: stat: ready to merge, stat: QA skipped

#25903 [NEW] [Video Conference] Capabilities Endpoint
  apps/meteor/app/api/server/v1/videoConference.ts
  apps/meteor/app/apps/server/bridges/videoConferences.ts
  apps/meteor/package.json
  apps/meteor/server/lib/videoConfProviders.ts
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/core-typings/src/VideoConferenceCapabilities.ts
  packages/core-typings/src/index.ts
  packages/rest-typings/src/v1/videoConference/index.ts
  yarn.lock
Labels: stat: needs QA

#25921 [FIX] [Video Conference] Action Order
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/tests/e2e/04-main-elements-render.spec.ts
Labels: stat: needs QA

#25830 Chore: Rewrite AddUsers to TS
  apps/meteor/client/components/VerticalBar/VerticalBarActionBack.tsx
  apps/meteor/client/components/VerticalBar/VerticalBarBack.tsx
  apps/meteor/client/components/VerticalBar/index.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.stories.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsersWithData.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#25873 [FIX] Update chartjs usage to v3
  apps/meteor/app/livechat/client/lib/chartHandler.js
  apps/meteor/app/livechat/client/lib/chartHandler.ts
  apps/meteor/client/views/omnichannel/analytics/InterchangeableChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/AgentStatusChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatDurationChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsPerAgentChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ResponseTimesChart.js
  package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#25915 Chore: Keep the option to run only the meteor app
  apps/meteor/package.json
  package.json
  turbo.json
Labels: stat: ready to merge, stat: QA skipped

#25911 Chore: Remove Imperative Modal from context
  apps/meteor/client/components/voip/modal/WrapUpCallModal.tsx
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#25923 Regression: Unable to edit user details via admin panel
  apps/meteor/client/views/admin/users/EditUser.js
  packages/rest-typings/src/v1/users/UsersUpdateParamsPOST.ts
Labels: stat: ready to merge, stat: QA skipped

#25743 Chore: Collect e2e coverage
  .github/workflows/build_and_test.yml
  apps/meteor/.babelrc
  apps/meteor/package.json
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/00-wizard.spec.ts
  apps/meteor/tests/e2e/01-forgot-password.spec.ts
  apps/meteor/tests/e2e/02-register.spec.ts
  apps/meteor/tests/e2e/03-login.spec.ts
  apps/meteor/tests/e2e/04-main-elements-render.spec.ts
  apps/meteor/tests/e2e/05-channel-creation.spec.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/07-emoji.spec.ts
  apps/meteor/tests/e2e/08-resolutions.spec.ts
  apps/meteor/tests/e2e/09-channel.spec.ts
  apps/meteor/tests/e2e/10-user-preferences.spec.ts
  apps/meteor/tests/e2e/11-admin.spec.ts
  apps/meteor/tests/e2e/12-settings.spec.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/14-setting-permissions.spec.ts
  apps/meteor/tests/e2e/15-message-popup.spec.ts
  apps/meteor/tests/e2e/16-discussion.spec.ts
  apps/meteor/tests/e2e/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/utils/test.ts
  yarn.lock
Labels: subj: Testing, stat: ready to merge, stat: QA skipped

#25877 [NEW] Homepage workspace name
  apps/meteor/client/views/home/DefaultHomePage.tsx
  apps/meteor/client/views/home/HomepageGridItem.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#25803 [NEW] [VideoConference] Blocked action hook & Modal
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/client/contexts/VideoConfContext.ts
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/sidebar/RoomList/Row.tsx
  apps/meteor/client/sidebar/hooks/useRoomList.ts
  apps/meteor/client/views/blocks/MessageBlock.js
  apps/meteor/client/views/room/contextualBar/VideoConference/JoinVideoConfModal/JoinVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartDirectVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartGroupVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartOmnichannelVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/CallingPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/ReceivingPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/TimedVideoConfPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.tsx
Labels: stat: ready to merge, stat: QA skipped

#25936 Revert: "Chore: Collect e2e coverage"
  .github/workflows/build_and_test.yml
  apps/meteor/.babelrc
  apps/meteor/package.json
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/00-wizard.spec.ts
  apps/meteor/tests/e2e/01-forgot-password.spec.ts
  apps/meteor/tests/e2e/02-register.spec.ts
  apps/meteor/tests/e2e/03-login.spec.ts
  apps/meteor/tests/e2e/04-main-elements-render.spec.ts
  apps/meteor/tests/e2e/05-channel-creation.spec.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/07-emoji.spec.ts
  apps/meteor/tests/e2e/08-resolutions.spec.ts
  apps/meteor/tests/e2e/09-channel.spec.ts
  apps/meteor/tests/e2e/10-user-preferences.spec.ts
  apps/meteor/tests/e2e/11-admin.spec.ts
  apps/meteor/tests/e2e/12-settings.spec.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/14-setting-permissions.spec.ts
  apps/meteor/tests/e2e/15-message-popup.spec.ts
  apps/meteor/tests/e2e/16-discussion.spec.ts
  apps/meteor/tests/e2e/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/utils/test.ts
  yarn.lock
Labels: stat: needs QA

#25931 Regression: Docker image publish
  .github/actions/build-docker-image-service/action.yml
  .github/actions/build-docker-image/action.yml
  .github/workflows/build_and_test.yml
Labels: stat: ready to merge, stat: QA skipped

#25886 [NEW] [VideoConference] Join conference endpoint call
  apps/meteor/app/models/server/raw/VideoConference.ts
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/views/blocks/MessageBlock.js
  apps/meteor/client/views/room/contextualBar/VideoConference/JoinVideoConfModal/JoinVideoConfModal.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/video-conference/service.ts
  packages/core-typings/src/IVideoConference.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25941 Chore: Avoid using console logs for email feature
  apps/meteor/server/email/IMAPInterceptor.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
Labels: stat: needs QA

#25947 [FIX] VOIP CallContext snapshot infinite loop
  apps/meteor/client/contexts/CallContext.ts
  apps/meteor/package.json
  packages/ui-contexts/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25876 Regression: Re-add view logs button
  apps/meteor/client/views/admin/apps/AppMenu.js
Labels: stat: ready to merge, stat: QA skipped

#25951 [NEW] [VideoConference] Create Ephemeral messages for config errors
  apps/meteor/app/api/server/v1/videoConference.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#25672 Chore: Upgrade and remove unnecessary Livechat dependencies
  packages/livechat/package.json
  packages/livechat/src/components/App/App.js
  packages/livechat/src/history.js
  packages/livechat/src/index.ts
  packages/livechat/src/routes/SwitchDepartment/container.js
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25900 [NEW] [VideoConference] Expire Old Calls
  apps/meteor/app/models/server/raw/VideoConference.ts
  apps/meteor/server/cron/videoConferences.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/server/startup/cron.js
Labels: stat: needs QA

#25905 [NEW] remove user from matrix room
  apps/meteor/app/federation-v2/server/application/RoomServiceSender.ts
  apps/meteor/app/federation-v2/server/application/input/RoomSenderDto.ts
  apps/meteor/app/federation-v2/server/domain/IFederationBridge.ts
  apps/meteor/app/federation-v2/server/index.ts
  apps/meteor/app/federation-v2/server/infrastructure/Factory.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/converters/RoomSender.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
Labels: stat: needs QA

#25822 [NEW] Hide channel actions + message box when the room is federated
  apps/meteor/app/discussion/client/tabBar.ts
  apps/meteor/app/livestream/client/tabBar.tsx
  apps/meteor/app/message-pin/client/tabBar.ts
  apps/meteor/app/threads/client/flextab/threadlist.tsx
  apps/meteor/app/ui-clean-history/client/lib/tabBar.ts
  apps/meteor/app/ui-message/client/messageBox/messageBox.html
  apps/meteor/app/ui-message/client/messageBox/messageBox.js
  apps/meteor/app/ui/client/views/app/room.js
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/app/webrtc/client/tabBar.tsx
  apps/meteor/client/components/Header/ToolBoxAction.tsx
  apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
  apps/meteor/client/views/room/lib/Toolbox/defaultActions.ts
  apps/meteor/client/views/room/lib/Toolbox/index.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: federation, stat: needs QA

#25773 [NEW] [Device Management] Manage Devices Admin Table
  apps/meteor/client/components/GenericModal.tsx
  apps/meteor/ee/app/license/server/bundles.ts
  apps/meteor/ee/client/startup/deviceManagement.ts
  apps/meteor/ee/client/startup/index.ts
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfo.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfoWithData.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/index.ts
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementPage.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementRoute.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementTable/DeviceIcon.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementTable/DeviceManagementRow.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementTable/DeviceManagementTable.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementTable/index.ts
  apps/meteor/ee/client/views/admin/deviceManagement/useDeviceLogout.tsx
  apps/meteor/ee/definition/rest/v1/sessions/sessions.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/ISession.ts
Labels: stat: needs QA

#11744 [NEW] Accept quoted slash command arguments
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/ui/client/lib/chatMessages.js
  apps/meteor/lib/utils/parseParameters.ts
  apps/meteor/tests/unit/lib/utils/parseParameters.tests.ts
Labels: stat: ready to merge, eng day, stat: QA tested

#25961 Regression: Set `offset` and `count` optional on `ChatGetThreadsListSchema`
  packages/rest-typings/src/v1/chat.ts
Labels: stat: ready to merge, stat: QA skipped

#25964 Chore: Update poplib
  .github/no-js-action-config.json
  apps/meteor/app/lib/server/lib/interceptDirectReplyEmails.js
  apps/meteor/package.json
  package.json
  packages/livechat/package.json
  packages/node-poplib/package.json
  packages/node-poplib/src/index.js
  yarn.lock
Labels: stat: needs QA

#25974 Regression: Fix e2e CI
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/11-admin.spec.ts
  turbo.json
Labels: stat: needs QA

#25874 [BREAK] use urlParams on omnichannel/agent/extension/
  apps/meteor/app/api/server/v1/voip/omnichannel.ts
  apps/meteor/client/views/admin/settings/groups/voip/RemoveAgentButton.tsx
  packages/rest-typings/src/v1/voip.ts
Labels: stat: ready to merge, stat: QA tested

#25980 Revert "[BREAK] use urlParams on omnichannel/agent/extension/"
  apps/meteor/app/api/server/v1/voip/omnichannel.ts
  apps/meteor/client/views/admin/settings/groups/voip/RemoveAgentButton.tsx
  packages/rest-typings/src/v1/voip.ts
Labels: Invalid PR Title, stat: needs QA

#25969 Chore: Colors
  apps/meteor/app/mentions/client/mentionLink.css
  apps/meteor/client/sidebar/Item/Condensed.stories.tsx
  apps/meteor/client/sidebar/Item/Extended.stories.tsx
  apps/meteor/client/sidebar/Item/Medium.stories.tsx
  apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.js
  apps/meteor/client/views/admin/permissions/EditRolePage.tsx
  apps/meteor/client/views/admin/permissions/UsersInRole/UsersInRoleTable/UsersInRoleTableRow.tsx
  apps/meteor/client/views/admin/settings/Section.tsx
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage.tsx
  apps/meteor/client/views/omnichannel/facebook/FacebookPage.tsx
  apps/meteor/client/views/room/contextualBar/OTR/components/OTREstablished.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/BBB/CallBBB.tsx
Labels: stat: ready to merge, stat: QA skipped

#25475 [FIX] Sort by scope or creation date not working on canned responses list
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx
Labels: stat: ready to merge, stat: QA tested

#25925 [FIX] toolbox menu behind thread component
  apps/meteor/client/views/room/MessageList/components/Toolbox/MessageActionMenu.tsx
  apps/meteor/client/views/room/MessageList/components/Toolbox/ToolboxDropdown.tsx
  apps/meteor/client/views/room/MessageList/components/Toolbox/ToolboxDropdownDesktop.tsx
Labels: stat: ready to merge, stat: QA tested

#25892 [NEW] [VideoConference] Conferences List contextualBar
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/JoinVideoConfModal/JoinVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfList.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListWithData.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/index.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/useVideoConfList.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#25849 [NEW] [Device Management] Logged out banner on Login Form
  apps/meteor/app/ui-login/client/index.js
  apps/meteor/app/ui-login/client/login/layout.html
  apps/meteor/app/ui-login/client/login/layout.js
  apps/meteor/app/ui-login/client/login/startup.ts
  apps/meteor/client/templates.ts
  apps/meteor/ee/client/components/deviceManagement/LoggedOutBanner.tsx
  apps/meteor/ee/server/api/sessions.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#25938 [NEW] [Video Conference] Hide buttons for unused capabilities
  apps/meteor/app/api/server/v1/videoConference.ts
  apps/meteor/client/views/blocks/MessageBlock.js
  apps/meteor/client/views/room/contextualBar/VideoConference/JoinVideoConfModal/JoinVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartDirectVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartGroupVideoConfModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/StartVideoConfModal/StartVideoConfModal.tsx
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/rest-typings/src/v1/videoConference/index.ts
Labels: stat: needs QA

#25990 Regression: Non-reactive routes
  apps/meteor/client/providers/RouterProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#25987 [FIX] sidebar colors
  apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.js
  turbo.json
Labels: stat: ready to merge, stat: QA skipped

#25983 Chore: Fuselage update
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25902 [NEW] [VideoConference] Statistics
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/client/views/admin/info/DeploymentCard.stories.tsx
  apps/meteor/client/views/admin/info/InformationPage.stories.tsx
  apps/meteor/client/views/admin/info/UsageCard.stories.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/server/models/raw/VideoConference.ts
  apps/meteor/server/sdk/types/IVideoConfService.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/server/settings/video-conference.ts
  packages/core-typings/src/IStats.ts
  packages/model-typings/src/models/IVideoConferenceModel.ts
Labels: stat: needs QA

#25756 Chore: Migrate from meteor model to raw
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/apps/server/converters/rooms.js
  apps/meteor/app/apps/server/converters/visitors.js
  apps/meteor/app/livechat/imports/server/rest/facebook.js
  apps/meteor/app/livechat/imports/server/rest/sms.js
  apps/meteor/app/livechat/imports/server/rest/upload.js
  apps/meteor/app/livechat/server/api/lib/livechat.js
  apps/meteor/app/livechat/server/api/v1/agent.js
  apps/meteor/app/livechat/server/api/v1/contact.js
  apps/meteor/app/livechat/server/api/v1/customField.js
  apps/meteor/app/livechat/server/api/v1/message.js
  apps/meteor/app/livechat/server/api/v1/room.js
  apps/meteor/app/livechat/server/api/v1/transcript.js
  apps/meteor/app/livechat/server/api/v1/videoCall.js
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/hooks/leadCapture.js
  apps/meteor/app/livechat/server/hooks/saveContactLastChat.js
  apps/meteor/app/livechat/server/hooks/sendToCRM.js
  apps/meteor/app/livechat/server/hooks/sendTranscriptOnClose.js
  apps/meteor/app/livechat/server/lib/Contacts.js
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/closeByVisitor.js
  apps/meteor/app/livechat/server/methods/getAgentData.js
  apps/meteor/app/livechat/server/methods/getInitialData.js
  apps/meteor/app/livechat/server/methods/loadHistory.js
  apps/meteor/app/livechat/server/methods/loginByToken.js
  apps/meteor/app/livechat/server/methods/registerGuest.js
  apps/meteor/app/livechat/server/methods/saveInfo.js
  apps/meteor/app/livechat/server/methods/saveSurveyFeedback.js
  apps/meteor/app/livechat/server/methods/sendFileLivechatMessage.js
  apps/meteor/app/livechat/server/methods/sendMessageLivechat.js
  apps/meteor/app/livechat/server/methods/setCustomField.js
  apps/meteor/app/livechat/server/methods/setDepartmentForVisitor.js
  apps/meteor/app/livechat/server/methods/startFileUploadRoom.js
  apps/meteor/app/livechat/server/methods/transfer.js
  apps/meteor/app/livechat/server/sendMessageBySMS.js
  apps/meteor/app/models/server/index.js
  apps/meteor/app/models/server/models/LivechatVisitors.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/ee/app/canned-responses/server/hooks/onMessageSentParsePlaceholder.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.js
  apps/meteor/ee/app/livechat-enterprise/server/methods/resumeOnHold.ts
  apps/meteor/imports/message-read-receipt/server/lib/ReadReceipt.js
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/server/lib/rooms/roomTypes/livechat.ts
  apps/meteor/server/models/raw/LivechatVisitors.ts
  apps/meteor/server/startup/migrations/v260.ts
  packages/core-typings/src/ILivechatVisitor.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
  yarn.lock
Labels: eng day, stat: needs QA

#26000 [FIX] Initial members value on Create Channel Modal
  apps/meteor/client/components/UserAutoComplete/UserAutoComplete.tsx
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx
  apps/meteor/client/sidebar/header/CreateChannelWithData.tsx
Labels: stat: ready to merge, stat: QA skipped

#25904 [NEW] [Device Management] User Preferences Table
  apps/meteor/ee/client/deviceManagement/components/DeviceIcon.tsx
  apps/meteor/ee/client/deviceManagement/components/DeviceManagementTable/DeviceManagementTable.tsx
  apps/meteor/ee/client/deviceManagement/components/DeviceManagementTable/index.ts
  apps/meteor/ee/client/hooks/useDeviceLogout.tsx
  apps/meteor/ee/client/startup/deviceManagement.ts
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountPage.tsx
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountRow.tsx
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountTable.tsx
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountTable/index.ts
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminPage.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminRow.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/index.ts
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfo.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#26004 Chore: Fuselage update
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25984 Chore: Fixes e2e playwright intermittences
  apps/meteor/client/components/Header/ToolBoxAction.tsx
  apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/List/RoomMembers.js
  apps/meteor/tests/e2e/00-wizard.spec.ts
  apps/meteor/tests/e2e/03-login.spec.ts
  apps/meteor/tests/e2e/04-main-elements-render.spec.ts
  apps/meteor/tests/e2e/05-channel-creation.spec.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/07-emoji.spec.ts
  apps/meteor/tests/e2e/08-resolutions.spec.ts
  apps/meteor/tests/e2e/09-channel.spec.ts
  apps/meteor/tests/e2e/10-user-preferences.spec.ts
  apps/meteor/tests/e2e/11-admin.spec.ts
  apps/meteor/tests/e2e/12-settings.spec.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/14-setting-permissions.spec.ts
  apps/meteor/tests/e2e/15-message-popup.spec.ts
  apps/meteor/tests/e2e/16-discussion.spec.ts
  apps/meteor/tests/e2e/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/pageobjects/Agents.ts
  apps/meteor/tests/e2e/pageobjects/ChannelCreation.ts
  apps/meteor/tests/e2e/pageobjects/Departments.ts
  apps/meteor/tests/e2e/pageobjects/Discussion.ts
  apps/meteor/tests/e2e/pageobjects/FlexTab.ts
  apps/meteor/tests/e2e/pageobjects/LoginPage.ts
  apps/meteor/tests/e2e/pageobjects/SideNav.ts
Labels: stat: ready to merge, stat: QA skipped

#26017 [NEW] [VideoConference] API Definition Tests
  apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfCancelProps.spec.ts
  apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfInfoProps.spec.ts
  apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfJoinProps.spec.ts
  apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfListProps.spec.ts
  apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfStartProps.spec.ts
Labels: stat: needs QA

#26018 [NEW] [VideoConference] API Tests
  apps/meteor/.mocharc.api.js
  apps/meteor/tests/data/apps/apps-data.js
  apps/meteor/tests/end-to-end/apps/00-installation.js
  apps/meteor/tests/end-to-end/apps/05-video-conferences.ts
Labels: stat: needs QA

#25928 Regression: Room Endpoint Call Issues
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfoWithData.js
  apps/meteor/client/views/teams/contextualBar/channels/RoomActions.js
  apps/meteor/client/views/teams/contextualBar/info/TeamsInfoWithData.js
Labels: stat: needs QA

#25958 Chore: convert e2e to ts
  apps/meteor/app/api/server/v1/e2e.ts
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/sidebar/search/SearchList.tsx
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/e2e.ts
  packages/rest-typings/src/v1/e2e/e2eGetUsersOfRoomWithoutKeyParamsGET.ts
  packages/rest-typings/src/v1/e2e/e2eSetRoomKeyIDParamsPOST.ts
  packages/rest-typings/src/v1/e2e/e2eSetUserPublicAndPrivateKeysParamsPOST.ts
  packages/rest-typings/src/v1/e2e/e2eUpdateGroupKeyParamsPOST.ts
Labels: stat: needs QA

#26008 Regression: Webhook Integration Creation + string error toast msg
  apps/meteor/client/hooks/useEndpointAction.ts
  apps/meteor/client/views/account/security/TwoFactorEmail.js
  apps/meteor/client/views/admin/integrations/edit/EditIncomingWebhook.js
  apps/meteor/client/views/admin/integrations/edit/EditOutgoingWebhook.js
  apps/meteor/client/views/admin/integrations/new/NewIncomingWebhook.js
  apps/meteor/client/views/admin/integrations/new/NewOutgoingWebhook.js
Labels: stat: ready to merge, stat: QA tested

#26015 Chore: Major refactors in pageobjects
  .github/workflows/build_and_test.yml
  apps/meteor/app/ui-message/client/message.html
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/00-wizard.spec.ts
  apps/meteor/tests/e2e/01-forgot-password.spec.ts
  apps/meteor/tests/e2e/02-register.spec.ts
  apps/meteor/tests/e2e/03-login.spec.ts
  apps/meteor/tests/e2e/04-main-elements-render.spec.ts
  apps/meteor/tests/e2e/05-channel-creation.spec.ts
  apps/meteor/tests/e2e/06-messaging.spec.ts
  apps/meteor/tests/e2e/07-emoji.spec.ts
  apps/meteor/tests/e2e/08-resolutions.spec.ts
  apps/meteor/tests/e2e/09-channel.spec.ts
  apps/meteor/tests/e2e/10-user-preferences.spec.ts
  apps/meteor/tests/e2e/11-admin.spec.ts
  apps/meteor/tests/e2e/12-settings.spec.ts
  apps/meteor/tests/e2e/13-permissions.spec.ts
  apps/meteor/tests/e2e/14-setting-permissions.spec.ts
  apps/meteor/tests/e2e/15-message-popup.spec.ts
  apps/meteor/tests/e2e/16-discussion.spec.ts
  apps/meteor/tests/e2e/configs/setup.ts
  apps/meteor/tests/e2e/configs/teardown.ts
  apps/meteor/tests/e2e/pageobjects/Administration.ts
  apps/meteor/tests/e2e/pageobjects/Agents.ts
  apps/meteor/tests/e2e/pageobjects/BasePage.ts
  apps/meteor/tests/e2e/pageobjects/ChannelCreation.ts
  apps/meteor/tests/e2e/pageobjects/Departments.ts
  apps/meteor/tests/e2e/pageobjects/Discussion.ts
  apps/meteor/tests/e2e/pageobjects/FlexTab.ts
  apps/meteor/tests/e2e/pageobjects/Global.ts
  apps/meteor/tests/e2e/pageobjects/LoginPage.ts
  apps/meteor/tests/e2e/pageobjects/MainContent.ts
  apps/meteor/tests/e2e/pageobjects/PreferencesMainContent.ts
  apps/meteor/tests/e2e/pageobjects/SetupWizard.ts
  apps/meteor/tests/e2e/pageobjects/SideNav.ts
  apps/meteor/tests/e2e/pageobjects/index.ts
  apps/meteor/tests/e2e/utils/MongoHelper.ts
  apps/meteor/tests/e2e/utils/configs/verifyTestBaseUrl.ts
  apps/meteor/tests/e2e/utils/constants.ts
  apps/meteor/tests/e2e/utils/enums/Checkbox.ts
  apps/meteor/tests/e2e/utils/helpers/clearMessages.ts
  apps/meteor/tests/e2e/utils/mocks/channel.ts
  apps/meteor/tests/e2e/utils/mocks/initialData.ts
  apps/meteor/tests/e2e/utils/mocks/interations.ts
  apps/meteor/tests/e2e/utils/mocks/userAndPasswordMock.ts
Labels: stat: ready to merge, stat: QA skipped

#25998 Chore: suggestions for PR #25993
  apps/meteor/server/startup/migrations/v270.ts
  packages/core-typings/src/IVoipExtension.ts
Labels: stat: needs QA

#25875 [IMPROVE] Moved call wrap up modal to EE
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/ee/app/license/server/bundles.ts
  apps/meteor/ee/client/hooks/useHasLicense.js
  apps/meteor/ee/client/hooks/useHasLicense.ts
  apps/meteor/ee/client/voip/components/modals/WrapUpCallModal.tsx
Labels: stat: ready to merge, stat: QA tested

#24379 [FIX] Append path To Route For Custom Emoji
  apps/meteor/app/emoji/client/emojiPicker.js
Labels: stat: ready to merge, stat: QA skipped

#25643 [IMPROVE] Differ Voip calls from Incoming and Outgoing
  apps/meteor/app/api/server/v1/voip/rooms.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTable.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/VoipRoom.ts
  apps/meteor/server/sdk/types/IOmnichannelVoipService.ts
  apps/meteor/server/services/omnichannel-voip/internalTypes.ts
  apps/meteor/server/services/omnichannel-voip/service.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v270.ts
  apps/meteor/tests/data/rooms.helper.js
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/IVoipRoomModel.ts
  packages/rest-typings/src/v1/voip.ts
Labels: stat: ready to merge, stat: QA skipped

#26001 Chore: Updating Apps-Engine
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26024 Regression: Fix voip call wrap-up model not working
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/tags.js
  apps/meteor/ee/server/models/raw/LivechatTag.ts
  apps/meteor/server/services/omnichannel-voip/service.ts
  packages/model-typings/src/models/ILivechatTagModel.ts
Labels: stat: ready to merge, stat: QA skipped

#25997 Chore: MDM Session sort by loginAt
  apps/meteor/app/models/server/raw/Sessions.ts
Labels: stat: needs QA

#26038 Chore: test turbo params
  .github/workflows/build_and_test.yml
  .github/workflows/no-new-js-files.yml
Labels: stat: needs QA

#26035 Chore: Convert usePreventDefault, useQueryOptions, useShortcutOpenMenu
  apps/meteor/client/sidebar/hooks/usePreventDefault.ts
  apps/meteor/client/sidebar/hooks/useQueryOptions.ts
  apps/meteor/client/sidebar/hooks/useShortcutOpenMenu.js
  apps/meteor/client/sidebar/hooks/useShortcutOpenMenu.ts
Labels: stat: needs QA

#25505 [NEW] Engagement Metrics - Phase 2
  apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.js
  apps/meteor/app/lib/server/lib/meteorFixes.js
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/app/livechat/server/api/v1/videoCall.js
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/app/models/server/models/Rooms.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/app/webrtc/server/settings.ts
  apps/meteor/client/views/admin/info/DeploymentCard.stories.tsx
  apps/meteor/client/views/admin/info/InformationPage.stories.tsx
  apps/meteor/client/views/admin/info/UsageCard.stories.tsx
  apps/meteor/server/models/raw/Roles.ts
  apps/meteor/server/models/raw/Rooms.js
  packages/core-typings/src/IStats.ts
  packages/model-typings/src/models/IRolesModel.ts
  packages/model-typings/src/models/IRoomsModel.ts
Labels: stat: ready to merge, stat: QA skipped

#26007 [IMPROVE] Moved call hold/unhold to EE
  apps/meteor/client/sidebar/footer/voip/VoipFooter.stories.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/client/sidebar/footer/voip/index.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#25934 [FIX] Importer fails to download files from URLs with query string params
  apps/meteor/app/importer/server/methods/downloadPublicImportFile.js
Labels: stat: ready to merge, stat: QA skipped

#26047 Chore: Introduce new index to query active livechat conversations for cloud scaling
  apps/meteor/app/models/server/models/LivechatRooms.js
Labels: stat: ready to merge, stat: QA skipped

#25937 [NEW][APPS] Allowing apps to register authenticated routes
  apps/meteor/app/api/server/middlewares/authentication.ts
  apps/meteor/app/apps/server/bridges/api.ts
  apps/meteor/app/apps/server/communication/uikit.ts
  apps/meteor/app/oauth2-server-config/server/oauth/oauth2-server.ts
  apps/meteor/definition/externals/express.d.ts
Labels: stat: ready to merge, stat: QA skipped

#26036 Chore: Bump fuselage and update icon
  apps/meteor/client/sidebar/header/actions/Directory.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26020 Chore: Corrections to suggested texts for MDM
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#25929 Chore: Account/Profile to TS
  apps/meteor/client/components/CustomFieldsForm.js
  apps/meteor/client/hooks/useUpdateAvatar.ts
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
  packages/core-typings/src/IUser.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#25966 [NEW] VoIP Input/Output Device Selection
  apps/meteor/client/contexts/CallContext.ts
  apps/meteor/client/lib/voip/LocalStream.ts
  apps/meteor/client/lib/voip/RemoteStream.ts
  apps/meteor/client/lib/voip/Stream.ts
  apps/meteor/client/lib/voip/VoIPUser.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/providers/DeviceProvider.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/ee/client/hooks/useDevicesMenuOption.tsx
  apps/meteor/ee/client/hooks/useVoipFooterMenu.tsx
  apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/ui-contexts/src/DeviceContext.ts
  packages/ui-contexts/src/hooks/useAvailableDevices.ts
  packages/ui-contexts/src/hooks/useDeviceConstraints.ts
  packages/ui-contexts/src/hooks/useSelectedDevices.ts
  packages/ui-contexts/src/hooks/useSetInputMediaDevice.ts
  packages/ui-contexts/src/hooks/useSetOutputMediaDevice.ts
  packages/ui-contexts/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#26006 [NEW] Device management feature modal
  apps/meteor/app/api/server/v1/modals.ts
  apps/meteor/ee/client/deviceManagement/components/featureModal/DeviceManagementFeatureModal.tsx
  apps/meteor/ee/client/deviceManagement/components/featureModal/FeatureModalBullets.tsx
  apps/meteor/ee/client/deviceManagement/components/featureModal/index.ts
  apps/meteor/ee/client/startup/deviceManagement.ts
  apps/meteor/ee/server/lib/deviceManagement/findDeviceManagementModal.ts
  apps/meteor/ee/server/lib/deviceManagement/startup.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/Modals.ts
  apps/meteor/server/models/raw/ModalDismiss.ts
  apps/meteor/server/models/raw/Modals.ts
  apps/meteor/server/models/startup.ts
  apps/meteor/server/startup/migrations/v272-deviceManagement.ts
  packages/core-typings/src/IModal.ts
  packages/core-typings/src/IModalDismiss.ts
  packages/model-typings/package.json
  packages/models/src/index.ts
Labels: stat: needs QA

#26052 Regression: Fix threads list
  apps/meteor/client/lib/utils/mapMessageFromApi.ts
Labels: stat: ready to merge, stat: QA skipped

#26054 Regression: Fix micro services
  apps/meteor/definition/externals/meteor/meteor.d.ts
  apps/meteor/definition/externals/meteor/rocketchat-streamer.d.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/ee/server/services/tsconfig.json
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/services/voip/lib/Helper.ts
  ee/apps/ddp-streamer/package.json
  ee/apps/ddp-streamer/tsconfig.json
Labels: stat: ready to merge, stat: QA skipped

#25993 [IMPROVE] VoIP admin page cleanup: remove unused settings
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/client/providers/CallProvider/hooks/useVoipClient.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/server/services/voip/lib/Helper.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v272.ts
  packages/core-typings/src/IVoipExtension.ts
  packages/core-typings/src/IVoipServerConfig.ts
  packages/core-typings/src/voip/IRegistrationInfo.ts
Labels: stat: ready to merge, stat: QA tested

#25889 [BREAK] remove unused endpoints and restify others
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/imports/server/rest/officeHour.js
  apps/meteor/app/livechat/server/api.js
  apps/meteor/app/livechat/server/api/lib/officeHour.js
  apps/meteor/app/livechat/server/index.js
  apps/meteor/app/livechat/server/methods/getInitialData.js
  apps/meteor/app/livechat/server/methods/startFileUploadRoom.js
  apps/meteor/client/components/Omnichannel/Tags.tsx
  apps/meteor/client/views/hooks/useDepartmentsByUnitsList.ts
  apps/meteor/client/views/hooks/useMonitorsList.ts
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/PriorityField.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit.js
  apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
  apps/meteor/ee/app/livechat-enterprise/client/views/app/customTemplates/visitorEditCustomFieldsForm.js
  apps/meteor/ee/app/livechat-enterprise/client/views/app/customTemplates/visitorInfoCustomForm.js
  apps/meteor/ee/app/livechat-enterprise/server/api/business-hours.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/departments.js
  apps/meteor/ee/app/livechat-enterprise/server/api/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/inquiries.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/priorities.js
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/priorities.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/monitors.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/priorities.js
  apps/meteor/ee/app/livechat-enterprise/server/api/priorities.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/units.ts
  apps/meteor/ee/client/hooks/useTagsList.ts
  apps/meteor/ee/client/omnichannel/BusinessHoursTableContainer.js
  apps/meteor/ee/client/omnichannel/monitors/MonitorsPage.js
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesRoute.js
  apps/meteor/ee/client/omnichannel/priorities/PriorityEditWithData.js
  apps/meteor/ee/client/omnichannel/tags/TagEditWithData.js
  apps/meteor/ee/client/omnichannel/tags/TagsRoute.js
  apps/meteor/ee/client/omnichannel/units/UnitEditWithData.tsx
  apps/meteor/ee/client/omnichannel/units/UnitNew.js
  apps/meteor/ee/client/omnichannel/units/UnitsRoute.js
  apps/meteor/ee/definition/rest/v1/omnichannel/businessHours.ts
  apps/meteor/ee/definition/rest/v1/omnichannel/businessUnits.ts
  apps/meteor/ee/server/models/raw/LivechatPriority.ts
  apps/meteor/tests/end-to-end/api/livechat/01-department.js
  apps/meteor/tests/end-to-end/api/livechat/office-hour.js
  packages/core-typings/src/ILivechatPriority.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/models/ILivechatPriorityModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested

#25844 [NEW] Community Edition Watermark
  apps/meteor/client/contexts/CallContext.ts
  apps/meteor/client/sidebar/footer/SidebarFooter.tsx
  apps/meteor/ee/server/api/licenses.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/20-licenses.js
  packages/rest-typings/src/v1/licenses.ts
Labels: stat: ready to merge, stat: QA tested

#25959 [FIX] Add HomePageHeader to CustomHomePage
  apps/meteor/client/views/home/CustomHomePage.tsx
Labels: stat: needs QA, stat: QA tested

#22588 [FIX] Direct Reply
  apps/meteor/app/lib/server/functions/notifications/email.js
  apps/meteor/app/lib/server/lib/interceptDirectReplyEmails.js
  apps/meteor/app/lib/server/lib/processDirectEmail.js
  apps/meteor/app/lib/server/lib/processDirectEmail.ts
  apps/meteor/app/lib/server/startup/settingsOnLoadDirectReply.js
  apps/meteor/app/lib/server/startup/settingsOnLoadDirectReply.ts
  apps/meteor/server/email/IMAPInterceptor.ts
Labels: stat: needs QA

#26056 Regression: Invalid Voip host issue preventing agents connecting to asterisk
  apps/meteor/client/providers/CallProvider/hooks/useVoipClient.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/voip/lib/Helper.ts
  apps/meteor/server/services/voip/service.ts
  packages/core-typings/src/IVoipServerConfig.ts
  packages/core-typings/src/voip/IRegistrationInfo.ts
Labels: stat: ready to merge, stat: QA skipped

#25916 Chore: ui-client package
  apps/meteor/client/providers/TooltipProvider.tsx
  apps/meteor/client/views/admin/apps/AppDetailsPageContent.tsx
  apps/meteor/client/views/admin/apps/AppsWhatIsIt.tsx
  apps/meteor/client/views/admin/info/TextSeparator.js
  apps/meteor/client/views/location/MapViewFallback.tsx
  apps/meteor/client/views/location/MapViewImage.tsx
  apps/meteor/client/views/omnichannel/webhooks/WebhooksPage.js
  apps/meteor/client/views/room/MessageList/MessageListErrorBoundary.tsx
  apps/meteor/client/views/room/Room/Room.tsx
  apps/meteor/ee/client/views/admin/info/SeatsCard.tsx
  apps/meteor/ee/client/views/admin/users/CloseToSeatsCapModal.tsx
  apps/meteor/ee/client/views/admin/users/ReachedSeatsCapModal.tsx
  apps/meteor/ee/client/views/admin/users/UserPageHeaderContentWithSeatsCap.tsx
  apps/meteor/package.json
  packages/ui-client/.eslintrc
  packages/ui-client/.storybook/main.js
  packages/ui-client/.storybook/preview.js
  packages/ui-client/package.json
  packages/ui-client/src/components/DotLeader.stories.tsx
  packages/ui-client/src/components/DotLeader.tsx
  packages/ui-client/src/components/ErrorBoundary.tsx
  packages/ui-client/src/components/ExternalLink.tsx
  packages/ui-client/src/components/TooltipComponent.tsx
  packages/ui-client/src/components/index.ts
  packages/ui-client/src/index.ts
  packages/ui-client/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, eng day, stat: QA skipped

#26059 Chore: Convert normalizeMessagesForUser
  apps/meteor/app/lib/server/functions/loadMessageHistory.ts
  apps/meteor/app/utils/server/lib/normalizeMessagesForUser.ts
Labels: stat: ready to merge, stat: QA skipped

#26058 [FIX] Error "numRequestsAllowed" property in rateLimiter for REST API endpoint when upgrading
  apps/meteor/app/api/server/v1/users.ts
Labels: stat: ready to merge, stat: QA skipped

#26065 Chore: Convert useSidebarPaletteColor
  apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts
  apps/meteor/package.json
  packages/ui-contexts/src/SettingsContext.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#25988 Regression: Add appId prop to slashcommand
  apps/meteor/app/slackbridge/client/slackbridge_import.client.js
  apps/meteor/app/slackbridge/server/slackbridge_import.server.js
  apps/meteor/app/slashcommand-asciiarts/lib/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/lib/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/lib/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/lib/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/lib/unflip.ts
  apps/meteor/app/slashcommands-archiveroom/client/client.ts
  apps/meteor/app/slashcommands-archiveroom/server/server.ts
  apps/meteor/app/slashcommands-bridge/client/index.ts
  apps/meteor/app/slashcommands-bridge/server/index.ts
  apps/meteor/app/slashcommands-create/client/client.ts
  apps/meteor/app/slashcommands-create/server/server.ts
  apps/meteor/app/slashcommands-help/server/server.ts
  apps/meteor/app/slashcommands-hide/client/hide.ts
  apps/meteor/app/slashcommands-hide/server/hide.ts
  apps/meteor/app/slashcommands-invite/client/client.ts
  apps/meteor/app/slashcommands-invite/server/server.ts
  apps/meteor/app/slashcommands-inviteall/client/client.ts
  apps/meteor/app/slashcommands-inviteall/server/server.ts
  apps/meteor/app/slashcommands-join/client/client.ts
  apps/meteor/app/slashcommands-join/server/server.ts
  apps/meteor/app/slashcommands-kick/client/client.ts
  apps/meteor/app/slashcommands-kick/server/server.ts
  apps/meteor/app/slashcommands-leave/server/leave.ts
  apps/meteor/app/slashcommands-me/server/me.ts
  apps/meteor/app/slashcommands-msg/server/server.ts
  apps/meteor/app/slashcommands-mute/server/mute.ts
  apps/meteor/app/slashcommands-mute/server/unmute.ts
  apps/meteor/app/slashcommands-open/client/client.ts
  apps/meteor/app/slashcommands-status/client/status.ts
  apps/meteor/app/slashcommands-status/server/status.ts
  apps/meteor/app/slashcommands-topic/client/topic.ts
  apps/meteor/app/slashcommands-topic/server/topic.ts
  apps/meteor/app/slashcommands-unarchiveroom/client/client.ts
  apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/client/startup/slashCommands.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
  packages/core-typings/src/SlashCommands/index.ts
  packages/rest-typings/src/v1/commands.ts
Labels: stat: ready to merge, stat: QA skipped

#25855 [FIX] Update subscription on update team member
  apps/meteor/server/services/team/service.ts
Labels: stat: ready to merge, stat: QA tested

#26069 Chore: Make kodiak merge message empty
  .kodiak.toml
Labels: stat: ready to merge, stat: QA skipped

#26070 Chore: Close tooltip on click
  apps/meteor/client/providers/TooltipProvider.tsx
Labels: stat: ready to merge, stat: QA skipped
