Repository RocketChat/Rocket.Chat, pull requests merged in 2022-01, with the labels that each got.

#23605 [IMPROVE] Add Rocket.Chat version to User-Agent header for oembed requests
  app/oembed/server/server.js
Labels: communityPR

#24078 [IMPROVE] Added a Reset Button in the Account Profile Page
  client/views/account/AccountProfilePage.js
Labels: communityPR

#24117 [FIX] Custom Emoji Image preview
  app/cors/server/cors.js
Labels: subj: ui/ux

#24098 [FIX] openUserInfo not working after changing room types
  client/views/room/providers/ToolboxProvider.tsx
Labels: communityPR

#24248 [FIX] Fixed broken links in setup wizard
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: communityPR

#24126 [FIX] Wrong german translation for 2FA-Promt
  packages/rocketchat-i18n/i18n/de.i18n.json
Labels: communityPR

#24177 [IMPROVE] lib/Statistics improved and metrics collector
  app/cloud/server/functions/buildRegistrationData.js
  app/statistics/server/lib/statistics.js
  definition/ISetting.ts
  server/lib/statistics/getSettingsStatistics.ts
Labels: feat: statistics, backend

#24109 [IMPROVE] Added a new "All" tab which shows all integrations in Integrations
  client/views/admin/integrations/IntegrationsPage.tsx
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: subj: ui/ux, communityPR
