Repository RocketChat/Rocket.Chat, pull requests merged in 2022-10, with the labels that each got.

#26983 Regression: Composer not reactive when omnichannel room closed
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/ComposerOmnichannel.tsx
  apps/meteor/client/views/room/contexts/RoomContext.ts
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26988 Regression: Handle `undefined` values on `useReactiveQuery`'s query function
  apps/meteor/app/ui-utils/client/lib/openRoom.tsx
  apps/meteor/client/hooks/useReactiveQuery.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/mergeSubscriptionsAndRooms.ts
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/usePutChatOnHoldMutation.ts
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useReturnChatToQueueMutation.ts
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerContainer.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/ComposerOmnichannel.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/ComposerOmnichannelOnHold.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/hooks/useResumeChatOnHoldMutation.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/definition/methods/omnichannel.ts
Labels: stat: needs QA

#26976 Regression: Fixed takeInquiry method not displaying error messages on the client
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/ComposerOmnichannelInquiry.tsx
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, Omnichannel

#26987 [IMPROVE] Use cached EE Cloud license on startup
  apps/meteor/app/cloud/server/functions/connectWorkspace.ts
  apps/meteor/app/cloud/server/functions/finishOAuthAuthorization.js
  apps/meteor/app/cloud/server/functions/getConfirmationPoll.ts
  apps/meteor/app/cloud/server/functions/getUserCloudAccessToken.js
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js
  apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts
  apps/meteor/app/cloud/server/functions/startRegisterWorkspace.ts
  apps/meteor/app/cloud/server/functions/startRegisterWorkspaceSetupWizard.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace.ts
  apps/meteor/app/cloud/server/functions/userLogout.js
Labels: stat: ready to merge, stat: QA skipped

#26975 Regression: Omnichannel Contact Center empty on no filter search
  apps/meteor/app/livechat/imports/server/rest/visitors.ts
  apps/meteor/app/livechat/server/api/lib/visitors.ts
  apps/meteor/server/models/raw/LivechatVisitors.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, Omnichannel

#26971 [FIX] Message Parser - Emphasis highlight in Links/URLs
  packages/gazzodown/src/elements/LinkSpan.tsx
Labels: stat: needs QA, feat: team-collab

#26426 Chore: `improve/media-recorder`
  apps/meteor/app/theme/client/imports/components/message-box.css
  apps/meteor/app/ui-message/client/messageBox/messageBox.html
  apps/meteor/app/ui-message/client/messageBox/messageBox.ts
  apps/meteor/app/ui-message/client/messageBox/messageBoxActions.ts
  apps/meteor/app/ui-message/client/messageBox/messageBoxAudioMessage.html
  apps/meteor/app/ui-message/client/messageBox/messageBoxAudioMessage.ts
  apps/meteor/app/ui/client/index.ts
  apps/meteor/app/ui/client/lib/fileUpload.ts
  apps/meteor/app/ui/client/lib/recorderjs/AudioEncoder.ts
  apps/meteor/app/ui/client/lib/recorderjs/AudioRecorder.ts
  apps/meteor/app/ui/client/lib/recorderjs/audioRecorder.js
  apps/meteor/client/templates.ts
  apps/meteor/client/views/composer/AudioMessageRecorder/AudioMessageRecorder.tsx
  apps/meteor/client/views/composer/AudioMessageRecorder/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: eng day, stat: needs QA

#27002 Regression: Use raw models instead of meteor ones on visitor inactivity processing
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.js
  apps/meteor/ee/app/livechat-enterprise/server/startup.ts
Labels: stat: ready to merge, stat: QA skipped, Omnichannel

#27023 Regression: Cannot edit messages in some environments.
  apps/meteor/app/lib/server/functions/updateMessage.ts
Labels: stat: needs QA

#27008 Regression: Double Table Cell Causing extra padding on Current Chats
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/client/views/omnichannel/currentChats/RemoveChatButton.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested, Omnichannel

#27009 Regression: VideoConf Actions Reactivity in SidebarItem
  apps/meteor/client/sidebar/RoomList/RoomList.tsx
  apps/meteor/client/sidebar/RoomList/RoomListRow.tsx
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
Labels: stat: ready to merge, stat: QA skipped

#27042 Chore: Bump fuselage to latest
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/presence-service/package.json
  ee/apps/stream-hub-service/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27059 Chore: Bump Apps-Engine version
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27067 Merge master into develop & Set version to 5.3.0-develop
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
Labels: stat: needs QA

#27044 [IMPROVE] Change status/price badge to fuselage tag
  apps/meteor/client/views/admin/apps/AppDetailsHeader.tsx
  apps/meteor/client/views/admin/apps/AppStatus.js
  apps/meteor/client/views/admin/apps/PriceDisplay.tsx
  apps/meteor/client/views/admin/apps/helpers.ts
  apps/meteor/client/views/admin/apps/helpers/filterAppsByEnabled.ts
Labels: stat: ready to merge, stat: QA tested

#27030 Chore: Implement short description for marketplace apps
  apps/meteor/client/views/admin/apps/AppDetailsHeader.tsx
  packages/core-typings/src/Apps.ts
Labels: stat: ready to merge, automerge, stat: QA tested

#27025 [FIX] Switch deprecated fields for projection
  apps/meteor/app/livechat/server/lib/Livechat.js
Labels: stat: ready to merge, stat: QA skipped, Omnichannel

#27038 [IMPROVE] Respect convert ascii to emoji preference for new message template
  apps/meteor/client/views/room/MessageList/components/MessageContentBody.tsx
  packages/gazzodown/src/Markup.spec.tsx
  packages/gazzodown/src/MarkupInteractionContext.ts
  packages/gazzodown/src/emoji/Emoji.tsx
  packages/gazzodown/src/emoji/EmojiRenderer.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27013 [FIX] On hold reactivity for Omnichannel rooms
  apps/meteor/app/livechat/server/lib/RoutingManager.js
  apps/meteor/app/models/server/models/Subscriptions.js
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26850 [FIX] Email inbox memory leak on connection failure
  apps/meteor/app/models/server/models/LivechatRooms.js
  apps/meteor/server/email/IMAPInterceptor.ts
  apps/meteor/server/features/EmailInbox/EmailInbox.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#27043 Chore: remove excess space from html preview
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedHtmlPreview.tsx
Labels: stat: ready to merge, stat: QA tested

#26995 Chore: Remove default value from custom home content setting
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/client/views/home/CustomHomePageContent.tsx
  apps/meteor/client/views/home/DefaultHomePage.tsx
Labels: stat: ready to merge, hacktoberfest-accepted, stat: QA tested

#26960 [FIX] Remove voip extension when agent is removed or deactivated
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/app/livechat/server/index.js
  apps/meteor/app/livechat/server/lib/Livechat.js
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26938 Chore: Refactor AppLogs to TS
  apps/meteor/client/views/admin/apps/AppLogs.js
  apps/meteor/client/views/admin/apps/AppLogs.tsx
  apps/meteor/client/views/admin/apps/LogItem.tsx
  apps/meteor/client/views/admin/apps/hooks/useLogs.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/ILogs.ts
  packages/core-typings/src/index.ts
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, stat: QA tested

#26963 [IMPROVE] Automatically open call info contextual bar when voip room is opened
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/client/views/room/providers/ToolboxProvider.tsx
  apps/meteor/lib/rooms/roomTypes/voip.ts
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#27052 [FIX] Actionable messages are now sent to integrations webhook
  apps/meteor/app/livechat/server/hooks/sendToCRM.js
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26682 Chore: Use a single notification listener for all videoconf messages
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
Labels: stat: ready to merge, stat: QA skipped

#27086 [FIX] Warning about livechat/inquiries.queuedForUser
  apps/meteor/app/livechat/client/lib/stream/queueManager.js
Labels: stat: ready to merge, stat: QA skipped, Omnichannel

#27068 Chore: UserCard loader tweaks
  apps/meteor/client/components/UserCard/UserCard.tsx
  apps/meteor/client/components/UserCard/UserCardContainer.tsx
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
Labels: stat: ready to merge, stat: QA skipped

#27040 [FIX] check if message block has item to show message body
  apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
  apps/meteor/tests/unit/client/views/room/MessageList/MessageContent.spec.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27088 [BREAK] Deprecate `queueOrder` property from routing/sorting
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/models/server/models/LivechatInquiry.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewInquiry.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/ee/app/models/server/models/LivechatInquiry.js
  apps/meteor/server/models/raw/LivechatInquiry.ts
  packages/core-typings/src/IInquiry.ts
Labels: stat: needs QA

#27087 [NEW] Add "Sorting Mechanism" setting
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#27020 [FIX] Uncaught error by listening stream-notify-room without subscription
  apps/meteor/server/modules/notifications/notifications.module.ts
Labels: stat: ready to merge, stat: QA skipped, Omnichannel

#26796 Chore: Email Inbox Sanitization
  apps/meteor/app/api/server/v1/email-inbox.ts
  apps/meteor/client/views/admin/emailInbox/EmailInboxEditWithData.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxForm.js
  apps/meteor/client/views/admin/emailInbox/EmailInboxForm.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxFormWithData.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxPage.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxRoute.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxTable.tsx
  apps/meteor/client/views/admin/emailInbox/SendTestButton.tsx
  apps/meteor/client/views/admin/emailInbox/Skeleton.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/email-inboxes.spec.ts
  apps/meteor/tests/e2e/page-objects/admin-email-inboxes.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/utils.ts
  apps/meteor/tests/end-to-end/api/livechat/11-email-inbox.ts
  packages/core-typings/src/IEmailInbox.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#27026 [NEW] Health check for data stream
  apps/meteor/server/database/DatabaseWatcher.ts
  apps/meteor/server/main.ts
  apps/meteor/server/routes/health.ts
  apps/meteor/server/startup/watchDb.ts
  ee/apps/stream-hub-service/src/StreamHub.ts
  ee/apps/stream-hub-service/src/service.ts
Labels: stat: ready to merge, stat: QA skipped

#27050 [FIX] Preview message not showing when reply direct message
  apps/meteor/client/views/room/MessageList/components/Toolbox/Toolbox.tsx
  apps/meteor/tests/e2e/message-actions.spec.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27012 Chore: Remove Unused CSS
  apps/meteor/app/livechat/client/stylesheets/livechat.css
Labels: stat: ready to merge, stat: QA skipped, Omnichannel

#26974 Chore: Tests for EE dashboards
  apps/meteor/ee/app/livechat-enterprise/server/api/business-hours.ts
  apps/meteor/server/models/raw/LivechatAgentActivity.ts
  apps/meteor/tests/data/livechat/business-hours.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/17-dashboards-ee.ts
  apps/meteor/tests/end-to-end/api/livechat/18-rooms-ee.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA skipped, Omnichannel

#26789 [NEW] Add new endpoint 'livechat/room.saveInfo' & deprecate 'livechat:saveInfo' meteor method
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/saveInfo.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit.js
  apps/meteor/tests/data/livechat/utils.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  packages/core-typings/src/IRoom.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, eng day, stat: QA tested, Omnichannel

#27076 [FIX] Livechat CurrentChats infinity re-rendering
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
Labels: stat: ready to merge, stat: QA tested

#27019 Chore: Update Image and link previews
  apps/meteor/app/ui/client/views/app/photoswipeContent.ts
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedCollapsible.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedHtmlPreview.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedImagePreview.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedLinkPreview.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedPreviewContent.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/PreviewList.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/UrlImagePreview.tsx
  apps/meteor/client/views/room/MessageList/components/UrlPreview/UrlPreview.tsx
  apps/meteor/client/views/room/MessageList/lib/isValidLink.ts
  apps/meteor/client/views/room/contexts/MessageContext.ts
  apps/meteor/client/views/room/providers/MessageProvider.tsx
  apps/meteor/tests/unit/client/views/room/MessageList/lib/buildImageURL.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isValidLink.spec.ts
  packages/fuselage-ui-kit/src/blocks/PreviewBlock.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27100 Regression: Remove margin-bottom inside UserCard actions
  apps/meteor/client/components/UserCard/UserCard.tsx
Labels: stat: ready to merge, stat: QA skipped

#27107 [FIX] CSS vars usage
  apps/meteor/app/theme/client/imports/components/message-box.css
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/theme/client/imports/general/variables.css
  apps/meteor/app/theme/server/server.js
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentDetails.tsx
  apps/meteor/client/components/message/Attachments/Files/VideoAttachment.tsx
  apps/meteor/client/components/message/Attachments/QuoteAttachment.tsx
  apps/meteor/client/components/message/Attachments/components/Load.tsx
  apps/meteor/client/components/message/Attachments/components/Retry.tsx
  apps/meteor/client/head.html
  apps/meteor/client/lib/clickableItem.js
  apps/meteor/client/sidebar/footer/SidebarFooterDefault.tsx
  apps/meteor/client/views/admin/cloud/ConnectToCloudSection.js
  apps/meteor/client/views/room/MessageList/components/MessageContentBody.tsx
  apps/meteor/ee/client/sidebar/footer/SidebarFooterWatermark.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/.eslintrc.json
  ee/packages/ui-theming/package.json
  ee/packages/ui-theming/src/PaletteStyleTag.tsx
  ee/packages/ui-theming/src/convertToCss.ts
  ee/packages/ui-theming/src/filterOnlyChangedColors.ts
  ee/packages/ui-theming/src/hasChanges.ts
  ee/packages/ui-theming/src/hooks/useLayoutVariables.ts
  ee/packages/ui-theming/src/hooks/useSetLayoutSetting.ts
  ee/packages/ui-theming/src/isHexColor.ts
  ee/packages/ui-theming/src/isLightColor.ts
  ee/packages/ui-theming/src/palette.ts
  ee/packages/ui-theming/tsconfig-build.json
  ee/packages/ui-theming/tsconfig.json
  packages/ui-client/src/components/Header/ToolBox/ToolboxDivider.tsx
  yarn.lock
Labels: stat: needs QA

#27116 Regression: Toolbox Divider Color
  packages/ui-client/src/components/Header/ToolBox/ToolboxDivider.tsx
Labels: stat: needs QA

#27110 Regression: Quote colors
  apps/meteor/client/components/message/Attachments/QuoteAttachment.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27120 Regression: Unify `isLastDocDelayed` logic
  apps/meteor/server/database/DatabaseWatcher.ts
  apps/meteor/server/startup/watchDb.ts
  ee/apps/stream-hub-service/src/service.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27095 [IMPROVE] Adapt apps management to use service
  apps/meteor/app/apps/server/communication/endpoints/actionButtonsHandler.ts
  apps/meteor/app/apps/server/communication/index.ts
  apps/meteor/app/apps/server/communication/methods.ts
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/apps/server/communication/uikit.ts
  apps/meteor/app/apps/server/communication/websockets.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/RoutingManager.js
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/server/methods/eraseRoom.js
  apps/meteor/server/sdk/index.ts
  apps/meteor/server/sdk/types/IAppsConverterService.ts
  apps/meteor/server/sdk/types/IAppsManagerService.ts
  apps/meteor/server/sdk/types/IAppsService.ts
  apps/meteor/server/sdk/types/IAppsStatisticsService.ts
  apps/meteor/server/sdk/types/IAppsVideoManagerService.ts
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/server/services/apps/communication/endpoints/actionButtonsHandler.ts
  apps/meteor/server/services/apps/converterService.ts
  apps/meteor/server/services/apps/cron.js
  apps/meteor/server/services/apps/index.ts
  apps/meteor/server/services/apps/managerService.ts
  apps/meteor/server/services/apps/orchestrator.js
  apps/meteor/server/services/apps/orchestratorFactory.ts
  apps/meteor/server/services/apps/service.ts
  apps/meteor/server/services/apps/statisticsService.ts
  apps/meteor/server/services/apps/videoManagerService.ts
  apps/meteor/server/services/startup.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#27138 [IMPROVE] Rename "Estimated due time" to "Estimated wait time"
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesRoute.js
  apps/meteor/ee/client/omnichannel/priorities/PriorityEdit.js
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: needs QA

#27123 [FIX] Microphone icon alignment issue (# 27073)
  apps/meteor/app/theme/client/imports/components/message-box.css
  apps/meteor/client/templates.ts
Labels: hacktoberfest

#27157 Chore: bump fuselage packages
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/presence-service/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/ui-theming/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: needs QA
