Repository RocketChat/Rocket.Chat, pull requests merged in 2022-09, with the labels that each got.

#26770 Chore: Fix docker latest tag push
  .github/workflows/build_and_test.yml
Labels: stat: needs QA

#26769 Chore: Bump fuselage packages
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: needs QA

#26765 Chore: Update Apps-Engine
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26756 Regression: Visitor being overwritten on call end
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#26729 [IMPROVE] Remove device-management banner and modal
  apps/meteor/client/startup/banners.ts
  apps/meteor/ee/client/deviceManagement/components/featureModal/DeviceManagementFeatureModal.tsx
  apps/meteor/ee/client/deviceManagement/components/featureModal/FeatureModalBullets.tsx
  apps/meteor/ee/client/deviceManagement/components/featureModal/index.ts
  apps/meteor/ee/server/lib/deviceManagement/startup.ts
  apps/meteor/ee/server/startup/deviceManagement.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v281.ts
Labels: stat: ready to merge, stat: QA tested

#26779 Regression: Instances Modal breaking
  apps/meteor/client/views/admin/info/InformationRoute.tsx
  yarn.lock
Labels: stat: needs QA

#26732 i18n: pt-BR translation typo
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: stat: needs QA

#26792 Merge master into develop & Set version to 5.2.0-develop
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
Labels: stat: needs QA

#26730 Chore: Add E2E tests to missing omnichannel endpoints
  apps/meteor/app/livechat/server/api/v1/agent.js
  apps/meteor/app/livechat/server/api/v1/customField.js
  apps/meteor/app/livechat/server/api/v1/room.js
  apps/meteor/app/livechat/server/api/v1/transcript.js
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
Labels: stat: ready to merge, stat: QA skipped

#26768 [FIX] Typo on new homepage
  apps/meteor/client/views/home/cards/DesktopAppsCard.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#26776 [FIX] Livechat trigger messages covering all the website
  packages/livechat/src/widget.js
Labels: stat: ready to merge, stat: QA tested

#26808 [FIX] Restore current chats default table order
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
Labels: stat: ready to merge, stat: QA tested

#26819 [FIX] Fix broken legacy message view
  apps/meteor/app/ui/client/views/app/lib/roomHelpers.ts
Labels: stat: ready to merge, stat: QA tested

#26775 [FIX] Menu options margin spacing
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-client/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#26130 [IMPROVE] System messages' consistency
  apps/meteor/app/channel-settings/server/functions/saveRoomType.js
  apps/meteor/app/lib/lib/MessageTypes.ts
  apps/meteor/app/livechat/lib/messageTypes.ts
  apps/meteor/app/user-data-download/server/cronProcessDownloads.js
  apps/meteor/client/startup/messageTypes.ts
  apps/meteor/client/views/room/MessageList/lib/isOwnUserMessage.spec.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#24297 [IMPROVE] OTR Message
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/otr/lib/IOTR.ts
  apps/meteor/app/otr/server/index.ts
  apps/meteor/app/otr/server/methods/updateOTRAck.ts
  apps/meteor/app/ui-utils/client/lib/RoomManager.ts
  apps/meteor/client/startup/otr.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: ready to merge, stat: QA tested

#26673 [IMPROVE] Allow delete attachment description on message edit
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/methods/updateMessage.js
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/client/methods/updateMessage.ts
Labels: stat: ready to merge, stat: QA tested

#26822 Release 5.1.1
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/ui/client/views/app/lib/roomHelpers.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/package.json
  package.json
  packages/livechat/src/widget.js
Labels: stat: ready to merge, stat: QA skipped

#26827 [FIX] Sign in with Apple on mobile
  apps/meteor/app/apple/lib/handleIdentityToken.ts
  apps/meteor/app/apple/server/AppleCustomOAuth.ts
  apps/meteor/app/apple/server/appleOauthRegisterService.ts
  apps/meteor/app/apple/server/index.ts
  apps/meteor/app/apple/server/loginHandler.ts
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#26826 Chore: add aria hidden if modal is open
  apps/meteor/client/views/modal/ModalRegion.tsx
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26749 Chore: Cleanup endpoint handlers
  apps/meteor/app/api/server/lib/emailInbox.ts
  apps/meteor/app/api/server/v1/email-inbox.ts
  apps/meteor/app/api/server/v1/voip/events.ts
  apps/meteor/app/api/server/v1/voip/omnichannel.ts
  apps/meteor/app/api/server/v1/voip/queues.ts
  apps/meteor/app/livechat/imports/server/rest/agent.js
  apps/meteor/app/livechat/imports/server/rest/dashboards.js
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/imports/server/rest/inquiries.js
  apps/meteor/app/livechat/imports/server/rest/users.js
  apps/meteor/app/livechat/server/api/v1/agent.js
  apps/meteor/app/livechat/server/api/v1/message.js
  apps/meteor/app/livechat/server/api/v1/offlineMessage.js
  apps/meteor/app/livechat/server/api/v1/pageVisited.js
  apps/meteor/app/livechat/server/api/v1/room.js
  apps/meteor/app/livechat/server/api/v1/videoCall.js
  apps/meteor/app/livechat/server/methods/transfer.js
  apps/meteor/ee/app/api-enterprise/server/canned-responses.js
  apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
  apps/meteor/ee/app/livechat-enterprise/server/api/agents.js
  apps/meteor/ee/app/livechat-enterprise/server/api/departments.js
  apps/meteor/ee/app/livechat-enterprise/server/api/inquiries.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/inquiries.js
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/monitors.js
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/priorities.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/monitors.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/priorities.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/rooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/units.ts
  apps/meteor/tests/data/livechat/inboxes.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/11-email-inbox.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
Labels: stat: ready to merge, stat: QA skipped

#26714 Chore: first non-aggressive CSS removal
  apps/meteor/app/discussion/client/views/DiscussionTabbar.html
  apps/meteor/app/livechat/client/stylesheets/livechat.css
  apps/meteor/app/theme/client/imports/components/badge.css
  apps/meteor/app/theme/client/imports/components/chip.css
  apps/meteor/app/theme/client/imports/components/contextual-bar.css
  apps/meteor/app/theme/client/imports/components/modal/create-channel.css
  apps/meteor/app/theme/client/imports/forms/select-avatar.css
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/forms.css
  apps/meteor/app/theme/client/imports/general/rtl.css
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/theme/client/main.css
  apps/meteor/app/ui/client/components/tabs.html
  apps/meteor/app/ui/client/components/tabs.js
  apps/meteor/app/ui/client/index.ts
Labels: stat: ready to merge, stat: QA skipped

#26514 [NEW] Sections layout and featured apps for marketplace
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/client/components/Page/Page.tsx
  apps/meteor/client/views/admin/apps/AppDetails.tsx
  apps/meteor/client/views/admin/apps/AppDetailsPage.tsx
  apps/meteor/client/views/admin/apps/AppStatus.js
  apps/meteor/client/views/admin/apps/AppsList.tsx
  apps/meteor/client/views/admin/apps/AppsListMain.tsx
  apps/meteor/client/views/admin/apps/AppsPage.tsx
  apps/meteor/client/views/admin/apps/AppsPageContent.tsx
  apps/meteor/client/views/admin/apps/AppsPageContentSkeleton.tsx
  apps/meteor/client/views/admin/apps/BundleChips.tsx
  apps/meteor/client/views/admin/apps/ConnectionErrorEmptyState.tsx
  apps/meteor/client/views/admin/apps/FeaturedAppsSections.tsx
  apps/meteor/client/views/admin/apps/NoInstalledAppMatchesEmptyState.tsx
  apps/meteor/client/views/admin/apps/NoInstalledAppsFoundEmptyState.tsx
  apps/meteor/client/views/admin/apps/NoMarketplaceOrInstalledAppMatchesEmptyState.tsx
  apps/meteor/client/views/admin/apps/components/RadioButtonList.tsx
  apps/meteor/client/views/admin/apps/components/RadioDropDown/RadioDropDown.tsx
  apps/meteor/client/views/admin/apps/helpers/normalizeFeaturedApps.ts
  apps/meteor/client/views/admin/apps/hooks/useFeaturedApps.ts
  apps/meteor/client/views/admin/settings/SettingsPage.tsx
  apps/meteor/client/views/home/DefaultHomePage.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardPage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/AppOverview.ts
  packages/core-typings/src/Apps.ts
  packages/core-typings/src/FeaturedApps.ts
  packages/core-typings/src/index.ts
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, stat: QA skipped, feat: marketplace

#26839 Chore: Deprecate some omnichannel meteor methods which aren't getting used
  apps/meteor/app/livechat/server/methods/addAgent.js
  apps/meteor/app/livechat/server/methods/addManager.js
  apps/meteor/app/livechat/server/methods/closeByVisitor.js
  apps/meteor/app/livechat/server/methods/getCustomFields.js
  apps/meteor/app/livechat/server/methods/getDepartmentForwardRestrictions.js
  apps/meteor/app/livechat/server/methods/getFirstRoomMessage.js
  apps/meteor/app/livechat/server/methods/getNextAgent.js
  apps/meteor/app/livechat/server/methods/getTagsList.js
  apps/meteor/app/livechat/server/methods/loadHistory.js
  apps/meteor/app/livechat/server/methods/loginByToken.js
  apps/meteor/app/livechat/server/methods/pageVisited.js
  apps/meteor/app/livechat/server/methods/registerGuest.js
  apps/meteor/app/livechat/server/methods/removeAgent.js
  apps/meteor/app/livechat/server/methods/removeDepartment.js
  apps/meteor/app/livechat/server/methods/removeManager.js
  apps/meteor/app/livechat/server/methods/saveDepartmentAgents.js
  apps/meteor/app/livechat/server/methods/saveSurveyFeedback.js
  apps/meteor/app/livechat/server/methods/searchAgent.js
  apps/meteor/app/livechat/server/methods/sendOfflineMessage.js
  apps/meteor/app/livechat/server/methods/setCustomField.js
  apps/meteor/app/livechat/server/methods/setDepartmentForVisitor.js
Labels: stat: ready to merge, stat: QA skipped

#26824 [IMPROVE] Include `syncAvatars` on `ldap.syncNow`
  apps/meteor/ee/server/api/ldap.ts
Labels: stat: ready to merge, stat: QA tested

#26652 [FIX] Check if messsage.replies exist on new message template
  apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
  apps/meteor/tests/unit/client/views/room/MessageList/MessageContent.spec.tsx
Labels: stat: ready to merge, stat: QA tested

#26793 Chore: Add RocketChatDesktop function to open video calls when using Electron
  apps/meteor/client/providers/VideoConfProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#26845 Chore: Rewrite apps WarningModal component to typescript
  apps/meteor/client/views/admin/apps/WarningModal.tsx
Labels: stat: ready to merge, eng day, stat: QA skipped

#26806 [NEW] Composer variations
  packages/ui-composer/src/MessageComposer/MessageComposer.stories.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerDisabled.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerDisabledAction.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerDisplay.tsx
  packages/ui-composer/src/MessageComposer/index.ts
Labels: stat: ready to merge, eng day, stat: QA skipped

#26836 [FIX] Importer fails when file includes user without an email.
  packages/rest-typings/src/v1/import/StartImportParamsPOST.ts
Labels: stat: ready to merge, stat: QA skipped

#26841 Chore: Update fuselage to next version.
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26873 Chore: fix wrong `test.step` usage
  apps/meteor/tests/e2e/omnichannel-currentChats.spec.ts
Labels: stat: needs QA

#26709 Chore: Upgrading livechat's ui-kit package to latest version
  packages/livechat/package.json
  packages/livechat/src/components/uiKit/message/ActionsBlock/index.js
  packages/livechat/src/components/uiKit/message/ButtonElement/index.js
  packages/livechat/src/components/uiKit/message/ButtonElement/stories.js
  packages/livechat/src/components/uiKit/message/ContextBlock/index.js
  packages/livechat/src/components/uiKit/message/ImageElement/index.js
  packages/livechat/src/components/uiKit/message/SectionBlock/index.js
  packages/livechat/src/components/uiKit/message/index.js
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26852 [FIX] Expanded thread behind sidebar on small screens
  apps/meteor/client/views/room/threads/ThreadView.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26876 Chore: Bump fuselage dependencies and implement new tabs variant in marketplace
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26669 [FIX] Unable to send native video recording to Whatsapp
  apps/meteor/app/ui-message/client/messageBox/messageBoxActions.ts
  apps/meteor/app/ui-vrecord/client/VRecDialog.js
  apps/meteor/app/ui-vrecord/client/vrecord.js
  apps/meteor/app/ui/client/lib/recorderjs/videoRecorder.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: feat: omnichannel, stat: ready to merge, stat: QA tested

#26755 [FIX] Asset settings description not showing on admin
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/client/views/admin/settings/Setting.tsx
  apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/page-objects/admin.ts
  apps/meteor/tests/e2e/settings-assets.spec.ts
Labels: stat: ready to merge, stat: QA tested

#26863 [IMPROVE] Changed dial pad appearance to match original design
  apps/meteor/ee/client/voip/modal/DialPad/DialPadModal.tsx
  apps/meteor/ee/client/voip/modal/DialPad/Pad.tsx
  apps/meteor/ee/client/voip/modal/DialPad/PadButton.tsx
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useDialPad.tsx
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26601 [FIX] Check admin setting for whether to display roles or not
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#26860 Chore: Fix API tests retry
  .github/workflows/build_and_test.yml
Labels: stat: ready to merge, stat: QA skipped

#26686 Chore: Change BundleChips component appearance
  apps/meteor/client/views/admin/apps/AppRow.tsx
  apps/meteor/client/views/admin/apps/AppsPage.tsx
  apps/meteor/client/views/admin/apps/BundleChips.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#26711 [FIX] Upload fails when using WebDav as file storage
  apps/meteor/app/file-upload/ufs/Webdav/server.js
  apps/meteor/app/webdav/server/lib/webdavClientAdapter.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26674 [NEW] Get moderators, owners and leaders from room scope via apps-engine
  apps/meteor/app/apps/server/bridges/rooms.ts
Labels: stat: ready to merge, stat: QA tested

#26831 [IMPROVE] Setting for login email notifications
  apps/meteor/client/views/account/preferences/PreferencesNotificationsSection.tsx
  apps/meteor/client/views/account/tokens/AccountTokensTable/AccountTokensTable.tsx
  apps/meteor/ee/client/deviceManagement/components/DeviceManagementTable/DeviceManagementTable.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfoWithData.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardCardErrorBoundary.tsx
  apps/meteor/ee/server/lib/deviceManagement/session.ts
  apps/meteor/ee/server/settings/deviceManagement.ts
  apps/meteor/ee/server/startup/deviceManagement.ts
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  packages/rest-typings/src/v1/users/UsersSetPreferenceParamsPOST.ts
  packages/ui-contexts/src/ServerContext/methods/saveUserPreferences.ts
Labels: stat: ready to merge, stat: QA tested

#26917 [FIX] Error when mentioning a non-member of a public channel
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
Labels: stat: ready to merge, stat: QA skipped

#26843 [FIX] [Livechat] Unread messages badge
  apps/meteor/tests/e2e/omnichannel-close-chat.spec.ts
  apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/index.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-close-chat-modal.ts
  apps/meteor/tests/e2e/page-objects/home-omnichannel.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  packages/livechat/src/components/Button/index.js
  packages/livechat/src/i18n/en.json
  packages/livechat/src/lib/room.js
  packages/livechat/src/routes/Chat/container.js
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26921 [FIX] MIME Type fallback for .mov File Extensions
  apps/meteor/client/components/message/Attachments/Files/VideoAttachment.tsx
  apps/meteor/client/lib/utils/userAgentMIMETypeFallback.ts
  apps/meteor/client/views/room/modals/FileUploadModal/MediaPreview.tsx
Labels: stat: ready to merge, stat: QA skipped

#26751 [NEW] Add Markup to QuoteAttachment
  apps/meteor/app/theme/client/imports/components/messages.css
  apps/meteor/client/components/message/Attachments/Attachment/AttachmentDetails.tsx
  apps/meteor/client/components/message/Attachments/Attachments.stories.tsx
  apps/meteor/client/components/message/Attachments/Attachments.tsx
  apps/meteor/client/components/message/Attachments/Item.tsx
  apps/meteor/client/components/message/Attachments/QuoteAttachment.tsx
  apps/meteor/client/lib/utils/mapMessageFromApi.ts
  apps/meteor/client/views/room/MessageList/components/Message.tsx
  apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
  apps/meteor/client/views/room/MessageList/components/MessageContentBody.tsx
  apps/meteor/client/views/room/MessageList/components/ThreadMessagePreviewBody.tsx
  apps/meteor/client/views/room/MessageList/hooks/useMessages.ts
  apps/meteor/client/views/room/MessageList/hooks/useParsedMessage.spec.tsx
  apps/meteor/client/views/room/MessageList/hooks/useParsedMessage.ts
  apps/meteor/client/views/room/MessageList/lib/isParsedMessage.ts
  apps/meteor/client/views/room/MessageList/lib/parseMessageTextToAstMarkdown.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/unit/client/views/room/MessageList/MessageContent.spec.tsx
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isMessageFirstUnread.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isMessageNewDay.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isMessageSequential.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isOwnUserMessage.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isParsedMessage.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/parseMessage.spec.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentAction.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentBase.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentDefault.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageQuoteAttachment.ts
  packages/gazzodown/src/elements/PreviewInlineElements.tsx
Labels: stat: ready to merge, stat: QA tested

#26829 Chore: Omnichannel endpoints to ts
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/livechat/imports/server/rest/agent.ts
  apps/meteor/app/livechat/imports/server/rest/appearance.ts
  apps/meteor/app/livechat/imports/server/rest/businessHours.ts
  apps/meteor/app/livechat/imports/server/rest/dashboards.ts
  apps/meteor/app/livechat/imports/server/rest/facebook.js
  apps/meteor/app/livechat/imports/server/rest/facebook.ts
  apps/meteor/app/livechat/imports/server/rest/inquiries.ts
  apps/meteor/app/livechat/imports/server/rest/integrations.ts
  apps/meteor/app/livechat/imports/server/rest/queue.ts
  apps/meteor/app/livechat/imports/server/rest/rooms.ts
  apps/meteor/app/livechat/imports/server/rest/triggers.ts
  apps/meteor/app/livechat/imports/server/rest/upload.ts
  apps/meteor/app/livechat/imports/server/rest/users.ts
  apps/meteor/app/livechat/imports/server/rest/visitors.js
  apps/meteor/app/livechat/imports/server/rest/visitors.ts
  apps/meteor/app/livechat/server/api.js
  apps/meteor/app/livechat/server/api.ts
  apps/meteor/app/livechat/server/api/rest.js
  apps/meteor/app/livechat/server/api/rest.ts
  apps/meteor/app/livechat/server/api/v1/agent.js
  apps/meteor/app/livechat/server/api/v1/agent.ts
  apps/meteor/app/livechat/server/api/v1/config.js
  apps/meteor/app/livechat/server/api/v1/config.ts
  apps/meteor/app/livechat/server/api/v1/customField.js
  apps/meteor/app/livechat/server/api/v1/customField.ts
  apps/meteor/app/livechat/server/api/v1/message.js
  apps/meteor/app/livechat/server/api/v1/message.ts
  apps/meteor/app/livechat/server/api/v1/offlineMessage.js
  apps/meteor/app/livechat/server/api/v1/offlineMessage.ts
  apps/meteor/app/livechat/server/api/v1/pageVisited.js
  apps/meteor/app/livechat/server/api/v1/pageVisited.ts
  apps/meteor/app/livechat/server/api/v1/room.js
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/api/v1/transcript.js
  apps/meteor/app/livechat/server/api/v1/transcript.ts
  apps/meteor/app/livechat/server/api/v1/transfer.ts
  apps/meteor/app/livechat/server/api/v1/videoCall.ts
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/client/views/omnichannel/currentChats/CustomFieldsVerticalBar.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/ComposerOmnichannelInquiry.tsx
  apps/meteor/ee/app/api-enterprise/server/canned-responses.ts
  apps/meteor/ee/app/api-enterprise/server/index.ts
  apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
  apps/meteor/ee/app/livechat-enterprise/server/api/agents.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/departments.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/inquiries.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/monitors.ts
  apps/meteor/ee/server/models/raw/CannedResponse.ts
  apps/meteor/package.json
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
  packages/model-typings/src/models/ICannedResponseModel.ts
  packages/rest-typings/src/helpers/Deprecated.ts
  packages/rest-typings/src/v1/omnichannel.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26548 [IMPROVE] VideoConference Messages UI
  apps/meteor/client/views/blocks/MessageBlock.js
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/VideoConference.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/sdk/lib/Events.ts
  apps/meteor/server/services/video-conference/service.ts
  ee/apps/ddp-streamer/package.json
  packages/agenda/package.json
  packages/api-client/package.json
  packages/cas-validate/package.json
  packages/core-typings/package.json
  packages/core-typings/src/IVideoConference.ts
  packages/eslint-config/package.json
  packages/favicon/package.json
  packages/fuselage-ui-kit/package.json
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/hooks/useVideoConfData.ts
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/hooks/useVideoConfDataStream.ts
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/index.tsx
  packages/fuselage-ui-kit/src/contexts/kitContext.ts
  packages/fuselage-ui-kit/src/surfaces/FuselageSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/MessageSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/index.ts
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/livechat/src/components/Messages/MessageList/index.js
  packages/livechat/src/lib/room.js
  packages/model-typings/package.json
  packages/model-typings/src/models/IVideoConferenceModel.ts
  packages/models/package.json
  packages/node-poplib/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/.eslintrc.json
  packages/ui-video-conf/.storybook/main.js
  packages/ui-video-conf/.storybook/preview.js
  packages/ui-video-conf/package.json
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.stories.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageAction.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageFooter.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageFooterText.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageIcon.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageRow.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageSkeleton.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageText.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageUserStack.tsx
  packages/ui-video-conf/src/VideoConfMessage/index.ts
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.tsx
  packages/ui-video-conf/src/index.ts
  yarn.lock
Labels: feat: video conferencing, stat: ready to merge, stat: QA tested

#26812 [FIX] Ephemeral messages not respecting katex setting
  apps/meteor/server/modules/listeners/listeners.module.ts
Labels: stat: ready to merge, stat: QA skipped

#26900 [FIX] Message sequential after message thread preview
  apps/meteor/client/views/room/MessageList/lib/isMessageSequential.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isMessageNewDay.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/isMessageSequential.spec.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26912 Chore: fix regressions for omnichannel due room refactor
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.js
  apps/meteor/app/ui-message/client/messageBox/messageBox.ts
  apps/meteor/client/components/voip/composer/NotAvailableOnCall/NotAvailable.stories.tsx
  apps/meteor/client/components/voip/composer/NotAvailableOnCall/NotAvailableContent.tsx
  apps/meteor/client/components/voip/composer/NotAvailableOnCall/NotAvailableContentWrapper.tsx
  apps/meteor/client/components/voip/composer/NotAvailableOnCall/NotAvailableOnCall.tsx
  apps/meteor/client/components/voip/composer/NotAvailableOnCall/index.ts
  apps/meteor/client/lib/rooms/roomCoordinator.ts
  apps/meteor/client/views/room/MessageList/components/Toolbox/Toolbox.tsx
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerContainer.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerVoIP.tsx
  apps/meteor/client/views/room/providers/ToolboxProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#26929 Chore: Refactor omnichannel livechat tests
  apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
Labels: stat: needs QA

#26928 Regression: wrong permission on livechat/tags endpoints
  apps/meteor/ee/app/livechat-enterprise/server/api/tags.ts
  apps/meteor/tests/data/livechat/priorities.ts
  apps/meteor/tests/data/livechat/tags.ts
  apps/meteor/tests/data/livechat/triggers.ts
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
  apps/meteor/tests/end-to-end/api/livechat/08-triggers.ts
  apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
  apps/meteor/tests/end-to-end/api/livechat/13-tags.ts
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26931 Chore: Convert current-chats to useQuery
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/client/views/omnichannel/currentChats/RemoveChatButton.tsx
  apps/meteor/client/views/omnichannel/currentChats/hooks/useAllCustomFields.tsx
  apps/meteor/client/views/omnichannel/currentChats/hooks/useCurrentChats.ts
  apps/meteor/client/views/omnichannel/currentChats/hooks/useRemoveCurrentChatMutation.ts
  apps/meteor/definition/methods/omnichannel.ts
Labels: stat: ready to merge, stat: QA skipped

#26924 Chore: Updating apps engine
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26930 Regression: Fix open room from current chats
  apps/meteor/app/ui-utils/client/lib/openRoom.tsx
  apps/meteor/client/lib/createReactiveSubscriptionFactory.ts
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/currentChats/hooks/useCurrentChats.ts
  apps/meteor/client/views/room/providers/ToolboxProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useToolboxActions.ts
Labels: stat: needs QA

#26880 [FIX] `MongoInvalidArgumentError` on overwriting existing setting
  apps/meteor/app/settings/server/SettingsRegistry.ts
  apps/meteor/app/settings/server/functions/settings.mocks.ts
  apps/meteor/tests/unit/app/settings/server/functions/settings.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#26867 [NEW] Move administration links to an exclusive kebab menu
  apps/meteor/app/livechat/client/ui.js
  apps/meteor/app/ui-utils/client/lib/AccountBox.ts
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.tsx
  apps/meteor/client/components/AdministrationList/SettingsModelList.tsx
  apps/meteor/client/components/Sidebar/ListItem.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/client/sidebar/header/index.tsx
  apps/meteor/client/views/admin/sidebar/UpgradeTab.tsx
  apps/meteor/client/views/admin/upgrade/UpgradePage/UpgradePage.tsx
  apps/meteor/client/views/hooks/useUpgradeTabParams.ts
  apps/meteor/ee/app/auditing/client/index.js
  apps/meteor/lib/getUpgradeTabType.ts
  apps/meteor/lib/upgradeTab.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/administration-menu.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/unit/client/components/AdministrationList/AdministrationList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AdministrationModelList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AppsModelList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AuditModelList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/SettingsModelList.spec.tsx
  apps/meteor/tests/unit/client/siderbar/header/actions/Administration.spec.tsx
  apps/meteor/tests/unit/lib/upgradeTab.spec.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#26940 Chore: Bump vm2 to 3.9.11
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26914 Release 5.1.3
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
  apps/meteor/app/settings/server/SettingsRegistry.ts
  apps/meteor/app/settings/server/functions/settings.mocks.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
  apps/meteor/package.json
  apps/meteor/tests/unit/app/settings/server/functions/settings.tests.ts
  apps/meteor/tests/unit/client/views/room/MessageList/MessageContent.spec.tsx
  package.json
  packages/rest-typings/src/v1/import/StartImportParamsPOST.ts
Labels: stat: needs QA

#26939 Chore: Tests for EE features
  apps/meteor/app/api/server/helpers/requestParams.ts
  apps/meteor/tests/data/livechat/canned-responses.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/livechat/units.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  apps/meteor/tests/end-to-end/api/livechat/15-canned-responses.ts
  apps/meteor/tests/end-to-end/api/livechat/16-video-call.ts
Labels: stat: ready to merge, stat: QA skipped

#26950 Regression: Sidebar Room List not working properly.
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.js
Labels: stat: ready to merge, stat: QA skipped

#26909 [FIX] Adjusted livechat fallbacks to take null values into account
  packages/livechat/src/components/App/App.js
  packages/livechat/src/lib/hooks.js
  packages/livechat/src/lib/room.js
  packages/livechat/src/lib/triggers.js
  packages/livechat/src/routes/Chat/container.js
  packages/livechat/src/routes/Register/component.js
Labels: stat: ready to merge, stat: QA tested, Omnichannel

#26965 Release 5.1.4
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
  packages/livechat/src/components/App/App.js
  packages/livechat/src/lib/hooks.js
  packages/livechat/src/lib/room.js
  packages/livechat/src/lib/triggers.js
  packages/livechat/src/routes/Chat/container.js
  packages/livechat/src/routes/Register/component.js
Labels: stat: ready to merge, stat: QA skipped

#26958 [FIX] Admin sidebar navigation
  apps/meteor/client/components/Sidebar/SidebarNavigationItem.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#26961 Revert: "[IMPROVE] VideoConference Messages UI (#26548)"
  apps/meteor/client/views/blocks/MessageBlock.js
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/VideoConference.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/sdk/lib/Events.ts
  apps/meteor/server/services/video-conference/service.ts
  ee/apps/ddp-streamer/package.json
  packages/agenda/package.json
  packages/api-client/package.json
  packages/cas-validate/package.json
  packages/core-typings/package.json
  packages/core-typings/src/IVideoConference.ts
  packages/eslint-config/package.json
  packages/favicon/package.json
  packages/fuselage-ui-kit/package.json
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/hooks/useVideoConfData.ts
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/hooks/useVideoConfDataStream.ts
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/index.tsx
  packages/fuselage-ui-kit/src/contexts/kitContext.ts
  packages/fuselage-ui-kit/src/surfaces/FuselageSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/MessageSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/index.ts
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/livechat/src/components/Messages/MessageList/index.js
  packages/livechat/src/lib/room.js
  packages/model-typings/package.json
  packages/model-typings/src/models/IVideoConferenceModel.ts
  packages/models/package.json
  packages/node-poplib/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/.eslintrc.json
  packages/ui-video-conf/.storybook/main.js
  packages/ui-video-conf/.storybook/preview.js
  packages/ui-video-conf/package.json
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.stories.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageAction.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageFooter.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageFooterText.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageIcon.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageRow.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageSkeleton.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageText.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageUserStack.tsx
  packages/ui-video-conf/src/VideoConfMessage/index.ts
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.tsx
  packages/ui-video-conf/src/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26962 Regression: Typo on livechat/queue endpoint client call
  apps/meteor/client/views/omnichannel/queueList/hooks/useQuery.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, Omnichannel

#26969 Regression: Remove symbols from number before storing PBX event
  apps/meteor/server/services/omnichannel-voip/service.ts
  apps/meteor/server/services/voip/connector/asterisk/ami/ContinuousMonitor.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, Omnichannel

#26964 Regression: Event handler blocking mention links
  apps/meteor/app/ui/client/views/app/lib/getCommonRoomEvents.ts
  apps/meteor/client/components/message/Metrics/Discussion.tsx
  apps/meteor/client/views/room/MessageList/components/MessageContentBody.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/contexts/MessageContext.ts
Labels: type: regression, stat: ready to merge, stat: QA tested

#26935 Regression: Incorrect on-hold chat resume message
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/ComposerOmnichannelOnHold.tsx
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, Omnichannel

#26687 [IMPROVE] Results of user auto complete
  apps/meteor/app/api/server/lib/users.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/server/lib/spotlight.js
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/tests/end-to-end/api/01-users.js
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab
