Repository RocketChat/Rocket.Chat, pull requests merged in 2023-03, with the labels that each got.

#28183 Regression: Save button is not enable while trying to save contact manager
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested, feat: omnichannel

#28078 Regression: Fixed room edit custom field validation
  apps/meteor/client/components/CustomFieldsFormV2.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
  apps/meteor/client/views/omnichannel/directory/utils/formatCustomFieldsMetadata.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested, feat: omnichannel

#28145 Regression: New messages not reflected in the chat window for queued chats.
  apps/meteor/app/livechat/server/hooks/saveLastMessageToInquiry.ts
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested, feat: omnichannel

#28199 Regression: Fix private apps already in marketplace not shown properly on app details page
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppInstallPage.js
  apps/meteor/client/views/marketplace/hooks/useAppInfo.ts
  apps/meteor/client/views/marketplace/sidebarItems.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: marketplace

#28209 Regression: Visitor abandonment job not working properly
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: omnichannel

#28210 Regression: Denied Camera permission do not disable VideoMessageAction
  apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/AudioMessageAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/hooks/useMediaActionTitle.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/hooks/useMediaPermissions.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28212 [FIX] File upload modal not opening after too long message modal
  apps/meteor/client/lib/chats/flows/processTooLongMessage.ts
Labels: type: regression, stat: ready to merge, stat: QA tested

#28214 Chore: Add dark theme assets
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/client/sidebar/footer/SidebarFooterDefault.tsx
  apps/meteor/client/views/oauth/components/Layout.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/images/logo/logo_dark.png
  apps/meteor/public/images/logo/logo_dark.svg
  apps/meteor/tests/e2e/settings-assets.spec.ts
  packages/core-typings/src/IRocketChatAssets.ts
  packages/ui-contexts/src/hooks/useAssetPath.ts
  packages/ui-contexts/src/hooks/useAssetWithDarkModePath.ts
  packages/ui-contexts/src/index.ts
  packages/web-ui-registration/src/CMSPage.tsx
  packages/web-ui-registration/src/template/HorizontalTemplate.tsx
  packages/web-ui-registration/src/template/VerticalTemplate.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28201 Regression: Tooltip for More options dont disappear after click.
  apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx
  apps/meteor/client/providers/TooltipProvider.tsx
  apps/meteor/client/views/meet/CallPage.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
Labels: type: bug, type: regression, stat: ready to merge, stat: QA tested

#28225 Regression: SendFileLivechatMessage using deprecated prop affecting PDF transcript
  apps/meteor/app/livechat/server/methods/sendFileLivechatMessage.js
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: omnichannel

#28200 Regression: Show mention instead of the name of the user in app request messages
  apps/meteor/ee/server/apps/communication/rest.js
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: marketplace

#28143 [FIX] User registration with EmailConfirmation not working
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/web-ui-registration/src/EmailConfirmationForm.tsx
  packages/web-ui-registration/src/LoginForm.tsx
  packages/web-ui-registration/src/RegisterForm.tsx
  packages/web-ui-registration/src/RegisterFormDisabled.tsx
  packages/web-ui-registration/src/RegistrationPageRouter.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested

#28139 Regression: Add auto translate option back to live chat room
  apps/meteor/app/autotranslate/client/lib/actionButton.ts
  apps/meteor/client/components/message/variants/room/RoomMessageContent.spec.tsx
  apps/meteor/client/lib/parseMessageTextToAstMarkdown.ts
  apps/meteor/client/views/room/MessageList/hooks/useAutoTranslate.spec.ts
  apps/meteor/client/views/room/MessageList/hooks/useAutoTranslate.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, feat: omnichannel

#28235 Regression: Fixed triggers edit form not being properly updated
  apps/meteor/client/views/omnichannel/triggers/TriggersPage.js
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: omnichannel

#28110 Chore: More E2E tests for PDF transcript feature of Omnichannel
  apps/meteor/app/models/server/models/LivechatRooms.js
  apps/meteor/ee/app/license/server/getStatistics.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/17-dashboards-ee.ts
  apps/meteor/tests/end-to-end/api/livechat/18-rooms-ee.ts
  packages/core-typings/src/IRoom.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: omnichannel

#28236 Regression: EmojiPicker missing shadow on dark mode
  apps/meteor/app/theme/client/imports/components/emojiPicker.css
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28228 Regression: Update Composer Formatters Translation Keys
  apps/meteor/app/ui-message/client/messageBox/messageBoxFormatting.ts
  apps/meteor/ee/client/omnichannel/components/CannedResponse/MarkdownTextEditor/index.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28221 Regression: EnableUnlimitedApps button action
  apps/meteor/client/views/marketplace/AppInstallPage.js
  apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
  apps/meteor/client/views/marketplace/components/AppInstallModal/AppInstallModal.tsx
  apps/meteor/client/views/marketplace/hooks/useAppInstallationHandler.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: marketplace

#28180 Regression: broken message exhibition when edited
  apps/meteor/.eslintcache
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
  apps/meteor/ee/app/message-read-receipt/server/hooks/afterSaveMessage.ts
  apps/meteor/tests/mocks/data.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/application/sender/RoomServiceSender.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/rocket-chat/hooks/hooks.spec.ts
  packages/core-typings/src/IMessage/IMessage.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28230 [FIX] Search list missing key parameter
  apps/meteor/client/sidebar/search/SearchList.tsx
Labels: type: regression, stat: needs QA, feat: team-collab

#28213 Regression: UiKit message surface styles
  apps/meteor/client/components/GazzodownText.tsx
  apps/meteor/client/components/message/MessageContentBody.tsx
  apps/meteor/client/components/message/content/uikit/ParsedText.tsx
  apps/meteor/client/lib/utils/detectEmoji.ts
  apps/meteor/client/providers/RouterProvider.tsx
  apps/meteor/tests/mocks/client/RouterContextMock.tsx
  packages/ui-contexts/src/RouterContext.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28198 Regression: Fix app status filter not working in private apps page
  apps/meteor/client/views/marketplace/helpers/filterAppsByDisabled.ts
  apps/meteor/client/views/marketplace/helpers/filterAppsByEnabled.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: marketplace

#28234 [BREAK] Remove support to deprecated typing event
  apps/meteor/server/modules/notifications/notifications.module.ts
Labels: type: regression, stat: QA skipped

#28188 Regression: Hide price and category filters when inside of private apps page
  apps/meteor/client/views/marketplace/AppsPage/AppsFilters.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDown.stories.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDown.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDownAnchor.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDownList.tsx
  apps/meteor/client/views/marketplace/definitions/CategoryDropdownDefinitions.ts
  apps/meteor/client/views/marketplace/hooks/useCategories.ts
  apps/meteor/client/views/marketplace/hooks/useCategoryFlatList.ts
  apps/meteor/client/views/marketplace/hooks/useCategoryToggle.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: marketplace

#28163 Regression: Jump to message not working
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/app/ui-utils/client/lib/openRoom.tsx
  apps/meteor/client/components/message/list/MessageListContext.tsx
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/lib/utils/legacyJumpToMessage.ts
  apps/meteor/client/lib/utils/setMessageJumpQueryStringParameter.ts
  apps/meteor/client/providers/RouterProvider.tsx
  apps/meteor/client/startup/actionButtons/jumpToMessage.ts
  apps/meteor/client/startup/actionButtons/jumpToPinMessage.ts
  apps/meteor/client/startup/actionButtons/jumpToSearchMessage.ts
  apps/meteor/client/startup/actionButtons/jumpToStarMessage.ts
  apps/meteor/client/views/room/MessageList/MessageList.tsx
  apps/meteor/client/views/room/MessageList/hooks/useJumpToMessage.ts
  apps/meteor/client/views/room/MessageList/hooks/useLoadSurroundingMessages.ts
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useGoToThread.ts
  apps/meteor/client/views/room/hooks/useScrollMessageList.ts
  apps/meteor/tests/mocks/client/RouterContextMock.tsx
  packages/ui-contexts/src/RouterContext.ts
Labels: type: regression, stat: needs QA

#27962 Regression: run clientMessageRecieved hooks on thread main message
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessages.ts
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28094 Regression: Change text of buttons tooltips on custom content homepage block
  apps/meteor/client/views/home/cards/CustomContentCard.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: type: regression, stat: ready to merge, stat: QA tested

#28233 Regression: Adjusted components using PaginatedMultiSelected to be compatible with new Fuselage version
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx
  apps/meteor/client/views/hooks/useDepartmentsByUnitsList.ts
  apps/meteor/client/views/hooks/useMonitorsList.ts
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentForwarding.tsx
  yarn.lock
Labels: type: regression, stat: needs QA, feat: omnichannel

#28211 Chore: Add extra stats for omnichannel video calling
  apps/meteor/app/models/server/models/LivechatRooms.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/client/views/admin/info/DeploymentCard.stories.tsx
  apps/meteor/client/views/admin/info/InformationPage.stories.tsx
  apps/meteor/client/views/admin/info/UsageCard.stories.tsx
  apps/meteor/ee/app/license/server/getStatistics.ts
  apps/meteor/server/models/raw/Rooms.js
  packages/core-typings/src/IStats.ts
  packages/model-typings/src/models/IRoomsModel.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: omnichannel

#28169 [FIX] Notify apps engine event through ms api
  apps/meteor/ee/client/apps/communication/websockets.js
  apps/meteor/ee/server/apps/communication/events.ts
  apps/meteor/ee/server/apps/communication/websockets.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/services/apps-engine/service.ts
  packages/core-services/src/Events.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28245 Regression: message-parse version update
  yarn.lock
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28246 Regression: Adjusted departments upsell modal to check for licence and modules
  apps/meteor/client/views/hooks/useUpgradeTabParams.ts
  apps/meteor/lib/upgradeTab.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: omnichannel

#28248 Regression: Client is not loading new settings from server
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28254 Regression: Fix intermitent apps engine startup
  apps/meteor/ee/app/license/server/lib/isUnderAppLimits.ts
  apps/meteor/ee/app/license/server/license.ts
  apps/meteor/server/services/apps-engine/service.ts
  packages/core-services/src/index.ts
  packages/core-services/src/types/IAppsEngineService.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28264 Regression: Apps provider not handling apps lists correctly
  apps/meteor/client/views/marketplace/AppsProvider.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped, feat: marketplace

#28265 Regression: Installation of some apps fail
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/helpers/installApp.ts
  apps/meteor/client/views/marketplace/helpers/updateApp.ts
  apps/meteor/ee/client/apps/orchestrator.ts
  packages/rest-typings/src/apps/index.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28258 Regression: Adjusted departments upsell modal message
  apps/meteor/client/components/Omnichannel/modals/EnterpriseDepartmentsModal.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested, feat: omnichannel

#28266 Regression: Disabled grandfathered apps must have the option to be enabled
  apps/meteor/client/views/marketplace/AppMenu.js
Labels: type: regression, stat: ready to merge, stat: QA tested

#28294 Chore: Fix Email Inbox flaky test
  apps/meteor/tests/e2e/email-inboxes.spec.ts
  apps/meteor/tests/e2e/page-objects/admin-email-inboxes.ts
Labels: type: regression, stat: QA skipped

#28292 Regression: Creating Custom status
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested

#28262 Regression: Decrypt thread main message for room
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useGetMessageByID.ts
Labels: type: regression, stat: ready to merge, stat: QA tested

#28257 Regression: OAuthApps are added with empty string `_id` field
  apps/meteor/app/oauth2-server-config/server/admin/functions/addOAuthApp.ts
Labels: type: regression, stat: ready to merge, stat: QA tested

#28298 Regression: Scrolling on threads
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageListScrolling.ts
Labels: type: regression, stat: ready to merge, stat: QA tested

#28304 Regression: Fix hasLicense failing due call stack limit reasons
  apps/meteor/client/lib/createRouteGroup.tsx
  apps/meteor/ee/app/license/client/index.ts
  apps/meteor/ee/client/hooks/useHasLicenseModule.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#27970 Regression: `Admin UI -> Rooms` Search filter not working
  apps/meteor/app/api/server/lib/rooms.ts
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/server/models/raw/Rooms.js
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/model-typings/src/models/IRoomsModel.ts
Labels: type: regression, stat: ready to merge, stat: QA tested

#28311 Regression: Zapier Callout using wrong props
  apps/meteor/client/views/admin/integrations/new/NewZapier.js
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28310 Regression: Remove duplicated broadcast App events
  apps/meteor/server/services/apps-engine/service.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28263 Chore: Convert Federation to internal service
  apps/meteor/app/federation-v2/server/application/AbstractFederationService.ts
  apps/meteor/app/federation-v2/server/application/listener/MessageServiceListener.ts
  apps/meteor/app/federation-v2/server/application/listener/RoomServiceListener.ts
  apps/meteor/app/federation-v2/server/application/listener/UserServiceListener.ts
  apps/meteor/app/federation-v2/server/application/sender/RoomInternalHooksValidator.ts
  apps/meteor/app/federation-v2/server/application/sender/RoomServiceSender.ts
  apps/meteor/app/federation-v2/server/application/sender/UserServiceSender.ts
  apps/meteor/app/federation-v2/server/domain/IFederationBridge.ts
  apps/meteor/app/federation-v2/server/index.ts
  apps/meteor/app/federation-v2/server/infrastructure/Factory.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/slash-commands/index.ts
  apps/meteor/app/lib/server/methods/addUsersToRoom.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/ee/app/federation-v2/server/application/RoomService.ts
  apps/meteor/ee/app/federation-v2/server/application/sender/AbstractFederationService.ts
  apps/meteor/ee/app/federation-v2/server/application/sender/room/DMRoomInternalHooksServiceSender.ts
  apps/meteor/ee/app/federation-v2/server/application/sender/room/RoomInternalHooksServiceSender.ts
  apps/meteor/ee/app/federation-v2/server/domain/IFederationBridge.ts
  apps/meteor/ee/app/federation-v2/server/index.ts
  apps/meteor/ee/app/federation-v2/server/infrastructure/Factory.ts
  apps/meteor/ee/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/ee/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/ee/app/federation-v2/server/infrastructure/rocket-chat/slash-commands/index.ts
  apps/meteor/ee/server/api/federation/rooms.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/ee/server/local-services/federation/service.ts
  apps/meteor/ee/server/startup/services.ts
  apps/meteor/ee/tests/unit/app/federation-v2/server/application/RoomInternalHooksServiceSender.spec.ts
  apps/meteor/ee/tests/unit/app/federation-v2/server/infrastructure/rocket-chat/hooks/hooks.spec.ts
  apps/meteor/server/importPackages.ts
  apps/meteor/server/lib/rooms/roomTypes/private.ts
  apps/meteor/server/lib/rooms/roomTypes/public.ts
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/services/federation/service.ts
  apps/meteor/server/services/startup.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/application/sender/RoomServiceSender.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/matrix/Bridge.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/rocket-chat/hooks/hooks.spec.ts
  packages/core-services/src/LocalBroker.ts
  packages/core-services/src/index.ts
  packages/core-services/src/types/IFederationService.ts
Labels: type: improvement, feat: federation, stat: QA skipped

#28315 Chore: Manually define shared secrets to reusable workflows
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28303 Regression: OAuth Login
  apps/meteor/app/api/server/helpers/deprecationWarning.ts
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/client/views/admin/oauthApps/EditOauthAppWithData.tsx
  apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx
  apps/meteor/server/models/raw/OAuthApps.ts
  packages/model-typings/src/models/IOAuthAppsModel.ts
  packages/rest-typings/src/v1/oauthapps.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28322 Regression: Apps-Engine startup process was faulty
  apps/meteor/client/views/room/contextualBar/Apps/AppsWithData.tsx
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/startup.ts
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/package.json
  yarn.lock
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28319 Chore: New temporary settings to limit access to files and outside room members
  apps/meteor/app/api/server/settings.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/file-upload/server/lib/FileUpload.js
  apps/meteor/app/file-upload/server/lib/requests.js
  apps/meteor/app/file-upload/server/startup/settings.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/api/09-rooms.js
Labels: stat: QA skipped

#28327 Regression: fix Thread horizontal scrolling
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28331 Regression: Fix emojiPicker reactivity on load-more
  apps/meteor/app/emoji/client/emojiPicker.js
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28333 Release 5.4.4
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/api/server/settings.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/file-upload/server/lib/FileUpload.js
  apps/meteor/app/file-upload/server/lib/requests.js
  apps/meteor/app/file-upload/server/startup/settings.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/api/09-rooms.js
  package.json
Labels: stat: needs QA

#28332 Regression: Attachment auto size
  apps/meteor/.eslintcache
  apps/meteor/app/theme/client/imports/general/base.css
  apps/meteor/client/components/message/content/attachments/structure/AttachmentImage.tsx
  apps/meteor/client/components/message/content/attachments/structure/image/ImageBox.tsx
  apps/meteor/client/components/message/content/urlPreviews/UrlImagePreview.tsx
  apps/meteor/client/providers/AttachmentProvider.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped

#27886 [FIX] room data is not erased after deleting rooms by app
  apps/meteor/app/apps/server/bridges/rooms.ts
Labels: stat: needs QA

#28336 Chore: Remove duplicated functions in tests
  apps/meteor/.eslintcache
  apps/meteor/tests/data/uploads.helper.ts
  apps/meteor/tests/data/users.helper.js
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/api/09-rooms.js
  apps/meteor/tests/end-to-end/api/18-oauthapps.js
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28341 Regression: Added anchors elements to the allowed list to be clicked
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28342 Regression: Fix not showing global search option
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearchForm.tsx
  packages/core-typings/src/search/IMessageSearchProvider.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#28189 Chore: Remove/replace some Meteor packages
  apps/meteor/.eslintcache
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/app/meteor-autocomplete/client/autocomplete-client.js
  apps/meteor/package.json
  apps/meteor/server/startup/initialData.js
  yarn.lock
Labels: stat: needs QA

#28285 [FIX] App crashing when switching to Hindi (hi-In) language
  apps/meteor/packages/rocketchat-i18n/i18n/hi.i18n.json
Labels: type: bug, stat: ready to merge, stat: QA skipped

#28317 Chore: remove unused prop in register workspace modal
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepOneModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceTokenModal.tsx
Labels: stat: ready to merge, stat: QA skipped, feat: cloud

#28187 [FIX] Normal and multiline messages adding extra spaces upon copying/pasting
  packages/gazzodown/src/blocks/HeadingBlock.tsx
  packages/gazzodown/src/blocks/ParagraphBlock.tsx
Labels: stat: ready to merge, stat: QA tested

#28159 [IMPROVE] Adding input type=password to AWS secrets fields
  apps/meteor/app/file-upload/server/startup/settings.ts
  apps/meteor/client/views/admin/settings/inputs/PasswordSettingInput.tsx
Labels: stat: ready to merge, stat: QA tested

#27908 [IMPROVE] Galician onboarding translation
  apps/meteor/packages/rocketchat-i18n/i18n/gl.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#28328 refactor: Improve sidebar search list hook
  apps/meteor/client/lib/utils/getConfig.ts
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/views/hooks/useMembersList.ts
  apps/meteor/client/views/room/contextualBar/Discussions/useDiscussionsList.ts
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useFilesList.ts
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadsList.ts
  apps/meteor/client/views/teams/contextualBar/channels/hooks/useTeamsChannelList.ts
Labels: stat: ready to merge, stat: QA skipped

#28346 fix: Thread list not scrolling to bottom when sending a message.
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageListScrolling.ts
Labels: stat: ready to merge, stat: QA tested

#28140 chore: Remove old css
  apps/meteor/.eslintcache
  apps/meteor/app/theme/client/imports/components/avatar.css
  apps/meteor/app/theme/client/imports/components/header.css
  apps/meteor/app/theme/client/imports/components/messages.css
  apps/meteor/app/theme/client/imports/components/userInfo.css
  apps/meteor/app/theme/client/imports/forms/popup-list.css
  apps/meteor/app/theme/client/imports/forms/select.css
  apps/meteor/app/theme/client/imports/forms/switch.css
  apps/meteor/app/theme/client/imports/forms/tags.css
  apps/meteor/app/theme/client/imports/general/animations.css
  apps/meteor/app/theme/client/imports/general/apps.css
  apps/meteor/app/theme/client/imports/general/base.css
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/rtl.css
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/theme/client/imports/general/typography.css
  apps/meteor/app/theme/client/main.css
  apps/meteor/app/theme/client/vendor/fontello/css/fontello.css
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ModalSeparator/ModalSeparator.tsx
  apps/meteor/client/components/Omnichannel/modals/ModalSeparator/index.ts
  apps/meteor/client/components/Omnichannel/modals/ModalSeparator/style.css
  apps/meteor/client/views/composer/EmojiPickerWrapper.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/ExportMessages/MailExportForm.tsx
  apps/meteor/ee/app/canned-responses/client/index.js
  apps/meteor/ee/app/canned-responses/client/stylesheets/cannedResponses.css
  apps/meteor/public/font/fontello.eot
  apps/meteor/public/font/fontello.svg
  apps/meteor/public/font/fontello.ttf
  apps/meteor/public/font/fontello.woff
  apps/meteor/public/font/fontello.woff2
Labels: stat: needs QA

#28376 refactor: Replace `_.isObject` with `isObject`
  apps/meteor/.eslintcache
  apps/meteor/app/api/server/api.js
  apps/meteor/app/bot-helpers/server/index.js
  apps/meteor/app/custom-oauth/server/transform_helpers.js
  apps/meteor/app/lib/server/functions/getRoomByNameOrIdWithOptionToJoin.ts
  apps/meteor/app/utils/lib/tapi18n.js
  apps/meteor/lib/utils/isObject.ts
Labels: stat: ready to merge, stat: QA skipped

#28377 chore(deps): Upgrade `caniuse-lite`
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28123 chore: Migrate SMS to Service
  apps/meteor/app/livechat/imports/server/rest/sms.js
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/config.ts
  apps/meteor/app/livechat/server/externalFrame/index.ts
  apps/meteor/app/livechat/server/hooks/sendEmailTranscriptOnClose.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.d.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/routing/AutoSelection.ts
  apps/meteor/app/livechat/server/lib/routing/External.ts
  apps/meteor/app/livechat/server/lib/routing/ManualSelection.ts
  apps/meteor/app/livechat/server/livechat.ts
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
  apps/meteor/app/livechat/server/sendMessageBySMS.ts
  apps/meteor/app/livechat/server/startup.ts
  apps/meteor/app/sms/README.md
  apps/meteor/app/sms/server/SMS.js
  apps/meteor/app/sms/server/index.ts
  apps/meteor/app/sms/server/settings.ts
  apps/meteor/definition/externals/meteor/base64.d.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/sendPdfTranscriptOnClose.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/importPackages.ts
  apps/meteor/server/services/omnichannel-integrations/providers/index.ts
  apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts
  apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts
  apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts
  apps/meteor/server/services/omnichannel-integrations/service.ts
  apps/meteor/server/services/startup.ts
  apps/meteor/tests/data/livechat/rooms.ts
  packages/core-services/src/index.ts
  packages/core-services/src/types/IOmnichannelIntegrationService.ts
  packages/core-typings/src/index.ts
  packages/core-typings/src/omnichannel/index.ts
  packages/core-typings/src/omnichannel/routing.ts
  packages/core-typings/src/omnichannel/sms.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28373 docs: Update Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: stat: QA skipped

#27957 fix: Gallery opening other image after closing
  apps/meteor/app/ui/client/views/app/photoswipeContent.ts
Labels: stat: ready to merge, stat: QA skipped

#28393 refactor(client): Embed error boundary into `AppRoot`
  apps/meteor/.eslintcache
  apps/meteor/client/components/root/ErrorBoundary.tsx
  apps/meteor/client/startup/appRoot.tsx
  apps/meteor/client/views/banners/BannerRegion.tsx
  apps/meteor/client/views/root/AppErrorPage.tsx
  apps/meteor/client/views/root/AppRoot.tsx
  apps/meteor/client/views/root/OutermostErrorBoundary.tsx
Labels: stat: ready to merge, stat: QA skipped

#28270 fix: Wrong error message when trying to create new team with existing team name
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
Labels: stat: ready to merge, stat: QA skipped

#28359 chore: File attachment input border cut fix
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
Labels: stat: ready to merge, stat: QA tested

#28403 refactor(client): Refine `IUser[settings]`
  apps/meteor/app/ui-utils/client/lib/messageContext.ts
  apps/meteor/app/utils/client/index.ts
  apps/meteor/app/utils/client/lib/getUserPreference.ts
  packages/core-typings/src/IUser.ts
Labels: stat: ready to merge, stat: QA skipped

#28399 refactor: Remove promise await
  apps/meteor/app/api/server/v1/cloud.ts
  apps/meteor/app/api/server/v1/integrations.ts
Labels: stat: ready to merge, stat: QA skipped

#28276 fix: No feedback given in case of wrong password input in modal confirm password
  apps/meteor/app/2fa/client/overrideMeteorCall.ts
Labels: stat: ready to merge, stat: QA skipped

#28407 refactor: remove `Promise.await` calls from twitter Oauth implementation
  apps/meteor/app/custom-oauth/server/custom_oauth_server.js
  apps/meteor/app/lib/server/oauth/facebook.js
  apps/meteor/app/lib/server/oauth/google.js
  apps/meteor/app/lib/server/oauth/oauth.js
  apps/meteor/app/lib/server/oauth/twitter.js
Labels: stat: ready to merge, stat: QA skipped

#28406 refactor: remove `Promise.await` calls from irc bridge
  apps/meteor/app/irc/server/irc-bridge/index.js
  apps/meteor/app/irc/server/irc-bridge/localHandlers/onCreateRoom.js
  apps/meteor/app/irc/server/irc-bridge/localHandlers/onCreateUser.js
  apps/meteor/app/irc/server/irc-bridge/localHandlers/onJoinRoom.js
  apps/meteor/app/irc/server/irc-bridge/localHandlers/onLeaveRoom.js
  apps/meteor/app/irc/server/irc-bridge/localHandlers/onLogin.js
  apps/meteor/app/irc/server/irc-bridge/localHandlers/onLogout.js
  apps/meteor/app/irc/server/irc-bridge/localHandlers/onSaveMessage.js
  apps/meteor/app/irc/server/irc-bridge/peerHandlers/disconnected.js
  apps/meteor/app/irc/server/irc-bridge/peerHandlers/joinedChannel.js
  apps/meteor/app/irc/server/irc-bridge/peerHandlers/leftChannel.js
  apps/meteor/app/irc/server/irc-bridge/peerHandlers/nickChanged.js
  apps/meteor/app/irc/server/irc-bridge/peerHandlers/sentMessage.js
  apps/meteor/app/irc/server/irc.js
Labels: stat: ready to merge, stat: QA skipped

#28414 refactor(client): Move banner orchestration to `BannerRegion` effects
  apps/meteor/.eslintcache
  apps/meteor/app/version-check/client/index.js
  apps/meteor/app/version-check/server/methods/banner_dismiss.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/lib/appLayout.tsx
  apps/meteor/client/startup/banners.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/routes.tsx
  apps/meteor/client/views/banners/BannerRegion.tsx
  apps/meteor/client/views/banners/hooks/useDismissUserBannerMutation.ts
  apps/meteor/client/views/banners/hooks/useRemoteBanners.ts
  apps/meteor/client/views/banners/hooks/useUserBanners.ts
  apps/meteor/client/views/root/AppRoot.tsx
  packages/core-typings/src/IUser.ts
Labels: stat: ready to merge, stat: QA skipped

#28241 chore: Add `rid` to scope of `create-invite-links` permission check
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28216 fix: Emoji don't work after text in contiunous
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
Labels: type: bug, stat: ready to merge, communityPR, stat: QA skipped

#28420 refactor: Types of Meteor methods (1/N)
  apps/meteor/app/2fa/server/methods/checkCodesRemaining.ts
  apps/meteor/app/2fa/server/methods/disable.ts
  apps/meteor/app/2fa/server/methods/enable.ts
  apps/meteor/app/2fa/server/methods/regenerateCodes.ts
  apps/meteor/app/2fa/server/methods/validateTempToken.ts
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/authorization/server/methods/addPermissionToRole.ts
  apps/meteor/app/authorization/server/methods/addUserToRole.ts
  apps/meteor/app/authorization/server/methods/deleteRole.ts
  apps/meteor/app/authorization/server/methods/removeRoleFromPermission.ts
  apps/meteor/app/authorization/server/methods/removeUserFromRole.ts
  apps/meteor/app/authorization/server/streamer/permissions/index.ts
  apps/meteor/app/autotranslate/server/methods/getProviderUiMetadata.ts
  apps/meteor/app/autotranslate/server/methods/getSupportedLanguages.ts
  apps/meteor/app/autotranslate/server/methods/saveSettings.ts
  apps/meteor/app/autotranslate/server/methods/translateMessage.ts
  apps/meteor/app/cloud/server/methods.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/e2e/server/methods/updateGroupKey.ts
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/methods/deleteMessage.ts
  apps/meteor/app/lib/server/methods/executeSlashCommandPreview.ts
  apps/meteor/app/lib/server/methods/getMessages.ts
  apps/meteor/app/lib/server/methods/getSlashCommandPreviews.ts
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/app/ui-utils/client/lib/openRoom.tsx
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/app/webdav/server/methods/addWebdavAccount.ts
  apps/meteor/app/webdav/server/methods/getFileFromWebdav.ts
  apps/meteor/app/webdav/server/methods/removeWebdavAccount.ts
  apps/meteor/app/webdav/server/methods/uploadFileToWebdav.ts
  apps/meteor/client/methods/updateMessage.ts
  apps/meteor/client/stories/contexts/ServerContextMock.tsx
  apps/meteor/client/views/account/security/TwoFactorTOTP.tsx
  apps/meteor/client/views/admin/cloud/CloudPage.tsx
  apps/meteor/client/views/room/webdav/SaveToWebdavModal.tsx
  apps/meteor/definition/externals/meteor/meteor.d.ts
  apps/meteor/server/methods/createDirectMessage.ts
  apps/meteor/server/modules/watchers/publishFields.ts
  apps/meteor/server/publications/room/index.ts
  apps/meteor/server/publications/settings/index.ts
  packages/core-services/src/types/IRoomService.ts
  packages/core-typings/src/SlashCommands/index.ts
  packages/ui-contexts/src/ServerContext/methods.ts
  packages/ui-contexts/src/ServerContext/methods/followMessage.ts
  packages/ui-contexts/src/ServerContext/methods/message/unfollowMessage.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/addWebdavAccount.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/getFileFromWebdav.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/index.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/removeWebdavAccount.ts
  packages/ui-contexts/src/ServerContext/methods/webdav/uploadFileToWebdav.ts
Labels: stat: ready to merge, stat: QA skipped

#28293 fix: Fixed no role assign to manual registered users despite of Default Roles for Users settings
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/client/views/admin/users/AddUser.js
Labels: stat: ready to merge, stat: QA skipped

#27940 refactor: Omnichannel analytics conversion to typescript
  apps/meteor/client/views/omnichannel/analytics/AgentOverview.tsx
  apps/meteor/client/views/omnichannel/analytics/AnalyticsPage.tsx
  apps/meteor/client/views/omnichannel/analytics/DateRangePicker.tsx
  apps/meteor/client/views/omnichannel/analytics/InterchangeableChart.tsx
  apps/meteor/client/views/omnichannel/analytics/Overview.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterItem.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28250 refactor: `RoomInfo` to typescript
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/groups.js
  apps/meteor/client/components/InfoPanel/InfoPanelAction.tsx
  apps/meteor/client/components/avatar/RoomAvatarEditor.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoActions.tsx
  apps/meteor/client/views/hooks/useActionSpread.ts
  apps/meteor/client/views/room/contextualBar/Info/ChannelToTeamModal/ChannelToTeamConfirmation.tsx
  apps/meteor/client/views/room/contextualBar/Info/ChannelToTeamModal/ChannelToTeamModal.js
  apps/meteor/client/views/room/contextualBar/Info/ChannelToTeamModal/ChannelToTeamModal.tsx
  apps/meteor/client/views/room/contextualBar/Info/ChannelToTeamModal/ChannelToTeamSelection.tsx
  apps/meteor/client/views/room/contextualBar/Info/ChannelToTeamModal/index.ts
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfo.stories.tsx
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfoWithData.js
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/index.ts
  apps/meteor/client/views/room/contextualBar/Info/RoomInfoRouter.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomConvertToTeam.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomDelete.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomHide.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomLeave.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomMoveToTeam.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/useCanEditRoom.ts
  apps/meteor/client/views/room/contextualBar/Info/hooks/useRoomActions.ts
  apps/meteor/client/views/room/contextualBar/Info/index.js
  apps/meteor/client/views/room/contextualBar/Info/index.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useBlockUserAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useCallAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeLeaderAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeModeratorAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeOwnerAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useDirectMessageAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useIgnoreUserAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useMuteUserAction.tsx
  apps/meteor/client/views/teams/contextualBar/info/TeamsInfo.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rest-typings/src/v1/channels/ChannelsConvertToTeamProps.ts
  packages/rest-typings/src/v1/groups.ts
  packages/rest-typings/src/v1/groups/GroupsArchiveProps.ts
  packages/rest-typings/src/v1/groups/GroupsCloseProps.ts
  packages/rest-typings/src/v1/groups/GroupsConvertToTeamProps.ts
  packages/rest-typings/src/v1/groups/GroupsCountersProps.ts
  packages/rest-typings/src/v1/groups/GroupsCreateProps.ts
  packages/rest-typings/src/v1/groups/GroupsDeleteProps.ts
  packages/rest-typings/src/v1/groups/GroupsFilesProps.ts
  packages/rest-typings/src/v1/groups/GroupsKickProps.ts
  packages/rest-typings/src/v1/groups/GroupsLeaveProps.ts
  packages/rest-typings/src/v1/groups/GroupsMembersProps.ts
  packages/rest-typings/src/v1/groups/GroupsMessageProps.ts
  packages/rest-typings/src/v1/groups/GroupsRolesProps.ts
  packages/rest-typings/src/v1/groups/GroupsUnarchiveProps.ts
  packages/rest-typings/src/v1/groups/groups.ts
  packages/rest-typings/src/v1/groups/index.ts
Labels: stat: QA skipped

#27072 fix: Display Avatar Preference not hiding avatars on messages
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/SystemMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.spec.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessagesVerticalBar.tsx
  apps/meteor/client/views/room/MessageList/MessageList.tsx
  apps/meteor/client/views/room/components/contextualBar/MessageListTab.tsx
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearch.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/ee/client/views/audit/components/AuditMessageList.tsx
  apps/meteor/tests/unit/client/views/room/MessageList/Message.spec.tsx
Labels: subj: ui/ux, hacktoberfest, stat: ready to merge, communityPR, stat: QA skipped

#28430 fix: missing margins in message composer icons
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
Labels: stat: ready to merge, stat: QA skipped

#28433 refactor(eslint): Add “no-misused-promises” eslint rule
  apps/meteor/.eslintrc.json
  apps/meteor/app/integrations/server/methods/incoming/deleteIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/outgoing/deleteOutgoingIntegration.ts
  apps/meteor/app/slashcommands-mute/server/unmute.ts
  apps/meteor/app/ui-message/client/actionButtons/tabbar.ts
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/client/components/GenericModal.tsx
  apps/meteor/client/lib/2fa/process2faReturn.ts
  apps/meteor/client/views/admin/permissions/CustomRoleUpsellModal.tsx
  apps/meteor/definition/externals/meteor/littledata-synced-cron.d.ts
  apps/meteor/ee/app/license/server/license.ts
  apps/meteor/ee/server/services/mongo.ts
  apps/meteor/package.json
  apps/meteor/server/lib/migrations.ts
  apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
  apps/meteor/server/startup/migrations/v273.ts
  apps/meteor/server/startup/migrations/v276.ts
  apps/meteor/server/startup/migrations/v291.ts
  apps/meteor/server/startup/migrations/v292.ts
Labels: stat: needs QA

#28302 fix: Error message is displayed in case no file is found in custom sound section.
  apps/meteor/client/views/admin/customSounds/CustomSoundsRoute.tsx
Labels: stat: ready to merge, stat: QA skipped

#28413 fix: Show all users on rooms members list
  apps/meteor/app/api/server/v1/channels.js
  apps/meteor/app/api/server/v1/groups.js
  apps/meteor/app/api/server/v1/im.ts
Labels: stat: ready to merge, stat: QA tested

#28418 fix: Routing fixed for private apps in marketplace section
  apps/meteor/client/views/marketplace/AppsList/AppRow.tsx
Labels: stat: ready to merge, stat: QA skipped

#28431 refactor: Types of Meteor methods (3/N)
  apps/meteor/app/channel-settings/server/methods/saveRoomSettings.ts
  apps/meteor/app/lib/client/methods/sendMessage.ts
  apps/meteor/app/lib/server/methods/saveSettings.ts
  apps/meteor/app/lib/server/methods/sendMessage.ts
  apps/meteor/app/mail-messages/server/methods/sendMail.ts
  apps/meteor/app/utils/server/lib/normalizeMessagesForUser.ts
  apps/meteor/server/methods/loadSurroundingMessages.ts
  apps/meteor/server/methods/logoutCleanUp.js
  apps/meteor/server/methods/logoutCleanUp.ts
  apps/meteor/server/methods/openRoom.ts
  apps/meteor/server/methods/readThreads.ts
  apps/meteor/server/methods/reportMessage.ts
  apps/meteor/server/methods/roomNameExists.ts
  apps/meteor/server/methods/saveUserPreferences.ts
  packages/ui-contexts/src/ServerContext/methods.ts
  packages/ui-contexts/src/ServerContext/methods/message/reportMessage.ts
  packages/ui-contexts/src/ServerContext/methods/roomNameExists.ts
  packages/ui-contexts/src/ServerContext/methods/saveRoomSettings.ts
  packages/ui-contexts/src/ServerContext/methods/saveSettings.ts
  packages/ui-contexts/src/ServerContext/methods/saveUserPreferences.ts
Labels: stat: ready to merge, stat: QA skipped

#26662 feat: Message Forwarding
  apps/meteor/app/models/client/models/CachedChatSubscription.ts
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/components/UserAndRoomAutoCompleteMultiple.tsx/UserAndRoomAutoCompleteMultiple.tsx
  apps/meteor/client/components/UserAndRoomAutoCompleteMultiple.tsx/index.ts
  apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx
  apps/meteor/client/sidebar/Sidebar.stories.tsx
  apps/meteor/client/views/room/modals/ShareMessageModal/ShareMessageModal.tsx
  apps/meteor/client/views/room/modals/ShareMessageModal/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/mocks/data.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageQuoteAttachment.ts
  packages/rest-typings/src/v1/chat.ts
Labels: stat: ready to merge, stat: QA tested

#28397 chore: Theme changes on clicking Label
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
Labels: stat: QA skipped

#28363 fix(upload): Restriction setting not being applied to the old UFS route
  apps/meteor/app/file-upload/server/lib/FileUpload.js
  apps/meteor/tests/end-to-end/api/09-rooms.js
Labels: stat: ready to merge, stat: QA skipped

#27881 fix: When clicking on display option their checked status does not changes
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.tsx
  apps/meteor/client/components/Sidebar/ListItem.tsx
  apps/meteor/client/components/SortList/GroupingList.tsx
  apps/meteor/client/components/SortList/SortModeList.tsx
  apps/meteor/client/components/SortList/ViewModeList.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28452 refactor: Types of Meteor methods (4/N)
  apps/meteor/app/authorization/server/streamer/permissions/index.ts
  apps/meteor/app/lib/server/methods/checkRegistrationSecretURL.ts
  apps/meteor/app/livechat/server/methods/changeLivechatStatus.ts
  apps/meteor/app/livechat/server/methods/saveAgentInfo.ts
  apps/meteor/app/livechat/server/methods/takeInquiry.ts
  apps/meteor/app/mail-messages/server/methods/unsubscribe.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/models/server/models/Messages.js
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/user-status/server/methods/setUserStatus.ts
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/client/lib/utils/mapMessageFromApi.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/resumeOnHold.ts
  apps/meteor/ee/server/methods/getReadReceipts.ts
  apps/meteor/server/methods/getPasswordPolicy.ts
  apps/meteor/server/methods/getRoomById.ts
  apps/meteor/server/models/raw/EmojiCustom.ts
  apps/meteor/server/publications/settings/index.ts
  apps/meteor/server/publications/spotlight.ts
  apps/meteor/server/publications/subscription/index.js
  apps/meteor/server/publications/subscription/index.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/model-typings/src/models/IEmojiCustomModel.ts
  packages/ui-contexts/src/ServerContext/methods.ts
  packages/ui-contexts/src/ServerContext/methods/getReadReceipts.ts
  packages/ui-contexts/src/ServerContext/methods/mailer/unsubscribe.ts
Labels: stat: ready to merge, stat: QA skipped

#28437 chore: ddp streamer typings
  apps/meteor/client/hooks/lists/useStreamUpdatesForMessageList.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/providers/ServerProvider.tsx
  apps/meteor/client/views/admin/import/ImportProgressPage.tsx
  apps/meteor/client/views/banners/hooks/useRemoteBanners.ts
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/hooks/useVideoConfDataStream.ts
  packages/ui-contexts/src/ServerContext/ServerContext.ts
  packages/ui-contexts/src/ServerContext/methods.ts
  packages/ui-contexts/src/ServerContext/streams.ts
  packages/ui-contexts/src/hooks/useStream.ts
  packages/ui-contexts/src/index.ts
Labels: stat: needs QA

#28445 fix: marketplace requested glitch
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28464 refactor(eslint): Add "no-floating-promises" eslint rule - Part 2
  apps/meteor/app/api/server/v1/mailer.ts
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/ee/tests/unit/server/federation/server/application/room/sender/RoomServiceSender.spec.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/26-LDAP.ts
  apps/meteor/tests/end-to-end/api/27-roles.ts
  apps/meteor/tests/end-to-end/api/import.spec.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
  apps/meteor/tests/end-to-end/api/livechat/07-queue.ts
  apps/meteor/tests/end-to-end/api/livechat/08-triggers.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  apps/meteor/tests/end-to-end/api/livechat/11-email-inbox.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
  apps/meteor/tests/end-to-end/api/livechat/12-mailer.ts
  apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
  apps/meteor/tests/end-to-end/api/livechat/13-tags.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  apps/meteor/tests/end-to-end/api/livechat/15-canned-responses.ts
  apps/meteor/tests/end-to-end/api/livechat/16-video-call.ts
  apps/meteor/tests/end-to-end/api/livechat/17-dashboards-ee.ts
  apps/meteor/tests/end-to-end/api/livechat/18-rooms-ee.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
  apps/meteor/tests/end-to-end/apps/05-video-conferences.ts
  apps/meteor/tests/unit/server/federation/infrastructure/matrix/handlers/BaseEvent.spec.ts
Labels: stat: needs QA

#28131 fix: Engagement dashboard crash on Users tab
  apps/meteor/server/models/raw/Messages.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28455 fix: videoconf stream
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: ready to merge, stat: QA skipped

#28471 chore: Remove invalid `aria-description` from list menus
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.tsx
  apps/meteor/client/components/SortList/GroupingList.tsx
  apps/meteor/client/components/SortList/SortModeList.tsx
  apps/meteor/client/components/SortList/ViewModeList.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
Labels: stat: ready to merge, stat: QA skipped

#28417 refactor: Convert chat endpoints to TS
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/tests/end-to-end/api/05-chat.js
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/chat.ts
Labels: feat: api, stat: ready to merge, stat: QA skipped

#28469 refactor: Convert channels endpoints to TS
  apps/meteor/app/api/server/api.d.ts
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/v1/channels.js
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/server/lib/findUsersOfRoom.ts
  packages/rest-typings/src/v1/channels/ChannelsCreateProps.ts
  packages/rest-typings/src/v1/channels/ChannelsGetIntegrationsProps.ts
  packages/rest-typings/src/v1/channels/ChannelsInviteProps.ts
  packages/rest-typings/src/v1/channels/ChannelsListProps.ts
  packages/rest-typings/src/v1/channels/ChannelsOnlineProps.ts
  packages/rest-typings/src/v1/channels/ChannelsRenameProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetCustomFieldsProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetDefaultProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetDescriptionProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetJoinCodeProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetPurposeProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetTopicProps.ts
  packages/rest-typings/src/v1/channels/ChannelsSetTypeProps.ts
  packages/rest-typings/src/v1/channels/channels.ts
Labels: type: improvement, stat: QA skipped

#28434 fix: Horizontal scroll in main room if text is too long
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/federation/tests/messaging/dm.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/private.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/public.spec.ts
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  packages/gazzodown/src/blocks/HeadingBlock.tsx
  packages/gazzodown/src/blocks/ParagraphBlock.tsx
Labels: stat: ready to merge, stat: QA tested

#28486 chore: make callbacks accept async
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.js
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
  apps/meteor/app/oembed/server/server.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/addDepartmentAncestors.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterForwardChatToAgent.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterForwardChatToDepartment.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterOnHoldChatResumed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterRemoveDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterReturnRoomAsInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTakeInquiry.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeJoinRoom.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewRoom.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onAgentAssignmentFailed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCloseLivechat.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadConfigApi.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/sendPdfTranscriptOnClose.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/setPredictedVisitorAbandonmentTime.js
  apps/meteor/ee/app/message-read-receipt/server/hooks/afterSaveMessage.ts
  apps/meteor/ee/server/configuration/oauth.ts
  apps/meteor/ee/server/local-services/federation/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: needs QA

#28408 refactor: Remove `Promise.await` calls from Slack Adapter
  apps/meteor/app/api/server/v1/commands.ts
  apps/meteor/app/slackbridge/server/RocketAdapter.js
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/slackbridge/server/slackbridge_import.server.js
  apps/meteor/app/slashcommands-join/client/client.ts
  apps/meteor/app/utils/lib/slashCommand.ts
Labels: stat: needs QA

#28485 refactor: convert getRoomRoles to async
  apps/meteor/server/lib/roles/getRoomRoles.ts
Labels: stat: ready to merge, stat: QA skipped

#28480 refactor: move from canDeleteMessage to canDeleteMessageAsync
  apps/meteor/app/api/server/default/info.ts
  apps/meteor/app/authorization/server/functions/canDeleteMessage.ts
  apps/meteor/app/lib/server/methods/deleteMessage.ts
Labels: stat: needs QA

#28488 refactor: Remove `FederationRoomEvents` model
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/federation/server/endpoints/requestFromLatest.js
  apps/meteor/app/federation/server/functions/dashboard.js
  apps/meteor/app/federation/server/hooks/afterAddedToRoom.js
  apps/meteor/app/federation/server/hooks/afterCreateDirectRoom.js
  apps/meteor/app/federation/server/hooks/afterCreateRoom.js
  apps/meteor/app/federation/server/hooks/afterDeleteMessage.js
  apps/meteor/app/federation/server/hooks/afterLeaveRoom.js
  apps/meteor/app/federation/server/hooks/afterMuteUser.js
  apps/meteor/app/federation/server/hooks/afterRemoveFromRoom.js
  apps/meteor/app/federation/server/hooks/afterSaveMessage.js
  apps/meteor/app/federation/server/hooks/afterSetReaction.js
  apps/meteor/app/federation/server/hooks/afterUnmuteUser.js
  apps/meteor/app/federation/server/hooks/afterUnsetReaction.js
  apps/meteor/app/federation/server/hooks/beforeDeleteRoom.js
  apps/meteor/app/federation/server/lib/context.ts
  apps/meteor/app/federation/server/methods/loadContextEvents.js
  apps/meteor/app/federation/server/methods/testSetup.js
  apps/meteor/app/models/server/index.ts
  apps/meteor/app/models/server/models/FederationEvents.js
  apps/meteor/app/models/server/models/FederationRoomEvents.js
  apps/meteor/server/cron/federation.ts
  apps/meteor/server/models/FederationRoomEvents.ts
  apps/meteor/server/models/raw/FederationEvents.ts
  apps/meteor/server/models/raw/FederationRoomEvents.ts
  apps/meteor/server/models/startup.ts
  packages/core-typings/src/federation/v1/IFederationEvent.ts
  packages/core-typings/src/federation/v1/events.ts
  packages/core-typings/src/federation/v1/index.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/IFederationRoomEventsModel.ts
  packages/models/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#28493 refactor(promise.await): saveUserIdentity.ts, saveUser.js, relinquishRoomOwnerships.ts and deleteMessage.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/relinquishRoomOwnerships.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/functions/saveUserIdentity.ts
  apps/meteor/app/lib/server/methods/insertOrUpdateUser.js
  apps/meteor/app/lib/server/methods/setUsername.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
  apps/meteor/app/meteor-accounts-saml/server/loginHandler.ts
  apps/meteor/server/methods/saveUserProfile.js
Labels: stat: needs QA

#28443 fix: remove link appearing in quotes preview
  apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx
  apps/meteor/lib/createQuoteAttachment.ts
Labels: stat: ready to merge, stat: QA tested

#28479 refactor: convert addUserToRoom to async
  apps/meteor/app/apps/server/bridges/rooms.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/invites/server/functions/useInviteToken.js
  apps/meteor/app/irc/server/irc-bridge/peerHandlers/joinedChannel.js
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/setUsername.ts
  apps/meteor/app/lib/server/methods/addUsersToRoom.js
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/lib/oauth/Manager.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
  apps/meteor/server/services/team/service.ts
Labels: stat: needs QA

#28458 refactor: Remove `ImportData` meteor model
  apps/meteor/app/importer-csv/server/importer.js
  apps/meteor/app/importer-hipchat-enterprise/server/importer.js
  apps/meteor/app/importer-slack/server/importer.js
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/importer/server/classes/ImporterBase.js
  apps/meteor/app/importer/server/classes/VirtualDataConverter.ts
  apps/meteor/app/models/server/index.ts
  apps/meteor/app/models/server/models/ImportData.ts
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/server/lib/ldap/DataConverter.ts
  apps/meteor/server/models/raw/ImportData.ts
  packages/model-typings/src/models/IImportDataModel.ts
Labels: stat: ready to merge, stat: QA skipped

#28492 refactor(promise.await): createRoom.ts, createDirectRoom.ts and cleanRoomHistory.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/irc/server/irc-bridge/peerHandlers/joinedChannel.js
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/methods/createChannel.ts
  apps/meteor/app/lib/server/methods/createPrivateGroup.js
  apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
  apps/meteor/app/slackbridge/server/RocketAdapter.js
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/ee/server/configuration/oauth.ts
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/lib/oauth/Manager.ts
  apps/meteor/server/methods/createDirectMessage.ts
Labels: stat: ready to merge, stat: QA skipped

#28483 refactor: remove Promise.await
  apps/meteor/app/authorization/server/functions/canSendMessage.ts
  apps/meteor/app/lib/server/methods/deleteUserOwnAccount.ts
  apps/meteor/app/livechat/imports/server/rest/users.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
  apps/meteor/ee/server/api/roles.ts
  apps/meteor/ee/server/lib/audit/startup.ts
  apps/meteor/ee/server/lib/roles/insertRole.ts
  apps/meteor/ee/server/lib/roles/updateRole.ts
  apps/meteor/ee/server/startup/audit.ts
  apps/meteor/server/lib/roles/removeUserFromRoles.ts
  apps/meteor/server/methods/addRoomLeader.js
  apps/meteor/server/methods/addRoomModerator.js
  apps/meteor/server/methods/addRoomOwner.js
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/methods/messageSearch.ts
  apps/meteor/server/methods/removeRoomLeader.js
  apps/meteor/server/methods/removeRoomModerator.js
  apps/meteor/server/methods/saveUserProfile.js
Labels: stat: needs QA

#28503 refactor(models): Use Messages Raw model (1/N)
  apps/meteor/app/api/server/lib/messages.ts
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/app/lib/server/methods/getMessages.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/registerGuest.js
  apps/meteor/app/livechat/server/methods/setDepartmentForVisitor.js
  apps/meteor/app/mentions/server/methods/getUserMentionsByChannel.js
  apps/meteor/app/message-mark-as-unread/server/unreadMessages.js
  apps/meteor/app/models/server/models/Messages.js
  apps/meteor/app/otr/server/methods/deleteOldOTRMessages.ts
  apps/meteor/app/threads/server/methods/getThreadMessages.ts
  apps/meteor/server/methods/loadMissedMessages.ts
  apps/meteor/server/methods/loadNextMessages.ts
  apps/meteor/server/methods/loadSurroundingMessages.ts
  apps/meteor/server/models/raw/Messages.ts
  packages/model-typings/src/models/IMessagesModel.ts
Labels: stat: ready to merge, stat: QA skipped

#28505 refactor(models): Use Messages Raw model (2/N)
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/models/server/models/Messages.js
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/client/methods/unpinMessage.ts
  apps/meteor/client/views/admin/info/DeploymentCard.stories.tsx
  apps/meteor/client/views/admin/info/InformationPage.stories.tsx
  apps/meteor/client/views/admin/info/InformationRoute.tsx
  apps/meteor/client/views/admin/info/UsageCard.stories.tsx
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/publications/messages.ts
  packages/core-typings/src/IStats.ts
  packages/model-typings/src/models/IMessagesModel.ts
Labels: stat: QA skipped

#27781 feat: Custom roles and Public&Private apps stats
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/client/views/admin/info/DeploymentCard.stories.tsx
  apps/meteor/client/views/admin/info/InformationPage.stories.tsx
  apps/meteor/client/views/admin/info/UsageCard.stories.tsx
  apps/meteor/server/models/raw/Roles.ts
  packages/core-typings/src/IStats.ts
  packages/model-typings/src/models/IRolesModel.ts
Labels: stat: ready to merge, stat: QA tested

#28476 refactor: Remove Promise.await - apps/meteor/app/api/server/api.js
  apps/meteor/.meteor/versions
  apps/meteor/app/api/server/api.js
  apps/meteor/package.json
  apps/meteor/packages/.eslintrc.json
  apps/meteor/packages/meteor-restivus/.gitignore
  apps/meteor/packages/meteor-restivus/lib/auth.js
  apps/meteor/packages/meteor-restivus/lib/iron-router-error-to-response.js
  apps/meteor/packages/meteor-restivus/lib/json-routes.js
  apps/meteor/packages/meteor-restivus/lib/restivus.js
  apps/meteor/packages/meteor-restivus/lib/route.js
  apps/meteor/packages/meteor-restivus/package.js
  apps/meteor/packages/rocketchat-mongo-config/server/index.js
  yarn.lock
Labels: stat: needs QA

#28391 fix: App Limitations UI changes
  apps/meteor/client/views/marketplace/components/EnabledAppsCount.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/images/unlimited-apps-modal.svg
Labels: stat: needs QA

#28472 refactor: `LivechatDepartmentAgents` removal
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/app/lib/server/functions/saveUserIdentity.ts
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/api/v1/agent.ts
  apps/meteor/app/livechat/server/hooks/beforeDelegateAgent.js
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/QueueManager.js
  apps/meteor/app/livechat/server/lib/RoutingManager.js
  apps/meteor/app/livechat/server/lib/routing/AutoSelection.ts
  apps/meteor/app/livechat/server/methods/getNextAgent.ts
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
  apps/meteor/app/livechat/server/roomAccessValidator.internalService.ts
  apps/meteor/app/models/server/index.ts
  apps/meteor/app/models/server/models/LivechatDepartment.js
  apps/meteor/app/models/server/models/LivechatDepartmentAgents.js
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
  apps/meteor/ee/app/models/server/raw/LivechatDepartmentAgents.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
Labels: stat: ready to merge, stat: QA skipped

#28467 fix: Offline register option
  apps/meteor/client/views/admin/cloud/ManualWorkspaceRegistrationModal.tsx
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, feat: cloud

#28529 refactor(promise.await): getMongoInfo.js, versio-check and missing meteor methods
  apps/meteor/app/channel-settings/server/methods/saveRoomSettings.ts
  apps/meteor/app/livechat/server/methods/registerGuest.ts
  apps/meteor/app/livechat/server/methods/saveBusinessHour.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/app/statistics/server/methods/getStatistics.js
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/app/utils/server/functions/getMongoInfo.js
  apps/meteor/app/version-check/server/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/removeBusinessHour.ts
  apps/meteor/server/methods/createDirectMessage.ts
  apps/meteor/server/startup/serverRunning.js
Labels: stat: ready to merge, stat: QA skipped

#28537 regression: fix CI
  apps/meteor/app/importer-csv/server/importer.js
  apps/meteor/app/importer-hipchat-enterprise/server/importer.js
  apps/meteor/app/importer-pending-avatars/server/importer.js
  apps/meteor/app/importer-pending-files/server/importer.js
  apps/meteor/app/importer-slack-users/server/importer.js
  apps/meteor/app/importer-slack/server/importer.js
  apps/meteor/app/importer/server/classes/ImporterBase.js
  apps/meteor/app/importer/server/methods/downloadPublicImportFile.ts
  apps/meteor/app/importer/server/methods/getLatestImportOperations.ts
  apps/meteor/app/importer/server/methods/uploadImportFile.ts
Labels: stat: needs QA

#28532 refactor: Remove Promise.await from teams-mention feature
  apps/meteor/app/mentions/server/Mentions.js
  apps/meteor/app/mentions/server/server.js
  apps/meteor/ee/app/teams-mention/server/EEMentionQueries.js
  apps/meteor/ee/app/teams-mention/server/EESpotlight.js
  apps/meteor/ee/app/teams-mention/server/index.ts
  apps/meteor/server/lib/spotlight.js
  apps/meteor/server/publications/spotlight.ts
  apps/meteor/tests/unit/app/mentions/server.tests.js
Labels: stat: needs QA

#28525 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: stat: needs QA

#28528 refactor: Types of Meteor methods (9/N)
  apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/outgoing/updateOutgoingIntegration.ts
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/functions/saveUserIdentity.ts
  apps/meteor/app/lib/server/functions/setUserAvatar.ts
  apps/meteor/app/lib/server/methods/addUsersToRoom.ts
  apps/meteor/app/lib/server/methods/cleanRoomHistory.ts
  apps/meteor/app/livechat/server/methods/saveCustomField.ts
  apps/meteor/app/message-mark-as-unread/server/logger.ts
  apps/meteor/app/message-mark-as-unread/server/unreadMessages.ts
  apps/meteor/app/user-status/server/methods/insertOrUpdateUserStatus.ts
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useMuteUserAction.tsx
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/ee/app/canned-responses/server/methods/saveCannedResponse.ts
  apps/meteor/ee/app/models/server/models/CannedResponse.js
  apps/meteor/imports/personal-access-tokens/server/api/methods/generateToken.ts
  apps/meteor/imports/personal-access-tokens/server/api/methods/index.ts
  apps/meteor/imports/personal-access-tokens/server/api/methods/regenerateToken.ts
  apps/meteor/imports/personal-access-tokens/server/api/methods/removeToken.ts
  apps/meteor/imports/personal-access-tokens/server/index.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/lib/findUsersOfRoom.ts
  apps/meteor/server/methods/OEmbedCacheCleanup.ts
  apps/meteor/server/methods/addAllUserToRoom.ts
  apps/meteor/server/methods/addRoomLeader.ts
  apps/meteor/server/methods/addRoomModerator.ts
  apps/meteor/server/methods/addRoomOwner.ts
  apps/meteor/server/methods/browseChannels.ts
  apps/meteor/server/methods/getRoomIdByNameOrId.ts
  apps/meteor/server/methods/getRoomNameById.ts
  apps/meteor/server/methods/getTotalChannels.ts
  apps/meteor/server/methods/getUsersOfRoom.ts
  apps/meteor/server/methods/loadLocale.ts
  apps/meteor/server/methods/muteUserInRoom.ts
  apps/meteor/server/methods/registerUser.ts
  apps/meteor/server/methods/resetAvatar.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/methods/sendForgotPasswordEmail.ts
  apps/meteor/server/methods/setAvatarFromService.ts
  apps/meteor/server/methods/unmuteUserInRoom.ts
  apps/meteor/server/methods/userSetUtcOffset.ts
  apps/meteor/server/models/raw/CustomUserStatus.ts
  apps/meteor/server/publications/messages.ts
  packages/core-services/src/types/ITeamService.ts
  packages/model-typings/src/models/ICustomUserStatusModel.ts
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: stat: needs QA

#28530 refactor: remove Promise.await from oauth manager
  apps/meteor/ee/server/configuration/oauth.ts
  apps/meteor/ee/server/lib/oauth/Manager.ts
Labels: stat: ready to merge, stat: QA skipped

#28552 chore: Make CI fail if checks fail
  .github/workflows/ci.yml
Labels: stat: needs QA

#28549 refactor(models): Use Messages Raw model (3/N)
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/discussion/server/hooks/propagateDiscussionMetadata.ts
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/app/lib/server/functions/saveUserIdentity.ts
  apps/meteor/app/models/server/models/Messages.js
  apps/meteor/app/models/server/models/Rooms.js
  apps/meteor/app/oembed/server/server.ts
  apps/meteor/ee/server/local-services/message-reads/service.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/models/raw/Rooms.js
  packages/model-typings/src/models/IMessagesModel.ts
  packages/model-typings/src/models/IRoomsModel.ts
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: QA skipped

#28487 refactor: Remove `LivechatInquiry` model
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/QueueManager.js
  apps/meteor/app/livechat/server/lib/RoutingManager.js
  apps/meteor/app/livechat/server/methods/setUpConnection.ts
  apps/meteor/app/livechat/server/methods/takeInquiry.ts
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
  apps/meteor/app/models/server/index.ts
  apps/meteor/app/models/server/models/LivechatInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onAgentAssignmentFailed.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/resumeOnHold.ts
  ee/apps/ddp-streamer/src/configureServer.ts
Labels: stat: ready to merge, stat: QA skipped

#28540 refactor: canAccessRoomId to async
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/api/server/v1/commands.ts
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/authorization/server/functions/canAccessRoom.ts
  apps/meteor/app/authorization/server/index.js
  apps/meteor/app/e2e/server/methods/getUsersOfRoomWithoutKey.ts
  apps/meteor/app/e2e/server/methods/setRoomKeyID.ts
  apps/meteor/app/lib/server/methods/getMessages.ts
  apps/meteor/app/lib/server/methods/getSingleMessage.ts
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/ee/server/methods/getReadReceipts.ts
  apps/meteor/server/methods/loadMissedMessages.ts
  apps/meteor/server/methods/loadNextMessages.ts
  apps/meteor/server/methods/loadSurroundingMessages.ts
  apps/meteor/server/methods/messageSearch.ts
  apps/meteor/server/publications/messages.ts
Labels: stat: needs QA

#28527 refactor: remove Promise.await from LDAP files
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/importer/server/classes/ImporterBase.js
  apps/meteor/app/importer/server/definitions/IConversionCallbacks.ts
  apps/meteor/ee/server/configuration/ldap.ts
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/server/configuration/ldap.ts
  apps/meteor/server/lib/ldap/DataConverter.ts
Labels: stat: needs QA

#27856 feat: Calendar Integration Authentication Modal
  apps/meteor/client/components/message/content/UiKitSurface.tsx
  apps/meteor/client/views/calendarIntegration/CalendarAuthModal.tsx
Labels: stat: needs QA

#28454 fix: Thread message preview
  apps/meteor/client/components/GazzodownText.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28555 refactor(promise.await): Low hanging fruits (1/N)
  apps/meteor/app/federation/server/endpoints/uploads.js
  apps/meteor/app/federation/server/hooks/afterAddedToRoom.js
  apps/meteor/app/federation/server/hooks/afterCreateDirectRoom.js
  apps/meteor/app/federation/server/hooks/afterCreateRoom.js
  apps/meteor/app/federation/server/hooks/afterDeleteMessage.js
  apps/meteor/app/federation/server/hooks/afterLeaveRoom.js
  apps/meteor/app/federation/server/hooks/afterMuteUser.js
  apps/meteor/app/federation/server/hooks/afterRemoveFromRoom.js
  apps/meteor/app/federation/server/hooks/afterSaveMessage.js
  apps/meteor/app/federation/server/hooks/afterSetReaction.js
  apps/meteor/app/federation/server/hooks/afterUnmuteUser.js
  apps/meteor/app/federation/server/hooks/afterUnsetReaction.js
  apps/meteor/app/federation/server/hooks/beforeDeleteRoom.js
  apps/meteor/app/importer-slack/server/importer.js
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/app/livechat/server/hooks/beforeDelegateAgent.js
  apps/meteor/app/livechat/server/hooks/processRoomAbandonment.js
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.js
  apps/meteor/app/livechat/server/hooks/saveContactLastChat.js
  apps/meteor/app/livechat/server/hooks/saveLastMessageToInquiry.ts
  apps/meteor/app/livechat/server/hooks/sendEmailTranscriptOnClose.ts
  apps/meteor/app/livechat/server/sendMessageBySMS.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
  apps/meteor/app/meteor-accounts-saml/server/loginHandler.ts
  apps/meteor/app/retention-policy/server/cronPruneMessages.ts
  apps/meteor/app/slackbridge/server/SlackAdapter.js
Labels: stat: needs QA

#28450 fix: Changing the app's error verification
  apps/meteor/app/file-upload/server/lib/FileUpload.js
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/package.json
  yarn.lock
Labels: feat: apps, stat: ready to merge, stat: QA tested

#28556 refactor(promise.await): Low hanging fruits (2/2)
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/startup.ts
  apps/meteor/ee/app/teams-mention/server/EEMentionQueries.js
  apps/meteor/server/services/federation/infrastructure/rocket-chat/hooks/index.ts
Labels: stat: needs QA

#28186 feat: VideoConference Guest mode and Conference Router
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/client/components/message/content/UiKitSurface.tsx
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/startup/routes.tsx
  apps/meteor/client/views/conference/ConferencePage.tsx
  apps/meteor/client/views/conference/ConferencePageError.tsx
  apps/meteor/client/views/conference/ConferenceRoute.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfBlockModal.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/hooks/useVideoConfOpenCall.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/hooks/useVideoConfWarning.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useCallAction.tsx
  apps/meteor/client/views/root/MainLayout/AuthenticationCheck.tsx
  apps/meteor/client/views/root/MainLayout/LoginPage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/web-ui-registration/src/CMSPage.tsx
  packages/web-ui-registration/src/GuestForm.tsx
  packages/web-ui-registration/src/RegistrationPageRouter.tsx
  packages/web-ui-registration/src/hooks/useLoginRouter.ts
  packages/web-ui-registration/src/index.ts
Labels: stat: ready to merge, stat: QA tested

#28563 refactor: Don't use meteor collections on migrations
  apps/meteor/app/api/server/v1/push.ts
  apps/meteor/app/notification-queue/server/NotificationQueue.ts
  apps/meteor/app/push-notifications/server/lib/PushNotification.ts
  apps/meteor/app/push/server/index.ts
  apps/meteor/app/push/server/methods.ts
  apps/meteor/app/push/server/push.js
  apps/meteor/server/lib/pushConfig.ts
  apps/meteor/server/models/AppsTokens.ts
  apps/meteor/server/models/raw/AppsTokens.ts
  apps/meteor/server/models/startup.ts
  apps/meteor/server/startup/migrations/v269.ts
  apps/meteor/server/startup/migrations/v273.ts
  apps/meteor/server/startup/migrations/v276.ts
  packages/core-typings/src/AppsTokens.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/IAppsTokensModel.ts
  packages/models/src/index.ts
Labels: stat: needs QA

#28558 refactor(models): Use Messages Raw model (4/N)
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/app/lib/server/functions/relinquishRoomOwnerships.ts
  apps/meteor/app/livechat/server/hooks/processRoomAbandonment.js
  apps/meteor/app/models/server/models/Messages.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/app/threads/server/functions.js
  apps/meteor/app/threads/server/hooks/aftersavemessage.js
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/getThreadsList.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/ee/app/message-read-receipt/server/hooks/afterReadMessages.ts
  apps/meteor/ee/app/message-read-receipt/server/hooks/afterSaveMessage.ts
  apps/meteor/ee/server/lib/message-read-receipt/ReadReceipt.js
  apps/meteor/ee/server/local-services/message-reads/service.ts
  apps/meteor/server/methods/deleteFileMessage.ts
  apps/meteor/server/models/raw/Messages.ts
  packages/model-typings/src/models/IMessagesModel.ts
Labels: stat: needs QA

#28568 Release 6.0.1
  .github/history.json
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/file-upload/server/lib/FileUpload.js
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/client/views/admin/cloud/ManualWorkspaceRegistrationModal.tsx
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageListScrolling.ts
  apps/meteor/ee/server/apps/communication/rest.js
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/federation/tests/messaging/dm.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/private.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/public.spec.ts
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  package.json
  packages/gazzodown/src/blocks/ParagraphBlock.tsx
  yarn.lock
Labels: stat: needs QA

#28566 refactor: Allow RoomCoordinator.roomFind to be async
  apps/meteor/definition/IRoomTypeConfig.ts
  apps/meteor/server/publications/room/index.ts
Labels: stat: ready to merge, stat: QA skipped

#28564 refactor: convert omnichannel callbacks to ts
  apps/meteor/app/livechat/server/methods/getDepartmentForwardRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/addDepartmentAncestors.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterForwardChatToDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeForwardRoomToDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeListTags.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewRoom.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCheckRoomParamsApi.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCloseLivechat.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCloseLivechat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadConfigApi.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadConfigApi.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadForwardDepartmentRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onSaveVisitorInfo.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/setPredictedVisitorAbandonmentTime.ts
  apps/meteor/lib/callbacks.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
Labels: stat: needs QA
