Repository RocketChat/Rocket.Chat, pull requests merged in 2023-12, with the labels that each got.

#31125 chore: fix invalid auth
  .github/workflows/ci.yml
  apps/meteor/client/lib/utils/isOverLicenseLimits.ts
Labels: stat: needs QA

#31126 test: created tests to max limit -1/0 and License.remove
  ee/packages/license/src/license.spec.ts
  ee/packages/license/src/validation/validateLicenseLimits.spec.ts
Labels: stat: needs QA

#31127 chore: get right type from supported version
  apps/meteor/packages/rocketchat-version/plugin/compile-version.js
Labels: stat: needs QA

#30623 feat: Image gallery with swiper
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.js
  apps/meteor/app/theme/client/main.css
  apps/meteor/app/theme/client/vendor/photoswipe.css
  apps/meteor/app/ui/client/index.ts
  apps/meteor/app/ui/client/views/app/photoswipeContent.ts
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
  apps/meteor/client/components/ImageGallery/ImageGalleryLoader.tsx
  apps/meteor/client/components/ImageGallery/hooks/useImageGallery.ts
  apps/meteor/client/components/ImageGallery/hooks/useImagesList.ts
  apps/meteor/client/components/ImageGallery/index.ts
  apps/meteor/client/components/message/content/Attachments.tsx
  apps/meteor/client/components/message/content/attachments/AttachmentsItem.tsx
  apps/meteor/client/components/message/content/attachments/FileAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/ImageAttachment.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentImage.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/contexts/ImageGalleryContext.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/lib/lists/ImagesList.ts
  apps/meteor/client/providers/ImageGalleryProvider.tsx
  apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItem.js
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/ImageItem.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useFilesList.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/package.json
  apps/meteor/server/models/raw/Uploads.ts
  packages/model-typings/src/models/IUploadsModel.ts
  packages/rest-typings/src/v1/channels/ChannelsImagesProps.ts
  packages/rest-typings/src/v1/channels/channels.ts
  packages/rest-typings/src/v1/channels/index.ts
  yarn.lock
Labels: stat: needs QA

#31113 fix: Discussion messages deleted despite the "Do not delete discussion messages" retention policy enabled
  .changeset/fifty-ducks-sing.md
  apps/meteor/app/retention-policy/server/cronPruneMessages.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30339 chore: rocketchat:coverage package
  .github/actions/meteor-build/action.yml
  .github/workflows/ci-test-e2e.yml
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-coverage/.npm/package/.gitignore
  apps/meteor/packages/rocketchat-coverage/.npm/package/README
  apps/meteor/packages/rocketchat-coverage/.npm/package/npm-shrinkwrap.json
  apps/meteor/packages/rocketchat-coverage/package.js
  apps/meteor/packages/rocketchat-coverage/plugin/compile-version.js
  codecov.yml
  docker-compose-ci.yml
Labels: stat: needs QA

#31139 i18n: Fixed all German translation handlebar errors
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31153 fix: New `custom-roles` license module isn't properly checked
  .changeset/fresh-radios-whisper.md
  apps/meteor/client/views/admin/permissions/EditRolePage.tsx
  apps/meteor/client/views/admin/permissions/EditRolePageWithData.tsx
  apps/meteor/client/views/admin/permissions/PermissionsContextBar.tsx
  apps/meteor/ee/server/api/roles.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31159 chore: ImageGallery tweaks
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
  apps/meteor/client/components/ImageGallery/ImageGalleryLoader.tsx
Labels: stat: needs QA

#30789 chore: Replace `useForm` in favor of RHF on Omnichannel `AgentsEdit`
  apps/meteor/client/views/omnichannel/additionalForms.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEditWithData.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoActions.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTab.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTableRow.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/RemoveAgentButton.tsx
  apps/meteor/client/views/omnichannel/agents/hooks/useRemoveAgent.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/MaxChatsPerAgent.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/MaxChatsPerAgentContainer.js
  apps/meteor/ee/client/omnichannel/additionalForms/MaxChatsPerAgentDisplay.tsx
  packages/core-typings/src/ILivechatAgent.ts
Labels: stat: ready to merge, stat: QA skipped

#30680 feat: Skip to main content shortcut and `useDocumentTitle`
  .changeset/kind-beers-share.md
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/sidebar/Item/Condensed.tsx
  apps/meteor/client/sidebar/Item/Extended.tsx
  apps/meteor/client/sidebar/Item/Medium.tsx
  apps/meteor/client/startup/unread.ts
  apps/meteor/client/views/directory/DirectoryPage.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTable.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTable.tsx
  apps/meteor/client/views/directory/tabs/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/home/cards/CustomContentCard.tsx
  apps/meteor/client/views/room/Header/RoomTitle.tsx
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/DocumentTitleWrapper.tsx
  apps/meteor/client/views/root/MainLayout/AccessibilityShortcut.tsx
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
  apps/meteor/client/views/root/hooks/useUnreadMessages.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/homepage.spec.ts
  packages/ui-client/src/hooks/useDocumentTitle.spec.ts
  packages/ui-client/src/hooks/useDocumentTitle.ts
  packages/ui-client/src/index.ts
  packages/web-ui-registration/src/GuestForm.tsx
  packages/web-ui-registration/src/LoginForm.tsx
  packages/web-ui-registration/src/RegisterSecretPageRouter.tsx
  packages/web-ui-registration/src/ResetPasswordForm.tsx
Labels: stat: needs QA

#31013 docs: fix lost image render in markdown
  packages/livechat/README.md
Labels: communityPR, stat: QA skipped

#30868 feat: Add `push.info` endpoint to retrieve push gateway info
  .changeset/fifty-maps-deny.md
  apps/meteor/app/api/server/v1/push.ts
  packages/rest-typings/src/v1/push.ts
Labels: stat: ready to merge, stat: QA tested

#31051 refactor: Migrate `analytics.js` to service
  apps/meteor/app/livechat/imports/server/rest/dashboards.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/app/livechat/server/lib/Analytics.js
  apps/meteor/app/livechat/server/lib/AnalyticsTyped.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/analytics/dashboards.ts
  apps/meteor/app/livechat/server/methods/getAgentOverviewData.ts
  apps/meteor/app/livechat/server/methods/getAnalyticsChartData.ts
  apps/meteor/app/livechat/server/methods/getAnalyticsOverviewData.ts
  apps/meteor/server/services/omnichannel-analytics/AgentData.ts
  apps/meteor/server/services/omnichannel-analytics/ChartData.ts
  apps/meteor/server/services/omnichannel-analytics/OverviewData.ts
  apps/meteor/server/services/omnichannel-analytics/logger.ts
  apps/meteor/server/services/omnichannel-analytics/service.ts
  apps/meteor/server/services/omnichannel-analytics/utils.ts
  apps/meteor/server/services/startup.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/unit/server/services/omnichannel-analytics/AgentData.tests.ts
  apps/meteor/tests/unit/server/services/omnichannel-analytics/ChartData.tests.ts
  apps/meteor/tests/unit/server/services/omnichannel-analytics/OverviewData.tests.ts
  apps/meteor/tests/unit/server/services/omnichannel-analytics/mockData.ts
  packages/core-services/src/index.ts
  packages/core-services/src/types/IOmnichannelAnalyticsService.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31025 chore: send streaming msg update on livechat decline call event
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#31094 chore: add a manual msg stream update for autotranslate
  apps/meteor/app/autotranslate/server/autotranslate.ts
Labels: stat: needs QA

#31098 chore: update editedBy when the user changes their username
  apps/meteor/client/startup/notifications/usersNameChanged.ts
Labels: stat: needs QA

#31105 chore: add msg stream to the federation v1 feature
  apps/meteor/app/federation/server/endpoints/dispatch.js
Labels: stat: needs QA

#30925 chore: notify messages on emails incoming and outgoing
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
Labels: stat: needs QA

#31179 refactor: Remove `livechat.js` file
  apps/meteor/app/livechat/client/ui.ts
  apps/meteor/app/livechat/imports/server/rest/sms.js
  apps/meteor/app/livechat/server/api/v1/webhooks.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/getAgentOverviewData.ts
  apps/meteor/app/livechat/server/methods/getAnalyticsChartData.ts
  apps/meteor/app/livechat/server/methods/getAnalyticsOverviewData.ts
  apps/meteor/app/livechat/server/methods/removeAllClosedRooms.ts
  apps/meteor/app/livechat/server/startup.ts
Labels: stat: ready to merge, automerge, stat: QA skipped, squad: omnichannel

#31186 chore: Rename useFileInput to useSingleFileInput
  apps/meteor/client/components/avatar/RoomAvatarEditor.tsx
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.tsx
  apps/meteor/client/hooks/useSingleFileInput.ts
  apps/meteor/client/views/admin/customEmoji/AddCustomEmoji.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx
  apps/meteor/client/views/admin/customSounds/AddCustomSound.tsx
  apps/meteor/client/views/admin/customSounds/EditSound.tsx
  apps/meteor/client/views/marketplace/AppInstallPage.js
Labels: stat: ready to merge, stat: QA skipped

#31101 chore: convert jumpToMessage callback to class
  apps/meteor/app/lib/server/functions/parseUrlsInMessage.ts
  apps/meteor/app/oembed/server/index.ts
  apps/meteor/app/oembed/server/jumpToMessage.ts
  apps/meteor/server/services/messages/hooks/BeforeSaveJumpToMessage.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveJumpToMessage.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#31187 refactor: move final server files to typescript
  apps/meteor/app/livechat/imports/server/rest/sms.ts
  apps/meteor/app/livechat/server/api.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/analytics/agents.ts
  apps/meteor/app/livechat/server/lib/analytics/dashboards.ts
  apps/meteor/app/livechat/server/lib/analytics/departments.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/agents.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/departments.ts
  apps/meteor/server/models/raw/LivechatAgentActivity.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/server/models/raw/Messages.ts
  packages/model-typings/src/models/ILivechatAgentActivityModel.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/model-typings/src/models/IMessagesModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30913 fix: initial stuck client if root_url is wrong
  apps/meteor/server/startup/initialData.js
Labels: stat: needs QA

#31185 fix: Registration Data
  apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
  apps/meteor/client/views/setupWizard/providers/SetupWizardProvider.tsx
  apps/meteor/server/cron/statistics.ts
  apps/meteor/server/settings/general.ts
Labels: stat: needs QA

#31198 fix: typo error in livechat.applySimultaneousChatRestrictions hook
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applySimultaneousChatsRestrictions.ts
Labels: stat: ready to merge, stat: QA skipped

#31168 chore: Add Project File for Sublime Text
  .gitignore
  .sublime-project
Labels: stat: needs QA

#31206 chore: rename sublime project file
  Rocket.Chat.sublime-project
Labels: stat: needs QA

#31204 fix: Remove non-monitor users from monitors list before saving unit
  .changeset/chilled-mails-greet.md
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31210 fix: Use proper key for init departmentagents model
  apps/meteor/ee/server/models/LivechatDepartmentAgents.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31209 fix: Show busiest time in timezone instead of UTC
  .changeset/spotty-bulldogs-fly.md
  apps/meteor/server/services/omnichannel-analytics/OverviewData.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31213 fix: Gallery not working inside threads
  apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
Labels: stat: ready to merge, stat: QA skipped

#31196 chore: improved agents e2e tests
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoAction.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTableRow.tsx
  apps/meteor/client/views/omnichannel/agents/hooks/useRemoveAgent.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
Labels: stat: QA skipped, squad: omnichannel

#30823 chore: refactored departments e2e tests
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/RemoveDepartmentModal.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-departaments-ce.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31190 chore: implemented chat transfer e2e tests
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-chat-transfers.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-transfer-chat-modal.ts
  apps/meteor/tests/e2e/utils/omnichannel/managers.ts
  apps/meteor/tests/e2e/utils/omnichannel/rooms.ts
Labels: stat: QA skipped, squad: omnichannel

#31205 fix: Wrong sysmessage when resuming chat from on hold
  .changeset/loud-planes-sneeze.md
  apps/meteor/ee/app/livechat-enterprise/server/api/rooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/resumeOnHold.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/end-to-end/api/livechat/18-rooms-ee.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31181 fix: Notifications for thread messages are sent even after thread has been read
  .changeset/calm-rules-dance.md
  apps/meteor/app/threads/server/functions.ts
  apps/meteor/server/methods/readThreads.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31223 fix: Wrong `Message Roundtrip Time` metric
  .changeset/new-avocados-sort.md
  apps/meteor/app/metrics/server/lib/metrics.ts
  apps/meteor/server/services/meteor/service.ts
Labels: stat: ready to merge, stat: QA skipped

#31217 refactor: `Conversations` Overview Analytics
  apps/meteor/server/services/omnichannel-analytics/OverviewData.ts
  apps/meteor/server/services/omnichannel-analytics/utils.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/unit/server/services/omnichannel-analytics/OverviewData.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#31182 chore: `Field` normalization
  apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
  apps/meteor/client/views/account/accessibility/AccessibilityPage.tsx
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.tsx
  apps/meteor/client/views/account/omnichannel/PreferencesConversationTranscript.tsx
  apps/meteor/client/views/account/omnichannel/PreferencesGeneral.tsx
  apps/meteor/client/views/account/preferences/PreferencesMessagesSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesNotificationsSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesSoundSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesUserPresenceSection.tsx
  apps/meteor/client/views/account/tokens/AccountTokensTable/AddToken.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxForm.tsx
  apps/meteor/client/views/admin/integrations/incoming/IncomingWebhookForm.tsx
  apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx
  apps/meteor/client/views/admin/mailer/MailerPage.tsx
  apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx
  apps/meteor/client/views/admin/oauthApps/OAuthAddApp.tsx
  apps/meteor/client/views/admin/permissions/RoleForm.tsx
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/settings/ResetSettingButton.tsx
  apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepOneModal.tsx
  apps/meteor/client/views/admin/workspace/WorkspaceRoute.tsx
  apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx
  apps/meteor/client/views/omnichannel/customFields/EditCustomFields.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentTags.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/client/views/omnichannel/triggers/EditTrigger.tsx
  apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslate.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearchForm.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/components/NotificationToggle.tsx
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessages.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/CustomFieldsAdditionalForm.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentBusinessHours.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/EeNumberInput.js
  apps/meteor/ee/client/omnichannel/additionalForms/EeNumberInput.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/EeTextAreaInput.js
  apps/meteor/ee/client/omnichannel/additionalForms/EeTextAreaInput.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/EeTextInput.js
  apps/meteor/ee/client/omnichannel/additionalForms/EeTextInput.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/page-objects/admin-email-inboxes.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31231 refactor: convert MAC check callback to class
  apps/meteor/app/livechat/server/hooks/checkMAC.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/server/services/messages/hooks/BeforeSaveCheckMAC.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/mocks/server/BrokerMocked.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveCheckMAC.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#31215 fix: image disappearing with new message
  apps/meteor/client/components/ImageGallery/hooks/useImagesList.ts
Labels: stat: needs QA

#31228 fix: file type filter not working on room's file list
  .changeset/violet-pears-cry.md
  apps/meteor/server/models/raw/Uploads.ts
Labels: stat: ready to merge, stat: QA skipped

#30691 chore: Refactor RoomFiles to typescript
  apps/meteor/client/views/room/contextualBar/RoomFiles/RoomFiles.stories.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/RoomFiles.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/RoomFilesWithData.js
  apps/meteor/client/views/room/contextualBar/RoomFiles/RoomFilesWithData.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/Row.js
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItem.stories.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItem.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItemIcon.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItemMenu.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/ImageItem.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/MenuItem.js
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useDeleteFile.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useMessageDeletionIsAllowed.js
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useMessageDeletionIsAllowed.ts
  apps/meteor/client/views/room/contextualBar/RoomFiles/lib/getDifference.js
  apps/meteor/client/views/room/contextualBar/RoomFiles/lib/getDifference.ts
  packages/core-typings/src/IUpload.ts
  packages/rest-typings/src/v1/channels/channels.ts
  packages/rest-typings/src/v1/dm/im.ts
  packages/rest-typings/src/v1/groups/groups.ts
Labels: stat: needs QA

#31219 chore: Use `MessageComposer` on Canned Responses message field
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposer.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/CannedResponsesComposer/CannedResponsesComposerPreview.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/CannedResponsesComposer/InsertPlaceholderDropdown.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/MarkdownTextEditor/MarkdownTextEditor.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/PreviewText.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/IconButton.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/TextButton.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/TextEditor.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/Textarea.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/Toolbox.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/index.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerInput.tsx
Labels: stat: ready to merge, stat: QA skipped

#31236 regression: `ResetButton` misaligned on `BooleanSettingInput`
  apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
Labels: stat: needs QA

#31242 chore: `Usercard` small visual changes
  apps/meteor/client/components/UserCard/UserCard.tsx
Labels: stat: ready to merge, stat: QA skipped

#31118 chore: omnichannel improved e2e tests
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ReturnChatQueueModal.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoAction.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTableRow.tsx
  apps/meteor/client/views/omnichannel/agents/hooks/useRemoveAgent.tsx
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/currentChats/RemoveChatButton.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/RemoveDepartmentModal.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
  apps/meteor/ee/app/livechat-enterprise/client/components/modals/PlaceChatOnHoldModal.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx
  apps/meteor/ee/client/omnichannel/monitors/MonitorsTable.tsx
  apps/meteor/ee/client/omnichannel/units/UnitEdit.tsx
  apps/meteor/ee/client/omnichannel/units/UnitsTable.tsx
  apps/meteor/ee/client/omnichannel/units/useRemoveUnit.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-chat-transfers.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-close-inquiry.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-current-chats.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-custom-fields.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-departaments-ce.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-manager-role.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-manual-selection.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-monitor-role.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-monitors.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-priorities-sidebar.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-takeChat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
  apps/meteor/tests/e2e/page-objects/home-omnichannel.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-administration.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-canned-responses.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-current-chats.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-monitors.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-transfer-chat-modal.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-units.ts
  apps/meteor/tests/e2e/utils/omnichannel/agents.ts
  apps/meteor/tests/e2e/utils/omnichannel/departments.ts
  apps/meteor/tests/e2e/utils/omnichannel/managers.ts
  apps/meteor/tests/e2e/utils/omnichannel/monitors.ts
  apps/meteor/tests/e2e/utils/omnichannel/rooms.ts
  apps/meteor/tests/e2e/utils/omnichannel/tags.ts
  apps/meteor/tests/e2e/utils/omnichannel/units.ts
  apps/meteor/tests/e2e/utils/omnichannel/utils.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31164 fix: mobile users receives two push notifications when a direct call is started
  .changeset/spotty-suns-grin.md
  apps/meteor/app/lib/server/functions/notifications/mobile.js
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
  apps/meteor/server/lib/isRoomCompatibleWithVideoConfRinging.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: ready to merge, stat: QA tested

#31244 chore: Replace `useForm` in favor of RHF on AppSettings
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
  apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/CodeSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/ColorSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/FontSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/GenericSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/IntSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/LanguageSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/LookupSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/MultiSelectSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/PasswordSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/RelativeUrlSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/RoomPickSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/SelectSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/SelectTimezoneSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/StringSettingInput.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppSettings/AppSetting.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppSettings/AppSettings.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppSettings/AppSettingsAssembler.tsx
Labels: stat: ready to merge, stat: QA skipped

#31224 refactor: convert markdown parser callback
  apps/meteor/server/hooks/index.ts
  apps/meteor/server/hooks/messages/markdownParser.ts
  apps/meteor/server/services/messages/hooks/BeforeSaveMarkdownParser.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveMarkdownParser.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#31235 fix: stop refetching banner data
  .changeset/gold-stingrays-compete.md
  apps/meteor/client/views/cloud/CloudAnnouncementsRegion.tsx
Labels: stat: needs QA

#31243 chore: use `findOneAndUpdate` from `BaseRaw` in all places
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/models/raw/NotificationQueue.ts
  apps/meteor/server/models/raw/Nps.ts
  apps/meteor/server/models/raw/Users.js
  apps/meteor/server/services/nps/service.ts
Labels: stat: ready to merge, stat: QA skipped

#30464 feat: Bot warning when mentioning users not in a channel
  .changeset/fresh-socks-fix.md
  apps/meteor/app/lib/server/index.ts
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
  apps/meteor/app/lib/server/startup/mentionUserNotInChannel.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/modules/core-apps/mention.module.ts
  apps/meteor/server/startup/coreApps.ts
  apps/meteor/tests/e2e/message-mentions.spec.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31134 fix: connected users search on spotlight for user mentions
  .changeset/pretty-eyes-sleep.md
  apps/meteor/server/lib/spotlight.js
Labels: stat: ready to merge, stat: QA tested

#31247 chore: Add slide window config to round trip metric
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/metrics/server/lib/metrics.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#31229 ci: collect coverage in any branch except for releases
  .github/actions/meteor-build/action.yml
  .github/workflows/ci.yml
Labels: stat: needs QA

#31211 refactor: convert canned response callback
  apps/meteor/ee/app/canned-responses/server/hooks/cannedResponses.ts
  apps/meteor/ee/app/canned-responses/server/hooks/onMessageSentParsePlaceholder.ts
  apps/meteor/ee/app/canned-responses/server/index.ts
  apps/meteor/ee/server/hooks/messages/BeforeSaveCannedResponse.ts
  apps/meteor/ee/tests/unit/server/hooks/messages/BeforeSaveCannedResponse.tests.ts
  apps/meteor/server/services/messages/service.ts
Labels: stat: ready to merge, stat: QA skipped

#31245 chore: Remove deprecated `useForm`
  apps/meteor/client/hooks/useForm.ts
Labels: stat: ready to merge, stat: QA skipped

#31227 fix: account verify email
  .changeset/tame-drinks-yell.md
  apps/meteor/app/2fa/server/loginHandler.ts
  apps/meteor/client/main.ts
  apps/meteor/client/startup/accounts.ts
  apps/meteor/client/startup/index.ts
Labels: stat: ready to merge, stat: QA tested

#31254 fix: Sending messages triggering stream unsub/sub
  apps/meteor/client/views/room/body/hooks/useGoToHomeOnRemoved.ts
Labels: stat: ready to merge, stat: QA skipped

#31263 chore: move `mention-user-not-in-channel` to afterSaveMessage
  apps/meteor/app/lib/server/startup/mentionUserNotInChannel.ts
Labels: stat: ready to merge, stat: QA skipped

#31188 chore: stop using callbacks for parsing mentions on messages
  apps/meteor/app/importer-slack/server/SlackImporter.ts
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/mentions/lib/MentionsParser.js
  apps/meteor/app/mentions/lib/MentionsParser.ts
  apps/meteor/app/mentions/server/Mentions.js
  apps/meteor/app/mentions/server/Mentions.ts
  apps/meteor/app/mentions/server/index.ts
  apps/meteor/app/threads/client/lib/normalizeThreadTitle.ts
  apps/meteor/client/components/GazzodownText.tsx
  apps/meteor/server/services/messages/hooks/BeforeSaveMentions.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/unit/app/mentions/client.tests.js
  apps/meteor/tests/unit/app/mentions/server.tests.js
  packages/core-typings/src/IMessage/IMessage.ts
  packages/gazzodown/src/MarkupInteractionContext.ts
Labels: stat: QA skipped

#31269 fix: Resolved Search List Issue when pressing ENTER
  .changeset/forty-adults-kneel.md
  apps/meteor/client/sidebar/search/SearchList.tsx
Labels: stat: ready to merge, stat: QA skipped

#31266 regression: `PageHeader` back button must be an `IconButton`
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxPage.tsx
  apps/meteor/client/views/admin/import/NewImportPage.tsx
  apps/meteor/client/views/admin/import/PrepareImportPage.tsx
  apps/meteor/client/views/admin/integrations/incoming/EditIncomingWebhook.tsx
  apps/meteor/client/views/admin/integrations/outgoing/EditOutgoingWebhook.tsx
  apps/meteor/client/views/admin/integrations/outgoing/history/OutgoingWebhookHistoryPage.tsx
  apps/meteor/client/views/admin/oauthApps/OAuthAppsPage.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEdit.tsx
Labels: stat: ready to merge, stat: QA skipped

#31274 chore: Login api types
  packages/rest-typings/src/v1/auth.ts
Labels: stat: ready to merge, stat: QA skipped

#31253 fix: start workspace pt-br translation not showing correctly on register page
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/gl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#31273 chore: remove `beforeSaveMessage` callback
  apps/meteor/app/lib/client/methods/sendMessage.ts
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/client/methods/updateMessage.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: QA skipped

#31278 fix: SDK login methods not saving token
  .changeset/real-items-tan.md
  ee/packages/ddp-client/src/DDPSDK.ts
  ee/packages/ddp-client/src/types/Account.ts
Labels: stat: needs QA

#31237 fix: Store custom status in localStorage
  apps/meteor/client/sidebar/header/EditStatusModal.tsx
Labels: stat: QA tested

#31277 fix: Can't create public channels with joinCode
  .changeset/thick-nails-explode.md
  apps/meteor/client/views/room/composer/ComposerContainer.tsx
  apps/meteor/client/views/room/composer/ComposerJoinWithPassword.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
Labels: stat: ready to merge, stat: QA skipped

#31264 fix: Fix wrong callback usage on after/before user actions
  .changeset/sour-kids-heal.md
  apps/meteor/ee/app/authorization/server/callback.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31282 chore: Update "Proposed changes" PR template's section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: stat: QA skipped

#31295 chore: Show `BusinessHourDisabledPage` when setting is disabled
  apps/meteor/client/views/omnichannel/businessHours/BusinessHoursDisabledPage.tsx
  apps/meteor/client/views/omnichannel/businessHours/BusinessHoursRouter.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#31297 fix: Remove trial param from checking cancel subscription button
  .changeset/lucky-apricots-change.md
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
Labels: stat: needs QA

#31288 fix: toolbox submenu not being displayed in small resolutions
  .changeset/green-turkeys-fry.md
  apps/meteor/client/views/room/Header/RoomToolbox/RoomToolbox.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31294 fix: Wrong "Open" translation in portuguese
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31301 refactor: SDK reconnection resume login attempt
  ee/packages/ddp-client/src/DDPSDK.ts
  ee/packages/ddp-client/src/types/Account.ts
Labels: stat: needs QA

#31287 fix: Avoid creating a visitor when `token` is an empty string
  .changeset/thin-socks-brush.md
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31298 test: Add unit tests to SDK account
  ee/packages/ddp-client/__tests__/Account.spec.ts
  ee/packages/ddp-client/__tests__/Connection.spec.ts
  ee/packages/ddp-client/__tests__/DDPSDK.spec.ts
  ee/packages/ddp-client/__tests__/helpers/index.ts
  ee/packages/ddp-client/src/ClientStream.ts
Labels: stat: needs QA

#31208 fix(otr): exceeding API calls when sending OTR messages
  .changeset/popular-beds-heal.md
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/otr/client/OTR.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/otr/lib/IOTR.ts
  apps/meteor/app/otr/server/methods/updateOTRAck.ts
  apps/meteor/client/components/message/StatusIndicators.tsx
  apps/meteor/client/hooks/roomActions/useOTRRoomAction.ts
  apps/meteor/client/lib/parseMessageTextToAstMarkdown.ts
  apps/meteor/client/lib/utils/getUidDirectMessage.ts
  apps/meteor/client/startup/otr.ts
  apps/meteor/client/views/room/contextualBar/OTR/OTRWithData.tsx
  apps/meteor/server/hooks/messages/markdownParser.ts
  apps/meteor/server/services/video-conference/service.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: needs QA

#31303 chore: Add missing changesets
  .changeset/remove-license-31189.md
  .changeset/resume-login-31301.md
  .changeset/save-token-31278.md
Labels: stat: needs QA

#31305 fix: country select
  .changeset/lucky-cycles-leave.md
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#31299 fix: Loading state for `Marketplace` related lists
  .changeset/late-pots-travel.md
  apps/meteor/client/contexts/AppsContext.tsx
  apps/meteor/client/providers/AppsProvider.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContentBody.tsx
  apps/meteor/client/views/marketplace/hooks/useFilteredApps.ts
Labels: stat: ready to merge, stat: QA tested, squad: apps-engine

#31312 fix: Language selection box is empty which should be default
  .changeset/chilled-cooks-end.md
  apps/meteor/client/views/account/preferences/useAccountPreferencesValues.ts
Labels: stat: ready to merge, stat: QA skipped

#31292 fix: Displaying wrong composer for archived room
  .changeset/thin-chairs-clean.md
  apps/meteor/client/views/room/composer/ComposerArchived.tsx
  apps/meteor/client/views/room/composer/ComposerContainer.tsx
  apps/meteor/client/views/room/composer/hooks/useMessageComposerIsArchived.ts
  apps/meteor/client/views/room/composer/hooks/useMessageComposerIsReadOnly.ts
Labels: stat: ready to merge, stat: QA tested

#30967 test: Livechat widget API Tests
  apps/meteor/client/views/omnichannel/directory/components/ContactField.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.tsx
  apps/meteor/packages/rocketchat-livechat/assets/demo.html
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-manager-role.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts
  packages/livechat/src/widget.js
Labels: stat: ready to merge, stat: QA skipped

#31267 fix: inquiries being limited to 50 items
  .changeset/three-moles-look.md
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31296 fix: Fallback forward department not working as expected on chat forwarding
  .changeset/eight-windows-report.md
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31302 fix: Show only departments that are allowed on registration page on livechat widget
  .changeset/three-steaks-cry.md
  packages/livechat/src/routes/Register/index.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31281 feat: Highlight words in thread messages
  .changeset/brave-shrimps-marry.md
  apps/meteor/app/lib/server/functions/notifications/desktop.ts
  apps/meteor/app/lib/server/functions/notifications/email.js
  apps/meteor/app/lib/server/functions/notifications/mobile.js
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.js
  apps/meteor/app/threads/server/functions.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31087 chore: add new msg stream for reported msgs
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/client/hooks/lists/useStreamUpdatesForMessageList.ts
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts
  apps/meteor/server/lib/moderation/deleteReportedMessages.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/events/Events.ts
Labels: stat: needs QA

#31326 refactor: unify useStream and useSingleStream
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/hooks/useAppSlashCommands.ts
  apps/meteor/client/hooks/useLicense.ts
  apps/meteor/client/hooks/useTranslationsForApps.ts
  apps/meteor/client/providers/AppsProvider.tsx
  apps/meteor/client/providers/ServerProvider.tsx
  apps/meteor/tests/mocks/client/ServerProviderMock.tsx
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/hooks/useVideoConfDataStream.ts
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/ui-contexts/src/ServerContext/ServerContext.ts
  packages/ui-contexts/src/hooks/useStream.ts
  packages/ui-contexts/src/index.ts
Labels: stat: needs QA

#31335 chore: `Card` normalization
  apps/meteor/client/components/GenericCard/GenericCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardPremium.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/components/VersionCardActionItem.tsx
  apps/meteor/client/views/admin/workspace/components/WorkspaceCardSection.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/AppsList/AppRow.tsx
  apps/meteor/client/views/marketplace/AppsList/AppsList.tsx
  apps/meteor/ee/client/components/dashboards/DownloadDataButton.tsx
  apps/meteor/ee/client/omnichannel/reports/components/ReportCard.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardCardFilter.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: needs QA

#31272 chore: remove Messages model dependency of Rooms model
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/services/messages/service.ts
  packages/model-typings/src/models/IRoomsModel.ts
Labels: stat: ready to merge, stat: QA skipped

#30996 chore: adapt read receipts feature to work without oplog on msgs
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/ee/server/lib/message-read-receipt/ReadReceipt.js
  apps/meteor/ee/server/local-services/message-reads/service.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/events/Events.ts
Labels: stat: needs QA

#31063 chore: adding new streamer event for imported messages
  apps/meteor/app/importer-pending-files/server/PendingFileImporter.ts
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/importer/server/classes/Importer.ts
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/events/Events.ts
Labels: stat: ready to merge, stat: QA skipped
