Repository RocketChat/Rocket.Chat, pull requests merged in 2023-02, with the labels that each got.

#27911 [FIX] Reduce re-subscription on `notify-room/user-activity` stream event
  apps/meteor/client/views/room/providers/RoomProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#27725 [FIX] Support the whole Matrix Markdown spec
  apps/meteor/app/federation-v2/server/application/RoomServiceListener.ts
  apps/meteor/app/federation-v2/server/application/input/RoomReceiverDto.ts
  apps/meteor/app/federation-v2/server/infrastructure/Factory.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/converters/MessageReceiver.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/converters/MessageTextParser.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/converters/RoomReceiver.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/handlers/Room.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/adapters/Message.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/converters/MessageTextParser.ts
  apps/meteor/ee/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/package.json
  apps/meteor/tests/unit/app/federation-v2/server/unit/application/RoomServiceListener.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/matrix/converters/MatrixTextParser.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/matrix/converters/RoomReceiver.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/matrix/handlers/Room.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/rocket-chat/converters/RocketTextParser.spec.ts
  yarn.lock
Labels: type: bug, feat: federation, stat: needs QA

#27559 [FIX] Allow federated rooms with the same name per servers
  apps/meteor/app/channel-settings/server/functions/saveRoomName.js
  apps/meteor/app/federation-v2/server/application/RoomServiceListener.ts
  apps/meteor/app/federation-v2/server/domain/FederatedRoom.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/converters/RoomReceiver.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/definitions/MatrixEventType.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/definitions/MatrixRoomVisibility.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/adapters/Room.ts
  apps/meteor/app/mentions/server/server.js
  apps/meteor/app/models/server/models/Rooms.js
  apps/meteor/app/ui-message/client/popup/messagePopupChannel.html
  apps/meteor/app/ui-message/client/popup/messagePopupChannel.js
  apps/meteor/app/ui-message/client/popup/messagePopupConfig.js
  apps/meteor/client/components/avatar/RoomAvatarEditor.tsx
  apps/meteor/client/lib/rooms/roomTypes/direct.ts
  apps/meteor/client/lib/rooms/roomTypes/private.ts
  apps/meteor/client/lib/rooms/roomTypes/public.ts
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/startup/mergeSubscriptionsAndRooms.ts
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/client/views/room/Header/FederatedRoomOriginServer.tsx
  apps/meteor/client/views/room/Header/RoomHeader.tsx
  apps/meteor/client/views/room/contexts/RoomContext.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/ee/app/federation-v2/server/application/sender/room/RoomInternalHooksServiceSender.ts
  apps/meteor/ee/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/lib/rooms/adminFields.ts
  apps/meteor/server/lib/rooms/roomTypes/private.ts
  apps/meteor/server/lib/rooms/roomTypes/public.ts
  apps/meteor/server/lib/spotlight.js
  apps/meteor/server/methods/browseChannels.js
  apps/meteor/server/models/raw/Rooms.js
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/server/publications/spotlight.js
  apps/meteor/server/routes/avatar/room.js
  apps/meteor/tests/unit/app/federation-v2/server/unit/application/RoomServiceListener.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/domain/FederatedRoom.spec.ts
  packages/model-typings/src/models/IRoomsModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: type: bug, feat: federation, stat: needs QA

#27327 [FIX] Matrix Federation send message when multiple users are involved was not working
  apps/meteor/app/federation-v2/server/application/RoomServiceListener.ts
  apps/meteor/app/federation-v2/server/application/input/RoomReceiverDto.ts
  apps/meteor/app/federation-v2/server/domain/IFederationBridge.ts
  apps/meteor/app/federation-v2/server/index.ts
  apps/meteor/app/federation-v2/server/infrastructure/Factory.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/Bridge.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/converters/RoomReceiver.ts
  apps/meteor/app/federation-v2/server/infrastructure/matrix/definitions/events/RoomCreated.ts
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/methods/addUsersToRoom.js
  apps/meteor/ee/app/federation-v2/server/application/sender/room/DMRoomInternalHooksServiceSender.ts
  apps/meteor/ee/app/federation-v2/server/application/sender/room/RoomInternalHooksServiceSender.ts
  apps/meteor/ee/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/ee/tests/unit/app/federation-v2/server/application/DMRoomInternalHooksServiceSender.spec.ts
  apps/meteor/ee/tests/unit/app/federation-v2/server/application/RoomInternalHooksServiceSender.spec.ts
  apps/meteor/ee/tests/unit/app/federation-v2/server/infrastructure/rocket-chat/hooks/hooks.spec.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/application/RoomServiceListener.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/matrix/converters/RoomReceiver.spec.ts
  apps/meteor/tests/unit/app/federation-v2/server/unit/infrastructure/rocket-chat/hooks/hooks.spec.ts
Labels: feat: federation, stat: needs QA

#27115 Chore: Federation e2e tests for channels
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
  apps/meteor/package.json
  apps/meteor/playwright-federation.config.ts
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/federation/README.md
  apps/meteor/tests/e2e/federation/channel/dm.spec.ts
  apps/meteor/tests/e2e/federation/channel/private.spec.ts
  apps/meteor/tests/e2e/federation/channel/public.spec.ts
  apps/meteor/tests/e2e/federation/config/constants.ts
  apps/meteor/tests/e2e/federation/config/global-setup.ts
  apps/meteor/tests/e2e/federation/page-objects/channel.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-channels.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-dm-member.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-members.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-notificationPreferences.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/federation/utils/auth.ts
  apps/meteor/tests/e2e/federation/utils/channel.ts
  apps/meteor/tests/e2e/federation/utils/format.ts
  apps/meteor/tests/e2e/federation/utils/register-user.ts
  apps/meteor/tests/e2e/federation/utils/test.ts
Labels: feat: federation, subj: testing, stat: needs QA

#27929 [FIX][ENTERPRISE] DDP streamer sending data to destroyed streams
  ee/apps/ddp-streamer/src/Server.ts
  ee/apps/ddp-streamer/src/Streamer.ts
Labels: stat: ready to merge, stat: QA skipped

#27282 Chore: Federation E2E tests for messaging + admin
  apps/meteor/playwright-federation.config.ts
  apps/meteor/tests/e2e/federation/files/test_image.jpeg
  apps/meteor/tests/e2e/federation/files/test_pdf_file.pdf
  apps/meteor/tests/e2e/federation/files/test_video.mp4
  apps/meteor/tests/e2e/federation/page-objects/account-profile.ts
  apps/meteor/tests/e2e/federation/page-objects/admin.ts
  apps/meteor/tests/e2e/federation/page-objects/channel.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/account-sidenav.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/admin-flextab-users.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/admin-flextab.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-members.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/federation/tests/admin/users.spec.ts
  apps/meteor/tests/e2e/federation/tests/ce-version/ce.spec.ts
  apps/meteor/tests/e2e/federation/tests/channel/dm.spec.ts
  apps/meteor/tests/e2e/federation/tests/channel/private.spec.ts
  apps/meteor/tests/e2e/federation/tests/channel/public.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/dm.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/private.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/public.spec.ts
  apps/meteor/tests/e2e/federation/tests/user-account/user.spec.ts
  apps/meteor/tests/e2e/federation/utils/auth.ts
  apps/meteor/tests/e2e/federation/utils/channel.ts
  apps/meteor/tests/e2e/federation/utils/test.ts
Labels: feat: federation, subj: testing, stat: needs QA

#27938 [IMPROVE] Add interpreter to message md
  ee/apps/omnichannel-transcript/src/OmnichannelTranscript.ts
  packages/pdf-worker/package.json
  packages/pdf-worker/public/inter400-italic.ttf
  packages/pdf-worker/public/inter500-italic.ttf
  packages/pdf-worker/public/inter700-italic.ttf
  packages/pdf-worker/src/templates/ChatTranscript/ChatTranscript.fixtures.ts
  packages/pdf-worker/src/templates/ChatTranscript/ChatTranscript.stories.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/MessageContent.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/MessageList.tsx
  packages/pdf-worker/src/templates/ChatTranscript/index.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/blocks/BigEmojiBlock.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/blocks/HeadingBlock.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/blocks/OrderedListBlock.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/blocks/ParagraphBlock.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/blocks/UnorderedListBlock.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/BoldSpan.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/EmojiSpan.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/InlineElements.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/ItalicSpan.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/LinkSpan.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/StrikeSpan.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/index.tsx
  yarn.lock
Labels: stat: needs QA

#27925 Chore: Notify Marketplace on App Install
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/apps/server/marketplace/appInstall.ts
Labels: stat: ready to merge, stat: QA skipped

#27894 [IMPROVE] Added PriorityIcon to PrioritiesSelect
  apps/meteor/ee/client/omnichannel/additionalForms/PrioritiesSelect.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27893 [NEW] Added new priority column to current chats table
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27744 [NEW] Warning Popup reinforcing Zapier deprecation on Integrations Admin settings
  apps/meteor/client/views/admin/integrations/new/NewZapier.js
  apps/meteor/packages/rocketchat-i18n/i18n/af.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/az.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/be-BY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bg.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cy.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-AT.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/el.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/eo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/id.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ku.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/mn.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ro.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sq.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/th-TH.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-HK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: ready to merge, stat: QA tested

#27936 Chore: improve some e2e selectors
  apps/meteor/tests/e2e/config/global-setup.ts
  apps/meteor/tests/e2e/fixtures/inject-initial-data.ts
  apps/meteor/tests/e2e/message-mentions.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-channels.ts
  apps/meteor/tests/e2e/page-objects/home-team.ts
  apps/meteor/tests/e2e/page-objects/utils.ts
  apps/meteor/tests/e2e/settings-account-profile.spec.ts
Labels: stat: needs QA

#27875 improve: Use workspace token when interacting with Marketplace
  apps/meteor/app/apps/server/communication/rest.js
Labels: Invalid PR Title, stat: needs QA

#27896 improve: Remove Cloud Login restrictions from Marketplace
  apps/meteor/client/views/admin/apps/AppsPage/AppsPage.tsx
  apps/meteor/client/views/admin/apps/AppsRoute.tsx
Labels: Invalid PR Title, stat: needs QA

#27762 [NEW] Complete sidebar sections and new style
  apps/meteor/app/apps/lib/misc/formatAppInstanceForRest.ts
  apps/meteor/client/components/Sidebar/Header.tsx
  apps/meteor/client/components/Sidebar/Sidebar.tsx
  apps/meteor/client/components/Sidebar/SidebarGenericItem.tsx
  apps/meteor/client/components/Sidebar/SidebarItemsAssembler.tsx
  apps/meteor/client/components/Sidebar/SidebarNavigationItem.tsx
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/lib/createSidebarItems.ts
  apps/meteor/client/views/marketplace/AppsContext.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPage.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsProvider.tsx
  apps/meteor/client/views/marketplace/hooks/useFilteredApps.ts
  apps/meteor/client/views/marketplace/sidebarItems.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/Apps.ts
Labels: stat: needs QA

#27892 [FIX] Embedded layout opening sidebar
  apps/meteor/app/search/client/provider/result.js
  apps/meteor/client/components/UserCard/UserCard.tsx
  apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx
  apps/meteor/client/lib/utils/jumpToMessage.ts
  apps/meteor/client/views/room/hooks/useGoToThreadList.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/useUserInfoActions.ts
  apps/meteor/client/views/room/providers/ToolboxProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#27797 [NEW] App request phase 2
  apps/meteor/app/apps/client/orchestrator.ts
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/client/components/AdministrationList/AdministrationList.spec.tsx
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/components/Sidebar/ListItem.tsx
  apps/meteor/client/components/Sidebar/SidebarGenericItem.tsx
  apps/meteor/client/components/Sidebar/SidebarNavigationItem.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPageHeader.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPageTabs.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogsItem.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogsItemEntry.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppReleases/AppReleasesItem.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppRequests/AppRequestItem.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppRequests/AppRequests.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppRequests/AppRequestsLoading.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppSecurity.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/AppMenu.js
  apps/meteor/client/views/marketplace/AppsList/AppRow.tsx
  apps/meteor/client/views/marketplace/AppsList/AppsList.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsFilters.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPage.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContentBody.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContentSkeleton.tsx
  apps/meteor/client/views/marketplace/AppsPage/FeaturedAppsSections.tsx
  apps/meteor/client/views/marketplace/AppsPage/NoAppRequestsEmptyState.tsx
  apps/meteor/client/views/marketplace/AppsProvider.tsx
  apps/meteor/client/views/marketplace/AppsRoute.tsx
  apps/meteor/client/views/marketplace/MarketplaceSidebar.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDownAnchor.tsx
  apps/meteor/client/views/marketplace/helpers.ts
  apps/meteor/client/views/marketplace/hooks/useAppRequestStats.ts
  apps/meteor/client/views/marketplace/hooks/useAppRequests.ts
  apps/meteor/client/views/marketplace/hooks/useFeaturedApps.ts
  apps/meteor/client/views/marketplace/hooks/useFilteredApps.ts
  apps/meteor/client/views/marketplace/sidebarItems.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/AppRequests.ts
  packages/core-typings/src/Apps.ts
  packages/rest-typings/src/apps/index.ts
Labels: stat: needs QA

#27932 [FIX] Hide generated PDF on Livechat upon chat close
  packages/livechat/src/routes/ChatFinished/component.js
Labels: stat: needs QA

#27843 Chore: Add hint (description) to CodeSettingInput after label
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
  apps/meteor/client/views/admin/settings/inputs/CodeSettingInput.stories.tsx
  apps/meteor/client/views/admin/settings/inputs/CodeSettingInput.tsx
Labels: stat: ready to merge, stat: QA tested

#27964 [FIX] PDF is not generated when chat is closed by visitors.
  apps/meteor/app/livechat/server/api/v1/room.ts
Labels: stat: needs QA

#27481 [BREAK] Freeze Custom Roles
  apps/meteor/app/api/server/v1/roles.ts
  apps/meteor/app/authorization/server/index.js
  apps/meteor/app/authorization/server/methods/saveRole.ts
  apps/meteor/client/views/admin/permissions/EditRolePage.tsx
  apps/meteor/client/views/admin/permissions/EditRolePageWithData.tsx
  apps/meteor/ee/definition/rest/index.ts
  apps/meteor/ee/definition/rest/v1/roles.ts
  apps/meteor/ee/server/api/index.ts
  apps/meteor/ee/server/api/roles.ts
  apps/meteor/ee/server/lib/roles/insertRole.ts
  apps/meteor/ee/server/lib/roles/updateRole.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/api/27-roles.ts
  packages/rest-typings/src/v1/roles.ts
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27609 [FIX] Black screen when try to open a chat with a non-existent department
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/lib/Departments.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/removeDepartment.js
  apps/meteor/app/models/server/models/LivechatDepartment.js
  apps/meteor/app/models/server/models/LivechatDepartmentAgents.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/DepartmentField.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/DepartmentField.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useDepartmentInfo.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterRemoveDepartment.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterRemoveDepartment.ts
  apps/meteor/ee/app/models/server/models/LivechatDepartment.js
  apps/meteor/ee/server/models/LivechatDepartment.ts
  apps/meteor/ee/server/models/raw/LivechatDepartment.ts
  apps/meteor/ee/server/models/startup.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  apps/meteor/server/models/raw/LivechatRooms.js
  apps/meteor/tests/data/livechat/units.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27858 [NEW] Notify admins via rocket.cat when a user requests to use an app
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/apps/server/marketplace/appRequestNotifyUsers.ts
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/AppMenu.js
  apps/meteor/client/views/marketplace/IframeModal.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rest-typings/src/apps/index.ts
Labels: stat: needs QA

#27919 [NEW] Add system message upon Priority and SLA change
  apps/meteor/app/models/server/models/LivechatRooms.js
  apps/meteor/ee/app/livechat-enterprise/lib/messageTypes.js
  apps/meteor/ee/app/livechat-enterprise/lib/messageTypes.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/inquiries.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/priorities.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/sla.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/rooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onSaveVisitorInfo.ts
  apps/meteor/ee/app/livechat-enterprise/server/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/SlaHelper.ts
  apps/meteor/ee/app/models/server/models/Messages.js
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v285.ts
  apps/meteor/tests/data/livechat/priorities.ts
  apps/meteor/tests/e2e/config/constants.ts
  apps/meteor/tests/e2e/omnichannel-changing-room-priority-and-sla.spec.ts
  apps/meteor/tests/e2e/utils/omnichannel/priority.ts
  apps/meteor/tests/e2e/utils/omnichannel/sla.ts
  apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/model-typings/src/models/IMessagesModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: needs QA

#27788 Chore: Implemented e2e tests for priorities
  apps/meteor/client/views/admin/settings/inputs/StringSettingInput.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
  apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx
  apps/meteor/tests/e2e/omnichannel-priorities.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-priorities.ts
Labels: stat: needs QA, feat: omnichannel

#27895 [NEW] Added priorities sidebar menu
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/ee/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27877 [NEW] Bridge to get all users crated by app and also delete them
  apps/meteor/app/apps/server/bridges/users.ts
  apps/meteor/app/lib/server/functions/getUserCreatedByApp.ts
  apps/meteor/app/lib/server/functions/index.ts
Labels: stat: ready to merge, stat: QA skipped

#27876 [FIX] Comunity users accessing exclusive ee endpoints in omnichannel section
  apps/meteor/client/components/Omnichannel/Tags.tsx
  apps/meteor/ee/client/omnichannel/tags/TagEditWithData.js
  apps/meteor/ee/client/omnichannel/units/UnitsRoute.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27965 Regression: upserting data into cached collections
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
Labels: stat: ready to merge, stat: QA skipped

#27760 [BREAK] Remove legacy FB Messenger integration
  apps/meteor/app/authorization/server/functions/upsertPermissions.ts
  apps/meteor/app/livechat/imports/server/rest/facebook.ts
  apps/meteor/app/livechat/server/api.ts
  apps/meteor/app/livechat/server/config.ts
  apps/meteor/app/livechat/server/hooks/sendToFacebook.js
  apps/meteor/app/livechat/server/index.js
  apps/meteor/app/livechat/server/lib/OmniChannel.js
  apps/meteor/app/livechat/server/methods/facebook.js
  apps/meteor/client/views/omnichannel/facebook/FacebookPage.tsx
  apps/meteor/client/views/omnichannel/facebook/FacebookPageContainer.tsx
  apps/meteor/client/views/omnichannel/facebook/PageToggle.tsx
  apps/meteor/client/views/omnichannel/facebook/PageToggleAssembler.tsx
  apps/meteor/client/views/omnichannel/routes.ts
  apps/meteor/client/views/omnichannel/sidebarItems.ts
  apps/meteor/definition/methods/omnichannel.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/modules/watchers/publishFields.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v283.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27898 [IMPROVE] Spanish home translation
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#27947 [FIX] Message-parser link issues
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27661 Chore: Settings regenerator on migration
  apps/meteor/server/lib/settingsRegenerator.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v284.ts
Labels: stat: ready to merge, stat: QA skipped

#27967 [FIX] Use fibers on async calls
  apps/meteor/ee/app/apps/bridges/internal.ts
  apps/meteor/ee/app/apps/bridges/livechat.ts
  apps/meteor/server/models/raw/Subscriptions.ts
Labels: stat: needs QA

#27707 [BREAK] [NEW] Custom roles upsell modal
  apps/meteor/client/components/GenericModal.tsx
  apps/meteor/client/views/admin/permissions/CustomRoleUpsellModal.tsx
  apps/meteor/client/views/admin/permissions/EditRolePage.tsx
  apps/meteor/client/views/admin/permissions/PermissionsContextBar.tsx
  apps/meteor/client/views/admin/permissions/PermissionsRouter.tsx
  apps/meteor/client/views/admin/permissions/PermissionsTable/PermissionsTable.tsx
  apps/meteor/client/views/admin/permissions/PermissionsTable/RoleHeader.tsx
  apps/meteor/client/views/admin/permissions/RoleForm.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/images/custom-role-upsell-modal.png
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27279 [FIX] Ignored messages reactivity
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/views/room/MessageList/MessageList.tsx
  apps/meteor/tests/unit/client/views/room/MessageList/Message.spec.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27855 Chore: Added Enterprise Options to Login customization
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/web-ui-registration/src/RegisterSecretPageRouter.tsx
  packages/web-ui-registration/src/RegisterTemplate.tsx
  packages/web-ui-registration/src/RegistrationPageRouter.tsx
  packages/web-ui-registration/src/SecretRegisterInvalidForm.tsx
  packages/web-ui-registration/src/components/LoginPoweredBy.tsx
  packages/web-ui-registration/src/components/RegisterTitle.tsx
  packages/web-ui-registration/src/template/HorizontalTemplate.tsx
  packages/web-ui-registration/src/template/VerticalTemplate.tsx
Labels: stat: ready to merge, stat: QA tested

#27921 Chore: Update EE upgrade callout button
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
  apps/meteor/client/views/admin/settings/Setting.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
Labels: stat: needs QA, feat: team-collab

#27931 Chore: Refactor Composer Dropdown
  apps/meteor/app/discussion/client/discussionFromMessageBox.js
  apps/meteor/app/discussion/client/index.js
  apps/meteor/app/ui-message/client/actionButtons/messageBox.ts
  apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
  apps/meteor/app/ui-message/client/messageBox/messageBox.ts
  apps/meteor/app/ui-message/client/messageBox/messageBoxActions.ts
  apps/meteor/app/webdav/client/index.js
  apps/meteor/app/webdav/client/startup/messageBoxActions.js
  apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx
  apps/meteor/client/views/composer/AudioMessageRecorder/AudioMessageRecorder.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxDropdown.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/actions/CreateDiscussionAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/actions/FileUploadAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/actions/ShareLocationAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/actions/VideoMessageAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/actions/WebdavAction.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/permissions.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#27978 Chore: Aria busy indicators
  apps/meteor/client/views/root/PageLoading.tsx
  apps/meteor/tests/e2e/config/global-setup.ts
  apps/meteor/tests/e2e/config/global.d.ts
  apps/meteor/tests/e2e/utils/test.ts
Labels: stat: needs QA

#27933 feat: Presence cap UI
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/client/hooks/usePresence.ts
  apps/meteor/client/hooks/useUserData.ts
  apps/meteor/client/lib/presence.ts
  apps/meteor/client/providers/UserPresenceProvider.tsx
  apps/meteor/client/sidebar/Sidebar.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/sections/StatusDisabledSection.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserActiveConnections.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusRoute.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusService.tsx
  apps/meteor/client/views/admin/customUserStatus/hooks/useActiveConnections.ts
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/room/components/body/LeaderBar.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/UserStatus.ts
  packages/ui-client/src/components/UserStatus/UserStatus.tsx
  yarn.lock
Labels: Invalid PR Title, stat: needs QA

#27977 [FIX] Clicking on view full icon navigates user to Home Screen
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/client/views/room/providers/RoomProvider.tsx
Labels: stat: needs QA, feat: omnichannel

#27817 Chore: Set missing colors
  apps/meteor/client/components/GenericTable/NoResults.tsx
  apps/meteor/client/components/Page/Page.tsx
  apps/meteor/client/components/VerticalBar/VerticalBar.tsx
  apps/meteor/client/sidebar/Sidebar.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleReady.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelLivechatToggle.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusRoute.tsx
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/client/views/room/Announcement/AnnouncementComponent.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseFilter.tsx
  ee/packages/ui-theming/src/sidebarPalette.ts
  ee/packages/ui-theming/src/sidebarPaletteDark.ts
  yarn.lock
Labels: stat: needs QA

#27764 [FIX] Video Conf Message Blocks not always updating when running on micro services
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/core-services/src/Events.ts
Labels: stat: ready to merge, stat: QA tested

#27966 [NEW] Department Archivation
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/api/lib/departments.ts
  apps/meteor/app/livechat/server/config.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/client/components/AutoCompleteDepartment.tsx
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.js
  apps/meteor/client/components/Omnichannel/hooks/useDepartmentsList.ts
  apps/meteor/client/views/hooks/useDepartmentsByUnitsList.ts
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEditWithData.tsx
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/departments/ArchivedDepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/ArchivedItemMenu.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentItemMenu.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsPage.js
  apps/meteor/client/views/omnichannel/departments/DepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsRoute.js
  apps/meteor/client/views/omnichannel/departments/DepartmentsRoute.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.js
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithData.js
  apps/meteor/client/views/omnichannel/departments/NewDepartment.tsx
  apps/meteor/client/views/omnichannel/departments/PermanentDepartmentRemovalModal.tsx
  apps/meteor/client/views/omnichannel/departments/RemoveDepartmentButton.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
  apps/meteor/ee/client/omnichannel/tags/TagEdit.js
  apps/meteor/ee/client/omnichannel/tags/TagNew.js
  apps/meteor/ee/client/omnichannel/tags/TagsRoute.js
  apps/meteor/ee/client/omnichannel/units/UnitNew.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  packages/core-typings/src/ILivechatDepartment.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: needs QA, feat: omnichannel

#27644 [NEW] Permission to bypass message editing and removing limits
  apps/meteor/app/authorization/server/functions/canDeleteMessage.ts
  apps/meteor/app/authorization/server/functions/upsertPermissions.ts
  apps/meteor/app/lib/server/methods/updateMessage.js
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/lib/chats/data.ts
  apps/meteor/client/methods/updateMessage.ts
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useMessageDeletionIsAllowed.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v286.ts
  apps/meteor/tests/end-to-end/api/24-methods.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27983 [IMPROVE] Changed RoomMenu maxHeight to accommodate priorities
  apps/meteor/client/sidebar/RoomMenu.tsx
Labels: stat: needs QA, feat: omnichannel

#27291 [NEW] Create stream for priority updates
  apps/meteor/ee/server/lib/registerServiceModels.ts
  apps/meteor/ee/server/models/startup.ts
  apps/meteor/server/database/watchCollections.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  packages/core-services/src/Events.ts
Labels: stat: needs QA, feat: omnichannel

#27990 Chore: remove listener service
  apps/meteor/ee/app/apps/listenerService.ts
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/sdk/index.ts
  apps/meteor/server/sdk/types/IAppsListenerService.ts
Labels: stat: needs QA

#27976 [FIX] Transcript email is not sent if chat is closed by visitor
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
Labels: stat: needs QA, feat: omnichannel

#27988 [FIX] Migration for priorities
  apps/meteor/server/startup/migrations/v287.ts
Labels: stat: needs QA, feat: omnichannel

#27913 [NEW] Added omnichannel sorting disclaimer to SortModeList menu
  apps/meteor/client/components/Omnichannel/OmnichannelSortingDisclaimer.tsx
  apps/meteor/client/components/SortList/SortModeList.tsx
  apps/meteor/client/contexts/OmnichannelContext.ts
  apps/meteor/client/hooks/omnichannel/useOmnichannelEnterpriseEnabled.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: stat: needs QA, feat: omnichannel

#27986 [IMPROVE] Add styles for inline and multi-line code
  packages/pdf-worker/src/public/fira-code700.ttf
  packages/pdf-worker/src/templates/ChatTranscript/ChatTranscript.fixtures.ts
  packages/pdf-worker/src/templates/ChatTranscript/ChatTranscript.stories.tsx
  packages/pdf-worker/src/templates/ChatTranscript/index.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/blocks/CodeBlock.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/CodeElement.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/CodeSpan.tsx
  packages/pdf-worker/src/templates/ChatTranscript/markup/elements/InlineElements.tsx
Labels: stat: needs QA, feat: omnichannel

#27419 [FIX] Use apps.engine service
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/threads/client/flextab/thread.ts
  apps/meteor/app/ui-message/client/messageBox/messageBox.ts
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/client/views/omnichannel/contactHistory/ContactHistoryItem.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/ee/app/apps/videoManagerService.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/sdk/types/IAppsVideoManagerService.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: needs QA

#27992 Chore: Add archived department tests
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
Labels: stat: needs QA

#27910 [FIX] Adjusted priority icon positioning and added spacing
  apps/meteor/client/components/InlineGroup/index.tsx
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27888 [NEW] Added priorities fetch to Omnichannel context
  apps/meteor/client/contexts/OmnichannelContext.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/client/views/omnichannel/directory/ChatsContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEditWithData.tsx
  apps/meteor/client/views/omnichannel/directory/components/PriorityField.tsx
  apps/meteor/client/views/omnichannel/directory/components/SlaField.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useOmnichannelRoomInfo.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/usePrioritiesData.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/usePriorityInfo.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useSlaInfo.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useSlaPolicies.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/PrioritiesSelect.tsx
  apps/meteor/ee/client/omnichannel/hooks/useOmnichannelPriorities.ts
  apps/meteor/ee/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesTable.tsx
  apps/meteor/ee/client/omnichannel/priorities/PriorityEditFormWithData.tsx
  apps/meteor/ee/client/omnichannel/priorities/PriorityIcon.tsx
  apps/meteor/server/startup/migrations/v287.ts
Labels: stat: needs QA, feat: omnichannel

#27854 [BREAK][ENTERPRISE] Limit presence statuses to 200 concurrent users when running monolith to keep performance
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/v1/presence.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/apps/server/storage/logs-storage.js
  apps/meteor/app/file-upload/server/lib/proxy.js
  apps/meteor/app/lib/server/lib/debug.js
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/client/hooks/usePresence.ts
  apps/meteor/client/hooks/useUserData.ts
  apps/meteor/client/lib/presence.ts
  apps/meteor/client/providers/UserPresenceProvider.tsx
  apps/meteor/client/sidebar/Sidebar.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/sections/StatusDisabledSection.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserActiveConnections.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusRoute.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusService.tsx
  apps/meteor/client/views/admin/customUserStatus/hooks/useActiveConnections.ts
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/room/components/body/LeaderBar.tsx
  apps/meteor/definition/externals/meteor/konecty-multiple-instances-status.d.ts
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/ee/server/startup/presence.ts
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/hooks/sauMonitorHooks.ts
  apps/meteor/server/startup/index.ts
  apps/meteor/server/startup/instance.ts
  apps/meteor/server/stream/streamBroadcast.js
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  apps/meteor/tests/end-to-end/api/27-presence.ts
  ee/apps/ddp-streamer/Dockerfile
  ee/apps/ddp-streamer/package.json
  ee/apps/ddp-streamer/src/DDPStreamer.ts
  ee/apps/presence-service/Dockerfile
  ee/packages/presence/.eslintrc
  ee/packages/presence/.gitignore
  ee/packages/presence/babel.config.js
  ee/packages/presence/package.json
  ee/packages/presence/src/Presence.ts
  ee/packages/presence/src/lib/processConnectionStatus.ts
  ee/packages/presence/tests/lib/processConnectionStatus.test.ts
  ee/packages/presence/tsconfig.json
  packages/core-services/src/types/IPresence.ts
  packages/core-typings/src/UserStatus.ts
  packages/instance-status/.eslintrc.json
  packages/instance-status/package.json
  packages/instance-status/src/index.ts
  packages/instance-status/tsconfig.json
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/presence.ts
  packages/ui-client/src/components/UserStatus/UserStatus.tsx
  yarn.lock
Labels: stat: needs QA

#27820 [IMPROVE] Registration Experience
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
  apps/meteor/app/cloud/server/functions/disconnectWorkspace.ts
  apps/meteor/app/cloud/server/functions/getUserCloudAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js
  apps/meteor/app/cloud/server/functions/reconnectWorkspace.ts
  apps/meteor/app/cloud/server/functions/removeWorkspaceRegistrationInfo.ts
  apps/meteor/app/cloud/server/methods.js
  apps/meteor/client/components/AdministrationList/AdministrationModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/providers/TranslationProvider.tsx
  apps/meteor/client/views/admin/apps/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/admin/apps/AppMenu.js
  apps/meteor/client/views/admin/apps/AppsPage/AppsPage.tsx
  apps/meteor/client/views/admin/apps/AppsRoute.tsx
  apps/meteor/client/views/admin/cloud/CloudRoute.js
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceCards.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx
  apps/meteor/client/views/admin/cloud/hooks/useFeatureBullets.tsx
  apps/meteor/client/views/admin/cloud/modals/ConnectWorkspaceModal.tsx
  apps/meteor/client/views/admin/cloud/modals/DisconnectWorkspaceModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepOneModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepTwoModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/index.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceTokenModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisteredWorkspaceModal.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/mocks/client/ModalContextMock.tsx
  packages/ui-contexts/src/ServerContext/methods.ts
Labels: stat: ready to merge, stat: QA tested

#27731 [NEW] Create `EnterpriseTrialEnded` banner
  apps/meteor/client/components/UpsellModal.tsx
  apps/meteor/client/views/marketplace/AppsRoute.tsx
  apps/meteor/client/views/marketplace/components/BannerEnterpriseTrialEnded.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#27997 [NEW] Update view logs action icon in `AppMenu`
  apps/meteor/client/views/marketplace/AppMenu.js
  yarn.lock
Labels: stat: needs QA

#27708 [NEW] Create page for "No private apps installed"
  apps/meteor/client/components/PageEmptyPrivateApps.stories.tsx
  apps/meteor/client/components/PageEmptyPrivateApps.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsPage/PrivateEmptyState.stories.tsx
  apps/meteor/client/views/marketplace/AppsPage/PrivateEmptyState.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#28000 Chore: Wait message to not be Busy
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/tests/e2e/permissions.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#27930 [FIX] Remove meteor dependencies from apps-engine
  apps/meteor/app/apps/server/api/index.ts
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/ee/app/apps/apiService.ts
  apps/meteor/ee/app/apps/bridges/api.ts
  apps/meteor/ee/app/apps/bridges/commands.ts
  apps/meteor/ee/app/apps/bridges/http.ts
  apps/meteor/ee/app/apps/bridges/internal.ts
  apps/meteor/ee/app/apps/bridges/livechat.ts
  apps/meteor/ee/app/apps/bridges/messages.ts
  apps/meteor/ee/app/apps/bridges/persistence.ts
  apps/meteor/ee/app/apps/converterService.ts
  apps/meteor/ee/app/apps/managerService.ts
  apps/meteor/ee/app/apps/settings.ts
  apps/meteor/server/main.ts
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/sdk/index.ts
  apps/meteor/server/sdk/types/IAppsApiService.ts
  apps/meteor/server/sdk/types/IAppsConverterService.ts
  apps/meteor/server/sdk/types/IAppsManagerService.ts
  apps/meteor/server/sdk/types/IFetchService.ts
  apps/meteor/server/sdk/types/ILivechatService.ts
  apps/meteor/server/sdk/types/IMessageService.ts
  apps/meteor/server/sdk/types/INotificationService.ts
  apps/meteor/server/sdk/types/ISlashCommandService.ts
  apps/meteor/server/services/fetch/service.ts
  apps/meteor/server/services/livechat/service.ts
  apps/meteor/server/services/message/service.ts
  apps/meteor/server/services/notification/service.ts
  apps/meteor/server/services/slashcommand/service.ts
  apps/meteor/server/services/startup.ts
  ee/apps/apps-engine/src/service.ts
  packages/model-typings/package.json
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: needs QA

#27996 [IMPROVE] Remove settings from apps-engine service
  apps/meteor/app/apps/server/settings.ts
  apps/meteor/app/apps/server/startup.ts
  apps/meteor/ee/app/apps/orchestrator.js
  apps/meteor/ee/app/apps/orchestratorFactory.ts
  apps/meteor/ee/app/apps/service.ts
  apps/meteor/server/main.ts
  apps/meteor/server/sdk/types/IAppsService.ts
Labels: stat: needs QA

#27251 [FIX] Disabling admin actions for federated users
  apps/meteor/app/2fa/server/functions/resetTOTP.ts
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/app/lib/server/functions/setUserActiveStatus.ts
  apps/meteor/app/lib/server/methods/setAdminStatus.ts
  apps/meteor/client/views/admin/users/AdminUserInfoActions.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoWithData.tsx
  apps/meteor/client/views/admin/users/EditUserWithData.tsx
  apps/meteor/ee/client/views/admin/users/SeatsCapUsage/SeatsCapUsage.tsx
  apps/meteor/server/lib/resetUserE2EKey.ts
Labels: feat: federation, stat: needs QA

#28011 [FIX] Hide generated PDF on Livechat upon chat close
  packages/livechat/src/lib/room.js
  packages/livechat/src/routes/ChatFinished/component.js
Labels: stat: needs QA

#27972 [NEW] Emojis rendering properly on quote message previews
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxReplies.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27969 [BREAK] Unify monolith and microservices intercommunication on same technology and limit to Enterprise only
  .vscode/settings.json
  apps/meteor/app/api/server/v1/instances.ts
  apps/meteor/client/views/admin/info/DeploymentCard.tsx
  apps/meteor/client/views/admin/info/InformationPage.tsx
  apps/meteor/client/views/admin/info/InformationRoute.tsx
  apps/meteor/client/views/admin/info/InstancesModal.js
  apps/meteor/ee/server/local-services/instance/service.ts
  apps/meteor/ee/server/sdk/index.ts
  apps/meteor/ee/server/sdk/types/IInstanceService.ts
  apps/meteor/ee/server/startup/services.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/main.ts
  apps/meteor/server/services/meteor/service.ts
  apps/meteor/server/startup/index.ts
  apps/meteor/server/startup/instance.ts
  apps/meteor/server/stream/streamBroadcast.js
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  packages/core-typings/src/IInstanceStatus.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/instances.ts
Labels: stat: ready to merge, stat: QA skipped

#27697 [NEW] Create header components for marketplace view
  apps/meteor/client/views/marketplace/AppsPage/AppsPage.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContentBody.tsx
  apps/meteor/client/views/marketplace/AppsProvider.tsx
  apps/meteor/client/views/marketplace/components/EnabledAppsCount.tsx
  apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
  apps/meteor/client/views/marketplace/hooks/useAppsCountQuery.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/ee/ILicense/ILicense.ts
  packages/rest-typings/src/apps/index.ts
Labels: stat: needs QA

#28012 [BREAK] Remove Chatpal
  apps/meteor/app/authorization/server/functions/upsertPermissions.ts
  apps/meteor/app/chatpal-search/client/index.js
  apps/meteor/app/chatpal-search/client/style.css
  apps/meteor/app/chatpal-search/client/template/admin.html
  apps/meteor/app/chatpal-search/client/template/admin.js
  apps/meteor/app/chatpal-search/client/template/result.html
  apps/meteor/app/chatpal-search/client/template/result.js
  apps/meteor/app/chatpal-search/client/template/suggestion.html
  apps/meteor/app/chatpal-search/client/template/suggestion.js
  apps/meteor/app/chatpal-search/server/asset/config.js
  apps/meteor/app/chatpal-search/server/index.js
  apps/meteor/app/chatpal-search/server/provider/index.js
  apps/meteor/app/chatpal-search/server/provider/provider.js
  apps/meteor/app/chatpal-search/server/utils/logger.js
  apps/meteor/app/chatpal-search/server/utils/settings.js
  apps/meteor/app/chatpal-search/server/utils/utils.js
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/definition/externals/meteor/templating.d.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/private/server/asset/chatpal-enter.svg
  apps/meteor/private/server/asset/chatpal-logo-icon-darkblue.svg
  apps/meteor/server/importPackages.ts
  apps/meteor/server/startup/migrations/v288.ts
Labels: stat: ready to merge, stat: QA skipped

#27942 [FIX] Invalid regex on search fields crashes UI
  apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx
  apps/meteor/client/views/admin/customSounds/CustomSoundsRoute.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusTable/CustomUserStatusTable.tsx
  apps/meteor/client/views/admin/integrations/IntegrationsTable.js
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28019 Chore: Refactor `AudioMessageRecorder`
  apps/meteor/client/views/composer/AudioMessageRecorder/AudioMessageRecorder.tsx
  apps/meteor/client/views/room/components/body/composer/RoomComposer/hooks/useAutoGrow.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/actions/AudioMessageAction.tsx
Labels: stat: ready to merge, stat: QA skipped

#27959 Chore: `desktop` icon instead of `computer` icon
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.tsx
Labels: stat: needs QA

#27779 [FIX] Broken settings check for updates
  apps/meteor/app/version-check/server/index.ts
Labels: stat: needs QA

#28020 [FIX] Move Omni startup to be EE wrapped
  apps/meteor/app/federation/server/functions/dashboard.js
  apps/meteor/app/livechat/server/business-hour/Helper.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/ee/app/livechat-enterprise/server/index.js
Labels: stat: ready to merge, stat: QA skipped

#27941 [FIX] "Jump to first unread" banner does not always appear when the first unread message is outside of the visible screen
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/components/body/useUnreadMessages.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27488 [FIX] Option to Join Read-Only Channels
  .gitignore
  apps/meteor/client/views/room/components/body/composer/ComposerContainer.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerReadOnly.tsx
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  packages/ui-composer/src/MessageFooterCallout/MessageFooterCalloutContent.tsx
Labels: stat: ready to merge, communityPR, stat: QA skipped, feat: team-collab

#28022 Chore: Service cap
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/sections/StatusDisabledSection.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusService.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#27561 [FIX] IPostMessageReacted return field named isReacted instead isRemoved
  apps/meteor/app/apps/server/bridges/listeners.js
Labels: stat: ready to merge, stat: QA skipped

#28013 Chore: Refactor Composer Popup
  .vscode/settings.json
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/ui-message/client/index.ts
  apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
  apps/meteor/app/ui-message/client/popup/ComposerBoxPopup.tsx
  apps/meteor/app/ui-message/client/popup/components/ComposerBoxPopupCannedResponse.tsx
  apps/meteor/app/ui-message/client/popup/components/ComposerBoxPopupEmoji.tsx
  apps/meteor/app/ui-message/client/popup/components/ComposerBoxPopupRoom.tsx
  apps/meteor/app/ui-message/client/popup/components/ComposerBoxPopupSlashCommand.tsx
  apps/meteor/app/ui-message/client/popup/components/ComposerBoxPopupUser.tsx
  apps/meteor/app/ui-message/client/popup/customMessagePopups.js
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopupQueries.ts
  apps/meteor/app/ui-message/client/popup/messagePopup.html
  apps/meteor/app/ui-message/client/popup/messagePopup.js
  apps/meteor/app/ui-message/client/popup/messagePopupChannel.html
  apps/meteor/app/ui-message/client/popup/messagePopupChannel.js
  apps/meteor/app/ui-message/client/popup/messagePopupConfig.html
  apps/meteor/app/ui-message/client/popup/messagePopupConfig.js
  apps/meteor/app/ui-message/client/popup/messagePopupEmoji.html
  apps/meteor/app/ui-message/client/popup/messagePopupEmoji.js
  apps/meteor/app/ui-message/client/popup/messagePopupSlashCommand.html
  apps/meteor/app/ui-message/client/popup/messagePopupSlashCommandPreview.js
  apps/meteor/app/ui-message/client/popup/messagePopupUser.html
  apps/meteor/client/components/RoomIcon/RoomIcon.tsx
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleOption.tsx
  apps/meteor/client/components/message/toolbox/DesktopToolboxDropdown.tsx
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/views/room/components/body/composer/hooks/useComposeChainEvents.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/contexts/ComposerPopupContext.ts
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/definition/externals/meteor/templating.d.ts
  apps/meteor/ee/app/canned-responses/client/collections/CannedResponse.js
  apps/meteor/ee/app/canned-responses/client/collections/CannedResponse.ts
  apps/meteor/ee/app/canned-responses/client/index.js
  apps/meteor/ee/app/canned-responses/client/views/popup/addMessagePopupCannedResponse.js
  apps/meteor/ee/app/canned-responses/client/views/popup/messagePopupCannedResponse.html
  apps/meteor/tests/e2e/message-mentions.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  packages/ui-contexts/src/ServerContext/methods.ts
  yarn.lock
Labels: stat: needs QA

#28026 Chore: startup communicators outside ee directory
  apps/meteor/app/apps/server/communication/index.ts
  apps/meteor/app/apps/server/communication/startup.ts
  apps/meteor/app/apps/server/communication/websockets.ts
  apps/meteor/ee/app/apps/bridges/activation.ts
  apps/meteor/ee/app/apps/bridges/commands.ts
  apps/meteor/ee/app/apps/bridges/details.ts
  apps/meteor/ee/app/apps/orchestrator.js
  apps/meteor/ee/app/apps/service.ts
  apps/meteor/server/main.ts
  apps/meteor/server/sdk/types/IAppsService.ts
Labels: stat: needs QA

#27920 Chore: move Meteor function calls out of the ee directory
  apps/meteor/ee/app/apps/bridges/rooms.ts
  apps/meteor/ee/app/apps/bridges/uploads.ts
  apps/meteor/ee/app/apps/bridges/users.ts
  apps/meteor/server/sdk/types/IRoomService.ts
  apps/meteor/server/sdk/types/IUploadService.ts
  apps/meteor/server/sdk/types/IUserService.ts
  apps/meteor/server/services/meteor/service.ts
  apps/meteor/server/services/room/service.ts
  apps/meteor/server/services/upload/service.ts
  apps/meteor/server/services/user/service.ts
Labels: stat: needs QA

#28021 [FIX] Register Workspace UI fixes and fix doc link
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepOneModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepTwoModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceTokenModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#28039 Chore: Refactor Composer Collapsed Formatters and Actions
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/AudioMessageAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/CreateDiscussionAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/ShareLocationAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/WebdavAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/index.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/FormattingToolbarDropdown.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/MessageBoxFormattingToolbar.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/index.ts
Labels: stat: ready to merge, stat: QA skipped

#27891 [BREAK] Drop support for MongoDB 4.2 and deprecate 4.4
  .github/workflows/build_and_test.yml
  apps/meteor/server/startup/serverRunning.js
Labels: stat: ready to merge, stat: QA skipped, feat: architecture

#27074 [BREAK] Move read-receipts to EE and threads check marks improvements
  apps/meteor/app/api/server/v1/chat.js
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/app/models/server/models/Messages.js
  apps/meteor/app/threads/server/methods/getThreadMessages.js
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
  apps/meteor/client/views/admin/info/LicenseCard.tsx
  apps/meteor/ee/app/license/server/bundles.ts
  apps/meteor/ee/app/message-read-receipt/server/hooks/afterReadMessages.ts
  apps/meteor/ee/app/message-read-receipt/server/hooks/afterSaveMessage.ts
  apps/meteor/ee/app/message-read-receipt/server/hooks/index.ts
  apps/meteor/ee/app/message-read-receipt/server/index.ts
  apps/meteor/ee/client/startup/index.ts
  apps/meteor/ee/client/startup/readReceipt.ts
  apps/meteor/ee/definition/rest/index.ts
  apps/meteor/ee/definition/rest/v1/chat.ts
  apps/meteor/ee/server/api/chat.ts
  apps/meteor/ee/server/api/index.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/ee/server/lib/constants.ts
  apps/meteor/ee/server/lib/message-read-receipt/ReadReceipt.js
  apps/meteor/ee/server/local-services/message-reads/service.ts
  apps/meteor/ee/server/methods/getReadReceipts.js
  apps/meteor/ee/server/models/ReadReceipts.ts
  apps/meteor/ee/server/models/raw/ReadReceipts.ts
  apps/meteor/ee/server/models/startup.ts
  apps/meteor/ee/server/sdk/index.ts
  apps/meteor/ee/server/sdk/types/IMessageReadsService.ts
  apps/meteor/ee/server/sdk/types/index.ts
  apps/meteor/ee/server/startup/services.ts
  apps/meteor/imports/message-read-receipt/server/index.js
  apps/meteor/imports/message-read-receipt/server/settings.ts
  apps/meteor/imports/startup/server/index.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/methods/readThreads.js
  apps/meteor/server/models/MessageReads.ts
  apps/meteor/server/models/raw/MessageReads.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/server/models/startup.ts
  apps/meteor/tests/end-to-end/api/05-chat.js
  packages/core-services/src/index.ts
  packages/core-services/src/types/IMessageReadsService.ts
  packages/core-typings/src/MessageReads.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/IMessageReadsModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
  packages/models/src/index.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28044 Regression: Fix missing Formatting items
  apps/meteor/client/views/room/components/body/composer/hooks/useMessageComposerMergedRefs.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
Labels: stat: ready to merge, stat: QA skipped

#27912 [FIX] Empty DMs go to sidebar's top after updating user preferences
  apps/meteor/app/models/client/models/CachedChatSubscription.ts
Labels: stat: ready to merge, stat: QA skipped

#28038 Chore: Add quote message option back on live chat rooms
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27752 [NEW] Create pre-install modal for apps limitation
  apps/meteor/client/components/PageEmptyPrivateApps.stories.tsx
  apps/meteor/client/components/PageEmptyPrivateApps.tsx
  apps/meteor/client/views/marketplace/AppMenu.js
  apps/meteor/client/views/marketplace/AppsProvider.tsx
  apps/meteor/client/views/marketplace/components/AppInstallModal/AppInstallModal.stories.tsx
  apps/meteor/client/views/marketplace/components/AppInstallModal/AppInstallModal.tsx
  apps/meteor/client/views/marketplace/hooks/useAppsCountQuery.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#27413 Chore: Add E2E tests to Triggers view
  apps/meteor/tests/e2e/omnichannel-triggers.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
  apps/meteor/tests/e2e/page-objects/home-omnichannel.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-triggers.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#28045 [NEW] Create uninstall modal for grandfathered apps
  apps/meteor/client/views/marketplace/AppMenu.js
  apps/meteor/client/views/marketplace/components/UninstallGrandfatheredAppModal/UninstallGrandfatheredAppModal.stories.tsx
  apps/meteor/client/views/marketplace/components/UninstallGrandfatheredAppModal/UninstallGrandfatheredAppModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#28046 Regression: Emoji picker styling
  apps/meteor/app/emoji/client/emojiPicker.html
  apps/meteor/app/theme/client/imports/components/emojiPicker.css
Labels: stat: ready to merge, stat: QA skipped

#28031 [FIX] Custom fields does not appear on the registration form
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/api/v1/config.ts
  apps/meteor/tests/data/livechat/custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28029 Chore: Fix babel config related to TypeScript `declare` usage
  apps/meteor/.storybook/babel.config.js
Labels: stat: ready to merge, stat: QA skipped

#28049 Chore: EmojiPicker Wrapper Styles
  apps/meteor/app/emoji/client/emojiPicker.html
  apps/meteor/app/emoji/client/emojiPicker.js
  apps/meteor/app/theme/client/imports/components/emojiPicker.css
  apps/meteor/client/main.ts
  apps/meteor/client/templates.ts
  apps/meteor/client/views/composer/EmojiPickerWrapper.tsx
Labels: stat: needs QA

#28056 Regression: 0 appearing on sidebar on specific occasions
  apps/meteor/client/components/InlineGroup/index.tsx
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
Labels: stat: needs QA

#28060 Regression: Formatted text rendered by UI Kit
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/client/components/message/content/UiKitSurface.tsx
  apps/meteor/client/components/message/content/uikit/ParsedText.tsx
  apps/meteor/client/lib/normalizeThreadMessage.tsx
  apps/meteor/client/lib/utils/renderMessageBody.ts
  apps/meteor/client/methods/updateMessage.ts
  apps/meteor/client/views/blocks/textParsers.js
  apps/meteor/client/views/room/contextualBar/Discussions/Row.js
  apps/meteor/client/views/room/contextualBar/Discussions/components/DiscussionMessage.js
  apps/meteor/client/views/room/contextualBar/Discussions/components/Message.js
  apps/meteor/client/views/room/contextualBar/Discussions/components/Message.stories.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadListMessage.tsx
Labels: stat: needs QA

#28067 Regression: fix api tests
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
Labels: stat: needs QA

#28047 [NEW] App record digital signature validation
  apps/meteor/app/apps/server/bridges/bridges.js
  apps/meteor/app/apps/server/bridges/internalFederation.ts
  apps/meteor/package.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v292.ts
  yarn.lock
Labels: stat: needs QA

#28061 Chore: Fix e2e EE tests not working reliably
  .github/workflows/build_and_test.yml
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/anonymous-user.spec.ts
  apps/meteor/tests/e2e/config/global-setup.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/homepage.spec.ts
  apps/meteor/tests/e2e/omnichannel-auto-onhold-chat-closing.spec.ts
  apps/meteor/tests/e2e/omnichannel-auto-transfer-unanswered-chat.spec.ts
  apps/meteor/tests/e2e/omnichannel-changing-room-priority-and-sla.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/omnichannel-takeChat.spec.ts
  apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/system-messages.spec.ts
  apps/meteor/tests/e2e/utils/test.ts
Labels: stat: ready to merge, stat: QA skipped

#28065 Chore: SlashCommands Preview
  apps/meteor/app/lib/server/methods/executeSlashCommandPreview.ts
  apps/meteor/app/lib/server/methods/getSlashCommandPreviews.ts
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/ui-message/client/popup/ComposerBoxPopup.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopup/ComposerBoxPopupCannedResponse.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopup/ComposerBoxPopupEmoji.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopup/ComposerBoxPopupRoom.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopup/ComposerBoxPopupSlashCommand.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopup/ComposerBoxPopupUser.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopupPreview/ComposerBoxPopupPreview.tsx
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopupQueries.ts
  apps/meteor/client/components/ScrollableContentWrapper.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/hooks/useMessageBoxAutoFocus.ts
  apps/meteor/client/views/room/contexts/ComposerPopupContext.ts
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#28076 Chore: CI improvements
  .github/workflows/build_and_test.yml
  apps/meteor/package.json
Labels: stat: needs QA

#28071 Regression: Fix file upload on collapsed composer menu
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
Labels: stat: ready to merge, stat: QA skipped

#28015 Regression: DateRangePicker errors
  apps/meteor/ee/client/views/audit/components/forms/DateRangePicker.tsx
Labels: stat: ready to merge, stat: QA tested

#27627 [FIX] Access to localStorage in Livechat
  packages/livechat/src/store/Store.js
Labels: stat: ready to merge, communityPR, stat: QA skipped, feat: omnichannel

#28062 Regression: Client crashing when updating CachedChatSubscription
  apps/meteor/app/models/client/models/CachedChatSubscription.ts
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
Labels: stat: ready to merge, stat: QA skipped

#24205 [IMPROVE] Play selected notification sounds as preview while changing sound settings
  apps/meteor/client/views/account/preferences/PreferencesSoundSection.tsx
Labels: stat: ready to merge, communityPR, stat: QA skipped

#28040 Regression: Message > `messageActionDefault`> Copy and Report
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/views/room/modals/ReportMessageModal/ReportMessageModal.tsx
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28064 Chore: Remove `body` template
  apps/meteor/app/ui-master/client/body.html
  apps/meteor/app/ui-master/client/body.js
  apps/meteor/app/ui-master/client/index.ts
  apps/meteor/app/ui-master/client/loading/index.ts
  apps/meteor/app/ui-master/server/index.js
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/AppRoot.tsx
  apps/meteor/client/views/root/hooks/useClearUnreadAllMessagesMutation.ts
  apps/meteor/client/views/root/hooks/useEscapeKeyStroke.ts
  apps/meteor/client/views/root/hooks/useGoogleTagManager.ts
  apps/meteor/client/views/root/hooks/useMessageLinkClicks.ts
Labels: stat: ready to merge, stat: QA skipped

#28085 Chore: OAuth authorization pages reconditioned
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/app/oauth2-server-config/client/index.js
  apps/meteor/app/oauth2-server-config/client/oauth/oauth2-client.html
  apps/meteor/app/oauth2-server-config/client/oauth/oauth2-client.js
  apps/meteor/app/oauth2-server-config/client/oauth/stylesheets/oauth2.css
  apps/meteor/app/oauth2-server-config/server/admin/functions/addOAuthApp.ts
  apps/meteor/app/oauth2-server-config/server/admin/functions/parseUriList.ts
  apps/meteor/app/oauth2-server-config/server/admin/methods/addOAuthApp.js
  apps/meteor/app/oauth2-server-config/server/admin/methods/addOAuthApp.ts
  apps/meteor/app/oauth2-server-config/server/admin/methods/deleteOAuthApp.ts
  apps/meteor/app/oauth2-server-config/server/admin/methods/updateOAuthApp.ts
  apps/meteor/app/oauth2-server-config/server/index.ts
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/client/importPackages.ts
  apps/meteor/client/providers/TranslationProvider.tsx
  apps/meteor/client/startup/routes.tsx
  apps/meteor/client/views/oauth/OAuthAuthorizationPage.tsx
  apps/meteor/client/views/oauth/OAuthErrorPage.tsx
  apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx
  apps/meteor/client/views/oauth/components/CurrentUserDisplay.tsx
  apps/meteor/client/views/oauth/components/ErrorPage.tsx
  apps/meteor/client/views/oauth/components/Layout.tsx
  apps/meteor/client/views/oauth/hooks/useOAuthAppQuery.ts
  apps/meteor/definition/externals/meteor/templating.d.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/ui-contexts/src/ServerContext/methods.ts
  packages/ui-contexts/src/hooks/useAssetPath.ts
  packages/ui-contexts/src/index.ts
  packages/web-ui-registration/src/CMSPage.tsx
  packages/web-ui-registration/src/template/HorizontalTemplate.tsx
  packages/web-ui-registration/src/template/VerticalTemplate.tsx
Labels: stat: needs QA

#28086 Chore: move PaletteStyleTag
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
Labels: stat: needs QA

#28083 Chore: RoomAutocomplete Debounce Query
  apps/meteor/client/components/RoomAutoComplete/RoomAutoComplete.tsx
Labels: stat: needs QA

#28017 Regression: Fix presence broadcast not re-enabling
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  ee/packages/presence/src/Presence.ts
Labels: stat: ready to merge, stat: QA skipped

#28074 Chore: Add Eslint rules to tests
  apps/meteor/.eslintcache
  apps/meteor/package.json
  apps/meteor/tests/.eslintrc.json
  apps/meteor/tests/e2e/.eslintrc.json
  apps/meteor/tests/e2e/federation/tests/admin/rooms.spec.ts
  apps/meteor/tests/e2e/federation/tests/admin/users.spec.ts
  apps/meteor/tests/e2e/federation/tests/ce-version/ce.spec.ts
  apps/meteor/tests/e2e/federation/tests/channel/dm.spec.ts
  apps/meteor/tests/e2e/federation/tests/channel/private.spec.ts
  apps/meteor/tests/e2e/federation/tests/channel/public.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/dm.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/private.spec.ts
  apps/meteor/tests/e2e/federation/tests/messaging/public.spec.ts
  apps/meteor/tests/e2e/federation/tests/user-account/user.spec.ts
  apps/meteor/tests/e2e/federation/utils/channel.ts
  apps/meteor/tests/e2e/federation/utils/test.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28087 Chore: improve global setup e2e
  apps/meteor/tests/e2e/config/global-setup.ts
Labels: stat: needs QA

#28092 Chore: Refactored Quotes component to use recursiveness
  ee/packages/pdf-worker/src/templates/ChatTranscript/components/Quotes.tsx
Labels: stat: needs QA

#28091 Regression: Scroll bars in sidebar
  apps/meteor/client/components/ScrollableContentWrapper.tsx
  apps/meteor/client/sidebar/RoomList/ScrollerWithCustomProps.tsx
Labels: stat: needs QA

#28075 Chore: QoL improvements to Omnichannel E2E tests
  apps/meteor/tests/e2e/omnichannel-auto-onhold-chat-closing.spec.ts
  apps/meteor/tests/e2e/omnichannel-auto-transfer-unanswered-chat.spec.ts
  apps/meteor/tests/e2e/omnichannel-canned-responses-sidebar.spec.ts
  apps/meteor/tests/e2e/omnichannel-chat-history.spec.ts
  apps/meteor/tests/e2e/omnichannel-contact-info.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments-ce.spec.ts
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/omnichannel-manager.spec.ts
  apps/meteor/tests/e2e/omnichannel-priorities.spec.ts
  apps/meteor/tests/e2e/omnichannel-takeChat.spec.ts
  apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel-triggers.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-manager.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-priorities.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#28097 Chore: fix e2e Omnichannel tests
  apps/meteor/client/components/GenericTable/V2/GenericTable.tsx
  apps/meteor/client/views/omnichannel/departments/ArchivedDepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable.tsx
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA skipped

#28082 Chore: test turbo cache action
  .github/workflows/build_and_test.yml
Labels: stat: needs QA

#28098 [BREAK] Upgrade to version 6.0 can be done only from version 5.x
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v241.ts
  apps/meteor/server/startup/migrations/v242.ts
  apps/meteor/server/startup/migrations/v243.ts
  apps/meteor/server/startup/migrations/v244.ts
  apps/meteor/server/startup/migrations/v245.ts
  apps/meteor/server/startup/migrations/v246.ts
  apps/meteor/server/startup/migrations/v247.ts
  apps/meteor/server/startup/migrations/v248.ts
  apps/meteor/server/startup/migrations/v249.ts
  apps/meteor/server/startup/migrations/v250.ts
  apps/meteor/server/startup/migrations/v251.ts
  apps/meteor/server/startup/migrations/v252.ts
  apps/meteor/server/startup/migrations/v253.ts
  apps/meteor/server/startup/migrations/v254.ts
  apps/meteor/server/startup/migrations/v255.ts
  apps/meteor/server/startup/migrations/v256.ts
  apps/meteor/server/startup/migrations/v257.ts
  apps/meteor/server/startup/migrations/v258.ts
  apps/meteor/server/startup/migrations/v259.ts
  apps/meteor/server/startup/migrations/v260.ts
  apps/meteor/server/startup/migrations/v261.ts
  apps/meteor/server/startup/migrations/v262.ts
  apps/meteor/server/startup/migrations/v263.ts
  apps/meteor/server/startup/migrations/v264.ts
  apps/meteor/server/startup/migrations/v265.ts
  apps/meteor/server/startup/migrations/v266.ts
Labels: stat: needs QA

#28073 Regression: Disable video message when composer is in use
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
Labels: stat: ready to merge, stat: QA skipped

#27706 [FIX] Filtering users by status username is broken in Administration -> Users
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/tests/end-to-end/api/01-users.js
Labels: stat: ready to merge, stat: QA tested

#28106 Chore: Move all variables to first step and reduce code duplication
  .github/workflows/build_and_test.yml
Labels: stat: needs QA

#28077 Regression: Fix agent departments select value
  apps/meteor/client/views/omnichannel/agents/AgentEditWithData.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28095 Regression: Broken message jump onto threads
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/app/ui-utils/client/lib/openRoom.tsx
  apps/meteor/client/lib/utils/jumpToMessage.ts
  apps/meteor/client/lib/utils/waitForElement.ts
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageJump.ts
Labels: stat: ready to merge, stat: QA tested

#28053 Regression: Fix department edit breaking
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithAllowedForwardData.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28051 Regression: Change wording on department removal setting
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#28121 Regression: Gracefully stop DDP Streamer publication and close WS
  ee/apps/ddp-streamer/src/Streamer.ts
Labels: stat: ready to merge, stat: QA skipped

#28122 Regression: Video Recorder "record" button alignment
  apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx
Labels: stat: needs QA

#28127 Regression: Fix slash command with preview
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopupPreview/ComposerBoxPopupPreview.tsx
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopupQueries.ts
Labels: stat: needs QA

#28134 Chore: Fix CI docker publish
  .github/workflows/ci-test-e2e.yml
Labels: stat: needs QA

#28138 Chore: Fix CI Docker Alpine build missing
  .github/workflows/ci.yml
Labels: stat: needs QA

#27993 Chore: Custom CSS
  apps/meteor/app/theme/client/imports/components/message-box.css
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
  apps/meteor/client/sidebar/footer/SidebarFooterDefault.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/team-management.spec.ts
  apps/meteor/tests/e2e/thread-actions.spec.ts
  ee/packages/ui-theming/src/PaletteStyleTag.tsx
  ee/packages/ui-theming/src/SidebarPaletteStyleTag.tsx
  ee/packages/ui-theming/src/hooks/useCreateStyleContainer.ts
  packages/ui-composer/src/MessageComposer/MessageComposerInput.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28058 Chore: Presence cap tweaks
  apps/meteor/client/sidebar/header/UserAvatarButton.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/sections/StatusDisabledSection.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusDisabledModal.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusRoute.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusService.tsx
  apps/meteor/client/views/admin/customUserStatus/hooks/useStatusDisabledModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#28125 Regression: Fix sidebar horizontal scrolling
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  ee/apps/omnichannel-transcript/package.json
  ee/apps/queue-worker/package.json
  ee/packages/omnichannel-services/package.json
  yarn.lock
Labels: stat: needs QA

#28079 Chore: Update tokens
  ee/packages/ui-theming/src/palette.ts
  ee/packages/ui-theming/src/paletteDark.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28128 Chore: Improve time of meteor build
  .github/actions/setup-node/action.yml
  .github/workflows/ci-code-check.yml
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci-test-unit.yml
  .github/workflows/ci.yml
  turbo.json
Labels: stat: needs QA

#28111 Regression: App requests notify admin function generating wrong link
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/AppMenu.js
  apps/meteor/ee/server/apps/communication/rest.js
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, stat: QA skipped, feat: marketplace

#28142 Regression: Slash commands detected at any line
  apps/meteor/client/lib/chats/flows/processSlashCommand.ts
  yarn.lock
Labels: stat: needs QA

#28129 Chore: Fix fetching Apps-Engine and MongoDB versions for release notes
  .houston/metadata.js
Labels: stat: ready to merge, stat: QA skipped

#28120 Regression: View mode preferences without the selected option by default
  apps/meteor/client/components/SortList/SortModeList.tsx
  apps/meteor/client/components/SortList/ViewModeList.tsx
Labels: stat: ready to merge, stat: QA tested

#28050 Regression: Fix improper usage of useEndpointData
  apps/meteor/client/views/omnichannel/currentChats/hooks/useCurrentChats.ts
  apps/meteor/client/views/omnichannel/directory/OmnichannelDirectoryPage.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatTab.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28153 Chore: Remove fail-fast from matrix strategy
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci-test-unit.yml
Labels: stat: needs QA

#28152 Chore: e2e omnichannel tests - Close every opened page after the test
  apps/meteor/tests/e2e/omnichannel-auto-onhold-chat-closing.spec.ts
  apps/meteor/tests/e2e/omnichannel-auto-transfer-unanswered-chat.spec.ts
  apps/meteor/tests/e2e/omnichannel-changing-room-priority-and-sla.spec.ts
  apps/meteor/tests/e2e/omnichannel-close-chat.spec.ts
  apps/meteor/tests/e2e/omnichannel-send-transcript.spec.ts
  apps/meteor/tests/e2e/omnichannel-takeChat.spec.ts
  apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
Labels: stat: needs QA

#28136 Chore: Convert small omni files to typescript
  .github/workflows/ci-test-e2e.yml
  apps/meteor/app/livechat/server/externalFrame/index.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/app/livechat/server/livechat.ts
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
  apps/meteor/app/livechat/server/sendMessageBySMS.ts
  apps/meteor/app/livechat/server/startup.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: needs QA

#28156 Regression: Fix RegisterForm Translations
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/web-ui-registration/src/RegisterForm.tsx
  packages/web-ui-registration/src/RegisterSecretPageRouter.tsx
  packages/web-ui-registration/src/SecretRegisterForm.tsx
Labels: stat: ready to merge, stat: QA skipped
