Repository RocketChat/Rocket.Chat, pull requests merged in 2023-01, with the labels that each got.

#27579 [NEW] Add export as PDF and send via email options
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/ToolBoxActionOptions.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/client/views/room/lib/QuickActions/defaultActions.ts
  apps/meteor/client/views/room/lib/QuickActions/index.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/omnichannel-send-transcript.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  ee/apps/omnichannel-transcript/src/service.ts
  packages/ui-client/src/components/Header/ToolBox/ToolBoxAction.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#27682 Chore: Upgrade EE license for CI
  .github/workflows/build_and_test.yml
Labels: stat: ready to merge, stat: QA skipped

#27493 [FIX] Team mention highlight EE
  apps/meteor/client/components/message/MessageContentBody.tsx
  packages/gazzodown/src/MarkupInteractionContext.ts
  packages/gazzodown/src/mentions/UserMentionElement.tsx
Labels: stat: ready to merge, stat: QA tested

#27188 [FIX] Showing Workspace Section For User Having LiveChat Manager Permission
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AdministrationList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AdministrationModelList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AppsModelList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AuditModelList.spec.tsx
Labels: stat: ready to merge, stat: QA tested

#27680 Regression: Rectifying thread layout
  apps/meteor/app/threads/client/threads.css
  apps/meteor/client/components/message/content/UrlPreviews.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerMessage.tsx
  apps/meteor/client/views/room/contexts/MessageContext.ts
  apps/meteor/client/views/room/contextualBar/Threads/Thread.tsx
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
  apps/meteor/client/views/room/providers/MessageProvider.tsx
  apps/meteor/tests/data/uploads.helper.ts
  apps/meteor/tests/end-to-end/api/20-licenses.js
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27683 Regression: Fix write stream error on user data export
  apps/meteor/server/lib/dataExport/processDataDownloads.ts
Labels: stat: needs QA

#27506 [FIX] Added form error validation for duplicated priority name
  apps/meteor/client/views/admin/settings/inputs/StringSettingInput.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
  apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27665 [IMPROVE] Increase read receipt size
  apps/meteor/client/components/message/ReadReceiptIndicator.tsx
Labels: stat: ready to merge, stat: QA tested

#27689 Chore: Reduce Less usage in theming
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/app/settings/server/SettingsRegistry.ts
  apps/meteor/app/theme/client/index.ts
  apps/meteor/app/theme/server/Theme.ts
  apps/meteor/app/theme/server/index.ts
  apps/meteor/app/theme/server/server.js
  apps/meteor/app/theme/server/server.ts
  apps/meteor/app/theme/server/variables.ts
  apps/meteor/client/startup/theme.ts
  apps/meteor/definition/externals/global.d.ts
  apps/meteor/definition/externals/less-plugin-autoprefixer.d.ts
  apps/meteor/definition/externals/less/browser.d.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27471 [IMPROVE] New marketplace routes
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPageHeader.tsx
  apps/meteor/client/views/marketplace/AppsList/AppRow.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsRoute.tsx
  apps/meteor/client/views/marketplace/AppsWhatIsIt.tsx
  apps/meteor/client/views/marketplace/MarketplaceRouter.tsx
  apps/meteor/client/views/marketplace/routes.tsx
  apps/meteor/client/views/marketplace/sidebarItems.ts
  apps/meteor/tests/unit/client/components/AdministrationList/AppsModelList.spec.tsx
Labels: stat: needs QA

#27671 [NEW] Add header component and load fonts to pdf react template
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  ee/apps/omnichannel-transcript/src/OmnichannelTranscript.ts
  packages/pdf-worker/.storybook/main.js
  packages/pdf-worker/.storybook/preview.js
  packages/pdf-worker/package.json
  packages/pdf-worker/src/assets/fonts/inter400.ttf
  packages/pdf-worker/src/assets/fonts/inter500.ttf
  packages/pdf-worker/src/assets/fonts/inter700.ttf
  packages/pdf-worker/src/stories/OmnichannelPDF.stories.tsx
  packages/pdf-worker/src/strategies/OmnichannelPDF.ts
  packages/pdf-worker/src/templates/transcriptTemplate.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/components/Divider.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/components/Header.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/components/Messages.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/components/OmnichannelTranscript.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/index.tsx
  packages/pdf-worker/src/types/Data.ts
  yarn.lock
Labels: stat: needs QA

#27329 [FIX] Remove unnecessary permissions check on app permissions review modal
  apps/meteor/client/views/admin/apps/AppMenu.js
Labels: stat: ready to merge, stat: QA skipped, feat: marketplace

#27575 i18n: Update Hungarian translation
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#27703 [BREAK] [FIX] VideoConference Ringer working intermittently on microservices
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/core-typings/src/IVideoConference.ts
Labels: stat: ready to merge, stat: QA skipped

#27551 [FIX] Anonymous user buttons
  apps/meteor/client/hooks/useRegisterAnonymousUserMutation.ts
  apps/meteor/client/views/room/components/body/composer/ComposerAnonymous.tsx
  apps/meteor/tests/e2e/anonymous-user.spec.ts
  apps/meteor/tests/e2e/omnichannel-manager.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA tested

#27691 Chore: Restrict legacy message events
  apps/meteor/app/emoji/client/lib/EmojiPicker.js
  apps/meteor/app/models/client/models/ChatMessage.ts
  apps/meteor/app/reactions/client/init.js
  apps/meteor/app/reactions/client/methods/setReaction.js
  apps/meteor/app/ui-message/client/message.html
  apps/meteor/app/ui/client/views/app/lib/getCommonRoomEvents.ts
  apps/meteor/client/components/message/content/Attachments.tsx
  apps/meteor/client/components/message/content/DiscussionMetrics.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/lib/portals/blazePortals.ts
  apps/meteor/client/lib/portals/createTemplateForComponent.ts
  apps/meteor/client/templates.ts
  apps/meteor/client/views/room/MessageList/MessageList.tsx
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/client/views/room/components/body/LegacyMessageTemplateList.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxBlazeWrapper.tsx
  apps/meteor/client/views/room/components/body/useLegacyMessageRef.ts
  apps/meteor/client/views/room/contextualBar/Threads/Thread.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/LegacyThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageListScrolling.ts
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageRef.ts
  apps/meteor/client/views/room/hooks/useLegacyMessageEvents.ts
  apps/meteor/client/views/room/providers/MessageProvider.tsx
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/MarkdownTextEditor/index.tsx
  packages/gazzodown/package.json
Labels: stat: ready to merge, stat: QA skipped

#27601 [FIX] Discussion visibility when inside a private team.
  apps/meteor/app/authorization/server/functions/canSendMessage.ts
  apps/meteor/app/autotranslate/server/autotranslate.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/definition/IRoomTypeConfig.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/lib/rooms/roomTypes/public.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
Labels: stat: ready to merge, automerge, stat: QA tested

#27714 Regression: Composer Toolbox overlapping borders
  packages/ui-composer/src/MessageComposer/MessageComposer.tsx
Labels: stat: ready to merge, automerge, stat: QA skipped

#27500 [NEW] Create enterprise apps page
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/hooks/useFilteredApps.ts
  apps/meteor/client/views/marketplace/sidebarItems.ts
Labels: stat: needs QA

#27672 [NEW] Rocket.cat message for users when an app previously requested is installed
  apps/meteor/app/apps/client/orchestrator.ts
  apps/meteor/app/apps/server/appRequestsCron.ts
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/apps/server/index.ts
  apps/meteor/app/apps/server/marketplace/appRequestNotifyUsers.ts
  apps/meteor/app/apps/server/orchestrator.js
  apps/meteor/client/views/admin/apps/AppMenu.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/lib/sendDirectMessageToUsers.ts
  packages/core-typings/src/AppRequests.ts
  packages/core-typings/src/MarketplaceRest.ts
  packages/core-typings/src/index.ts
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, stat: QA skipped, feat: marketplace

#27513 [FIX] Save button does not stay disabled in Notification Preferences for no change on mute group option
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.tsx
Labels: stat: ready to merge, communityPR, stat: QA skipped

#27734 Regression: Missing contexts on contextual bar
  apps/meteor/client/components/message/content/BroadcastMetrics.tsx
  apps/meteor/client/components/message/content/DiscussionMetrics.tsx
  apps/meteor/client/components/message/content/ThreadMetrics.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
  apps/meteor/client/views/room/components/BlazeTemplate.tsx
  apps/meteor/client/views/room/components/VerticalBarOldActions.tsx
Labels: stat: ready to merge, stat: QA skipped

#27330 [FIX] Marketplace app status initially disabled
  apps/meteor/client/views/admin/apps/helpers.ts
Labels: stat: ready to merge, stat: QA tested, feat: marketplace

#27631 Chore: Invites Empty State
  apps/meteor/client/views/admin/invites/InviteRow.tsx
  apps/meteor/client/views/admin/invites/InvitesPage.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
Labels: stat: ready to merge, stat: QA skipped

#27075 Chore: add e2e test coverage for Video Conference
  apps/meteor/tests/e2e/apps.spec.ts
  apps/meteor/tests/e2e/config/global-setup.ts
  apps/meteor/tests/e2e/fixtures/insert-apps.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/utils/create-target-channel.ts
  apps/meteor/tests/e2e/video-conference-ring.spec.ts
  apps/meteor/tests/e2e/video-conference.spec.ts
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.tsx
Labels: stat: ready to merge, stat: QA skipped

#27405 [IMPROVE] SAML and OAuth role sync to support id and name
  apps/meteor/ee/server/configuration/oauth.ts
  apps/meteor/ee/server/configuration/saml.ts
  apps/meteor/ee/server/lib/oauth/Manager.ts
  apps/meteor/server/models/raw/Roles.ts
  packages/model-typings/src/models/IRolesModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27699 [FIX] Missing placeholders from encrypted channel preview messages now with expected behavior
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.tsx
Labels: stat: ready to merge, stat: QA tested

#27754 Regression: Broken room and message composer events
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerMessage.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
Labels: stat: ready to merge, stat: QA skipped

#27737 [FIX] Incorrect sorting policy for conflicts withing priorities and SLA's
  apps/meteor/app/livechat/lib/inquiries.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/models/server/models/LivechatInquiry.ts
  apps/meteor/client/definitions/SubscriptionWithRoom.ts
  apps/meteor/client/startup/mergeSubscriptionsAndRooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/SlaNPriorityHelper.ts
  apps/meteor/ee/server/models/raw/LivechatInquiry.ts
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/tests/data/livechat/priorities.ts
  apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
  packages/core-typings/src/IInquiry.ts
  packages/core-typings/src/IOmnichannelServiceLevelAgreements.ts
  packages/core-typings/src/IRoom.ts
Labels: stat: needs QA

#27556 [IMPROVE] Require acceptance when setting new E2E Encryption key for another user
  apps/meteor/app/api/server/v1/e2e.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.room.js
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/e2e/server/functions/handleSuggestedGroupKey.ts
  apps/meteor/app/e2e/server/methods/updateGroupKey.js
  apps/meteor/app/e2e/server/methods/updateGroupKey.ts
  apps/meteor/app/models/server/models/Subscriptions.js
  apps/meteor/client/startup/e2e.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/server/modules/watchers/publishFields.ts
  packages/core-typings/src/ISubscription.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
  packages/rest-typings/src/v1/e2e.ts
Labels: stat: ready to merge, stat: QA tested

#27632 Chore: Custom Sounds Empty State
  apps/meteor/client/views/admin/customSounds/AddCustomSound.tsx
  apps/meteor/client/views/admin/customSounds/CustomSoundsRoute.tsx
  apps/meteor/client/views/admin/customSounds/EditSound.tsx
  apps/meteor/client/views/admin/routes.tsx
Labels: stat: ready to merge, stat: QA skipped

#27317 [FIX] Auto Translate not working on new message template
  .vscode/settings.json
  apps/meteor/app/autotranslate/client/lib/actionButton.ts
  apps/meteor/app/autotranslate/client/lib/autotranslate.ts
  apps/meteor/app/autotranslate/server/autotranslate.ts
  apps/meteor/app/autotranslate/server/googleTranslate.ts
  apps/meteor/app/ui-message/client/message.html
  apps/meteor/app/ui-message/client/message.js
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/components/message/StatusIndicators.tsx
  apps/meteor/client/components/message/content/attachments/file/AudioAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/GenericFileAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/ImageAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/VideoAttachment.tsx
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.tsx
  apps/meteor/client/lib/utils/messageArgs.ts
  apps/meteor/client/views/room/MessageList/MessageList.tsx
  apps/meteor/client/views/room/MessageList/contexts/MessageListContext.tsx
  apps/meteor/client/views/room/MessageList/hooks/useAutoTranslate.ts
  apps/meteor/client/views/room/MessageList/hooks/useAutotranslateLanguage.ts
  apps/meteor/client/views/room/MessageList/hooks/useKatex.ts
  apps/meteor/client/views/room/MessageList/hooks/useMessageBody.tsx
  apps/meteor/client/views/room/MessageList/hooks/useMessages.ts
  apps/meteor/client/views/room/MessageList/lib/autoTranslate.ts
  apps/meteor/client/views/room/MessageList/lib/parseMessageTextToAstMarkdown.ts
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/tests/unit/client/views/room/MessageList/hooks/useAutoTranslate.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/hooks/useKatex.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/autoTranslate.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/parseMessage.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/parseMessageAttachments.spec.ts
  apps/meteor/tests/unit/client/views/room/MessageList/lib/parseMessageQuoteAttachment.spec.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentDefault.ts
  packages/core-typings/src/IMessage/MessageAttachment/TranslatedMessageAttachment.ts
  packages/core-typings/src/IMessage/MessageAttachment/index.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#27293 Chore: Change bundle tags color and refactor app details page header styles
  apps/meteor/client/components/avatar/AppAvatar.tsx
  apps/meteor/client/views/admin/apps/AppDetailsPage/AppDetailsPageHeader.tsx
  apps/meteor/client/views/admin/apps/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/admin/apps/AppsList/AppRow.tsx
  apps/meteor/client/views/admin/apps/BundleChips.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, feat: marketplace

#27729 Chore: Show different labels based on the call originator on direct calls
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
Labels: stat: ready to merge, stat: QA tested

#27765 Chore: Add surface-light background to AppRow
  apps/meteor/client/views/admin/apps/AppsList/AppRow.tsx
Labels: stat: ready to merge, stat: QA skipped

#27766 [FIX] App page showing version undefined for apps not in marketplace
  apps/meteor/client/views/admin/apps/AppDetailsPage/AppDetailsPageHeader.tsx
Labels: stat: ready to merge, stat: QA skipped

#27741 [FIX] Changed sorting mechanism select option from "Service level agreement" to "SLA Policies"
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27470 [NEW] Attachment Files Redesign
  apps/meteor/app/file-upload/server/lib/FileUpload.js
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/client/components/message/MessageCollapsible.tsx
  apps/meteor/client/components/message/content/attachments/FileAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/AudioAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/GenericFileAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/ImageAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/VideoAttachment.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentDownload.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentImage.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentSize.tsx
  apps/meteor/client/components/message/content/urlPreviews/OEmbedCollapsible.tsx
  apps/meteor/client/providers/AttachmentProvider.tsx
  apps/meteor/client/views/room/MessageList/lib/parseMessageTextToAstMarkdown.ts
  apps/meteor/lib/utils/getFileExtension.ts
  apps/meteor/server/hooks/messages/markdownParser.ts
  apps/meteor/tests/e2e/imports.spec.ts
  apps/meteor/tests/e2e/message-mentions.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentBase.ts
  packages/ui-contexts/src/AttachmentContext.ts
Labels: stat: ready to merge, stat: QA tested

#27638 [IMPROVE] Added priority field to edit room contextual bar
  apps/meteor/client/components/Omnichannel/Tags.tsx
  apps/meteor/client/views/omnichannel/components/CustomField.js
  apps/meteor/client/views/omnichannel/components/CustomField.tsx
  apps/meteor/client/views/omnichannel/components/Info.tsx
  apps/meteor/client/views/omnichannel/directory/CallsContextualBarDirectory.tsx
  apps/meteor/client/views/omnichannel/directory/ChatsContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/ContactContextualBar.js
  apps/meteor/client/views/omnichannel/directory/ContactContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/ContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/OmnichannelDirectoryPage.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTableRow.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfoCallButton.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/AgentField.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfoDirectory.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatsContextualBar.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatsContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ContactField.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/DepartmentField.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/PriorityField.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEditWithData.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/index.ts
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEditWithData.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/VisitorClientInfo.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/VisitorData.js
  apps/meteor/client/views/omnichannel/directory/components/AgentField.tsx
  apps/meteor/client/views/omnichannel/directory/components/CallDialpadButton.tsx
  apps/meteor/client/views/omnichannel/directory/components/ContactField.tsx
  apps/meteor/client/views/omnichannel/directory/components/FormSkeleton.tsx
  apps/meteor/client/views/omnichannel/directory/components/PriorityField.tsx
  apps/meteor/client/views/omnichannel/directory/components/SlaField.tsx
  apps/meteor/client/views/omnichannel/directory/components/SourceField.tsx
  apps/meteor/client/views/omnichannel/directory/components/index.ts
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactEditWithData.js
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useCustomFieldsMetadata.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/usePrioritiesData.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/usePriorityInfo.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useRoomInfo.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useSlaInfo.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useSlaPolicies.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useVisitorInfo.tsx
  apps/meteor/client/views/omnichannel/directory/utils/formatCustomFieldsMetadata.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/PrioritiesSelect.js
  apps/meteor/ee/client/omnichannel/additionalForms/PrioritiesSelect.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/SlaPoliciesSelect.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/register.ts
  apps/meteor/ee/client/omnichannel/priorities/PriorityEditFormWithData.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/core-typings/src/ILivechatVisitor.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#27767 Regression: Add support for 2FA errors to `Meteor.callAsync`
  apps/meteor/app/2fa/client/overrideMeteorCall.ts
  apps/meteor/client/lib/2fa/process2faReturn.ts
Labels: stat: ready to merge, stat: QA skipped

#27521 [NEW] Implement first phase of the app request flow
  apps/meteor/app/apps/client/orchestrator.ts
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPageTabs.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/AppMenu.js
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsPage/NoInstalledAppsEmptyState.tsx
  apps/meteor/client/views/marketplace/AppsProvider.tsx
  apps/meteor/client/views/marketplace/AppsRoute.tsx
  apps/meteor/client/views/marketplace/helpers.ts
  apps/meteor/tests/unit/client/components/AdministrationList/AdministrationList.spec.tsx
  apps/meteor/tests/unit/client/components/AdministrationList/AppsModelList.spec.tsx
  packages/rest-typings/src/apps/index.ts
Labels: stat: needs QA, feat: marketplace

#27784 Chore: Remove medium prop from ButtonGroup
  apps/meteor/client/components/VerticalBar/VerticalBarActions.tsx
  apps/meteor/client/components/message/content/attachments/default/ActionAttachtment.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/client/views/admin/apps/AppDetailsPage/tabs/AppDetails/AppDetails.tsx
  packages/ui-client/src/components/Card/CardFooter.tsx
  packages/ui-client/src/components/Header/ToolBox/ToolBox.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupControllers.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooterButtons.tsx
  packages/web-ui-registration/src/RegisterFormDisabled.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27769 [NEW] Create generic upsell modal component
  apps/meteor/client/components/UpsellModal.stories.tsx
  apps/meteor/client/components/UpsellModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#27532 Chore: change colors to dark theme on Marketplace
  apps/meteor/client/views/admin/apps/AppDetailsPage/tabs/AppDetails/AppDetails.tsx
Labels: stat: ready to merge, stat: QA skipped

#27690 Chore: Move service shutdown logic to each service
  apps/meteor/ee/app/license/server/license.internalService.ts
  apps/meteor/ee/server/NetworkBroker.ts
  apps/meteor/ee/server/lib/EnterpriseCheck.ts
Labels: stat: needs QA

#27745 [IMPROVE] Emoji picker for large amount of custom emojis
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.js
  apps/meteor/app/emoji-custom/server/startup/emoji-custom.js
  apps/meteor/app/emoji/client/emojiPicker.js
  apps/meteor/app/emoji/client/lib/EmojiPicker.js
  apps/meteor/app/theme/client/imports/components/emojiPicker.css
Labels: stat: ready to merge, stat: QA skipped

#27768 Chore: remove request button when chat is close
  apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx
  apps/meteor/tests/unit/client/components/Omnichannel/modals/TranscriptModal.spec.tsx
Labels: stat: ready to merge, stat: QA tested

#27816 [FIX] Not all messages in chat conversations are available when forwarding between agents or departments.
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
Labels: stat: ready to merge, stat: QA tested

#27624 [FIX] Toast notification ignoring 403 errors
  apps/meteor/app/utils/client/lib/RestApiClient.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#27740 Chore: OmnichannelRoomIconProvider order breaking VideoConfPopup
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/views/root/AppRoot.tsx
Labels: stat: needs QA

#27716 [FIX] Unintended "Reply on thread" button showing on thread's first message
  apps/meteor/client/components/message/ToolboxHolder.tsx
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: ready to merge, stat: QA tested

#27756 [NEW] Create upsell modal
  apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/images/unlimited-apps-modal.svg
Labels: stat: needs QA

#27840 Release 5.4.2
  .github/history.json
  .github/workflows/build_and_test.yml
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/api/server/v1/channels.js
  apps/meteor/app/api/server/v1/groups.js
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/app/custom-oauth/server/custom_oauth_server.js
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.js
  apps/meteor/app/emoji-custom/server/startup/emoji-custom.js
  apps/meteor/app/emoji/client/emojiPicker.js
  apps/meteor/app/emoji/client/lib/EmojiPicker.js
  apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/app/file-upload/server/lib/FileUpload.js
  apps/meteor/app/lib/server/methods/deleteMessage.ts
  apps/meteor/app/theme/client/imports/components/emojiPicker.css
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/client/views/root/AppRoot.tsx
  apps/meteor/ee/server/configuration/oauth.ts
  apps/meteor/ee/server/lib/oauth/Manager.ts
  apps/meteor/package.json
  apps/meteor/server/models/raw/Uploads.ts
  apps/meteor/tests/data/uploads.helper.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
  apps/meteor/tests/end-to-end/api/04-direct-message.js
  package.json
  packages/model-typings/src/models/IUploadsModel.ts
Labels: stat: needs QA

#27718 [FIX] asyncawaitify app converters
  apps/meteor/app/apps/lib/misc/transformMappedData.js
  apps/meteor/app/apps/server/communication/rest.js
  apps/meteor/app/apps/server/communication/uikit.ts
  apps/meteor/ee/app/apps/bridges/commands.ts
  apps/meteor/ee/app/apps/bridges/listeners.js
  apps/meteor/ee/app/apps/bridges/livechat.ts
  apps/meteor/ee/app/apps/bridges/messages.ts
  apps/meteor/ee/app/apps/bridges/rooms.ts
  apps/meteor/ee/app/apps/bridges/settings.ts
  apps/meteor/ee/app/apps/bridges/users.ts
  apps/meteor/ee/app/apps/converterService.ts
  apps/meteor/ee/app/apps/converters/departments.js
  apps/meteor/ee/app/apps/converters/messages.js
  apps/meteor/ee/app/apps/converters/rooms.js
  apps/meteor/ee/app/apps/converters/uploads.js
  apps/meteor/ee/app/apps/converters/users.js
  apps/meteor/ee/app/apps/converters/visitors.js
  apps/meteor/ee/app/apps/service.ts
  apps/meteor/server/sdk/types/IAppsConverterService.ts
  yarn.lock
Labels: stat: needs QA

#27850 Chore: Refactor `VideoMessageRecorder`
  apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
  apps/meteor/app/ui-message/client/messageBox/messageBoxActions.ts
  apps/meteor/app/ui-vrecord/client/VRecDialog.js
  apps/meteor/app/ui-vrecord/client/index.js
  apps/meteor/app/ui-vrecord/client/vrecord.css
  apps/meteor/app/ui-vrecord/client/vrecord.html
  apps/meteor/app/ui-vrecord/client/vrecord.js
  apps/meteor/client/importPackages.ts
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/views/composer/AudioMessageRecorder/AudioMessageRecorder.tsx
  apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx
  apps/meteor/client/views/composer/VideoMessageRecorder/index.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#27789 [FIX] Disable video call on read-only rooms for not allowed users
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/tests/e2e/utils/create-target-channel.ts
  apps/meteor/tests/e2e/video-conference.spec.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/channels/ChannelsCreateProps.ts
  packages/rest-typings/src/v1/channels/channels.ts
  packages/rest-typings/src/v1/channels/index.ts
Labels: stat: ready to merge, stat: QA tested

#27863 [FIX] Emoji rendering on reactions
  apps/meteor/client/lib/utils/renderEmoji.ts
Labels: stat: ready to merge, stat: QA skipped

#27646 Chore: Refactor Directory Tables
  apps/meteor/client/components/RoomIcon/RoomIcon.tsx
  apps/meteor/client/views/directory/ChannelsTable.js
  apps/meteor/client/views/directory/DirectoryPage.tsx
  apps/meteor/client/views/directory/RoomTags.tsx
  apps/meteor/client/views/directory/TeamsTable.js
  apps/meteor/client/views/directory/tabs/channels/ChannelsTab.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTable.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTableRow.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/index.ts
  apps/meteor/client/views/directory/tabs/teams/TeamsTab.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTable.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTableRow.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/index.ts
  apps/meteor/client/views/directory/tabs/users/UsersTab.tsx
  apps/meteor/client/views/directory/tabs/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/directory/tabs/users/UsersTable/UsersTableRow.tsx
  apps/meteor/client/views/directory/tabs/users/UsersTable/index.ts
Labels: stat: ready to merge, stat: QA skipped

#27857 Regression: fix close flextab on click outside the container
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/message-actions.spec.ts
Labels: stat: needs QA

#27874 Chore: Do not rely on external service on tests
  apps/meteor/tests/end-to-end/api/05-chat.js
Labels: stat: needs QA

#27647 [BREAK] Remove less theming
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/theme/client/imports/general/variables.css
  apps/meteor/app/theme/server/Theme.ts
  apps/meteor/app/theme/server/server.ts
  apps/meteor/app/theme/server/variables.ts
  apps/meteor/app/ui-login/username/username.html
  apps/meteor/app/ui-master/client/error.html
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/theme.ts
  apps/meteor/client/views/hooks/useExperimentalTheme.ts
  apps/meteor/client/views/invite/InvitePage.tsx
  apps/meteor/client/views/mailer/MailerUnsubscriptionPage.tsx
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  ee/packages/ui-theming/src/PaletteStyleTag.tsx
  ee/packages/ui-theming/src/SidebarPaletteStyleTag.tsx
  ee/packages/ui-theming/src/hooks/useThemeMode.ts
  yarn.lock
Labels: documentation: needed, stat: needs QA

#27870 Regression: Undefined default message context
  apps/meteor/app/ui-utils/client/lib/messageContext.ts
Labels: stat: needs QA

#27862 Chore: Update Some Composer Icons
  apps/meteor/app/ui-message/client/messageBox/messageBoxFormatting.ts
  apps/meteor/client/views/composer/AudioMessageRecorder/AudioMessageRecorder.tsx
  apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27673 Chore: use useQuery in place of deprecated useEndpointData
  apps/meteor/client/views/admin/apps/AppDetailsPage/tabs/AppReleases/AppReleases.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmojiWithData.tsx
  apps/meteor/client/views/admin/customSounds/CustomSoundsRoute.tsx
  apps/meteor/client/views/admin/customSounds/EditCustomSound.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusFormWithData.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusTable/CustomUserStatusTable.tsx
  apps/meteor/client/views/admin/integrations/IntegrationsTable.js
  apps/meteor/client/views/admin/integrations/edit/EditIncomingWebhookWithData.js
  apps/meteor/client/views/admin/integrations/edit/EditOutgoingWebhookWithData.js
  apps/meteor/client/views/admin/invites/InvitesPage.tsx
  apps/meteor/client/views/admin/oauthApps/EditOauthAppWithData.tsx
  apps/meteor/client/views/admin/oauthApps/OAuthAppsTable.tsx
  apps/meteor/client/views/admin/permissions/UsersInRole/UsersInRoleTable/UsersInRoleTableWithData.tsx
  apps/meteor/client/views/admin/rooms/EditRoomWithData.tsx
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/client/views/admin/users/AddUser.js
  apps/meteor/client/views/admin/users/AdminUserInfoWithData.tsx
  apps/meteor/client/views/admin/users/EditUserWithData.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
Labels: stat: ready to merge, stat: QA skipped

#27825 [IMPROVE] Livechat Persian translation
  packages/livechat/src/i18n/fa.json
Labels: stat: needs QA

#27872 Chore: Improve service's licence check
  apps/meteor/ee/server/lib/EnterpriseCheck.ts
Labels: stat: ready to merge, stat: QA skipped

#27750 [NEW] Add files component to chat transcript template
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/Messages.ts
  ee/apps/omnichannel-transcript/package.json
  ee/apps/omnichannel-transcript/src/OmnichannelTranscript.ts
  packages/model-typings/src/models/IMessagesModel.ts
  packages/pdf-worker/.storybook/main.js
  packages/pdf-worker/README.md
  packages/pdf-worker/jest.config.js
  packages/pdf-worker/package.json
  packages/pdf-worker/public/inter400.ttf
  packages/pdf-worker/public/inter500.ttf
  packages/pdf-worker/public/inter700.ttf
  packages/pdf-worker/src/index.ts
  packages/pdf-worker/src/stories/OmnichannelPDF.stories.tsx
  packages/pdf-worker/src/strategies/ChatTranscript.spec.ts
  packages/pdf-worker/src/strategies/ChatTranscript.ts
  packages/pdf-worker/src/strategies/OmnichannelPDF.ts
  packages/pdf-worker/src/templates/ChatTranscript/ChatTranscript.fixtures.ts
  packages/pdf-worker/src/templates/ChatTranscript/ChatTranscript.stories.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/Divider.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/Files.spec.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/Files.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/Header.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/MessageContent.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/MessageHeader.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/MessageList.spec.tsx
  packages/pdf-worker/src/templates/ChatTranscript/components/MessageList.tsx
  packages/pdf-worker/src/templates/ChatTranscript/index.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/components/Messages.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/components/OmnichannelTranscript.tsx
  packages/pdf-worker/src/templates/transcriptTemplate/index.tsx
  packages/pdf-worker/src/types/Data.ts
  yarn.lock
Labels: stat: needs QA

#27539 [FIX] Unread Message count not displayed for new messages in Omni-Rooms
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.js
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/subscriptions.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel
