Repository RocketChat/Rocket.Chat, pull requests merged in 2023-07, with the labels that each got.

#29696 chore: bump turbo
  package.json
  turbo.json
  yarn.lock
Labels: stat: needs QA

#29635 fix: Required custom field consider blank space as valid input
  .changeset/olive-pears-sell.md
  packages/ui-client/src/components/CustomFieldsForm.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29673 fix: livechat url triggers only fire when using the widget
  packages/livechat/src/lib/triggers.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29652 regression: Livechat UiKit button not working
  apps/meteor/server/models/raw/LivechatRooms.ts
  packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/ddp-client/src/livechat/types/LivechatSDK.ts
  packages/livechat/src/lib/uiKit.js
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29169 fix: Omnichannel Tags available to be used in the wrong department
  .changeset/great-brooms-invent.md
  apps/meteor/client/components/Omnichannel/Tags.tsx
  apps/meteor/client/components/Omnichannel/hooks/useLivechatTags.ts
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/departments.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/tags.ts
  apps/meteor/ee/client/hooks/useTagsList.ts
  apps/meteor/ee/client/omnichannel/tags/AutoCompleteTagsMultiple.js
  apps/meteor/ee/client/omnichannel/tags/CurrentChatTags.tsx
  apps/meteor/ee/client/omnichannel/tags/TagsTable.tsx
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/tests/data/livechat/tags.ts
  apps/meteor/tests/end-to-end/api/livechat/13-tags.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28783 feat: Add custom OAuth setting to allow merging users to others from distinct services
  .changeset/dirty-singers-promise.md
  apps/meteor/app/custom-oauth/server/custom_oauth_server.js
  apps/meteor/app/lib/server/functions/addOAuthService.ts
  apps/meteor/app/lib/server/startup/oAuthServicesUpdate.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/v300.ts
  packages/rest-typings/src/v1/settings.ts
Labels: stat: ready to merge, stat: QA tested, squad: WM

#29606 chore: Device Management version info at table and contextual bar
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminRow.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfo.tsx
Labels: stat: ready to merge, stat: QA tested, squad: WM

#29524 fix: call-management permission not doing anything
  .changeset/call-management-permission.md
  apps/meteor/app/api/server/v1/videoConference.ts
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/app/videobridge/client/tabBar.tsx
Labels: feat: video conferencing, stat: ready to merge, stat: QA tested

#29703 chore: upgrading fuselage package
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#29708 chore: update button-secondary colors
  ee/packages/ui-theming/src/paletteDark.ts
Labels: stat: ready to merge, stat: QA skipped

#29682 fix: Video Conf information block not updating automatically
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/core-services/src/Events.ts
Labels: stat: needs QA

#29681 chore: Improve performance of getActiveLocalUserCount
  apps/meteor/server/models/raw/Users.js
Labels: stat: ready to merge, stat: QA skipped

#29653 ci: fixing and updating Stale action
  .github/workflows/stale.yml
Labels: stat: ready to merge, stat: QA skipped

#29552 refactor: Administration sidebar reorg
  apps/meteor/client/views/admin/customEmoji/CustomEmojiRoute.tsx
  apps/meteor/client/views/admin/customSounds/CustomSoundsPage.tsx
  apps/meteor/client/views/admin/federationDashboard/FederationDashboardPage.tsx
  apps/meteor/client/views/admin/info/InformationPage.tsx
  apps/meteor/client/views/admin/info/InformationRoute.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsolePage.tsx
  apps/meteor/client/views/admin/oauthApps/OAuthAppsPage.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/admin/viewLogs/ViewLogsPage.tsx
  apps/meteor/ee/client/startup/engagementDashboard.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardPage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/administration-menu.spec.ts
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/engagement-dashboard.spec.ts
  yarn.lock
Labels: stat: needs QA, feat: workspace-mgmt, squad: WM

#29685 fix: avatar is reset in the UI when username is changed
  .changeset/green-icons-smash.md
  apps/meteor/app/lib/server/functions/saveUserIdentity.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28181 fix: sound status goes out of window on popout mode
  packages/livechat/src/components/Screen/Header.js
Labels: stat: ready to merge, communityPR, stat: QA skipped, feat: omnichannel

#29719 chore: throttle exceptions counter increment
  apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.ts
  apps/meteor/app/lib/server/lib/meteorFixes.js
  apps/meteor/ee/server/startup/seatsCap.ts
  apps/meteor/lib/utils/throttledCounter.ts
Labels: stat: QA skipped

#29712 chore: device management improve readability and performance
  apps/meteor/ee/server/lib/deviceManagement/session.ts
  apps/meteor/ee/server/startup/deviceManagement.ts
  apps/meteor/server/models/raw/Users.js
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA skipped

#29718 fix(meteor): `room-opened` event not dispatching when navigating cached rooms
  .changeset/hip-hornets-fail.md
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
Labels: stat: needs QA

#29722 regression: Livechat not unsubscribing after the chat is closed
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
  packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/livechat/src/lib/room.js
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#29697 feat: Introduce contextualBar surface renderer for UiKit blocks
  .changeset/popular-donkeys-laugh.md
  apps/meteor/client/views/room/contextualBar/Apps/Apps.tsx
  packages/fuselage-ui-kit/src/contexts/SurfaceContext.ts
  packages/fuselage-ui-kit/src/contexts/kitContext.ts
  packages/fuselage-ui-kit/src/surfaces/ContextualBarSurface.tsx
  packages/fuselage-ui-kit/src/surfaces/FuselageContextualBarRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/index.ts
  packages/fuselage-ui-kit/src/utils/UiKitComponent.tsx
  packages/uikit-playground/package.json
  packages/uikit-playground/src/Components/Preview/Display/Surface/ContextualBarSurface.tsx
  packages/uikit-playground/src/Components/Preview/Display/Surface/Surface.tsx
  packages/uikit-playground/src/Components/SurfaceSelect/options.ts
  yarn.lock
Labels: stat: needs QA

#29728 chore: Add missing migration to index
  apps/meteor/server/startup/migrations/index.ts
Labels: stat: ready to merge, stat: QA skipped

#28912 fix: Time format in quoted message according to user preference
  .changeset/timeFormat.md
  apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx
  apps/meteor/client/hooks/useTimeAgo.ts
Labels: stat: ready to merge, communityPR, stat: QA tested

#29727 fix: Toggle message box formatting toolbar on click
  .changeset/fuzzy-parents-drop.md
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/FormattingToolbarDropdown.tsx
Labels: stat: ready to merge, stat: QA tested

#29543 fix: Remove the association between BH and disabled/archived departments
  .changeset/funny-coins-trade.md
  .changeset/rotten-spoons-teach.md
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/app/livechat/server/business-hour/BusinessHourManager.ts
  apps/meteor/app/livechat/server/business-hour/Single.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/lib/business-hour.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/app/livechat-enterprise/server/startup.ts
  apps/meteor/ee/client/omnichannel/additionalForms/BusinessHoursMultiple.js
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/LivechatBusinessHours.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  apps/meteor/tests/data/livechat/business-hours.ts
  apps/meteor/tests/data/livechat/businessHours.ts
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
  packages/model-typings/src/models/ILivechatBusinessHoursModel.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29540 fix: Only update online & unavailable agents when opening business hours
  .changeset/thirty-lobsters-vanish.md
  apps/meteor/app/livechat/server/business-hour/Helper.ts
  apps/meteor/app/livechat/server/business-hour/Single.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
  apps/meteor/server/models/raw/Users.js
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29735 chore: Most used emojis as `quickReactions`
  apps/meteor/app/emoji/client/helpers.ts
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/contexts/EmojiPickerContext.ts
  apps/meteor/client/providers/EmojiPickerProvider.tsx
Labels: stat: needs QA

#29709 fix: Clear MessageBox popup on message send
  .changeset/rare-dingos-boil.md
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#29624 fix: Last message appears in extended view after deletion
  .changeset/modern-geese-laugh.md
  apps/meteor/app/lib/server/functions/deleteMessage.ts
Labels: stat: ready to merge, stat: QA tested

#29750 chore: console warning on sending messages
  apps/meteor/app/lib/client/methods/sendMessage.ts
Labels: stat: ready to merge, stat: QA skipped

#29753 regression: Omit `quickReactions` based on `MessageContext`
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
Labels: stat: ready to merge, stat: QA skipped

#29698 feat: Introduce Feature Preview page
  .changeset/fair-rivers-occur.md
  apps/meteor/app/reactions/client/init.js
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/hooks/useFeaturePreview.ts
  apps/meteor/client/hooks/useFeaturePreviewList.ts
  apps/meteor/client/sidebar/header/hooks/useAccountItems.tsx
  apps/meteor/client/sidebar/header/index.tsx
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewBadge.tsx
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.tsx
  apps/meteor/client/views/account/routes.tsx
  apps/meteor/client/views/account/sidebarItems.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/images/featurePreview/quick-reactions.png
  apps/meteor/server/settings/accounts.ts
  packages/rest-typings/src/v1/users/UsersSetPreferenceParamsPOST.ts
  yarn.lock
Labels: stat: needs QA

#29662 ci: create reporter
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
  apps/meteor/playwright.config.ts
  apps/meteor/reporters/rocketchat.ts
Labels: stat: needs QA

#29745 chore: improve server error handling
  apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.ts
  apps/meteor/app/lib/server/lib/meteorFixes.js
Labels: stat: ready to merge, stat: QA skipped

#29734 test: remove tests that were not unit tests
  .github/workflows/ci-test-unit.yml
  apps/meteor/tests/unit/app/models/server/raw/Sessions.tests.js
Labels: stat: ready to merge, stat: QA skipped

#29647 chore: Update VideoConferenceBlock user stack size
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageUserStack.tsx
Labels: stat: ready to merge, stat: QA skipped

#29754 regression: Wrong addon usage on account menu itens
  apps/meteor/client/sidebar/header/hooks/useAccountItems.tsx
Labels: stat: needs QA

#29749 regression: `UserMenu` add missing translations
  apps/meteor/client/sidebar/header/hooks/useUserMenu.tsx
Labels: stat: QA skipped

#29752 ci: Improve release automation
  .changeset/config.json
  .changeset/nine-yaks-draw.md
  .github/workflows/changesets.yml
  .github/workflows/publish-release.yml
  package.json
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/fixWorkspaceVersionsBeforePublish.ts
  packages/release-action/src/gitUtils.ts
  packages/release-action/src/publishRelease.ts
  packages/release-action/src/startPatchRelease.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29751 chore: `GenericMenu` logic to add gap
  apps/meteor/client/components/GenericMenu/GenericMenu.tsx
  apps/meteor/client/components/GenericMenu/GenericMenuItem.tsx
Labels: stat: ready to merge, stat: QA skipped

#29391 fix: mentions and emojis inside bold, italic and strikethrough
  .changeset/mentions-emoji-emphasis.md
  ee/packages/pdf-worker/src/templates/ChatTranscript/markup/elements/BoldSpan.tsx
  ee/packages/pdf-worker/src/templates/ChatTranscript/markup/elements/ItalicSpan.tsx
  ee/packages/pdf-worker/src/templates/ChatTranscript/markup/elements/StrikeSpan.tsx
  packages/gazzodown/src/elements/BoldSpan.tsx
  packages/gazzodown/src/elements/ImageElement.tsx
  packages/gazzodown/src/elements/ItalicSpan.tsx
  packages/gazzodown/src/elements/StrikeSpan.tsx
  yarn.lock
Labels: stat: ready to merge, communityPR, stat: QA tested

#29744 refactor: Changed `getUserPreference` to `useUserPreference` on `useVoipSounds`
  apps/meteor/client/providers/CallProvider/hooks/useVoipSounds.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#29739 chore: bump fuselage deps
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: needs QA

#29755 test: add unit tests for feature preview hooks
  apps/meteor/.mocharc.client.js
  apps/meteor/client/hooks/useFeaturePreview.spec.tsx
  apps/meteor/client/hooks/useFeaturePreview.ts
  apps/meteor/client/hooks/useFeaturePreviewList.spec.tsx
  apps/meteor/jest.client.config.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#29571 feat: Create sidebar upsell options
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/client/components/GenericUpsellModal.tsx
  apps/meteor/client/components/UpsellModal.stories.tsx
  apps/meteor/client/components/UpsellModal.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
  apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
  apps/meteor/ee/client/startup/deviceManagement.ts
  apps/meteor/ee/client/startup/engagementDashboard.ts
  apps/meteor/ee/client/startup/index.ts
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx
  apps/meteor/ee/server/lib/deviceManagement/startup.ts
  apps/meteor/ee/server/lib/engagementDashboard/startup.ts
  apps/meteor/ee/server/startup/engagementDashboard.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/images/device-management.png
  apps/meteor/public/images/engagement.png
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v301.ts
Labels: stat: needs QA, squad: workspace-mgmt

#29761 regression: fix condition to `GenericMenu` gap
  apps/meteor/client/components/GenericMenu/GenericMenu.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29694 fix: Canned Response custom tags break the GUI on enterprise
  .changeset/kind-coats-worry.md
  apps/meteor/client/components/Omnichannel/Tags.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
  apps/meteor/client/views/omnichannel/directory/chats/hooks/useTagsLabels.tsx
  apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
  apps/meteor/ee/app/api-enterprise/server/lib/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTagRemoved.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/client/hooks/useTagsList.ts
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEdit.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/index.tsx
  apps/meteor/ee/server/models/raw/CannedResponse.ts
  apps/meteor/ee/server/models/raw/LivechatTag.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/tests/data/livechat/tags.ts
  apps/meteor/tests/end-to-end/api/livechat/15-canned-responses.ts
  packages/core-typings/src/IOmnichannelCannedResponse.ts
  packages/model-typings/src/models/ICannedResponseModel.ts
  packages/model-typings/src/models/ILivechatTagModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29764 refactor: Lazy initialization on client-side
  apps/meteor/app/emoji-emojione/client/lib.ts
  apps/meteor/app/emoji-emojione/lib/emojioneRender.ts
  apps/meteor/app/emoji-emojione/lib/getEmojiConfig.ts
  apps/meteor/app/emoji-emojione/lib/isSetNotNull.ts
  apps/meteor/app/emoji-emojione/lib/rocketchat.js
  apps/meteor/app/emoji-emojione/server/lib.ts
  apps/meteor/app/emoji/client/lib.ts
  apps/meteor/client/contexts/EmojiPickerContext.ts
  apps/meteor/client/lib/rooms/roomCoordinator.tsx
  apps/meteor/client/providers/EmojiPickerProvider.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  apps/meteor/client/views/root/MainLayout/index.ts
  apps/meteor/definition/externals/emojione.d.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#29762 chore: `CloudRoute` to typescript
  apps/meteor/app/emoji/client/helpers.ts
  apps/meteor/client/lib/constants.ts
  apps/meteor/client/views/admin/cloud/CloudRoute.tsx
  apps/meteor/client/views/admin/cloud/CopyStep.tsx
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx
  apps/meteor/client/views/admin/cloud/constants.js
Labels: stat: ready to merge, stat: QA skipped

#29758 regression: Current Chats tags filter not showing department tags
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx
  apps/meteor/ee/client/hooks/useTagsList.ts
  apps/meteor/ee/client/omnichannel/tags/AutoCompleteTagsMultiple.js
  apps/meteor/ee/client/omnichannel/tags/CurrentChatTags.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29770 docs: Updated README file
  README.md
Labels: stat: ready to merge, stat: QA skipped

#29765 test: create mock package
  packages/mock-providers/.eslintrc.json
  packages/mock-providers/package.json
  packages/mock-providers/src/MockedAuthorizationContext.tsx
  packages/mock-providers/src/MockedServerContext.tsx
  packages/mock-providers/src/MockedSettingsContext.tsx
  packages/mock-providers/src/MockedUiKitActionManager.tsx
  packages/mock-providers/src/MockedUserContext.tsx
  packages/mock-providers/tsconfig.json
  yarn.lock
Labels: stat: needs QA

#29777 regression: add missing translations on MenuV2 replace
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useSortMenu.tsx
Labels: stat: ready to merge, stat: QA skipped

#29759 chore: create FeaturePreview Component
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/hooks/useFeaturePreviewList.spec.tsx
  apps/meteor/client/sidebar/header/hooks/useAccountItems.tsx
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewBadge.tsx
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.tsx
  apps/meteor/client/views/account/sidebarItems.tsx
  apps/meteor/jest.client.config.ts
  apps/meteor/package.json
  ee/packages/api-client/package.json
  ee/packages/ddp-client/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/presence/package.json
  ee/packages/ui-theming/package.json
  packages/account-utils/package.json
  packages/agenda/package.json
  packages/base64/package.json
  packages/cas-validate/package.json
  packages/core-services/package.json
  packages/cron/package.json
  packages/gazzodown/package.json
  packages/i18n/package.json
  packages/log-format/package.json
  packages/mock-providers/package.json
  packages/model-typings/package.json
  packages/models/package.json
  packages/node-poplib/package.json
  packages/random/package.json
  packages/rest-typings/package.json
  packages/server-fetch/package.json
  packages/sha256/package.json
  packages/tools/package.json
  packages/ui-client/jest.config.ts
  packages/ui-client/package.json
  packages/ui-client/src/components/FeaturePreview/FeaturePreview.spec.tsx
  packages/ui-client/src/components/FeaturePreview/FeaturePreview.tsx
  packages/ui-client/src/hooks/useFeaturePreview.spec.tsx
  packages/ui-client/src/hooks/useFeaturePreview.ts
  packages/ui-client/src/hooks/useFeaturePreviewList.spec.tsx
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
  packages/ui-client/src/index.ts
  packages/ui-client/tsconfig.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: needs QA

#29766 chore: stop importing action manager as global
  apps/meteor/app/ui-message/client/ActionButtonSyncer.ts
  apps/meteor/app/ui-message/client/ActionManager.js
  apps/meteor/app/ui-message/client/actionButtons/dropdownAction.ts
  apps/meteor/app/ui-message/client/actionButtons/messageAction.ts
  apps/meteor/app/ui-message/client/actionButtons/messageBox.ts
  apps/meteor/app/ui-message/client/actionButtons/tabbar.ts
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/app/ui-utils/client/lib/messageBox.ts
  apps/meteor/client/UIKit/hooks/useUIKitHandleAction.tsx
  apps/meteor/client/UIKit/hooks/useUIKitHandleClose.tsx
  apps/meteor/client/UIKit/hooks/useUIKitStateManager.tsx
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/hooks/useAppSlashCommands.ts
  apps/meteor/client/hooks/useAppUiKitInteraction.ts
  apps/meteor/client/hooks/useUiKitActionManager.ts
  apps/meteor/client/providers/ActionManagerProvider.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAppsItems.tsx
  apps/meteor/client/views/marketplace/components/MarketplaceRequestBadge.tsx
  apps/meteor/client/views/marketplace/hooks/useAppRequestStats.ts
  apps/meteor/client/views/modal/uikit/UiKitModal.tsx
  apps/meteor/client/views/modal/uikit/hooks/useActionManagerState.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx
  apps/meteor/client/views/room/contextualBar/Apps/AppsWithData.tsx
  apps/meteor/client/views/room/hooks/useAppsContextualBar.ts
  apps/meteor/client/views/room/providers/ToolboxProvider.tsx
  apps/meteor/ee/client/apps/communication/websockets.js
  ee/packages/ddp-client/src/types/streams.ts
Labels: stat: needs QA

#29774 regression: External links inside ButtonGroup
  apps/meteor/ee/client/views/admin/info/SeatsCard.tsx
  apps/meteor/ee/client/views/admin/users/ReachedSeatsCapModal.tsx
  apps/meteor/ee/client/views/admin/users/UserPageHeaderContentWithSeatsCap.tsx
Labels: stat: ready to merge, stat: QA skipped

#29786 refactor: Remove Accountbox usage
  apps/meteor/app/lib/README.md
  apps/meteor/app/livechat/client/ui.js
  apps/meteor/app/ui-utils/client/index.ts
  apps/meteor/app/ui-utils/client/lib/AccountBox.ts
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.tsx
  apps/meteor/client/sidebar/header/hooks/useStatusItems.tsx
  apps/meteor/client/startup/iframeCommands.ts
Labels: stat: ready to merge, stat: QA skipped

#29654 feat: Add missing variants to UIKit button
  .changeset/cuddly-ties-bake.md
  packages/fuselage-ui-kit/src/elements/ButtonElement.tsx
  packages/uikit-playground/src/Payload/BlocksTree.ts
  packages/uikit-playground/src/Payload/action/button.ts
  packages/uikit-playground/src/Payload/section/button.ts
Labels: stat: ready to merge, stat: QA tested

#29799 regression: fix `MenuV2` behavior on touch press
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29724 chore: Improve system messages for omni-visitor abandonment feature
  .changeset/hip-mugs-promise.md
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29783 regression: False live-chat status when using a dept that has already been used for other BH
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Custom.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29671 feat: `Navbar lvl 1`
  apps/meteor/client/components/Navbar/Navbar.stories.tsx
  apps/meteor/client/components/Navbar/Navbar.tsx
  apps/meteor/client/components/Navbar/NavbarAction.tsx
  apps/meteor/client/components/Navbar/NavbarBadge.tsx
  apps/meteor/client/components/Navbar/index.ts
  apps/meteor/client/navbar/Navbar.tsx
  apps/meteor/client/navbar/actions/NavbarAdministrationAction.tsx
  apps/meteor/client/navbar/actions/NavbarAuditAction.tsx
  apps/meteor/client/navbar/actions/NavbarHomeAction.tsx
  apps/meteor/client/navbar/actions/NavbarMarketplaceAction.tsx
  apps/meteor/client/navbar/actions/NavbarUserAction.tsx
  apps/meteor/client/navbar/index.ts
  apps/meteor/client/sidebar/header/Header.tsx
  apps/meteor/client/sidebar/header/HeaderUnstable.tsx
  apps/meteor/client/sidebar/header/UserAvatarWithStatus.tsx
  apps/meteor/client/sidebar/header/UserAvatarWithStatusUnstable.tsx
  apps/meteor/client/sidebar/header/UserMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAppsItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.tsx
  apps/meteor/client/sidebar/header/index.tsx
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/ui-client/src/components/index.ts
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29814 Release 6.2.10
  .changeset/dirty-crabs-deliver.md
  .changeset/fuzzy-parents-drop.md
  .changeset/nine-yaks-draw.md
  .changeset/ninety-cats-arrive.md
  .github/workflows/changesets.yml
  .github/workflows/new-release.yml
  .github/workflows/publish-release.yml
  apps/meteor/app/apps/server/converters/rooms.js
  apps/meteor/app/livechat/server/hooks/saveLastVisitorMessageTs.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/FormattingToolbarDropdown.tsx
  package.json
  packages/core-typings/src/IInquiry.ts
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/fixWorkspaceVersionsBeforePublish.ts
  packages/release-action/src/gitUtils.ts
  packages/release-action/src/index.ts
  packages/release-action/src/publishRelease.ts
  yarn.lock
Labels: stat: needs QA

#29772 regression: Hide tags to which livechat-monitor does not have access
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29820 chore(gazzodown): remove `ui-client` and `ui-contexts` peer deps from `gazzodown`
  apps/meteor/client/components/GazzodownText.tsx
  packages/gazzodown/package.json
  packages/gazzodown/src/MarkupInteractionContext.ts
  packages/gazzodown/src/mentions/UserMentionElement.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29822 regression: Apply right filters to action buttons and convert `applyButtonFilters` to `useApplyButtonFilters`
  apps/meteor/.mocharc.client.js
  apps/meteor/app/ui-message/client/actionButtons/lib/applyButtonFilters.ts
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/hooks/useApplyButtonFilters.ts
  apps/meteor/client/providers/AuthorizationProvider.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAppsItems.spec.tsx
  apps/meteor/jest.client.config.ts
  packages/mock-providers/src/MockedAuthorizationContext.tsx
  packages/mock-providers/src/MockedServerContext.tsx
  packages/ui-contexts/src/AuthorizationContext.ts
Labels: stat: ready to merge, stat: QA skipped

#29826 ci: create bump changeset on publish
  .changeset/stupid-lions-hope.md
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/gitUtils.ts
  packages/release-action/src/publishRelease.ts
  packages/release-action/src/startPatchRelease.ts
  packages/release-action/src/utils.ts
Labels: stat: ready to merge, stat: QA skipped

#29831 ci: skip ci on release publish
  .github/workflows/publish-release.yml
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/publishRelease.ts
  packages/release-action/src/startPatchRelease.ts
Labels: stat: needs QA

#29796 regression: Move changeset to correct directory
  .changeset/password-verification-front.md
Labels: stat: ready to merge, stat: QA skipped

#29704 refactor: replace useForm in favor of RHF on Prune Messages
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessages.stories.tsx
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessages.tsx
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesDateTimeRow.tsx
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.tsx
  apps/meteor/package.json
Labels: stat: ready to merge, stat: QA skipped, squad: team-collab

#29836 regression: Leader Bar chat now link
  .changeset/tiny-eyes-swim.md
  apps/meteor/client/views/room/components/body/LeaderBar.tsx
Labels: stat: ready to merge, stat: QA tested

#29840 regression: Duplicate `Search federated rooms` option
  apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomItems.tsx
Labels: stat: ready to merge, stat: QA skipped

#29846 regression: Router not capturing search string parameters
  apps/meteor/client/providers/RouterProvider.tsx
  apps/meteor/definition/externals/meteor/kadira-flow-router.d.ts
Labels: stat: ready to merge, stat: QA skipped

#29821 test: Cover sidebar audit/administration items hooks
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.spec.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.spec.tsx
  apps/meteor/client/views/hooks/useUpgradeTabParams.ts
  apps/meteor/jest.config.ts
  apps/meteor/package.json
  packages/mock-providers/src/MockedModalContext.tsx
  packages/mock-providers/src/MockedServerContext.tsx
  packages/mock-providers/src/index.ts
  packages/ui-client/src/hooks/useFeaturePreviewList.spec.tsx
Labels: stat: ready to merge, stat: QA skipped

#29825 regression: Showing tag id instead of label on chat directory
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfoDirectory.js
  apps/meteor/client/views/omnichannel/directory/chats/hooks/useTagsLabels.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29830 regression: VoIP call icon misaligned
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29841 regression: Priority changes not being reflected on the room information
  apps/meteor/ee/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29090 fix: misleading of 'total' in team members & members fixed
  .changeset/lazy-ghosts-design.md
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#29834 regression: Calling inexistent functions AppMenu on action change
  apps/meteor/client/views/marketplace/AppMenu.js
  apps/meteor/ee/client/apps/communication/websockets.js
Labels: stat: needs QA

#29651 fix: Time format of Retention Policy
  .changeset/friendly-glasses-mate.md
  apps/meteor/client/components/InfoPanel/RetentionPolicyCallout.tsx
Labels: stat: ready to merge, stat: QA skipped

#29789 chore: Normalize `Contextualbar` footer buttons
  apps/meteor/client/views/admin/customEmoji/AddCustomEmoji.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx
  apps/meteor/client/views/admin/customSounds/AddCustomSound.tsx
  apps/meteor/client/views/admin/customSounds/EditSound.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/users/AddUser.js
  apps/meteor/client/views/admin/users/EditUser.js
  apps/meteor/client/views/admin/users/InviteUsers.tsx
  apps/meteor/client/views/admin/users/UserForm.js
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditChannel.js
Labels: stat: ready to merge, stat: QA skipped

#29849 refactor: Spread REST endpoints and methods types across EE code
  apps/meteor/client/main.ts
  apps/meteor/ee/app/api-enterprise/server/canned-responses.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/business-hours.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/units.ts
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEditWithData.tsx
  apps/meteor/ee/definition/.eslintrc.json
  apps/meteor/ee/definition/index.ts
  apps/meteor/ee/definition/methods/index.ts
  apps/meteor/ee/definition/methods/license.ts
  apps/meteor/ee/definition/rest/index.ts
  apps/meteor/ee/definition/rest/v1/chat.ts
  apps/meteor/ee/definition/rest/v1/engagementDashboard.ts
  apps/meteor/ee/definition/rest/v1/omnichannel/businessHours.ts
  apps/meteor/ee/definition/rest/v1/omnichannel/businessUnits.ts
  apps/meteor/ee/definition/rest/v1/omnichannel/cannedResponses.ts
  apps/meteor/ee/definition/rest/v1/omnichannel/index.ts
  apps/meteor/ee/definition/rest/v1/roles.ts
  apps/meteor/ee/definition/rest/v1/sessions/SessionsPaginateProps.ts
  apps/meteor/ee/definition/rest/v1/sessions/SessionsProps.ts
  apps/meteor/ee/definition/rest/v1/sessions/index.ts
  apps/meteor/ee/definition/rest/v1/sessions/sessions.ts
  apps/meteor/ee/server/api/chat.ts
  apps/meteor/ee/server/api/engagementDashboard/channels.ts
  apps/meteor/ee/server/api/engagementDashboard/messages.ts
  apps/meteor/ee/server/api/engagementDashboard/users.ts
  apps/meteor/ee/server/api/roles.ts
  apps/meteor/ee/server/api/sessions.ts
Labels: stat: QA skipped

#29853 chore: Deprecate `cloud:checkRegisterStatus` method
  apps/meteor/app/cloud/server/methods.ts
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/startup/startup.ts
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
Labels: stat: ready to merge, stat: QA skipped

#29858 test: Cover `sortMenu`
  apps/meteor/client/sidebar/header/actions/hooks/useGroupingListItems.spec.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useSortModeItems.spec.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useViewModeItems.spec.tsx
Labels: stat: needs QA

#29848 ci: Report Jest coverage
  .github/workflows/ci-test-unit.yml
  apps/meteor/.mocharc.client.js
  apps/meteor/client/components/message/content/reactions/useToggleReactionMutation.spec.tsx
  apps/meteor/jest.config.ts
  codecov.yml
  ee/packages/ddp-client/jest.config.ts
  turbo.json
Labels: stat: needs QA

#29859 regression: Remove wrong navigation bar feature preview image
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
Labels: stat: ready to merge, stat: QA skipped

#29829 regression: Dial pad button not enabling after phone number is informed
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useDialPad.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29856 regression: Fix emoji previews on hover
  .changeset/silent-ties-pay.md
  apps/meteor/client/providers/EmojiPickerProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#29862 regression: Align user status on discussions header
  .changeset/sixty-ravens-marry.md
  packages/ui-client/src/components/Header/HeaderTag/HeaderTagIcon.tsx
Labels: stat: ready to merge, stat: QA tested

#29864 test: use jest as the default unit test for client code
  apps/meteor/.mocharc.client.js
  apps/meteor/client/components/message/variants/ThreadMessagePreview.spec.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.spec.tsx
  apps/meteor/client/views/room/MessageList/hooks/useAutoTranslate.spec.ts
  apps/meteor/client/views/room/components/body/composer/MessageComposer.spec.ts
  apps/meteor/jest.config.ts
  ee/packages/api-client/jest.config.ts
Labels: stat: ready to merge, stat: QA skipped

#29872 chore: bump fuselage
  packages/ui-client/src/components/Header/HeaderToolbox/HeaderToolboxAction.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29877 chore: sidebar actions pressed state
  apps/meteor/client/sidebar/header/actions/Directory.tsx
  apps/meteor/client/sidebar/header/actions/Home.tsx
  ee/packages/ui-theming/src/sidebarPalette.ts
  ee/packages/ui-theming/src/sidebarPaletteDark.ts
Labels: stat: ready to merge, stat: QA skipped

#29839 fix: Prevent refetch queries on windows focus
  apps/meteor/client/hooks/useIsEnterprise.ts
  apps/meteor/client/hooks/useLicense.ts
  apps/meteor/client/hooks/useRegistrationStatus.ts
  apps/meteor/client/hooks/useUserInfoQuery.ts
  apps/meteor/client/lib/queryClient.ts
  apps/meteor/client/providers/AppsProvider.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/useInfiniteFederationSearchPublicRooms.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/useMatrixServerList.ts
  apps/meteor/client/stories/contexts/QueryClientProviderMock.tsx
  apps/meteor/client/views/admin/integrations/edit/OutgoingWebhookHistoryPage.tsx
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/client/views/admin/settings/groups/voip/VoipExtensionsPage.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/marketplace/hooks/useAppRequestStats.ts
  apps/meteor/client/views/marketplace/hooks/useAppRequests.ts
  apps/meteor/client/views/marketplace/hooks/useFeaturedApps.ts
  apps/meteor/client/views/omnichannel/agents/hooks/useAgentsQuery.ts
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/DepartmentsTable.tsx
  apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
  apps/meteor/client/views/omnichannel/queueList/QueueListTable.tsx
  apps/meteor/client/views/outlookCalendar/hooks/useOutlookCalendarList.ts
  apps/meteor/client/views/room/Header/ParentTeam.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts
  apps/meteor/ee/client/hooks/useHasLicenseModule.ts
  apps/meteor/ee/client/omnichannel/slaPolicies/SlaTable.tsx
  apps/meteor/ee/client/omnichannel/tags/TagsTable.tsx
  apps/meteor/ee/client/omnichannel/units/UnitsTable.tsx
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/hooks/useVideoConfData.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, squad: Workspace Management

#29819 fix: show requested filters only on requested apps view
  .changeset/silver-mugs-unite.md
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
Labels: stat: ready to merge, stat: QA tested

#29793 chore: move some message functions to message service
  apps/meteor/server/services/messages/service.ts
  packages/core-services/src/types/IMessageService.ts
Labels: stat: ready to merge, stat: QA skipped

#28301 fix: Wrong toast message while creating a new custom sound with an existing name
  .changeset/empty-ants-enjoy.md
  apps/meteor/client/views/admin/customSounds/AddCustomSound.tsx
Labels: stat: ready to merge, stat: QA skipped

#29794 chore: move some room functions to room service
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/server/services/room/service.ts
  packages/core-services/src/types/IRoomService.ts
Labels: stat: needs QA

#29881 chore: Reduce complexity to infer IconName type
  apps/meteor/app/ui-message/client/messageBox/messageBoxFormatting.ts
  apps/meteor/app/ui-utils/client/lib/AccountBox.ts
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/client/components/GenericModal/GenericModal.tsx
  apps/meteor/client/components/GenericNoResults/GenericNoResults.tsx
  apps/meteor/client/components/InfoPanel/InfoPanelAction.tsx
  apps/meteor/client/components/InfoPanel/InfoPanelTitle.tsx
  apps/meteor/client/components/Sidebar/SidebarNavigationItem.tsx
  apps/meteor/client/components/UpsellModal.tsx
  apps/meteor/client/components/UserInfo/UserInfoAction.tsx
  apps/meteor/client/components/message/content/MessageActions.tsx
  apps/meteor/client/components/message/content/actions/MessageAction.tsx
  apps/meteor/client/lib/banners.ts
  apps/meteor/client/lib/createSidebarItems.ts
  apps/meteor/client/sidebar/Item/Condensed.tsx
  apps/meteor/client/sidebar/Item/Extended.tsx
  apps/meteor/client/views/banners/UiKitBanner.tsx
  apps/meteor/client/views/hooks/useActionSpread.ts
  apps/meteor/client/views/omnichannel/agents/AgentInfoAction.tsx
  apps/meteor/client/views/room/components/contextualBar/MessageListTab.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/components/NotificationByDevice.tsx
  apps/meteor/client/views/room/contextualBar/OTR/components/OTRStates.tsx
  apps/meteor/client/views/room/lib/Toolbox/index.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerGrid/WebdavFilePickerGrid.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerTable.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/lib/getNodeIconType.ts
  apps/meteor/client/views/teams/contextualBar/info/TeamsInfo.tsx
  apps/meteor/definition/IRoomTypeConfig.ts
  apps/meteor/ee/client/deviceManagement/components/DeviceIcon.tsx
  packages/ui-client/src/components/Header/HeaderIcon.tsx
  packages/ui-video-conf/src/VideoConfButton.tsx
  packages/ui-video-conf/src/VideoConfController.tsx
  packages/web-ui-registration/src/LoginServicesButton.tsx
Labels: stat: ready to merge, stat: QA skipped

#29731 feat: Create upsell options in the admin sidebar and reorganize it
  .changeset/tidy-bears-camp.md
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/client/components/GenericUpsellModal.tsx
  apps/meteor/client/components/UpsellModal.stories.tsx
  apps/meteor/client/components/UpsellModal.tsx
  apps/meteor/client/views/admin/AdministrationRouter.tsx
  apps/meteor/client/views/admin/customEmoji/CustomEmojiRoute.tsx
  apps/meteor/client/views/admin/customSounds/CustomSoundsPage.tsx
  apps/meteor/client/views/admin/federationDashboard/FederationDashboardPage.tsx
  apps/meteor/client/views/admin/info/InformationPage.tsx
  apps/meteor/client/views/admin/info/InformationRoute.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsolePage.tsx
  apps/meteor/client/views/admin/oauthApps/OAuthAppsPage.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/admin/viewLogs/ViewLogsPage.tsx
  apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
  apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
  apps/meteor/ee/client/startup/deviceManagement.ts
  apps/meteor/ee/client/startup/engagementDashboard.ts
  apps/meteor/ee/client/startup/index.ts
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardPage.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx
  apps/meteor/ee/server/lib/deviceManagement/startup.ts
  apps/meteor/ee/server/lib/engagementDashboard/startup.ts
  apps/meteor/ee/server/startup/engagementDashboard.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/public/images/device-management.png
  apps/meteor/public/images/engagement.png
  apps/meteor/server/startup/migrations/v302.ts
  apps/meteor/tests/e2e/administration-menu.spec.ts
  apps/meteor/tests/e2e/administration.spec.ts
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#29593 feat: return all broken password policies at once
  .changeset/soft-yaks-matter.md
  apps/meteor/app/lib/server/lib/PasswordPolicyClass.js
  apps/meteor/tests/end-to-end/api/01-users.js
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#29837 chore: move getUrl to meteor service
  apps/meteor/server/services/meteor/service.ts
  packages/core-services/src/types/IMeteor.ts
Labels: stat: needs QA

#29850 regression: Check room scoped permissions for slash commands
  .changeset/moody-countries-sit.md
  apps/meteor/client/lib/chats/flows/processSlashCommand.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#29867 regression: Reverted UI logic to send tag labels instead of tag id's
  apps/meteor/client/components/Omnichannel/Tags.tsx
  apps/meteor/client/components/Omnichannel/hooks/useLivechatTags.ts
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfoDirectory.js
  apps/meteor/client/views/omnichannel/directory/chats/hooks/useTagsLabels.tsx
  apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
  apps/meteor/ee/app/api-enterprise/server/lib/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTagRemoved.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/client/hooks/useTagsList.ts
  apps/meteor/tests/end-to-end/api/livechat/15-canned-responses.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, squad: omnichannel

#29845 chore: Fix some CodeLint warnings
  ee/packages/ddp-client/__examples__/simple.ts
  ee/packages/ddp-client/src/types/Account.ts
  packages/server-fetch/src/parsers.ts
  packages/ui-contexts/src/hooks/useSearchParameter.ts
Labels: stat: ready to merge, stat: QA skipped

#29891 ci: cache eslint
  .github/workflows/ci-code-check.yml
Labels: stat: needs QA

#29889 chore(eslint): ESLint configuration
  _templates/package/new/package.json.ejs.t
  _templates/service/new/package.json.ejs.t
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/account-service/.eslintrc.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/.eslintrc.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/.eslintrc.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/.eslintrc.json
  ee/apps/stream-hub-service/package.json
  ee/packages/api-client/package.json
  ee/packages/ddp-client/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/presence/.eslintrc.json
  ee/packages/presence/package.json
  ee/packages/ui-theming/package.json
  packages/account-utils/package.json
  packages/agenda/package.json
  packages/base64/package.json
  packages/cas-validate/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/cron/package.json
  packages/eslint-config/package.json
  packages/favicon/package.json
  packages/fuselage-ui-kit/.eslintrc.js
  packages/fuselage-ui-kit/.eslintrc.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/i18n/package.json
  packages/instance-status/package.json
  packages/livechat/package.json
  packages/log-format/package.json
  packages/mock-providers/package.json
  packages/model-typings/package.json
  packages/models/package.json
  packages/node-poplib/package.json
  packages/random/package.json
  packages/release-action/package.json
  packages/rest-typings/package.json
  packages/server-fetch/package.json
  packages/sha256/package.json
  packages/tools/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: needs QA

#29892 ci: adjust `.eslintignore` file
  apps/meteor/.eslintignore
Labels: stat: needs QA

#29566 feat: Adding new UIKit components
  .changeset/loud-sheep-try.md
  packages/fuselage-ui-kit/src/blocks/CalloutBlock.tsx
  packages/fuselage-ui-kit/src/contexts/kitContext.ts
  packages/fuselage-ui-kit/src/elements/CheckboxElement.tsx
  packages/fuselage-ui-kit/src/elements/RadioButtonElement.tsx
  packages/fuselage-ui-kit/src/elements/TimePickerElement.tsx
  packages/fuselage-ui-kit/src/elements/ToggleSwitchElement.tsx
  packages/fuselage-ui-kit/src/hooks/useUiKitState.ts
  packages/fuselage-ui-kit/src/surfaces/FuselageContextualBarRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/FuselageModalSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/FuselageSurfaceRenderer.tsx
  packages/uikit-playground/src/Components/Preview/Display/RenderPayload/RenderPayload.tsx
  packages/uikit-playground/src/Payload/BlocksTree.ts
  packages/uikit-playground/src/Payload/action/checkbox.ts
  packages/uikit-playground/src/Payload/action/index.ts
  packages/uikit-playground/src/Payload/action/radioButton.ts
  packages/uikit-playground/src/Payload/action/timePicker.ts
  packages/uikit-playground/src/Payload/action/toggleSwitch.ts
  packages/uikit-playground/src/Payload/callout/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29893 chore: Use `screen.getBy*` instead of the render return
  apps/meteor/tests/unit/client/components/Omnichannel/modals/TranscriptModal.spec.tsx
Labels: stat: ready to merge, stat: QA skipped

#29878 regression: Omni-monitors unable to see canned responses from disabled department
  apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/departments.ts
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/users.helper.js
  apps/meteor/tests/end-to-end/api/livechat/15-canned-responses.ts
  packages/model-typings/src/models/ILivechatUnitModel.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, squad: omnichannel

#29894 regression: Open default BH not being unlinked when department is connected to a custom BH
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Custom.ts
  apps/meteor/tests/data/livechat/businessHours.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29885 regression: broken error message when trying to save duplicate SLA
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/server/models/raw/ServiceLevelAgreements.ts
  apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
  packages/model-typings/src/models/IOmnichannelServiceLevelAgreementsModel.ts
Labels: type: regression, stat: ready to merge, stat: QA tested, squad: omnichannel

#29879 regression: raw i18n displayed on mc context bar header title
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#29634 feat: remove enforce password fallback dependency
  .changeset/shiny-tools-worry.md
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/client/views/admin/users/hooks/useResetE2EEKeyAction.tsx
  apps/meteor/client/views/admin/users/hooks/useResetTOTPAction.tsx
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#29887 chore: Add icons on Omnichannel sidebar
  apps/meteor/client/views/omnichannel/sidebarItems.ts
  apps/meteor/ee/app/livechat-enterprise/client/views/livechatSideNavItems.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29899 regression: Fix Email variables
  .changeset/welcome-email.md
  apps/meteor/client/views/home/DefaultHomePage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-AT.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
  apps/meteor/server/settings/email.ts
Labels: stat: needs QA, squad: Workspace Management

#29900 regression: E2EE modal translation
  .changeset/giant-chairs-rush.md
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/client/views/e2e/SaveE2EPasswordModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#29725 regression: Apps not able to upload files
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
Labels: feat: apps, stat: ready to merge, stat: QA skipped

#29906 chore: Bump up apps-engine
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29787 chore: improve health check log messages
  apps/meteor/server/routes/health.ts
  ee/apps/ddp-streamer/src/DDPStreamer.ts
  ee/apps/stream-hub-service/src/service.ts
Labels: stat: ready to merge, stat: QA skipped

#29897 test: Use `findByRole` instead `getByRole` in `TranscriptModal.spec.ts`
  apps/meteor/tests/e2e/omnichannel/omnichannel-changing-room-priority-and-sla.spec.ts
  apps/meteor/tests/unit/client/components/Omnichannel/modals/TranscriptModal.spec.tsx
Labels: stat: ready to merge, stat: QA skipped

#29888 chore: Bump Fuselage Packages
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29816 chore: Navbar lvl1 arrangements
  apps/meteor/client/sidebar/Sidebar.stories.tsx
  apps/meteor/client/sidebar/Sidebar.tsx
  apps/meteor/client/sidebar/SidebarRegion.tsx
  apps/meteor/client/sidebar/index.ts
  apps/meteor/client/views/modal/ModalRegion.tsx
  apps/meteor/client/views/room/Header/Header.tsx
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
Labels: stat: ready to merge, stat: QA skipped

#29585 chore: streams refactor
  apps/meteor/app/custom-sounds/client/index.ts
  apps/meteor/app/custom-sounds/client/notifications/deleteCustomSound.js
  apps/meteor/app/custom-sounds/client/notifications/updateCustomSound.js
  apps/meteor/ee/client/apps/communication/websockets.js
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  ee/packages/ddp-client/src/types/streams.ts
  turbo.json
Labels: stat: ready to merge, stat: QA skipped

#29883 chore: isolate callbacks and typings
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/dolphin/server/lib.ts
  apps/meteor/app/e2e/server/beforeCreateRoom.ts
  apps/meteor/app/integrations/server/triggers.ts
  apps/meteor/app/irc/server/irc-bridge/index.js
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/livechat/server/startup.ts
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/startup/afterLogoutCleanUp/customScriptOnLogout.ts
  apps/meteor/client/startup/afterLogoutCleanUp/purgeAllDrafts.ts
  apps/meteor/client/startup/afterLogoutCleanUp/roomManager.ts
  apps/meteor/client/startup/iframeCommands.ts
  apps/meteor/lib/callbacks.spec.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/lib/callbacks/afterLeaveRoomCallback.ts
  apps/meteor/lib/callbacks/afterLogoutCleanUpCallback.ts
  apps/meteor/lib/callbacks/afterRemoveFromRoomCallback.ts
  apps/meteor/lib/callbacks/beforeCreateRoomCallback.ts
  apps/meteor/lib/callbacks/beforeCreateUserCallback.ts
  apps/meteor/lib/callbacks/beforeLeaveRoomCallback.ts
  apps/meteor/lib/callbacks/callbacksBase.ts
  apps/meteor/server/methods/logoutCleanUp.ts
  apps/meteor/server/methods/removeUserFromRoom.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/tests/unit/server/federation/infrastructure/rocket-chat/hooks/hooks.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#29907 fix: Users can mention `here` and `all` even without permission
  .changeset/shaggy-beans-poke.md
  apps/meteor/app/lib/server/startup/filterATAllTag.ts
  apps/meteor/app/lib/server/startup/filterATHereTag.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#29919 ci: fix flaky test - Threads hide flextab
  apps/meteor/client/views/room/MessageList/hooks/useLoadSurroundingMessages.ts
Labels: stat: needs QA

#29920 ci: fix flaky tests - mention all here
  apps/meteor/client/views/room/layout/RoomLayout.tsx
Labels: stat: needs QA

#29917 ci: Skip HTTPBin container on UI tests
  .github/workflows/ci-test-e2e.yml
Labels: stat: ready to merge, stat: QA skipped

#29914 fix: Performance issue when using api to create users
  .changeset/fifty-lizards-jump.md
  apps/meteor/app/lib/server/functions/checkEmailAvailability.ts
  apps/meteor/server/models/raw/Users.js
Labels: stat: ready to merge, stat: QA skipped

#29915 Release 6.2.11
  .changeset/fifty-lizards-jump.md
  .changeset/quick-spies-count.md
  apps/meteor/app/lib/server/functions/checkEmailAvailability.ts
  apps/meteor/server/models/raw/Users.js
Labels: stat: needs QA

#29913 ci: package build step
  .github/workflows/ci.yml
Labels: stat: needs QA

#29795 fix: custom emoji file upload with FileSystem method
  .changeset/custom-emoji-fs.md
  apps/meteor/app/file/server/file.server.ts
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#29869 fix: Permissions Table > Roles sdk stream
  apps/meteor/client/startup/roles.ts
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#29876 fix: check when CAS popup is closed to proceed with login
  .changeset/gold-horses-pretend.md
  apps/meteor/app/cas/client/cas_client.ts
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#29901 regression: BH not being applied to agent's if they're added to departments from Agent's panel
  apps/meteor/app/livechat/server/api/v1/agent.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/methods/changeLivechatStatus.ts
  apps/meteor/app/livechat/server/methods/saveAgentInfo.ts
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29925 regression: Server isn't adding agent required properties to users created/updated through admin UI
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#29936 refactor: Migrate some room actions to hooks
  apps/meteor/app/autotranslate/client/index.ts
  apps/meteor/app/autotranslate/client/lib/tabBar.ts
  apps/meteor/app/videobridge/client/index.ts
  apps/meteor/app/videobridge/client/tabBar.tsx
  apps/meteor/client/hooks/roomActions/useAutotranslateRoomAction.ts
  apps/meteor/client/hooks/roomActions/useStartCallRoomAction.tsx
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/ui.ts
  apps/meteor/client/views/room/Header/RoomHeader.tsx
  apps/meteor/client/views/room/Header/RoomToolbox/RoomToolbox.tsx
  apps/meteor/client/views/room/Header/RoomToolbox/index.ts
  apps/meteor/client/views/room/Header/ToolBox/index.ts
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/client/views/room/lib/Toolbox/index.tsx
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/client/views/room/providers/RoomToolboxProvider.tsx
  apps/meteor/client/views/room/providers/VirtualAction.tsx
  apps/meteor/client/views/room/providers/hooks/useAppsRoomActions.ts
  apps/meteor/client/views/room/providers/hooks/useCoreRoomActions.tsx
  apps/meteor/client/views/room/providers/hooks/useToolboxActions.ts
  apps/meteor/ee/client/hooks/roomActions/useCallsRoomAction.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29923 chore: zodern minifier
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
Labels: stat: needs QA

#29937 refactor: Migrate some room actions to hooks
  apps/meteor/app/channel-settings/client/index.ts
  apps/meteor/app/channel-settings/client/tabBar.ts
  apps/meteor/app/ui-clean-history/client/index.ts
  apps/meteor/app/ui-clean-history/client/lib/tabBar.ts
  apps/meteor/client/hooks/roomActions/useChannelSettingsRoomAction.ts
  apps/meteor/client/hooks/roomActions/useCleanHistoryRoomAction.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/ui.ts
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/Info/RoomInfoRouter.tsx
  apps/meteor/ee/app/canned-responses/client/index.ts
  apps/meteor/ee/app/canned-responses/client/tabBar.ts
  apps/meteor/ee/client/apps/gameCenter/tabBar.tsx
  apps/meteor/ee/client/apps/index.ts
  apps/meteor/ee/client/hooks/roomActions/useCannedResponsesRoomAction.tsx
  apps/meteor/ee/client/hooks/roomActions/useGameCenterRoomAction.ts
  apps/meteor/ee/client/startup/index.ts
Labels: stat: ready to merge, stat: QA skipped

#29939 refactor: Migrate some room actions to hooks
  apps/meteor/app/discussion/client/index.ts
  apps/meteor/app/discussion/client/tabBar.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/e2e/client/tabbar.ts
  apps/meteor/app/livechat/client/externalFrame/index.ts
  apps/meteor/app/livechat/client/externalFrame/tabBar.ts
  apps/meteor/app/livechat/client/tabBar.ts
  apps/meteor/app/otr/client/index.ts
  apps/meteor/app/otr/client/tabBar.ts
  apps/meteor/client/hooks/roomActions/useContactChatHistoryRoomAction.ts
  apps/meteor/client/hooks/roomActions/useContactProfileRoomAction.ts
  apps/meteor/client/hooks/roomActions/useDiscussionsRoomAction.ts
  apps/meteor/client/hooks/roomActions/useE2EERoomAction.ts
  apps/meteor/client/hooks/roomActions/useExportMessagesRoomAction.ts
  apps/meteor/client/hooks/roomActions/useKeyboardShortcutListRoomAction.ts
  apps/meteor/client/hooks/roomActions/useMembersListRoomAction.ts
  apps/meteor/client/hooks/roomActions/useMentionsRoomAction.ts
  apps/meteor/client/hooks/roomActions/useOTRRoomAction.ts
  apps/meteor/client/hooks/roomActions/useOmnichannelExternalFrameRoomAction.ts
  apps/meteor/client/hooks/roomActions/useUserInfoGroupRoomAction.ts
  apps/meteor/client/hooks/roomActions/useUserInfoRoomAction.ts
  apps/meteor/client/startup/contextualBar/exportMessagesTab.ts
  apps/meteor/client/startup/contextualBar/index.ts
  apps/meteor/client/startup/contextualBar/mentionsTab.ts
  apps/meteor/client/ui.ts
  apps/meteor/client/views/room/index.ts
  apps/meteor/client/views/room/lib/Toolbox/defaultActions.ts
  apps/meteor/client/views/room/providers/hooks/useCoreRoomActions.ts
Labels: stat: QA skipped

#29642 chore: `refactor/livechat`
  packages/livechat/src/components/App/App.tsx
  packages/livechat/src/components/App/index.tsx
  packages/livechat/src/components/Avatar/index.tsx
  packages/livechat/src/components/Avatar/stories.tsx
  packages/livechat/src/components/ButtonGroup/index.tsx
  packages/livechat/src/components/Calls/CallIFrame.tsx
  packages/livechat/src/components/Calls/CallNotification.tsx
  packages/livechat/src/components/Calls/CallStatus.js
  packages/livechat/src/components/Calls/CallStatus.ts
  packages/livechat/src/components/Calls/JoinCallButton.tsx
  packages/livechat/src/components/Footer/index.js
  packages/livechat/src/components/Footer/index.tsx
  packages/livechat/src/components/Form/DateInput/index.js
  packages/livechat/src/components/Form/DateInput/index.tsx
  packages/livechat/src/routes/Chat/connector.tsx
  packages/livechat/src/routes/Chat/index.ts
  packages/livechat/src/routes/ChatFinished/index.ts
  packages/livechat/src/routes/GDPRAgreement/index.ts
  packages/livechat/src/routes/LeaveMessage/container.js
  packages/livechat/src/routes/LeaveMessage/index.ts
  packages/livechat/src/routes/Register/container.js
  packages/livechat/src/routes/Register/index.ts
  packages/livechat/src/routes/SwitchDepartment/connector.tsx
  packages/livechat/src/routes/SwitchDepartment/index.ts
  packages/livechat/src/routes/TriggerMessage/container.js
  packages/livechat/src/routes/TriggerMessage/index.ts
Labels: stat: ready to merge, stat: QA skipped

#29947 chore: Improve Composer Skeleton
  apps/meteor/client/views/room/Room/ComposerSkeleton.tsx
Labels: stat: ready to merge, stat: QA skipped

#29943 refactor: Migrate some room actions to hooks
  apps/meteor/app/livechat/client/index.ts
  apps/meteor/app/livechat/client/tabBar.ts
  apps/meteor/app/push-notifications/client/index.ts
  apps/meteor/app/push-notifications/client/tabBar.ts
  apps/meteor/app/threads/client/flextab/threadlist.tsx
  apps/meteor/app/threads/client/index.ts
  apps/meteor/app/webrtc/client/index.ts
  apps/meteor/app/webrtc/client/tabBar.tsx
  apps/meteor/client/hooks/roomActions/useOutlookCalenderRoomAction.ts
  apps/meteor/client/hooks/roomActions/usePinnedMessagesRoomAction.ts
  apps/meteor/client/hooks/roomActions/usePushNotificationsRoomAction.ts
  apps/meteor/client/hooks/roomActions/useRocketSearchRoomAction.ts
  apps/meteor/client/hooks/roomActions/useRoomInfoRoomAction.ts
  apps/meteor/client/hooks/roomActions/useStarredMessagesRoomAction.ts
  apps/meteor/client/hooks/roomActions/useStartCallRoomAction.ts
  apps/meteor/client/hooks/roomActions/useTeamChannelsRoomAction.ts
  apps/meteor/client/hooks/roomActions/useTeamInfoRoomAction.ts
  apps/meteor/client/hooks/roomActions/useThreadRoomAction.tsx
  apps/meteor/client/hooks/roomActions/useUploadedFilesListRoomAction.ts
  apps/meteor/client/hooks/roomActions/useVoIPRoomInfoRoomAction.ts
  apps/meteor/client/hooks/roomActions/useWebRTCVideoRoomAction.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/main.ts
  apps/meteor/client/startup/contextualBar/index.ts
  apps/meteor/client/startup/contextualBar/pinnedMessagesTab.ts
  apps/meteor/client/startup/contextualBar/starredMessagesTab.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/ui.ts
  apps/meteor/client/views/outlookCalendar/index.ts
  apps/meteor/client/views/outlookCalendar/tabBar.ts
  apps/meteor/client/views/room/contexts/ToolboxContext.ts
  apps/meteor/client/views/room/lib/Toolbox/defaultActions.ts
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.tsx
  apps/meteor/client/views/teams/contextualBar/channels/tabBar.ts
  apps/meteor/client/views/teams/contextualBar/info/tabBar.ts
  apps/meteor/client/views/teams/index.ts
  apps/meteor/ee/client/hooks/roomActions/useCallsRoomAction.ts
  apps/meteor/ee/client/hooks/roomActions/useCannedResponsesRoomAction.ts
Labels: stat: QA skipped

#29932 chore: Trigger docs update
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA skipped

#29951 regression: Device management module verification
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
Labels: stat: ready to merge, stat: QA skipped

#29827 chore: Improve bio and nickname exceeded max length errors
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/tests/data/constants.ts
  apps/meteor/tests/end-to-end/api/01-users.js
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#29918 fix: Teams are not displayed with the correct icon on spotlight sidebar search
  .changeset/sour-parrots-nail.md
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/server/lib/spotlight.js
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#29945 regression: Login with SAML not working
  apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
  apps/meteor/client/startup/routes.tsx
  apps/meteor/client/views/home/HomePage.tsx
  apps/meteor/client/views/root/SAMLLoginRoute.tsx
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#29956 chore: `GenericUpsellModal` sanitization
  apps/meteor/client/components/GenericUpsellModal.tsx
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.tsx
  apps/meteor/client/components/GenericUpsellModal/hooks/index.ts
  apps/meteor/client/components/GenericUpsellModal/hooks/useUpsellActions.ts
  apps/meteor/client/components/GenericUpsellModal/index.ts
  apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
  apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx
  apps/meteor/public/images/unlimited-apps-modal.png
  apps/meteor/public/images/unlimited-apps-modal.svg
Labels: stat: ready to merge, stat: QA skipped
