Repository RocketChat/Rocket.Chat, pull requests merged in 2023-04, with the labels that each got.

#28710 refactor: Move callbacks to ts 1X
  apps/meteor/app/livechat/server/hooks/beforeDelegateAgent.ts
  apps/meteor/app/livechat/server/hooks/leadCapture.ts
  apps/meteor/app/livechat/server/hooks/markRoomNotResponded.ts
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/app/livechat/server/hooks/offlineMessage.ts
  apps/meteor/app/livechat/server/hooks/offlineMessageToChannel.ts
  apps/meteor/app/livechat/server/hooks/processRoomAbandonment.ts
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/app/livechat/server/hooks/saveContactLastChat.ts
  apps/meteor/app/livechat/server/hooks/saveLastVisitorMessageTs.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Department.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/Messages.ts
  packages/core-typings/src/IInquiry.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
  packages/model-typings/src/models/IMessagesModel.ts
  packages/model-typings/src/models/IUsersModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: QA skipped

#28742 refactor: `Rooms` model 4/4
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/invites/server/functions/findOrCreateInvite.js
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/loadMessageHistory.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/lib/processDirectEmail.ts
  apps/meteor/app/lib/server/methods/addUsersToRoom.ts
  apps/meteor/app/lib/server/methods/archiveRoom.ts
  apps/meteor/app/lib/server/methods/blockUser.ts
  apps/meteor/app/lib/server/methods/getChannelHistory.ts
  apps/meteor/app/lib/server/methods/getRoomRoles.ts
  apps/meteor/app/lib/server/methods/joinRoom.ts
  apps/meteor/app/lib/server/methods/leaveRoom.ts
  apps/meteor/app/lib/server/methods/unarchiveRoom.ts
  apps/meteor/app/livechat/server/hooks/offlineMessageToChannel.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/mentions/server/Mentions.js
  apps/meteor/app/mentions/server/methods/getUserMentionsByChannel.ts
  apps/meteor/app/mentions/server/server.js
  apps/meteor/app/models/server/index.ts
  apps/meteor/app/models/server/models/Rooms.js
  apps/meteor/app/oembed/server/jumpToMessage.ts
  apps/meteor/app/search/server/methods.ts
  apps/meteor/app/slackbridge/server/RocketAdapter.js
  apps/meteor/app/slackbridge/server/slackbridge_import.server.js
  apps/meteor/app/slashcommands-archiveroom/server/server.ts
  apps/meteor/app/slashcommands-create/server/server.ts
  apps/meteor/app/smarsh-connector/server/functions/generateEml.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/server/lib/spotlight.js
  apps/meteor/server/publications/room/index.ts
  apps/meteor/tests/unit/app/mentions/server.tests.js
Labels: stat: ready to merge, stat: QA skipped

#28754 ci: revert Variable Setup changes
  .github/workflows/ci.yml
Labels: stat: QA skipped

#28765 chore: /help notifying the shortcuts in multiple messages
  apps/meteor/app/slashcommands-help/server/server.ts
Labels: type: improvement, stat: ready to merge, stat: QA skipped

#28719 docs: update documentation
  README.md
Labels: type: documentation, stat: ready to merge, stat: QA skipped

#28281 fix: Quotes chain off by one error in quote chain limit settings
  apps/meteor/app/oembed/server/jumpToMessage.ts
Labels: stat: ready to merge, communityPR, stat: QA tested

#28770 fix: Messages jumping after reaction
  apps/meteor/app/reactions/server/setReaction.ts
Labels: stat: ready to merge, stat: QA tested

#28777 fix: #28762 - fix missing command in /help
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: type: bug, stat: ready to merge, stat: QA skipped

#28789 refactor: remove Users from fibers 15
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/api/server/v1/cloud.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/apps/server/bridges/cloud.ts
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/apps/server/bridges/rooms.ts
  apps/meteor/app/apps/server/converters/messages.js
  apps/meteor/app/apps/server/converters/rooms.js
  apps/meteor/app/apps/server/converters/uploads.js
  apps/meteor/app/apps/server/converters/users.js
  apps/meteor/app/authorization/server/methods/removeUserFromRole.ts
  apps/meteor/app/cas/server/cas_server.js
  apps/meteor/app/cloud/server/functions/checkUserHasCloudLogin.js
  apps/meteor/app/cloud/server/functions/connectWorkspace.ts
  apps/meteor/app/cloud/server/functions/disconnectWorkspace.ts
  apps/meteor/app/cloud/server/functions/getUserCloudAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js
  apps/meteor/app/cloud/server/functions/getWorkspaceKey.js
  apps/meteor/app/cloud/server/functions/reconnectWorkspace.ts
  apps/meteor/app/cloud/server/functions/removeWorkspaceRegistrationInfo.ts
  apps/meteor/app/cloud/server/functions/retrieveRegistrationStatus.ts
  apps/meteor/app/cloud/server/functions/startRegisterWorkspace.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace.ts
  apps/meteor/app/cloud/server/functions/userLogout.js
  apps/meteor/app/cloud/server/index.js
  apps/meteor/app/lib/server/functions/checkEmailAvailability.ts
  apps/meteor/app/lib/server/functions/checkUsernameAvailability.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/functions/setEmail.ts
  apps/meteor/app/lib/server/functions/setUserAvatar.ts
  apps/meteor/app/lib/server/methods/setAdminStatus.ts
  apps/meteor/app/lib/server/methods/updateMessage.ts
  apps/meteor/app/livechat/server/methods/saveInfo.ts
  apps/meteor/app/models/server/models/Users.js
  apps/meteor/app/slackbridge/server/slackbridge_import.server.js
  apps/meteor/app/slashcommands-invite/server/server.ts
  apps/meteor/app/slashcommands-join/server/server.ts
  apps/meteor/app/version-check/server/functions/checkVersionUpdate.ts
  apps/meteor/imports/personal-access-tokens/server/api/methods/regenerateToken.ts
  apps/meteor/packages/meteor-restivus/lib/auth.js
  apps/meteor/packages/meteor-restivus/lib/restivus.js
  apps/meteor/packages/meteor-restivus/lib/route.js
  apps/meteor/server/routes/avatar/middlewares/auth.js
  apps/meteor/server/routes/avatar/user.js
  apps/meteor/server/routes/avatar/utils.js
  apps/meteor/server/routes/userDataDownload.ts
  apps/meteor/server/startup/initialData.js
  apps/meteor/server/startup/serverRunning.js
  apps/meteor/tests/unit/app/apps/server/messages.tests.js
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA skipped

#28790 refactor: convert Audit model to async
  apps/meteor/ee/client/views/audit/components/AuditForm.tsx
  apps/meteor/ee/client/views/audit/components/AuditLogEntry.tsx
  apps/meteor/ee/client/views/audit/components/AuditLogTable.tsx
  apps/meteor/ee/client/views/audit/hooks/useAuditMutation.ts
  apps/meteor/ee/client/views/audit/hooks/useAuditTab.ts
  apps/meteor/ee/definition/IAuditLog.ts
  apps/meteor/ee/server/lib/audit/methods.ts
  apps/meteor/ee/server/models/AuditLog.ts
  apps/meteor/ee/server/models/raw/AuditLog.ts
  apps/meteor/ee/server/models/startup.ts
  packages/core-typings/src/ee/IAuditLog.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/IAuditLogModel.ts
  packages/models/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#28807 regression: add missing await for RocketChatFile
  apps/meteor/app/custom-sounds/server/methods/deleteCustomSound.ts
  apps/meteor/app/custom-sounds/server/methods/insertOrUpdateSound.ts
  apps/meteor/app/custom-sounds/server/methods/uploadCustomSound.ts
  apps/meteor/app/custom-sounds/server/startup/custom-sounds.js
  apps/meteor/app/emoji-custom/server/methods/deleteEmojiCustom.ts
  apps/meteor/app/emoji-custom/server/methods/insertOrUpdateEmoji.ts
  apps/meteor/app/emoji-custom/server/methods/uploadEmojiCustom.ts
  apps/meteor/app/emoji-custom/server/startup/emoji-custom.js
Labels: stat: ready to merge, stat: QA skipped

#28803 refactor: Remove unnecessary Tokens collection and Fibers usage
  apps/meteor/app/apps/server/bridges/uploads.ts
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/file-upload/server/lib/proxy.ts
  apps/meteor/app/file-upload/ufs/AmazonS3/server.ts
  apps/meteor/app/file-upload/ufs/GoogleStorage/server.ts
  apps/meteor/app/file-upload/ufs/Webdav/server.ts
  apps/meteor/app/file/server/file.server.js
  apps/meteor/app/importer-pending-files/server/importer.js
  apps/meteor/app/lib/server/functions/setRoomAvatar.ts
  apps/meteor/app/lib/server/functions/setUserAvatar.ts
  apps/meteor/app/livechat/imports/server/rest/sms.js
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/server/lib/dataExport/uploadZipFile.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/File.ts
  apps/meteor/server/startup/initialData.js
  apps/meteor/server/ufs/definition.ts
  apps/meteor/server/ufs/index.ts
  apps/meteor/server/ufs/ufs-filter.ts
  apps/meteor/server/ufs/ufs-gridfs.ts
  apps/meteor/server/ufs/ufs-local.ts
  apps/meteor/server/ufs/ufs-methods.ts
  apps/meteor/server/ufs/ufs-server.ts
  apps/meteor/server/ufs/ufs-store.ts
  apps/meteor/server/ufs/ufs-tokens.ts
Labels: stat: ready to merge, stat: QA skipped

#28809 regression: remove callbacks from `Meteor.callAsync`
  apps/meteor/app/slashcommands-hide/server/hide.ts
  apps/meteor/app/slashcommands-open/client/client.ts
  apps/meteor/app/slashcommands-status/client/status.ts
  apps/meteor/app/slashcommands-status/server/status.ts
  apps/meteor/app/slashcommands-topic/client/topic.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
Labels: stat: ready to merge, stat: QA skipped

#28776 refactor: Remove fibers from `rocketchat-version` package
  apps/meteor/packages/rocketchat-version/plugin/compile-version.js
Labels: stat: ready to merge, stat: QA skipped

#28813 refactor: `Service Configuration` async on server
  apps/meteor/app/api/server/v1/settings.ts
  apps/meteor/app/apple/server/appleOauthRegisterService.ts
  apps/meteor/app/cas/server/cas_rocketchat.js
  apps/meteor/app/custom-oauth/client/custom_oauth_client.js
  apps/meteor/app/custom-oauth/server/custom_oauth_server.js
  apps/meteor/app/dolphin/lib/common.js
  apps/meteor/app/lib/server/functions/getAvatarSuggestionForUser.ts
  apps/meteor/app/lib/server/methods/refreshOAuthService.ts
  apps/meteor/app/lib/server/oauth/oauth.js
  apps/meteor/app/lib/server/startup/oAuthServicesUpdate.js
  apps/meteor/app/meteor-accounts-saml/client/saml_client.js
  apps/meteor/app/meteor-accounts-saml/server/lib/settings.ts
  apps/meteor/app/wordpress/lib/common.js
  apps/meteor/server/services/meteor/service.ts
  apps/meteor/server/startup/migrations/v267.ts
Labels: stat: ready to merge, stat: QA skipped

#28453 fix: Confirm password flow fixed and refactored
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
Labels: type: bug, stat: ready to merge, stat: QA tested

#28428 fix: check if custom field is required to apply rule
  apps/meteor/client/components/CustomFieldsFormV2.tsx
  apps/meteor/client/views/omnichannel/components/CustomField.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28647 refactor(Meteor.user): Remove all occurrences
  apps/meteor/app/2fa/client/TOTPOAuth.js
  apps/meteor/app/2fa/client/TOTPPassword.js
  apps/meteor/app/2fa/client/overrideMeteorCall.ts
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/autotranslate/client/lib/autotranslate.ts
  apps/meteor/app/lib/client/methods/sendMessage.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/models/client/index.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/reactions/client/methods/setReaction.ts
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/app/ui/client/lib/UserAction.ts
  apps/meteor/app/utils/client/lib/RestApiClient.ts
  apps/meteor/app/utils/server/functions/safeGetMeteorUser.ts
  apps/meteor/client/lib/2fa/overrideLoginMethod.ts
  apps/meteor/client/lib/2fa/process2faReturn.ts
  apps/meteor/client/startup/iframeCommands.ts
  apps/meteor/client/startup/notifications/konchatNotifications.ts
  apps/meteor/client/startup/reloadRoomAfterLogin.ts
  apps/meteor/client/startup/routes.tsx
  apps/meteor/ee/client/apps/RealAppsEngineUIHost.js
Labels: stat: QA skipped

#28831 regression(e2e): Missing private key blocks sending message in encrypted rooms
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
Labels: stat: ready to merge, stat: QA skipped

#28600 fix: Invalid JSON in Custom Translations setting crashes the UI
  apps/meteor/app/lib/server/methods/saveSettings.ts
  apps/meteor/app/lib/server/startup/settings.ts
  apps/meteor/client/lib/utils/applyCustomTranslations.ts
  apps/meteor/client/providers/TranslationProvider.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#28779 refactor: Remove fibers from `linkedin-oauth`
  apps/meteor/packages/accounts-linkedin/linkedin.js
  apps/meteor/packages/linkedin-oauth/linkedin-client.js
  apps/meteor/packages/linkedin-oauth/linkedin-server.js
  apps/meteor/packages/linkedin-oauth/package.js
Labels: stat: QA skipped

#28774 refactor: Remove `Meteor.call` from server calls
  apps/meteor/app/apps/server/bridges/uploads.ts
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/app/lib/server/functions/notifications/index.js
  apps/meteor/app/lib/server/functions/setEmail.ts
  apps/meteor/app/slackbridge/server/SlackAdapter.js
Labels: stat: QA skipped

#28857 chore(deps): Prettier version
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/client/components/Sidebar/SidebarGenericItem.tsx
  apps/meteor/client/components/message/notification/MessageNotification.tsx
  apps/meteor/client/lib/2fa/process2faReturn.ts
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
  apps/meteor/client/startup/iframeCommands.ts
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/dataView/periods.ts
  apps/meteor/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/eslint-config/package.json
  packages/fuselage-ui-kit/package.json
  packages/instance-status/package.json
  yarn.lock
Labels: stat: needs QA

#28830 feat: add GA4 support
  apps/meteor/app/analytics/client/loadScript.ts
Labels: stat: ready to merge, stat: QA skipped

#28753 chore: Update issue_template.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: documentation, stat: ready to merge, stat: QA skipped

#28771 refactor: Move callbacks to ts - 2
  apps/meteor/app/e2e/server/beforeCreateRoom.ts
  apps/meteor/app/e2e/server/index.ts
  apps/meteor/app/emoji-emojione/server/callbacks.ts
  apps/meteor/app/federation/server/lib/callbacks.ts
  apps/meteor/app/integrations/server/triggers.ts
  apps/meteor/app/lib/server/startup/filterATAllTag.ts
  apps/meteor/app/lib/server/startup/filterATHereTag.ts
  apps/meteor/app/markdown/server/index.ts
  apps/meteor/app/mentions/server/server.ts
  apps/meteor/app/nextcloud/server/addWebdavServer.ts
  apps/meteor/app/threads/server/hooks/aftersavemessage.ts
  apps/meteor/app/threads/server/hooks/index.ts
  apps/meteor/ee/app/license/server/settings.ts
  apps/meteor/ee/app/license/server/startup.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/methods/addAllUserToRoom.ts
  packages/core-typings/src/IUser.ts
Labels: stat: QA skipped

#28822 refactor: remove some Meteor.bindEnvironment
  apps/meteor/app/apps/server/bridges/api.ts
  apps/meteor/app/apps/server/bridges/cloud.ts
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/cas/server/cas_server.js
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js
  apps/meteor/app/custom-sounds/server/startup/custom-sounds.js
  apps/meteor/app/emoji-custom/server/methods/insertOrUpdateEmoji.ts
  apps/meteor/app/emoji-custom/server/methods/uploadEmojiCustom.ts
  apps/meteor/app/emoji-custom/server/startup/emoji-custom.js
  apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.js
  apps/meteor/app/importer-hipchat-enterprise/server/importer.js
  apps/meteor/app/importer/server/methods/downloadPublicImportFile.ts
  apps/meteor/app/importer/server/methods/uploadImportFile.ts
  apps/meteor/app/irc/server/irc-bridge/index.js
  apps/meteor/app/lib/server/lib/processDirectEmail.ts
  apps/meteor/app/lib/server/startup/rateLimiter.js
  apps/meteor/app/lib/server/startup/robots.js
  apps/meteor/app/livechat/server/hooks/offlineMessage.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/stream/agentStatus.ts
  apps/meteor/app/livechat/server/livechat.ts
  apps/meteor/app/nextcloud/lib/common.js
  apps/meteor/app/search/server/service/SearchProviderService.ts
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/ui-master/server/index.js
  apps/meteor/app/wordpress/lib/common.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
  apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
  apps/meteor/ee/server/apps/appRequestsCron.ts
  apps/meteor/ee/server/apps/cron.js
  apps/meteor/ee/server/requestSeatsRoute.ts
  apps/meteor/packages/meteor-restivus/lib/json-routes.js
  apps/meteor/server/features/EmailInbox/EmailInbox.ts
  apps/meteor/server/lib/dataExport/exportRoomMessagesToFile.ts
  apps/meteor/server/modules/core-apps/nps/createModal.ts
  apps/meteor/server/routes/avatar/middlewares/auth.js
  apps/meteor/server/routes/avatar/room.js
  apps/meteor/server/routes/avatar/user.js
  apps/meteor/server/routes/i18n.ts
  apps/meteor/server/routes/userDataDownload.ts
  apps/meteor/server/services/nps/getAndCreateNpsSurvey.ts
  apps/meteor/server/services/nps/notification.ts
  apps/meteor/server/services/nps/sendNpsResults.ts
  apps/meteor/tests/end-to-end/api/12-emoji-custom.js
  apps/meteor/tests/end-to-end/api/17-custom-sounds.js
  apps/meteor/tests/mocks/files/audio_mock.wav
Labels: stat: ready to merge, stat: QA skipped

#28791 refactor: Make `onLicense` support async callbacks
  apps/meteor/ee/app/api-enterprise/server/index.ts
  apps/meteor/ee/app/canned-responses/server/index.js
  apps/meteor/ee/app/canned-responses/server/index.ts
  apps/meteor/ee/app/license/server/license.ts
  apps/meteor/ee/app/livechat-enterprise/server/index.ts
  apps/meteor/ee/app/message-read-receipt/server/index.ts
  apps/meteor/ee/app/teams-mention/server/index.ts
  apps/meteor/ee/app/voip-enterprise/server/services/voipService.ts
  apps/meteor/ee/server/configuration/oauth.ts
  apps/meteor/ee/server/configuration/saml.ts
  apps/meteor/ee/server/models/startup.ts
  apps/meteor/ee/server/startup/audit.ts
  apps/meteor/ee/server/startup/services.ts
Labels: stat: ready to merge, stat: QA skipped

#28861 fix(docs,readme): use raw image url
  README.md
Labels: stat: ready to merge, stat: QA skipped

#28866 regression: `fetch` call in `getWorkspaceAccessTokenWithScope`
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js
Labels: stat: ready to merge, stat: QA skipped

#28806 fix: Add function to get installation source
  apps/meteor/ee/app/license/server/lib/isUnderAppLimits.ts
  apps/meteor/ee/app/license/server/license.ts
  apps/meteor/ee/lib/misc/formatAppInstanceForRest.ts
  apps/meteor/ee/server/apps/communication/endpoints/appsCountHandler.ts
  apps/meteor/lib/apps/getInstallationSourceFromAppStorageItem.ts
Labels: stat: ready to merge, stat: QA tested

#28798 fix: quote line break
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#28141 chore: Limit 10 usernames on reactions tooltip
  apps/meteor/client/components/message/content/reactions/Reaction.tsx
Labels: stat: ready to merge, stat: QA tested

#28874 revert: removal of `Meteor.bindEnvironment` on `DDPRateLimiter.addRule`
  apps/meteor/app/lib/server/startup/rateLimiter.js
Labels: stat: ready to merge, stat: QA skipped

#28860 chore(deps): Upgrade `vm2`
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27778 chore: Modal form wrapper
  apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx
  apps/meteor/client/components/GenericModal.tsx
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorEmailModal.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorPasswordModal.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorTotpModal.tsx
  apps/meteor/client/components/withDoNotAskAgain.tsx
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/client/sidebar/header/CreateDirectMessage.tsx
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
  apps/meteor/client/sidebar/header/EditStatusModal.tsx
  apps/meteor/client/views/account/profile/ActionConfirmModal.tsx
  apps/meteor/client/views/admin/info/FederationCard/components/FederationModal/FederationModal.tsx
  apps/meteor/client/views/admin/info/OfflineLicenseModal.tsx
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/settings/groups/CreateOAuthModal.tsx
  apps/meteor/client/views/admin/settings/groups/LDAPGroupPage.tsx
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage.tsx
  apps/meteor/client/views/admin/settings/groups/voip/AssignAgentModal.tsx
  apps/meteor/client/views/e2e/EnterE2EPasswordModal.tsx
  apps/meteor/client/views/omnichannel/departments/PermanentDepartmentRemovalModal.tsx
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
  apps/meteor/client/views/room/modals/ReportMessageModal/ReportMessageModal.tsx
  apps/meteor/client/views/room/webdav/AddWebdavAccountModal.tsx
  apps/meteor/client/views/room/webdav/SaveToWebdavModal.tsx
  apps/meteor/client/views/teams/contextualBar/channels/AddExistingModal/AddExistingModal.tsx
  apps/meteor/ee/client/voip/components/modals/WrapUpCallModal.tsx
  apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
Labels: stat: ready to merge, stat: QA skipped

#28584 fix: Hide System Messages for room requires refresh
  apps/meteor/client/views/room/MessageList/hooks/useMessages.ts
  packages/core-typings/src/IRoom.ts
Labels: stat: ready to merge, stat: QA tested

#28832 fix: SMTP warnings on user form
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/lib/server/startup/settingsOnLoadSMTP.ts
  apps/meteor/client/views/admin/users/AddUser.js
  apps/meteor/client/views/admin/users/EditUser.js
  apps/meteor/client/views/admin/users/InviteUsers.tsx
  apps/meteor/client/views/admin/users/UserForm.js
  apps/meteor/client/views/admin/users/hooks/useSmtpConfig.ts
  packages/rest-typings/src/v1/misc.ts
Labels: stat: ready to merge, stat: QA tested

#28885 chore: bump apps-engine version to 1.38.1
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28613 fix: `UI_Use_Real_Name` not being respected in quotes and RoomForeword
  apps/meteor/app/apps/server/converters/rooms.js
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/lib/client/methods/sendMessage.ts
  apps/meteor/app/lib/server/functions/attachMessage.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/oembed/server/jumpToMessage.ts
  apps/meteor/client/components/message/MessageHeader.tsx
  apps/meteor/client/components/message/variants/SystemMessage.tsx
  apps/meteor/client/hooks/useUserDisplayName.ts
  apps/meteor/client/hooks/useUserInfoQuery.ts
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/components/body/RoomForeword/RoomForeword.tsx
  apps/meteor/client/views/room/components/body/RoomForeword/RoomForewordUsernameList.tsx
  apps/meteor/client/views/room/components/body/RoomForeword/RoomForewordUsernameListItem.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxReplies.tsx
  apps/meteor/client/views/room/modals/ShareMessageModal/ShareMessageModal.tsx
  apps/meteor/lib/createQuoteAttachment.ts
  apps/meteor/lib/getUserDisplayName.ts
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/services/messages/service.ts
  packages/core-services/src/types/IMessageService.ts
  packages/model-typings/src/models/IMessagesModel.ts
Labels: stat: ready to merge, stat: QA tested

#28741 fix: Livechat notifications not working correctly
  packages/livechat/src/components/Messages/MessageList/index.js
  packages/livechat/src/components/Messages/constants.js
  packages/livechat/src/components/helpers.js
  packages/livechat/src/lib/main.js
  packages/livechat/src/routes/Chat/component.js
  packages/livechat/src/routes/Chat/container.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28887 Bump apps-engine to v1.36.1
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28888 Bump apps-engine to v1.37.2
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#26810 chore: create EditOauthApp endpoints
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/app/oauth2-server-config/server/admin/methods/addOAuthApp.ts
  apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx
  apps/meteor/tests/end-to-end/api/18-oauthapps.js
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/Ajv.ts
  packages/rest-typings/src/v1/oauthapps.ts
  packages/rest-typings/src/v1/oauthapps/DeleteOAuthAppParamsDELETE.ts
  packages/rest-typings/src/v1/oauthapps/OAuthAppsAddParamsPOST.ts
  packages/rest-typings/src/v1/oauthapps/OAuthAppsGetParamsGET.ts
  packages/rest-typings/src/v1/oauthapps/UpdateOAuthAppParamsPOST.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28893 fix(client): Small UI bugs
  apps/meteor/app/settings/index.js
  apps/meteor/app/utils/index.js
  apps/meteor/client/views/room/components/body/composer/messageBox/hooks/useMessageBoxAutoFocus.ts
Labels: stat: ready to merge, stat: QA skipped

#28891 Release 6.1.2
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/startup/settingsOnLoadSMTP.ts
  apps/meteor/app/oembed/server/jumpToMessage.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/client/views/admin/users/AddUser.js
  apps/meteor/client/views/admin/users/EditUser.js
  apps/meteor/client/views/admin/users/InviteUsers.tsx
  apps/meteor/client/views/admin/users/UserForm.js
  apps/meteor/client/views/admin/users/hooks/useSmtpConfig.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx
  apps/meteor/ee/app/license/server/lib/isUnderAppLimits.ts
  apps/meteor/ee/app/license/server/license.ts
  apps/meteor/ee/lib/misc/formatAppInstanceForRest.ts
  apps/meteor/ee/server/apps/communication/endpoints/appsCountHandler.ts
  apps/meteor/lib/apps/getInstallationSourceFromAppStorageItem.ts
  apps/meteor/package.json
  package.json
  packages/rest-typings/src/v1/misc.ts
  yarn.lock
Labels: stat: needs QA

#28884 chore: Update meteor types
  apps/meteor/app/2fa/server/loginHandler.ts
  apps/meteor/app/crowd/server/crowd.js
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/ServiceProvider.ts
  apps/meteor/app/slackbridge/server/RocketAdapter.js
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-mongo-config/server/index.js
  apps/meteor/server/lib/ldap/Manager.ts
  apps/meteor/server/methods/registerUser.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/methods/setUserPassword.ts
  apps/meteor/server/startup/initialData.js
  ee/apps/ddp-streamer/package.json
  packages/ui-contexts/src/UserContext.ts
  packages/ui-contexts/src/hooks/useLoginWithPassword.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#27645 fix: Responsiveness of New Integration
  apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js
  apps/meteor/client/views/admin/integrations/OutgoiongWebhookForm.js
Labels: stat: ready to merge, stat: QA skipped

#28778 fix: Resolve Reset Password feature not sending email for emails containing capital letters
  apps/meteor/app/api/server/v1/users.ts
Labels: stat: ready to merge, stat: QA skipped

#28899 regression: push gateway response as JSON
  apps/meteor/app/push/server/push.js
Labels: stat: ready to merge, stat: QA skipped

#28894 chore: Change Restore Section Settings button text
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#28858 ci: new label to check stale condition
  .github/workflows/stale.yml
Labels: stat: ready to merge, stat: QA skipped

#28871 i18n: German translation
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
Labels: feat: i18n, stat: ready to merge, stat: QA skipped

#28785 refactor: Apps modal adjustments and Typescript rewrite
  .vscode/settings.json
  apps/meteor/app/ui-message/client/ActionManager.js
  apps/meteor/client/components/message/content/UiKitSurface.tsx
  apps/meteor/client/components/message/content/uikit/ParsedText.tsx
  apps/meteor/client/lib/normalizeThreadMessage.tsx
  apps/meteor/client/views/blocks/ConnectedModalBlock.js
  apps/meteor/client/views/blocks/textParsers.js
  apps/meteor/client/views/modal/uikit/ModalBlock.tsx
  apps/meteor/client/views/modal/uikit/UiKitModal.tsx
  apps/meteor/client/views/modal/uikit/getButtonStyle.ts
  apps/meteor/client/views/modal/uikit/hooks/useActionManagerState.ts
  apps/meteor/client/views/modal/uikit/hooks/useValues.ts
  apps/meteor/client/views/room/contextualBar/Apps/Apps.tsx
  packages/fuselage-ui-kit/src/surfaces/FuselageModalSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/FuselageSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/index.ts
Labels: stat: ready to merge, stat: QA skipped

#27587 fix: Revert breaking change to groups.list API: 404 vs. empty list
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
Labels: stat: ready to merge, stat: QA skipped

#28416 fix: `emoji` property in messages not being respected
  apps/meteor/client/components/Emoji.tsx
  apps/meteor/client/components/message/header/MessageAvatar.tsx
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/lib/lists/DiscussionsList.ts
  apps/meteor/client/lib/lists/MessageList.ts
  apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsList.tsx
  apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsListContextBar.tsx
  apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsListRow.tsx
  apps/meteor/client/views/room/contextualBar/Discussions/components/DiscussionMessage.js
  apps/meteor/client/views/room/contextualBar/Discussions/components/DiscussionsListItem.stories.tsx
  apps/meteor/client/views/room/contextualBar/Discussions/components/DiscussionsListItem.tsx
  apps/meteor/client/views/room/contextualBar/Discussions/index.ts
  apps/meteor/client/views/room/contextualBar/Discussions/mapProps.js
  apps/meteor/client/views/room/contextualBar/Discussions/useDiscussionsList.ts
  apps/meteor/client/views/room/contextualBar/Discussions/withData.js
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadListItem.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadListMessage.tsx
Labels: stat: ready to merge, stat: QA tested

#28913 chore: fix ha scripts
  apps/meteor/package.json
Labels: stat: ready to merge, stat: QA skipped

#28658 chore: improve tests for livechat/config api
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/livechat/users.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#28886 chore: adjust sidebarPalette font colors
  ee/packages/ui-theming/src/sidebarPalette.ts
  ee/packages/ui-theming/src/sidebarPaletteDark.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28877 fix: Single omni closed room can't be deleted when the user doesn't have the permission to 'remove all closed omni rooms'
  apps/meteor/app/livechat/server/methods/removeRoom.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#28219 feat: New timeout setting for Omnichannel Webhooks
  apps/meteor/app/livechat/server/api/lib/integrations.ts
  apps/meteor/app/livechat/server/api/rest.ts
  apps/meteor/app/livechat/server/api/v1/integration.ts
  apps/meteor/app/livechat/server/config.ts
  apps/meteor/app/livechat/server/hooks/offlineMessage.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/methods/saveIntegration.ts
  apps/meteor/app/metrics/server/lib/metrics.js
  apps/meteor/client/views/omnichannel/webhooks/WebhooksPage.js
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/server/lib/http/fetch.ts
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
  packages/rest-typings/src/v1/omnichannel.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28834 refactor: Remove `logging` and `gravatar` packages
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/app/lib/server/functions/getAvatarSuggestionForUser.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/definition/externals/meteor/jparker-gravatar.d.ts
  apps/meteor/package.json
  apps/meteor/server/stream/stdout.ts
  packages/log-format/.eslintrc.json
  packages/log-format/package.json
  packages/log-format/src/index.ts
  packages/log-format/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28905 fix: Fixed join button being displayed for agents without permission
  apps/meteor/client/views/room/providers/RoomProvider.tsx
Labels: stat: needs QA, feat: omnichannel

#28883 fix: Delete accounts modal asks for a username instead of the password
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
  apps/meteor/client/views/account/profile/ActionConfirmModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/IUser.ts
Labels: stat: ready to merge, stat: QA tested

#28667 fix: team channel reload error message
  apps/meteor/client/views/teams/contextualBar/channels/AddExistingModal/AddExistingModal.tsx
  apps/meteor/tests/e2e/team-management.spec.ts
Labels: stat: ready to merge, stat: QA tested

#28922 regression: Render `Markup` for all UiKit surfaces
  apps/meteor/client/components/GazzodownText.tsx
  apps/meteor/client/components/message/MessageContentBody.tsx
  apps/meteor/client/components/message/content/UiKitSurface.tsx
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.tsx
  apps/meteor/client/lib/normalizeThreadMessage.tsx
  apps/meteor/client/views/modal/uikit/ModalBlock.tsx
  apps/meteor/client/views/room/contextualBar/Apps/Apps.tsx
  packages/fuselage-ui-kit/package.json
  packages/fuselage-ui-kit/src/surfaces/FuselageModalSurfaceRenderer.tsx
  packages/fuselage-ui-kit/src/surfaces/FuselageSurfaceRenderer.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28896 fix: `ComposerPopupPreview` trespassing the composer limit
  apps/meteor/app/ui-message/client/popup/ComposerBoxPopup.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopupPreview/ComposerBoxPopupPreview.tsx
Labels: stat: ready to merge, stat: QA skipped

#28833 refactor(client): Remove dangling `direct` field on minimongo collections
  apps/meteor/app/models/client/models/ChatMessage.ts
  apps/meteor/app/models/client/models/Roles.ts
  apps/meteor/client/definitions/MinimongoCollection.ts
Labels: stat: ready to merge, stat: QA skipped

#28470 fix: Thread message preview to ignore hide_FlexTab preference
  apps/meteor/client/components/message/content/ThreadMetrics.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/thread-actions.spec.ts
  apps/meteor/tests/e2e/threads.spec.ts
Labels: stat: ready to merge, stat: QA tested

#28559 chore: New inquiry functional test
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts
  packages/core-typings/src/IInquiry.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#28305 fix: Export as PDF button is disabled when chat is closed by the visitor
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/ComposerOmnichannel.tsx
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/tests/e2e/omnichannel-close-inquiry.spec.ts
  apps/meteor/tests/e2e/page-objects/home-omnichannel.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-current-chats.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28943 docs: how can i help? link broken
  README.md
Labels: stat: ready to merge, stat: QA skipped

#28938 fix: Error logging in with TOTP on "reset password" workflow
  apps/meteor/app/2fa/server/loginHandler.ts
Labels: stat: ready to merge, stat: QA tested

#27961 feat: Moderation Console
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/lib/createSidebarItems.ts
  apps/meteor/client/views/admin/moderation/MessageContextFooter.tsx
  apps/meteor/client/views/admin/moderation/MessageReportInfo.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleActions.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsolePage.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleRoute.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleTable.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleTableRow.tsx
  apps/meteor/client/views/admin/moderation/UserMessages.tsx
  apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx
  apps/meteor/client/views/admin/moderation/helpers/DateRangePicker.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDeactivateUserAction.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDeleteMessage.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDeleteMessagesAction.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDismissUserAction.tsx
  apps/meteor/client/views/admin/moderation/hooks/useResetAvatarAction.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useRedirectModerationConsole.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/useUserInfoActions.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rest-typings/src/v1/moderation/ArchiveReportProps.ts
Labels: stat: needs QA

#28952 regression: `fetch` JSON response doesn't have a `data` property
  apps/meteor/app/version-check/server/functions/getNewUpdates.ts
  apps/meteor/ee/server/apps/appRequestsCron.ts
  apps/meteor/ee/server/apps/cron.js
  apps/meteor/ee/server/apps/marketplace/appRequestNotifyUsers.ts
  apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts
Labels: stat: ready to merge, stat: QA skipped

#28945 refactor: convert migration model to raw
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/server/lib/migrations.ts
  apps/meteor/server/models/Migrations.ts
  apps/meteor/server/models/raw/Migrations.ts
  apps/meteor/server/models/startup.ts
  packages/core-typings/src/IStats.ts
  packages/core-typings/src/index.ts
  packages/core-typings/src/migrations/IControl.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/IMigrationsModel.ts
  packages/models/src/index.ts
Labels: stat: needs QA

#28941 refactor: Remove mongo collections from migrations
  apps/meteor/server/startup/migrations/v267.ts
  apps/meteor/server/startup/migrations/v287.ts
  apps/meteor/server/startup/migrations/v290.ts
Labels: stat: needs QA

#28939 refactor: Convert trash to raw
  apps/meteor/server/database/trash.ts
  apps/meteor/server/models/raw/Trash.ts
Labels: stat: ready to merge, stat: QA skipped

#28876 refactor: internalize user-presence package
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/client/startup/startup.ts
  apps/meteor/definition/externals/meteor/konecty-user-presence.d.ts
  apps/meteor/packages/meteor-user-presence/.gitignore
  apps/meteor/packages/meteor-user-presence/client/client.js
  apps/meteor/packages/meteor-user-presence/client/utils.js
  apps/meteor/packages/meteor-user-presence/package.js
Labels: stat: ready to merge, stat: QA skipped

#28942 regression: smtp connection error
  apps/meteor/app/mailer/server/api.ts
Labels: stat: ready to merge, stat: QA skipped

#28980 regression: Message auditing panel not working
  apps/meteor/ee/server/models/AuditLog.ts
  apps/meteor/ee/server/models/raw/AuditLog.ts
  apps/meteor/server/models/raw/Users.js
Labels: stat: needs QA

#28892 refactor: Remove Meteor timers
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/autotranslate/server/autotranslate.ts
  apps/meteor/app/cas/server/cas_rocketchat.js
  apps/meteor/app/cloud/server/index.js
  apps/meteor/app/crowd/server/crowd.js
  apps/meteor/app/emoji-custom/server/methods/uploadEmojiCustom.ts
  apps/meteor/app/importer-pending-avatars/server/importer.js
  apps/meteor/app/importer-pending-files/server/importer.js
  apps/meteor/app/integrations/server/lib/triggerHandler.js
  apps/meteor/app/lib/server/functions/setRoomAvatar.ts
  apps/meteor/app/lib/server/functions/setUserAvatar.ts
  apps/meteor/app/lib/server/functions/setUsername.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/lib/meteorFixes.js
  apps/meteor/app/lib/server/methods/restartServer.ts
  apps/meteor/app/lib/server/methods/setUsername.ts
  apps/meteor/app/livechat/imports/server/rest/sms.js
  apps/meteor/app/livechat/server/lib/Departments.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/methods/saveInfo.ts
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/app/meteor-autocomplete/client/autocomplete-client.js
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/push/server/push.js
  apps/meteor/app/slackbridge/server/RocketAdapter.js
  apps/meteor/app/smarsh-connector/server/functions/generateEml.js
  apps/meteor/app/ui-message/client/popup/messagePopupSlashCommandPreview.ts
  apps/meteor/app/version-check/server/index.ts
  apps/meteor/app/webrtc/client/WebRTCClass.js
  apps/meteor/client/startup/e2e.ts
  apps/meteor/client/startup/notifications/notification.ts
  apps/meteor/client/startup/routes.tsx
  apps/meteor/ee/app/livechat-enterprise/server/methods/resumeOnHold.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/packages/meteor-restivus/lib/route.js
  apps/meteor/server/methods/logoutCleanUp.ts
  apps/meteor/server/methods/removeUserFromRoom.ts
  apps/meteor/server/methods/saveUserPreferences.ts
  apps/meteor/server/methods/unmuteUserInRoom.ts
  apps/meteor/server/startup/serverRunning.js
Labels: stat: ready to merge, stat: QA skipped

#28992 regression: Emoji fill prop
  apps/meteor/client/components/Emoji.tsx
Labels: stat: needs QA

#28966 regression: Reactivity Issue when agent takes a chat
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/RoutingManager.js
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onAgentAssignmentFailed.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28957 regression: Livechat rooms not opening
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/lib/rooms/roomTypes/livechat.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28965 fix: Fixing the user status change by app
  apps/meteor/app/apps/server/bridges/users.ts
Labels: stat: needs QA

#28994 Bump apps-engine to v1.37.3
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28993 Bump apps-engine to v1.36.2
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28997 Bump apps-engine version to 1.38.2
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29005 Release 6.1.4
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#28998 regression: user creation is failing
  apps/meteor/app/utils/server/functions/safeGetMeteorUser.ts
Labels: stat: needs QA

#29009 chore(deps): Bump apps-engine version to 1.38.2
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#29002 refactor: Remove _sleepForMs usage
  apps/meteor/app/lib/server/startup/rateLimiter.js
  apps/meteor/app/slackbridge/server/RocketAdapter.js
  apps/meteor/lib/utils/sleep.ts
  apps/meteor/server/lib/migrations.ts
Labels: stat: ready to merge, stat: QA skipped

#28882 refactor(oauth-server): Import code, convert to TS and update dependency
  apps/meteor/app/oauth2-server-config/server/admin/methods/deleteOAuthApp.ts
  apps/meteor/app/oauth2-server-config/server/oauth/oauth2-server.ts
  apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx
  apps/meteor/package.json
  apps/meteor/server/models/OAuthAccessTokens.ts
  apps/meteor/server/models/OAuthAuthCodes.ts
  apps/meteor/server/models/OAuthRefreshTokens.ts
  apps/meteor/server/models/raw/OAuthAccessTokens.ts
  apps/meteor/server/models/raw/OAuthApps.ts
  apps/meteor/server/models/raw/OAuthAuthCodes.ts
  apps/meteor/server/models/raw/OAuthRefreshTokens.ts
  apps/meteor/server/models/startup.ts
  apps/meteor/server/oauth2-server/model.ts
  apps/meteor/server/oauth2-server/oauth.ts
  apps/meteor/tests/end-to-end/api/28-roles.ts
  apps/meteor/tests/end-to-end/api/29-oauth-server.ts
  apps/meteor/tsconfig.json
  packages/core-typings/src/IOAuthAccessToken.ts
  packages/core-typings/src/IOAuthAuthCode.ts
  packages/core-typings/src/IOAuthRefreshToken.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/IOAuthAccessTokensModel.ts
  packages/model-typings/src/models/IOAuthAppsModel.ts
  packages/model-typings/src/models/IOAuthAuthCodesModel.ts
  packages/model-typings/src/models/IOAuthRefreshTokensModel.ts
  packages/models/src/index.ts
  yarn.lock
Labels: stat: needs QA

#29010 regression: Missing display prop on `ComposerBoxPopupPreview`
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopupPreview/ComposerBoxPopupPreview.tsx
Labels: type: bug, stat: ready to merge, stat: QA skipped

#29028 Release 6.1.5
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
  yarn.lock
Labels: stat: needs QA

#29032 regression: `fetch` response
  apps/meteor/app/apple/lib/handleIdentityToken.ts
  apps/meteor/app/autotranslate/server/googleTranslate.ts
Labels: type: regression, stat: ready to merge, stat: QA skipped

#29021 regression: Fixed livechat notifications displaying [object Promise] on title
  apps/meteor/server/lib/rooms/roomTypes/livechat.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28961 fix: `HeaderTag`
  apps/meteor/client/views/room/Header/FederatedRoomOriginServer.tsx
  apps/meteor/client/views/room/Header/ParentRoom.tsx
  apps/meteor/client/views/room/Header/ParentTeam.tsx
  packages/ui-client/src/components/Header/HeaderLink.tsx
  packages/ui-client/src/components/Header/HeaderTag.tsx
  packages/ui-client/src/components/Header/HeaderTagIcon.tsx
  packages/ui-client/src/components/Header/index.ts
Labels: stat: ready to merge, stat: QA skipped

#29050 regression: SlackBridge settings UI crashing
  apps/meteor/client/views/admin/settings/inputs/RoomPickSettingInput.tsx
Labels: stat: needs QA

#28977 refactor: No reference to jQuery types
  apps/meteor/app/custom-sounds/client/lib/CustomSounds.js
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.js
  apps/meteor/app/emoji/client/emojiPicker.js
  apps/meteor/app/emoji/client/lib/EmojiPicker.js
  apps/meteor/app/meteor-autocomplete/client/autocomplete-client.js
  apps/meteor/app/meteor-autocomplete/client/templates.js
  apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
  apps/meteor/app/ui-utils/client/lib/readMessages.ts
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/app/ui/client/views/app/photoswipeContent.ts
  apps/meteor/client/lib/errorHandling.ts
  apps/meteor/definition/externals/meteor/templating.d.ts
  packages/eslint-config/original/index.js
Labels: stat: ready to merge, stat: QA skipped

#28925 refactor: Remove Meteor.userId from Slashcommands
  apps/meteor/app/api/server/v1/commands.ts
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/slackbridge/server/slackbridge_import.server.js
  apps/meteor/app/slashcommand-asciiarts/client/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/client/index.ts
  apps/meteor/app/slashcommand-asciiarts/client/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/client/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/client/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/client/unflip.ts
  apps/meteor/app/slashcommand-asciiarts/server/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/server/index.ts
  apps/meteor/app/slashcommand-asciiarts/server/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/server/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/server/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/server/unflip.ts
  apps/meteor/app/slashcommands-archiveroom/server/server.ts
  apps/meteor/app/slashcommands-create/server/server.ts
  apps/meteor/app/slashcommands-help/server/server.ts
  apps/meteor/app/slashcommands-hide/server/hide.ts
  apps/meteor/app/slashcommands-invite/server/server.ts
  apps/meteor/app/slashcommands-inviteall/server/server.ts
  apps/meteor/app/slashcommands-join/client/client.ts
  apps/meteor/app/slashcommands-join/server/server.ts
  apps/meteor/app/slashcommands-kick/client/client.ts
  apps/meteor/app/slashcommands-kick/server/server.ts
  apps/meteor/app/slashcommands-leave/server/leave.ts
  apps/meteor/app/slashcommands-me/server/me.ts
  apps/meteor/app/slashcommands-msg/server/server.ts
  apps/meteor/app/slashcommands-mute/server/mute.ts
  apps/meteor/app/slashcommands-mute/server/unmute.ts
  apps/meteor/app/slashcommands-open/client/client.ts
  apps/meteor/app/slashcommands-status/client/status.ts
  apps/meteor/app/slashcommands-status/server/status.ts
  apps/meteor/app/slashcommands-topic/client/topic.ts
  apps/meteor/app/slashcommands-topic/server/topic.ts
  apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/lib/chats/flows/processSlashCommand.ts
  apps/meteor/client/views/room/providers/hooks/useChatMessagesInstance.ts
  apps/meteor/ee/server/local-services/federation/infrastructure/rocket-chat/slash-commands/index.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/slash-commands/index.ts
  packages/core-typings/src/SlashCommands/index.ts
Labels: stat: needs QA

#29052 refactor: Separate isomorphic imports on utils - 1
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/authorization/index.js
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/importer-slack/server/importer.js
  apps/meteor/app/invites/server/functions/findOrCreateInvite.js
  apps/meteor/app/lib/server/functions/attachMessage.ts
  apps/meteor/app/lib/server/functions/notifications/email.js
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/oembed/server/jumpToMessage.ts
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/app/utils/client/getAvatarURL.ts
  apps/meteor/app/utils/client/getURL.ts
  apps/meteor/app/utils/client/getUserAvatarURL.ts
  apps/meteor/app/utils/client/index.ts
  apps/meteor/app/utils/client/restrictions.ts
  apps/meteor/app/utils/lib/getURL.ts
  apps/meteor/app/utils/lib/getUserAvatarURL.js
  apps/meteor/app/utils/lib/restrictions.ts
  apps/meteor/app/utils/server/functions/normalizeMessageFileUpload.ts
  apps/meteor/app/utils/server/getAvatarURL.ts
  apps/meteor/app/utils/server/getURL.ts
  apps/meteor/app/utils/server/getUserAvatarURL.ts
  apps/meteor/app/utils/server/index.ts
  apps/meteor/app/utils/server/restrictions.ts
  apps/meteor/app/webdav/client/actionButton.ts
  apps/meteor/client/components/avatar/RoomAvatarEditor.tsx
  apps/meteor/client/components/voip/room/VoipRoomForeword.tsx
  apps/meteor/client/lib/rooms/roomTypes/direct.ts
  apps/meteor/client/lib/rooms/roomTypes/livechat.ts
  apps/meteor/client/lib/rooms/roomTypes/private.ts
  apps/meteor/client/lib/rooms/roomTypes/public.ts
  apps/meteor/client/lib/rooms/roomTypes/voip.ts
  apps/meteor/client/lib/utils/getAvatarAsPng.ts
  apps/meteor/client/providers/AvatarUrlProvider.tsx
  apps/meteor/client/templateHelpers/avatarUrlFromUsername.ts
  apps/meteor/client/views/modal/uikit/ModalBlock.tsx
  apps/meteor/client/views/room/contextualBar/Apps/Apps.tsx
  apps/meteor/ee/client/apps/RealAppsEngineUIHost.js
  apps/meteor/lib/createQuoteAttachment.ts
  apps/meteor/server/lib/dataExport/processDataDownloads.ts
  apps/meteor/server/lib/dataExport/sendFile.ts
  apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts
  apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts
  apps/meteor/tests/unit/app/utils/lib/getURL.tests.js
Labels: stat: ready to merge, stat: QA tested

#29035 regression: `ToolboxDropdown` being used as `IconButton` child
  apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx
  apps/meteor/client/components/message/toolbox/ToolboxDropdown.tsx
Labels: stat: ready to merge, stat: QA skipped

#28907 refactor: Move `cloud` and `channel settings` to typescript
  apps/meteor/app/authorization/index.ts
  apps/meteor/app/authorization/server/index.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomAnnouncement.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomCustomFields.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomDescription.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomName.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomType.ts
  apps/meteor/app/channel-settings/server/functions/saveStreamingOptions.ts
  apps/meteor/app/channel-settings/server/methods/saveRoomSettings.ts
  apps/meteor/app/cloud/server/functions/checkUserHasCloudLogin.ts
  apps/meteor/app/cloud/server/functions/finishOAuthAuthorization.ts
  apps/meteor/app/cloud/server/functions/getRedirectUri.js
  apps/meteor/app/cloud/server/functions/getRedirectUri.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceKey.ts
  apps/meteor/app/cloud/server/functions/saveRegistrationData.ts
  apps/meteor/app/cloud/server/functions/userLoggedOut.ts
  apps/meteor/app/cloud/server/functions/userLogout.ts
  apps/meteor/app/cloud/server/index.ts
  apps/meteor/app/cloud/server/license.js
  apps/meteor/app/cloud/server/license.ts
  apps/meteor/app/cloud/server/methods.ts
  apps/meteor/app/cloud/server/oauthScopes.ts
  packages/core-typings/src/IRoom.ts
Labels: stat: ready to merge, stat: QA skipped

#29065 refactor: Remove imports based on isomorphic logic - 2
  apps/meteor/app/custom-oauth/index.js
  apps/meteor/app/custom-oauth/server/custom_oauth_server.d.ts
  apps/meteor/app/dolphin/client/index.ts
  apps/meteor/app/dolphin/client/lib.ts
  apps/meteor/app/dolphin/lib/common.js
  apps/meteor/app/dolphin/server/index.ts
  apps/meteor/app/dolphin/server/lib.ts
  apps/meteor/app/drupal/client/index.ts
  apps/meteor/app/drupal/client/lib.ts
  apps/meteor/app/drupal/server/index.ts
  apps/meteor/app/drupal/server/lib.ts
  apps/meteor/app/github-enterprise/client/index.ts
  apps/meteor/app/github-enterprise/client/lib.ts
  apps/meteor/app/github-enterprise/server/index.ts
  apps/meteor/app/github-enterprise/server/lib.ts
  apps/meteor/app/gitlab/client/index.ts
  apps/meteor/app/gitlab/client/lib.ts
  apps/meteor/app/gitlab/lib/common.js
  apps/meteor/app/gitlab/server/index.ts
  apps/meteor/app/gitlab/server/lib.ts
  apps/meteor/app/nextcloud/client/index.ts
  apps/meteor/app/nextcloud/client/lib.ts
  apps/meteor/app/nextcloud/lib/common.js
  apps/meteor/app/nextcloud/server/index.ts
  apps/meteor/app/nextcloud/server/lib.ts
  apps/meteor/app/tokenpass/client/index.ts
  apps/meteor/app/tokenpass/client/lib.ts
  apps/meteor/app/tokenpass/server/index.ts
  apps/meteor/app/tokenpass/server/lib.ts
  apps/meteor/app/wordpress/client/index.ts
  apps/meteor/app/wordpress/client/lib.ts
  apps/meteor/app/wordpress/lib/common.js
  apps/meteor/app/wordpress/server/index.ts
  apps/meteor/app/wordpress/server/lib.ts
  packages/core-typings/src/ICustomOAuthConfig.ts
  packages/core-typings/src/IUser.ts
  packages/core-typings/src/index.ts
Labels: stat: needs QA

#29047 regression: Remove unused autocomplete Blaze Template
  apps/meteor/app/meteor-autocomplete/client/autocomplete-client.js
  apps/meteor/app/meteor-autocomplete/client/autocomplete.css
  apps/meteor/app/meteor-autocomplete/client/collection.js
  apps/meteor/app/meteor-autocomplete/client/index.ts
  apps/meteor/app/meteor-autocomplete/client/inputs.html
  apps/meteor/app/meteor-autocomplete/client/templates.js
  apps/meteor/client/importPackages.ts
  apps/meteor/definition/externals/meteor/templating.d.ts
Labels: stat: ready to merge, stat: QA skipped

#29053 fix: Notification badge background
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
Labels: stat: ready to merge, stat: QA skipped

#29045 chore: improve unread indicator colors
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/client/views/room/components/body/UnreadMessagesIndicator.tsx
Labels: stat: ready to merge, stat: QA skipped

#29057 chore: Remove duplicated key in turbo.json
  turbo.json
Labels: stat: ready to merge, stat: QA skipped

#29066 chore: Improve bash script and add new detailed infos
  fuselage.sh
Labels: type: improvement, stat: needs QA

#29008 chore: `PageHeader` misaligned
  apps/meteor/client/components/Page/PageHeader.tsx
Labels: stat: ready to merge, stat: QA skipped

#28909 refactor: Remove Meteor.runAsUser part 1
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/api/server/v1/integrations.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/importer-pending-avatars/server/importer.js
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/app/integrations/server/methods/incoming/deleteIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/outgoing/deleteOutgoingIntegration.ts
  apps/meteor/app/lib/server/functions/checkUsernameAvailability.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/index.ts
  apps/meteor/app/lib/server/functions/joinDefaultChannels.ts
  apps/meteor/app/lib/server/functions/setUserAvatar.ts
  apps/meteor/app/lib/server/functions/setUsername.ts
  apps/meteor/app/lib/server/methods/checkUsernameAvailability.ts
  apps/meteor/app/lib/server/methods/deleteMessage.ts
  apps/meteor/app/lib/server/methods/setUsername.ts
  apps/meteor/server/methods/deleteFileMessage.ts
  apps/meteor/server/methods/saveUserPreferences.ts
  apps/meteor/server/methods/setAvatarFromService.ts
Labels: stat: needs QA

#28924 fix: unread message counter on channels
  apps/meteor/app/ui-utils/client/lib/readMessages.ts
  apps/meteor/client/views/room/components/body/RoomBody.tsx
Labels: stat: ready to merge, stat: QA skipped

#29078 fix: JumpToRecentMessage behavior
  apps/meteor/client/views/room/components/body/JumpToRecentMessageButton.tsx
Labels: stat: ready to merge, stat: QA skipped

#29086 fix: composer slashcommands duplication
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts
Labels: stat: needs QA

#29006 regression: Room crashes
  apps/meteor/app/authorization/client/hasPermission.ts
  apps/meteor/app/lib/server/functions/loadMessageHistory.ts
  apps/meteor/app/models/client/models/CachedChatSubscription.ts
  apps/meteor/app/models/client/models/Users.ts
  apps/meteor/app/utils/server/lib/normalizeMessagesForUser.ts
  apps/meteor/client/hooks/useReactiveQuery.ts
  apps/meteor/client/lib/userData.ts
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useRoomQuery.ts
  apps/meteor/client/views/root/MainLayout/UsernameCheck.tsx
  apps/meteor/lib/publishFields.ts
  apps/meteor/server/methods/loadHistory.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  apps/meteor/server/publications/room/index.ts
  apps/meteor/server/publications/subscription/index.ts
Labels: stat: needs QA

#29089 fix: Custom Sounds not being added to the DOM correctly
  apps/meteor/app/custom-sounds/client/lib/CustomSounds.ts
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/providers/CustomSoundProvider.tsx
  apps/meteor/client/startup/notifications/notification.ts
  packages/core-typings/src/ICustomSound.ts
  packages/ui-contexts/src/CustomSoundContext.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29073 regression: fix issue with triggers
  packages/livechat/src/lib/main.js
Labels: stat: ready to merge, stat: QA tested
