Repository RocketChat/Rocket.Chat, pull requests merged in 2023-09, with the labels that each got.

#30106 fix: Login page language switcher
  .changeset/wise-onions-trade.md
  .yarn/patches/@storybook-react-docgen-typescript-plugin-npm-1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0-b31cc57c40.patch
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/utils/lib/i18n.ts
  apps/meteor/client/providers/TranslationProvider.tsx
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/sidebar/header/actions/hooks/mockAppRoot.tsx
  apps/meteor/client/stories/contexts/TranslationContextMock.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/server/lib/i18n.ts
  package.json
  packages/i18n/babel.config.cjs
  packages/i18n/package.json
  packages/i18n/tsconfig.json
  packages/livechat/package.json
  packages/livechat/src/components/Calls/CallNotification.tsx
  packages/livechat/src/components/Calls/JoinCallButton.tsx
  packages/mock-providers/package.json
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/ui-client/package.json
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifiers.spec.tsx
  packages/ui-contexts/src/TranslationContext.ts
  packages/web-ui-registration/.babelrc.json
  packages/web-ui-registration/.storybook/logo.svg
  packages/web-ui-registration/.storybook/logo.svg.d.ts
  packages/web-ui-registration/.storybook/main.ts
  packages/web-ui-registration/.storybook/preview.tsx
  packages/web-ui-registration/package.json
  packages/web-ui-registration/src/ResetPassword/ResetPassword.stories.tsx
  packages/web-ui-registration/src/components/LoginSwitchLanguageFooter.stories.tsx
  packages/web-ui-registration/src/components/LoginSwitchLanguageFooter.tsx
  packages/web-ui-registration/tsconfig.build.json
  packages/web-ui-registration/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#30212 fix: Custom OAuth services can't be fully removed
  .changeset/fifty-cars-divide.md
  apps/meteor/app/lib/server/methods/removeOAuthService.ts
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage.tsx
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#30202 fix: new `overrideDestinationChannelEnabled` param in integrations' endpoints is required
  .changeset/chilled-phones-give.md
  apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts
  apps/meteor/tests/end-to-end/api/07-incoming-integrations.js
  packages/core-typings/src/IIntegration.ts
  packages/rest-typings/src/v1/integrations/IntegrationsCreateProps.ts
  packages/rest-typings/src/v1/integrations/IntegrationsUpdateProps.ts
Labels: stat: QA tested, squad: team-collab

#30194 fix: `default` field is not returned from the `setDefault` endpoint when setting to false
  .changeset/real-pets-visit.md
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  packages/core-typings/src/IRoom.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30244 regression: Crash in livechat with manual routing
  packages/livechat/src/routes/Chat/container.js
Labels: stat: needs QA

#30248 chore: Add missing loading state on `AdminInviteUsers`
  apps/meteor/client/views/admin/users/AdminInviteUsers.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/admin/users/hooks/useSmtpConfig.ts
  apps/meteor/client/views/admin/users/hooks/useSmtpQuery.ts
Labels: stat: ready to merge, stat: QA skipped

#30251 regression: add deps props for useDebouncedCallback for app stream
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/hooks/useAppSlashCommands.ts
  apps/meteor/client/hooks/useAppTranslations.ts
  apps/meteor/client/providers/AppsProvider.tsx
Labels: stat: needs QA

#30235 chore: Fix envvar name in patch notes
  .changeset/hip-hounds-ring.md
Labels: stat: QA skipped

#30223 chore: Reports dashboard E2E tests
  apps/meteor/client/lib/queryClient.ts
  apps/meteor/ee/client/components/dashboards/PeriodSelector.tsx
  apps/meteor/ee/client/omnichannel/reports/components/BarChart.tsx
  apps/meteor/ee/client/omnichannel/reports/components/ReportCard.tsx
  apps/meteor/ee/client/omnichannel/reports/hooks/useAgentsSection.tsx
  apps/meteor/ee/client/omnichannel/reports/hooks/useChannelsSection.tsx
  apps/meteor/ee/client/omnichannel/reports/hooks/useDepartmentsSection.tsx
  apps/meteor/ee/client/omnichannel/reports/hooks/useStatusSection.tsx
  apps/meteor/ee/client/omnichannel/reports/hooks/useTagsSection.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-reports.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-reports.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30197 fix: Message Menu is cut vertically if screen is too small
  .changeset/serious-shrimps-try.md
  apps/meteor/client/components/message/MessageToolboxHolder.tsx
  apps/meteor/client/components/message/toolbox/DesktopToolboxDropdown.tsx
  apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx
  apps/meteor/client/components/message/toolbox/MessageToolbox.tsx
  apps/meteor/client/components/message/toolbox/ToolboxDropdown.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped, squad: team-collab

#30253 regression(fuselage-ui-kit): remove `ui-kit` icons dependency
  packages/fuselage-ui-kit/src/blocks/CalloutBlock.tsx
Labels: stat: ready to merge, stat: QA skipped, squad: apps ecosystem

#30232 fix: importer filter not working
  .changeset/red-zebras-clap.md
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/importer/server/classes/ImporterBase.js
Labels: stat: ready to merge, stat: QA tested

#30233 test: Avoid flakiness in failed login attempts end-to-end tests
  apps/meteor/tests/end-to-end/api/31-failed-login-attempts.ts
Labels: stat: ready to merge, stat: QA skipped

#30257 chore: removed force click to prevent flaky test
  apps/meteor/tests/e2e/page-objects/omnichannel-reports.ts
Labels: stat: ready to merge, stat: QA skipped

#30203 chore: Improve form fields on `CreateChannelModal`
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/create-channel.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
Labels: stat: ready to merge, stat: QA skipped

#30214 chore: Add danger variant to apps action button menus
  .changeset/honest-glasses-roll.md
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/views/room/contexts/RoomToolboxContext.ts
  apps/meteor/client/views/room/providers/hooks/useAppsRoomActions.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, squad: apps ecosystem

#30273 fix: Prevent `RoomProvider.useEffect` from subscribing multiple times
  .changeset/forty-hotels-pretend.md
  apps/meteor/client/views/room/providers/RoomProvider.tsx
Labels: stat: needs QA, squad: omnichannel

#30196 fix: Remove options on `Chat Now` page
  packages/livechat/src/routes/Chat/component.js
Labels: stat: ready to merge, stat: QA tested

#30210 chore: add missing voip setting translation on pt-BR
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30271 regression: Webhook / bot message without link previews
  apps/meteor/app/oembed/server/server.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30275 regression: Thread badge click-animation
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/admin-flextab-users.ts
  apps/meteor/tests/e2e/user-invitations.spec.ts
  packages/ui-client/src/components/Header/HeaderToolbox/HeaderToolboxActionBadge.tsx
  yarn.lock
Labels: stat: QA skipped

#30278 test: enable http cache for tests
  .github/workflows/ci-test-e2e.yml
  apps/meteor/package.json
  apps/meteor/playwright.config.ts
  apps/meteor/playwright.prepare.mjs
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/homepage.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-priorities-sidebar.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
Labels: stat: needs QA

#30293 chore: Move a11y violation tests to Playwright
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.spec.tsx
  apps/meteor/client/views/account/omnichannel/OmnichannelPreferencesPage.spec.tsx
  apps/meteor/client/views/admin/mailer/MailerPage.spec.tsx
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.spec.tsx
  apps/meteor/package.json
  apps/meteor/tests/e2e/account-profile.spec.ts
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-current-chats.spec.ts
  apps/meteor/tests/e2e/settings-account-profile.spec.ts
  apps/meteor/tests/e2e/utils/test.ts
  yarn.lock
Labels: stat: needs QA

#30252 fix: linkedin oauth broken
  .changeset/odd-elephants-promise.md
  apps/meteor/app/lib/server/startup/oAuthServicesUpdate.js
  apps/meteor/packages/linkedin-oauth/linkedin-client.js
  apps/meteor/packages/linkedin-oauth/linkedin-server.js
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#30280 chore: Registration form a11y improvements
  apps/meteor/tests/e2e/register.spec.ts
  packages/ui-client/src/components/CustomFieldsForm.tsx
  packages/web-ui-registration/src/RegisterForm.tsx
Labels: stat: ready to merge, stat: QA skipped

#30291 fix: added debounce to units and custom fields search
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
  apps/meteor/ee/client/omnichannel/units/UnitsTable.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30285 chore: Increase cache time to 10s on `getUnits` function
  .changeset/three-birds-tickle.md
  apps/meteor/ee/app/livechat-enterprise/server/lib/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/getUnitsFromUserRoles.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30249 chore: prevent unneeded calls to EE settings service
  apps/meteor/server/modules/listeners/listeners.module.ts
Labels: stat: ready to merge, stat: QA skipped

#30292 fix: Selected options not being displayed for monitors and departments
  apps/meteor/client/views/hooks/useDepartmentsByUnitsList.ts
  apps/meteor/client/views/hooks/useMonitorsList.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Department.ts
  apps/meteor/ee/client/omnichannel/units/UnitEdit.js
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30302 test: codecov flags
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci-test-unit.yml
  .github/workflows/ci.yml
  codecov.yml
Labels: stat: ready to merge, stat: QA skipped

#30310 regression: Change UiKit buttons event handler
  packages/fuselage-ui-kit/src/elements/ButtonElement.tsx
  packages/fuselage-ui-kit/src/hooks/useUiKitState.ts
Labels: stat: ready to merge, stat: QA skipped

#30258 regression(deps): Bumping Fuselage breaks `uikit-playground`
  packages/uikit-playground/src/Payload/callout/index.ts
  yarn.lock
Labels: stat: QA skipped

#30206 test: Export PDF transcript
  apps/meteor/tests/e2e/omnichannel/omnichannel-send-pdf-transcript.spec.ts
  apps/meteor/tests/e2e/page-objects/home-omnichannel.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-transcript.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30303 fix: Managers allowed to make deactivated agent's available
  .changeset/breezy-bugs-jam.md
  apps/meteor/app/livechat/server/api/v1/agent.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30284 fix: agent role being removed upon user deactivation
  .changeset/seven-jobs-tickle.md
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/app/livechat/server/business-hour/Single.ts
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/server/models/raw/Users.js
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30277 fix: engagement dashboard not working
  .changeset/lucky-balloons-divide.md
  apps/meteor/app/statistics/server/lib/SAUMonitor.ts
Labels: stat: needs QA

#30265 fix: moment locale change
  .changeset/gold-moose-press.md
  apps/meteor/client/providers/TranslationProvider.tsx
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30141 fix: importers progress bar
  .changeset/importer-progress-bar.md
  apps/meteor/client/views/admin/import/ImportProgressPage.tsx
  apps/meteor/client/views/admin/import/PrepareImportPage.js
Labels: stat: ready to merge, stat: QA tested

#30328 chore: increase ts memory
  apps/meteor/package.json
Labels: stat: ready to merge, stat: QA skipped

#30072 fix: use agent's first response time to calculate visitor's abandonment
  .changeset/tough-candles-heal.md
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/setPredictedVisitorAbandonmentTime.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/server/services/omnichannel-voip/service.ts
  apps/meteor/tests/end-to-end/api/livechat/18-rooms-ee.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30329 chore: Only load sounds on use
  .changeset/four-parents-cheer.md
  apps/meteor/app/custom-sounds/client/lib/CustomSounds.ts
Labels: stat: ready to merge, stat: QA skipped

#30306 feat: Add `ChangePassword` field to Account/Security
  .changeset/yellow-buttons-agree.md
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
  apps/meteor/client/views/account/profile/getProfileInitialValues.ts
  apps/meteor/client/views/account/security/AccountSecurityPage.tsx
  apps/meteor/client/views/account/security/ChangePassword.tsx
  apps/meteor/client/views/account/security/useAllowPasswordChange.ts
  apps/meteor/tests/e2e/account-profile.spec.ts
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifier.tsx
Labels: stat: ready to merge, stat: QA skipped

#30321 fix: update type of message bridge's create method
  .changeset/loud-bees-smoke.md
  apps/meteor/app/apps/server/bridges/messages.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#30332 regression: `AccountProfileForm` not reseting
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
Labels: stat: ready to merge, stat: QA skipped

#30337 chore: `LoginForm` a11y improvements
  apps/meteor/tests/e2e/login.spec.ts
  apps/meteor/tests/e2e/register.spec.ts
  packages/web-ui-registration/src/LoginForm.tsx
  packages/web-ui-registration/src/RegisterForm.tsx
  packages/web-ui-registration/src/RegisterTemplate.tsx
  packages/web-ui-registration/src/components/RegisterTitle.tsx
  packages/web-ui-registration/src/template/HorizontalTemplate.tsx
Labels: stat: needs QA

#30294 Release 6.3.4
  .changeset/bump-patch-1693944810152.md
  .changeset/forty-hotels-pretend.md
  .changeset/seven-jobs-tickle.md
  .changeset/three-birds-tickle.md
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/app/livechat/server/business-hour/Single.ts
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/client/views/hooks/useDepartmentsByUnitsList.ts
  apps/meteor/client/views/hooks/useMonitorsList.ts
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Department.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/getUnitsFromUserRoles.ts
  apps/meteor/ee/client/omnichannel/units/UnitEdit.js
  apps/meteor/ee/client/omnichannel/units/UnitsTable.tsx
  apps/meteor/server/models/raw/Users.js
  apps/meteor/server/modules/listeners/listeners.module.ts
  packages/model-typings/src/models/IUsersModel.ts
  yarn.lock
Labels: stat: needs QA

#30335 chore: Remove `Card` deprecation warning
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceCards.tsx
  apps/meteor/client/views/admin/info/DeploymentCard.tsx
  apps/meteor/client/views/admin/info/LicenseCard.tsx
  apps/meteor/client/views/admin/info/UsageCard.tsx
  apps/meteor/client/views/admin/settings/SettingsGroupCard.tsx
  apps/meteor/client/views/home/cards/AddUsersCard.tsx
  apps/meteor/client/views/home/cards/CreateChannelsCard.tsx
  apps/meteor/client/views/home/cards/CustomContentCard.tsx
  apps/meteor/client/views/home/cards/DesktopAppsCard.tsx
  apps/meteor/client/views/home/cards/DocumentationCard.tsx
  apps/meteor/client/views/home/cards/JoinRoomsCard.tsx
  apps/meteor/client/views/home/cards/MobileAppsCard.tsx
  apps/meteor/ee/client/omnichannel/reports/components/ReportCard.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardCard.tsx
  apps/meteor/ee/client/views/admin/info/SeatsCard.tsx
  apps/meteor/package.json
  packages/ui-client/src/components/Card/Card.stories.tsx
  packages/ui-client/src/components/Card/index.ts
  packages/ui-client/src/components/index.ts
Labels: stat: ready to merge, stat: QA skipped

#30313 chore: remove istanbul from prod env
  .github/actions/build-docker/action.yml
  .github/actions/meteor-build/action.yml
  .github/workflows/ci.yml
  apps/meteor/.babelrc
Labels: stat: needs QA

#30343 test: More Business Hour tests surrounding user activation/deactivation
  apps/meteor/app/lib/server/functions/getFullUserData.ts
  apps/meteor/tests/data/users.helper.js
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30289 chore: add subscription metrics to ddp-streamer
  ee/apps/ddp-streamer/src/DDPStreamer.ts
  ee/apps/ddp-streamer/src/Server.ts
  packages/core-services/src/types/IBroker.ts
Labels: stat: needs QA

#30175 chore: move team mentions to ce
  apps/meteor/app/mentions/server/getMentionedTeamMembers.ts
  apps/meteor/app/mentions/server/index.ts
  apps/meteor/app/mentions/server/server.ts
  apps/meteor/ee/app/license/server/bundles.ts
  apps/meteor/ee/app/teams-mention/server/EEMentionQueries.js
  apps/meteor/ee/app/teams-mention/server/EESpotlight.js
  apps/meteor/ee/app/teams-mention/server/index.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/server/lib/spotlight.js
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30354 fix: Consider only sessions from last few days for SAU/MAU
  .changeset/strong-laws-pump.md
  apps/meteor/app/statistics/server/lib/SAUMonitor.ts
  apps/meteor/server/models/raw/Sessions.ts
  packages/model-typings/src/models/ISessionsModel.ts
Labels: stat: QA skipped

#30357 chore: bump fuselage
  yarn.lock
Labels: stat: needs QA

#30315 regression: Rooms page filters faulty behavior
  apps/meteor/client/views/admin/rooms/RoomRow.tsx
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/client/views/admin/rooms/RoomsTableFilters.tsx
  apps/meteor/client/views/admin/rooms/useFilteredTypeRooms.tsx
  apps/meteor/client/views/admin/rooms/useFilteredVisibilityRooms.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: type: regression, stat: needs QA, squad: Workspace Management

#30156 fix: missing params on `updateOwnBasicInfo` endpoint
  .changeset/wise-walls-tan.md
  apps/meteor/app/api/server/v1/users.ts
  packages/rest-typings/src/v1/users.ts
  packages/rest-typings/src/v1/users/UsersUpdateOwnBasicInfoParamsPOST.ts
Labels: stat: needs QA

#30349 test: Changed Home Page spec titles
  apps/meteor/tests/e2e/homepage.spec.ts
Labels: stat: needs QA

#30356 fix: apps name misalignment in case of no icons
  .changeset/young-trains-glow.md
  apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx
Labels: stat: ready to merge, stat: QA tested

#30314 refactor(client): async loading
  apps/meteor/client/lib/2fa/process2faReturn.ts
  apps/meteor/client/main.ts
  apps/meteor/client/polyfills/index.ts
  apps/meteor/client/polyfills/objectFromEntries.ts
  apps/meteor/client/providers/RouterProvider.tsx
Labels: stat: needs QA

#30350 regression: Reports by-department showing null when department no longer exists
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30365 fix: selected departments not being displayed due to pagination
  .changeset/slimy-cheetahs-heal.md
  apps/meteor/client/components/Omnichannel/hooks/useDepartmentsList.ts
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithData.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentForwarding.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30353 fix: Disabled call to EE tags endpoint when on CE license
  .changeset/honest-mirrors-sit.md
  apps/meteor/client/components/Omnichannel/hooks/useLivechatTags.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30359 Release 6.3.5
  .changeset/bump-patch-1694524270831.md
  .changeset/fuzzy-points-care.md
  .changeset/slimy-cheetahs-heal.md
  .changeset/strong-laws-pump.md
  apps/meteor/app/statistics/server/lib/SAUMonitor.ts
  apps/meteor/client/components/Omnichannel/hooks/useDepartmentsList.ts
  apps/meteor/client/views/marketplace/AppInstallPage.js
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithData.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentForwarding.tsx
  apps/meteor/server/models/raw/Sessions.ts
  packages/model-typings/src/models/ISessionsModel.ts
  yarn.lock
Labels: stat: needs QA

#30355 chore: Revert "fix: update type of message bridge's create method"
  .changeset/loud-bees-smoke.md
  apps/meteor/app/apps/server/bridges/messages.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#30372 feat: Add flag to disable teams mention via troubleshoot
  .changeset/nine-bottles-press.md
  apps/meteor/app/mentions/server/getMentionedTeamMembers.ts
  apps/meteor/app/mentions/server/server.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/lib/spotlight.js
  apps/meteor/server/settings/troubleshoot.ts
Labels: stat: needs QA

#30270 refactor: password policies
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/lib/generatePassword.ts
  apps/meteor/app/lib/server/lib/passwordPolicy.js
  apps/meteor/app/lib/server/lib/passwordPolicy.ts
  apps/meteor/package.json
  apps/meteor/server/methods/getPasswordPolicy.ts
  apps/meteor/server/settings/accounts.ts
  apps/meteor/tests/unit/app/lib/server.tests.js
  ee/apps/ddp-streamer/Dockerfile
  packages/password-policies/.eslintrc.json
  packages/password-policies/jest.config.ts
  packages/password-policies/package.json
  packages/password-policies/src/PasswordPolicyClass.ts
  packages/password-policies/src/PasswordPolicyError.ts
  packages/password-policies/src/index.ts
  packages/password-policies/tests/passwordPolicyClass.test.ts
  packages/password-policies/tsconfig.json
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifier.stories.tsx
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifier.tsx
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifiers.spec.tsx
  packages/ui-client/src/hooks/useValidatePassword.spec.ts
  packages/ui-client/src/hooks/useValidatePassword.ts
  packages/ui-contexts/package.json
  packages/ui-contexts/src/hooks/usePasswordPolicy.ts
  packages/ui-contexts/src/hooks/useVerifyPassword.ts
  packages/ui-contexts/src/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#30387 chore: Add commit subject to info panel
  apps/meteor/client/views/admin/info/DeploymentCard.tsx
Labels: stat: ready to merge, stat: QA skipped

#30368 feat: Automate omnichannel verification process
  apps/meteor/app/livechat/lib/messageTypes.ts
  apps/meteor/app/livechat/server/hooks/automateVerificationProcess.tsx
  apps/meteor/app/livechat/server/hooks/verificationCheck.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/omnichannel-verification/service.ts
  apps/meteor/server/settings/omnichannel.ts
  packages/core-services/src/types/IOmnichannelVerification.ts
  packages/core-typings/src/omnichannel/routing.ts
  packages/livechat/src/helpers/normalizeTransferHistoryMessage.ts
  packages/livechat/src/i18n/en.json
Labels: stat: needs QA

#30254 refactor: FilesDropTarget -> TS
  packages/livechat/src/components/FilesDropTarget/index.js
  packages/livechat/src/components/FilesDropTarget/index.tsx
  packages/livechat/src/components/FilesDropTarget/stories.tsx
  packages/livechat/src/routes/Chat/component.js
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30386 regression: Move queue-timeout setting to CE and remove dependency on waiting queue
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
  apps/meteor/server/services/omnichannel/queue.ts
  apps/meteor/server/settings/omnichannel.ts
Labels: stat: needs QA, squad: omnichannel

#30361 regression: Fix rooms table not showing teams
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
Labels: type: regression, stat: needs QA, squad: Workspace Management

#30286 test: tests for muting and unmuting
  apps/meteor/tests/end-to-end/api/24-methods.js
Labels: stat: ready to merge, automerge, stat: QA skipped, squad: team-collab

#30399 regression: Login page callout messages
  packages/web-ui-registration/src/LoginForm.tsx
Labels: type: regression, stat: ready to merge, stat: QA skipped, squad: Workspace Management

#30396 Release 6.3.6
  .changeset/bump-patch-1694715003701.md
  .changeset/lucky-balloons-divide.md
  apps/meteor/app/statistics/server/lib/SAUMonitor.ts
  yarn.lock
Labels: stat: needs QA

#30279 refactor: Implement functional code for the 'useFilteredApps' hook
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/hooks/useFilteredApps.ts
Labels: stat: ready to merge, stat: QA tested

#30371 test: create non private team and readonly team
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
  apps/meteor/tests/e2e/page-objects/home-team.ts
  apps/meteor/tests/e2e/team-management.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#30402 fix: increase cron job check delay to 1 min
  .changeset/three-ants-give.md
  packages/cron/src/index.ts
Labels: stat: needs QA

#30385 chore: color palette changes
  ee/packages/ui-theming/src/PaletteStyleTag.tsx
  ee/packages/ui-theming/src/paletteDark.ts
Labels: stat: ready to merge, stat: QA skipped

#30400 regression: fix Issues with livechat queue
  packages/livechat/src/lib/api.js
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30274 chore: Webhooks page refactor
  apps/meteor/app/livechat/server/api/v1/webhooks.ts
  apps/meteor/client/views/omnichannel/webhooks/WebhooksPage.js
  apps/meteor/client/views/omnichannel/webhooks/WebhooksPage.tsx
  apps/meteor/client/views/omnichannel/webhooks/WebhooksPageContainer.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested

#30424 chore: bump fuselage packages
  apps/meteor/client/components/RoomAutoCompleteMultiple/RoomAutoCompleteMultiple.tsx
  apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useGroupingListItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useSortModeItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useViewModeItems.tsx
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: needs QA

#30407 regression: Show correct date for last day time
  .changeset/heavy-zebras-wonder.md
  apps/meteor/client/hooks/useTimeAgo.ts
Labels: stat: ready to merge, stat: QA tested

#30429 chore: remove Troubleshoot options
  apps/meteor/app/cloud/server/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/cron/statistics.ts
  apps/meteor/server/settings/troubleshoot.ts
Labels: stat: ready to merge, stat: QA skipped

#30430 chore: remove connectToCloud option
  apps/meteor/app/cloud/server/functions/checkUserHasCloudLogin.ts
  apps/meteor/app/cloud/server/functions/connectWorkspace.ts
  apps/meteor/app/cloud/server/functions/disconnectWorkspace.ts
  apps/meteor/app/cloud/server/functions/getUserCloudAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceKey.ts
  apps/meteor/app/cloud/server/functions/retrieveRegistrationStatus.ts
  apps/meteor/app/cloud/server/functions/startRegisterWorkspace.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace.ts
  apps/meteor/app/cloud/server/functions/userLogout.ts
  apps/meteor/app/cloud/server/methods.ts
  apps/meteor/client/startup/startup.ts
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx
  apps/meteor/client/views/admin/cloud/modals/DisconnectWorkspaceModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisteredWorkspaceModal.tsx
  packages/core-typings/src/ICloud.ts
Labels: stat: ready to merge, stat: QA skipped

#30438 regression(Apps): Apps translations overriding core translations
  apps/meteor/client/hooks/useAppTranslations.ts
Labels: stat: needs QA

#30388 regression: CSS adjustments in `ActionManagerBusyState`
  apps/meteor/client/components/ActionManagerBusyState.tsx
Labels: stat: QA skipped

#30391 regression: `$group` by `alias + type` instead of full `$source` object on reports page
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
Labels: stat: needs QA, squad: omnichannel

#30428 regression: custom fields not showing in current chats
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
Labels: stat: needs QA

#30432 regression: close button not working on contact history
  apps/meteor/client/views/omnichannel/contactHistory/ContactHistory.tsx
Labels: stat: needs QA

#30436 ci: Add step to notify external services about a new release after Docker image publish
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA skipped

#30319 fix: Disables `GenericMenu` without any sections or items
  .changeset/strange-papayas-yell.md
  apps/meteor/client/components/GenericMenu/GenericMenu.tsx
Labels: stat: ready to merge, stat: QA skipped

#30440 chore: Assertion accuracy on registration test
  apps/meteor/tests/e2e/page-objects/auth.ts
  apps/meteor/tests/e2e/page-objects/utils.ts
  apps/meteor/tests/e2e/register.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#29989 chore: update meteor 2.13.0
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/release
  apps/meteor/.meteor/versions
Labels: stat: ready to merge, stat: QA skipped

#30447 chore: cache incremental ts check
  .github/workflows/ci-code-check.yml
  apps/meteor/.gitignore
  apps/meteor/tsconfig.typecheck.json
Labels: stat: needs QA

#30449 ci: patch mongo type definitions
  .yarn/patches/mongodb-npm-4.17.1-a2fe811ff1.patch
  apps/meteor/tsconfig.typecheck.json
  package.json
Labels: stat: needs QA

#30450 chore: bump mongo deps
  apps/meteor/ee/server/services/Dockerfile
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/account-service/Dockerfile
  ee/apps/account-service/package.json
  ee/apps/authorization-service/Dockerfile
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/Dockerfile
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/Dockerfile
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/Dockerfile
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/Dockerfile
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/Dockerfile
  ee/apps/stream-hub-service/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/presence/package.json
  package.json
  packages/agenda/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/cron/package.json
  packages/instance-status/package.json
  packages/model-typings/package.json
  packages/rest-typings/package.json
  packages/ui-contexts/package.json
  yarn.lock
Labels: stat: needs QA

#30443 regression: `LoginForm` validation
  packages/web-ui-registration/src/LoginForm.tsx
Labels: stat: ready to merge, stat: QA tested

#30383 fix: Custom translations do not work
  .changeset/cuddly-donkeys-remember.md
  apps/meteor/client/providers/TranslationProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#30445 chore: add tooltip to mentions
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/gazzodown/src/elements/PlainSpan.tsx
  packages/gazzodown/src/mentions/ChannelMentionElement.tsx
  packages/gazzodown/src/mentions/UserMentionElement.tsx
  packages/password-policies/tsconfig.json
Labels: stat: ready to merge, stat: QA skipped

#30456 regression: Videoconf message actions
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/ee/client/startup/readReceipt.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30452 fix: Message disappears from room after deletion even if "Show Deleted Status" is enabled
  .changeset/kind-books-love.md
  apps/meteor/client/lib/chats/data.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30472 regression: multiselect
  apps/meteor/client/views/admin/rooms/RoomsTableFilters.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomList.tsx
Labels: stat: ready to merge, stat: QA tested

#30241 chore: Move bad words filter callback to service
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/discussion/server/hooks/joinDiscussionOnMessage.ts
  apps/meteor/app/lib/server/functions/notifications/index.ts
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/index.ts
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
  apps/meteor/app/lib/server/methods/filterBadWords.ts
  apps/meteor/app/lib/server/methods/joinRoom.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/slashcommands-join/server/server.ts
  apps/meteor/server/lib/rooms/roomTypes/direct.ts
  apps/meteor/server/services/messages/hooks/badwords.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/server/services/room/service.ts
  packages/core-services/src/types/IMessageService.ts
  packages/core-services/src/types/IRoomService.ts
Labels: stat: ready to merge, stat: QA skipped

#30476 chore: `ResetPasswordForm` a11y improvements
  packages/web-ui-registration/src/RegisterForm.tsx
  packages/web-ui-registration/src/ResetPasswordForm.tsx
  packages/web-ui-registration/src/hooks/useSendForgotPassword.ts
Labels: stat: ready to merge, stat: QA skipped

#30479 chore: `ResetPasswordPage` a11y improvements
  apps/meteor/tests/e2e/forgot-password.spec.ts
  apps/meteor/tests/e2e/page-objects/auth.ts
  apps/meteor/tests/e2e/reset-password.spec.ts
  packages/web-ui-registration/src/RegisterForm.tsx
  packages/web-ui-registration/src/ResetPassword/ResetPasswordPage.tsx
Labels: stat: ready to merge, stat: QA skipped

#30394 regression: Reports button visible when downgrading from EE to CE
  apps/meteor/client/views/omnichannel/sidebarItems.ts
  apps/meteor/ee/app/livechat-enterprise/client/views/livechatSideNavItems.ts
  apps/meteor/ee/client/omnichannel/reports/ReportsPage.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30470 fix: selected options not being displayed on `PaginatedMultiSelect`
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx
  apps/meteor/ee/client/hooks/useTagsList.ts
  apps/meteor/ee/client/omnichannel/tags/AutoCompleteTagsMultiple.js
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30390 fix: Microsoft autotranslate not working
  apps/meteor/app/autotranslate/server/msTranslate.ts
Labels: stat: ready to merge, stat: QA tested

#30484 regression: livechat uiKit actions not working
  packages/livechat/src/lib/random.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30489 fix: Lazy loading not working on 'Forward to department' field
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30446 fix: do not broadcast events from the local node to the local service (duplicated event)
  .changeset/brave-snakes-scream.md
  apps/meteor/ee/server/local-services/instance/service.ts
Labels: stat: needs QA

#30229 feat: use isolated-vm to run integration scripts
  .changeset/thirty-pumpkins-fix.md
  apps/meteor/.docker/Dockerfile.alpine
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/app/integrations/server/lib/ScriptEngine.ts
  apps/meteor/app/integrations/server/lib/definition.ts
  apps/meteor/app/integrations/server/lib/isolated-vm/buildSandbox.ts
  apps/meteor/app/integrations/server/lib/isolated-vm/getCompatibilityScript.ts
  apps/meteor/app/integrations/server/lib/isolated-vm/isolated-vm.ts
  apps/meteor/app/integrations/server/lib/triggerHandler.js
  apps/meteor/app/integrations/server/lib/updateHistory.ts
  apps/meteor/app/integrations/server/lib/validateOutgoingIntegration.ts
  apps/meteor/app/integrations/server/lib/validateScriptEngine.ts
  apps/meteor/app/integrations/server/lib/vm2/buildSandbox.ts
  apps/meteor/app/integrations/server/lib/vm2/vm2.ts
  apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/outgoing/addOutgoingIntegration.ts
  apps/meteor/app/integrations/server/methods/outgoing/updateOutgoingIntegration.ts
  apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js
  apps/meteor/client/views/admin/integrations/OutgoiongWebhookForm.js
  apps/meteor/client/views/admin/integrations/edit/EditIncomingWebhook.js
  apps/meteor/client/views/admin/integrations/edit/EditOutgoingWebhook.js
  apps/meteor/client/views/admin/integrations/new/NewIncomingWebhook.js
  apps/meteor/client/views/admin/integrations/new/NewOutgoingWebhook.js
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/IIntegration.ts
  packages/core-typings/src/IIntegrationHistory.ts
  packages/rest-typings/src/v1/integrations/IntegrationsCreateProps.ts
  packages/tools/src/index.ts
  packages/tools/src/wrapExceptions.ts
  yarn.lock
Labels: stat: QA tested

#30457 Release 6.3.8
  .changeset/bump-patch-1695309507614.md
  .github/workflows/ci.yml
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/release
  apps/meteor/.meteor/versions
  yarn.lock
Labels: stat: needs QA

#30462 chore: Changing some key translations - Setup Wizard
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#30373 feat: New records page analytics tab
  .changeset/fluffy-monkeys-sing.md
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/admin/viewLogs/AnalyticsReports.tsx
  apps/meteor/client/views/admin/viewLogs/ViewLogsPage.tsx
  apps/meteor/client/views/admin/viewLogs/hooks/useAnalyticsObject.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#30393 fix: RTL lang crashes Moderation Console
  apps/meteor/client/views/admin/moderation/helpers/DateRangePicker.tsx
Labels: stat: ready to merge, stat: QA tested

#30502 chore: move Omnichannel toolbox section from sidebar room list
  apps/meteor/client/sidebar/RoomList/RoomListRow.tsx
  apps/meteor/client/sidebar/Sidebar.tsx
  apps/meteor/client/sidebar/hooks/useRoomList.ts
  apps/meteor/client/sidebar/sections/OmnichannelSection.tsx
Labels: stat: ready to merge, stat: QA skipped

#30504 chore: Add mocked license
  apps/meteor/ee/app/license/server/settings.ts
  apps/meteor/ee/app/license/server/startup.ts
  apps/meteor/ee/server/lib/EnterpriseCheck.ts
  ee/packages/license/__tests__/MockedLicenseBuilder.ts
  ee/packages/license/__tests__/emitter.spec.ts
  ee/packages/license/__tests__/setLicense.spec.ts
  ee/packages/license/babel.config.json
  ee/packages/license/package.json
  ee/packages/license/src/events/deprecated.ts
  ee/packages/license/src/events/emitter.ts
  ee/packages/license/src/index.ts
  ee/packages/license/src/license.spec.ts
  ee/packages/license/src/license.ts
  ee/packages/license/src/token.ts
  ee/packages/license/src/v2/convertToV3.ts
  ee/packages/license/src/validation/getCurrentValueForLicenseLimit.ts
  ee/packages/license/src/validation/runValidation.spec.ts
  ee/packages/license/src/validation/runValidation.ts
  ee/packages/license/src/validation/validateFormat.ts
  ee/packages/license/src/validation/validateLicensePeriods.ts
  packages/jwt/src/index.ts
  yarn.lock
Labels: stat: needs QA

#29776 ci: Security/GitHub jira integration
  .github/workflows/vulnerabilities-jira-integration.yml
Labels: stat: ready to merge, stat: QA skipped

#30336 chore: Prevent call license and registration status endpoints when not enough permission
  apps/meteor/client/hooks/useLicense.ts
  apps/meteor/client/hooks/useRegistrationStatus.ts
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.spec.tsx
Labels: stat: QA tested

#30370 feat: Auto-enable autotranslate
  .changeset/large-pandas-beam.md
  apps/meteor/app/lib/server/functions/addUserToDefaultChannels.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/lib/getSubscriptionAutotranslateDefaultConfig.ts
  apps/meteor/server/methods/addAllUserToRoom.ts
  apps/meteor/server/settings/message.ts
  apps/meteor/tests/end-to-end/api/00-autotranslate.js
Labels: stat: QA tested

#30178 feat: add supported versions + minimum clients versions to the info endpoint
  apps/meteor/app/api/server/default/info.ts
  apps/meteor/app/api/server/lib/getServerInfo.spec.ts
  apps/meteor/app/api/server/lib/getServerInfo.ts
  apps/meteor/app/cloud/server/functions/getUserCloudAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts
  apps/meteor/app/cloud/server/functions/reconnectWorkspace.ts
  apps/meteor/app/cloud/server/functions/startRegisterWorkspace.ts
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsChooseLatest.spec.ts
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsChooseLatest.ts
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/syncCloudData.ts
  apps/meteor/app/cloud/server/methods.ts
  apps/meteor/client/definitions/info.d.ts
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-version/plugin/compile-version.js
  apps/meteor/server/settings/setup-wizard.ts
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  ee/apps/account-service/Dockerfile
  ee/apps/authorization-service/Dockerfile
  ee/apps/ddp-streamer/Dockerfile
  ee/apps/omnichannel-transcript/Dockerfile
  ee/apps/presence-service/Dockerfile
  ee/apps/queue-worker/Dockerfile
  ee/apps/stream-hub-service/Dockerfile
  ee/packages/license/package.json
  ee/packages/license/src/definition/ILicenseV3.ts
  ee/packages/license/src/index.ts
  packages/rest-typings/src/default/index.ts
  packages/server-cloud-communication/.eslintrc.json
  packages/server-cloud-communication/package.json
  packages/server-cloud-communication/src/definitions/index.ts
  packages/server-cloud-communication/src/index.ts
  packages/server-cloud-communication/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#30421 chore: Deprecate un-used meteor method for omnichannel analytics
  .changeset/thirty-jokes-compete.md
  apps/meteor/app/livechat/server/methods/getAgentOverviewData.ts
  apps/meteor/app/livechat/server/methods/getAnalyticsOverviewData.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30526 fix: Monitors now able to forward a chat without taking it first
  .changeset/old-colts-wonder.md
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#30322 refactor: Omni logs
  apps/meteor/app/api/server/v1/voip/omnichannel.ts
  apps/meteor/app/livechat/server/business-hour/BusinessHourManager.ts
  apps/meteor/app/livechat/server/business-hour/Helper.ts
  apps/meteor/app/livechat/server/business-hour/Single.ts
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/app/livechat/server/lib/Analytics.js
  apps/meteor/app/livechat/server/lib/Departments.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/livechat/server/sendMessageBySMS.ts
  apps/meteor/app/livechat/server/startup.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterForwardChatToDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterInquiryQueued.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterOnHold.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterOnHoldChatResumed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterRemoveDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterReturnRoomAsInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applyDepartmentRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applyRoomRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applySimultaneousChatsRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeForwardRoomToDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onAgentAssignmentFailed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCloseLivechat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadForwardDepartmentRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onSaveVisitorInfo.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoCloseOnHoldScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/services/omnichannel.internalService.ts
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
  apps/meteor/server/services/omnichannel-voip/service.ts
  apps/meteor/server/services/omnichannel/queue.ts
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30401 chore: refactor cloud sync
  apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
  apps/meteor/app/cloud/server/functions/connectWorkspace.ts
  apps/meteor/app/cloud/server/functions/finishOAuthAuthorization.ts
  apps/meteor/app/cloud/server/functions/getConfirmationPoll.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts
  apps/meteor/app/cloud/server/functions/registerPreIntentWorkspaceWizard.ts
  apps/meteor/app/cloud/server/functions/startRegisterWorkspace.ts
  apps/meteor/app/cloud/server/functions/startRegisterWorkspaceSetupWizard.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/syncCloudData.ts
  apps/meteor/app/cloud/server/functions/userLogout.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/lib/errors/CloudWorkspaceAccessError.ts
  apps/meteor/lib/errors/CloudWorkspaceConnectionError.ts
  apps/meteor/lib/errors/CloudWorkspaceError.ts
  apps/meteor/lib/errors/CloudWorkspaceLicenseError.ts
  apps/meteor/lib/errors/CloudWorkspaceRegistrationError.ts
  apps/meteor/package.json
  apps/meteor/server/models/CloudAnnouncements.ts
  apps/meteor/server/models/raw/CloudAnnouncements.ts
  apps/meteor/server/models/startup.ts
  apps/meteor/server/services/banner/service.ts
  package.json
  packages/core-services/src/types/IBannerService.ts
  packages/core-typings/.eslintrc.json
  packages/core-typings/package.json
  packages/core-typings/src/IStats.ts
  packages/core-typings/src/cloud/Announcement.ts
  packages/core-typings/src/cloud/NpsSurveyAnnouncement.ts
  packages/core-typings/src/cloud/WorkspaceLicensePayload.ts
  packages/core-typings/src/cloud/WorkspaceSyncPayload.ts
  packages/core-typings/src/cloud/index.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/IBannersModel.ts
  packages/model-typings/src/models/ICloudAnnouncementsModel.ts
  packages/models/src/index.ts
  packages/rest-typings/src/v1/autotranslate/AutotranslateSaveSettingsParamsPOST.ts
  packages/rest-typings/src/v1/federation/FederationVerifyMatrixIdProps.ts
  packages/rest-typings/src/v1/moderation/ReportHistoryProps.ts
  packages/rest-typings/src/v1/omnichannel.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped
