Repository RocketChat/Rocket.Chat, pull requests merged in 2023-06, with the labels that each got.

#27955 docs: new README file
  README.md
Labels: stat: ready to merge, stat: QA tested

#29401 fix: Importer crashes when sending the "active status" e-mail notification to users
  .changeset/chatty-numbers-approve.md
  apps/meteor/app/importer/server/classes/ImporterBase.js
  apps/meteor/app/lib/server/functions/setUserActiveStatus.ts
  apps/meteor/server/models/raw/Users.js
Labels: stat: ready to merge, stat: QA tested

#29426 chore(meteor): Update mention style
  .changeset/warm-scissors-itch.md
  packages/gazzodown/src/mentions/ChannelMentionElement.tsx
  packages/gazzodown/src/mentions/UserMentionElement.tsx
  yarn.lock
Labels: stat: needs QA

#29424 regression: Update `LoadingIndicator` colors
  apps/meteor/app/theme/client/imports/components/loading.css
  apps/meteor/app/theme/client/imports/general/base.css
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/variables.css
  apps/meteor/app/theme/client/main.css
  apps/meteor/app/ui-master/server/index.js
  apps/meteor/client/components/LoadingIndicator.tsx
Labels: stat: ready to merge, stat: QA skipped

#29428 refactor: `Table` on Integrations Page
  apps/meteor/client/views/admin/integrations/FilterByTypeAndText.js
  apps/meteor/client/views/admin/integrations/IntegrationRow.js
  apps/meteor/client/views/admin/integrations/IntegrationRow.tsx
  apps/meteor/client/views/admin/integrations/IntegrationsTable.js
  apps/meteor/client/views/admin/integrations/IntegrationsTable.tsx
Labels: stat: ready to merge, stat: QA skipped

#29430 chore(ddp-client): freeze data emitted by the sdk
  packages/ddp-client/src/MinimalDDPClient.ts
Labels: stat: needs QA

#29203 feat: access-marketplace permission
  .changeset/curvy-hounds-sniff.md
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/client/components/AdministrationList/AdministrationList.spec.tsx
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/client/views/marketplace/AppsRoute.tsx
  apps/meteor/client/views/marketplace/MarketplaceRouter.tsx
  apps/meteor/client/views/marketplace/sidebarItems.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v297.ts
  apps/meteor/tests/unit/client/sidebar/header/actions/Administration.spec.tsx
Labels: stat: ready to merge, stat: QA tested

#29421 fix: Import progress page stuck at 0%
  .changeset/quiet-bottles-fry.md
  apps/meteor/client/views/admin/import/ImportProgressPage.tsx
Labels: stat: ready to merge, stat: QA tested

#29373 feat: add support for `MONOLITH_TRANSPORTER` env var
  .changeset/mean-guests-love.md
  apps/meteor/ee/server/local-services/instance/getTransporter.ts
  apps/meteor/ee/server/local-services/instance/service.ts
  apps/meteor/ee/tests/unit/apps/meteor/ee/server/local-services/instance/getTransporter.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#29320 chore: `ComposerBoxPopup` Items alignment
  apps/meteor/app/ui-message/client/popup/ComposerBoxPopup.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopup/ComposerBoxPopupSlashCommand.tsx
  apps/meteor/app/ui-message/client/popup/components/composerBoxPopup/ComposerBoxPopupUser.tsx
  apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts
Labels: stat: ready to merge, stat: QA skipped

#29441 regression: `Contextualbar` size
  apps/meteor/client/providers/LayoutProvider.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29189 fix: `queuedForUser` endpoint not filtering by status
  .changeset/honest-coins-bow.md
  apps/meteor/app/livechat/server/api/lib/inquiries.ts
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29408 regression: emojiPicker position
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPickerDesktopDropdown.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPickerDropDown.tsx
Labels: stat: needs QA

#29405 Release 6.2.3
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/importer/server/classes/ImporterBase.js
  apps/meteor/app/lib/server/functions/setUserActiveStatus.ts
  apps/meteor/app/livechat/server/api/lib/inquiries.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/otr/lib/OtrRoomState.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/client/views/admin/import/ImportProgressPage.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
  apps/meteor/client/views/room/providers/ToolboxProvider.tsx
  apps/meteor/ee/server/local-services/instance/getTransporter.ts
  apps/meteor/ee/server/local-services/instance/service.ts
  apps/meteor/ee/tests/unit/apps/meteor/ee/server/local-services/instance/getTransporter.spec.ts
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/server/models/raw/Users.js
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts
  package.json
Labels: stat: needs QA

#29449 fix: Saving Business hour throws an alert
  .changeset/modern-terms-jump.md
  packages/agenda/src/Agenda.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29378 fix: check for $addToSet to be not empty before passing update params
  .changeset/violet-beans-breathe.md
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/server/models/raw/LivechatVisitors.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29470 chore: `CurrentChats` empty state
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
Labels: stat: ready to merge, stat: QA skipped

#29335 fix: Room history scroll position
  .changeset/pretty-dots-leave.md
  apps/meteor/client/views/room/components/body/RoomBody.tsx
  apps/meteor/client/views/room/components/body/hooks/useRestoreScrollPosition.ts
Labels: stat: ready to merge, stat: QA tested

#29476 chore: `Managers` empty state
  apps/meteor/client/views/omnichannel/managers/AddManager.tsx
  apps/meteor/client/views/omnichannel/managers/ManagersRoute.tsx
  apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
Labels: stat: ready to merge, stat: QA skipped

#29098 chore: use new Livechat SDK Implementation
  .changeset/early-turtles-report.md
  packages/api-client/src/RestClientInterface.ts
  packages/api-client/src/index.ts
  packages/ddp-client/__tests__/Connection.spec.ts
  packages/ddp-client/__tests__/DDPSDK.spec.ts
  packages/ddp-client/__tests__/helpers/index.ts
  packages/ddp-client/src/Connection.ts
  packages/ddp-client/src/DDPSDK.ts
  packages/ddp-client/src/index.ts
  packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/ddp-client/src/livechat/types/LivechatSDK.ts
  packages/livechat/package.json
  packages/livechat/src/api.ts
  packages/livechat/src/components/Calls/CallIFrame.js
  packages/livechat/src/components/Calls/CallNotification.js
  packages/livechat/src/components/Calls/JoinCallButton.js
  packages/livechat/src/components/helpers.js
  packages/livechat/src/lib/connection.js
  packages/livechat/src/lib/customFields.js
  packages/livechat/src/lib/hooks.js
  packages/livechat/src/lib/room.js
  packages/livechat/src/lib/uiKit.js
  packages/livechat/src/routes/Chat/container.js
  packages/livechat/src/routes/Register/container.js
  packages/livechat/src/routes/SwitchDepartment/container.js
  packages/rest-typings/src/v1/omnichannel.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29475 chore: convert metrics to ts
  apps/meteor/app/metrics/server/lib/metrics.js
  apps/meteor/app/metrics/server/lib/metrics.ts
Labels: stat: ready to merge, stat: QA skipped

#29478 chore: `Agents` empty state
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoActions.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTab.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AddAgent.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTableRow.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/RemoveAgentButton.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/index.ts
  apps/meteor/client/views/omnichannel/agents/hooks/useAgentsQuery.ts
Labels: stat: ready to merge, stat: QA skipped

#29416 fix: Imported messages are not displayed
  .changeset/slow-maps-swim.md
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/importer-slack/server/importer.js
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/insertMessage.ts
  apps/meteor/app/lib/server/methods/createChannel.ts
  apps/meteor/app/lib/server/methods/createPrivateGroup.ts
  apps/meteor/server/methods/createDirectMessage.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
  apps/meteor/server/services/room/service.ts
Labels: stat: ready to merge, stat: QA tested

#29479 chore: `CustomFields` empty state
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsPage.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsRoute.js
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsRoute.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
  apps/meteor/client/views/omnichannel/customFields/RemoveCustomFieldButton.tsx
Labels: stat: ready to merge, stat: QA skipped

#29347 chore: deprecation api
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/api/server/helpers/deprecationWarning.ts
  apps/meteor/app/api/server/helpers/parseJsonQuery.ts
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/app/api/server/v1/roles.ts
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/authorization/server/methods/addUserToRole.ts
  apps/meteor/app/authorization/server/methods/deleteRole.ts
  apps/meteor/app/authorization/server/methods/removeUserFromRole.ts
  apps/meteor/app/emoji-custom/server/methods/listEmojiCustom.ts
  apps/meteor/app/lib/server/lib/deprecationWarningLogger.ts
  apps/meteor/app/lib/server/methods/checkUsernameAvailability.ts
  apps/meteor/app/lib/server/methods/deleteMessage.ts
  apps/meteor/app/livechat/imports/server/rest/inquiries.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/methods/addAgent.ts
  apps/meteor/app/livechat/server/methods/addManager.ts
  apps/meteor/app/livechat/server/methods/changeLivechatStatus.ts
  apps/meteor/app/livechat/server/methods/closeRoom.ts
  apps/meteor/app/livechat/server/methods/getCustomFields.ts
  apps/meteor/app/livechat/server/methods/getDepartmentForwardRestrictions.ts
  apps/meteor/app/livechat/server/methods/getFirstRoomMessage.ts
  apps/meteor/app/livechat/server/methods/getNextAgent.ts
  apps/meteor/app/livechat/server/methods/getTagsList.ts
  apps/meteor/app/livechat/server/methods/loadHistory.ts
  apps/meteor/app/livechat/server/methods/loginByToken.ts
  apps/meteor/app/livechat/server/methods/pageVisited.ts
  apps/meteor/app/livechat/server/methods/registerGuest.ts
  apps/meteor/app/livechat/server/methods/removeAgent.ts
  apps/meteor/app/livechat/server/methods/removeDepartment.ts
  apps/meteor/app/livechat/server/methods/removeManager.ts
  apps/meteor/app/livechat/server/methods/saveDepartmentAgents.ts
  apps/meteor/app/livechat/server/methods/saveInfo.ts
  apps/meteor/app/livechat/server/methods/saveIntegration.ts
  apps/meteor/app/livechat/server/methods/saveSurveyFeedback.ts
  apps/meteor/app/livechat/server/methods/searchAgent.ts
  apps/meteor/app/livechat/server/methods/sendOfflineMessage.ts
  apps/meteor/app/livechat/server/methods/setCustomField.ts
  apps/meteor/app/livechat/server/methods/setDepartmentForVisitor.ts
  apps/meteor/app/livechat/server/methods/transfer.ts
  apps/meteor/app/livechat/server/methods/webhookTest.ts
  apps/meteor/app/mail-messages/server/methods/sendMail.ts
  apps/meteor/app/mail-messages/server/methods/unsubscribe.ts
  apps/meteor/app/webdav/server/methods/removeWebdavAccount.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/methods/getAvatarSuggestion.ts
  apps/meteor/server/methods/getPasswordPolicy.ts
  apps/meteor/server/methods/reportMessage.ts
  apps/meteor/server/methods/roomNameExists.ts
  apps/meteor/server/methods/sendConfirmationEmail.ts
Labels: stat: needs QA

#29318 chore: replace meteor.call -> sdk.call
  apps/meteor/app/autotranslate/client/lib/actionButton.ts
  apps/meteor/app/autotranslate/client/lib/autotranslate.ts
  apps/meteor/app/custom-sounds/client/lib/CustomSounds.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.room.js
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/lib/server/methods/getUserRoles.ts
  apps/meteor/app/lib/server/methods/saveSetting.ts
  apps/meteor/app/livechat/client/externalFrame/generateNewKey.ts
  apps/meteor/app/message-mark-as-unread/client/actionButton.ts
  apps/meteor/app/meteor-accounts-saml/client/saml_client.js
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/otr/server/methods/sendSystemMessages.ts
  apps/meteor/app/reactions/client/init.js
  apps/meteor/app/settings/lib/settings.ts
  apps/meteor/app/slashcommand-asciiarts/client/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/client/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/client/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/client/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/client/unflip.ts
  apps/meteor/app/slashcommands-open/client/client.ts
  apps/meteor/app/slashcommands-status/client/status.ts
  apps/meteor/app/slashcommands-topic/client/topic.ts
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/app/user-status/client/lib/customUserStatus.js
  apps/meteor/app/utils/client/lib/SDKClient.ts
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/client/lib/chats/data.ts
  apps/meteor/client/lib/chats/flows/processSlashCommand.ts
  apps/meteor/client/lib/chats/flows/sendMessage.ts
  apps/meteor/client/lib/utils/call.ts
  apps/meteor/client/lib/utils/callWithErrorHandling.ts
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/startup/accounts.ts
  apps/meteor/client/startup/actionButtons/pinMessage.ts
  apps/meteor/client/startup/actionButtons/starMessage.ts
  apps/meteor/client/startup/actionButtons/unpinMessage.ts
  apps/meteor/client/startup/actionButtons/unstarMessage.ts
  apps/meteor/client/startup/iframeCommands.ts
  apps/meteor/client/startup/otr.ts
  apps/meteor/client/startup/rootUrlChange.ts
  apps/meteor/client/startup/startup.ts
  apps/meteor/client/startup/userRoles.ts
  apps/meteor/ee/app/authorization/client/index.ts
  apps/meteor/ee/client/lib/fetchFeatures.ts
  apps/meteor/server/services/authorization/service.ts
  packages/core-services/src/types/IAuthorization.ts
  packages/core-typings/src/SlashCommands/index.ts
  packages/ddp-client/src/DDPSDK.ts
Labels: stat: needs QA

#29313 fix: message deletion fails if has files attached on filesystem storage
  .changeset/friendly-spies-retire.md
  apps/meteor/server/ufs/ufs-local.ts
Labels: stat: needs QA

#29485 fix: Imported messages are not displayed
  .changeset/heavy-bananas-crash.md
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/importer-slack/server/importer.js
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/insertMessage.ts
  apps/meteor/app/lib/server/methods/createChannel.ts
  apps/meteor/app/lib/server/methods/createPrivateGroup.ts
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/lib/oauth/Manager.ts
  apps/meteor/server/methods/createDirectMessage.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
  apps/meteor/server/services/room/service.ts
Labels: stat: needs QA

#29483 Release 6.2.4
  .github/workflows/ci-test-e2e.yml
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/importer-slack/server/importer.js
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/insertMessage.ts
  apps/meteor/app/lib/server/methods/createChannel.ts
  apps/meteor/app/lib/server/methods/createPrivateGroup.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/lib/oauth/Manager.ts
  apps/meteor/package.json
  apps/meteor/server/methods/createDirectMessage.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
  apps/meteor/server/services/room/service.ts
  apps/meteor/server/ufs/ufs-local.ts
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
  docker-compose-ci.yml
  package.json
Labels: stat: needs QA

#29474 fix: Invalid message draft
  .changeset/quiet-kids-admire.md
  apps/meteor/client/views/room/components/body/composer/ComposerMessage.tsx
Labels: stat: ready to merge, stat: QA tested

#29480 chore: `Triggers` empty state
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/triggers/EditTriggerPage.js
  apps/meteor/client/views/omnichannel/triggers/NewTriggerPage.js
  apps/meteor/client/views/omnichannel/triggers/TriggersPage.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersRow.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersTable.js
  apps/meteor/client/views/omnichannel/triggers/TriggersTable.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersTableContainer.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: QA skipped

#29491 chore: `Tags` empty state
  apps/meteor/ee/client/omnichannel/monitors/MonitorsTable.tsx
  apps/meteor/ee/client/omnichannel/tags/RemoveTagButton.tsx
  apps/meteor/ee/client/omnichannel/tags/TagsPage.tsx
  apps/meteor/ee/client/omnichannel/tags/TagsRoute.js
  apps/meteor/ee/client/omnichannel/tags/TagsTable.tsx
Labels: stat: QA skipped

#29489 fix: Seat counter including apps
  .changeset/sixty-owls-shout.md
  apps/meteor/server/models/raw/Users.js
Labels: stat: ready to merge, stat: QA tested

#29496 chore: `Audit` empty state
  apps/meteor/ee/client/views/audit/AuditLogPage.tsx
  apps/meteor/ee/client/views/audit/components/AuditLogTable.tsx
  apps/meteor/ee/client/views/audit/components/AuditResult.tsx
Labels: stat: ready to merge, stat: QA skipped

#29495 chore: `oauthApps` empty state
  apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx
  apps/meteor/client/views/admin/oauthApps/OAuthAppsTable.tsx
Labels: stat: QA skipped

#29372 i18n: system message copy updates
  .changeset/bright-masks-enjoy.md
  apps/meteor/app/lib/lib/MessageTypes.ts
  apps/meteor/client/startup/messageTypes.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeLeaderAction.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#29498 Release 6.2.5
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  apps/meteor/server/models/raw/Users.js
  package.json
Labels: stat: needs QA

#29484 test: runInBand unit test
  packages/gazzodown/jest.config.ts
  packages/gazzodown/package.json
Labels: stat: needs QA

#28611 chore: break down helpers.ts and create new files
  .changeset/helpers.md
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppDetails/AppDetailsAPIs.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatusPriceDisplay.tsx
  apps/meteor/client/views/marketplace/helpers.ts
  apps/meteor/client/views/marketplace/helpers/apiCurlGetter.ts
  apps/meteor/client/views/marketplace/helpers/appErroredStatuses.ts
  apps/meteor/client/views/marketplace/helpers/formatPrice.ts
  apps/meteor/client/views/marketplace/helpers/formatPriceAndPurchaseType.ts
  apps/meteor/client/views/marketplace/helpers/formatPricingPlan.ts
  apps/meteor/client/views/marketplace/helpers/handleAPIError.ts
  apps/meteor/client/views/marketplace/helpers/handleInstallError.ts
  apps/meteor/client/views/marketplace/helpers/installApp.ts
  apps/meteor/client/views/marketplace/helpers/updateApp.ts
  apps/meteor/client/views/marketplace/helpers/warnAppInstall.ts
  apps/meteor/client/views/marketplace/helpers/warnEnableDisableApp.ts
  apps/meteor/client/views/marketplace/helpers/warnStatusChange.ts
  apps/meteor/client/views/marketplace/hooks/useAppInstallationHandler.tsx
  apps/meteor/client/views/marketplace/hooks/useCategories.ts
  apps/meteor/client/views/marketplace/hooks/useOpenIncompatibleModal.tsx
Labels: feat: apps, stat: ready to merge, stat: QA skipped

#29499 chore: `Departments` empty state
  apps/meteor/client/views/omnichannel/departments/ArchivedDepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/ArchivedItemMenu.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentItemMenu.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsPage.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsRoute.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/DepartmentItemMenu.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/DepartmentsTable.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/RemoveDepartmentModal.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/index.ts
Labels: stat: QA skipped

#29228 fix: Room members list out of order
  .changeset/heavy-spoons-beam.md
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/client/views/hooks/useMembersList.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.stories.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersItem.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersRow.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx
  apps/meteor/lib/getUserDisplayNames.ts
  apps/meteor/server/lib/findUsersOfRoom.ts
Labels: stat: ready to merge, stat: QA tested

#29454 fix(meteor): Scroll position is lost when loading older messages
  .changeset/honest-mails-try.md
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
Labels: stat: ready to merge, stat: QA tested

#29304 fix: Trigger url evaluation requiring `CORS` access
  .changeset/strong-fans-exist.md
  packages/livechat/src/lib/hooks.js
  packages/livechat/src/lib/main.js
  packages/livechat/src/lib/triggers.js
  packages/livechat/src/store/index.js
  packages/livechat/src/widget.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28720 chore: convert Livechat.js to ts (1/N)
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/livechat/imports/server/rest/sms.js
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/api/v1/agent.ts
  apps/meteor/app/livechat/server/api/v1/config.ts
  apps/meteor/app/livechat/server/api/v1/message.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/QueueManager.js
  apps/meteor/app/livechat/server/methods/getNextAgent.ts
  apps/meteor/app/livechat/server/methods/registerGuest.ts
  apps/meteor/app/livechat/server/methods/removeAllClosedRooms.ts
  apps/meteor/app/livechat/server/methods/removeRoom.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  packages/core-typings/src/ILivechatVisitor.ts
  packages/core-typings/src/omnichannel/routing.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29468 fix: Editing a department shows incorrect data
  .changeset/many-nails-cough.md
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/DepartmentItemMenu.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithData.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29494 chore: improve AppsFilter
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsFilters.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDown.stories.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDownAnchor.tsx
  apps/meteor/client/views/marketplace/components/RadioDropDown/RadioDownAnchor.tsx
  apps/meteor/client/views/marketplace/components/RadioDropDown/RadioDropDown.stories.tsx
  apps/meteor/client/views/marketplace/components/RadioDropDown/RadioDropDown.tsx
  apps/meteor/client/views/marketplace/helpers/isValidReference.tsx
Labels: stat: ready to merge, stat: QA skipped

#29482 chore: `Toolbox Options` visual consistency
  apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
  yarn.lock
Labels: stat: needs QA

#28608 fix: `executePreRoomUserJoined` hook called 2 times
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
Labels: stat: needs QA

#29261 refactor: Big enterprise file to ts
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/methods/saveDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/routing/LoadBalancing.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/runEndpointsAsUser.js
  apps/meteor/ee/server/models/raw/LivechatDepartment.ts
  apps/meteor/ee/server/models/raw/LivechatTag.ts
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  apps/meteor/ee/server/models/raw/ServiceLevelAgreements.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  packages/core-typings/src/ILivechatDepartment.ts
  packages/core-typings/src/ILivechatTag.ts
  packages/core-typings/src/IOmnichannelServiceLevelAgreements.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
  packages/model-typings/src/models/ILivechatTagModel.ts
  packages/model-typings/src/models/ILivechatUnitModel.ts
  packages/model-typings/src/models/IOmnichannelServiceLevelAgreementsModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29537 regression: Fix typecheck issues caused by #29261
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  packages/core-typings/src/IInquiry.ts
Labels: stat: needs QA

#29536 regression: `FilterByText` display
  apps/meteor/client/components/FilterByText.tsx
Labels: stat: ready to merge, stat: QA skipped

#29500 feat: Add Apps-engine Thread Bridge
  .changeset/cyan-panthers-allow.md
  apps/meteor/app/apps/server/bridges/bridges.js
  apps/meteor/app/apps/server/bridges/thread.ts
  apps/meteor/app/apps/server/converters/threads.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#29519 ci: New action to publish releases
  .changeset/tiny-cups-pump.md
  .github/workflows/new-release.yml
  .github/workflows/publish-release.yml
  packages/release-action/.eslintrc.json
  packages/release-action/.gitignore
  packages/release-action/CHANGELOG.md
  packages/release-action/README.md
  packages/release-action/action.yml
  packages/release-action/package.json
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/createNpmFile.ts
  packages/release-action/src/fixWorkspaceVersionsBeforePublish.ts
  packages/release-action/src/gitUtils.ts
  packages/release-action/src/index.ts
  packages/release-action/src/publishRelease.ts
  packages/release-action/src/setupOctokit.ts
  packages/release-action/src/startPatchRelease.ts
  packages/release-action/src/utils.ts
  packages/release-action/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29253 refactor: Move units check outside of model for finds
  .changeset/breezy-drinks-switch.md
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/lib/server/functions/closeOmnichannelConversations.ts
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/api/lib/rooms.ts
  apps/meteor/app/livechat/server/api/lib/visitors.ts
  apps/meteor/app/livechat/server/api/v1/message.ts
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/Analytics.js
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/methods/getNextAgent.ts
  apps/meteor/app/livechat/server/methods/registerGuest.ts
  apps/meteor/app/livechat/server/methods/removeAllClosedRooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applyDepartmentRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applyRoomRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/SlaHelper.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/query.helper.js
  apps/meteor/ee/server/lib/audit/methods.ts
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#26875 feat: Allow Incoming Webhooks to override destination channel
  .changeset/shy-bees-serve.md
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts
  apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js
  apps/meteor/client/views/admin/integrations/edit/EditIncomingWebhook.js
  apps/meteor/client/views/admin/integrations/new/NewIncomingWebhook.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v298.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
  apps/meteor/tests/end-to-end/api/07-incoming-integrations.js
  packages/core-typings/src/IIntegration.ts
  packages/rest-typings/src/v1/integrations/IntegrationsCreateProps.ts
  packages/rest-typings/src/v1/integrations/IntegrationsUpdateProps.ts
Labels: stat: QA tested, feat: team-collab

#29539 ci: Mock highlight for unit tests
  packages/gazzodown/src/Markup.spec.tsx
Labels: stat: needs QA

#29538 fix: search (ctrl + K) and keyboard arrow issue
  .changeset/search-shortcut.md
  apps/meteor/client/sidebar/search/SearchList.tsx
Labels: stat: ready to merge, stat: QA skipped

#29453 fix: Frontend crash if IndexedDB is not available, i.e. in Firefox private mode
  .changeset/silly-stingrays-play.md
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
Labels: stat: QA skipped

#29522 feat: add message to uikit interaction
  apps/meteor/app/ui-message/client/actionButtons/messageBox.ts
  apps/meteor/app/ui-utils/client/lib/messageBox.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx
  apps/meteor/ee/server/apps/communication/uikit.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#29477 chore(meteor): Replace `useEndpointData` in favor of `useQuery` in `UserCard`
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
Labels: stat: ready to merge, stat: QA skipped

#29546 fix: Message sent triggering thread subscriptions multiple times
  .changeset/tricky-tomatoes-sit.md
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts
Labels: stat: needs QA

#29535 refactor: Livechat Button to TS
  packages/livechat/src/components/Button/index.js
  packages/livechat/src/components/Button/index.tsx
  packages/livechat/src/scss.d.ts
Labels: stat: ready to merge, stat: QA skipped

#28252 refactor: omnichannel on-hold feature
  .changeset/moody-teachers-cheer.md
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/lib/QueueManager.js
  apps/meteor/app/livechat/server/lib/RoutingManager.js
  apps/meteor/client/views/room/components/body/composer/ComposerOmnichannel/hooks/useResumeChatOnHoldMutation.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/rooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterOnHold.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterOnHoldChatResumed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onAgentAssignmentFailed.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCloseLivechat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts
  apps/meteor/ee/app/livechat-enterprise/server/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/resumeOnHold.ts
  apps/meteor/ee/app/livechat-enterprise/server/services/omnichannel.internalService.ts
  apps/meteor/ee/server/startup/services.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/18-rooms-ee.ts
  packages/core-services/src/index.ts
  packages/core-services/src/types/IOmnichannelEEService.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/IMessagesModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29493 fix: Emoji being rendered as big
  .changeset/gorgeous-lamps-tan.md
  apps/meteor/app/emoji-emojione/client/emojione-sprites.css
  apps/meteor/app/emoji-emojione/lib/generateEmojiIndex.mjs
  apps/meteor/app/theme/client/imports/components/emoji.css
Labels: stat: ready to merge, stat: QA tested

#29547 fix: spotlight reacts to new rooms
  .changeset/flat-fireants-itch.md
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/tests/e2e/message-actions.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#29550 chore: add message body fallback while markup is loading
  apps/meteor/client/components/message/MessageContentBody.tsx
Labels: stat: ready to merge, stat: QA skipped

#29523 fix: re-added pagination to department's agents table
  .changeset/nervous-bulldogs-fix.md
  apps/meteor/client/components/GenericTable/hooks/usePagination.ts
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/DepartmentAgentsTable.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29418 fix: Unable to open Releases inside App info
  .changeset/app-release-info-page.md
  apps/meteor/ee/server/apps/communication/rest.ts
Labels: stat: ready to merge, stat: QA skipped

#26400 fix: [ENTERPRISE] Guest users can join more than maxRoomsPerGuest rooms
  .changeset/shiny-donkeys-prove.md
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/ee/app/license/server/license.ts
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/ee/server/startup/maxRoomsPerGuest.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/tests/data/constants.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
  apps/meteor/tests/end-to-end/api/24-methods.js
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#29115 fix: Incomplete emails are being accepted at user registration
  .changeset/incomplete-emails.md
  packages/web-ui-registration/src/RegisterForm.tsx
Labels: stat: QA tested

#29459 fix: Custom Translation setting does not wrap text correctly
  .changeset/custom-translations-text-wrap.md
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
Labels: stat: ready to merge, stat: QA tested, feat: workspace-mgmt

#29554 regression: slashcommands
  .changeset/dull-apples-fold.md
  apps/meteor/app/slashcommand-asciiarts/client/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/client/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/client/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/client/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/client/unflip.ts
  apps/meteor/app/slashcommand-asciiarts/server/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/server/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/server/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/server/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/server/unflip.ts
  apps/meteor/app/utils/lib/slashCommand.ts
  apps/meteor/app/utils/server/index.ts
  apps/meteor/app/utils/server/slashCommand.ts
Labels: stat: ready to merge, stat: QA tested

#29563 ci: Fixes to publish automation
  .changeset/popular-llamas-notice.md
  .changeset/wet-cherries-hunt.md
  .github/workflows/new-release.yml
  .github/workflows/publish-release.yml
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/fixWorkspaceVersionsBeforePublish.ts
  packages/release-action/src/gitUtils.ts
  packages/release-action/src/index.ts
  packages/release-action/src/publishRelease.ts
  packages/release-action/src/startPatchRelease.ts
  packages/release-action/src/utils.ts
Labels: stat: ready to merge, stat: QA skipped

#29530 regression(meteor): Fix message composer popup
  .changeset/soft-rabbits-sin.md
  apps/meteor/app/ui-message/client/popup/hooks/useEnablePopupPreview.ts
Labels: stat: ready to merge, stat: QA tested

#29420 fix: Manually approved user registration flow
  .changeset/registration-flow.md
  packages/web-ui-registration/src/RegisterForm.tsx
Labels: stat: ready to merge, stat: QA tested, feat: workspace-mgmt

#29457 fix: handle list type values in app setting comparison (old vs new)
  apps/meteor/server/services/apps-engine/service.ts
Labels: stat: ready to merge, stat: QA tested

#28589 feat: Add setting to synchronize LDAP info on OAuth logins
  .changeset/purple-tigers-taste.md
  apps/meteor/app/custom-oauth/server/custom_oauth_server.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/lib/ldap/Manager.ts
  apps/meteor/server/services/ldap/service.ts
  apps/meteor/server/settings/ldap.ts
  packages/core-services/src/types/ILDAPService.ts
Labels: stat: ready to merge, stat: QA tested

#29056 fix: Custom OAuth settings are not visible
  .changeset/stale-moose-grab.md
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v299.ts
Labels: stat: ready to merge, stat: QA tested, squad: WM

#29578 fix: Direct message notification
  .changeset/rude-islands-clap.md
  apps/meteor/server/lib/rooms/roomTypes/direct.ts
Labels: stat: needs QA

#29581 chore: Add eslint `react-jsx-key` rule on client
  apps/meteor/client/.eslintrc.json
  apps/meteor/client/components/CustomFieldsForm.js
  apps/meteor/client/components/message/hooks/useCollapse.tsx
  apps/meteor/client/views/admin/federationDashboard/OverviewSection.tsx
  apps/meteor/client/views/admin/settings/groups/voip/VoipExtensionsPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/CustomFieldsList.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/RealTimeMonitoringPage.js
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
  apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItem.js
  apps/meteor/client/views/room/lib/Toolbox/index.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/BusinessHoursMultiple.stories.tsx
  apps/meteor/server/lib/rooms/roomTypes/direct.ts
Labels: stat: ready to merge, stat: QA skipped

#29521 fix: Ignore archived departments from business hours queries
  .changeset/rotten-spoons-teach.md
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
Labels: stat: needs QA, feat: omnichannel

#29565 fix: Canned responses filter not working
  .changeset/twelve-mirrors-destroy.md
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29551 fix: Wrong IP usage on monolith TCP transporter configuration
  .changeset/five-clouds-obey.md
  apps/meteor/ee/server/local-services/instance/getLogger.ts
  apps/meteor/ee/server/local-services/instance/getTransporter.ts
  apps/meteor/ee/server/local-services/instance/service.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
Labels: stat: ready to merge, stat: QA skipped

#29490 feat: Save deprecation usage on prometheus
  .changeset/cool-roses-melt.md
  apps/meteor/app/lib/server/lib/deprecationWarningLogger.ts
  apps/meteor/app/metrics/server/lib/metrics.ts
Labels: stat: ready to merge, stat: QA skipped

#29569 feat: Quick reactions on message toolbox
  .changeset/early-bikes-dream.md
  apps/meteor/app/emoji/client/helpers.ts
  apps/meteor/app/emoji/client/types.ts
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/contexts/EmojiPickerContext.ts
  apps/meteor/client/providers/EmojiPickerProvider.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiCategoryRow.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiElement.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/composer/EmojiPicker/SearchingResult.tsx
Labels: stat: ready to merge, stat: QA skipped

#29582 chore: Sanitize `Header` component
  apps/meteor/app/threads/client/flextab/threadlist.tsx
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/views/room/Header/FederatedRoomOriginServer.tsx
  apps/meteor/client/views/room/Header/Header.tsx
  apps/meteor/client/views/room/Header/HeaderIconWithRoom.tsx
  apps/meteor/client/views/room/Header/Omnichannel/BackButton.tsx
  apps/meteor/client/views/room/Header/Omnichannel/OmnichannelRoomHeader.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/ToolBoxActionOptions.tsx
  apps/meteor/client/views/room/Header/Omnichannel/VoipRoomHeader.tsx
  apps/meteor/client/views/room/Header/ParentRoom.tsx
  apps/meteor/client/views/room/Header/ParentRoomWithEndpointData.tsx
  apps/meteor/client/views/room/Header/ParentTeam.tsx
  apps/meteor/client/views/room/Header/RoomHeader.tsx
  apps/meteor/client/views/room/Header/RoomTitle.tsx
  apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
  apps/meteor/client/views/room/Header/icons/Encrypted.tsx
  apps/meteor/client/views/room/Header/icons/Favorite.tsx
  apps/meteor/client/views/room/Header/icons/Translate.tsx
  apps/meteor/client/views/room/RoomNotFound.tsx
  apps/meteor/client/views/room/RoomSkeleton.tsx
  packages/ui-client/src/components/Header/Header.stories.tsx
  packages/ui-client/src/components/Header/HeaderTag/HeaderTag.tsx
  packages/ui-client/src/components/Header/HeaderTag/HeaderTagIcon.tsx
  packages/ui-client/src/components/Header/HeaderTag/HeaderTagSkeleton.tsx
  packages/ui-client/src/components/Header/HeaderTag/index.ts
  packages/ui-client/src/components/Header/HeaderToolbox/HeaderToolbox.tsx
  packages/ui-client/src/components/Header/HeaderToolbox/HeaderToolboxAction.tsx
  packages/ui-client/src/components/Header/HeaderToolbox/HeaderToolboxActionBadge.tsx
  packages/ui-client/src/components/Header/HeaderToolbox/HeaderToolboxDivider.tsx
  packages/ui-client/src/components/Header/HeaderToolbox/index.ts
  packages/ui-client/src/components/Header/ToolBox/ToolBox.tsx
  packages/ui-client/src/components/Header/ToolBox/ToolboxDivider.tsx
  packages/ui-client/src/components/Header/ToolBox/index.ts
  packages/ui-client/src/components/Header/index.ts
  packages/ui-client/src/components/index.ts
Labels: stat: needs QA

#29588 chore: replace `Menu` in favor of `MenuV2` on `CreateRoom.tsx`
  apps/meteor/client/components/GenericMenu.tsx
  apps/meteor/client/components/GenericMenuContent.tsx
  apps/meteor/client/components/GenericMenuItem.tsx
  apps/meteor/client/hooks/useHandleMenuAction.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoom.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
  apps/meteor/client/sidebar/header/actions/Sort.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useGroupingListItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useMatrixFederationItems.tsx.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useSortMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useSortModeItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useViewModeItems.tsx
  apps/meteor/client/sidebar/header/hooks/useCreateRoomModal.tsx
Labels: stat: needs QA

#29584 fix(meteor): Room history being lost
  .changeset/kind-experts-shake.md
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
Labels: stat: needs QA

#29472 fix(multiinstance): use ipList for node:node connection
  .changeset/pink-carrots-matter.md
  apps/meteor/ee/server/local-services/instance/getTransporter.ts
  apps/meteor/ee/tests/unit/apps/meteor/ee/server/local-services/instance/getTransporter.spec.ts
Labels: stat: needs QA

#29596 Release 6.2.7
  .changeset/five-clouds-obey.md
  .changeset/pink-carrots-matter.md
  .changeset/popular-llamas-notice.md
  .changeset/proud-cars-guess.md
  .changeset/wet-cherries-hunt.md
  .github/workflows/new-release.yml
  .github/workflows/publish-release.yml
  apps/meteor/ee/server/local-services/instance/getLogger.ts
  apps/meteor/ee/server/local-services/instance/getTransporter.ts
  apps/meteor/ee/server/local-services/instance/service.ts
  apps/meteor/ee/tests/unit/apps/meteor/ee/server/local-services/instance/getTransporter.spec.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/fixWorkspaceVersionsBeforePublish.ts
  packages/release-action/src/gitUtils.ts
  packages/release-action/src/index.ts
  packages/release-action/src/publishRelease.ts
  packages/release-action/src/startPatchRelease.ts
  packages/release-action/src/utils.ts
Labels: stat: needs QA

#29591 fix: Avoid invalid time ranges when adding/editing a Business Hour
  .changeset/kind-insects-agree.md
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29595 test: omnichannel departaments flaky test
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#29425 fix: Omnichannel making an excessive amount of requests to room.info
  .changeset/light-toys-refuse.md
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/client/views/omnichannel/directory/hooks/useOmnichannelRoomInfo.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29577 regression(meteor): Fix dates translations
  .changeset/rare-goats-promise.md
  apps/meteor/client/providers/TranslationProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#29549 fix: Dept w/o any BH do not adhere to the default BH rules.
  .changeset/little-ligers-hug.md
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29608 regression: revert eslint upgrade
  apps/meteor/app/slashcommands-inviteall/server/server.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/hooks/useMediaPermissions.ts
  apps/meteor/package.json
  apps/meteor/server/startup/migrations/v273.ts
  yarn.lock
Labels: stat: QA skipped

#29603 regression: Emojis taking too long to render on `EmojiPicker`
  apps/meteor/app/emoji/client/helpers.ts
  apps/meteor/app/emoji/client/types.ts
  apps/meteor/client/components/message/toolbox/Toolbox.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiCategoryRow.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiElement.tsx
  apps/meteor/client/views/composer/EmojiPicker/SearchingResult.tsx
Labels: stat: ready to merge, stat: QA skipped

#29612 regression: `Contextualbar` size on wider screens
  apps/meteor/client/providers/LayoutProvider.tsx
Labels: stat: QA skipped

#29497 fix: self dm is not found with `im.messages`
  .changeset/friendly-terms-tell.md
  apps/meteor/app/lib/server/functions/getRoomByNameOrIdWithOptionToJoin.ts
  apps/meteor/tests/end-to-end/api/04-direct-message.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#29610 fix: Adjusted to not show 'removed from' notification on Omnichannel rooms
  apps/meteor/client/views/room/components/body/hooks/useGoToHomeOnRemoved.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29594 chore: Remove old deprecated `GenericTable` in favor of v2
  apps/meteor/client/components/GenericTable/GenericTable.stories.tsx
  apps/meteor/client/components/GenericTable/GenericTable.tsx
  apps/meteor/client/components/GenericTable/GenericTableBody.tsx
  apps/meteor/client/components/GenericTable/GenericTableCell.tsx
  apps/meteor/client/components/GenericTable/GenericTableHeader.tsx
  apps/meteor/client/components/GenericTable/GenericTableHeaderCell.tsx
  apps/meteor/client/components/GenericTable/GenericTableLoadingRow.tsx
  apps/meteor/client/components/GenericTable/GenericTableLoadingTable.tsx
  apps/meteor/client/components/GenericTable/GenericTableRow.tsx
  apps/meteor/client/components/GenericTable/HeaderCell.tsx
  apps/meteor/client/components/GenericTable/V2/GenericTable.tsx
  apps/meteor/client/components/GenericTable/V2/GenericTableBody.tsx
  apps/meteor/client/components/GenericTable/V2/GenericTableCell.tsx
  apps/meteor/client/components/GenericTable/V2/GenericTableHeader.tsx
  apps/meteor/client/components/GenericTable/V2/GenericTableRow.tsx
  apps/meteor/client/components/GenericTable/index.ts
  apps/meteor/client/views/admin/customSounds/CustomSoundsTable/CustomSoundRow.tsx
  apps/meteor/client/views/admin/permissions/PermissionsTable/RoleHeader.tsx
  apps/meteor/client/views/admin/settings/groups/voip/VoipExtensionsPage.tsx
  apps/meteor/client/views/omnichannel/businessHours/BusinessHoursPage.js
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTable.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTableRow.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTab.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/omnichannel/queueList/QueueListPage.tsx
  apps/meteor/client/views/omnichannel/queueList/QueueListTable.tsx
  apps/meteor/client/views/omnichannel/queueList/index.ts
  apps/meteor/client/views/omnichannel/queueList/index.tsx
  apps/meteor/client/views/teams/contextualBar/info/Delete/ChannelDeletionTable.js
  apps/meteor/client/views/teams/contextualBar/info/Delete/ChannelDeletionTable.tsx
  apps/meteor/client/views/teams/contextualBar/info/Delete/ChannelDeletionTableRow.tsx
  apps/meteor/client/views/teams/contextualBar/info/Delete/ChannelRow.js
  apps/meteor/ee/client/omnichannel/BusinessHoursRow.js
  apps/meteor/ee/client/omnichannel/BusinessHoursTable.js
  apps/meteor/ee/client/omnichannel/BusinessHoursTable.stories.tsx
  apps/meteor/ee/client/omnichannel/BusinessHoursTableContainer.js
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesPage.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/RemoveCannedResponseButton.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesTable.tsx
Labels: stat: needs QA

#29583 chore: replace `Menu` in favor of `MenuV2` on `Administration.tsx`
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAppsItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.tsx
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/unit/client/sidebar/header/actions/Administration.spec.tsx
Labels: stat: needs QA

#29587 fix: Show badge for threads direct mentions
  .changeset/little-crews-end.md
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
Labels: stat: ready to merge, stat: QA tested

#29322 feat: Implement new password verification flow front
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  packages/rest-typings/src/v1/misc.ts
  packages/ui-client/src/components/PasswordVerifier.tsx
  packages/ui-client/src/components/index.ts
  packages/ui-contexts/src/hooks/usePasswordPolicy.ts
  packages/ui-contexts/src/hooks/useVerifyPassword.ts
  packages/ui-contexts/src/index.ts
  packages/web-ui-registration/package.json
  packages/web-ui-registration/src/RegisterForm.tsx
  packages/web-ui-registration/src/ResetPassword/ResetPasswordPage.tsx
  packages/web-ui-registration/src/hooks/usePasswordPolicy.ts
  password-verification-front.md
  yarn.lock
Labels: stat: QA tested, feat: workspace-mgmt

#29599 ci(lint): Broken ESLint
  apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/outgoing/updateOutgoingIntegration.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/server/lib/parseMessageSearchQuery.ts
  apps/meteor/server/models/raw/Analytics.ts
  apps/meteor/server/models/raw/VideoConference.ts
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/presence/package.json
  ee/packages/ui-theming/package.json
  packages/account-utils/package.json
  packages/agenda/package.json
  packages/api-client/package.json
  packages/base64/package.json
  packages/cas-validate/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/cron/package.json
  packages/ddp-client/package.json
  packages/eslint-config/package.json
  packages/favicon/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/i18n/package.json
  packages/instance-status/package.json
  packages/livechat/package.json
  packages/log-format/package.json
  packages/model-typings/package.json
  packages/models/package.json
  packages/node-poplib/package.json
  packages/random/package.json
  packages/release-action/package.json
  packages/rest-typings/package.json
  packages/server-fetch/package.json
  packages/sha256/package.json
  packages/tools/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29526 fix(meteor): Message composer keeps recording even though permission was denied
  .changeset/soft-carrots-add.md
  apps/meteor/app/ui/client/lib/recorderjs/AudioRecorder.ts
Labels: stat: ready to merge, stat: QA tested

#29556 fix: hidden custom fields being validated on some cases
  .changeset/pretty-clocks-add.md
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/server/models/raw/LivechatCustomField.ts
  apps/meteor/tests/e2e/omnichannel-contact-center.spec.ts
  packages/model-typings/src/models/ILivechatCustomFieldModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29455 fix: Show agent email not being passed to model calls
  .changeset/brown-forks-fry.md
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/app/livechat/server/methods/getAgentData.ts
  apps/meteor/app/livechat/server/methods/getNextAgent.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/server/models/raw/Users.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29629 chore: load dialpad modal lazy
  apps/meteor/client/hooks/useDialModal.tsx
  apps/meteor/client/startup/customOAuth.ts
Labels: stat: needs QA

#28240 fix: Events listeners were not being removed when services (local) were destroyed
  apps/meteor/ee/server/NetworkBroker.ts
  packages/core-services/babel.config.js
  packages/core-services/package.json
  packages/core-services/src/LocalBroker.ts
  packages/core-services/src/types/ServiceClass.ts
  packages/core-services/tests/LocalBroker.test.ts
  packages/core-services/tests/ServiceClass.test.ts
  yarn.lock
Labels: type: bug, stat: needs QA

#29572 chore: improve omnichannel tests reliability
  apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-auto-onhold-chat-closing.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-auto-transfer-unanswered-chat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-canned-responses-sidebar.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-changing-room-priority-and-sla.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-chat-history.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-close-chat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-close-inquiry.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-center.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-info.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-currentChats.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-custom-fields.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-departaments-ce.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-manager.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-priorities.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-send-transcript.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-sla-policies.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-takeChat.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-transfer-to-another-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-triggers.ts
Labels: stat: QA skipped, feat: omnichannel

#29406 refactor: convert routing manager to ts
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/hooks/saveLastMessageToInquiry.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/livechat/server/methods/getRoutingConfig.ts
  apps/meteor/app/livechat/server/methods/takeInquiry.ts
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/lib/callbacks.ts
  packages/core-typings/src/IInquiry.ts
  packages/core-typings/src/omnichannel/routing.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29625 fix(meteor): Autotranslate encoding message
  .changeset/hungry-oranges-explode.md
  apps/meteor/app/autotranslate/server/deeplTranslate.ts
  apps/meteor/app/autotranslate/server/googleTranslate.ts
Labels: stat: ready to merge, stat: QA tested

#29202 feat: custom fields component to registration form
  .changeset/custom-fields.md
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/client/components/AccountsCustomFields/AccountsCustomFieldsAssembler.tsx
  apps/meteor/client/components/AccountsCustomFields/index.ts
  apps/meteor/client/components/CustomFieldsForm.js
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
  apps/meteor/client/views/admin/users/AddUser.js
  apps/meteor/client/views/admin/users/EditUser.js
  apps/meteor/client/views/admin/users/UserForm.js
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsForm.stories.tsx
  apps/meteor/client/views/omnichannel/customFields/EditCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/customFields/NewCustomFieldsForm.js
  apps/meteor/client/views/omnichannel/customFields/NewCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
  apps/meteor/client/views/omnichannel/directory/utils/formatCustomFieldsMetadata.tsx
  apps/meteor/client/views/root/MainLayout/RegisterUsername.tsx
  packages/core-typings/src/CustomFieldMetadata.ts
  packages/core-typings/src/index.ts
  packages/rest-typings/src/v1/users/UserRegisterParamsPOST.ts
  packages/ui-client/package.json
  packages/ui-client/src/components/CustomFieldsForm.tsx
  packages/ui-client/src/components/index.ts
  packages/ui-contexts/src/hooks/useAccountsCustomFields.ts
  packages/ui-contexts/src/index.ts
  packages/web-ui-registration/src/RegisterForm.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA tested, feat: workspace-mgmt

#29633 ci: uikit loglevel silent
  .github/workflows/ci.yml
  packages/uikit-playground/vite.config.ts
Labels: stat: needs QA

#29628 chore: `Table` in favor of `GenericTable`
  apps/meteor/client/views/account/tokens/AccountTokensTable/AccountTokensRow.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusTable/CustomUserStatusRow.tsx
  apps/meteor/client/views/admin/emailInbox/SendTestButton.tsx
  apps/meteor/client/views/admin/import/ImportHistoryPage.tsx
  apps/meteor/client/views/admin/import/ImportOperationSummary.js
  apps/meteor/client/views/admin/import/ImportOperationSummary.stories.tsx
  apps/meteor/client/views/admin/import/ImportOperationSummarySkeleton.js
  apps/meteor/client/views/admin/import/PrepareChannels.tsx
  apps/meteor/client/views/admin/import/PrepareUsers.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleTableRow.tsx
  apps/meteor/client/views/admin/permissions/PermissionsTable/PermissionRow.tsx
  apps/meteor/client/views/admin/permissions/PermissionsTable/RoleCell.tsx
  apps/meteor/client/views/admin/permissions/UsersInRole/UsersInRoleTable/UsersInRoleTableRow.tsx
  apps/meteor/client/views/admin/settings/groups/voip/AssignAgentButton.tsx
  apps/meteor/client/views/admin/settings/groups/voip/RemoveAgentButton.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTableRow.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTableRow.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTableRow.tsx
  apps/meteor/client/views/directory/tabs/users/UsersTable/UsersTableRow.tsx
  apps/meteor/client/views/omnichannel/analytics/AgentOverview.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/AgentRow.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTableRow.tsx
  apps/meteor/client/views/omnichannel/managers/RemoveManagerButton.tsx
  apps/meteor/client/views/teams/ChannelDesertionTable/ChannelDesertionTableRow.tsx
  apps/meteor/ee/client/omnichannel/RemoveBusinessHourButton.js
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountRow.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminRow.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/channels/ChannelsOverview.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/messages/MessagesPerChannelSection.tsx
  apps/meteor/ee/client/views/audit/components/AuditLogEntry.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29302 feat: `showThreadsInMainChannel` Preference
  .changeset/slimy-olives-march.md
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.tsx
  apps/meteor/client/views/account/preferences/PreferencesMessagesSection.tsx
  apps/meteor/client/views/room/MessageList/hooks/useMessages.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/settings/accounts.ts
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  packages/rest-typings/src/v1/users/UsersSetPreferenceParamsPOST.ts
Labels: stat: ready to merge, stat: QA tested

#29639 feat: add `tmid` to UiKit interaction block action
  apps/meteor/app/ui-message/client/ActionManager.js
  apps/meteor/ee/server/apps/communication/uikit.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29413 feat(fuselage-ui-kit): Add `i18n` parser to render surfaces and blocks
  .changeset/rude-insects-speak.md
  apps/meteor/ee/client/apps/i18n.js
  packages/fuselage-ui-kit/src/elements/MarkdownTextElement.tsx
  packages/fuselage-ui-kit/src/elements/PlainTextElement.tsx
  packages/fuselage-ui-kit/src/surfaces/FuselageSurfaceRenderer.tsx
  yarn.lock
Labels: feat: apps, stat: ready to merge, stat: QA tested

#29264 refactor: `AppsProvider`
  apps/meteor/client/contexts/AppsContext.tsx
  apps/meteor/client/contexts/hooks/useAppsReload.ts
  apps/meteor/client/contexts/hooks/useAppsResult.ts
  apps/meteor/client/providers/AppsProvider.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppRequests/AppRequests.tsx
  apps/meteor/client/views/marketplace/AppInstallPage.js
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContentBody.tsx
  apps/meteor/client/views/marketplace/AppsRoute.tsx
  apps/meteor/client/views/marketplace/helpers/installApp.ts
  apps/meteor/client/views/marketplace/helpers/updateApp.ts
  apps/meteor/client/views/marketplace/hooks/useAppInfo.ts
  apps/meteor/client/views/marketplace/hooks/useAppInstallationHandler.tsx
  apps/meteor/client/views/marketplace/hooks/useCategories.ts
  apps/meteor/client/views/marketplace/hooks/useFilteredApps.ts
  apps/meteor/client/views/marketplace/hooks/useOpenIncompatibleModal.tsx
  apps/meteor/ee/client/apps/i18n.js
  apps/meteor/ee/client/apps/index.ts
  apps/meteor/ee/client/apps/orchestrator.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-members.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
Labels: feat: apps, stat: ready to merge, stat: QA tested

#29648 fix: Canned responses filter not working
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#29650 refactor: simplified canned response filter query
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#29626 chore: Add tests to business hours and remove logs
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/app/livechat/server/business-hour/BusinessHourManager.ts
  apps/meteor/app/utils/server/functions/getDefaultUserFields.ts
  apps/meteor/ee/app/livechat-enterprise/client/startup.ts
  apps/meteor/tests/data/livechat/business-hours.ts
  apps/meteor/tests/data/livechat/businessHours.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#29636 fix: Canned responses text editor without contrast in dark mode
  .changeset/smooth-hotels-hunt.md
  apps/meteor/ee/client/omnichannel/components/CannedResponse/TextEditor/Textarea.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29649 fix(meteor): Video Record button disabled on iOS browsers
  .changeset/itchy-hotels-care.md
  apps/meteor/app/ui/client/lib/recorderjs/videoRecorder.ts
  apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
Labels: stat: ready to merge, stat: QA tested

#29580 chore: Menu v2
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AppsModelList.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AuditModelList.tsx
  apps/meteor/client/components/GenericMenu.tsx
  apps/meteor/client/components/GenericMenuItem.tsx
  apps/meteor/client/components/SortList/GroupingList.tsx
  apps/meteor/client/components/SortList/SortList.tsx
  apps/meteor/client/components/SortList/SortModeList.tsx
  apps/meteor/client/components/SortList/ViewModeList.tsx
  apps/meteor/client/components/SortList/index.ts
  apps/meteor/client/hooks/useHandleMenuAction.tsx
  apps/meteor/client/providers/TooltipProvider.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoom.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
  apps/meteor/client/sidebar/header/actions/Sort.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAppsItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useGroupingListItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useMatrixFederationItems.tsx.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useSortMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useSortModeItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useViewModeItems.tsx
  apps/meteor/client/sidebar/header/hooks/useCreateRoomModal.tsx
  apps/meteor/tests/e2e/administration-menu.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/unit/client/sidebar/header/actions/Administration.spec.tsx
  ee/packages/ui-theming/src/paletteDark.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29659 regression: Apps translations not working randomly
  apps/meteor/app/ui-message/client/actionButtons/messageAction.ts
  apps/meteor/app/ui-message/client/actionButtons/messageBox.ts
  apps/meteor/app/ui-message/client/actionButtons/tabbar.ts
  apps/meteor/client/providers/TranslationProvider.tsx
  apps/meteor/ee/client/apps/orchestrator.ts
Labels: stat: needs QA

#28986 fix: close button of Invite friends Dialog in the Game Center
  apps/meteor/ee/client/apps/gameCenter/GameCenterInvitePlayersModal.tsx
Labels: communityPR, stat: QA skipped

#29290 fix: Omnichannel queue not running for all queues
  .changeset/spicy-kiwis-invent.md
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#29669 regression: `showThreadsInMainChannel` preference misaligned
  apps/meteor/client/views/account/preferences/PreferencesMessagesSection.tsx
Labels: stat: ready to merge, stat: QA skipped

#28627 fix: Misaligned alignment of prompt when hover on user / room name in room information and user information section
  apps/meteor/client/components/InfoPanel/InfoPanelTitle.tsx
Labels: communityPR, stat: QA skipped

#29670 regression: Opening the dial pad crashes the GUI
  apps/meteor/client/hooks/useDialModal.tsx
  apps/meteor/ee/client/voip/modal/DialPad/hooks/useDialPad.tsx
Labels: stat: needs QA, feat: omnichannel

#29676 ci: Add missing `context` property on compose file
  docker-compose-ci.yml
Labels: stat: ready to merge, stat: QA skipped

#29675 regression: `onLogin` hook not destructuring user prop
  .changeset/dull-rockets-own.md
  apps/meteor/app/livechat/server/business-hour/index.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#29529 fix: Newly added agent not following business hours
  .changeset/quick-coats-protect.md
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/app/livechat/server/business-hour/BusinessHourManager.ts
  apps/meteor/app/livechat/server/business-hour/Helper.ts
  apps/meteor/app/livechat/server/business-hour/Single.ts
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/logger.ts
  apps/meteor/app/livechat/server/sendMessageBySMS.ts
  apps/meteor/app/livechat/server/startup.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCloseLivechat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.ts
  apps/meteor/ee/app/livechat-enterprise/server/startup.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/Users.js
  apps/meteor/tests/data/livechat/businessHours.ts
  apps/meteor/tests/data/livechat/users.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
  packages/core-typings/src/ILivechatAgent.ts
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29644 chore: tests for BH behavior (department actions)
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: needs QA, feat: omnichannel

#29684 ci: update EE license
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA skipped

#29627 chore: add change stream option to get full doc
  apps/meteor/server/database/DatabaseWatcher.ts
  apps/meteor/server/database/convertChangeStreamPayload.ts
  apps/meteor/server/database/watchCollections.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  ee/apps/stream-hub-service/src/service.ts
Labels: stat: needs QA

#29686 Release 6.2.9
  .changeset/hip-comics-drop.md
  .changeset/itchy-hotels-care.md
  .changeset/soft-carrots-add.md
  .github/workflows/ci.yml
  apps/meteor/app/ui/client/lib/recorderjs/AudioRecorder.ts
  apps/meteor/app/ui/client/lib/recorderjs/videoRecorder.ts
  apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
  apps/meteor/server/database/DatabaseWatcher.ts
  apps/meteor/server/database/convertChangeStreamPayload.ts
  apps/meteor/server/database/watchCollections.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  docker-compose-ci.yml
  ee/apps/stream-hub-service/src/service.ts
Labels: stat: needs QA
