Repository RocketChat/Rocket.Chat, pull requests merged in 2023-05, with the labels that each got.

#28836 refactor: `EmojiPicker` to React Component
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.js
  apps/meteor/app/emoji-emojione/client/lib.ts
  apps/meteor/app/emoji-emojione/server/lib.ts
  apps/meteor/app/emoji/client/emojiPicker.html
  apps/meteor/app/emoji/client/emojiPicker.js
  apps/meteor/app/emoji/client/helpers.ts
  apps/meteor/app/emoji/client/index.ts
  apps/meteor/app/emoji/client/lib.ts
  apps/meteor/app/emoji/client/lib/EmojiPicker.js
  apps/meteor/app/emoji/client/types.ts
  apps/meteor/app/emoji/lib/rocketchat.ts
  apps/meteor/app/emoji/server/lib.ts
  apps/meteor/app/reactions/client/init.js
  apps/meteor/app/theme/client/imports/components/emoji.css
  apps/meteor/app/theme/client/imports/components/emojiPicker.css
  apps/meteor/app/theme/client/main.css
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/client/components/ScrollableContentWrapper.tsx
  apps/meteor/client/contexts/EmojiPickerContext.ts
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/main.ts
  apps/meteor/client/providers/EmojiPickerProvider.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/templates.ts
  apps/meteor/client/views/composer/EmojiPicker/CategoriesResult.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiCategoryRow.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiElement.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPickerCategoryItem.tsx
  apps/meteor/client/views/composer/EmojiPicker/SearchingResult.tsx
  apps/meteor/client/views/composer/EmojiPicker/SearchingResultWrapper.tsx
  apps/meteor/client/views/composer/EmojiPicker/ToneSelector/ToneItem.tsx
  apps/meteor/client/views/composer/EmojiPicker/ToneSelector/ToneSelector.tsx
  apps/meteor/client/views/composer/EmojiPicker/ToneSelector/index.ts
  apps/meteor/client/views/composer/EmojiPicker/index.ts
  apps/meteor/client/views/composer/EmojiPickerWrapper.tsx
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useChatMessagesInstance.ts
  apps/meteor/definition/externals/meteor/templating.d.ts
  apps/meteor/ee/client/omnichannel/components/CannedResponse/MarkdownTextEditor/index.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/emojis.spec.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  packages/ui-client/src/components/EmojiPicker/EmojiPickerCategoryHeader.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerCategoryWrapper.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerContainer.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerFooter.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerHeader.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerListArea.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerLoadMore.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerNotFound.tsx
  packages/ui-client/src/components/EmojiPicker/index.ts
  packages/ui-client/src/components/index.ts
  yarn.lock
Labels: stat: needs QA

#27770 feat(matrix): Matrix search UI
  apps/meteor/client/sidebar/header/MatrixFederationSearch/FederatedRoomList.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/FederatedRoomListEmptyPlaceholder.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/FederatedRoomListErrorBoundary.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/FederatedRoomListItem.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationManageServerModal.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationRemoveServerList.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationSearch.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationSearchModalContent.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/index.ts
  apps/meteor/client/sidebar/header/MatrixFederationSearch/useInfiniteFederationSearchPublicRooms.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/useMatrixServerList.ts
  apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/mocks/client/ServerProviderMock.tsx
  apps/meteor/tests/unit/client/sidebar/header/MatrixFederationSearch/MatrixFederationSearch.spec.tsx
  apps/meteor/tests/unit/client/sidebar/header/actions/Administration.spec.tsx
Labels: stat: QA tested

#29076 refactor: Convert `cors` and `invites` to ts
  apps/meteor/app/cors/client/index.ts
  apps/meteor/app/cors/server/cors.ts
  apps/meteor/app/cors/server/index.ts
  apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.ts
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/highlight-words/client/helper.ts
  apps/meteor/app/integrations/server/lib/mountQueriesBasedOnPermission.ts
  apps/meteor/app/integrations/server/logger.ts
  apps/meteor/app/invites/server/functions/findOrCreateInvite.ts
  apps/meteor/app/invites/server/functions/listInvites.ts
  apps/meteor/app/invites/server/functions/removeInvite.ts
  apps/meteor/app/invites/server/functions/useInviteToken.ts
  apps/meteor/app/invites/server/functions/validateInviteToken.ts
  apps/meteor/app/threads/server/functions.ts
  packages/core-services/src/Events.ts
Labels: stat: needs QA

#29026 regression: Fixed department fowarding not accounting for empty array
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/lib/Helper.js
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeForwardRoomToDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28910 fix: External avatar url provider for rooms not respected.
  apps/meteor/app/utils/client/getRoomAvatarURL.ts
  apps/meteor/client/lib/rooms/roomTypes/private.ts
  apps/meteor/client/lib/rooms/roomTypes/public.ts
  apps/meteor/tests/e2e/avatar-settings.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/utils/create-target-channel.ts
Labels: stat: ready to merge, stat: QA tested

#29113 refactor: Replace `useForm` in favor of RHF on `NotificationPreferences`
  apps/meteor/client/providers/CustomSoundProvider.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.stories.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesForm.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/components/NotificationPreference.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/components/Preferences.tsx
Labels: stat: ready to merge, stat: QA skipped

#29110 tests: fix flaky canned responses test
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesPage.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx
Labels: stat: QA skipped

#29122 chore: Script to replace all i18n interpolation values to i18next compatible ones
  packages/i18n/.eslintrc.json
  packages/i18n/babel.config.cjs
  packages/i18n/jest.config.mjs
  packages/i18n/package.json
  packages/i18n/src/index.mjs
  packages/i18n/src/index.spec.mjs
  yarn.lock
Labels: stat: needs QA

#29131 regression: "Bad Request" error on custom OAuth token request
  apps/meteor/app/custom-oauth/server/custom_oauth_server.js
Labels: stat: ready to merge, stat: QA skipped

#29055 fix: reset link color
  apps/meteor/app/theme/client/imports/general/reset.css
Labels: stat: ready to merge, stat: QA skipped

#29080 chore: Replace OptionColumn in favor of OptionInput
  apps/meteor/client/components/Sidebar/ListItem.tsx
  apps/meteor/client/components/SortList/GroupingList.tsx
  apps/meteor/client/components/SortList/SortModeList.tsx
  apps/meteor/client/components/SortList/ViewModeList.tsx
  apps/meteor/client/sidebar/header/UserDropdown.tsx
Labels: stat: ready to merge, stat: QA skipped

#29138 chore: `Tag` wrong size in home page
  apps/meteor/client/views/home/cards/CustomContentCard.tsx
Labels: stat: ready to merge, stat: QA skipped

#29144 regression: Model `upsert` doesn't exist anymore
  apps/meteor/app/irc/server/irc-bridge/index.js
  apps/meteor/app/smarsh-connector/server/functions/generateEml.js
Labels: stat: ready to merge, stat: QA skipped

#29141 chore: remove last templates using blaze
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/app/analytics/client/index.ts
  apps/meteor/app/analytics/client/loadScript.ts
  apps/meteor/app/livechat/client/externalFrame/ExternalFrameContainer.tsx
  apps/meteor/app/livechat/client/externalFrame/externalFrameContainer.html
  apps/meteor/app/livechat/client/externalFrame/externalFrameContainer.js
  apps/meteor/app/livechat/client/externalFrame/index.ts
  apps/meteor/app/livechat/client/externalFrame/tabBar.ts
  apps/meteor/app/logger/client/index.ts
  apps/meteor/app/logger/client/logger.js
  apps/meteor/app/ui-master/client/index.ts
  apps/meteor/app/ui-master/client/loading/index.ts
  apps/meteor/app/ui-master/client/loading/loading.css
  apps/meteor/app/ui-master/client/loading/loading.html
  apps/meteor/app/ui-message/client/index.ts
  apps/meteor/app/ui-message/client/popup/messagePopupSlashCommandPreview.html
  apps/meteor/app/ui-message/client/popup/messagePopupSlashCommandPreview.ts
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/app/ui-utils/client/lib/messageContext.ts
  apps/meteor/app/ui/client/views/app/photoswipeContent.html
  apps/meteor/app/ui/client/views/app/photoswipeContent.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/lib/portals/blazePortals.ts
  apps/meteor/client/lib/portals/createTemplateForComponent.ts
  apps/meteor/client/lib/rooms/roomCoordinator.tsx
  apps/meteor/client/lib/rooms/roomExit.ts
  apps/meteor/client/main.ts
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/templateHelpers/avatarUrlFromUsername.ts
  apps/meteor/client/templateHelpers/emojiUrlFromName.ts
  apps/meteor/client/templateHelpers/hasPermission.ts
  apps/meteor/client/templateHelpers/index.ts
  apps/meteor/client/templateHelpers/log.ts
  apps/meteor/client/templateHelpers/nrrargs.ts
  apps/meteor/client/templateHelpers/preference.ts
  apps/meteor/client/templateHelpers/renderEmoji.ts
  apps/meteor/client/templateHelpers/setting.ts
  apps/meteor/client/templateHelpers/userHasAllPermission.ts
  apps/meteor/client/views/room/Room/Room.tsx
  apps/meteor/client/views/room/components/BlazeTemplate.tsx
  apps/meteor/client/views/room/components/VerticalBarOldActions.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/components/body/hooks/useRoomMessageContext.ts
  apps/meteor/client/views/room/lib/Toolbox/index.tsx
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/definition/externals/meteor/templating.d.ts
  apps/meteor/ee/app/canned-responses/client/index.js
  apps/meteor/ee/app/canned-responses/client/views/icons.html
  apps/meteor/packages/rocketchat-i18n/package.js
Labels: stat: ready to merge, stat: QA skipped

#28260 chore: convert Rooms Model Raw to TypeScript
  apps/meteor/app/api/server/lib/rooms.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/app/authentication/server/lib/restrictLoginAttempts.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/livechat/server/hooks/offlineMessageToChannel.ts
  apps/meteor/app/slashcommands-hide/server/hide.ts
  apps/meteor/app/slashcommands-inviteall/server/server.ts
  apps/meteor/ee/server/lib/engagementDashboard/channels.ts
  apps/meteor/server/models/raw/Rooms.js
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/services/federation/domain/FederatedRoom.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
  apps/meteor/server/services/team/service.ts
  packages/model-typings/src/models/IRoomsModel.ts
Labels: stat: QA skipped

#29150 fix: redirect not authorized and room not found errors
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
Labels: stat: ready to merge, stat: QA tested

#29070 fix: Sidebar vars
  apps/meteor/app/theme/client/imports/general/variables.css
Labels: stat: ready to merge, stat: QA skipped

#29137 regression: submitting text in the LDAP User Search modal reloads the page
  apps/meteor/client/views/admin/settings/groups/LDAPGroupPage.tsx
Labels: stat: ready to merge, stat: QA tested

#29149 refactor: remove all (possible) run as user
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/api/server/v1/integrations.ts
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/apps/server/bridges/rooms.ts
  apps/meteor/app/apps/server/bridges/uploads.ts
  apps/meteor/app/discussion/server/hooks/joinDiscussionOnMessage.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts
  apps/meteor/app/integrations/server/methods/outgoing/addOutgoingIntegration.ts
  apps/meteor/app/lib/server/functions/notifications/index.ts
  apps/meteor/app/lib/server/methods/joinRoom.ts
  apps/meteor/app/livechat/imports/server/rest/inquiries.ts
  apps/meteor/app/livechat/imports/server/rest/upload.ts
  apps/meteor/app/livechat/server/methods/sendFileLivechatMessage.ts
  apps/meteor/app/livechat/server/methods/sendMessageLivechat.ts
  apps/meteor/app/livechat/server/methods/takeInquiry.ts
  apps/meteor/app/nextcloud/server/addWebdavServer.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/slackbridge/server/SlackAdapter.js
  apps/meteor/app/slashcommands-join/server/server.ts
  apps/meteor/app/webdav/server/methods/addWebdavAccount.ts
  apps/meteor/ee/app/livechat/imports/server/rest/departments.js
  apps/meteor/ee/app/livechat/imports/server/rest/inquiries.js
  apps/meteor/ee/app/livechat/imports/server/rest/rooms.js
  apps/meteor/ee/app/livechat/imports/server/rest/sms.js
  apps/meteor/ee/app/livechat/imports/server/rest/upload.js
  apps/meteor/ee/app/livechat/index.js
  apps/meteor/server/lib/ldap/Manager.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/File.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Message.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/User.ts
  apps/meteor/server/services/upload/service.ts
  apps/meteor/server/startup/initialData.js
  packages/core-services/src/types/IUploadService.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/core-typings/src/IWebdavAccount.ts
Labels: stat: needs QA

#29111 refactor: remove run as user from slashcommands (final)
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/bot-helpers/server/index.ts
  apps/meteor/app/channel-settings/server/methods/saveRoomSettings.ts
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/app/lib/server/methods/leaveRoom.ts
  apps/meteor/app/slashcommands-kick/server/server.ts
  apps/meteor/app/slashcommands-leave/server/leave.ts
  apps/meteor/app/slashcommands-msg/server/server.ts
  apps/meteor/app/slashcommands-mute/server/mute.ts
  apps/meteor/app/slashcommands-mute/server/unmute.ts
  apps/meteor/app/slashcommands-status/server/status.ts
  apps/meteor/app/slashcommands-topic/server/topic.ts
  apps/meteor/app/user-status/server/methods/setUserStatus.ts
  apps/meteor/server/methods/muteUserInRoom.ts
  apps/meteor/server/methods/removeUserFromRoom.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/methods/unmuteUserInRoom.ts
Labels: stat: needs QA

#29157 chore: Update fuselage packages
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: QA skipped

#29136 chore: Improve `EmojiPicker` UI
  apps/meteor/app/emoji/client/helpers.ts
  apps/meteor/client/components/UserStatusMenu.tsx
  apps/meteor/client/components/message/toolbox/DesktopToolboxDropdown.tsx
  apps/meteor/client/contexts/EmojiPickerContext.ts
  apps/meteor/client/providers/EmojiPickerProvider.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/views/composer/EmojiPicker/CategoriesResult.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiCategoryRow.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiElement.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPickerCategoryItem.tsx
  apps/meteor/client/views/composer/EmojiPicker/SearchingResultWrapper.tsx
  apps/meteor/client/views/composer/EmojiPicker/ToneSelector/ToneItem.tsx
  apps/meteor/client/views/composer/EmojiPicker/ToneSelector/ToneSelector.tsx
  apps/meteor/client/views/composer/EmojiPicker/ToneSelector/ToneSelectorWrapper.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/ui-client/src/components/EmojiPicker/EmojiPickerCategoryHeader.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerCategoryWrapper.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerContainer.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerFooter.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerHeader.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerListArea.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerPreview.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerPreviewArea.tsx
  packages/ui-client/src/components/EmojiPicker/index.ts
  yarn.lock
Labels: stat: needs QA

#29092 chore: add status-bullet colors on palettes
  ee/packages/ui-theming/src/palette.ts
  ee/packages/ui-theming/src/paletteDark.ts
  ee/packages/ui-theming/src/sidebarPalette.ts
  ee/packages/ui-theming/src/sidebarPaletteDark.ts
Labels: stat: ready to merge, stat: QA skipped

#29127 Release 6.1.6
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
  packages/livechat/src/lib/main.js
Labels: stat: ready to merge, stat: QA tested

#29084 regression: custom emojis are not visible
  apps/meteor/client/components/Emoji.tsx
Labels: type: regression, stat: ready to merge, stat: QA tested

#29170 chore: remove reactive-store package
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
Labels: stat: needs QA

#29107 fix: ui crash if no app requests found
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppRequests/AppRequests.tsx
Labels: stat: ready to merge, stat: QA tested

#27247 ci: trigger repository_dispatch event on release
  .github/workflows/ci.yml
Labels: stat: needs QA

#29178 ci: only trigger repo_dispatch on release event
  .github/workflows/ci.yml
Labels: stat: needs QA

#29176 chore: `EmojiPicker` visual tweaks
  apps/meteor/client/views/composer/EmojiPicker/EmojiCategoryRow.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerCategoryWrapper.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerContainer.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerPreview.tsx
Labels: stat: QA skipped

#28947 fix: Videoconf Avatar Popup
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupInfo.tsx
Labels: stat: ready to merge, stat: QA tested

#29182 regression: missing meta tags
  apps/meteor/client/head.html
  apps/meteor/client/views/root/AppRoot.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#29146 test(omni): Improve test coverage for "Current chats" panel
  apps/meteor/tests/data/api-data.js
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/permissions.helper.ts
  apps/meteor/tests/data/uploads.helper.ts
  apps/meteor/tests/data/user.ts
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
  apps/meteor/tests/end-to-end/api/04-direct-message.js
  apps/meteor/tests/end-to-end/api/10-subscriptions.js
  apps/meteor/tests/end-to-end/api/20-licenses.js
  apps/meteor/tests/end-to-end/api/27-presence.ts
  apps/meteor/tests/end-to-end/api/import.spec.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
  apps/meteor/tests/end-to-end/api/livechat/17-dashboards-ee.ts
  apps/meteor/tests/end-to-end/api/livechat/18-rooms-ee.ts
  apps/meteor/tests/end-to-end/apps/02-send-messages-as-user.js
Labels: stat: needs QA, feat: omnichannel

#29160 regression: Change the apps translation namespace to `core`
  apps/meteor/client/lib/utils/applyCustomTranslations.ts
  apps/meteor/ee/client/apps/i18n.js
Labels: stat: ready to merge, stat: QA skipped

#29194 chore: Add interactive-widget meta tag
  apps/meteor/client/views/root/AppRoot.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#26440 chore(deps): Update exif-be-gone, enable eslint no-var-requires
  apps/meteor/package.json
  apps/meteor/server/services/image/service.ts
  yarn.lock
Labels: stat: ready to merge, communityPR, stat: QA skipped

#29191 ci: trigger repository_dispatch event on release
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA skipped

#29192 refactor: replace `useForm` in favor of `RHF` on `AddToken`
  apps/meteor/client/views/account/tokens/AccountTokensTable/AddToken.tsx
Labels: stat: needs QA

#29188 fix(livechat): trigger not evaluating correct url
  packages/livechat/src/lib/triggers.js
Labels: stat: needs QA

#28921 fix: missing suggestions from list of suggested emojis in Emoji Popup
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
Labels: communityPR, stat: needs QA

#29197 chore: Bump fuselage packages
  yarn.lock
Labels: stat: needs QA

#29185 regression: Room avatar upload not working
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
Labels: stat: ready to merge, stat: QA tested

#29190 regression: Opening DM through UserCard takes too long.
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
Labels: stat: ready to merge, stat: QA tested

#29209 fix: name search not working in moderation console
  apps/meteor/server/models/raw/ModerationReports.ts
Labels: stat: ready to merge, stat: QA tested

#27819 fix: Add support for non-alphanumeric letters in LDAP Sync
  apps/meteor/server/lib/ldap/DataConverter.ts
  apps/meteor/server/lib/ldap/Manager.ts
  apps/meteor/server/models/raw/Users.js
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#28665 fix: Password Policy mismatch on user creation with random password
  apps/meteor/app/lib/server/lib/PasswordPolicyClass.js
  apps/meteor/client/views/admin/users/UserForm.js
  apps/meteor/package.json
  yarn.lock
Labels: stat: QA tested

#29214 regression: Escape regex for moderation dashboard filters
  apps/meteor/app/api/server/v1/moderation.ts
Labels: stat: ready to merge, stat: QA skipped

#29215 fix: Migration error when removing 'snipetted' index
  apps/meteor/server/startup/migrations/v287.ts
Labels: stat: ready to merge, stat: QA skipped

#29205 regression: `AppDetails` crash when `documentationUrl` is undefined
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppDetails/AppDetails.tsx
Labels: stat: ready to merge, stat: QA skipped

#29212 regression: Quote message not working for omnichannel visitors
  apps/meteor/app/oembed/server/jumpToMessage.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29210 fix: migration to fix apps in invalid state
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v294.ts
Labels: stat: ready to merge, stat: QA tested

#29213 regression: Fix monitor validation logic for rooms & departments
  apps/meteor/ee/app/livechat-enterprise/server/lib/query.helper.js
Labels: stat: ready to merge, stat: QA tested

#29184 regression: Delete Message Modal not closing on error in deleting a message
  apps/meteor/app/api/server/v1/moderation.ts
  apps/meteor/client/views/admin/moderation/hooks/useDeleteMessage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/27-moderation.ts
Labels: stat: ready to merge, stat: QA tested

#29227 regression: Reply in DM not working with hide_FlexTab
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx
Labels: stat: ready to merge, stat: QA tested

#29229 chore: update Apps-Engine to latest
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29219 [FIX] app status inconsistencies when running multiple instances in a cluster
  apps/meteor/app/apps/server/bridges/activation.ts
  apps/meteor/ee/server/apps/communication/rest.js
  apps/meteor/ee/server/apps/communication/websockets.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/server/services/apps-engine/service.ts
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29220 [FIX] app status inconsistencies when running multiple instances in a cluster
  apps/meteor/app/apps/server/bridges/activation.ts
  apps/meteor/ee/server/apps/communication/rest.js
  apps/meteor/ee/server/apps/communication/websockets.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/server/services/apps-engine/service.ts
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29208 fix: convert OVERWRITE_SETTING type MULTISELECT to array
  apps/meteor/app/settings/server/functions/convertValue.ts
  apps/meteor/app/settings/server/functions/overrideGenerator.ts
  apps/meteor/tests/unit/app/settings/server/functions/settings.tests.ts
Labels: stat: needs QA

#29195 chore: improve change stream error handler
  apps/meteor/server/database/DatabaseWatcher.ts
Labels: stat: needs QA

#29218 Release 6.1.7
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/apps/server/bridges/activation.ts
  apps/meteor/app/lib/server/functions/getFullUserData.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/ee/server/apps/communication/rest.js
  apps/meteor/ee/server/apps/communication/websockets.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/server/startup/migrations/v287.ts
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#29216 [FIX][APPS] Fix setting listener
  apps/meteor/app/apps/server/orchestrator.js
Labels: stat: needs QA

#29234 fix: Media Keys controlling sounds after call ringing
  apps/meteor/app/custom-sounds/client/lib/CustomSounds.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.tsx
  packages/ui-contexts/src/CustomSoundContext.ts
Labels: stat: needs QA

#29064 fix: Typos settings admin panel
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#29240 test: verify omni-visitors can quote messages
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/20-messages.ts
Labels: stat: needs QA

#29221 chore: Remove Meteor.Streamer client usage
  apps/meteor/app/authorization/client/lib/streamer.ts
  apps/meteor/app/emoji-custom/client/notifications/deleteEmojiCustom.ts
  apps/meteor/app/emoji-custom/client/notifications/updateEmojiCustom.ts
  apps/meteor/app/integrations/client/streamer.js
  apps/meteor/app/livechat/client/lib/stream/inquiry.ts
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/app/notifications/client/lib/Notifications.js
  apps/meteor/app/notifications/client/lib/Notifications.ts
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/app/ui/client/lib/UserAction.ts
  apps/meteor/app/utils/client/lib/SDKClient.ts
  apps/meteor/app/webrtc/client/actionLink.tsx
  apps/meteor/client/hooks/lists/useStreamUpdatesForMessageList.ts
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/client/lib/settings/PrivateSettingsCachedCollection.ts
  apps/meteor/client/lib/userData.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/client/providers/ServerProvider.tsx
  apps/meteor/client/startup/UserDeleted.ts
  apps/meteor/client/startup/e2e.ts
  apps/meteor/client/startup/notifications/konchatNotifications.ts
  apps/meteor/client/startup/notifications/updateAvatar.ts
  apps/meteor/client/startup/otr.ts
  apps/meteor/client/startup/roles.ts
  apps/meteor/client/startup/userRoles.ts
  apps/meteor/client/views/admin/import/ImportProgressPage.tsx
  apps/meteor/client/views/admin/integrations/edit/OutgoingWebhookHistoryPage.tsx
  apps/meteor/client/views/meet/CallPage.tsx
  apps/meteor/definition/externals/meteor/meteor.d.ts
  apps/meteor/ee/app/canned-responses/client/startup/responses.js
  apps/meteor/ee/app/canned-responses/client/streamer.js
  apps/meteor/ee/client/apps/communication/websockets.js
  apps/meteor/server/modules/notifications/notifications.module.ts
  packages/ddp-client/src/DDPSDK.ts
  packages/ddp-client/src/legacy/RocketchatSDKLegacy.ts
  packages/ddp-client/src/legacy/types/SDKLegacy.ts
  packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/ddp-client/src/livechat/types/LivechatSDK.ts
  packages/ui-contexts/src/ServerContext/streams.ts
Labels: stat: needs QA

#29193 chore: `ListItem` gap
  apps/meteor/client/components/Sidebar/ListItem.tsx
Labels: stat: ready to merge, stat: QA skipped

#29207 refactor: replace `useForm` in favor of `RHF` on `TwoFactorTOTP`
  apps/meteor/client/views/account/security/TwoFactorTOTP.tsx
Labels: stat: ready to merge, stat: QA skipped

#29233 refactor: replace `useForm` in favor of `RHF` on `TranscriptModal`
  apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx
  apps/meteor/tests/unit/client/components/Omnichannel/modals/TranscriptModal.spec.tsx
Labels: stat: needs QA

#29244 fix: Google Cloud Storage not working
  apps/meteor/app/file-upload/server/config/GoogleStorage.ts
Labels: stat: needs QA

#29243 chore: Move from APIClient to sdk.rest
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.js
  apps/meteor/app/livechat/client/externalFrame/ExternalFrameContainer.tsx
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/ui-message/client/ActionButtonSyncer.ts
  apps/meteor/app/ui-message/client/ActionManager.js
  apps/meteor/app/ui-utils/client/lib/AccountBox.ts
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/app/ui-utils/client/lib/readMessages.ts
  apps/meteor/app/webdav/client/startup/sync.js
  apps/meteor/app/webrtc/client/actionLink.tsx
  apps/meteor/app/webrtc/client/tabBar.tsx
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/lib/OmnichannelRoomIcon.ts
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/client/lib/chats/flows/processSlashCommand.ts
  apps/meteor/client/lib/chats/uploads.ts
  apps/meteor/client/lib/meteorCallWrapper.ts
  apps/meteor/client/lib/presence.ts
  apps/meteor/client/lib/userData.ts
  apps/meteor/client/providers/ServerProvider.tsx
  apps/meteor/client/startup/routes.tsx
  apps/meteor/client/startup/slashCommands/list.ts
  apps/meteor/client/views/invite/InvitePage.tsx
  apps/meteor/client/views/meet/MeetPage.tsx
  apps/meteor/ee/app/canned-responses/client/startup/responses.js
  apps/meteor/ee/client/apps/RealAppsEngineUIHost.js
  apps/meteor/ee/client/apps/communication/websockets.js
  apps/meteor/ee/client/apps/orchestrator.ts
  apps/meteor/ee/client/ecdh.ts
  packages/api-client/src/RestClientInterface.ts
Labels: stat: needs QA

#28927 fix: Change audit main titles
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#29158 fix: download data page show status 403
  apps/meteor/server/routes/userDataDownload.ts
Labels: stat: ready to merge, stat: QA tested

#29120 chore: remove grandfathered app message showing to enterprise workspaces
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/helpers.ts
Labels: stat: ready to merge, stat: QA tested

#29147 fix: Embedded layout stops working after navigation occurs
  apps/meteor/client/views/room/providers/ToolboxProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#29231 refactor: Improve troubleshoot settings
  apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
  apps/meteor/server/settings/troubleshoot.ts
Labels: stat: ready to merge, stat: QA skipped

#29242 chore: `Tag` size on Registration Page
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
Labels: stat: ready to merge, stat: QA skipped

#29054 fix: Fixed canned responses popup adding ! prefix
  apps/meteor/client/views/room/contexts/ComposerPopupContext.ts
  apps/meteor/client/views/room/layout/RoomLayout.tsx
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29020 fix: System throws an error while visitor tries to register in public queue.
  apps/meteor/app/livechat/server/lib/Livechat.js
  packages/livechat/src/routes/Register/container.js
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29246 fix: broken storybook
  apps/meteor/.storybook/main.js
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29172 feat: `AudioPlayer` Implementation
  apps/meteor/client/components/message/content/attachments/file/AudioAttachment.tsx
  apps/meteor/client/components/message/content/urlPreviews/UrlAudioPreview.tsx
  apps/meteor/client/views/room/modals/FileUploadModal/MediaPreview.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29000 chore: Add copy action option to `SaveE2EModal`
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/client/views/e2e/SaveE2EPasswordModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#29256 chore: Composer missing scrollbar color
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/theme/client/imports/general/variables.css
Labels: stat: ready to merge, stat: QA skipped

#29258 Bump vm2 version 3.9.19
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#29259 Bump apps engine version and vm2
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#29257 Bump apps engine and vm2
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/presence/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29262 Bump apps engine and vm2
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29260 Bump apps engine and vm2
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29067 test: use local httpbin container on github CI's
  .github/workflows/ci-test-e2e.yml
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
  docker-compose-ci.yml
Labels: stat: needs QA, feat: architecture

#28636 fix: Members/Channels list infinite scroll
  apps/meteor/client/components/InfiniteListAnchor.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/client/views/teams/contextualBar/channels/BaseTeamsChannels.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.tsx
Labels: stat: ready to merge, stat: QA tested

#29271 Release 6.2.1
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#29095 feat(Marketplace): Scroll to the top of the marketplace apps list when page changed
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContentBody.tsx
Labels: stat: ready to merge, stat: QA tested

#29277 regression: fix console warnings
  apps/meteor/client/views/admin/invites/InvitesPage.tsx
  apps/meteor/client/views/root/AppRoot.tsx
Labels: stat: ready to merge, stat: QA skipped

#29255 chore: Add `roomName` on Composer placeholder
  .changeset/rare-bats-compare.md
  apps/meteor/client/hooks/useRoomName.ts
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/components/body/composer/messageBox/hooks/useMessageBoxPlaceholder.ts
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/team-management.spec.ts
  apps/meteor/tests/e2e/threads.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#29279 ci: skip husky hooks on ci
  .github/workflows/changesets.yml
Labels: stat: needs QA

#28795 fix: Handle login services errors
  .changeset/beige-windows-film.md
  packages/web-ui-registration/src/LoginForm.tsx
  packages/web-ui-registration/src/LoginServices.tsx
  packages/web-ui-registration/src/LoginServicesButton.tsx
Labels: stat: ready to merge, stat: QA tested

#29287 regression(push): fix error when adding headers to send push notification
  apps/meteor/app/push/server/push.js
Labels: stat: ready to merge, stat: QA skipped

#29251 chore: `ListItem` stories
  apps/meteor/client/components/ListItem.stories.tsx
Labels: stat: ready to merge, stat: QA skipped

#29278 fix: Livechat `CSP` whitelist validation
  .changeset/mean-bottles-work.md
  apps/meteor/app/livechat/server/livechat.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29128 chore: improve server stream typings
  .changeset/poor-pants-suffer.md
  apps/meteor/app/apps/server/bridges/messages.ts
  apps/meteor/app/authorization/server/methods/addUserToRole.ts
  apps/meteor/app/authorization/server/methods/removeUserFromRole.ts
  apps/meteor/app/integrations/server/methods/clearIntegrationHistory.ts
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/app/notifications/server/lib/Notifications.ts
  apps/meteor/app/notifications/server/lib/Presence.ts
  apps/meteor/app/search/server/search.internalService.ts
  apps/meteor/client/lib/userData.ts
  apps/meteor/client/startup/incomingMessages.ts
  apps/meteor/client/startup/notifications/konchatNotifications.ts
  apps/meteor/client/startup/notifications/updateAvatar.ts
  apps/meteor/client/startup/userRoles.ts
  apps/meteor/client/views/room/components/body/hooks/useRoomRolesManagement.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/definition/externals/meteor/rocketchat-streamer.d.ts
  apps/meteor/ee/app/canned-responses/client/startup/responses.js
  apps/meteor/ee/app/canned-responses/server/hooks/onSaveAgentDepartment.ts
  apps/meteor/ee/server/apps/communication/websockets.ts
  apps/meteor/ee/server/lib/roles/updateRole.ts
  apps/meteor/ee/server/lib/syncUserRoles.ts
  apps/meteor/server/methods/addRoomLeader.ts
  apps/meteor/server/methods/addRoomModerator.ts
  apps/meteor/server/methods/addRoomOwner.ts
  apps/meteor/server/methods/removeRoomModerator.ts
  apps/meteor/server/methods/removeRoomOwner.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  apps/meteor/server/modules/streamer/streamer.module.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
  apps/meteor/server/services/meteor/service.ts
  apps/meteor/server/services/push/service.ts
  apps/meteor/server/services/video-conference/service.ts
  ee/apps/ddp-streamer/Dockerfile
  ee/apps/ddp-streamer/package.json
  ee/apps/ddp-streamer/src/Streamer.ts
  packages/core-services/src/Events.ts
  packages/core-typings/src/IUser.ts
  packages/ddp-client/src/legacy/RocketchatSDKLegacy.ts
  packages/ddp-client/src/legacy/types/SDKLegacy.ts
  packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/ui-contexts/src/ServerContext/streams.ts
  packages/ui-contexts/src/index.ts
  yarn.lock
Labels: stat: needs QA

#29081 refactor(integrations): Replace Fibers dependency by Deasync
  apps/meteor/app/apps/server/bridges/internal.ts
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/app/integrations/server/lib/triggerHandler.js
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/package.json
  apps/meteor/server/deasync/deasync.ts
  yarn.lock
Labels: stat: needs QA

#29263 chore: Move 2fa challenge handler to rest api package
  .changeset/seven-rules-search.md
  .changeset/shy-maps-admire.md
  apps/meteor/app/2fa/client/overrideMeteorCall.ts
  apps/meteor/app/2fa/server/code/index.ts
  apps/meteor/app/utils/client/lib/RestApiClient.ts
  apps/meteor/client/components/TwoFactorModal/TwoFactorEmailModal.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorModal.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorPasswordModal.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorTotpModal.tsx
  apps/meteor/client/lib/2fa/process2faReturn.ts
  packages/api-client/__tests__/2fahandling.spec.ts
  packages/api-client/jest.config.ts
  packages/api-client/package.json
  packages/api-client/src/RestClientInterface.ts
  packages/api-client/src/errors.ts
  packages/api-client/src/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28975 fix: respect useEmoji pref on messages
  .changeset/large-penguins-suffer.md
  apps/meteor/client/components/GazzodownText.tsx
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
  packages/gazzodown/src/Markup.spec.tsx
  packages/gazzodown/src/MarkupInteractionContext.ts
  packages/gazzodown/src/emoji/Emoji.tsx
Labels: stat: ready to merge, stat: QA tested

#29296 fix: EmojiPicker position on small views
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  packages/ui-client/src/components/EmojiPicker/EmojiPickerContainer.tsx
Labels: stat: needs QA

#29297 chore: Move some compatible changes back from meteor 3 branch
  apps/meteor/app/2fa/server/code/PasswordCheckFallback.ts
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/app/cas/server/cas_server.js
  apps/meteor/app/custom-sounds/server/methods/uploadCustomSound.ts
  apps/meteor/app/emoji-custom/server/methods/uploadEmojiCustom.ts
  apps/meteor/app/file-upload/server/lib/proxy.ts
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/lib/server/methods/deleteUserOwnAccount.ts
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/definition/externals/meteor/oauth2server.d.ts
  apps/meteor/packages/meteor-restivus/lib/auth.js
  apps/meteor/packages/meteor-user-presence/package.js
  apps/meteor/packages/rocketchat-mongo-config/server/index.js
  apps/meteor/server/lib/compareUserPassword.ts
  apps/meteor/server/lib/compareUserPasswordHistory.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/methods/setUserPassword.ts
  apps/meteor/server/services/team/service.ts
  apps/meteor/server/ufs/index.ts
  apps/meteor/server/ufs/ufs-gridfs.ts
  apps/meteor/server/ufs/ufs-local.ts
  apps/meteor/server/ufs/ufs-methods.ts
  apps/meteor/server/ufs/ufs-server.ts
  apps/meteor/server/ufs/ufs.ts
  apps/meteor/tests/end-to-end/api/livechat/20-messages.ts
Labels: stat: needs QA

#29298 Release 6.2.2
  HISTORY.md
  apps/meteor/.docker/Dockerfile.rhel
  apps/meteor/app/livechat/server/livechat.ts
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
Labels: stat: needs QA

#29294 chore: Update meteor to version 2.12
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/release
  apps/meteor/.meteor/versions
  apps/meteor/package.json
  apps/meteor/server/startup/serverRunning.js
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29311 chore: Use Assets’ async API
  apps/meteor/app/livechat/server/livechat.ts
  apps/meteor/app/ui-master/server/index.js
  apps/meteor/definition/externals/meteor/meteor.d.ts
  apps/meteor/server/lib/dataExport/sendViaEmail.ts
  apps/meteor/server/lib/getMomentLocale.ts
  apps/meteor/server/routes/i18n.ts
  apps/meteor/server/startup/initialData.js
Labels: stat: ready to merge, stat: QA skipped

#28814 feat: [ENTERPRISE] Add setting to control user merge on LDAP Background Sync
  .changeset/cold-meals-camp.md
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/settings/ldap.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#29327 regression: fix sdk regressions
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  packages/api-client/__tests__/2fahandling.spec.ts
  packages/api-client/src/index.ts
  packages/ui-contexts/src/ServerContext/streams.ts
Labels: stat: needs QA

#29293 fix: unable to create user if Accounts_ManuallyApproveNewUsers is enabled
  .changeset/heavy-years-repeat.md
  apps/meteor/app/authentication/server/startup/index.js
Labels: stat: needs QA

#29129 chore: hide releases tab for private apps on marketplace
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPageTabs.tsx
Labels: feat: apps, stat: ready to merge, stat: QA tested

#29344 test: Fix Omnichannel Webhooks tests
  .github/workflows/ci-test-e2e.yml
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
  docker-compose-ci.yml
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#29340 regression: Fix secondary presence streamer
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/app/notifications/server/lib/Presence.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
Labels: stat: ready to merge, stat: QA skipped

#29286 fix: Application crashes when clicking on Analytics option in Omnichannel view page
  .changeset/wild-lizards-guess.md
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29326 chore: add `badge-level-0` token
  ee/packages/ui-theming/src/palette.ts
  ee/packages/ui-theming/src/paletteDark.ts
Labels: stat: ready to merge, stat: QA skipped

#29353 chore: Separate ownership of tests for back and front
  .github/CODEOWNERS
Labels: stat: ready to merge, stat: QA skipped

#29350 chore: Normalize the caps bar usage
  apps/meteor/client/components/GenericResourceUsage/GenericResourceUsage.tsx
  apps/meteor/client/components/GenericResourceUsage/GenericResourceUsageSkeleton.tsx
  apps/meteor/client/components/GenericResourceUsage/index.ts
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserActiveConnections.tsx
  apps/meteor/client/views/marketplace/components/EnabledAppsCount.tsx
  apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
  apps/meteor/client/views/marketplace/hooks/useAppsCountQuery.ts
  apps/meteor/ee/client/views/admin/users/SeatsCapUsage/SeatsCapUsage.tsx
  apps/meteor/ee/client/views/admin/users/useSeatsCap.ts
Labels: stat: ready to merge, stat: QA skipped

#29037 feat(apps): Disabling apps on trial license expiration
  apps/meteor/ee/app/license/server/license.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/startup/apps/index.ts
  apps/meteor/ee/server/startup/apps/trialExpiration.ts
  apps/meteor/ee/server/startup/index.ts
Labels: stat: ready to merge, stat: QA tested

#29316 chore: update status-bullet colors
  ee/packages/ui-theming/src/paletteDark.ts
  ee/packages/ui-theming/src/sidebarPalette.ts
  ee/packages/ui-theming/src/sidebarPaletteDark.ts
Labels: stat: QA skipped

#27121 fix: File upload in Safari, IOS devices
  .changeset/nervous-masks-speak.md
  apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
Labels: stat: ready to merge, stat: QA skipped

#29321 chore: update `status-warning-2` color
  ee/packages/ui-theming/src/palette.ts
  ee/packages/ui-theming/src/paletteDark.ts
Labels: stat: ready to merge, stat: QA skipped

#29360 ci: omit vite log
  packages/uikit-playground/vite.config.ts
Labels: stat: needs QA

#29358 fix: Missing await on agent leave action
  apps/meteor/app/livechat/server/lib/stream/agentStatus.ts
Labels: stat: ready to merge, stat: QA skipped, feat: omnichannel

#29369 chore: small tricks with keys and invalidations with marketplace page
  apps/meteor/client/views/marketplace/AppsProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#28081 fix: Added check if count is truthy on `cleanRoomHistory`
  .changeset/polite-clouds-notice.md
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/tests/end-to-end/api/24-methods.js
Labels: stat: ready to merge, stat: QA tested, feat: team-collab

#29374 regression: Missing loading indicator
  apps/meteor/client/components/LoadingIndicator.tsx
  apps/meteor/client/views/room/components/body/LoadingMessagesIndicator.tsx
  apps/meteor/client/views/root/PageLoading.tsx
  yarn.lock
Labels: stat: QA skipped

#28367 fix: broken error messages on room.saveInfo & missing CF validations on omni/contact api
  .changeset/blue-cougars-wave.md
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29336 feat: Added attachments to contact history message list
  .changeset/strange-clocks-peel.md
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#28948 refactor: Omnichannel Department re-write
  .changeset/mean-keys-rhyme.md
  apps/meteor/client/hooks/useRoomsList.ts
  apps/meteor/client/views/omnichannel/departments/AgentRow.js
  apps/meteor/client/views/omnichannel/departments/ArchivedDepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/Count.js
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/AddAgent.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/AgentAvatar.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/AgentRow.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/DepartmentAgentsTable.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/RemoveAgentButton.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentTags/index.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsAgentsTable.js
  apps/meteor/client/views/omnichannel/departments/DepartmentsPageWithData.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.js
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithAllowedForwardData.js
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithAllowedForwardData.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithData.js
  apps/meteor/client/views/omnichannel/departments/EditDepartmentWithData.tsx
  apps/meteor/client/views/omnichannel/departments/NewDepartment.tsx
  apps/meteor/client/views/omnichannel/departments/Order.js
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentBusinessHours.js
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentBusinessHours.tsx
  apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29250 fix: Changed contact form async validations to onSubmit
  .changeset/great-dolphins-remember.md
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
  apps/meteor/tests/e2e/omnichannel-contact-center.spec.ts
Labels: stat: ready to merge, stat: QA tested, feat: omnichannel

#29162 chore: New mention styles
  packages/gazzodown/src/mentions/ChannelMentionElement.tsx
  packages/gazzodown/src/mentions/UserMentionElement.tsx
Labels: stat: ready to merge, stat: QA skipped

#29142 feat: Implement new Administration kebab reroute algorithm
  apps/meteor/client/components/AdministrationList/AdministrationList.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.spec.tsx
  apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx
  apps/meteor/client/hooks/useDefaultRoute.ts
  apps/meteor/client/lib/createSidebarItems.ts
  apps/meteor/client/views/admin/AdministrationRouter.tsx
  apps/meteor/tests/e2e/administration-menu.spec.ts
Labels: stat: ready to merge, stat: QA tested

#29375 chore: Change ddpsdk.stream to return subscription
  apps/meteor/app/utils/client/lib/SDKClient.ts
  apps/meteor/client/providers/ServerProvider.tsx
  apps/meteor/definition/externals/meteor/meteor.d.ts
  packages/api-client/tsconfig.json
  packages/ddp-client/__tests__/ClientStream.spec.ts
  packages/ddp-client/__tests__/Connection.spec.ts
  packages/ddp-client/__tests__/DDPSDK.spec.ts
  packages/ddp-client/__tests__/Timeout.spec.ts
  packages/ddp-client/__tests__/helpers/index.ts
  packages/ddp-client/jest.config.ts
  packages/ddp-client/package.json
  packages/ddp-client/src/ClientStream.ts
  packages/ddp-client/src/Connection.ts
  packages/ddp-client/src/DDPSDK.ts
  packages/ddp-client/src/README.md
  packages/ddp-client/src/TimeoutControl.ts
  packages/ddp-client/src/legacy/RocketchatSDKLegacy.ts
  packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/ddp-client/src/types/Account.ts
  packages/ddp-client/src/types/ClientStream.ts
  packages/ddp-client/src/types/SDK.ts
  packages/ddp-client/src/types/Subscription.ts
  packages/ui-contexts/src/ServerContext/ServerContext.ts
  packages/ui-contexts/src/hooks/useStream.ts
Labels: stat: needs QA

#29289 regression(push): fix error when selecting what to import
  apps/meteor/app/importer/server/classes/ImporterBase.js
Labels: stat: needs QA

#29395 fix: fix wrong %s translations
  .changeset/khaki-avocados-fix.md
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
Labels: stat: needs QA

#29396 regression: `t` using always sprintf
  apps/meteor/app/utils/lib/i18n.ts
Labels: stat: ready to merge, stat: QA skipped

#29397 chore: `ToolboxAction` pressed state
  apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
  packages/ui-client/src/components/Header/ToolBox/ToolBoxAction.tsx
Labels: stat: ready to merge, stat: QA skipped

#29380 chore(ddp-sdk): ts-jest -> swc/jest
  packages/api-client/__tests__/2fahandling.spec.ts
  packages/api-client/jest.config.ts
  packages/api-client/package.json
  packages/ddp-client/__tests__/ClientStream.spec.ts
  packages/ddp-client/__tests__/Connection.spec.ts
  packages/ddp-client/__tests__/DDPSDK.spec.ts
  packages/ddp-client/__tests__/helpers/index.ts
  packages/ddp-client/jest.config.ts
  packages/ddp-client/package.json
  packages/gazzodown/jest.config.ts
  packages/gazzodown/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#28738 fix: marketplace filters are changing size
  apps/meteor/client/views/marketplace/AppsPage/AppsFilters.tsx
Labels: stat: ready to merge, stat: QA tested

#29412 regression(ui-client): Toolbox action button badge in the wrong position
  packages/ui-client/src/components/Header/ToolBox/ToolBoxAction.tsx
Labels: stat: ready to merge, stat: QA skipped

#29394 fix: Apps settings i18n translation
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppSettings/AppSetting.tsx
Labels: stat: ready to merge, stat: QA skipped

#29048 fix: Broken link fixed inside webhook menu
  apps/meteor/client/views/omnichannel/webhooks/WebhooksPage.js
Labels: stat: ready to merge, communityPR, stat: QA skipped

#29368 refactor: replace with new `Select`
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationSearchModalContent.tsx
  apps/meteor/client/views/account/integrations/AccountIntegrationsPage.tsx
  apps/meteor/client/views/account/preferences/PreferencesMessagesSection.tsx
  apps/meteor/client/views/account/preferences/PreferencesNotificationsSection.tsx
  apps/meteor/client/views/admin/settings/inputs/LanguageSettingInput.stories.tsx
  apps/meteor/client/views/admin/settings/inputs/LanguageSettingInput.tsx
  apps/meteor/client/views/marketplace/components/RadioDropDown/RadioDownAnchor.tsx
  apps/meteor/client/views/marketplace/components/RadioDropDown/RadioDropDown.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/analytics/AnalyticsPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/queueList/QueueListFilter.tsx
  apps/meteor/client/views/room/contextualBar/ExportMessages/ExportMessages.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/RoomFiles.js
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/EditInviteLink.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
  apps/meteor/client/views/teams/contextualBar/channels/BaseTeamsChannels.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/PrioritiesSelect.tsx
  apps/meteor/ee/client/omnichannel/components/contextualBar/CannedResponse/CannedResponseList.tsx
  apps/meteor/package.json
  apps/meteor/tests/e2e/omnichannel-agents.spec.ts
  yarn.lock
Labels: stat: needs QA
