Repository RocketChat/Rocket.Chat, pull requests merged in 2023-11, with the labels that each got.

#30776 chore: Replace `useForm` in favor of RHF on Omnichannel Triggers
  apps/meteor/client/components/GenericError/GenericError.tsx
  apps/meteor/client/components/GenericError/index.ts
  apps/meteor/client/views/omnichannel/routes.ts
  apps/meteor/client/views/omnichannel/triggers/EditTrigger.tsx
  apps/meteor/client/views/omnichannel/triggers/EditTriggerPage.js
  apps/meteor/client/views/omnichannel/triggers/EditTriggerPageContainer.js
  apps/meteor/client/views/omnichannel/triggers/EditTriggerWithData.tsx
  apps/meteor/client/views/omnichannel/triggers/NewTriggerPage.js
  apps/meteor/client/views/omnichannel/triggers/TriggersForm.stories.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersForm.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersPage.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersRoute.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersTable.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-triggers.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: needs QA

#30715 chore: remove upgrade page and references
  apps/meteor/client/components/GenericUpsellModal/hooks/useUpsellActions.ts
  apps/meteor/client/components/Omnichannel/modals/EnterpriseDepartmentsModal.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.spec.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/views/admin/AdministrationRouter.tsx
  apps/meteor/client/views/admin/permissions/CustomRoleUpsellModal.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebar/AdminSidebarPages.tsx
  apps/meteor/client/views/admin/sidebar/UpgradeTab.tsx
  apps/meteor/client/views/admin/upgrade/UpgradePage/UpgradePage.tsx
  apps/meteor/client/views/admin/upgrade/UpgradePage/index.ts
  apps/meteor/client/views/admin/upgrade/UpgradePageError/UpgradePageError.tsx
  apps/meteor/client/views/admin/upgrade/UpgradePageError/index.ts
  apps/meteor/client/views/hooks/useUpgradeTabParams.ts
  apps/meteor/client/views/marketplace/AppInstallPage.js
  apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
  apps/meteor/client/views/marketplace/components/BannerEnterpriseTrialEnded.tsx
  apps/meteor/client/views/marketplace/hooks/useAppInstallationHandler.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx
  apps/meteor/lib/upgradeTab.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/administration-menu.spec.ts
  apps/meteor/tests/mocks/client/RouterContextMock.tsx
  apps/meteor/tests/unit/lib/upgradeTab.spec.ts
Labels: stat: needs QA

#30763 regression: Inquiries not showing "over MAC limit" indicator
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/client/hooks/omnichannel/useIsRoomOverMacLimit.tsx
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/services/omnichannel/service.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/23-mac.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/Events.ts
  packages/core-typings/src/IInquiry.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
Labels: stat: needs QA, squad: omnichannel

#30828 chore: update matrix dependencies (#30521)
  apps/meteor/package.json
  package.json
  yarn.lock
Labels: stat: needs QA

#30818 chore: normalize `Button` loading states
  apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx
  apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx
  apps/meteor/client/sidebar/header/CreateDirectMessage.tsx
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationManageServerModal.tsx
  apps/meteor/client/views/account/accessibility/AccessibilityPage.tsx
  apps/meteor/client/views/account/profile/AccountProfileForm.tsx
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
  apps/meteor/client/views/admin/cloud/PasteStep.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisterWorkspaceTokenModal.tsx
  apps/meteor/client/views/admin/cloud/modals/RegisteredWorkspaceModal.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmojiWithData.tsx
  apps/meteor/client/views/admin/customSounds/EditCustomSound.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusFormWithData.tsx
  apps/meteor/client/views/admin/import/ImportHistoryPage.tsx
  apps/meteor/client/views/admin/import/NewImportPage.js
  apps/meteor/client/views/admin/oauthApps/EditOauthAppWithData.tsx
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
  apps/meteor/client/views/marketplace/AppInstallPage.js
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
  apps/meteor/client/views/omnichannel/webhooks/WebhooksPage.tsx
  apps/meteor/client/views/outlookCalendar/OutlookEventsList/OutlookEventsList.tsx
  apps/meteor/client/views/room/composer/ComposerReadOnly.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/contextualBar/ExportMessages/MailExportForm.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/EditInviteLink.tsx
  apps/meteor/client/views/room/modals/ForwardMessageModal/ForwardMessageModal.tsx
  apps/meteor/client/views/room/webdav/AddWebdavAccountModal.tsx
  apps/meteor/client/views/room/webdav/SaveToWebdavModal.tsx
  apps/meteor/ee/client/omnichannel/monitors/MonitorsTable.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
  apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  packages/web-ui-registration/src/EmailConfirmationForm.tsx
  packages/web-ui-registration/src/LoginForm.tsx
  packages/web-ui-registration/src/RegisterForm.tsx
  packages/web-ui-registration/src/ResetPassword/ResetPasswordPage.tsx
  packages/web-ui-registration/src/ResetPasswordForm.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#30830 chore: Bring back the Plan tag based on license tag names
  apps/meteor/client/components/PlanTag.tsx
Labels: stat: needs QA

#30787 chore: Replace `enterprise` labels to `premium`
  .changeset/sour-hotels-flash.md
  apps/meteor/client/components/Omnichannel/modals/EnterpriseDepartmentsModal.tsx
  apps/meteor/client/views/account/omnichannel/PreferencesConversationTranscript.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusService.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfConfigModal.tsx
  apps/meteor/ee/app/license/server/settings.ts
  apps/meteor/ee/server/settings/ldap.ts
  apps/meteor/ee/server/settings/saml.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#30822 feat: add `channels.images` endpoint
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/server/models/raw/Uploads.ts
  packages/model-typings/src/models/IUploadsModel.ts
  packages/rest-typings/src/v1/channels/ChannelsImagesProps.ts
  packages/rest-typings/src/v1/channels/channels.ts
  packages/rest-typings/src/v1/channels/index.ts
Labels: stat: needs QA

#30820 test: Omnichannel Users & Departments
  apps/meteor/tests/data/livechat/units.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  apps/meteor/tests/end-to-end/api/livechat/22-monitors.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30827 Release 6.4.5
  .changeset/bump-patch-1698839399442.md
  apps/meteor/app/cors/server/cors.ts
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-mongo-config/server/index.js
  apps/meteor/server/lib/dataExport/uploadZipFile.ts
  apps/meteor/server/settings/troubleshoot.ts
  package.json
  yarn.lock
Labels: stat: needs QA

#30840 regression: wrong app limits displayed on the UI
  ee/packages/license/src/deprecated.ts
  ee/packages/license/src/getLicenseLimit.spec.ts
  ee/packages/license/src/license.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#30806 chore: Change user created page message from string to states
  apps/meteor/client/views/admin/users/AdminUserCreated.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/admin/users/AdminUserSetRandomPasswordRadios.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#30851 regression: license v3 decrypt when using v2 public key
  ee/packages/license/src/token.ts
Labels: stat: needs QA

#30849 chore: Re-org `DeviceManagement` files inside EE folder
  apps/meteor/ee/client/components/deviceManagement/DeviceIcon.tsx
  apps/meteor/ee/client/components/deviceManagement/DeviceManagementTable/DeviceManagementTable.tsx
  apps/meteor/ee/client/components/deviceManagement/DeviceManagementTable/index.ts
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountRow.tsx
  apps/meteor/ee/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountTable.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminRow.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx
Labels: stat: ready to merge, stat: QA skipped

#30852 refactor: Remove `formsSubscription` hooks in favor of `EE` components
  apps/meteor/client/components/Omnichannel/Tags.tsx
  apps/meteor/client/views/omnichannel/additionalForms.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/businessHours/BusinessHoursFormContainer.js
  apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
  apps/meteor/client/views/omnichannel/customFields/EditCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/customFields/NewCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/ContactManager.js
  apps/meteor/ee/client/omnichannel/additionalForms/CurrentChatTags.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/CustomFieldsAdditionalFormContainer.js
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentBusinessHours.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentForwarding.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/EeNumberInput.js
  apps/meteor/ee/client/omnichannel/additionalForms/EeTextAreaInput.js
  apps/meteor/ee/client/omnichannel/additionalForms/MaxChatsPerAgentContainer.js
  apps/meteor/ee/client/omnichannel/additionalForms/MaxChatsPerAgentDisplay.js
  apps/meteor/ee/client/omnichannel/additionalForms/PrioritiesSelect.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/SlaPoliciesSelect.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/register.ts
  apps/meteor/ee/client/omnichannel/index.ts
  apps/meteor/ee/client/omnichannel/tags/CurrentChatTags.tsx
Labels: stat: ready to merge, stat: QA skipped

#30831 refactor: Integrations Forms & UI
  apps/meteor/app/integrations/lib/outgoingEvents.ts
  apps/meteor/app/integrations/server/lib/updateHistory.ts
  apps/meteor/client/views/admin/integrations/EditIntegrationsPage.tsx
  apps/meteor/client/views/admin/integrations/EditIntegrationsPageWithData.tsx
  apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js
  apps/meteor/client/views/admin/integrations/IntegrationsPage.tsx
  apps/meteor/client/views/admin/integrations/IntegrationsRoute.tsx
  apps/meteor/client/views/admin/integrations/NewBot.tsx
  apps/meteor/client/views/admin/integrations/NewZapier.tsx
  apps/meteor/client/views/admin/integrations/OutgoiongWebhookForm.js
  apps/meteor/client/views/admin/integrations/edit/EditIncomingWebhook.js
  apps/meteor/client/views/admin/integrations/edit/EditIncomingWebhookWithData.js
  apps/meteor/client/views/admin/integrations/edit/EditIntegrationsPage.js
  apps/meteor/client/views/admin/integrations/edit/EditOutgoingWebhook.js
  apps/meteor/client/views/admin/integrations/edit/EditOutgoingWebhookWithData.js
  apps/meteor/client/views/admin/integrations/hooks/useCreateIntegration.ts
  apps/meteor/client/views/admin/integrations/hooks/useDeleteIntegration.ts
  apps/meteor/client/views/admin/integrations/hooks/useExampleIncomingData.tsx
  apps/meteor/client/views/admin/integrations/hooks/useUpdateIntegration.ts
  apps/meteor/client/views/admin/integrations/incoming/EditIncomingWebhook.tsx
  apps/meteor/client/views/admin/integrations/incoming/IncomingWebhookForm.tsx
  apps/meteor/client/views/admin/integrations/new/NewIncomingWebhook.js
  apps/meteor/client/views/admin/integrations/new/NewIntegrationsPage.js
  apps/meteor/client/views/admin/integrations/new/NewOutgoingWebhook.js
  apps/meteor/client/views/admin/integrations/outgoing/EditOutgoingWebhook.tsx
  apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx
  apps/meteor/client/views/admin/integrations/outgoing/history/HistoryContent.tsx
  apps/meteor/client/views/admin/integrations/outgoing/history/HistoryItem.tsx
  apps/meteor/client/views/admin/integrations/outgoing/history/OutgoingWebhookHistoryPage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/core-typings/src/IIntegrationHistory.ts
  packages/rest-typings/src/v1/integrations/IntegrationsUpdateProps.ts
Labels: stat: needs QA

#30848 chore: Change "Enterprise" labels do "Premium"
  apps/meteor/client/components/Omnichannel/modals/EnterpriseDepartmentsModal.tsx
  apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/client/sidebar/sections/actions/OmnichannelCallDialPad.tsx
  apps/meteor/client/views/home/cards/CustomContentCard.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsPage.tsx
  apps/meteor/client/views/marketplace/AppsRoute.tsx
  apps/meteor/client/views/marketplace/components/BannerEnterpriseTrialEnded.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfoCallButton.tsx
  apps/meteor/client/views/omnichannel/directory/components/CallDialpadButton.tsx
  apps/meteor/client/views/room/composer/ComposerFederation/ComposerFederationJoinRoomDisabled.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/federation/application/room/sender/RoomInternalValidator.ts
  apps/meteor/server/settings/setup-wizard.ts
  apps/meteor/tests/unit/server/federation/application/room/sender/RoomInternalValidator.spec.ts
Labels: stat: needs QA

#30867 chore: new modules to license v2 enterprise bundle
  ee/packages/license/src/v2/bundles.ts
Labels: stat: needs QA

#30766 fix: Invite link registration not navigating to homepage
  .changeset/blue-trainers-explain.md
  apps/meteor/client/views/invite/InvitePage.tsx
  apps/meteor/client/views/invite/hooks/useInviteTokenMutation.ts
  apps/meteor/client/views/invite/hooks/useValidateInviteQuery.ts
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#30833 test: Omnichannel Agents, Visitors, Rooms & Routing tests
  apps/meteor/tests/data/licenses.helper.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/livechat/utils.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
  apps/meteor/tests/end-to-end/api/livechat/24-routing.ts
Labels: stat: ready to merge, stat: QA skipped

#30854 chore: Remove unnecessary `useForm` in `CannedResponsesTable`
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseFilter.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx
Labels: stat: ready to merge, stat: QA skipped

#30433 chore: Support for deepl free api
  .changeset/cool-rockets-talk.md
  apps/meteor/app/autotranslate/server/deeplTranslate.ts
Labels: stat: ready to merge, stat: QA skipped

#30805 fix: videoconf ringing iOS push notification wrong params
  apps/meteor/app/push/server/apn.ts
  apps/meteor/app/push/server/definition.ts
  apps/meteor/app/push/server/push.ts
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: ready to merge, stat: QA skipped

#30878 regression: Remove more keys from visitor object
  .changeset/angry-kids-occur.md
  apps/meteor/server/models/raw/LivechatVisitors.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30884 regression: workspace stats cache loading
  apps/meteor/client/hooks/useWorkspaceInfo.ts
  apps/meteor/client/views/admin/workspace/WorkspacePage.tsx
  apps/meteor/client/views/admin/workspace/WorkspaceRoute.tsx
Labels: stat: needs QA

#30864 fix: GUI crash when visitor asks to be forgotten
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/composer/ComposerContainer.tsx
  apps/meteor/client/views/room/composer/ComposerMessage.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30881 test: Routing & Transcript tests
  apps/meteor/app/livechat/server/methods/sendTranscript.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/24-routing.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30897 chore: added subscription callout limits
  apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#30899 regression: adjust colors after limit
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/client/views/admin/subscription/components/FeatureUsageCard.tsx
  apps/meteor/client/views/admin/subscription/components/PieGraphCard.tsx
  apps/meteor/client/views/admin/subscription/components/UpgradeButton.tsx
  apps/meteor/client/views/admin/subscription/components/cards/ActiveSessionsCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/ActiveSessionsPeakCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/AppsUsageCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/MACCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardTrial.tsx
  apps/meteor/client/views/admin/subscription/components/cards/SeatsCard.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/ui-client/src/components/Card/CardBody.tsx
Labels: stat: needs QA

#30901 chore: unify plan name
  apps/meteor/client/hooks/useLicense.ts
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardPremium.tsx
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardTrial.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
  apps/meteor/ee/client/sidebar/footer/SidebarFooterWatermark.tsx
Labels: stat: needs QA

#30904 regression: flaky test
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
Labels: stat: needs QA

#30885 feat(cloud): Cloud announcements core app
  apps/meteor/app/api/server/v1/cloud.ts
  apps/meteor/app/ui-message/client/ActionManager.ts
  apps/meteor/client/hooks/useLicense.ts
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/hooks/useCloudAnnouncements.ts
  apps/meteor/server/models/raw/CloudAnnouncements.ts
  apps/meteor/server/modules/core-apps/cloudAnnouncements.module.ts
  apps/meteor/server/startup/coreApps.ts
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/model-typings/src/models/ICloudAnnouncementsModel.ts
  packages/rest-typings/src/v1/cloud.ts
  packages/ui-contexts/src/ActionManagerContext.ts
Labels: stat: needs QA

#30909 regression: adjust user creation limits
  apps/meteor/client/hooks/useShouldPreventAction.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/ee/client/views/admin/users/UserPageHeaderContentWithSeatsCap.tsx
  apps/meteor/ee/server/startup/seatsCap.ts
  ee/packages/license/src/license.ts
Labels: stat: needs QA

#30915 regression: report as supporting license v3
  apps/meteor/app/cloud/server/license.ts
Labels: stat: ready to merge, stat: QA skipped

#30914 chore: remove redundant indexes
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/server/models/raw/Users.js
Labels: stat: ready to merge, stat: QA skipped

#30858 fix: immediate auto reload issues
  .changeset/thick-ads-run.md
  apps/meteor/packages/autoupdate/autoupdate_client.js
  apps/meteor/packages/autoupdate/autoupdate_server.js
  apps/meteor/packages/autoupdate/client_versions.js
  apps/meteor/packages/autoupdate/package.js
  package.json
  yarn.lock
Labels: stat: needs QA

#30911 regression: "Enterprise" to "Premium" in settings
  apps/meteor/ee/app/license/server/settings.ts
  apps/meteor/ee/server/settings/ldap.ts
  apps/meteor/ee/server/settings/saml.ts
  apps/meteor/packages/rocketchat-i18n/i18n/af.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/az.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/be-BY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bg.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cy.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-AT.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/el.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/eo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/id.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ku.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/mn.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ro.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sq.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/th-TH.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-HK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: needs QA

#30786 chore: Refactor Omnichannel EditCustomField UI
  apps/meteor/client/views/omnichannel/additionalForms.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsForm.stories.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsPage.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsRoute.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
  apps/meteor/client/views/omnichannel/customFields/EditCustomFields.tsx
  apps/meteor/client/views/omnichannel/customFields/EditCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/customFields/EditCustomFieldsPageContainer.js
  apps/meteor/client/views/omnichannel/customFields/EditCustomFieldsWithData.tsx
  apps/meteor/client/views/omnichannel/customFields/NewCustomFieldsForm.js
  apps/meteor/client/views/omnichannel/customFields/NewCustomFieldsPage.js
  apps/meteor/client/views/omnichannel/customFields/useRemoveCustomField.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/CustomFieldsAdditionalForm.js
  apps/meteor/ee/client/omnichannel/additionalForms/CustomFieldsAdditionalForm.tsx
  apps/meteor/ee/client/omnichannel/additionalForms/CustomFieldsAdditionalFormContainer.js
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/omnichannel/omnichannel-custom-fields.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-custom-fields.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA skipped

#30907 chore: Replace `useForm` on admin `EditRoom`
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/rooms/EditRoomContextBar.tsx
  apps/meteor/client/views/admin/rooms/EditRoomWithData.tsx
  apps/meteor/client/views/admin/rooms/RoomsPage.tsx
  apps/meteor/client/views/admin/rooms/useEditAdminRoomPermissions.ts
  apps/meteor/client/views/hooks/roomActions/useArchiveRoom.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
Labels: stat: needs QA

#30435 chore: make delete user method keep working without relying on msg db watcher
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/client/startup/UserDeleted.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/events/Events.ts
Labels: stat: needs QA

#30935 regression: Enterprise_License_Data not updating
  apps/meteor/ee/app/license/server/settings.ts
  apps/meteor/ee/app/license/server/startup.ts
Labels: stat: needs QA

#30750 fix: oauth login by redirect failing on firefox
  .changeset/chatty-schools-notice.md
  apps/meteor/app/custom-oauth/client/custom_oauth_client.js
  apps/meteor/app/custom-oauth/client/swapSessionStorage.js
Labels: stat: ready to merge, stat: QA tested

#30919 regression: Workspace and Subscription bugs
  apps/meteor/client/lib/utils/isOverLicenseLimits.ts
  apps/meteor/client/views/admin/subscription/components/cards/ActiveSessionsPeakCard.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#30936 regression: Disable `mem` for `TEST_MODE` on `analytics/overview` endpoint
  apps/meteor/app/livechat/server/lib/AnalyticsTyped.ts
Labels: stat: needs QA

#30937 regression: Infinite loop when a license with MAC reached `fair_policy` limit
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/server/services/omnichannel/queue.ts
Labels: stat: needs QA

#30902 regression: Don't block visitor from changing departments when out of MAC
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/livechat/server/methods/sendTranscript.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30948 regression: adjust license
  apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/syncCloudData.ts
  apps/meteor/client/hooks/useIsEnterprise.ts
  apps/meteor/client/hooks/useLicense.ts
  apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.spec.tsx
  apps/meteor/ee/client/hooks/useHasLicenseModule.ts
  apps/meteor/ee/server/startup/engagementDashboard.ts
  apps/meteor/server/models/raw/Analytics.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v304.ts
  ee/packages/license/src/events/emitter.ts
  ee/packages/license/src/index.ts
  ee/packages/license/src/license.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#30945 regression: Dangling type for `cloud:disconnectWorkspace`
  apps/meteor/app/cloud/server/methods.ts
Labels: stat: QA skipped

#30952 regression: Broken plan name in Community workspace
  apps/meteor/client/hooks/useLicense.ts
Labels: stat: needs QA

#30941 regression: Remove pending cloud registration banner
  apps/meteor/client/startup/startup.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#30955 regression: getCheckoutUrl function to use correct access token with scope
  apps/meteor/app/cloud/server/functions/getCheckoutUrl.ts
Labels: stat: needs QA

#30929 regression: Remove onboarding translations from i18n in favor of `en` new content
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/gl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
Labels: stat: QA skipped

#30857 fix: wrong client hash calculation due to race condition on assets
  .changeset/rotten-pears-watch.md
  apps/meteor/app/assets/server/assets.ts
Labels: stat: needs QA

#30963 regression: UniqueID change detection showing on upgrade
  apps/meteor/server/settings/misc.ts
Labels: stat: needs QA

#30964 chore: LICENSE v3 make visualExpiration optional
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardPremium.tsx
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardTrial.tsx
  ee/packages/license/__tests__/MockedLicenseBuilder.ts
  ee/packages/license/src/definition/ILicenseV3.ts
  ee/packages/license/src/v2/convertToV3.ts
Labels: stat: needs QA

#30966 regression: self checkout success callback
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
Labels: stat: needs QA

#30962 regression: Set `queue.running` to false when stopped by mac limit
  apps/meteor/server/services/omnichannel/queue.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30959 fix: Canned responses stream not working
  .changeset/selfish-panthers-stare.md
  apps/meteor/ee/app/canned-responses/client/startup/responses.js
Labels: stat: needs QA

#30968 Release 6.4.6
  .changeset/bump-patch-1699997094756.md
  .changeset/chatty-schools-notice.md
  .changeset/rotten-pears-watch.md
  .changeset/thick-ads-run.md
  .changeset/weak-elephants-kneel.md
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/custom-oauth/client/custom_oauth_client.js
  apps/meteor/app/custom-oauth/client/swapSessionStorage.js
  apps/meteor/packages/autoupdate/autoupdate_client.js
  apps/meteor/packages/autoupdate/autoupdate_server.js
  apps/meteor/packages/autoupdate/client_versions.js
  apps/meteor/packages/autoupdate/package.js
  apps/meteor/server/services/push/service.ts
  package.json
  yarn.lock
Labels: stat: needs QA

#30991 regression: fix livechat not working when embedded
  apps/meteor/packages/rocketchat-livechat/assets/demo.html
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-widget.spec.ts
  packages/livechat/webpack.config.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30995 regression: airgaped server breaking workspace page
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
Labels: stat: ready to merge, stat: QA skipped

#30973 regression: changed UniqueID modal being displayed wrongly during startup
  .changeset/ninety-files-sing.md
  apps/meteor/server/settings/misc.ts
Labels: stat: needs QA

#30739 fix: invite link with Registration mode as Secret URL
  apps/meteor/client/views/invite/hooks/useValidateInviteQuery.ts
  packages/web-ui-registration/src/RegisterSecretPageRouter.tsx
  packages/web-ui-registration/src/RegistrationPageRouter.tsx
  packages/web-ui-registration/src/hooks/useLoginRouter.ts
Labels: stat: ready to merge, stat: QA tested

#30999 chore: call sync cloud after registration
  apps/meteor/app/cloud/server/functions/saveRegistrationData.ts
Labels: stat: needs QA

#30972 regression: PDF transcript should not depend on scalability module when running in monolith
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  ee/packages/omnichannel-services/src/QueueWorker.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31002 fix: Google Maps config settings not visible
  .changeset/honest-socks-sniff.md
  apps/meteor/server/settings/message.ts
Labels: stat: ready to merge, stat: QA skipped

#30994 Release 6.4.7
  .changeset/bump-patch-1700162556041.md
  .changeset/sour-keys-tickle.md
  apps/meteor/.docker/Dockerfile.alpine
  apps/meteor/package.json
  apps/meteor/server/models/raw/OAuthAccessTokens.ts
  ee/apps/ddp-streamer/package.json
  yarn.lock
Labels: stat: needs QA

#30986 feat: add date and time into device login email
  .changeset/old-buckets-camp.md
  apps/meteor/ee/server/lib/deviceManagement/session.ts
  apps/meteor/ee/server/lib/deviceManagement/startup.ts
Labels: stat: ready to merge, stat: QA skipped

#30992 chore: remove `required` on subscription page
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/client/views/admin/subscription/components/UsagePieGraph.tsx
  apps/meteor/client/views/admin/subscription/components/cards/MACCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/SeatsCard.tsx
Labels: stat: needs QA

#30975 regression: Queue start/stop flow causing inquiries to be queued again
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/services/omnichannel/queue.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31010 regression: Start queue on license invalidation
  apps/meteor/server/services/omnichannel/service.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31011 chore: improve license sync
  apps/meteor/ee/app/license/server/startup.ts
  ee/packages/license/src/definition/events.ts
  ee/packages/license/src/license.ts
Labels: stat: QA tested

#31012 chore: License change to trigger `start_fair_policy` events and revalidate only once
  ee/packages/license/__tests__/emitter.spec.ts
  ee/packages/license/src/license.spec.ts
  ee/packages/license/src/license.ts
Labels: stat: ready to merge, stat: QA tested

#31009 chore: add target to subscription action
  apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/client/views/admin/subscription/components/FeatureUsageCard.tsx
  apps/meteor/client/views/admin/subscription/components/UpgradeButton.tsx
  apps/meteor/client/views/admin/subscription/components/cards/ActiveSessionsCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/ActiveSessionsPeakCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/AppsUsageCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/MACCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardTrial.tsx
  apps/meteor/client/views/admin/subscription/components/cards/SeatsCard.tsx
  apps/meteor/client/views/admin/subscription/hooks/useCheckoutUrl.ts
Labels: stat: needs QA

#30989 regression: Register offline blinking when form is loading
  apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
Labels: stat: needs QA

#31007 fix: Ensure `viewId` in UiKit banners
  apps/meteor/ee/app/license/server/maxSeatsBanners.ts
  apps/meteor/server/services/nps/notification.ts
Labels: stat: needs QA

#31006 regression: Subscription page apps count in Community edition
  apps/meteor/client/providers/AppsProvider.tsx
Labels: stat: needs QA

#30984 regression: Update Enterprise description setting to Premium
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
Labels: stat: needs QA

#30933 fix: Visitor message not being sent to webhook
  .changeset/loud-foxes-grin.md
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
Labels: stat: ready to merge, communityPR, stat: QA skipped

#30993 fix: Livechat Reactivity issues with createOrUpdateGuest (6.4.8 version)
  packages/livechat/src/lib/hooks.js
Labels: stat: ready to merge, stat: QA tested

#31021 regression: Calculate MAC from DB instead of Statistics
  apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31024 chore: #30993 changeset
  .changeset/sixty-goats-divide.md
Labels: stat: ready to merge, stat: QA skipped

#31020 Release 6.4.8
  .changeset/bump-patch-1700490400253.md
  .changeset/sixty-goats-divide.md
  packages/livechat/src/lib/hooks.js
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#30947 chore: migrate filter mention to service
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/index.ts
  apps/meteor/app/lib/server/startup/filterATAllTag.ts
  apps/meteor/app/lib/server/startup/filterATHereTag.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/server/services/messages/hooks/BeforeSavePreventMention.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSavePreventMention.tests.ts
  packages/core-services/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#31035 chore: show license with after code sequence
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
Labels: stat: needs QA

#31037 regression: `saveGuest` triggering app events for invalid visitor ids
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31034 regression: error when archiving rooms in the UI
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31038 regression: handle cloud delete registration
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessToken.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts
  apps/meteor/app/cloud/server/functions/removeWorkspaceRegistrationInfo.ts
Labels: stat: needs QA

#31022 regression: Bump `fuselage` packages version
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/logger/package.json
  packages/rest-typings/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31040 chore: improve license sync
  apps/meteor/app/cloud/server/functions/getConfirmationPoll.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts
  apps/meteor/app/cloud/server/functions/removeWorkspaceRegistrationInfo.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/announcementSync.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/legacySyncWorkspace.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/syncCloudData.ts
Labels: stat: needs QA

#31026 chore: demonstration findings
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts
  apps/meteor/app/lib/server/methods/saveSettings.ts
  apps/meteor/client/hooks/useLicense.ts
  apps/meteor/client/views/admin/cloud/PasteStep.tsx
  apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/client/views/admin/subscription/components/cards/MACCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/SeatsCard.tsx
  apps/meteor/client/views/setupWizard/providers/SetupWizardProvider.tsx
  apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#31028 chore: build meteor with cloud version
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts
  apps/meteor/app/utils/rocketchat-supported-versions.info
  apps/meteor/client/definitions/info.d.ts
  apps/meteor/packages/rocketchat-version/plugin/compile-version.js
Labels: stat: needs QA

#31005 fix: fixing the href message link parsing
  .changeset/great-queens-joke.md
  apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/tests/e2e/message-actions.spec.ts
  yarn.lock
Labels: stat: needs QA

#31043 regression: airgapped
  apps/meteor/app/api/server/v1/cloud.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts
  apps/meteor/app/cloud/server/functions/saveRegistrationData.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
  apps/meteor/ee/app/license/server/startup.ts
Labels: stat: needs QA

#30816 fix: Desktop notification routing for direct rooms
  .changeset/spicy-kiwis-argue.md
  apps/meteor/app/lib/server/functions/notifications/desktop.ts
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/client/views/account/preferences/PreferencesNotificationsSection.tsx
  apps/meteor/definition/IRoomTypeConfig.ts
  apps/meteor/server/lib/rooms/roomCoordinator.ts
  apps/meteor/server/lib/rooms/roomTypes/direct.ts
  apps/meteor/server/lib/rooms/roomTypes/livechat.ts
  apps/meteor/server/lib/rooms/roomTypes/voip.ts
  packages/core-typings/src/INotification.ts
Labels: stat: ready to merge, stat: QA tested

#31046 chore: Changed over mac limit Banner to Callout
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31019 fix: OTR calling a deprecated method
  .changeset/great-kings-tickle.md
  apps/meteor/app/otr/client/OTRRoom.ts
Labels: stat: needs QA

#31044 regression: remove unlimited mac info
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardPremium.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#30998 chore: Bump Apps-Engine version
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: QA skipped, squad: apps ecosystem

#31053 regression: fix registration sync
  apps/meteor/app/api/server/v1/cloud.ts
  ee/packages/license/__tests__/MockedLicenseBuilder.ts
  ee/packages/license/__tests__/setLicense.spec.ts
  ee/packages/license/src/license.ts
Labels: stat: ready to merge, stat: QA tested

#31055 regression: Cloud communication
  apps/meteor/client/views/cloud/CloudAnnouncementHandler.tsx
  apps/meteor/client/views/cloud/CloudAnnouncementsRegion.tsx
Labels: stat: ready to merge, stat: QA tested

#31047 chore: remove seats cap banner
  apps/meteor/ee/app/license/server/maxSeatsBanners.ts
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/ee/server/startup/seatsCap.ts
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: ready to merge, stat: QA tested

#31041 chore: unify subscription manage urls
  apps/meteor/app/api/server/middlewares/authentication.ts
  apps/meteor/app/cloud/server/functions/getCheckoutUrl.ts
  apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx
  apps/meteor/client/views/admin/subscription/components/UpgradeButton.tsx
  apps/meteor/client/views/admin/subscription/hooks/useCheckoutUrl.ts
  apps/meteor/ee/app/license/server/getSeatsRequestLink.ts
  apps/meteor/ee/client/views/admin/users/useRequestSeatsLink.ts
  apps/meteor/ee/server/requestSeatsRoute.ts
Labels: stat: needs QA

#30381 chore: Add the possibility for removing the watcher for the message collection
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/client/startup/UserDeleted.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/watchers/lib/messages.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/LocalBroker.ts
  packages/core-services/src/events/Events.ts
  packages/core-services/src/events/listeners.ts
  packages/core-services/src/index.ts
  packages/core-services/src/lib/Api.ts
  packages/core-services/src/types/IApiService.ts
  packages/core-services/src/types/IBroker.ts
  packages/core-services/src/types/ServiceClass.ts
Labels: stat: needs QA

#31059 regression: New Release banner showing for pre-releases
  apps/meteor/app/version-check/server/functions/buildVersionUpdateMessage.ts
Labels: stat: needs QA

#30928 i18n: fix german language encryption password not showing
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#30906 chore: Pin, star and react to message without oplog
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/reactions/server/setReaction.ts
Labels: stat: needs QA

#30674 chore: fix priorities sidebar flaky test
  apps/meteor/tests/e2e/omnichannel/omnichannel-priorities-sidebar.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/utils/omnichannel/rooms.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30855 chore: Restore Managers SearchBar and add tests
  apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-manager.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-manager.ts
Labels: stat: ready to merge, stat: QA skipped

#30408 chore: Adapt some messaging features to work without the DB watcher
  apps/meteor/app/discussion/server/hooks/propagateDiscussionMetadata.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/sendMessage.js
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.js
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/threads/server/hooks/aftersavemessage.ts
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/server/services/meteor/service.ts
  packages/model-typings/src/models/IMessagesModel.ts
Labels: stat: needs QA

#31039 fix: creating group with the name of an already existing room throws `internalError`
  .changeset/dirty-rings-fry.md
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
Labels: stat: needs QA, squad: team-collab

#31060 regression(fuselage-ui-kit): Handle null text before parsing
  packages/fuselage-ui-kit/package.json
  packages/fuselage-ui-kit/src/elements/MarkdownTextElement.tsx
Labels: stat: ready to merge, stat: QA tested

#29677 fix: File uploads even size limit exceed
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31061 regression: update seats cap modal
  apps/meteor/app/api/server/middlewares/authentication.ts
  apps/meteor/app/cloud/server/functions/getCheckoutUrl.ts
  apps/meteor/client/views/admin/subscription/hooks/useCheckoutUrl.ts
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/definition/externals/express.d.ts
  apps/meteor/ee/app/license/server/getSeatsRequestLink.ts
  apps/meteor/ee/client/views/admin/users/CloseToSeatsCapModal.tsx
  apps/meteor/ee/client/views/admin/users/ReachedSeatsCapModal.tsx
  apps/meteor/ee/client/views/admin/users/UserPageHeaderContentWithSeatsCap.tsx
  apps/meteor/ee/client/views/admin/users/useRequestSeatsLink.ts
  apps/meteor/ee/server/requestSeatsRoute.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/admin-flextab-users.ts
Labels: stat: needs QA

#31033 regression: banners close
  apps/meteor/client/views/banners/hooks/useRemoteBanners.ts
  apps/meteor/ee/server/apps/communication/uikit.ts
  apps/meteor/server/modules/core-apps/banner.module.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/fixtures/userStates.ts
Labels: stat: needs QA

#31064 chore: format limit cards
  apps/meteor/client/hooks/useFormatNumber.ts
  apps/meteor/client/views/admin/subscription/components/UsagePieGraph.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#31066 regression: active users count validation
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/ee/app/authorization/server/callback.ts
  apps/meteor/ee/app/authorization/server/index.ts
  apps/meteor/ee/app/authorization/server/validateUserRoles.spec.ts
  apps/meteor/ee/app/authorization/server/validateUserRoles.ts
  apps/meteor/jest.config.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/methods/deleteUser.ts
  ee/packages/license/__tests__/MockedLicenseBuilder.ts
  ee/packages/license/src/MockedLicenseBuilder.ts
  ee/packages/license/src/index.ts
Labels: stat: needs QA

#31008 regression: Use `this.getLicense` to instead of `this._license` when calculating shouldPreventAction map
  ee/packages/license/src/license.spec.ts
  ee/packages/license/src/license.ts
  ee/packages/license/src/validation/getCurrentValueForLicenseLimit.ts
Labels: stat: ready to merge, stat: QA skipped

#31068 chore: Improve license events
  apps/meteor/ee/app/authorization/server/callback.ts
  apps/meteor/ee/app/authorization/server/validateUserRoles.spec.ts
  apps/meteor/ee/app/authorization/server/validateUserRoles.ts
  apps/meteor/ee/app/license/server/startup.ts
  apps/meteor/ee/server/startup/index.ts
  ee/packages/license/src/events/listeners.ts
  ee/packages/license/src/index.ts
Labels: stat: needs QA

#31052 fix: Avoid using `anyOf` when validating settings array on `livechat/appearance` endpoint
  apps/meteor/app/livechat/server/api/v1/config.ts
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31065 chore: convert bad words to class
  apps/meteor/server/services/messages/hooks/BeforeSaveBadWords.ts
  apps/meteor/server/services/messages/hooks/badwords.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveBadWords.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#31054 chore: refactored livechat e2e tests
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30765 fix: Single Business hours not working when start/end are on different days
  apps/meteor/server/models/raw/LivechatBusinessHours.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31073 regression: user activation events
  apps/meteor/ee/app/authorization/server/callback.ts
Labels: stat: needs QA

#31074 fix: Change search box placeholder text for windows devices
  apps/meteor/client/sidebar/search/SearchList.tsx
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31086 fix: Missing info about license removal
  apps/meteor/ee/app/license/server/settings.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#31085 fix: Prevent process crash when broadcasting before broker set
  apps/meteor/app/cloud/server/functions/saveRegistrationData.ts
  apps/meteor/ee/app/license/server/applyLicense.ts
  apps/meteor/ee/app/license/server/startup.ts
Labels: stat: needs QA

#31088 chore: change trigger logic
  apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx
  apps/meteor/ee/app/authorization/server/callback.ts
  ee/packages/license/src/license.spec.ts
  ee/packages/license/src/validation/validateLimit.ts
Labels: stat: needs QA

#31071 regression: remove registration page and related methods and files
  apps/meteor/app/cloud/server/functions/reconnectWorkspace.ts
  apps/meteor/app/cloud/server/methods.ts
  apps/meteor/client/lib/constants.ts
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/views/admin/cloud/CloudRoute.tsx
  apps/meteor/client/views/admin/cloud/CopyStep.tsx
  apps/meteor/client/views/admin/cloud/ManualWorkspaceRegistrationModal.tsx
  apps/meteor/client/views/admin/cloud/PasteStep.tsx
  apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceCards.tsx
  apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx
  apps/meteor/client/views/admin/cloud/modals/ConnectWorkspaceModal.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/hooks/useFeatureBullets.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepOneModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepTwoModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceSetupModal/index.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceTokenModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisteredWorkspaceModal.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#31072 regression: Registration Wizard UI fixes
  apps/meteor/client/views/root/MainLayout/RegisterUsername.tsx
  apps/meteor/client/views/setupWizard/contexts/SetupWizardContext.tsx
  apps/meteor/client/views/setupWizard/providers/SetupWizardProvider.tsx
  apps/meteor/client/views/setupWizard/steps/AdminInfoStep.tsx
  apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
  apps/meteor/ee/app/license/server/startup.ts
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/af.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#30807 refactor: Move functions out of `livechat.js`
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/imports/server/rest/users.ts
  apps/meteor/app/livechat/server/api/v1/agent.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/lib/Livechat.js
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/methods/addAgent.ts
  apps/meteor/app/livechat/server/methods/addManager.ts
  apps/meteor/app/livechat/server/methods/changeLivechatStatus.ts
  apps/meteor/app/livechat/server/methods/registerGuest.ts
  apps/meteor/app/livechat/server/methods/saveDepartmentAgents.ts
  apps/meteor/app/livechat/server/methods/saveInfo.ts
  apps/meteor/app/livechat/server/methods/setUpConnection.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/services/meteor/service.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA skipped

#30916 chore: replace `useForm` on Omnichannel `AppearanceForm`
  apps/meteor/client/views/omnichannel/appearance/AppearanceForm.stories.tsx
  apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx
  apps/meteor/client/views/omnichannel/appearance/AppearancePage.tsx
Labels: stat: ready to merge, stat: QA skipped

#31091 chore: convert Spotify callback to class
  apps/meteor/app/spotify/lib/spotify.ts
  apps/meteor/app/spotify/server/index.ts
  apps/meteor/package.json
  apps/meteor/server/importPackages.ts
  apps/meteor/server/services/messages/hooks/BeforeSaveSpotify.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveSpotify.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#31050 chore: Reduce amount of logs on info level
  apps/meteor/app/api/server/v1/cloud.ts
  apps/meteor/server/services/omnichannel/queue.ts
  packages/logger/src/getPino.ts
Labels: stat: needs QA

#30869 feat: endpoints to new users panel
  .changeset/serious-poets-smash.md
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/server/methods/sendWelcomeEmail.ts
  apps/meteor/tests/end-to-end/api/01-users.js
  packages/rest-typings/src/v1/users.ts
  packages/rest-typings/src/v1/users/UsersListStatusParamsGET.ts
  packages/rest-typings/src/v1/users/UsersSendWelcomeEmailParamsPOST.ts
Labels: stat: needs QA

#30887 chore: Replace `useForm` in favor of RHF on CannedResponses
  apps/meteor/client/components/AutoCompleteDepartment.tsx
  apps/meteor/ee/client/hooks/roomActions/useCannedResponsesRoomAction.ts
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEdit.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEditWithData.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEditWithDepartmentData.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseNew.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesPage.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/RemoveCannedResponseButton.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/MarkdownTextEditor/InsertPlaceholderDropdown.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/MarkdownTextEditor/MarkdownTextEditor.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/MarkdownTextEditor/index.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/PreviewText.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/IconButton.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/TextButton.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/TextEditor.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/Textarea.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/Toolbox.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/TextEditor/index.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/CannedResponse.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/CannedResponse.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/CannedResponseList.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/CannedResponseList.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/Item.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/Item.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/WrapCannedResponse.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/WrapCannedResponseList.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/modals/CreateCannedResponse/CreateCannedResponseModal.stories.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/modals/CreateCannedResponse/CreateCannedResponseModal.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/modals/CreateCannedResponse/index.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/useRemoveCannedResponse.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/CreateCannedResponseModal.stories.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/CreateCannedResponseModal.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/SharingOptions.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/index.tsx
  apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/index.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: needs QA

#31089 chore: Remove duplicated file related to read receipts
  apps/meteor/client/startup/actionButtons/index.ts
  apps/meteor/client/startup/actionButtons/readReceipt.ts
Labels: stat: ready to merge, stat: QA skipped

#30920 chore: remove sidebar palette in favor of dark palette
  ee/packages/ui-theming/src/SidebarPaletteStyleTag.tsx
  ee/packages/ui-theming/src/paletteDark.ts
  ee/packages/ui-theming/src/sidebarPalette.ts
  ee/packages/ui-theming/src/sidebarPaletteDark.ts
Labels: stat: needs QA

#30532 feat: Implement users page deactivated tab
  apps/meteor/client/components/UserCard/UserCardRoles.tsx
  apps/meteor/client/components/UserInfo/UserInfo.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoActions.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoWithData.tsx
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTableRow.tsx
  apps/meteor/client/views/admin/users/hooks/useFilterActiveOrDeactivatedUsers.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx
Labels: stat: needs QA

#31099 fix: mention channel redirecting to own DM
  .changeset/silver-mice-allow.md
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
Labels: stat: ready to merge, stat: QA tested

#31116 chore: add license into registration data
  apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
Labels: stat: needs QA

#31107 chore: allow to remove license
  apps/meteor/app/api/server/v1/cloud.ts
  apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts
  apps/meteor/app/cloud/server/functions/removeLicense.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/syncCloudData.ts
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/client/views/admin/subscription/components/UpgradeButton.tsx
  apps/meteor/client/views/admin/subscription/components/UpgradeToGetMore.tsx
  apps/meteor/client/views/admin/subscription/components/cards/FeaturesCard.tsx
  apps/meteor/client/views/admin/subscription/hooks/useRemoveLicense.ts
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/components/VersionTag.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/getVersionStatus.spec.ts
  apps/meteor/client/views/admin/workspace/VersionCard/getVersionStatus.ts
  apps/meteor/ee/app/license/server/applyLicense.ts
  apps/meteor/ee/app/license/server/settings.ts
  apps/meteor/ee/app/license/server/startup.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  ee/packages/license/src/definition/ILicenseV3.ts
  ee/packages/license/src/definition/events.ts
  ee/packages/license/src/events/listeners.ts
  ee/packages/license/src/index.ts
  ee/packages/license/src/license.ts
  packages/core-typings/src/cloud/WorkspaceSyncPayload.ts
  packages/rest-typings/src/v1/cloud.ts
Labels: stat: ready to merge, stat: QA tested

#31119 chore: bump `message-parser` package version
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#31097 regression: condition to show buy now in the MACCard
  apps/meteor/client/views/admin/subscription/components/cards/MACCard.tsx
Labels: stat: needs QA

#31123 chore: Use draft release on supported versions
  .github/workflows/ci.yml
  apps/meteor/packages/rocketchat-version/plugin/compile-version.js
Labels: stat: needs QA

#31124 chore: Fix notify-draft-services
  .github/workflows/ci.yml
Labels: stat: needs QA
