Repository RocketChat/Rocket.Chat, pull requests merged in 2024-11, with the labels that each got.

#33856 test: fix flaky e2e test omnichannel-takeChat
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
Labels: stat: ready to merge, stat: QA assured

#33347 refactor: CreateOAuthModal to use React Hook Form
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage/CreateOAuthModal.spec.tsx
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage/CreateOAuthModal.tsx
  packages/i18n/src/locales/af.i18n.json
  packages/i18n/src/locales/ar.i18n.json
  packages/i18n/src/locales/az.i18n.json
  packages/i18n/src/locales/be-BY.i18n.json
  packages/i18n/src/locales/bg.i18n.json
  packages/i18n/src/locales/bs.i18n.json
  packages/i18n/src/locales/ca.i18n.json
  packages/i18n/src/locales/cs.i18n.json
  packages/i18n/src/locales/cy.i18n.json
  packages/i18n/src/locales/da.i18n.json
  packages/i18n/src/locales/de-AT.i18n.json
  packages/i18n/src/locales/de-IN.i18n.json
  packages/i18n/src/locales/de.i18n.json
  packages/i18n/src/locales/el.i18n.json
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/eo.i18n.json
  packages/i18n/src/locales/es.i18n.json
  packages/i18n/src/locales/fa.i18n.json
  packages/i18n/src/locales/fi.i18n.json
  packages/i18n/src/locales/fr.i18n.json
  packages/i18n/src/locales/he.i18n.json
  packages/i18n/src/locales/hi-IN.i18n.json
  packages/i18n/src/locales/hr.i18n.json
  packages/i18n/src/locales/hu.i18n.json
  packages/i18n/src/locales/id.i18n.json
  packages/i18n/src/locales/it.i18n.json
  packages/i18n/src/locales/ja.i18n.json
  packages/i18n/src/locales/ka-GE.i18n.json
  packages/i18n/src/locales/km.i18n.json
  packages/i18n/src/locales/ko.i18n.json
  packages/i18n/src/locales/ku.i18n.json
  packages/i18n/src/locales/lo.i18n.json
  packages/i18n/src/locales/lt.i18n.json
  packages/i18n/src/locales/lv.i18n.json
  packages/i18n/src/locales/mn.i18n.json
  packages/i18n/src/locales/ms-MY.i18n.json
  packages/i18n/src/locales/nl.i18n.json
  packages/i18n/src/locales/nn.i18n.json
  packages/i18n/src/locales/no.i18n.json
  packages/i18n/src/locales/pl.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/i18n/src/locales/pt.i18n.json
  packages/i18n/src/locales/ro.i18n.json
  packages/i18n/src/locales/ru.i18n.json
  packages/i18n/src/locales/se.i18n.json
  packages/i18n/src/locales/sk-SK.i18n.json
  packages/i18n/src/locales/sl-SI.i18n.json
  packages/i18n/src/locales/sq.i18n.json
  packages/i18n/src/locales/sv.i18n.json
  packages/i18n/src/locales/ta-IN.i18n.json
  packages/i18n/src/locales/th-TH.i18n.json
  packages/i18n/src/locales/tr.i18n.json
  packages/i18n/src/locales/ug.i18n.json
  packages/i18n/src/locales/uk.i18n.json
  packages/i18n/src/locales/vi-VN.i18n.json
  packages/i18n/src/locales/zh-HK.i18n.json
  packages/i18n/src/locales/zh-TW.i18n.json
  packages/i18n/src/locales/zh.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33857 regression: apps without networking permission failing to start
  packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
Labels: stat: ready to merge, stat: QA assured

#33780 refactor: Take away stale `messageArgs()` helper
  apps/meteor/app/autotranslate/client/lib/actionButton.ts
  apps/meteor/app/discussion/client/createDiscussionMessageAction.ts
  apps/meteor/app/message-mark-as-unread/client/actionButton.ts
  apps/meteor/app/reactions/client/init.ts
  apps/meteor/app/threads/client/messageAction/replyInThread.ts
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/components/message/toolbar/useWebDAVMessageAction.tsx
  apps/meteor/client/lib/utils/messageArgs.ts
  apps/meteor/client/startup/actionButtons/jumpToMessage.ts
  apps/meteor/client/startup/actionButtons/jumpToPinMessage.ts
  apps/meteor/client/startup/actionButtons/jumpToSearchMessage.ts
  apps/meteor/client/startup/actionButtons/jumpToStarMessage.ts
  apps/meteor/client/startup/actionButtons/permalinkPinned.ts
  apps/meteor/client/startup/actionButtons/permalinkStar.ts
  apps/meteor/client/startup/actionButtons/pinMessage.tsx
  apps/meteor/client/startup/actionButtons/starMessage.ts
  apps/meteor/client/startup/actionButtons/unpinMessage.ts
  apps/meteor/client/startup/actionButtons/unstarMessage.ts
  apps/meteor/client/startup/readReceipt.ts
Labels: stat: ready to merge, stat: QA assured

#33866 chore: swap `mitt` for `@rocket.chat/emitter`
  packages/livechat/package.json
  packages/livechat/src/helpers/canRenderMessage.ts
  packages/livechat/src/hooks/useDeleteMessageSubscription.ts
  packages/livechat/src/lib/connection.ts
  packages/livechat/src/lib/triggers.js
  packages/livechat/src/store/Store.ts
  packages/livechat/src/store/index.tsx
  packages/livechat/src/widget.ts
  yarn.lock
Labels: stat: needs testing

#33872 chore: Upgrade to Storybook 8.4
  apps/meteor/package.json
  apps/uikit-playground/package.json
  ee/packages/pdf-worker/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/mock-providers/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33839 chore: bump deps 6th wave
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/uikit-playground/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/license/package.json
  ee/packages/network-broker/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/presence/package.json
  ee/packages/ui-theming/package.json
  package.json
  packages/apps-engine/package.json
  packages/cas-validate/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/ddp-client/package.json
  packages/eslint-config/package.json
  packages/freeswitch/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/jest-presets/package.json
  packages/livechat/package.json
  packages/livechat/src/components/Messages/MessageText/markdown.ts
  packages/log-format/package.json
  packages/message-parser/package.json
  packages/peggy-loader/package.json
  packages/release-action/package.json
  packages/release-changelog/package.json
  packages/rest-typings/package.json
  packages/tracing/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-kit/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33785 fix: installed apps query not refreshing on mount
  .changeset/spicy-spiders-search.md
  apps/meteor/client/providers/AppsProvider/AppsProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#33861 test: updated createVisitor test util to use unique visitor names
  apps/meteor/tests/e2e/utils/omnichannel/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#33792 chore: refactor sidebar unread handler
  apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx
  apps/meteor/client/sidebarv2/hooks/useUnreadDisplay.spec.tsx
  apps/meteor/client/sidebarv2/hooks/useUnreadDisplay.ts
  apps/meteor/client/views/room/Sidepanel/hooks/useItemData.tsx
  apps/meteor/lib/getSubscriptionUnreadData.ts
Labels: stat: QA assured

#33896 regression: revert mp3-encoder bump
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33899 chore: improve unread badges a11y
  apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx
  apps/meteor/client/views/room/Sidepanel/hooks/useItemData.tsx
Labels: stat: ready to merge, stat: QA assured

#33791 test: `edit-room-retention-policy permission`duplicated actions
  apps/meteor/tests/e2e/retention-policy.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33865 fix: engine restart process for Deno used wrong status
  .changeset/old-coins-bow.md
  packages/apps-engine/src/definition/metadata/AppMethod.ts
  packages/apps-engine/src/server/compiler/AppCompiler.ts
  packages/apps-engine/src/server/managers/AppRuntimeManager.ts
  packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
  packages/apps-engine/src/server/runtime/deno/LivenessManager.ts
  packages/apps-engine/tests/server/runtime/DenoRuntimeSubprocessController.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33808 fix: broken client-side updates for recent emoji list
  .changeset/serious-mice-film.md
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.ts
  apps/meteor/app/emoji/client/helpers.ts
  apps/meteor/tests/unit/app/emoji/helpers.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33908 fix: newly created teams displayed as channels in sidebar with DISABLE_DB_WATCHERS enabled
  .changeset/light-terms-ring.md
  apps/meteor/server/services/team/service.ts
Labels: stat: ready to merge, stat: QA assured

#33772 fix: `Waiting Queue` feature not queueing rooms
  .changeset/stale-actors-enjoy.md
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-queue-management-autoselection.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
Labels: stat: ready to merge, stat: QA assured

#33880 i18n: Updated VoIP field labels from "Free Extension Numbers" to "Available extensions"
  .changeset/unlucky-kangaroos-yawn.md
  apps/meteor/client/views/admin/settings/groups/VoipGroupPage/AssignAgentModal.tsx
  apps/meteor/client/views/admin/users/voip/AssignExtensionModal.spec.tsx
  apps/meteor/client/views/admin/users/voip/AssignExtensionModal.tsx
  packages/i18n/src/locales/ar.i18n.json
  packages/i18n/src/locales/ca.i18n.json
  packages/i18n/src/locales/de.i18n.json
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/es.i18n.json
  packages/i18n/src/locales/fi.i18n.json
  packages/i18n/src/locales/fr.i18n.json
  packages/i18n/src/locales/hi-IN.i18n.json
  packages/i18n/src/locales/hu.i18n.json
  packages/i18n/src/locales/ja.i18n.json
  packages/i18n/src/locales/nl.i18n.json
  packages/i18n/src/locales/pl.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/i18n/src/locales/ru.i18n.json
  packages/i18n/src/locales/se.i18n.json
  packages/i18n/src/locales/sv.i18n.json
  packages/i18n/src/locales/zh-TW.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33910 ci: skip docker login for dependabot
  .github/actions/build-docker/action.yml
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA assured

#33900 chore: create more page/header variations
  apps/meteor/client/components/Page/PageBlock.tsx
  apps/meteor/client/components/Page/PageBlockWithBorder.tsx
  apps/meteor/client/components/Page/PageHeader.tsx
  apps/meteor/client/components/Page/PageHeaderNoShadow.tsx
Labels: stat: ready to merge, stat: QA assured

#33929 fix: apps-engine runtime fixes
  .changeset/thin-dryers-grow.md
  .changeset/weak-moons-battle.md
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33923 chore: add more logs to verification and merging
  apps/meteor/ee/app/livechat-enterprise/server/lib/logger.ts
  apps/meteor/ee/server/patches/mergeContacts.ts
  apps/meteor/ee/server/patches/verifyContactChannel.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/mergeContacts.spec.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/verifyContactChannel.spec.ts
Labels: stat: QA assured

#33930 chore: add reason to app restart log
  packages/apps-engine/src/server/runtime/deno/LivenessManager.ts
Labels: stat: ready to merge, stat: QA assured

#33921 regression: Restore contextualbar resizable handler
  apps/meteor/client/components/Contextualbar/ContextualbarResizable.tsx
Labels: stat: ready to merge, stat: QA assured

#33911 fix: Livechat finish chat option being enabled before room is created
  .changeset/metal-avocados-serve.md
  packages/livechat/src/routes/Chat/container.js
Labels: stat: ready to merge, stat: QA assured

#33912 test: improvements for livechat tab communication
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-tab-communication.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
Labels: stat: ready to merge, stat: QA assured

#33897 feat: add unread badge to sidebar collapser
  .changeset/friendly-ravens-teach.md
  apps/meteor/client/sidebarv2/RoomList/RoomList.tsx
  apps/meteor/client/sidebarv2/RoomList/RoomListCollapser.tsx
  apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx
  apps/meteor/client/sidebarv2/hooks/useRoomList.ts
  apps/meteor/tests/e2e/feature-preview.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/fragments/index.ts
  apps/meteor/tests/e2e/page-objects/fragments/sidebar.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
Labels: stat: ready to merge, stat: QA assured

#32991 fix: custom emoji update issues
  .changeset/green-papayas-thank.md
  apps/meteor/app/api/server/lib/getUploadFormData.ts
  apps/meteor/app/api/server/v1/emoji-custom.ts
  apps/meteor/app/emoji-custom/client/lib/emojiCustom.ts
  apps/meteor/app/emoji-custom/server/lib/insertOrUpdateEmoji.ts
  apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts
  apps/meteor/app/emoji/lib/rocketchat.ts
  apps/meteor/app/utils/client/getURL.ts
  apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx
  apps/meteor/server/models/raw/EmojiCustom.ts
  apps/meteor/tests/end-to-end/api/emoji-custom.ts
  packages/core-typings/src/IEmojiCustom.ts
  packages/model-typings/src/models/IEmojiCustomModel.ts
Labels: stat: ready to merge, stat: QA assured

#33960 chore: bump minor deps
  apps/meteor/client/components/MarkdownText.tsx
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/uikit-playground/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/network-broker/package.json
  ee/packages/pdf-worker/package.json
  packages/apps-engine/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/jest-presets/package.json
  packages/livechat/package.json
  packages/message-parser/package.json
  packages/mock-providers/package.json
  packages/tracing/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-kit/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33953 fix: Missing divider in Create team
  .changeset/neat-flies-drive.md
  apps/meteor/client/sidebarv2/header/CreateTeamModal.tsx
Labels: stat: ready to merge, stat: QA assured

#33941 fix: imported fixes
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/api/server/v1/import.ts
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/federation/server/endpoints/requestFromLatest.js
  apps/meteor/app/federation/server/endpoints/uploads.js
  apps/meteor/app/federation/server/endpoints/users.js
  apps/meteor/app/lib/server/methods/sendMessage.ts
  apps/meteor/tests/end-to-end/api/chat.ts
  apps/meteor/tests/end-to-end/api/import.spec.ts
  apps/meteor/tests/end-to-end/api/methods.ts
Labels: stat: ready to merge, stat: QA assured

#33952 chore: change oauth apps authorize page message
  apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx
  packages/i18n/src/locales/da.i18n.json
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/fi.i18n.json
  packages/i18n/src/locales/hi-IN.i18n.json
  packages/i18n/src/locales/it.i18n.json
  packages/i18n/src/locales/nn.i18n.json
  packages/i18n/src/locales/no.i18n.json
  packages/i18n/src/locales/pl.i18n.json
  packages/i18n/src/locales/ru.i18n.json
  packages/i18n/src/locales/se.i18n.json
  packages/i18n/src/locales/sv.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33278 fix: no spaces between emoji aliases
  .changeset/spotty-ads-knock.md
  apps/meteor/client/views/admin/customEmoji/CustomEmoji.spec.tsx
  apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx
Labels: stat: ready to merge, stat: QA assured

#33961 chore: bump swiper
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
  apps/meteor/definition/externals/swiper.d.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33218 fix: File Upload description bypassing message maximum character limit setting
  .changeset/lemon-foxes-carry.md
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.spec.tsx
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
  apps/meteor/tests/e2e/file-upload.spec.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33920 feat: Persistent Chat Discussion Name wildcard
  .changeset/silent-steaks-happen.md
  apps/meteor/ee/server/settings/video-conference.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/tests/end-to-end/apps/video-conferences.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33963 fix: Thread unread not in unread group
  .changeset/sweet-needles-melt.md
  apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx
  apps/meteor/client/sidebarv2/hooks/useRoomList.ts
Labels: stat: ready to merge, stat: QA assured

#33311 chore: improve stats cronjob scheduling
  .changeset/seven-otters-fold.md
  apps/meteor/app/statistics/server/functions/sendUsageReport.ts
Labels: stat: ready to merge, stat: QA assured

#33944 fix(Livechat): Popout mode not working in cross domains
  .changeset/swift-suns-perform.md
  packages/livechat/src/components/Screen/Header.tsx
  packages/livechat/src/components/Screen/ScreenProvider.tsx
  packages/livechat/src/routes/TriggerMessage/container.tsx
  packages/livechat/src/widget.ts
Labels: stat: ready to merge, stat: QA assured

#33814 feat: cancel subscription confirmation modal
  .changeset/twelve-horses-suffer.md
  apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
  apps/meteor/client/views/admin/subscription/components/CancelSubscriptionModal.spec.tsx
  apps/meteor/client/views/admin/subscription/components/CancelSubscriptionModal.tsx
  apps/meteor/client/views/admin/subscription/hooks/useCancelSubscriptionModal.spec.tsx
  apps/meteor/client/views/admin/subscription/hooks/useCancelSubscriptionModal.tsx
  apps/meteor/tests/mocks/utils/createDeferredMockFn.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33984 fix: wrong permission name used
  packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
Labels: stat: ready to merge, stat: QA assured

#33852 refactor: `pinMessage` method
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/tests/end-to-end/api/chat.ts
Labels: stat: ready to merge, stat: QA assured

#33958 fix(contextualbar thread): Remove resizable handler when thread is expanded
  .changeset/unlucky-wasps-check.md
  apps/meteor/client/components/Contextualbar/ContextualbarResizable.tsx
Labels: stat: ready to merge, stat: QA assured

#33949 feat: disable uploading of exempt apps
  .changeset/twenty-news-own.md
  apps/meteor/client/views/marketplace/AppExemptModal.tsx
  apps/meteor/client/views/marketplace/hooks/useInstallApp.tsx
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/tests/e2e/apps/private-apps-upload.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33994 fix: `resetIrcConnection` not requiring user logged
  .changeset/tricky-trees-destroy.md
  apps/meteor/app/irc/server/methods/resetIrcConnection.ts
Labels: stat: ready to merge, stat: QA assured

#33981 chore: Move `notify-user` `/notification` and `/subscriptions-changed` stream events to hook
  apps/meteor/client/hooks/useNotifyUser.ts
  apps/meteor/client/startup/notifications/konchatNotifications.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#33996 chore: Patch `swiper` for compatibility with Meteor bundler
  .yarn/patches/swiper-npm-11.1.14-8126fa478a.patch
  apps/meteor/definition/externals/swiper.d.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33962 chore: Discussion message action meteor removal
  apps/meteor/app/discussion/client/createDiscussionMessageAction.ts
  apps/meteor/app/discussion/client/index.ts
  apps/meteor/client/components/message/toolbar/MessageToolbar.tsx
  apps/meteor/client/components/message/toolbar/useNewDiscussionMessageAction.tsx
  apps/meteor/client/importPackages.ts
Labels: stat: ready to merge, stat: QA assured

#34001 regression: Fix file upload modal not receiving focus on description field
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.spec.tsx
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
Labels: stat: ready to merge, stat: QA assured

#33975 chore: Remove meteor cached collection startup for anons
  apps/meteor/client/hooks/useLoadRoomForAllowedAnonymousRead.ts
  apps/meteor/client/startup/collections.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#32906 feat: Improve thread metrics
  .changeset/lazy-avocados-whisper.md
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/utils/server/lib/normalizeMessagesForUser.ts
  apps/meteor/client/components/UserInfo/UserInfoAvatar.tsx
  apps/meteor/client/components/message/content/ThreadMetrics.spec.tsx
  apps/meteor/client/components/message/content/ThreadMetrics.tsx
  apps/meteor/client/components/message/content/ThreadMetricsFollow.tsx
  apps/meteor/client/components/message/content/ThreadMetricsParticipants.tsx
  apps/meteor/client/components/message/content/ThreadMetricsUnreadBadge.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/lib/lists/ThreadsList.ts
  apps/meteor/client/providers/AvatarUrlProvider.tsx
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadListItem.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadListMessage.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadListMetrics.tsx
  packages/i18n/src/locales/en.i18n.json
  packages/mock-providers/src/MockedRouterContext.tsx
  packages/mock-providers/src/index.ts
  packages/rest-typings/src/v1/chat.ts
  packages/ui-avatar/src/components/UserAvatar.tsx
  packages/ui-contexts/src/AvatarUrlContext.ts
  packages/ui-contexts/src/hooks/useUserAvatarPath.ts
Labels: stat: ready to merge, stat: QA assured

#33997 feat: make Deno capture unhandled exceptions and rejections and report them to the server
  .changeset/three-dragons-brush.md
  packages/apps-engine/deno-runtime/error-handlers.ts
  packages/apps-engine/deno-runtime/main.ts
  packages/apps-engine/src/definition/metadata/AppMethod.ts
  packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
Labels: stat: ready to merge, stat: QA assured

#34002 regression: `AudioMessageRecorder` missing styles
  apps/meteor/client/views/composer/AudioMessageRecorder/AudioMessageRecorder.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33937 chore: Improve performance of `users.listByStatus` on some circumstances
  apps/meteor/app/api/server/lib/users.ts
  apps/meteor/server/models/raw/Users.js
Labels: subj: performance, stat: ready to merge, stat: QA assured

#33991 chore: improve indexes of the livechat contacts collection
  apps/meteor/app/livechat/server/lib/contacts/ContactMerger.ts
  apps/meteor/server/models/raw/LivechatContacts.ts
  packages/core-typings/src/ILivechatContact.ts
Labels: stat: ready to merge, stat: QA assured

#34016 regression: `lastChat` property missing on contact migrated from visitor
  apps/meteor/app/livechat/server/lib/contacts/createContact.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
Labels: stat: ready to merge, stat: QA assured

#34029 regression: Contact center crashing when creating a new contact
  apps/meteor/client/NavBarV2/NavBar.tsx
  apps/meteor/client/views/omnichannel/contactInfo/EditContactInfo.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTableRow.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-center.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-contacts-list.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-manage-contact.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA assured

#34050 ci: do not rename test container on forks
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA assured

#34040 regression: `ContactInfo` should always display history tab
  apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ContactInfo.tsx
Labels: stat: ready to merge, stat: QA assured

#34013 fix: livechat appearance not savable on CE servers
  .changeset/curly-snails-walk.md
  apps/meteor/client/views/omnichannel/appearance/AppearancePage.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-appearance.ts
Labels: stat: ready to merge, stat: QA assured

#34055 chore: Drop unused type declarations and type exports
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/importer/server/classes/converters/UserConverter.ts
  apps/meteor/app/livechat/server/lib/localTypes.ts
  apps/meteor/app/push/server/push.ts
  apps/meteor/app/statistics/server/lib/getAppsStatistics.ts
  apps/meteor/client/apps/@types/IOrchestrator.ts
  apps/meteor/client/contexts/ImageGalleryContext.ts
  apps/meteor/client/lib/cachedCollections/CachedCollection.ts
  apps/meteor/client/lib/minimongo/types.ts
  apps/meteor/client/views/admin/mailer/MailerPage.tsx
  apps/meteor/client/views/admin/subscription/components/InfoTextIconModal.tsx
  apps/meteor/client/views/admin/subscription/components/UsagePieGraph.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.tsx
  apps/meteor/client/views/room/Sidepanel/SidepanelItem/RoomSidepanelItem.tsx
  apps/meteor/client/views/room/contexts/UserCardContext.ts
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.tsx
Labels: stat: ready to merge, stat: QA assured

#34025 regression: `lastChat` property missing on contact channel migrated from visitor
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
Labels: stat: ready to merge, stat: QA assured

#33906 fix: Language Options Sorting by Using 'Name' Property.
  .changeset/strange-bulldogs-roll.md
  apps/meteor/client/providers/TranslationProvider.tsx
  apps/meteor/client/views/account/preferences/PreferencesLocalizationSection.tsx
Labels: stat: ready to merge, stat: QA assured

#33993 regression: Use visitor activity to define if its contact is unknown
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
Labels: stat: ready to merge, stat: QA assured

#33939 regression: Update and notify subscriptions on contact name update
  apps/meteor/app/lib/server/lib/notifyListener.ts
  apps/meteor/app/livechat/server/lib/contacts/updateContact.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-info.spec.ts
  apps/meteor/tests/end-to-end/api/livechat/contacts.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA assured

#34060 fix: Premium settings using wrong `Tag` variant in Omnichannel
  .changeset/lucky-mirrors-tickle.md
  apps/meteor/client/views/omnichannel/appearance/AppearanceFieldLabel.tsx
  apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx
Labels: stat: ready to merge, stat: QA assured

#34056 chore(deps): Upgrade Yarn
  .yarn/releases/yarn-4.5.0.cjs
  .yarn/releases/yarn-4.5.3.cjs
  .yarnrc.yml
  package.json
  packages/livechat/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34030 regression: Do not throw an error on custom fields validation when migrating visitors to contacts
  apps/meteor/app/livechat/server/lib/contacts/ContactMerger.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
  apps/meteor/app/livechat/server/lib/contacts/validateCustomFields.spec.ts
  apps/meteor/app/livechat/server/lib/contacts/validateCustomFields.ts
Labels: stat: ready to merge, stat: QA assured

#34052 test: Missing setting clean-up in Livechat autoselection test
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-queue-management-autoselection.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33766 chore: Remove hideRoom client meteor method
  apps/meteor/client/hooks/useHideRoomAction.tsx
  apps/meteor/client/lib/mutationEffects/updateSubscription.ts
  apps/meteor/client/methods/hideRoom.ts
  apps/meteor/client/methods/index.ts
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/sidebarv2/RoomMenu.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomHide.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/useRoomActions.ts
  apps/meteor/client/views/teams/contextualBar/info/TeamsInfoWithData.tsx
Labels: stat: ready to merge, stat: QA assured

#34068 fix: videoconf ringer fails to accept calls after a logout/login
  .changeset/strange-countries-carry.md
  apps/meteor/client/lib/VideoConfManager.ts
Labels: stat: ready to merge, stat: QA assured

#34071 regression: Do not throw an error when a required custom field is missing on visitor to contact migration
  apps/meteor/app/livechat/server/lib/contacts/createContact.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts
  apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
Labels: stat: ready to merge, stat: QA assured

#34066 test: improve locator of sidebar collapser
  apps/meteor/tests/e2e/feature-preview.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/sidebar.ts
Labels: stat: ready to merge, stat: QA assured

#34084 chore: remove sidepanel item warnings
  apps/meteor/client/sidebarv2/Item/Condensed.tsx
  apps/meteor/client/sidebarv2/Item/Medium.tsx
  apps/meteor/client/views/room/Sidepanel/hooks/useItemData.tsx
Labels: stat: ready to merge, stat: QA assured

#34019 chore: remove meteor.startup from pin-message
  apps/meteor/client/components/message/hooks/usePinMessageMutation.ts
  apps/meteor/client/components/message/toolbar/MessageToolbar.tsx
  apps/meteor/client/components/message/toolbar/usePinMessageAction.tsx
  apps/meteor/client/lib/queryKeys.ts
  apps/meteor/client/startup/actionButtons/index.ts
  apps/meteor/client/startup/actionButtons/pinMessage.tsx
Labels: stat: ready to merge, stat: QA assured
