Repository RocketChat/Rocket.Chat, pull requests merged in 2024-06, with the labels that each got.

#32499 fix: `codeBlock` styles in light mode
  .changeset/five-shoes-fly.md
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
  apps/meteor/client/views/root/MainLayout/MainLayoutStyleTags.spec.tsx
  apps/meteor/client/views/root/MainLayout/MainLayoutStyleTags.tsx
  apps/meteor/client/views/root/lib/codeBlockStyles.ts
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32525 chore: Deprecate `banners.getNew` endpoint
  apps/meteor/app/api/server/v1/banners.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#32504 refactor: LivechatDepartmentAgents out of DB Watcher
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/app/lib/server/lib/notifyListener.ts
  apps/meteor/app/livechat/server/hooks/afterAgentRemoved.ts
  apps/meteor/app/livechat/server/lib/Departments.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/server/database/watchCollections.ts
  apps/meteor/server/models/dummy/BaseDummy.ts
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  packages/model-typings/src/models/IBaseModel.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
Labels: stat: ready to merge, stat: QA assured

#32376 fix: Moderators with `Bypass Time limits` permission cannot edit messages
  .changeset/eighty-wasps-kneel.md
  apps/meteor/app/authorization/server/functions/canDeleteMessage.ts
  apps/meteor/app/lib/server/methods/updateMessage.ts
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/lib/chats/data.ts
  apps/meteor/client/methods/updateMessage.ts
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useMessageDeletionIsAllowed.ts
Labels: stat: ready to merge, stat: QA assured

#32565 Bump to 6.10.0-develop
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
Labels: stat: ready to merge, stat: QA assured

#32534 fix: Installed apps not appearing in the list if they're not published in the Marketplace
  .changeset/short-coins-enjoy.md
  apps/meteor/client/providers/AppsProvider/AppsProvider.spec.ts
  apps/meteor/client/providers/AppsProvider/AppsProvider.tsx
  apps/meteor/client/providers/AppsProvider/index.ts
  apps/meteor/client/providers/AppsProvider/storeQueryFunction.ts
  apps/meteor/tests/mocks/data/marketplace.ts
Labels: stat: ready to merge, stat: QA assured

#32106 fix: Image gallery moves to older images when clicking on the right arrow button
  .changeset/tidy-apes-fry.md
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
  apps/meteor/tests/e2e/fixtures/files/number1.png
  apps/meteor/tests/e2e/fixtures/files/number2.png
  apps/meteor/tests/e2e/fixtures/files/number3.png
  apps/meteor/tests/e2e/fixtures/files/number4.png
  apps/meteor/tests/e2e/fixtures/files/number5.png
  apps/meteor/tests/e2e/fixtures/files/number6.png
  apps/meteor/tests/e2e/image-gallery.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#31363 fix: remove reason when password change is set to false
  .changeset/wild-carrots-know.md
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/tests/data/users.helper.js
  apps/meteor/tests/end-to-end/api/01-users.js
Labels: stat: ready to merge, stat: QA assured

#32578 regression: Fixed image gallery not working on Electron app
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
Labels: stat: ready to merge, squad: core, stat: QA assured

#32552 fix: Using the banner _id field as a fallback for the view.viewId field
  .changeset/late-drinks-brake.md
  apps/meteor/server/services/banner/service.ts
  apps/meteor/tests/unit/server/services/banner/service.tests.ts
Labels: stat: ready to merge, stat: QA assured

#32175 fix(Omnichannel): Omnichannel agent `take it` button
  .changeset/forty-ghosts-flow.md
  apps/meteor/client/views/room/composer/ComposerOmnichannel/ComposerOmnichannelInquiry.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-changing-room-priority-and-sla.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-close-inquiry.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-takeChat.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: QA assured

#32430 fix: OTR conversation closes automatically when any of the peers goes offline
  apps/meteor/app/otr/client/OTR.ts
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/app/otr/client/events.ts
  apps/meteor/app/otr/client/index.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32581 regression: Disable animation on image gallery pagination transition
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
Labels: stat: ready to merge, squad: core, stat: QA assured

#32572 fix(Omnichannel): nonstop sound on current chats using continuous notifications
  .changeset/thin-suns-invent.md
  apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
Labels: stat: ready to merge, stat: QA assured

#32303 test: Add Omnichannel Business Hours E2E tests
  apps/meteor/tests/e2e/omnichannel/omnichannel-business-hours.spec.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-business-hours.ts
  apps/meteor/tests/e2e/utils/omnichannel/businessHours.ts
Labels: stat: ready to merge, stat: QA assured

#32587 fix: Run QueryClient.clear() on logout
  .changeset/fuzzy-readers-bake.md
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-enterprise-menus-logout.spec.ts
Labels: stat: ready to merge, stat: QA assured

#31859 feat: Limit of members that can be added using the autojoin feature in a team's channel to the value of the API_Users_Limit setting
  .changeset/clean-moose-cover.md
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannelItem.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannelItemMenu.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannelsWithData.tsx
  apps/meteor/client/views/teams/contextualBar/channels/hooks/useToggleAutoJoin.tsx
  apps/meteor/server/services/team/service.ts
  apps/meteor/tests/data/teams.helper.ts
  apps/meteor/tests/end-to-end/api/25-teams.js
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32589 chore: disable db watchers on local envs
  packages/core-services/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#32556 test: Rewrote the rooms.helper file in typescript
  apps/meteor/tests/data/rooms.helper.js
  apps/meteor/tests/data/rooms.helper.ts
  apps/meteor/tests/data/uploads.helper.ts
  apps/meteor/tests/end-to-end/api/05-chat.js
  apps/meteor/tests/end-to-end/api/07-incoming-integrations.js
  apps/meteor/tests/end-to-end/api/16-commands.js
  apps/meteor/tests/end-to-end/apps/05-video-conferences.ts
Labels: stat: ready to merge, stat: QA assured

#32569 chore: change e2e password placeholder
  apps/meteor/client/views/e2e/EnterE2EPasswordModal.tsx
  packages/i18n/src/locales/ar.i18n.json
  packages/i18n/src/locales/ca.i18n.json
  packages/i18n/src/locales/cs.i18n.json
  packages/i18n/src/locales/da.i18n.json
  packages/i18n/src/locales/de-IN.i18n.json
  packages/i18n/src/locales/de.i18n.json
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/es.i18n.json
  packages/i18n/src/locales/fi.i18n.json
  packages/i18n/src/locales/fr.i18n.json
  packages/i18n/src/locales/hr.i18n.json
  packages/i18n/src/locales/hu.i18n.json
  packages/i18n/src/locales/ja.i18n.json
  packages/i18n/src/locales/ka-GE.i18n.json
  packages/i18n/src/locales/km.i18n.json
  packages/i18n/src/locales/ko.i18n.json
  packages/i18n/src/locales/nl.i18n.json
  packages/i18n/src/locales/pl.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/i18n/src/locales/pt.i18n.json
  packages/i18n/src/locales/ru.i18n.json
  packages/i18n/src/locales/sv.i18n.json
  packages/i18n/src/locales/tr.i18n.json
  packages/i18n/src/locales/uk.i18n.json
  packages/i18n/src/locales/zh-TW.i18n.json
  packages/i18n/src/locales/zh.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32459 fix: prevent OTR in E2EE
  .changeset/famous-scissors-teach.md
  apps/meteor/client/hooks/roomActions/useE2EERoomAction.spec.ts
  apps/meteor/client/hooks/roomActions/useE2EERoomAction.ts
  apps/meteor/client/hooks/useOTR.spec.tsx
  apps/meteor/client/hooks/useOTR.ts
  apps/meteor/client/views/room/contextualBar/OTR/OTR.tsx
  apps/meteor/client/views/room/contextualBar/OTR/OTRWithData.tsx
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32585 chore: bump meteor 2.16
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/release
  apps/meteor/.meteor/versions
  apps/meteor/packages/flow-router/.npm/package/npm-shrinkwrap.json
Labels: stat: ready to merge, stat: QA assured

#32478 fix: Accepted Media Types settings validation
  .changeset/chilly-toys-hunt.md
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/utils/client/restrictions.ts
  apps/meteor/app/utils/lib/restrictions.ts
  apps/meteor/app/utils/server/restrictions.ts
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
  apps/meteor/tests/unit/app/utils/lib/restrictions.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32432 chore: remove message column on moderation console
  apps/meteor/client/views/admin/moderation/ModerationConsoleTable.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleTableRow.tsx
Labels: stat: ready to merge, stat: QA assured

#32431 fix: sidebar last message E2EE
  .changeset/lastmessage-e2ee.md
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/server/models/raw/Messages.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  packages/model-typings/src/models/IMessagesModel.ts
Labels: stat: ready to merge, stat: QA assured

#32507 fix: Force highlighted code language registration
  .changeset/weak-books-tell.md
  apps/meteor/client/hooks/useHighlightedCode.ts
  apps/meteor/client/views/admin/integrations/IntegrationsTable.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
  apps/meteor/tests/e2e/utils/index.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32113 chore: Add telemetry to CI so we can get a better understanding of resource usage
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci-test-unit.yml
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA assured

#32381 fix: E2EE thread main message reactivity
  .changeset/three-squids-brake.md
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA assured

#32446 feat: E2EE room setup header
  .changeset/gold-flowers-shake.md
  apps/meteor/client/ui.ts
  apps/meteor/client/views/room/Header/Header.tsx
  apps/meteor/client/views/room/Header/RoomHeader.tsx
  apps/meteor/client/views/room/Header/RoomHeaderE2EESetup.tsx
  apps/meteor/client/views/room/Header/RoomToolbox/RoomToolboxE2EESetup.tsx
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
Labels: stat: ready to merge, stat: QA assured

#31821 feat: Apps-Engine Deno Runtime update
  .changeset/tame-weeks-shout.md
  .github/actions/setup-node/action.yml
  apps/meteor/.docker/Dockerfile
  apps/meteor/.docker/Dockerfile.alpine
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/apps/server/bridges/http.ts
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/app/statistics/server/lib/getAppsStatistics.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/ee/lib/misc/formatAppInstanceForRest.ts
  apps/meteor/ee/server/apps/communication/endpoints/appsCountHandler.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/communication/websockets.ts
  apps/meteor/ee/server/apps/cron.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/storage/AppRealLogStorage.ts
  apps/meteor/ee/server/apps/storage/index.js
  apps/meteor/ee/server/apps/storage/logs-storage.js
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/tests/end-to-end/apps/02-send-messages-as-user.js
  docker-compose-ci.yml
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/model-typings/src/models/IAppLogsModel.ts
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32547 fix: Not possible to edit room without proper permission with retention policy enabled
  .changeset/nervous-wolves-collect.md
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/useEditRoomInitialValues.ts
  apps/meteor/tests/e2e/retention-policy.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32522 fix: prevent broadcasting of system messages when hide setting is enabled
  .changeset/grumpy-games-greet.md
  apps/meteor/app/lib/server/functions/loadMessageHistory.ts
  apps/meteor/app/lib/server/lib/getHiddenSystemMessages.ts
  apps/meteor/app/lib/server/methods/getChannelHistory.ts
  apps/meteor/server/lib/systemMessage/hideSystemMessage.ts
  apps/meteor/server/modules/watchers/lib/messages.ts
  apps/meteor/tests/unit/app/lib/server/lib/getHiddenSystemMessage.spec.ts
  apps/meteor/tests/unit/server/lib/systemMessage/hideSystemMessage.spec.ts
  apps/meteor/tests/unit/server/modules/watchers/lib/messages.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32619 regression: don't notify role changes during startup
  apps/meteor/server/lib/roles/createOrUpdateProtectedRole.ts
Labels: stat: ready to merge, stat: QA assured

#32610 fix: Supported Versions misbehaving
  .changeset/dry-shoes-tap.md
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsChooseLatest.ts
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts
  apps/meteor/jest.config.ts
  apps/meteor/packages/rocketchat-version/plugin/compile-version.js
Labels: stat: ready to merge, stat: QA assured

#32452 fix: `QueueInactivityMonitor` not processing inquiries
  .changeset/green-camels-repair.md
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterInquiryQueued.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/hooks/afterInquiryQueued.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32329 fix: PDFs uploaded by "PDF transcript" feature were returnig 403 when attempting to download
  .changeset/rude-llamas-notice.md
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/server/settings/file-upload.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32471 feat: Use `application/octet-stream` as a fallback media type to avoid "Unknown media type" errors
  .changeset/breezy-pens-sing.md
  apps/meteor/app/api/server/lib/getUploadFormData.ts
  apps/meteor/app/utils/lib/mimeTypes.ts
  apps/meteor/client/views/room/body/hooks/useFileUploadDropTarget.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useFileUploadAction.ts
  apps/meteor/server/settings/file-upload.ts
  apps/meteor/tests/data/interactions.ts
  apps/meteor/tests/e2e/file-upload.spec.ts
  apps/meteor/tests/e2e/fixtures/files/diagram.drawio
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, squad: core, stat: QA assured

#32566 fix(Omnichannel): Contact Center sort by date
  .changeset/proud-coats-repair.md
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
Labels: stat: ready to merge, stat: QA assured

#32625 fix: Settings code mirror broken on full screen mode
  .changeset/odd-goats-fix.md
  apps/meteor/client/components/CustomScrollbars/CustomScrollbars.tsx
  apps/meteor/client/components/CustomScrollbars/VirtuosoScrollbars.tsx
  apps/meteor/client/views/admin/settings/inputs/CodeMirror/CodeMirrorBox.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA assured

#32548 feat: Disable slash commands for encrypted rooms
  .changeset/popular-bulldogs-accept.md
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/lib/chats/flows/sendMessage.ts
  apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupSlashCommand.tsx
  apps/meteor/client/views/room/composer/ComposerMessage.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/contexts/ComposerPopupContext.ts
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32624 fix: Enable encryption for direct/private rooms by default is overriding E2EE setting
  .changeset/happy-cameras-mix.md
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
Labels: stat: ready to merge, stat: QA assured

#32559 feat: Disable some message menu items for encrypted messages.
  .changeset/plenty-buses-kneel.md
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/client/components/GenericMenu/GenericMenu.tsx
  apps/meteor/client/components/GenericMenu/GenericMenuItem.tsx
  apps/meteor/client/components/message/toolbar/MessageActionMenu.tsx
  apps/meteor/client/components/message/toolbar/MessageToolbar.tsx
  apps/meteor/package.json
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/i18n/src/locales/en.i18n.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32612 fix: Emoji picker's object and symbols category icon swapped
  .changeset/red-cheetahs-heal.md
  apps/meteor/client/views/composer/EmojiPicker/EmojiPickerCategoryItem.tsx
Labels: stat: ready to merge, stat: QA assured

#32641 regression: Incorrect translation of room data on listeners of message events
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32485 fix: Override retention policy missing ignore threads option
  .changeset/rare-dancers-own.md
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/useEditRoomInitialValues.ts
  apps/meteor/client/views/room/hooks/useRetentionPolicy.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/retention-policy.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32605 feat: Change Quote Position
  .changeset/nasty-windows-reply.md
  apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
  apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
Labels: stat: ready to merge, stat: QA assured

#32604 feat: Upgrade `fuselage-toastbar` adding RTL support
  .changeset/spotty-seals-whisper.md
  apps/meteor/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32358 refactor: LivechatInquiry out of DB Watcher
  apps/meteor/app/lib/server/lib/notifyListener.ts
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/app/livechat/server/hooks/saveLastMessageToInquiry.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/ee/app/livechat-enterprise/server/services/omnichannel.internalService.ts
  apps/meteor/server/database/watchCollections.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/services/omnichannel/queue.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
Labels: stat: ready to merge, stat: QA assured

#32563 fix(Marketplace): Wrong modal if app already purchased
  .changeset/five-monkeys-applaud.md
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
Labels: stat: QA assured

#32428 fix: saveSettings endpoint allowing NaN to be stored on Int settings
  .changeset/happy-windows-drum.md
  apps/meteor/app/lib/server/methods/saveSettings.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
  apps/meteor/tests/e2e/settings-int.spec.ts
  apps/meteor/tests/end-to-end/api/24-methods.js
Labels: stat: QA assured

#32436 feat: Add LDAP group validation strategy setting to channels and roles sync
  .changeset/mighty-oranges-wait.md
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/settings/ldap.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: QA assured

#32640 fix: Modal backdrop overlapping `Select` options
  .changeset/heavy-dolphins-lie.md
  apps/meteor/client/components/GenericMenu/GenericMenu.tsx
  apps/meteor/client/components/GenericMenu/hooks/useHandleMenuAction.tsx
  apps/meteor/client/components/ModalBackdrop.tsx
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
Labels: stat: ready to merge, stat: QA assured

#32152 fix: cleaning the room filter between navigation on the admin section
  .changeset/brown-lobsters-join.md
  apps/meteor/client/views/admin/rooms/RoomsTableFilters.tsx
  apps/meteor/tests/e2e/admin-room.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomAnchor.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomListWrapper.tsx
Labels: stat: ready to merge, stat: QA assured

#32551 feat: E2EE warnings on search and audit panel
  .changeset/friendly-months-attack.md
  apps/meteor/app/api/server/lib/rooms.ts
  apps/meteor/app/lib/server/functions/notifications/email.js
  apps/meteor/client/components/RoomAutoComplete/RoomAutoComplete.tsx
  apps/meteor/client/lib/getRoomTypeTranslation.ts
  apps/meteor/client/views/audit/AuditPage.tsx
  apps/meteor/client/views/audit/components/AuditForm.tsx
  apps/meteor/client/views/audit/components/tabs/RoomsTab.tsx
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearchForm.tsx
  packages/core-typings/src/IRoom.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32458 fix: `EditRoomInfo` encrypted field placement
  .changeset/shy-eyes-march.md
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/useEditRoomPermissions.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
Labels: stat: ready to merge, stat: QA assured

#32316 feat(E2EEncryption): File encryption support
  .changeset/metal-cats-suffer.md
  .vscode/settings.json
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/e2e/client/helper.js
  apps/meteor/app/e2e/client/rocketchat.e2e.room.js
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/app/lib/server/methods/sendMessage.ts
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentDownload.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentDownloadBase.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentEncryptedDownload.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentImage.tsx
  apps/meteor/client/components/message/hooks/useNormalizedMessage.ts
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
  apps/meteor/client/hooks/useDownloadFromServiceWorker.ts
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/lib/chats/data.ts
  apps/meteor/client/lib/chats/flows/sendMessage.ts
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
  apps/meteor/client/lib/chats/uploads.ts
  apps/meteor/client/startup/e2e.ts
  apps/meteor/client/views/room/ImageGallery/hooks/useImagesList.ts
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItem.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/components/FileItemMenu.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useFilesList.ts
  apps/meteor/package.json
  apps/meteor/public/enc.js
  apps/meteor/server/cron/temporaryUploadsCleanup.ts
  apps/meteor/server/models/raw/BaseUploadModel.ts
  apps/meteor/server/routes/fileDecrypt.ts
  apps/meteor/server/routes/index.ts
  apps/meteor/server/startup/cron.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/fixtures/collections/users.ts
  apps/meteor/tests/e2e/fixtures/inject-initial-data.ts
  apps/meteor/tests/e2e/fixtures/userStates.ts
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/core-typings/src/IMessage/IMessage.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentBase.ts
  packages/core-typings/src/IUpload.ts
  packages/model-typings/src/models/IBaseUploadsModel.ts
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#32380 fix: Handle encrypted pinned messages
  .changeset/forty-bikes-check.md
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/client/components/message/StatusIndicators.tsx
  apps/meteor/client/startup/e2e.ts
  apps/meteor/client/startup/messageTypes.ts
  apps/meteor/client/views/room/contextualBar/PinnedMessagesTab.tsx
  apps/meteor/client/views/room/contextualBar/StarredMessagesTab.tsx
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: ready to merge, stat: QA assured

#32197 feat(E2EE): Async E2EE keys exchange
  .changeset/orange-clocks-raise.md
  apps/meteor/app/api/server/v1/e2e.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.room.js
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/e2e/server/functions/handleSuggestedGroupKey.ts
  apps/meteor/app/e2e/server/functions/provideUsersSuggestedGroupKeys.ts
  apps/meteor/app/e2e/server/methods/setUserPublicAndPrivateKeys.ts
  apps/meteor/app/e2e/server/methods/updateGroupKey.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/client/startup/e2e.ts
  apps/meteor/client/views/teams/contextualBar/channels/hooks/useTeamsChannelList.ts
  apps/meteor/lib/publishFields.ts
  apps/meteor/server/lib/resetUserE2EKey.ts
  apps/meteor/server/methods/removeUserFromRoom.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  packages/core-typings/src/IRoom.ts
  packages/i18n/src/locales/en.i18n.json
  packages/model-typings/src/models/IRoomsModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/e2e.ts
Labels: stat: ready to merge, stat: QA assured

#32542 refactor!: removed listEmojiCustom method
  apps/meteor/app/emoji-custom/server/index.ts
  apps/meteor/app/emoji-custom/server/methods/listEmojiCustom.ts
Labels: stat: ready to merge, stat: QA assured

#32670 regression: Fix encrypted file upload ignoring enabling setting
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
Labels: stat: ready to merge, stat: QA assured

#32626 fix(Livechat): Restore missing setDepartment livechat API endpoint functionality
  .changeset/funny-snails-promise.md
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts
  packages/livechat/src/components/Form/CustomFields/index.tsx
  packages/livechat/src/components/Form/SelectInput/index.tsx
  packages/livechat/src/lib/hooks.ts
  packages/livechat/src/routes/Chat/container.js
  packages/livechat/src/routes/Register/index.tsx
  packages/livechat/src/store/index.tsx
Labels: stat: ready to merge, stat: QA assured

#32681 test: close pages properly
  apps/meteor/tests/e2e/admin-room.spec.ts
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
Labels: stat: ready to merge, stat: QA assured

#32674 regression(E2EEncryption): Service Worker not installing on first load
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
  apps/meteor/client/main.ts
  apps/meteor/client/serviceWorker.ts
  apps/meteor/public/enc.js
Labels: stat: ready to merge, stat: QA assured

#32680 regression: Notifier accessor proxy and not rethrowing internal JSON-RPC errors
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32694 regression: Email notification for end-to-end encrypted message
  apps/meteor/app/lib/server/functions/notifications/email.js
  apps/meteor/tests/unit/app/mailer/getEmailContent.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32702 ci: update EE license
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA assured
