Repository RocketChat/Rocket.Chat, pull requests merged in 2024-01, with the labels that each got.

#31262 fix: Text area only shows the last line of the message for very long texts #31252 #31257
  apps/meteor/client/views/room/composer/RoomComposer/hooks/useAutoGrow.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31346 fix: No error message when uploading a file that is not allowed
  .changeset/lemon-shrimps-draw.md
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31344 fix: close image gallery on backdrop click
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31329 Release 6.5.2
  .changeset/bump-patch-1703700471583.md
  .changeset/three-moles-look.md
  .changeset/tiny-glasses-help.md
  .github/workflows/pr-update-description.yml
  apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  packages/release-action/src/index.ts
  packages/release-action/src/updatePRDescription.ts
  yarn.lock
Labels: stat: needs QA

#31356 chore: Replace `FramedIcon` in favor of fuselage component
  apps/meteor/client/components/GenericCard/GenericCard.tsx
  apps/meteor/client/views/admin/subscription/components/cards/FeaturesCard.tsx
  apps/meteor/client/views/admin/workspace/UsersUploadsCard/UsersUploadsCard.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/components/VersionCardActionItem.tsx
  packages/ui-client/src/components/FramedIcon.tsx
  packages/ui-client/src/components/index.ts
Labels: stat: ready to merge, stat: QA skipped

#31248 fix: engagement dashboard timezone selector
  .changeset/rude-spoons-pump.md
  apps/meteor/ee/client/views/admin/engagementDashboard/users/UsersByTimeOfTheDaySection.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#31249 chore: add aria-label to Select Inputs at Engagement Dashboard
  apps/meteor/ee/client/components/dashboards/PeriodSelector.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardPage.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/BusiestChatTimesSection.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#31318 fix: Attachments not collapsing when using incoming webhook
  .changeset/attachment-collapse.md
  apps/meteor/client/components/message/content/Attachments.tsx
  apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx
Labels: stat: ready to merge, communityPR, stat: QA tested

#31279 feat: Add Desktop PDF viewer
  apps/meteor/client/components/message/content/attachments/file/GenericFileAttachment.tsx
  apps/meteor/client/definitions/IRocketChatDesktop.ts
  apps/meteor/client/definitions/global.d.ts
  apps/meteor/client/lib/utils/window.RocketChatDesktop.d.ts
Labels: stat: ready to merge, stat: QA skipped

#31373 regression: `AppRow` bundleIn verification
  apps/meteor/client/views/marketplace/AppsList/AppRow.tsx
Labels: stat: ready to merge, stat: QA skipped

#30406 i18n: adds video call translations for Persian language
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#29462 i18n: update translations
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#31376 test: bump playwright
  .github/workflows/ci-test-e2e.yml
  apps/meteor/package.json
  yarn.lock
Labels: stat: needs QA

#31375 chore: services changes on lifecycle methods + throw if svc is not available
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/ee/server/NetworkBroker.ts
  apps/meteor/ee/server/local-services/instance/service.ts
  apps/meteor/server/services/authorization/service.ts
  ee/apps/ddp-streamer/src/DDPStreamer.ts
  ee/apps/ddp-streamer/src/configureServer.ts
  packages/core-services/src/LocalBroker.ts
Labels: stat: needs QA

#31270 fix: not being able to access or create rooms with join code
  .changeset/stale-monkeys-yell.md
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/services/room/service.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  packages/model-typings/src/models/IRoomsModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31348 feat: added modal confirmation before pinning message
  .changeset/swift-beans-reflect.md
  apps/meteor/client/startup/actionButtons/pinMessage.tsx
  apps/meteor/client/views/room/modals/PinMessageModal/PinMessageModal.tsx
  apps/meteor/client/views/room/modals/PinMessageModal/index.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31222 feat: Allow user to set timeout of outgoing webhook
  apps/meteor/app/integrations/server/lib/triggerHandler.js
Labels: stat: ready to merge, stat: QA skipped

#30921 chore: add gitpod config file for quick setup
  .gitpod.yml
  README.md
Labels: stat: ready to merge, stat: QA skipped

#31387 fix: Editing room type or name doesn't always refresh the room
  .changeset/nice-points-notice.md
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useRedirectOnSettingsChanged.ts
Labels: stat: ready to merge, stat: QA skipped

#31384 fix: Admin's edit room form not triggering
  .changeset/breezy-ladybugs-sip.md
  apps/meteor/client/views/admin/emailInbox/EmailInboxForm.tsx
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/rooms/useEditAdminRoomPermissions.ts
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA skipped

#31388 chore: remove RedHat stuff
  .github/workflows/ci.yml
  apps/meteor/.docker/Dockerfile.rhel
  package.json
Labels: stat: QA skipped

#31393 fix: Disable quote avatars according to user preference
  .changeset/itchy-zoos-appear.md
  apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx
Labels: stat: ready to merge, stat: QA skipped

#31332 fix: Dropping a file from another browser window creates two upload dialogs
  .changeset/clean-melons-return.md
  apps/meteor/client/views/room/body/hooks/useFileUploadDropTarget.ts
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31389 fix: room avatar UnHandledPromiseRejection
  apps/meteor/server/ufs/ufs-methods.ts
Labels: stat: ready to merge, stat: QA skipped

#31184 feat: Hide UI elements through window postmessage
  .changeset/big-teachers-change.md
  apps/meteor/app/ui-utils/client/lib/messageBox.ts
  apps/meteor/client/components/message/toolbox/MessageToolbox.tsx
  apps/meteor/client/hooks/useAppActionButtons.ts
  apps/meteor/client/hooks/useFileInput.ts
  apps/meteor/client/providers/LayoutProvider.tsx
  apps/meteor/client/views/room/Header/RoomToolbox/RoomToolbox.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/ToolbarAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useAudioMessageAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useCreateDiscussionAction.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useFileUploadAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useShareLocationAction.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useToolbarActions.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useVideoMessageAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useWebdavActions.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/useUserInfoActions.ts
  apps/meteor/client/views/room/providers/RoomToolboxProvider.tsx
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  packages/ui-contexts/src/LayoutContext.ts
  packages/ui-contexts/src/hooks/useLayoutHiddenActions.ts
  packages/ui-contexts/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#31345 refactor: Subscribe to only one stream at a time
  apps/meteor/app/utils/client/lib/SDKClient.ts
  apps/meteor/client/providers/ServerProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#31395 chore: Refactor `app.getStatus()` usages
  apps/meteor/app/metrics/server/lib/collectMetrics.ts
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/communication/websockets.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/server/services/apps-engine/service.ts
Labels: stat: needs QA

#31371 fix: login buttons remain visible until refresh after disabling authentication service
  .changeset/little-planes-wonder.md
  apps/meteor/packages/rocketchat-mongo-config/server/index.js
  apps/meteor/server/modules/watchers/watchers.module.ts
  apps/meteor/server/services/meteor/service.ts
  apps/meteor/tests/e2e/fixtures/inject-initial-data.ts
  apps/meteor/tests/e2e/oauth.spec.ts
  apps/meteor/tests/e2e/page-objects/auth.ts
  apps/meteor/tests/end-to-end/api/08-settings.js
  ee/apps/ddp-streamer/src/DDPStreamer.ts
  packages/core-services/src/events/Events.ts
Labels: stat: ready to merge, stat: QA skipped

#31366 chore: internalize meteor cookies (from meteor 3)
  apps/meteor/packages/meteor-cookies/cookies.js
  apps/meteor/packages/meteor-cookies/package.js
Labels: stat: ready to merge, stat: QA skipped

#31367 chore: internalize meteor inject initial (from meteor 3)
  apps/meteor/packages/meteor-inject-initial/lib/inject-core.js
  apps/meteor/packages/meteor-inject-initial/lib/inject-server.js
  apps/meteor/packages/meteor-inject-initial/package.js
Labels: stat: ready to merge, stat: QA skipped

#31370 chore: internalize meteor run as user (from meteor 3)
  apps/meteor/packages/meteor-run-as-user/lib/collection.overwrites.js
  apps/meteor/packages/meteor-run-as-user/lib/common.js
  apps/meteor/packages/meteor-run-as-user/lib/pre.1.0.3.js
  apps/meteor/packages/meteor-run-as-user/package.js
Labels: stat: ready to merge, stat: QA skipped

#31365 chore: internalize flow-router (from meteor 3 branch)
  apps/meteor/packages/flow-router/.gitignore
  apps/meteor/packages/flow-router/.npm/package/.gitignore
  apps/meteor/packages/flow-router/.npm/package/README
  apps/meteor/packages/flow-router/.npm/package/npm-shrinkwrap.json
  apps/meteor/packages/flow-router/client/_init.js
  apps/meteor/packages/flow-router/client/group.js
  apps/meteor/packages/flow-router/client/modules.js
  apps/meteor/packages/flow-router/client/route.js
  apps/meteor/packages/flow-router/client/router.js
  apps/meteor/packages/flow-router/client/triggers.js
  apps/meteor/packages/flow-router/lib/router.js
  apps/meteor/packages/flow-router/package.js
  apps/meteor/packages/flow-router/server/_init.js
  apps/meteor/packages/flow-router/server/group.js
  apps/meteor/packages/flow-router/server/plugins/fast_render.js
  apps/meteor/packages/flow-router/server/route.js
  apps/meteor/packages/flow-router/server/router.js
Labels: stat: ready to merge, stat: QA skipped

#31369 feat: add `ImageGallery` zoom controls
  .changeset/funny-buses-own.md
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
Labels: stat: ready to merge, stat: QA skipped

#31412 fix: async operations
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/ee/lib/misc/formatAppInstanceForRest.ts
  apps/meteor/ee/server/apps/communication/endpoints/appsCountHandler.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/cron.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/package.json
  apps/meteor/server/services/apps-engine/service.ts
  yarn.lock
Labels: stat: needs QA

#31413 fix: multiple indexes creations during migrations
  .changeset/fresh-maps-rhyme.md
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/startup/migrations/v304.ts
Labels: stat: ready to merge, stat: QA skipped

#31343 refactor(i18n): Translation's lint and load
  apps/meteor/.scripts/check-i18n.js
  apps/meteor/.scripts/translation-check.ts
  apps/meteor/.scripts/translation-diff.ts
  apps/meteor/.scripts/translation-fix-order.ts
  apps/meteor/app/utils/lib/i18n.ts
  apps/meteor/client/lib/utils/applyCustomTranslations.ts
  apps/meteor/client/providers/TranslationProvider.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/mn.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
  apps/meteor/server/lib/i18n.ts
  apps/meteor/server/settings/email.ts
  packages/i18n/src/index.mjs
  packages/ui-contexts/package.json
  packages/ui-contexts/src/TranslationContext.ts
  packages/ui-contexts/src/en.json
  yarn.lock
Labels: stat: needs QA

#31374 chore: Replace `Dropdown` in favor of `MenuV2` on `MessageComposer`
  apps/meteor/client/components/GenericMenu/GenericMenu.tsx
  apps/meteor/client/components/GenericMenu/GenericMenuItem.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/ToolbarAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useAudioMessageAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useCreateDiscussionAction.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useFileUploadAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useShareLocationAction.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useToolbarActions.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useVideoMessageAction.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useWebdavActions.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxFormattingToolbar/FormattingToolbarDropdown.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxFormattingToolbar/MessageBoxFormattingToolbar.tsx
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/message-composer.spec.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-composer/src/MessageComposer/MessageComposerToolbar.tsx
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#29367 fix: Automate text direction based on the language in messages
  .changeset/cyan-penguins-listen.md
  apps/meteor/client/components/message/IgnoredContent.tsx
  apps/meteor/client/components/message/MessageContentBody.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
Labels: stat: ready to merge, stat: QA skipped

#31136 feat: new apps logger deno-runtime
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/storage/AppRealLogStorage.ts
  apps/meteor/ee/server/apps/storage/index.js
  apps/meteor/ee/server/apps/storage/logs-storage.js
  packages/model-typings/src/models/IAppLogsModel.ts
Labels: stat: needs QA

#31414 fix: Some Omnichannel charts not available when calling through endpoint
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/omnichannel-analytics/ChartData.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31431 chore: Add missing changeset file
  .changeset/silent-shirts-knock.md
Labels: stat: needs QA

#31440 chore(i18n): prevent error on `./dist` folder deletion
  packages/i18n/src/index.mjs
Labels: stat: needs QA

#31435 chore: Make room closing process more sequential
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31377 fix: LDAP Group filter doesn't work and throws "No Such Object" error on login
  .changeset/wet-crabs-brush.md
  apps/meteor/server/lib/ldap/Connection.ts
  apps/meteor/server/lib/ldap/Manager.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31439 chore: reorganize server imports
  apps/meteor/ee/app/license/server/index.ts
  apps/meteor/ee/app/license/server/startup.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/ee/server/models/startup.ts
  apps/meteor/ee/server/startup/apps/trialExpiration.ts
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/imports/personal-access-tokens/server/index.ts
  apps/meteor/imports/startup/server/index.ts
  apps/meteor/server/configureLogLevel.ts
  apps/meteor/server/main.ts
  apps/meteor/server/methods/index.ts
  apps/meteor/server/publications/index.ts
  apps/meteor/server/routes/index.ts
  apps/meteor/server/services/startup.ts
  apps/meteor/server/settings/index.ts
  apps/meteor/server/startup/index.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/xrun.ts
Labels: stat: needs QA

#31234 refactor(client): Move components from `app/` to `client/`
  apps/meteor/app/ui/client/lib/userCard.ts
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.tsx
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarSuggestion.ts
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarSuggestions.tsx
  apps/meteor/client/components/avatar/UserAvatarEditor/readFileAsDataURL.ts
  apps/meteor/client/components/avatar/UserAvatarEditor/useUserAvatarSuggestions.ts
  apps/meteor/client/hooks/roomActions/useOmnichannelExternalFrameRoomAction.ts
  apps/meteor/client/hooks/useAvatarSuggestions.ts
  apps/meteor/client/lib/portals/portalsSubscription.ts
  apps/meteor/client/views/omnichannel/ExternalFrameContainer.tsx
  apps/meteor/client/views/room/UserCardHolder.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupCannedResponse.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupEmoji.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupPreview.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupRoom.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupSlashCommand.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupUser.tsx
  apps/meteor/client/views/room/composer/hooks/useComposerBoxPopup.ts
  apps/meteor/client/views/room/composer/hooks/useComposerBoxPopupQueries.ts
  apps/meteor/client/views/room/composer/hooks/useEnablePopupPreview.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
  apps/meteor/server/methods/getAvatarSuggestion.ts
  package.json
  packages/rest-typings/src/v1/users.ts
  yarn.lock
Labels: stat: needs QA

#31453 chore: federation startup
  apps/meteor/ee/server/startup/services.ts
Labels: stat: needs QA

#31457 chore: app startup
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/startup.ts
Labels: stat: needs QA

#31458 chore: server import order
  apps/meteor/app/lib/server/startup/index.ts
  apps/meteor/app/lib/server/startup/oAuthServicesUpdate.js
  apps/meteor/server/main.ts
Labels: stat: needs QA

#31409 refactor: Replace `Notifications` in favor of `sdk.stream`;
  apps/meteor/app/e2e/client/rocketchat.e2e.room.js
  apps/meteor/app/emoji-custom/client/index.ts
  apps/meteor/app/emoji-custom/client/notifications/deleteEmojiCustom.ts
  apps/meteor/app/emoji-custom/client/notifications/updateEmojiCustom.ts
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/app/ui/client/lib/UserAction.ts
  apps/meteor/app/user-status/client/index.ts
  apps/meteor/app/user-status/client/notifications/deleteCustomUserStatus.js
  apps/meteor/app/user-status/client/notifications/updateCustomUserStatus.js
  apps/meteor/client/lib/settings/PrivateSettingsCachedCollection.ts
  apps/meteor/client/lib/userData.ts
  apps/meteor/client/providers/EmojiPickerProvider/EmojiPickerProvider.tsx
  apps/meteor/client/providers/EmojiPickerProvider/index.ts
  apps/meteor/client/providers/EmojiPickerProvider/useUpdateCustomEmoji.ts
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/providers/UserProvider/hooks/useDeleteUser.ts
  apps/meteor/client/providers/UserProvider/hooks/useUpdateAvatar.ts
  apps/meteor/client/providers/UserProvider/hooks/useUpdateCustomUserStatus.ts
  apps/meteor/client/startup/UserDeleted.ts
  apps/meteor/client/startup/e2e.ts
  apps/meteor/client/startup/forceLogout.ts
  apps/meteor/client/startup/incomingMessages.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/notifications/index.ts
  apps/meteor/client/startup/notifications/konchatNotifications.ts
  apps/meteor/client/startup/notifications/updateAvatar.ts
  apps/meteor/client/startup/notifications/usersNameChanged.ts
  apps/meteor/client/startup/userRoles.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useUsersNameChanged.ts
  ee/packages/ddp-client/src/types/streams.ts
Labels: stat: ready to merge, stat: QA skipped

#31461 chore: Add missing changeset
  .changeset/witty-dogs-share.md
Labels: stat: ready to merge, stat: QA skipped

#31432 fix: update SHIFT+ESCAPE handler for consistent clear unread modal display
  .changeset/many-dolphins-deny.md
  apps/meteor/client/views/root/hooks/useEscapeKeyStroke.ts
Labels: stat: ready to merge, stat: QA tested

#31347 feat: Add support to cancel editing message action
  .changeset/message-composer-hint.md
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  packages/ui-composer/src/MessageComposer/MessageComposerButton.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerHint.tsx
  packages/ui-composer/src/MessageComposer/index.ts
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31462 refactor: Replace `Notifications` module in favor of `sdk` for Video Conf
  apps/meteor/client/lib/VideoConfManager.ts
Labels: stat: needs QA

#31460 refactor: Replace `Notifications` module in favor of `sdk` for Omnichannel/WebRTC
  apps/meteor/app/webrtc/client/WebRTCClass.js
  apps/meteor/app/webrtc/client/actionLink.tsx
  apps/meteor/app/webrtc/lib/constants.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/client/views/meet/CallPage.tsx
  ee/packages/ddp-client/src/types/streams.ts
Labels: stat: needs QA

#30977 chore(eslint-config): Include missing ESLint configuration for React
  .changeset/angry-llamas-retire.md
  packages/eslint-config/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31472 chore: Remove unnecessary changeset file
  .changeset/breezy-ladybugs-sip.md
Labels: stat: ready to merge, stat: QA skipped

#31454 fix: Department name being double escaped
  .changeset/green-tools-exercise.md
  packages/livechat/src/helpers/normalizeTransferHistoryMessage.ts
  packages/livechat/src/i18next.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31477 chore: fix embedded livechat tests
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-widget.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts
  packages/livechat/src/components/Button/index.tsx
  packages/livechat/src/components/Screen/index.js
Labels: stat: needs QA

#31479 chore: improve backend startup
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Settings.ts
Labels: stat: needs QA

#31424 chore: Replace `Notifications` module in favor of `SDK` inside CachedCollection
  apps/meteor/app/models/client/models/ChatPermissions.ts
  apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
  apps/meteor/client/lib/settings/PrivateSettingsCachedCollection.ts
  apps/meteor/client/lib/settings/PublicSettingsCachedCollection.ts
Labels: stat: ready to merge, stat: QA skipped

#31476 chore: Remove `MessageContentBody` additional styles
  apps/meteor/client/components/message/MessageContentBody.tsx
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31481 chore: Revert "chore: Add missing changeset file"
  .changeset/silent-shirts-knock.md
Labels: stat: needs QA

#31480 chore: RateLimiter to async
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/lib/server/lib/RateLimiter.js
  apps/meteor/app/lib/server/startup/rateLimiter.js
  apps/meteor/definition/externals/meteor/rate-limit.d.ts
Labels: stat: needs QA

#31451 Release 6.5.3
  .changeset/beige-deers-laugh.md
  .changeset/bump-patch-1705335886930.md
  .changeset/fresh-maps-rhyme.md
  apps/meteor/app/2fa/server/methods/validateTempToken.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/client/components/TwoFactorModal/TwoFactorModal.tsx
  apps/meteor/client/views/account/security/TwoFactorTOTP.tsx
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/startup/migrations/v304.ts
  package.json
  yarn.lock
Labels: stat: needs QA

#31486 test: fix flaky setGuestName test
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts
Labels: stat: needs QA

#21600 i18n: zh translation error
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31463 refactor: Remove `Notifications` module
  apps/meteor/app/notifications/client/index.ts
  apps/meteor/app/notifications/client/lib/Notifications.ts
  apps/meteor/app/webdav/client/startup/sync.ts
  apps/meteor/client/importPackages.ts
  packages/core-typings/src/IWebdavAccount.ts
Labels: stat: needs QA

#31452 chore: remove client references to the service configurations collection
  apps/meteor/app/custom-oauth/client/CustomOAuth.ts
  apps/meteor/client/lib/loginServices.ts
  apps/meteor/client/lib/wrapRequestCredentialFn.ts
  apps/meteor/client/meteorOverrides/login/facebook.ts
  apps/meteor/client/meteorOverrides/login/github.ts
  apps/meteor/client/meteorOverrides/login/google.ts
  apps/meteor/client/meteorOverrides/login/linkedin.ts
  apps/meteor/client/meteorOverrides/login/meteorDeveloperAccount.ts
  apps/meteor/client/meteorOverrides/login/saml.ts
  apps/meteor/client/meteorOverrides/login/twitter.ts
  apps/meteor/client/providers/AuthenticationProvider.tsx
  apps/meteor/client/startup/customOAuth.ts
  apps/meteor/client/startup/iframeCommands.ts
  apps/meteor/definition/externals/meteor/oauth.d.ts
  apps/meteor/packages/linkedin-oauth/linkedin-client.js
  packages/ui-contexts/src/AuthenticationContext.ts
  packages/ui-contexts/src/hooks/useLoginServices.ts
  packages/ui-contexts/src/index.ts
  packages/web-ui-registration/src/LoginServices.tsx
Labels: stat: needs QA

#31368 fix: add missing labels to UsersByTimeOfTheDaySection
  .changeset/tender-lizards-shop.md
  apps/meteor/ee/client/views/admin/engagementDashboard/users/UsersByTimeOfTheDaySection.tsx
Labels: stat: ready to merge, stat: QA tested, squad: Workspace Management

#31468 chore: QoL changes for Omnichannel
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/imports/server/rest/inquiries.ts
  apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
  apps/meteor/app/livechat/server/lib/Departments.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/startup.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/addDepartmentAncestors.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterForwardChatToDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterRemoveDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadForwardDepartmentRestrictions.ts
  apps/meteor/ee/server/models/raw/LivechatDepartment.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#30478 feat: Add `chat.getURLPreview` endpoint
  .changeset/lucky-bikes-enjoy.md
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/oembed/server/server.ts
  apps/meteor/tests/end-to-end/api/05-chat.js
  packages/core-typings/src/IMessage/IMessage.ts
  packages/rest-typings/src/v1/chat.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30645 chore: Handling plural translations
  .changeset/grumpy-trainers-hope.md
  apps/meteor/.scripts/translation-check.ts
  apps/meteor/app/utils/lib/i18n.ts
  apps/meteor/client/components/connectionStatus/ConnectionStatusBar.tsx
  apps/meteor/client/components/message/content/DiscussionMetrics.tsx
  apps/meteor/client/sidebar/footer/voip/index.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleTable.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDismissUserAction.tsx
  apps/meteor/client/views/admin/settings/inputs/ActionSettingInput.stories.tsx
  apps/meteor/client/views/admin/settings/inputs/MultiSelectSettingInput.stories.tsx
  apps/meteor/client/views/admin/settings/inputs/SelectSettingInput.stories.tsx
  apps/meteor/client/views/marketplace/components/EnabledAppsCount.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/et.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/id.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
  packages/ui-contexts/src/TranslationContext.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31491 chore: improve type definitions for login service configurations
  apps/meteor/app/api/server/v1/settings.ts
  apps/meteor/client/startup/customOAuth.ts
  apps/meteor/server/models/raw/LoginServiceConfiguration.ts
  apps/meteor/server/services/meteor/service.ts
  packages/core-services/src/types/IMeteor.ts
  packages/core-typings/src/ILoginServiceConfiguration.ts
  packages/model-typings/src/models/ILoginServiceConfigurationModel.ts
  packages/rest-typings/src/v1/settings.ts
Labels: stat: ready to merge, stat: QA skipped

#31499 chore: Normalize `ButtonGroup`
  apps/meteor/client/components/NotFoundState.tsx
  apps/meteor/client/components/message/content/attachments/default/ActionAttachtment.tsx
  apps/meteor/client/sidebar/header/HeaderUnstable.tsx
  apps/meteor/client/views/account/preferences/PreferencesMyDataSection.tsx
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx
  apps/meteor/client/views/admin/customSounds/AddCustomSound.tsx
  apps/meteor/client/views/admin/customSounds/EditSound.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
  apps/meteor/client/views/admin/emailInbox/EmailInboxForm.tsx
  apps/meteor/client/views/admin/moderation/MessageContextFooter.tsx
  apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx
  apps/meteor/client/views/admin/oauthApps/OAuthAddApp.tsx
  apps/meteor/client/views/admin/permissions/UsersInRole/UsersInRolePage.tsx
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/settings/inputs/CodeMirror/CodeMirrorBox.tsx
  apps/meteor/client/views/admin/subscription/components/UpgradeToGetMore.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoActions.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/TagList.tsx
  apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
  apps/meteor/client/views/meet/CallPage.tsx
  apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
  apps/meteor/client/views/omnichannel/agents/AgentInfoAction.tsx
  apps/meteor/client/views/omnichannel/customFields/EditCustomFields.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.tsx
  apps/meteor/client/views/outlookCalendar/OutlookEventsList/OutlookEventsList.tsx
  apps/meteor/client/views/room/composer/ComposerAnonymous.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoActions.tsx
  apps/meteor/client/views/root/MainLayout/RegisterUsername.tsx
  apps/meteor/ee/client/omnichannel/tags/TagEdit.tsx
  apps/meteor/ee/client/omnichannel/units/UnitEdit.tsx
  apps/meteor/ee/client/views/audit/components/AuditForm.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/fuselage-ui-kit/src/elements/LinearScaleElement.tsx
  packages/gazzodown/package.json
  packages/ui-client/package.json
  packages/ui-client/src/components/EmojiPicker/EmojiPickerCategoryHeader.tsx
  packages/ui-client/src/components/Header/HeaderToolbox/HeaderToolbox.tsx
  packages/ui-composer/package.json
  packages/ui-composer/src/MessageComposer/MessageComposerToolbar.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerToolbarActions.tsx
  packages/ui-video-conf/package.json
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupControllers.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooter.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooterButtons.tsx
  packages/uikit-playground/package.json
  packages/uikit-playground/src/Components/Preview/NavPanel/NavPanel.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31225 feat: Convert emoji shortname to unicode on notification emails.
  .changeset/green-timers-cross.md
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
Labels: stat: ready to merge, stat: QA tested

#31492 chore: convert CAS integration code to typescript
  apps/meteor/app/cas/server/cas_rocketchat.js
  apps/meteor/app/cas/server/cas_server.js
  apps/meteor/app/cas/server/index.ts
  apps/meteor/server/configuration/cas.ts
  apps/meteor/server/importPackages.ts
  apps/meteor/server/lib/cas/createNewUser.ts
  apps/meteor/server/lib/cas/findExistingCASUser.ts
  apps/meteor/server/lib/cas/logger.ts
  apps/meteor/server/lib/cas/loginHandler.ts
  apps/meteor/server/lib/cas/middleware.ts
  apps/meteor/server/lib/cas/updateCasService.ts
  apps/meteor/server/main.ts
  packages/cas-validate/src/validate.ts
  packages/cas-validate/tsconfig.json
  packages/tools/src/getObjectKeys.ts
  packages/tools/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#31507 fix: Can't remove channel's password to join
  .changeset/forty-dragons-juggle.md
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
Labels: stat: ready to merge, stat: QA skipped

#31513 chore: split UserProvider into two: User and Authentication
  apps/meteor/client/providers/AuthenticationProvider/AuthenticationProvider.tsx
  apps/meteor/client/providers/AuthenticationProvider/hooks/useLDAPAndCrowdCollisionWarning.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/sidebar/Sidebar.stories.tsx
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/mock-providers/src/MockedUserContext.tsx
  packages/ui-contexts/src/AuthenticationContext.tsx
  packages/ui-contexts/src/UserContext.ts
  packages/ui-contexts/src/hooks/useLoginServices.ts
  packages/ui-contexts/src/hooks/useLoginWithPassword.ts
  packages/ui-contexts/src/hooks/useLoginWithService.ts
  packages/ui-contexts/src/hooks/useLoginWithToken.ts
  packages/ui-contexts/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#31289 feat: Add `push.test` endpoint
  .changeset/kind-melons-try.md
  apps/meteor/app/api/server/v1/push.ts
  apps/meteor/app/push/server/push.ts
  apps/meteor/server/lib/pushConfig.ts
  apps/meteor/server/models/raw/AppsTokens.ts
  apps/meteor/tests/end-to-end/api/22-push.ts
  packages/model-typings/src/models/IAppsTokensModel.ts
  packages/rest-typings/src/v1/push.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31328 fix: Prevent `Fallback forward departments` feature to go on loop when configured as circular chain
  .changeset/tiny-onions-remember.md
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  packages/core-typings/src/omnichannel/routing.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31500 refactor(client): Handling of custom statuses
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/app/user-status/client/index.ts
  apps/meteor/app/user-status/client/lib/customUserStatus.js
  apps/meteor/app/user-status/client/lib/userStatus.ts
  apps/meteor/app/user-status/server/methods/listCustomUserStatus.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/lib/presence.ts
  apps/meteor/client/lib/userStatuses.ts
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/providers/UserProvider/hooks/useUpdateCustomUserStatus.ts
  apps/meteor/client/sidebar/header/hooks/useStatusItems.tsx
  apps/meteor/client/sidebar/header/hooks/useUserMenu.tsx
  apps/meteor/definition/externals/meteor/meteor.d.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/events/Events.ts
  packages/core-typings/src/ICustomUserStatus.ts
Labels: stat: ready to merge, stat: QA skipped

#31336 fix: Cron job for clearing OEmbed cache isn't working
  .changeset/selfish-rice-wave.md
  apps/meteor/client/views/admin/settings/inputs/ActionSettingInput.tsx
  apps/meteor/server/cron/oembed.ts
  apps/meteor/server/methods/OEmbedCacheCleanup.ts
  apps/meteor/server/models/raw/OEmbedCache.ts
  packages/model-typings/src/models/IOEmbedCacheModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#30338 refactor: Pay the debt of some TODO comments
  apps/meteor/app/livechat/server/methods/sendFileLivechatMessage.ts
  apps/meteor/client/components/GenericTable/GenericTable.tsx
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/CloseChatModalData.tsx
  apps/meteor/client/components/TextCopy.tsx
  apps/meteor/client/components/connectionStatus/ConnectionStatusBar.styles.css
  apps/meteor/client/components/connectionStatus/ConnectionStatusBar.tsx
  apps/meteor/client/components/connectionStatus/useReconnectCountdown.ts
  apps/meteor/client/components/message/content/attachments/AttachmentsItem.tsx
  apps/meteor/client/components/message/content/attachments/FileAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/AudioAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/GenericFileAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/ImageAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/VideoAttachment.tsx
  apps/meteor/client/hooks/useEndpointAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeLeaderAction.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeModeratorAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeOwnerAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useRemoveUserAction.tsx
  packages/core-typings/src/IMessage/MessageAttachment/Files/FileAttachmentProps.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentBase.ts
Labels: stat: needs QA

#31427 feat(agenda): Changes in Agenda API
  .changeset/wicked-pumpkins-walk.md
  packages/agenda/src/Agenda.ts
Labels: stat: needs QA

#31170 chore: handle rocket.cat creation and deletion
  apps/meteor/app/lib/server/functions/deleteUser.ts
  apps/meteor/server/startup/initialData.js
Labels: stat: needs QA

#31487 fix: ensure sessionId on Sessions documents
  .changeset/clever-parrots-count.md
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/statistics/server/lib/SAUMonitor.ts
  apps/meteor/definition/externals/meteor/ddp-common.d.ts
  apps/meteor/server/models/raw/Sessions.ts
Labels: stat: needs QA

#30910 fix: change the push sound sent when the push is from video conference
  .changeset/yellow-brooms-brake.md
  apps/meteor/server/services/video-conference/service.ts
Labels: stat: QA skipped

#31512 test: fix messaging flaky test
  apps/meteor/tests/e2e/messaging.spec.ts
Labels: stat: needs QA

#31514 fix: Marketplace apps installed as private showing as installed
  .changeset/honest-gorillas-reply.md
  apps/meteor/client/providers/AppsProvider.tsx
Labels: stat: ready to merge, stat: QA skipped

#30554 feat: Introduce User Report Section on Moderation Console
  .changeset/rare-eels-fetch.md
  apps/meteor/app/api/server/v1/moderation.ts
  apps/meteor/client/views/admin/moderation/MessageContextFooter.tsx
  apps/meteor/client/views/admin/moderation/MessageReportInfo.tsx
  apps/meteor/client/views/admin/moderation/ModConsoleReportDetails.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsolePage.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleRoute.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleTable.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsoleTableRow.tsx
  apps/meteor/client/views/admin/moderation/UserMessages.tsx
  apps/meteor/client/views/admin/moderation/UserReports/ModConsoleUserActions.tsx
  apps/meteor/client/views/admin/moderation/UserReports/ModConsoleUserTableRow.tsx
  apps/meteor/client/views/admin/moderation/UserReports/ModConsoleUsersTable.tsx
  apps/meteor/client/views/admin/moderation/UserReports/UserContextFooter.tsx
  apps/meteor/client/views/admin/moderation/UserReports/UserReportInfo.tsx
  apps/meteor/client/views/admin/moderation/helpers/DateRangePicker.tsx
  apps/meteor/client/views/admin/moderation/helpers/ModerationFilter.tsx
  apps/meteor/client/views/admin/moderation/helpers/ReportReason.tsx
  apps/meteor/client/views/admin/moderation/helpers/UserColumn.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDeactivateUserAction.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDeleteMessage.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDeleteMessagesAction.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDismissMessageAction.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDismissUserAction.tsx
  apps/meteor/client/views/admin/moderation/hooks/useResetAvatarAction.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/models/raw/ModerationReports.ts
  apps/meteor/tests/data/moderation.helper.ts
  apps/meteor/tests/end-to-end/api/27-moderation.ts
  packages/model-typings/src/models/IModerationReportsModel.ts
  packages/rest-typings/src/v1/moderation/GetUserReportsParams.ts
  packages/rest-typings/src/v1/moderation/index.ts
  packages/rest-typings/src/v1/moderation/moderation.ts
Labels: stat: ready to merge, stat: QA tested

#31304 chore: Add readme to ddp-client package
  .changeset/cyan-balloons-unite.md
  ee/packages/ddp-client/README.md
  ee/packages/ddp-client/src/README.md
Labels: stat: needs QA

#31433 fix: Engagement Dashboard - values discrepancy with downloaded report
  .changeset/friendly-cycles-grab.md
  apps/meteor/ee/client/components/dashboards/periods.ts
  apps/meteor/ee/client/views/admin/engagementDashboard/users/ActiveUsersSection.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/users/useActiveUsers.ts
  apps/meteor/server/models/raw/Sessions.ts
Labels: stat: ready to merge, stat: QA skipped

#31385 chore: refactor the refresh oauth services function
  apps/meteor/app/lib/server/methods/addOAuthService.ts
  apps/meteor/app/lib/server/methods/refreshOAuthService.ts
  apps/meteor/app/lib/server/startup/index.ts
  apps/meteor/app/lib/server/startup/oAuthServicesUpdate.js
  apps/meteor/app/meteor-accounts-saml/server/lib/settings.ts
  apps/meteor/ee/server/configuration/oauth.ts
  apps/meteor/server/configuration/accounts_meld.js
  apps/meteor/server/configuration/cas.ts
  apps/meteor/server/configuration/index.ts
  apps/meteor/server/configuration/ldap.ts
  apps/meteor/server/configuration/oauth.ts
  apps/meteor/server/lib/oauth/addOAuthService.ts
  apps/meteor/server/lib/oauth/initCustomOAuthServices.ts
  apps/meteor/server/lib/oauth/logger.ts
  apps/meteor/server/lib/oauth/removeOAuthService.ts
  apps/meteor/server/lib/oauth/updateOAuthServices.ts
  apps/meteor/server/lib/refreshLoginServices.ts
  apps/meteor/server/main.ts
  apps/meteor/server/models/raw/LoginServiceConfiguration.ts
  packages/model-typings/src/models/ILoginServiceConfigurationModel.ts
  packages/ui-contexts/src/AuthenticationContext.ts
  packages/ui-contexts/src/index.ts
Labels: stat: needs QA

#31520 regression: LoginForm button misalignment
  packages/web-ui-registration/src/LoginForm.tsx
Labels: stat: needs QA

#31322 chore: e2e tests for basic login and saml
  apps/meteor/app/meteor-accounts-saml/server/startup.ts
  apps/meteor/package.json
  apps/meteor/tests/e2e/config/constants.ts
  apps/meteor/tests/e2e/containers/saml/Dockerfile
  apps/meteor/tests/e2e/containers/saml/config/apache/cert_crt
  apps/meteor/tests/e2e/containers/saml/config/apache/ports.conf
  apps/meteor/tests/e2e/containers/saml/config/apache/private_key
  apps/meteor/tests/e2e/containers/saml/config/apache/simplesamlphp.conf
  apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/authsources.php
  apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/config.php
  apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/saml20-sp-remote.php
  apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/server_crt
  apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/server_pem
  apps/meteor/tests/e2e/containers/saml/docker-compose.yml
  apps/meteor/tests/e2e/fixtures/collections/users.ts
  apps/meteor/tests/e2e/fixtures/inject-initial-data.ts
  apps/meteor/tests/e2e/fixtures/userStates.ts
  apps/meteor/tests/e2e/login.spec.ts
  apps/meteor/tests/e2e/page-objects/auth.ts
  apps/meteor/tests/e2e/saml.spec.ts
  apps/meteor/tests/e2e/utils/getUserInfo.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31521 regression: Convert emoji shortname to unicode on notification emails
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
Labels: stat: needs QA

#31523 refactor: convert sendNotification to ts
  apps/meteor/app/lib/server/functions/notifications/desktop.ts
  apps/meteor/app/lib/server/functions/notifications/index.ts
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
Labels: stat: needs QA

#29797 chore: move some file functions to upload service
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/File.ts
  apps/meteor/server/services/upload/service.ts
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  packages/core-services/src/types/IUploadService.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageAttachment.ts
Labels: stat: ready to merge, stat: QA skipped

#31522 fix: records without sessionId in the device management table
  apps/meteor/server/models/raw/Sessions.ts
Labels: stat: ready to merge, stat: QA skipped

#31349 feat: Implemented InlineCode handling in Bold, Italic and Strike
  .changeset/calm-carrots-judge.md
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/packages/pdf-worker/src/templates/ChatTranscript/markup/elements/BoldSpan.tsx
  ee/packages/pdf-worker/src/templates/ChatTranscript/markup/elements/ItalicSpan.tsx
  ee/packages/pdf-worker/src/templates/ChatTranscript/markup/elements/StrikeSpan.tsx
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/gazzodown/package.json
  packages/gazzodown/src/elements/BoldSpan.tsx
  packages/gazzodown/src/elements/ImageElement.tsx
  packages/gazzodown/src/elements/ItalicSpan.tsx
  packages/gazzodown/src/elements/StrikeSpan.tsx
  packages/livechat/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: QA skipped

#31526 chore: Normalize `MessageToolbar`
  apps/meteor/client/components/message/MessageToolbarHolder.tsx
  apps/meteor/client/components/message/toolbar/DesktopToolbarDropdown.tsx
  apps/meteor/client/components/message/toolbar/MessageActionMenu.tsx
  apps/meteor/client/components/message/toolbar/MessageToolbar.tsx
  apps/meteor/client/components/message/toolbar/MobileToolbarDropdown.tsx
  apps/meteor/client/components/message/toolbar/ToolbarDropdown.tsx
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/fuselage-ui-kit/src/stories/Message.stories.tsx
  packages/gazzodown/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  packages/uikit-playground/src/Components/Preview/Display/Surface/MessageSurface.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31498 chore: remove link css overrides
  apps/meteor/app/theme/client/imports/general/base.css
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/reset.css
  apps/meteor/client/views/room/Header/RoomHeader.tsx
Labels: stat: ready to merge, stat: QA skipped

#20019 fix: Missing error message when user limit exceeds in direct message
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/client/sidebar/header/CreateDirectMessage.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: communityPR, stat: needs QA

#31230 feat: Ability to add custom scripts to Livechat bundle
  apps/meteor/app/livechat/server/livechat.ts
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
Labels: stat: ready to merge, stat: QA tested, squad: Professional Services

#30069 fix(meteor): Respect `UI_Use_Real_Name` setting for reactions
  .changeset/seven-pugs-argue.md
  apps/meteor/client/components/message/content/Reactions.tsx
  apps/meteor/client/components/message/content/reactions/Reaction.tsx
  apps/meteor/client/components/message/list/MessageListContext.tsx
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31527 chore: use single message event
  apps/meteor/app/autotranslate/server/autotranslate.ts
  apps/meteor/app/discussion/server/hooks/propagateDiscussionMetadata.ts
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/threads/server/hooks/aftersavemessage.ts
  apps/meteor/ee/server/lib/message-read-receipt/ReadReceipt.js
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/watchers/lib/messages.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/server/services/meteor/service.ts
  apps/meteor/server/services/video-conference/service.ts
  packages/core-services/src/events/Events.ts
  packages/core-services/src/events/listeners.ts
  packages/core-services/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#31535 chore: bump meteor 2.4
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/release
  apps/meteor/.meteor/versions
  apps/meteor/app/2fa/server/definitions/MeteorUser.d.ts
  apps/meteor/app/2fa/server/methods/disable.ts
  apps/meteor/definition/externals/meteor/meteor.d.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/tsconfig.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
  ee/packages/omnichannel-services/package.json
  ee/packages/presence/package.json
  packages/agenda/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/core-typings/src/IUser.ts
  packages/cron/package.json
  packages/instance-status/package.json
  packages/model-typings/package.json
  packages/rest-typings/package.json
  packages/ui-contexts/package.json
  yarn.lock
Labels: stat: needs QA

#31540 fix: use EJSON serializer for data transfer between multi instances
  .changeset/spotty-tips-sell.md
  apps/meteor/ee/server/local-services/instance/service.ts
Labels: stat: ready to merge, automerge, stat: QA skipped

#31537 fix: webclient still showing DM messages that had already been deleted from the server
  .changeset/mighty-shirts-sell.md
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/providers/UserProvider/hooks/useClearRemovedRoomsHistory.ts
Labels: stat: ready to merge, stat: QA tested

#31543 chore: change network broker defaults
  apps/meteor/ee/server/startup/broker.ts
Labels: stat: QA skipped

#31544 regression(i18n): Pass only `number` values to `unread_messages_counter` translation string
  apps/meteor/client/views/root/hooks/useUnreadMessages.ts
Labels: stat: ready to merge, stat: QA skipped

#31503 regression: error when archiving rooms through the admin panel
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA skipped

#31551 ci: add do not merge label to kodiak
  .kodiak.toml
Labels: stat: ready to merge, stat: QA skipped

#31362 fix: user check on login with OAuth
  apps/meteor/server/configuration/accounts_meld.js
Labels: stat: needs QA

#31528 fix: Coerce values on appearance endpoint from setting data types
  apps/meteor/app/livechat/imports/server/rest/appearance.ts
  apps/meteor/server/models/raw/Settings.ts
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
  packages/model-typings/src/models/ISettingsModel.ts
Labels: stat: ready to merge, stat: QA skipped, squad: omnichannel

#31417 feat: Update autotranslate on language preference change
  .changeset/sixty-bananas-sit.md
  apps/meteor/server/methods/saveUserPreferences.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/tests/end-to-end/api/00-autotranslate.js
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31467 fix: breaks the avatar if you hit the button adding an invalid link
  .changeset/tough-candles-argue.md
  apps/meteor/client/components/avatar/BaseAvatar.tsx
  apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/account-profile.spec.ts
  apps/meteor/tests/e2e/page-objects/account-profile.ts
Labels: stat: needs QA

#31555 chore: remove prepare script from ui-kit
  packages/ui-kit/package.json
Labels: stat: needs QA

#31557 chore: Restore ui-kit prepare script
  packages/ui-kit/package.json
Labels: stat: needs QA

#31567 chore: change SAML single sign out to access workspace settings directly
  apps/meteor/app/meteor-accounts-saml/server/lib/settings.ts
  apps/meteor/client/meteorOverrides/login/saml.ts
  apps/meteor/tests/e2e/saml.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#31573 ci: create better preview release notes for candidates
  packages/release-action/src/bumpNextVersion.ts
  packages/release-action/src/publishRelease.ts
  packages/release-action/src/updatePRDescription.ts
  packages/release-action/src/utils.ts
Labels: stat: needs QA

#31571 fix: dryrun option sending email to all queried users
  .changeset/grumpy-eagles-roll.md
  apps/meteor/app/mail-messages/server/functions/sendMail.ts
  apps/meteor/tests/end-to-end/api/livechat/12-mailer.ts
Labels: stat: ready to merge, stat: QA tested

#31553 refactor(client): Decouple WebDAV accounts integration from client initialization
  apps/meteor/app/models/client/index.ts
  apps/meteor/app/models/client/models/WebdavAccounts.ts
  apps/meteor/app/webdav/client/actionButton.ts
  apps/meteor/app/webdav/client/index.js
  apps/meteor/app/webdav/client/startup/sync.ts
  apps/meteor/client/components/message/toolbar/MessageToolbar.tsx
  apps/meteor/client/components/message/toolbar/useWebDAVMessageAction.tsx
  apps/meteor/client/hooks/webdav/useWebDAVAccountIntegrationsQuery.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/account/integrations/AccountIntegrationsPage.tsx
  apps/meteor/client/views/account/integrations/AccountIntegrationsRoute.tsx
  apps/meteor/client/views/account/integrations/hooks/useRemoveWebDAVAccountIntegrationMutation.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useWebdavActions.tsx
  apps/meteor/client/views/room/webdav/SaveToWebdavModal.tsx
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/events/Events.ts
Labels: stat: ready to merge, stat: QA skipped

#31591 regression: Engagement dashboard crashing
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx
Labels: stat: ready to merge, stat: QA tested

#31473 feat: a11y doc links
  .changeset/kind-dragons-flash.md
  apps/meteor/client/views/account/accessibility/AccessibilityPage.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/businessHours/BusinessHoursDisabledPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/DepartmentsTable.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTable.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersTable.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx
  apps/meteor/ee/client/omnichannel/monitors/MonitorsTable.tsx
  apps/meteor/ee/client/omnichannel/slaPolicies/SlaTable.tsx
  apps/meteor/ee/client/omnichannel/tags/TagsTable.tsx
  apps/meteor/ee/client/omnichannel/units/UnitsTable.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: needs QA

#31583 fix: Login email verification flow
  .changeset/flat-windows-juggle.md
  apps/meteor/tests/e2e/page-objects/auth.ts
  packages/web-ui-registration/src/EmailConfirmationForm.tsx
  packages/web-ui-registration/src/LoginForm.tsx
Labels: stat: ready to merge, stat: QA tested

#31532 refactor: Move reaction tooltip to its own component
  apps/meteor/client/components/message/content/reactions/Reaction.tsx
  apps/meteor/client/components/message/content/reactions/ReactionTooltip.tsx
Labels: stat: ready to merge, stat: QA skipped

#31589 fix: Composer losing edit state when resizing the window.
  .changeset/curly-years-smile.md
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
Labels: stat: ready to merge, stat: QA skipped
