Repository RocketChat/Rocket.Chat, pull requests merged in 2024-09, with the labels that each got.

#33160 feat: email bridge
  .changeset/tame-mayflies-press.md
  apps/meteor/app/apps/server/bridges/bridges.js
  apps/meteor/app/apps/server/bridges/email.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33149 test: create tests for omnichannel queue management
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-queue-management.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
Labels: stat: ready to merge, stat: QA assured

#33200 regression: fix subscription counter for DMs
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts
Labels: stat: ready to merge, stat: QA assured

#33159 chore: improve omni queue metrics query
  .changeset/cool-actors-sin.md
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/07-queue.ts
Labels: stat: ready to merge, stat: QA assured

#32729 feat: update contact endpoint
  .changeset/heavy-snails-help.md
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/server/models/raw/LivechatContacts.ts
  apps/meteor/tests/end-to-end/api/livechat/contacts.ts
  apps/meteor/tests/unit/app/livechat/server/lib/Contacts.spec.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/model-typings/src/models/ILivechatContactsModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#32999 fix(fuselage-ui-kit): `MultiStaticSelectElement` not working as expected
  .changeset/mighty-drinks-hide.md
  apps/meteor/tests/e2e/apps/apps-modal.spec.ts
  packages/fuselage-ui-kit/src/hooks/useUiKitState.spec.ts
  packages/fuselage-ui-kit/src/hooks/useUiKitState.ts
Labels: stat: ready to merge, stat: QA assured

#33213 chore: Add proper deprecation remarks on Minimongo collections
  apps/meteor/app/models/client/index.ts
  apps/meteor/app/models/client/models/CachedChatRoom.ts
  apps/meteor/app/models/client/models/CachedChatSubscription.ts
  apps/meteor/app/models/client/models/ChatMessage.ts
  apps/meteor/app/models/client/models/ChatRoom.ts
  apps/meteor/app/models/client/models/ChatSubscription.ts
  apps/meteor/app/models/client/models/Roles.ts
  apps/meteor/app/models/client/models/RoomRoles.ts
  apps/meteor/app/models/client/models/UserAndRoom.ts
  apps/meteor/app/models/client/models/UserRoles.ts
  apps/meteor/app/models/client/models/Users.ts
Labels: stat: ready to merge, stat: QA assured

#33216 fix: prevent uiInteraction to invalidate multiple times
  .changeset/rich-toes-bow.md
  apps/meteor/client/hooks/useAppUiKitInteraction.ts
Labels: stat: ready to merge, stat: QA assured

#33217 refactor: `AnchorPortal` component
  apps/meteor/client/lib/utils/createAnchor.ts
  apps/meteor/client/lib/utils/deleteAnchor.ts
  apps/meteor/client/portals/TooltipPortal.tsx
  apps/meteor/client/portals/VideoConfPopupPortal.tsx
  packages/ui-client/src/components/AnchorPortal.spec.tsx
  packages/ui-client/src/components/AnchorPortal.tsx
  packages/ui-client/src/components/index.ts
  packages/ui-client/src/helpers/anchors.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33197 fix: Retention policy warning keep displaying if disabled in room
  .changeset/khaki-cameras-glow.md
  apps/meteor/client/views/room/hooks/useRetentionPolicy.spec.ts
  apps/meteor/client/views/room/hooks/useRetentionPolicy.ts
Labels: stat: ready to merge, stat: QA assured

#32821 feat: `Sidebar` new components
  .changeset/many-balloons-scream.md
  apps/meteor/client/sidebarv2/Item/Condensed.tsx
  apps/meteor/client/sidebarv2/Item/Extended.stories.tsx
  apps/meteor/client/sidebarv2/Item/Extended.tsx
  apps/meteor/client/sidebarv2/Item/Medium.tsx
  apps/meteor/client/sidebarv2/RoomList/RoomList.tsx
  apps/meteor/client/sidebarv2/RoomList/RoomListRow.tsx
  apps/meteor/client/sidebarv2/RoomList/RoomListRowWrapper.tsx
  apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx
  apps/meteor/client/sidebarv2/RoomList/useSidebarListNavigation.ts
  apps/meteor/client/sidebarv2/Sidebar.tsx
  apps/meteor/client/sidebarv2/header/SearchList.tsx
  apps/meteor/client/sidebarv2/header/SearchSection.tsx
  apps/meteor/client/sidebarv2/header/actions/CreateRoom.tsx
  apps/meteor/client/sidebarv2/header/actions/Search.tsx
  apps/meteor/client/sidebarv2/header/actions/Sort.tsx
  apps/meteor/client/sidebarv2/hooks/useAvatarTemplate.tsx
  apps/meteor/client/sidebarv2/search/Row.tsx
  apps/meteor/client/sidebarv2/search/SearchList.tsx
  apps/meteor/client/sidebarv2/search/UserItem.tsx
  apps/meteor/client/sidebarv2/sections/StatusDisabledSection.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33155 fix: NPS passing `startAt` as the expiration date when creating a banner
  .changeset/nasty-tools-enjoy.md
  apps/meteor/server/services/nps/service.ts
  apps/meteor/tests/unit/server/services/nps/spec.tests.ts
Labels: stat: ready to merge, stat: QA assured

#32865 feat: unknown contacts
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  packages/core-typings/src/ILivechatContact.ts
  packages/core-typings/src/ILivechatVisitor.ts
Labels: stat: ready to merge, stat: QA assured

#33139 feat: Allow admins to control if visitors can close omnichannel conversations
  .changeset/healthy-rivers-nail.md
  apps/meteor/app/livechat/imports/server/rest/appearance.ts
  apps/meteor/app/livechat/server/api/lib/appearance.ts
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx
  apps/meteor/client/views/omnichannel/appearance/AppearancePage.tsx
  apps/meteor/server/settings/omnichannel.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  packages/i18n/src/locales/en.i18n.json
  packages/livechat/src/routes/Chat/connector.tsx
  packages/livechat/src/routes/Chat/container.js
  packages/livechat/src/store/index.tsx
Labels: stat: ready to merge, stat: QA assured

#33211 fix: Allow to use the token from `room.v` when requesting transcript instead of finding visitor
  .changeset/four-cherries-kneel.md
  apps/meteor/app/livechat/server/lib/sendTranscript.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
  apps/meteor/tests/unit/app/livechat/server/lib/sendTranscript.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32945 feat: Option to disable 2FA for OAuth users
  .changeset/tiny-geckos-kiss.md
  apps/meteor/app/2fa/server/code/EmailCheck.spec.ts
  apps/meteor/app/2fa/server/code/EmailCheck.ts
  apps/meteor/app/2fa/server/code/index.ts
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/utils/server/functions/getBaseUserFields.ts
  apps/meteor/app/utils/server/functions/getDefaultUserFields.ts
  apps/meteor/client/views/account/security/AccountSecurityPage.tsx
  apps/meteor/client/views/account/security/TwoFactorEmail.tsx
  apps/meteor/server/settings/accounts.ts
  packages/core-typings/src/IUser.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33250 chore: fix ui-playground build
  packages/password-policies/tsconfig.json
  packages/uikit-playground/vite.config.ts
Labels: stat: QA assured

#33227 fix: message parser being slow to process very long messages with too many symbols
  .changeset/short-drinks-itch.md
  packages/message-parser/src/grammar.pegjs
  packages/message-parser/src/utils.ts
  packages/message-parser/tests/abuse.test.ts
  packages/message-parser/tests/emphasis.test.ts
  packages/message-parser/tests/link.test.ts
Labels: stat: ready to merge, stat: QA tested, stat: QA assured

#33224 chore: E2EE setting warning update
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33248 chore: publish preview github pages
  .github/workflows/ci-preview.yml
  .gitignore
  _templates/package/new/package.json.ejs.t
  apps/uikit-playground/package.json
  turbo.json
Labels: stat: ready to merge, stat: QA assured

#33181 fix: Infinite loading when uploading a private app
  .changeset/wet-hats-walk.md
  apps/meteor/client/views/marketplace/hooks/useInstallApp.tsx
Labels: stat: ready to merge, stat: QA assured

#33261 chore: add index to preview page
  .github/workflows/ci-deploy-gh-pages-preview.yml
  .github/workflows/ci-deploy-gh-pages.yml
Labels: stat: ready to merge, stat: QA assured

#33237 fix: Retention Policy cached settings not updated during upgrade procedure
  .changeset/pink-swans-teach.md
  apps/meteor/server/startup/migrations/xrun.ts
Labels: stat: ready to merge, stat: QA assured

#33246 fix: imported fixes
  .changeset/many-rules-shout.md
  apps/meteor/app/authorization/server/functions/canDeleteMessage.ts
  apps/meteor/app/otr/server/methods/updateOTRAck.ts
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppDetails/AppDetails.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppReleases/AppReleasesItem.tsx
  apps/meteor/client/views/marketplace/lib/purifyOptions.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/tests/end-to-end/api/methods.ts
  packages/gazzodown/package.json
  packages/gazzodown/src/emoji/EmojiRenderer.tsx
  packages/gazzodown/src/katex/KatexBlock.tsx
  packages/gazzodown/src/katex/KatexElement.tsx
  packages/model-typings/src/models/IRoomsModel.ts
Labels: stat: ready to merge, stat: QA assured

#33249 chore: moved UserAutoComplete to ui-client package
  apps/meteor/client/omnichannel/monitors/MonitorsTable.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AddAgent.tsx
  apps/meteor/client/views/omnichannel/managers/AddManager.tsx
  packages/ui-client/src/components/UserAutoComplete/UserAutoComplete.stories.tsx
  packages/ui-client/src/components/UserAutoComplete/UserAutoComplete.tsx
  packages/ui-client/src/components/UserAutoComplete/index.ts
  packages/ui-client/src/components/index.ts
Labels: stat: ready to merge, stat: QA assured

#33286 ci: Include hidden files when uploading artifacts
  .github/actions/meteor-build/action.yml
  .github/workflows/ci-test-e2e.yml
Labels: stat: ready to merge, stat: QA assured

#33041 feat: get contact by id endpoint
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/tests/end-to-end/api/livechat/contacts.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#33298 fix: Federation callback not awaiting model call
  .changeset/great-humans-live.md
  apps/meteor/app/federation/server/hooks/afterUnsetReaction.js
Labels: stat: ready to merge, stat: QA assured

#33295 fix: correct parameter order in afterSaveMessage to restore outgoing webhooks and related features
  .changeset/rotten-rabbits-brush.md
  apps/meteor/app/autotranslate/server/autotranslate.ts
  apps/meteor/app/integrations/server/triggers.ts
  apps/meteor/app/irc/server/irc-bridge/index.js
  apps/meteor/ee/server/lib/engagementDashboard/startup.ts
Labels: stat: ready to merge, stat: QA assured

#33177 feat: New endpoint for listing rooms & discussions from teams
  .changeset/soft-mirrors-remember.md
  apps/meteor/app/api/server/v1/teams.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/services/team/service.ts
  apps/meteor/tests/data/teams.helper.ts
  apps/meteor/tests/end-to-end/api/teams.ts
  packages/core-services/src/types/ITeamService.ts
  packages/model-typings/src/models/IRoomsModel.ts
  packages/rest-typings/src/v1/teams/TeamsListChildren.ts
  packages/rest-typings/src/v1/teams/index.ts
Labels: stat: ready to merge, stat: QA assured

#33305 chore: Update typings on callbacks to accept less than a full room object
  apps/meteor/app/lib/server/functions/isTheLastMessage.ts
  apps/meteor/server/services/messages/hooks/BeforeFederationActions.ts
  apps/meteor/server/services/messages/service.ts
  packages/core-services/src/types/IMessageService.ts
Labels: stat: ready to merge, stat: QA assured

#33193 fix: resolve avatar download issue on setUsername by refining service selection logic
  .changeset/small-crabs-travel.md
  apps/meteor/app/lib/server/functions/setUsername.ts
  apps/meteor/tests/unit/app/lib/server/functions/setUsername.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32682 feat: Allow managing association to business units on departments' creation and update
  .changeset/dirty-stingrays-beg.md
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/methods/saveDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/manageDepartmentUnit.ts
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/hooks/manageDepartmentUnit.spec.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/LivechatDepartment.ts
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/livechat/units.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  packages/core-typings/src/ILivechatDepartment.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
  packages/model-typings/src/models/ILivechatUnitModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#33296 fix: Local avatars prioritized over external avatar provider and remove remnant references on client of `Accounts_AvatarExternalProviderUrl`
  .changeset/strong-grapes-brake.md
  apps/meteor/app/utils/client/getUserAvatarURL.ts
  apps/meteor/app/utils/server/getUserAvatarURL.ts
  apps/meteor/client/providers/AvatarUrlProvider.tsx
  apps/meteor/server/routes/avatar/user.js
Labels: stat: ready to merge, stat: QA assured

#32939 fix: Mark as unread not working
  .changeset/hot-balloons-travel.md
  apps/meteor/app/message-mark-as-unread/client/actionButton.ts
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx
  apps/meteor/client/sidebarv2/RoomMenu.tsx
  apps/meteor/tests/e2e/mark-unread.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
Labels: stat: ready to merge, stat: QA assured

#33309 refactor: Remove old `setreaction` callbacks and use new after/before callbacks
  apps/meteor/app/reactions/client/methods/setReaction.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/slackbridge/server/RocketAdapter.js
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA assured

#33209 fix: `LivechatSessionTaken` webhook event called without `agent` param
  .changeset/spicy-rocks-burn.md
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
Labels: stat: ready to merge, stat: QA assured

#33317 fix: error on sendmessage stub
  .changeset/cyan-ladybugs-thank.md
  apps/meteor/app/lib/client/methods/sendMessage.ts
Labels: stat: ready to merge, stat: QA assured

#33225 feat: `RoomSidepanel`
  .changeset/witty-lemons-type.md
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/client/components/FeaturePreviewSidePanelNavigation.tsx
  apps/meteor/client/hooks/useRoomInfoEndpoint.ts
  apps/meteor/client/hooks/useSidePanelNavigation.ts
  apps/meteor/client/lib/RoomManager.ts
  apps/meteor/client/sidebarv2/header/CreateTeamModal.tsx
  apps/meteor/client/sidebarv2/header/SearchSection.tsx
  apps/meteor/client/views/room/RoomOpener.tsx
  apps/meteor/client/views/room/Sidepanel/RoomSidepanel.tsx
  apps/meteor/client/views/room/Sidepanel/RoomSidepanelListWrapper.tsx
  apps/meteor/client/views/room/Sidepanel/RoomSidepanelLoading.tsx
  apps/meteor/client/views/room/Sidepanel/SidepanelItem/RoomSidepanelItem.tsx
  apps/meteor/client/views/room/Sidepanel/SidepanelItem/index.ts
  apps/meteor/client/views/room/Sidepanel/hooks/useItemData.tsx
  apps/meteor/client/views/room/Sidepanel/hooks/useTeamslistChildren.ts
  apps/meteor/client/views/room/Sidepanel/index.ts
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/useEditRoomInitialValues.ts
  apps/meteor/client/views/room/layout/RoomLayout.tsx
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/lib/publishFields.ts
  apps/meteor/server/services/team/service.ts
  packages/core-typings/src/IRoom.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/v1/rooms.ts
  packages/ui-client/src/components/FeaturePreview/FeaturePreview.tsx
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
Labels: stat: ready to merge, stat: QA assured

#32994 refactor: Reactions set/unset
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/server/models/raw/EmojiCustom.ts
  apps/meteor/tests/unit/app/reactions/server/setReaction.spec.ts
  packages/model-typings/src/models/IEmojiCustomModel.ts
Labels: stat: ready to merge, stat: QA assured

#32510 feat: E2EE messages mentions
  .changeset/late-planes-sniff.md
  apps/meteor/app/lib/server/methods/updateMessage.ts
  apps/meteor/app/mentions/server/Mentions.ts
  apps/meteor/client/startup/e2e.ts
  apps/meteor/server/settings/e2e.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: QA assured

#33157 fix: markdown inconsistency with bold and italics
  .changeset/sweet-nails-grin.md
  apps/meteor/client/components/MarkdownText.spec.tsx
  apps/meteor/client/components/MarkdownText.tsx
Labels: stat: ready to merge, stat: QA assured

#33179 fix: conference calls are shown as "not answered" after they end
  .changeset/five-coats-rhyme.md
  apps/uikit-playground/package.json
  apps/uikit-playground/vite.config.ts
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
Labels: stat: ready to merge, stat: QA assured

#33226 chore: update E2EE setting text
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33004 feat: VoIP freeswitch UI admin
  apps/meteor/app/models/client/models/Users.ts
  apps/meteor/app/utils/client/lib/SDKClient.ts
  apps/meteor/client/views/admin/users/AdminUserInfoActions.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoWithData.tsx
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/client/views/admin/users/UserPageHeaderContentWithSeatsCap.spec.tsx
  apps/meteor/client/views/admin/users/UserPageHeaderContentWithSeatsCap.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.spec.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTableRow.tsx
  apps/meteor/client/views/admin/users/hooks/useFilteredUsers.ts
  apps/meteor/client/views/admin/users/hooks/useVoipExtensionAction.tsx
  apps/meteor/client/views/admin/users/voip/AssignExtensionButton.tsx
  apps/meteor/client/views/admin/users/voip/AssignExtensionModal.spec.tsx
  apps/meteor/client/views/admin/users/voip/AssignExtensionModal.tsx
  apps/meteor/client/views/admin/users/voip/RemoveExtensionModal.spec.tsx
  apps/meteor/client/views/admin/users/voip/RemoveExtensionModal.tsx
  apps/meteor/jest.config.ts
  apps/meteor/tests/mocks/client/meteor.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/mock-providers/src/MockedAppRootBuilder.tsx
Labels: stat: ready to merge, stat: QA assured

#33294 feat: Implement proper accessbility for report user modal
  .changeset/late-hats-carry.md
  apps/meteor/client/views/room/contextualBar/UserInfo/ReportUserModal.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33330 fix: imported fixes
  .changeset/little-bottles-peel.md
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/lib/server/methods/cleanRoomHistory.ts
  apps/meteor/client/components/message/content/urlPreviews/OEmbedHtmlPreview.tsx
  apps/meteor/tests/end-to-end/api/methods.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#33338 chore: create network broker package
  _templates/service/new/package.json.ejs.t
  _templates/service/new/service.ejs.t
  apps/meteor/ee/server/services/ecdh-proxy/service.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/package.json
  ee/apps/account-service/Dockerfile
  ee/apps/account-service/package.json
  ee/apps/account-service/src/service.ts
  ee/apps/authorization-service/Dockerfile
  ee/apps/authorization-service/package.json
  ee/apps/authorization-service/src/service.ts
  ee/apps/ddp-streamer/Dockerfile
  ee/apps/ddp-streamer/package.json
  ee/apps/ddp-streamer/src/service.ts
  ee/apps/omnichannel-transcript/Dockerfile
  ee/apps/omnichannel-transcript/package.json
  ee/apps/omnichannel-transcript/src/service.ts
  ee/apps/presence-service/Dockerfile
  ee/apps/presence-service/package.json
  ee/apps/presence-service/src/service.ts
  ee/apps/queue-worker/Dockerfile
  ee/apps/queue-worker/package.json
  ee/apps/queue-worker/src/service.ts
  ee/apps/stream-hub-service/Dockerfile
  ee/apps/stream-hub-service/package.json
  ee/apps/stream-hub-service/src/service.ts
  ee/packages/network-broker/.eslintrc.json
  ee/packages/network-broker/jest.config.ts
  ee/packages/network-broker/package.json
  ee/packages/network-broker/src/EnterpriseCheck.ts
  ee/packages/network-broker/src/NetworkBroker.test.ts
  ee/packages/network-broker/src/NetworkBroker.ts
  ee/packages/network-broker/src/index.ts
  ee/packages/network-broker/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33212 feat: Adds new admin feature preview setting management
  .changeset/quick-rings-wave.md
  apps/meteor/client/NavBarV2/NavBarSettingsToolbar/UserMenu/hooks/useAccountItems.tsx
  apps/meteor/client/hooks/useFeaturePreviewEnableQuery.ts
  apps/meteor/client/sidebar/header/hooks/useAccountItems.tsx
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewBadge.tsx
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.tsx
  apps/meteor/client/views/account/sidebarItems.tsx
  apps/meteor/client/views/admin/featurePreview/AdminFeaturePreviewPage.tsx
  apps/meteor/client/views/admin/featurePreview/AdminFeaturePreviewRoute.tsx
  apps/meteor/client/views/admin/routes.tsx
  apps/meteor/client/views/admin/sidebarItems.ts
  apps/meteor/public/images/featurePreview/enhanced-navigation.png
  apps/meteor/public/images/featurePreview/resizable-contextual-bar.png
  apps/meteor/public/images/featurePreview/timestamp.png
  apps/meteor/server/settings/accounts.ts
  apps/meteor/tests/end-to-end/api/miscellaneous.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/hi-IN.i18n.json
  packages/ui-client/src/components/FeaturePreview/FeaturePreviewBadge.tsx
  packages/ui-client/src/components/FeaturePreview/index.ts
  packages/ui-client/src/components/index.ts
  packages/ui-client/src/hooks/useDefaultSettingFeaturePreviewList.ts
  packages/ui-client/src/hooks/useFeaturePreview.ts
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
  packages/ui-client/src/hooks/usePreferenceFeaturePreviewList.spec.tsx
  packages/ui-client/src/hooks/usePreferenceFeaturePreviewList.ts
  packages/ui-client/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#33341 chore: move common files to core-services
  _templates/service/new/service.ejs.t
  ee/apps/account-service/src/service.ts
  ee/apps/authorization-service/src/service.ts
  ee/apps/ddp-streamer/src/service.ts
  ee/apps/omnichannel-transcript/src/service.ts
  ee/apps/presence-service/src/service.ts
  ee/apps/queue-worker/src/service.ts
  ee/apps/stream-hub-service/src/service.ts
  packages/core-services/src/index.ts
  packages/core-services/src/lib/mongo.ts
Labels: stat: ready to merge, stat: QA assured

#33342 regression: `Sidepanel` color highlight
  apps/meteor/package.json
  apps/uikit-playground/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33339 fix: Avoid destructuring `connectionData` when value is undefined
  .changeset/brave-brooms-invent.md
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
Labels: stat: ready to merge, stat: QA assured

#33356 chore: replace Meteor._localStorage -> Accounts.storageLocation
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/ui-master/server/scripts.ts
  apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
  apps/meteor/app/ui-utils/server/Message.ts
  apps/meteor/app/utils/client/lib/RestApiClient.ts
  apps/meteor/client/meteorOverrides/login/saml.ts
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/startup/accounts.ts
  apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
Labels: stat: ready to merge, stat: QA assured

#33368 Bump Apps-Engine version
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33370 regression: `Sidepanel` sort requires refresh after room update
  apps/meteor/client/views/room/Sidepanel/hooks/useTeamslistChildren.ts
Labels: stat: ready to merge, stat: QA assured

#33384 ci: remove Jira-GitHub security integration
  .github/workflows/vulnerabilities-jira-integration.yml
Labels: stat: ready to merge, stat: QA assured

#33324 chore: Single Contact ID: improved typings and removed some duplicated code
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/server/models/raw/LivechatCustomField.ts
Labels: stat: ready to merge, stat: QA assured

#33381 fix: race condition when forwarding livechat by splitting subscription removal
  .changeset/dry-taxis-cry.md
  apps/meteor/server/models/raw/BaseRaw.ts
Labels: stat: ready to merge, stat: QA assured

#33376 fix: Avoid notifying `watch.settings` on uncaught errors
  apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.ts
Labels: stat: ready to merge, stat: QA assured

#33279 chore: add gazzodown preview
  .gitignore
  packages/gazzodown/.storybook/main.js
  packages/gazzodown/package.json
Labels: stat: ready to merge, stat: QA assured

#33387 chore(Sidepanel): uses only local channels and discussions
  apps/meteor/client/views/room/Sidepanel/RoomSidepanel.tsx
  apps/meteor/client/views/room/Sidepanel/SidepanelItem/RoomSidepanelItem.tsx
  apps/meteor/client/views/room/Sidepanel/hooks/useTeamslistChildren.ts
Labels: stat: ready to merge, stat: QA assured

#33385 regression: MarkdownText component to parse nested emphasis tokens
  apps/meteor/client/components/MarkdownText.spec.tsx
  apps/meteor/client/components/MarkdownText.tsx
Labels: stat: ready to merge, stat: QA assured

#33378 fix: Async E2EE key exchange not working on develop
  .changeset/witty-apples-pretend.md
  apps/meteor/app/e2e/server/functions/handleSuggestedGroupKey.ts
  apps/meteor/app/e2e/server/methods/setUserPublicAndPrivateKeys.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
Labels: stat: ready to merge, stat: QA assured
