Repository RocketChat/Rocket.Chat, pull requests merged in 2024-03, with the labels that each got.

#31866 chore: remove hardcoded position for message date
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useDateScroll.ts
Labels: stat: needs QA

#31868 fix: message parser emphasis black hole
  packages/message-parser/src/grammar.pegjs
  packages/message-parser/src/utils.ts
  packages/message-parser/tests/emphasis.test.ts
  packages/message-parser/tsconfig.json
Labels: stat: ready to merge, stat: QA skipped

#31803 fix: Room import doesn't honor the specified owner
  .changeset/funny-cooks-sneeze.md
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/tests/e2e/fixtures/files/csv_import.zip
  apps/meteor/tests/e2e/fixtures/files/csv_import_rooms.csv
  apps/meteor/tests/e2e/fixtures/files/csv_import_users.csv
  apps/meteor/tests/e2e/fixtures/files/dm_messages.csv
  apps/meteor/tests/e2e/imports.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA tested, squad: core

#31757 chore: Remove references to EE code from the app bridges
  apps/meteor/app/apps/server/bridges/activation.ts
  apps/meteor/app/apps/server/bridges/api.ts
  apps/meteor/app/apps/server/bridges/cloud.ts
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/apps/server/bridges/details.ts
  apps/meteor/app/apps/server/bridges/environmental.ts
  apps/meteor/app/apps/server/bridges/http.ts
  apps/meteor/app/apps/server/bridges/internal.ts
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/apps/server/bridges/messages.ts
  apps/meteor/app/apps/server/bridges/moderation.ts
  apps/meteor/app/apps/server/bridges/oauthApps.ts
  apps/meteor/app/apps/server/bridges/persistence.ts
  apps/meteor/app/apps/server/bridges/roles.ts
  apps/meteor/app/apps/server/bridges/rooms.ts
  apps/meteor/app/apps/server/bridges/scheduler.ts
  apps/meteor/app/apps/server/bridges/settings.ts
  apps/meteor/app/apps/server/bridges/thread.ts
  apps/meteor/app/apps/server/bridges/uiInteraction.ts
  apps/meteor/app/apps/server/bridges/uploads.ts
  apps/meteor/app/apps/server/bridges/users.ts
  apps/meteor/app/apps/server/bridges/videoConferences.ts
  apps/meteor/app/apps/server/converters/departments.js
  apps/meteor/app/apps/server/converters/messages.js
  apps/meteor/app/apps/server/converters/roles.ts
  apps/meteor/app/apps/server/converters/rooms.js
  apps/meteor/app/apps/server/converters/threads.ts
  apps/meteor/app/apps/server/converters/transformMappedData.ts
  apps/meteor/app/apps/server/converters/uploads.js
  apps/meteor/app/apps/server/converters/videoConferences.ts
  apps/meteor/app/apps/server/converters/visitors.js
  apps/meteor/package.json
  packages/apps/.eslintrc.json
  packages/apps/package.json
  packages/apps/src/AppsEngine.ts
  packages/apps/src/IAppServerNotifier.ts
  packages/apps/src/IAppServerOrchestrator.ts
  packages/apps/src/converters/IAppConvertersMap.ts
  packages/apps/src/converters/IAppDepartmentsConverter.ts
  packages/apps/src/converters/IAppMessagesConverter.ts
  packages/apps/src/converters/IAppRolesConverter.ts
  packages/apps/src/converters/IAppRoomsConverter.ts
  packages/apps/src/converters/IAppSettingsConverter.ts
  packages/apps/src/converters/IAppThreadsConverter.ts
  packages/apps/src/converters/IAppUploadsConverter.ts
  packages/apps/src/converters/IAppUsersConverter.ts
  packages/apps/src/converters/IAppVideoConferencesConverter.ts
  packages/apps/src/converters/IAppVisitorsConverter.ts
  packages/apps/src/converters/index.ts
  packages/apps/src/index.ts
  packages/apps/tsconfig.json
  yarn.lock
Labels: stat: needs QA

#31207 chore: move utilitary functions out of ee folder
  apps/meteor/client/components/voip/room/VoipRoomForeword.tsx
  apps/meteor/client/lib/voip/parseOutboundPhoneNumber.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/sidebar/footer/voip/hooks/useOmnichannelContactLabel.ts
  apps/meteor/client/views/omnichannel/directory/calls/CallTableRow.tsx
  apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.tsx
  apps/meteor/client/views/room/Header/Omnichannel/VoipRoomHeader.tsx
Labels: stat: ready to merge, stat: QA skipped

#31885 chore: update ts version on recently merged package
  packages/apps/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31884 chore: Deprecate `insertOrUpdateUser` method
  .changeset/cuddly-rocks-fix.md
  apps/meteor/app/lib/server/methods/insertOrUpdateUser.ts
Labels: stat: ready to merge, stat: QA skipped, squad: core

#31651 fix: livechat agent status set to available after reactivation
  .changeset/nice-ducks-shout.md
  apps/meteor/app/livechat/server/hooks/afterUserActions.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/tests/data/livechat/users.ts
  apps/meteor/tests/end-to-end/api/01-users.js
Labels: stat: ready to merge, stat: QA tested

#31720 fix: New users are not automatically inserted in auto-join rooms inside default teams
  .changeset/calm-penguins-do.md
  apps/meteor/app/lib/server/functions/addUserToDefaultChannels.ts
  apps/meteor/app/lib/server/functions/getDefaultChannels.ts
  apps/meteor/tests/data/rooms.helper.js
  apps/meteor/tests/data/uploads.helper.ts
  apps/meteor/tests/end-to-end/api/01-users.js
  apps/meteor/tests/end-to-end/apps/05-video-conferences.ts
Labels: stat: ready to merge, stat: QA tested, squad: core

#31839 chore: replace `PaletteStyleTag` in favor of fuselage component
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
  apps/meteor/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/ui-theming/package.json
  ee/packages/ui-theming/src/PaletteStyleTag.tsx
  ee/packages/ui-theming/src/SidebarPaletteStyleTag.tsx
  ee/packages/ui-theming/src/codeBlockStyles.ts
  ee/packages/ui-theming/src/palette.ts
  ee/packages/ui-theming/src/paletteDark.ts
  ee/packages/ui-theming/src/paletteHighContrast.ts
  packages/fuselage-ui-kit/.storybook/DocsContainer.tsx
  packages/fuselage-ui-kit/.storybook/helpers.ts
  packages/fuselage-ui-kit/.storybook/preview.tsx
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31907 chore: improve useJumpToMessage
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/views/room/MessageList/hooks/useJumpToMessage.ts
Labels: stat: needs QA

#31903 Release 6.6.3
  .changeset/bump-patch-1709669273957.md
  .changeset/wicked-months-laugh.md
  apps/meteor/ee/server/startup/presence.ts
  apps/meteor/tests/end-to-end/api/01-users.js
  yarn.lock
Labels: stat: needs QA

#31662 fix: Jump to message only works once
  .changeset/gold-tigers-rhyme.md
  apps/meteor/client/lib/utils/setMessageJumpQueryStringParameter.ts
Labels: stat: ready to merge, stat: QA tested

#31901 chore: remove useScrollMessageList hook
  apps/meteor/client/components/message/list/MessageListContext.tsx
  apps/meteor/client/views/room/MessageList/MessageList.tsx
  apps/meteor/client/views/room/MessageList/hooks/useJumpToMessage.ts
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useScrollMessageList.ts
Labels: stat: needs QA

#31902 chore: create useListIsAtBottom hook
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useListIsAtBottom.ts
Labels: stat: needs QA

#31912 chore: create RoomBody useFileUpload hook
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useFileUpload.ts
Labels: stat: ready to merge, stat: QA skipped

#31908 chore: move store scroll position to useRestoreScrollPosition (#31902)
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
Labels: stat: ready to merge, stat: QA skipped

#31910 chore: create RoomBody useQuoteMessageByUrl hook
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useQuoteMessageByUrl.ts
Labels: stat: needs QA

#31911 chore: create Roombody useLeaderBanner hook
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useLeaderBanner.ts
Labels: stat: needs QA

#31790 fix: Fixes SAML Role mapping of custom roles
  .changeset/curly-impalas-wave.md
Labels: stat: QA tested

#31539 refactor: Delay queue-worker start until first work is received
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  ee/packages/omnichannel-services/src/QueueWorker.ts
  ee/packages/omnichannel-services/src/externals/mongo-message-queue.d.ts
Labels: stat: ready to merge, stat: QA skipped

#31914 chore: create RoomBody useHandleUnread hook
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/UnreadMessagesIndicator.tsx
  apps/meteor/client/views/room/body/hooks/useLeaderBanner.ts
  apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
Labels: stat: needs QA

#31913 chore: create RoomBody useGetMore hook
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useGetMore.ts
Labels: stat: needs QA

#31921 refactor: RoomBody reorganize props, hooks, callbacks, effects in order
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useGetMore.ts
  apps/meteor/client/views/room/body/hooks/useHasNewMessages.ts
  apps/meteor/client/views/room/body/hooks/useLeaderBanner.ts
  apps/meteor/client/views/room/body/hooks/useListIsAtBottom.ts
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
  apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useDateScroll.ts
Labels: stat: ready to merge, stat: QA skipped

#31775 chore: Remove references to EE code from the app events
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/methods/deleteUserOwnAccount.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/ee/server/apps/index.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/server/lib/moderation/reportMessage.ts
  apps/meteor/server/methods/deleteUser.ts
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/methods/logoutCleanUp.ts
  apps/meteor/server/methods/reportMessage.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/server/startup/migrations/v291.ts
  apps/meteor/server/startup/migrations/v292.ts
  apps/meteor/server/startup/migrations/v294.ts
  packages/apps/src/AppsEngine.ts
  packages/apps/src/IAppServerOrchestrator.ts
  packages/apps/src/bridges/IListenerBridge.ts
  packages/apps/src/index.ts
  packages/apps/src/orchestrator.ts
  yarn.lock
Labels: stat: needs QA

#31922 Revert "chore: Remove references to EE code from the app events"
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/methods/deleteUserOwnAccount.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/ee/server/apps/index.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/server/lib/moderation/reportMessage.ts
  apps/meteor/server/methods/deleteUser.ts
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/methods/logoutCleanUp.ts
  apps/meteor/server/methods/reportMessage.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/server/startup/migrations/v291.ts
  apps/meteor/server/startup/migrations/v292.ts
  apps/meteor/server/startup/migrations/v294.ts
  packages/apps/src/AppsEngine.ts
  packages/apps/src/IAppServerOrchestrator.ts
  packages/apps/src/bridges/IListenerBridge.ts
  packages/apps/src/index.ts
  packages/apps/src/orchestrator.ts
  yarn.lock
Labels: stat: needs QA

#31916 regression: `MessageToolbarMenu` not rendering on demand
  apps/meteor/client/components/message/MessageToolbarHolder.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/room/hooks/useIsVisible.ts
  apps/meteor/package.json
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-center.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-manage-contact.ts
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: needs QA

#31928 chore: remove forgotten console.log from federation
  apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
Labels: stat: needs QA

#31872 chore: date scroll improvements
  apps/meteor/client/views/room/BubbleDate/BubbleDate.tsx
  apps/meteor/client/views/room/BubbleDate/index.tsx
  apps/meteor/client/views/room/MessageList/MessageListItem.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/UnreadMessagesIndicator.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageItem.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useDateScroll.ts
Labels: stat: needs QA

#31915 refactor: Use `settings` instead of model for fetching initial omnichannel config
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
Labels: stat: ready to merge, stat: QA tested

#31929 regression: `RoomBody` unread and new messages behavior
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/hooks/useHasNewMessages.ts
  apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
Labels: stat: needs QA

#31877 chore: Migrate notifyUsersOnMessage to TypeScript
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts
  apps/meteor/app/mentions/server/getMentionedTeamMembers.ts
  apps/meteor/app/threads/server/hooks/aftersavemessage.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  packages/model-typings/src/models/IRoomsModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA skipped

#31934 regression: Favorite action announcement
  apps/meteor/client/views/room/Header/icons/Favorite.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: needs QA

#31935 Revert "regression: Favorite action announcement"
  apps/meteor/client/views/room/Header/icons/Favorite.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: needs QA

#31660 fix: Quote attachments are not deleted on message update
  .changeset/eight-rice-tease.md
  apps/meteor/server/services/messages/hooks/BeforeSaveJumpToMessage.ts
  apps/meteor/tests/end-to-end/api/05-chat.js
  apps/meteor/tests/end-to-end/api/24-methods.js
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveJumpToMessage.tests.ts
  packages/core-typings/src/IMessage/MessageAttachment/MessageQuoteAttachment.ts
Labels: stat: ready to merge, stat: QA tested, squad: core

#31938 chore: improve connecting procedure
  packages/livechat/src/api.ts
  packages/livechat/src/lib/connection.ts
  packages/livechat/src/providers/SDKProvider.tsx
  packages/livechat/src/store/index.tsx
Labels: stat: needs QA

#31896 fix: Validate rooms are not taken before processing by queue
  .changeset/strange-jars-invent.md
  apps/meteor/server/services/omnichannel/queue.ts
Labels: stat: ready to merge, stat: QA tested

#31919 refactor: use uiContexts on livechat
  packages/livechat/package.json
  packages/livechat/src/api.ts
  packages/livechat/src/components/App/index.tsx
  packages/livechat/src/components/Calls/CallIFrame.tsx
  packages/livechat/src/components/Calls/JoinCallButton.tsx
  packages/livechat/src/hooks/livechatRoomSubscriptionHooks.ts
  packages/livechat/src/hooks/useDeleteMessageSubscription.ts
  packages/livechat/src/hooks/useRoomMessagesSubscription.ts
  packages/livechat/src/hooks/useUserActivitySubscription.ts
  packages/livechat/src/lib/connection.ts
  packages/livechat/src/lib/room.js
  packages/livechat/src/providers/ConnectionStatusProvider.tsx
  packages/livechat/src/providers/SDKProvider.tsx
  packages/livechat/src/providers/ServerProvider.tsx
  packages/livechat/src/routes/Chat/container.js
  packages/livechat/src/store/index.tsx
  yarn.lock
Labels: stat: needs QA

#31932 regression: undefined guest causing issues
  packages/livechat/src/lib/hooks.ts
  packages/livechat/src/store/index.tsx
Labels: stat: ready to merge, stat: QA tested

#31927 fix: convert network broker stopped lifecycle method to async
  .changeset/slimy-clocks-argue.md
  apps/meteor/app/search/server/search.internalService.ts
  apps/meteor/ee/server/NetworkBroker.ts
  apps/meteor/ee/server/startup/services.ts
  apps/meteor/ee/tests/unit/server/NetworkBroker.tests.ts
  apps/meteor/tests/mocks/server/BrokerMocked.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveCheckMAC.tests.ts
  packages/core-services/src/LocalBroker.ts
  packages/core-services/src/lib/Api.ts
  packages/core-services/src/types/IApiService.ts
  packages/core-services/src/types/IBroker.ts
Labels: stat: ready to merge, stat: QA skipped

#31810 feat(message-parser): add timestamps pattern
  .changeset/stupid-trains-trade.md
  apps/meteor/client/components/GazzodownText.tsx
  ee/packages/pdf-worker/src/templates/ChatTranscript/markup/elements/StrikeSpan.tsx
  packages/gazzodown/.storybook/main.js
  packages/gazzodown/package.json
  packages/gazzodown/src/Markup.stories.tsx
  packages/gazzodown/src/MarkupInteractionContext.ts
  packages/gazzodown/src/elements/ImageElement.tsx
  packages/gazzodown/src/elements/InlineElements.tsx
  packages/gazzodown/src/elements/StrikeSpan.tsx
  packages/gazzodown/src/elements/Timestamp/ErrorBoundary.tsx
  packages/gazzodown/src/elements/Timestamp/index.tsx
  packages/gazzodown/src/elements/Timestamp/timeago.ts
  packages/i18n/src/locales/en.i18n.json
  packages/message-parser/README.md
  packages/message-parser/package.json
  packages/message-parser/src/definitions.ts
  packages/message-parser/src/grammar.pegjs
  packages/message-parser/src/utils.ts
  packages/message-parser/tests/timestamp.test.ts
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31869 regression: Prevents `ImageGallery` to restore focus on message
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
Labels: stat: ready to merge, stat: QA skipped

#31940 regression: Favorite action announcement
  apps/meteor/client/views/room/Header/icons/Favorite.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#31909 fix: Trigger app event after inquiry is created
  .changeset/bright-cycles-count.md
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
Labels: stat: ready to merge, stat: QA skipped

#31792 fix: setDepartment not persisting on chat closed
  .changeset/thin-keys-impress.md
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  packages/livechat/src/lib/hooks.ts
  packages/livechat/src/lib/room.js
Labels: stat: ready to merge, stat: QA tested

#31656 test: make outgoing integrations fully independent
  apps/meteor/tests/end-to-end/api/06-outgoing-integrations.js
Labels: stat: ready to merge, stat: QA skipped

#31880 fix: CRM integration mismatch on callback type
  .changeset/slow-jobs-think.md
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/tests/unit/app/livechat/server/hooks/sendToCRM.tests.ts
Labels: stat: ready to merge, stat: QA skipped

#31268 feat: Use external service for triggers
  .changeset/rich-rocks-happen.md
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/client/views/omnichannel/triggers/ConditionForm.tsx
  apps/meteor/client/views/omnichannel/triggers/EditTrigger.tsx
  apps/meteor/client/views/omnichannel/triggers/actions/ActionExternalServiceUrl.tsx
  apps/meteor/client/views/omnichannel/triggers/actions/ActionForm.tsx
  apps/meteor/client/views/omnichannel/triggers/actions/ActionSender.tsx
  apps/meteor/client/views/omnichannel/triggers/actions/ExternalServiceActionForm.tsx
  apps/meteor/client/views/omnichannel/triggers/actions/SendMessageActionForm.tsx
  apps/meteor/client/views/omnichannel/triggers/hooks/index.ts
  apps/meteor/client/views/omnichannel/triggers/hooks/useFieldError.tsx
  apps/meteor/client/views/omnichannel/triggers/utils/getActionFormFields.tsx
  apps/meteor/client/views/omnichannel/triggers/utils/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/triggers.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/triggers.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-triggers.ts
  apps/meteor/tests/end-to-end/api/livechat/08-triggers.ts
  packages/core-typings/src/ILivechatTrigger.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/livechat/src/components/App/App.tsx
  packages/livechat/src/definitions/agents.d.ts
  packages/livechat/src/helpers/canRenderMessage.ts
  packages/livechat/src/lib/api.ts
  packages/livechat/src/lib/hooks.ts
  packages/livechat/src/lib/triggerActions.ts
  packages/livechat/src/lib/triggerConditions.ts
  packages/livechat/src/lib/triggerUtils.ts
  packages/livechat/src/lib/triggers.js
  packages/livechat/src/routes/Chat/connector.tsx
  packages/livechat/src/routes/Register/index.tsx
  packages/livechat/src/store/index.tsx
  packages/livechat/src/widget.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31962 regression: Livechat offline color not being applied
  packages/livechat/src/components/Screen/index.js
  packages/livechat/src/routes/LeaveMessage/index.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31963 regression: Timestamp missing milliseconds
  packages/gazzodown/src/Markup.stories.tsx
  packages/gazzodown/src/elements/Timestamp/index.tsx
Labels: stat: ready to merge, stat: QA tested

#31971 chore: `UnreadMessages` bubble tweaks
  apps/meteor/client/views/room/body/UnreadMessagesIndicator.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/i18n/src/locales/en.i18n.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31973 fix: command preview
  .changeset/cmd_preview.md
  apps/meteor/client/views/room/composer/ComposerBoxPopupPreview.tsx
Labels: stat: ready to merge, stat: QA skipped

#31663 fix: setDepartment Livechat API call overriding triggers
  .changeset/afraid-mugs-priest.md
  packages/livechat/src/lib/hooks.ts
  packages/livechat/src/routes/Register/index.tsx
  packages/livechat/src/store/index.tsx
Labels: stat: ready to merge, stat: QA skipped

#31961 regression: `EmojiPicker` wrong height calculation
  apps/meteor/client/views/composer/EmojiPicker/EmojiPickerDesktopDropdown.tsx
Labels: stat: ready to merge, stat: QA skipped

#31970 fix: enterprise settings value not being updated when license is removed/invalid
  .changeset/chatty-horses-peel.md
  apps/meteor/ee/app/settings/server/settings.ts
Labels: stat: ready to merge, stat: QA tested

#31985 regression: Livechat resubscription
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  packages/livechat/src/providers/ServerProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#31538 feat: introduce new methods to fetch rooms on Livechat Bridge
  .changeset/tiny-toes-fail.md
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/server/models/raw/LivechatRooms.ts
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#31999 regression: triggers being scheduled when user is already registered
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-open-by-visitor.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-time-on-site.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  packages/livechat/src/lib/triggers.js
Labels: stat: ready to merge, stat: QA tested

#31900 refactor: Improve queue startup process & reliability
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/livechat/server/startup.ts
  apps/meteor/server/services/omnichannel/queue.ts
Labels: stat: ready to merge, stat: QA skipped

#31883 fix: generate png thumbnail previews for svg files
  .changeset/happy-jars-lick.md
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/tests/data/interactions.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
  apps/meteor/tests/mocks/files/sample-jpeg.jpg
Labels: stat: ready to merge, stat: QA tested

#32002 test: forward messages
  apps/meteor/client/views/room/modals/ForwardMessageModal/ForwardMessageModal.tsx
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA skipped

#31718 feat: Trigger chat-visitor-registered on 'new chat' after closing
  .changeset/fair-triggers-suffer.md
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-after-registration.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-triggers.ts
  packages/livechat/src/lib/room.js
  packages/livechat/src/lib/triggers.js
  packages/livechat/src/routes/ChatFinished/component.tsx
Labels: stat: ready to merge, stat: QA tested

#32001 chore: do not expect retries for pull requests
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
Labels: stat: ready to merge, stat: QA tested

#31983 fix: `Edit Discussion` name validation allow special characters
  .changeset/mean-rabbits-hope.md
  apps/meteor/app/channel-settings/server/functions/saveRoomName.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/utils/server/lib/getValidRoomName.ts
  apps/meteor/server/services/room/service.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/core-services/src/types/IRoomService.ts
  packages/rest-typings/src/v1/teams/index.ts
Labels: stat: ready to merge, stat: QA tested

#31942 chore: split scalability EE module into two
  ee/packages/license/src/v2/bundles.ts
  ee/packages/presence/src/Presence.ts
  packages/core-typings/src/license/LicenseModule.ts
  packages/jwt/__tests__/jwt.spec.ts
Labels: stat: ready to merge, stat: QA tested

#32017 test: solve flaky edit unit test
  apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
Labels: stat: ready to merge, stat: QA tested

#31978 chore: `Contextualbar` as `dialog` instead of `aside`
  apps/meteor/client/components/Contextualbar/Contextualbar.tsx
  apps/meteor/client/components/Contextualbar/ContextualbarDialog.tsx
  apps/meteor/client/components/Contextualbar/ContextualbarTitle.tsx
  apps/meteor/client/components/Contextualbar/index.ts
  apps/meteor/client/components/UserInfo/UserInfo.tsx
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfList.tsx
  apps/meteor/client/views/room/layout/RoomLayout.tsx
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/team-management.spec.ts
  apps/meteor/tests/e2e/threads.spec.ts
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#31948 fix: Incorrect initial data not allowing edit webhooks properly
  .changeset/breezy-fireants-float.md
  apps/meteor/client/views/admin/integrations/incoming/EditIncomingWebhook.tsx
  apps/meteor/client/views/admin/integrations/outgoing/EditOutgoingWebhook.tsx
Labels: stat: ready to merge, stat: QA tested

#31881 fix: Multiple type of BH making bots not available on opening
  .changeset/brown-houses-rush.md
  apps/meteor/server/models/raw/Users.js
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA tested

#32005 chore: remove duplicate function call
  apps/meteor/client/components/message/hooks/useNormalizedMessage.ts
Labels: stat: ready to merge, stat: QA skipped

#31904 fix: Always show all rooms when requesting chat history, even unserved ones
  .changeset/spotty-students-warn.md
  apps/meteor/client/views/omnichannel/contactHistory/useHistoryList.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
Labels: stat: ready to merge, stat: QA tested

#32025 chore(livechat): stop calling twice closeChat
  packages/livechat/src/lib/room.js
Labels: stat: ready to merge, stat: QA tested

#31813 chore: Allow multiple regions for Modals.
  apps/meteor/client/lib/imperativeModal.ts
  apps/meteor/client/lib/imperativeModal.tsx
  apps/meteor/client/providers/MeteorProvider.tsx
  apps/meteor/client/providers/ModalProvider.tsx
  apps/meteor/client/providers/ModalProvider/ModalProvider.spec.tsx
  apps/meteor/client/providers/ModalProvider/ModalProvider.tsx
  apps/meteor/client/providers/ModalProvider/ModalProviderWithRegion.tsx
  apps/meteor/client/providers/ModalProvider/ModalStore.ts
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/hooks/useVideoConfOpenCall.spec.tsx
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/mock-providers/src/MockedModalContext.tsx
  packages/ui-contexts/src/ModalContext.ts
  packages/ui-contexts/src/hooks/useCurrentModal.ts
Labels: stat: ready to merge, stat: QA tested

#32020 chore: Extra log on `setDepartment` API call when department provided is invalid
  packages/livechat/src/lib/hooks.ts
Labels: stat: ready to merge, stat: QA skipped

#32012 chore(federation-v2): do not load registration.yaml file in container
  .changeset/moody-ghosts-add.md
  apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Settings.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: needs QA

#32029 regression: `UserCard` alignment
  apps/meteor/client/views/room/providers/UserCardProvider.tsx
Labels: stat: ready to merge, stat: QA tested

#32016 Release 6.6.4
  .changeset/bump-patch-1710772454766.md
  .changeset/cyan-countries-impress.md
  .changeset/moody-ghosts-add.md
  .changeset/slimy-clocks-argue.md
  .gitignore
  apps/meteor/app/search/server/search.internalService.ts
  apps/meteor/ee/server/NetworkBroker.ts
  apps/meteor/ee/server/startup/services.ts
  apps/meteor/ee/tests/unit/server/NetworkBroker.tests.ts
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Settings.ts
  apps/meteor/tests/mocks/server/BrokerMocked.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveCheckMAC.tests.ts
  packages/core-services/src/LocalBroker.ts
  packages/core-services/src/lib/Api.ts
  packages/core-services/src/types/IApiService.ts
  packages/core-services/src/types/IBroker.ts
  yarn.lock
Labels: stat: needs QA

#32027 test: fix Manual Selection - queue
  apps/meteor/client/hooks/useRoomInfoEndpoint.ts
  apps/meteor/client/views/omnichannel/directory/hooks/useOmnichannelRoomInfo.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useReturnChatToQueueMutation.ts
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
Labels: stat: ready to merge, stat: QA tested

#32026 regression: Missing `ContextualbarDialog` wrapping in administration and Omnichannel
  apps/meteor/client/components/Contextualbar/ContextualbarDialog.tsx
  apps/meteor/client/views/admin/customEmoji/CustomEmojiRoute.tsx
  apps/meteor/client/views/admin/customSounds/CustomSoundsPage.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusRoute.tsx
  apps/meteor/client/views/admin/moderation/ModConsoleReportDetails.tsx
  apps/meteor/client/views/admin/moderation/ModerationConsolePage.tsx
  apps/meteor/client/views/admin/permissions/PermissionsContextBar.tsx
  apps/meteor/client/views/admin/rooms/RoomsPage.tsx
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx
  apps/meteor/client/views/omnichannel/currentChats/CustomFieldsList.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsPage.tsx
  apps/meteor/client/views/omnichannel/directory/ContactContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/OmnichannelDirectoryPage.tsx
  apps/meteor/client/views/omnichannel/triggers/TriggersPage.tsx
  apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
  apps/meteor/ee/client/omnichannel/priorities/PriorityList.tsx
  apps/meteor/ee/client/omnichannel/slaPolicies/SlaPage.tsx
  apps/meteor/ee/client/omnichannel/tags/TagsPage.tsx
  apps/meteor/ee/client/omnichannel/units/UnitsPage.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminPage.tsx
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfoWithData.tsx
Labels: stat: ready to merge, stat: QA tested

#32031 fix(Livechat): Livechat_Display_Offline_Form not working correctly
  .changeset/polite-cars-love.md
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  packages/livechat/src/i18n/en.json
  packages/livechat/src/i18n/pt-BR.json
  packages/livechat/src/routes/LeaveMessage/index.tsx
Labels: stat: ready to merge, stat: QA tested

#32033 test: fix Default rooms flaky
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA tested

#32023 docs: Fix code typo in ddp-client readme
  ee/packages/ddp-client/README.md
Labels: type: documentation, stat: ready to merge, stat: QA skipped

#32019 fix: "Media type not accepted" error when uploading `lst` files
  .changeset/lovely-berries-type.md
  apps/meteor/app/utils/lib/mimeTypes.ts
  apps/meteor/tests/data/interactions.ts
  apps/meteor/tests/e2e/file-upload.spec.ts
  apps/meteor/tests/e2e/fixtures/files/lst-test.lst
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
Labels: stat: ready to merge, stat: QA tested

#31997 chore: Change internal and external links target
  apps/meteor/client/components/MarkdownText.tsx
  packages/gazzodown/jest.config.ts
  packages/gazzodown/src/elements/LinkSpan.tsx
  packages/i18n/src/locales/en.i18n.json
  packages/ui-client/src/helpers/getBaseURI.ts
  packages/ui-client/src/helpers/index.ts
  packages/ui-client/src/index.ts
Labels: stat: ready to merge, stat: QA skipped

#32037 regression: `EmojiPicker` wrong placement
  apps/meteor/client/views/composer/EmojiPicker/EmojiPickerDesktopDropdown.tsx
Labels: stat: ready to merge, stat: QA tested

#31998 fix: Allow queue to fix inquiry status when processing items
  .changeset/tough-doors-juggle.md
  apps/meteor/server/services/omnichannel/queue.ts
  apps/meteor/tests/unit/server/services/omnichannel/queue.tests.ts
Labels: stat: ready to merge, stat: QA tested

#32039 Release 6.6.5
  .changeset/bump-patch-1710964059521.md
  .changeset/empty-hounds-jog.md
  .changeset/thin-keys-impress.md
  .changeset/tough-doors-juggle.md
  apps/meteor/server/services/omnichannel/queue.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  apps/meteor/tests/unit/server/services/omnichannel/queue.tests.ts
  ee/packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/livechat/src/lib/hooks.js
  packages/livechat/src/lib/room.js
  yarn.lock
Labels: stat: needs QA

#31995 test(Livechat): More Livechat Tests
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-department.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/page-objects/home-omnichannel.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  apps/meteor/tests/e2e/utils/omnichannel/departments.ts
  packages/livechat/src/components/Header/index.tsx
  packages/livechat/src/routes/SwitchDepartment/index.tsx
Labels: stat: ready to merge, stat: QA tested

#32036 refactor: Add `projection` and change promise calls to `Promise.all` on LivechatAgentActivityMonitor
  apps/meteor/app/livechat/server/statistics/LivechatAgentActivityMonitor.ts
Labels: stat: ready to merge, stat: QA skipped

#31751 feat: Added setting and method to control Livechat system messages visibility
  .changeset/cyan-shoes-fly.md
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/livechat/src/helpers/canRenderMessage.ts
  packages/livechat/src/lib/hooks.ts
  packages/livechat/src/store/index.tsx
  packages/livechat/src/widget.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#32050 test(Omnichannel): fix flaky units test
  apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
Labels: stat: ready to merge, stat: QA tested

#31890 fix: `livechat/visitor` not updating custom fields some times
  .changeset/happy-pillows-call.md
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/server/models/raw/LivechatCustomField.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  packages/model-typings/src/models/ILivechatCustomFieldModel.ts
Labels: stat: ready to merge, stat: QA tested

#31894 fix: Layout shift on room body when loading uikit messages
  .changeset/long-phones-reflect.md
  apps/meteor/client/components/message/uikit/UiKitMessageBlock.tsx
  packages/fuselage-ui-kit/src/elements/MarkdownTextElement.tsx
  packages/gazzodown/src/elements/BoldSpan.tsx
  packages/gazzodown/src/elements/InlineElements.tsx
  packages/gazzodown/src/elements/ItalicSpan.tsx
  packages/gazzodown/src/elements/StrikeSpan.tsx
Labels: stat: ready to merge, stat: QA skipped

#32051 test(Omnichannel): fix priorities flaky test
  apps/meteor/tests/e2e/omnichannel/omnichannel-priorities-sidebar.spec.ts
Labels: stat: ready to merge, stat: QA tested

#32038 feat: added tag to premium settings in CE workspaces
  .changeset/thirty-berries-learn.md
  apps/meteor/client/views/admin/settings/MemoizedSetting.tsx
  apps/meteor/client/views/admin/settings/Setting.tsx
  apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/CodeMirror/CodeMirrorBox.tsx
  apps/meteor/client/views/admin/settings/inputs/CodeSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/ColorSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/FontSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/GenericSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/IntSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/LanguageSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/LookupSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/MultiSelectSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/PasswordSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/RelativeUrlSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/RoomPickSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/SelectSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/SelectTimezoneSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/StringSettingInput.tsx
  apps/meteor/client/views/admin/settings/inputs/types.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31772 feat: Livechat theming improvements
  .changeset/fuzzy-vans-own.md
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/livechat/src/components/App/App.tsx
  packages/livechat/src/components/Messages/Message/index.js
  packages/livechat/src/components/Messages/MessageAvatars/index.js
  packages/livechat/src/components/Messages/MessageBubble/styles.scss
  packages/livechat/src/components/Messages/MessageList/index.js
  packages/livechat/src/components/Messages/MessageList/styles.scss
  packages/livechat/src/components/Screen/ScreenProvider.tsx
  packages/livechat/src/components/Screen/index.js
  packages/livechat/src/components/Screen/styles.scss
  packages/livechat/src/lib/hooks.ts
  packages/livechat/src/routes/Chat/component.js
  packages/livechat/src/routes/Chat/connector.tsx
  packages/livechat/src/store/index.tsx
  packages/livechat/src/widget.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#32056 fix: proxified model props were missing context before attribution
  .changeset/thirty-ducks-smell.md
  .changeset/twenty-dolls-obey.md
  .vscode/settings.json
  packages/models/jest.config.ts
  packages/models/package.json
  packages/models/src/proxify.spec.ts
  packages/models/src/proxify.ts
Labels: stat: ready to merge, stat: QA skipped

#32049 regression: Focus the most recent message instead of the first on message list
  apps/meteor/client/views/room/hooks/useMessageListNavigation.ts
Labels: stat: needs QA

#31820 feat(livechat): hide or change logo
  .changeset/clean-cars-teach.md
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/ee/app/livechat-enterprise/server/settings.ts
  packages/core-typings/src/IRocketChatAssets.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/livechat/src/components/Screen/ChatButton.tsx
  packages/livechat/src/components/Screen/ScreenProvider.tsx
  packages/livechat/src/components/Screen/index.js
  packages/livechat/src/store/index.tsx
Labels: stat: QA tested, squad: omnichannel

#31968 test: failing registerGuest function when same token is provided
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
Labels: stat: ready to merge, stat: QA tested

#32043 feat: added Livechat's new theming settings to Appearance page
  .changeset/good-baboons-shop.md
  apps/meteor/app/livechat/imports/server/rest/appearance.ts
  apps/meteor/app/livechat/server/api/lib/appearance.ts
  apps/meteor/client/views/omnichannel/appearance/AppearanceFieldLabel.tsx
  apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#32061 regression: Unintentional semi-colon on ui-kit messages
  packages/fuselage-ui-kit/src/elements/MarkdownTextElement.tsx
Labels: stat: ready to merge, stat: QA skipped

#32064 chore: bump apps engine version
  .changeset/chatty-suits-dance.md
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#32065 chore: bump apps engine version to 1.41.1
  .changeset/nervous-parrots-march.md
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#32057 Release 6.6.6
  .changeset/bump-patch-1711139853086.md
  .changeset/chatty-suits-dance.md
  .changeset/thirty-ducks-smell.md
  .changeset/twenty-dolls-obey.md
  .vscode/settings.json
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/models/jest.config.ts
  packages/models/package.json
  packages/models/src/proxify.spec.ts
  packages/models/src/proxify.ts
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: needs QA

#32021 fix: prevent duplicate api calls in forwarding livechat rooms
  .changeset/strong-bananas-flash.md
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
Labels: stat: ready to merge, stat: QA tested

#32055 feat: `ConnectionStatusBar` redesign
  .changeset/two-suns-marry.md
  apps/meteor/client/components/connectionStatus/ConnectionStatusBar.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#32077 regression: `ContextualbarDialog` being displayed without route param on Omnichannel directory
  apps/meteor/client/views/omnichannel/directory/ContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/OmnichannelDirectoryPage.tsx
Labels: stat: ready to merge, stat: QA tested

#32067 regression: `UserCard` overlapping `Modal`
  apps/meteor/client/components/modal/ModalBackdrop.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/livechat/package.json
  packages/ui-client/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#32022 chore: register a dummy Read Receipts model in CE
  apps/meteor/server/models/ReadReceipts.ts
  apps/meteor/server/models/dummy/BaseDummy.ts
  apps/meteor/server/models/dummy/ReadReceipts.ts
  apps/meteor/server/models/startup.ts
  packages/models/src/proxify.ts
Labels: stat: ready to merge, stat: QA skipped

#32086 fix!: api login should not suggest which credential is wrong
  .changeset/fuzzy-cherries-buy.md
  apps/meteor/app/lib/server/lib/loginErrorMessageOverride.js
  apps/meteor/app/lib/server/lib/loginErrorMessageOverride.ts
  apps/meteor/client/meteorOverrides/login/google.ts
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/tests/end-to-end/api/31-failed-login-attempts.ts
Labels: stat: ready to merge, stat: QA skipped

#31786 test: make login api tests fully independent
  apps/meteor/tests/end-to-end/api/31-failed-login-attempts.ts
Labels: stat: ready to merge, stat: QA skipped

#32085 fix: internal server error when connecting to publication with backward compatibility flag
  .changeset/great-yaks-dream.md
  ee/apps/ddp-streamer/src/Publication.ts
Labels: stat: ready to merge, stat: QA skipped

#31783 test: make roles fully independent
  apps/meteor/tests/end-to-end/api/28-roles.ts
Labels: stat: ready to merge, stat: QA skipped

#31782 test: make presence api tests fully independent
  apps/meteor/tests/end-to-end/api/27-presence.ts
Labels: stat: ready to merge, stat: QA skipped

#32092 test(Livechat): Clean up after registerGuest() test
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
Labels: stat: ready to merge, stat: QA tested
