Repository RocketChat/Rocket.Chat, pull requests merged in 2024-08, with the labels that each got.

#32942 chore: Remove `ui-kit` from `yarn fuselage` script
  fuselage.sh
Labels: stat: QA assured

#32944 chore: Exclude Storybook stories from the build of `@rocket.chat/ui-composer`
  packages/ui-composer/package.json
  packages/ui-composer/tsconfig.build.json
Labels: stat: ready to merge, stat: QA assured

#32860 chore: Use index on `unlockAll` query called when changing OM routing methods
  apps/meteor/server/models/raw/LivechatInquiry.ts
Labels: stat: ready to merge, stat: QA assured

#32867 feat: add `Advanced settings` on create Team and Channel
  .changeset/lemon-steaks-provide.md
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
  apps/meteor/client/sidebarv2/header/CreateChannelModal.tsx
  apps/meteor/client/sidebarv2/header/CreateTeamModal.tsx
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/team-management.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32958 chore: update apps-engine
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32968 fix: `Menu` onPointerUp event behavior
  .changeset/brown-crabs-chew.md
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32970 chore: create `afterOmnichannelSaveMessage`
  apps/meteor/app/livechat/server/hooks/afterSaveOmnichannelMessage.ts
  apps/meteor/app/livechat/server/hooks/leadCapture.ts
  apps/meteor/app/livechat/server/hooks/markRoomNotResponded.ts
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/app/livechat/server/hooks/saveLastMessageToInquiry.ts
  apps/meteor/app/livechat/server/hooks/saveLastVisitorMessageTs.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/app/livechat/server/sendMessageBySMS.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/setPredictedVisitorAbandonmentTime.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: needs testing

#32948 chore: create `orm` for specific cases
  apps/meteor/server/models/raw/BaseRaw.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/updater.ts
  packages/models/package.json
  packages/models/src/index.ts
  packages/models/src/updater.spec.ts
  packages/models/src/updater.ts
  yarn.lock
Labels: stat: needs testing

#32972 regression: fix dispatchInquiryPosition not being fired on room creation
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
Labels: stat: ready to merge, stat: QA assured

#32961 chore: saveAnalyticsData with accumulator
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: needs testing

#32969 feat: Upgrade `fuselage-toastbar` adding pause on hover
  .changeset/strong-swans-double.md
  apps/meteor/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32978 chore: move afterOmnichannelSaveMessage hook to work with updater
  apps/meteor/app/livechat/server/hooks/afterSaveOmnichannelMessage.ts
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: needs testing

#32977 chore: add updater on afterOmnichannelSaveMessage (save-last-visitor-message-timestamp) hook
  apps/meteor/app/livechat/server/hooks/saveLastVisitorMessageTs.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: needs testing

#32990 chore: replace `dtinth/setup-github-actions-caching-for-turbo` to use `rhark…
  .github/actions/build-docker/action.yml
  .github/actions/meteor-build/action.yml
  .github/workflows/ci-code-check.yml
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci-test-unit.yml
  .github/workflows/ci.yml
  .github/workflows/new-release.yml
  .github/workflows/pr-update-description.yml
  .github/workflows/publish-release.yml
  package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32941 chore: don't mark room as read after sending message
  apps/meteor/client/lib/chats/flows/sendMessage.ts
  apps/meteor/tests/end-to-end/api/subscriptions.ts
Labels: stat: ready to merge, stat: QA assured

#32987 chore: Renders back button through prop in admin settings
  apps/meteor/client/views/admin/settings/GroupPage.tsx
  apps/meteor/client/views/admin/settings/GroupSelector.tsx
  apps/meteor/client/views/admin/settings/SettingsRoute.tsx
  apps/meteor/client/views/admin/settings/groups/AssetsGroupPage.tsx
  apps/meteor/client/views/admin/settings/groups/GenericGroupPage.tsx
  apps/meteor/client/views/admin/settings/groups/LDAPGroupPage.tsx
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage.tsx
  apps/meteor/client/views/admin/settings/groups/TabbedGroupPage.tsx
  apps/meteor/client/views/admin/settings/groups/VoipGroupPage.tsx
  apps/meteor/tests/e2e/administration-settings.spec.ts
  apps/meteor/tests/e2e/administration.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32957 chore: `FilterByText` component sanitization
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/omnichannel/businessHours/BusinessHoursTable.tsx
  apps/meteor/client/omnichannel/monitors/MonitorsTable.tsx
  apps/meteor/client/omnichannel/slaPolicies/SlaTable.tsx
  apps/meteor/client/omnichannel/tags/TagsTable.tsx
  apps/meteor/client/omnichannel/units/UnitsTable.tsx
  apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx
  apps/meteor/client/views/admin/customSounds/CustomSoundsTable/CustomSoundsTable.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusTable/CustomUserStatusTable.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx
  apps/meteor/client/views/admin/integrations/IntegrationsTable.tsx
  apps/meteor/client/views/admin/moderation/helpers/ModerationFilter.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTableFilters.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTable.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTable.tsx
  apps/meteor/client/views/directory/tabs/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/marketplace/AppsPage/AppsFilters.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/TagList.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentsTable/DepartmentsTable.tsx
  apps/meteor/client/views/omnichannel/directory/calls/CallTable.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx
  apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
  apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerModal.tsx
Labels: stat: ready to merge, stat: QA assured

#32995 test: Mock `dns.lookup` on `checkUrlForSsrf` tests
  apps/meteor/tests/unit/app/lib/server/lib/checkUrlForSsrf.tests.ts
Labels: stat: ready to merge, stat: QA assured

#32967 test: Make Omnichannel jobs run every 3 secs on CI instead of 1 min
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoCloseOnHoldScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
Labels: stat: ready to merge, stat: QA assured

#32791 fix: Allow custom fields on messages to be updated even if `msg` prop is not updated (via API)
  .changeset/rude-dogs-burn.md
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/methods/updateMessage.ts
  apps/meteor/tests/end-to-end/api/chat.ts
Labels: stat: ready to merge, stat: QA assured

#32930 ci: Bump `@actions/download-artifact` and `@actions/upload-artifact`
  .github/actions/build-docker/action.yml
  .github/actions/meteor-build/action.yml
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA assured

#32983 chore: add updater on afterOmnichannelSaveMessage (markRoomResponded) hook
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/setPredictedVisitorAbandonmentTime.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: needs testing

#32925 refactor: custom-emoji functions out of meteor methods
  apps/meteor/app/api/server/v1/emoji-custom.ts
  apps/meteor/app/emoji-custom/server/lib/insertOrUpdateEmoji.ts
  apps/meteor/app/emoji-custom/server/lib/uploadEmojiCustom.ts
  apps/meteor/app/emoji-custom/server/methods/insertOrUpdateEmoji.ts
  apps/meteor/app/emoji-custom/server/methods/uploadEmojiCustom.ts
Labels: stat: ready to merge, stat: QA assured

#33018 chore(models): Filter update accumulator
  packages/model-typings/src/updater.ts
  packages/models/src/updater.spec.ts
  packages/models/src/updater.ts
Labels: stat: ready to merge, stat: QA assured

#33021 chore: create getNotResponseByRoomIdUpdateQuery method
  apps/meteor/app/livechat/server/hooks/markRoomNotResponded.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: needs testing

#32943 chore: Add `departmentName` to the return values of `:agentId/departments` endpoint
  apps/meteor/app/livechat/server/api/lib/agents.ts
  apps/meteor/server/models/raw/LivechatDepartmentAgents.ts
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  packages/core-typings/src/ILivechatDepartmentAgents.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#33026 chore: add roomUpdater on notifyUsersOnMessage
  apps/meteor/app/federation/server/endpoints/dispatch.js
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts
  apps/meteor/server/models/dummy/BaseDummy.ts
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/server/models/raw/Rooms.ts
  packages/model-typings/src/models/IBaseModel.ts
  packages/model-typings/src/models/IRoomsModel.ts
Labels: stat: ready to merge, stat: QA assured

#32916 feat(audit): New endpoint for listing members of any room
  .changeset/funny-boats-guess.md
  apps/meteor/client/views/audit/components/AuditFiltersDisplay.tsx
  apps/meteor/client/views/audit/components/AuditLogEntry.tsx
  apps/meteor/ee/server/api/audit.ts
  apps/meteor/ee/server/lib/audit/startup.ts
  apps/meteor/ee/server/startup/audit.ts
  apps/meteor/tests/end-to-end/api/audit.ts
  packages/core-typings/src/ee/IAuditLog.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33032 ci: regression `actions/upload-artifact@v4` meteor build production
  .github/actions/meteor-build/action.yml
Labels: stat: QA assured

#33000 fix(ui-kit): Missing a peer dependency
  .changeset/calm-tigers-peel.md
  packages/ui-kit/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33030 refactor: Cover implicit `any` types
  packages/fuselage-ui-kit/src/blocks/InputBlock.tsx
  packages/fuselage-ui-kit/src/elements/ChannelsSelectElement/ChannelsSelectElement.tsx
  packages/fuselage-ui-kit/src/elements/ChannelsSelectElement/MultiChannelsSelectElement.tsx
  packages/fuselage-ui-kit/src/elements/MultiStaticSelectElement.tsx
  packages/fuselage-ui-kit/src/elements/StaticSelectElement.tsx
  packages/fuselage-ui-kit/src/elements/UsersSelectElement/MultiUsersSelectElement.tsx
  packages/fuselage-ui-kit/src/elements/UsersSelectElement/UsersSelectElement.tsx
  packages/fuselage-ui-kit/src/surfaces/createSurfaceRenderer.tsx
  packages/gazzodown/src/elements/Timestamp/ErrorBoundary.tsx
  packages/ui-client/src/components/CustomFieldsForm.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomList.tsx
  packages/uikit-playground/src/Components/FlowContainer/FlowContainer.tsx
  packages/uikit-playground/src/Components/SurfaceSelect/SurfaceSelect.tsx
  packages/web-ui-registration/src/components/LoginSwitchLanguageFooter.tsx
Labels: stat: ready to merge, stat: QA assured

#33029 fix(i18n): fixes onboarding.component.emailCodeFallback translation
  .changeset/proud-years-buy.md
  packages/i18n/src/locales/de.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32852 fix: disable deletion for federated users
  .changeset/empty-toys-smell.md
  apps/meteor/app/lib/server/functions/deleteUser.ts
Labels: stat: ready to merge, stat: QA assured

#33044 feat: Replaces outdated retention policy warning in favor of `Bubble`
  .changeset/large-geese-ring.md
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/client/views/room/body/RetentionPolicyWarning.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/RoomBodyV2.tsx
Labels: stat: ready to merge, stat: QA assured

#33056 chore: turbo env-mode: loose for dev
  package.json
Labels: stat: ready to merge, stat: QA assured

#30927 i18n: more Hindi translation keys added
  packages/i18n/src/locales/hi-IN.i18n.json
Labels: communityPR, stat: QA assured

#32915 chore(client): Remove Meteor.Error from `slashCommand`
  apps/meteor/app/slackbridge/client/slackbridge_import.client.js
  apps/meteor/app/slashcommand-asciiarts/client/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/client/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/client/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/client/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/client/unflip.ts
  apps/meteor/app/slashcommand-asciiarts/server/gimme.ts
  apps/meteor/app/slashcommand-asciiarts/server/lenny.ts
  apps/meteor/app/slashcommand-asciiarts/server/shrug.ts
  apps/meteor/app/slashcommand-asciiarts/server/tableflip.ts
  apps/meteor/app/slashcommand-asciiarts/server/unflip.ts
  apps/meteor/app/slashcommands-archiveroom/client/client.ts
  apps/meteor/app/slashcommands-archiveroom/server/server.ts
  apps/meteor/app/slashcommands-create/client/client.ts
  apps/meteor/app/slashcommands-create/server/server.ts
  apps/meteor/app/slashcommands-help/server/server.ts
  apps/meteor/app/slashcommands-hide/client/hide.ts
  apps/meteor/app/slashcommands-invite/client/client.ts
  apps/meteor/app/slashcommands-invite/server/server.ts
  apps/meteor/app/slashcommands-inviteall/client/client.ts
  apps/meteor/app/slashcommands-inviteall/server/server.ts
  apps/meteor/app/slashcommands-join/client/client.ts
  apps/meteor/app/slashcommands-join/server/server.ts
  apps/meteor/app/slashcommands-kick/client/client.ts
  apps/meteor/app/slashcommands-kick/server/server.ts
  apps/meteor/app/slashcommands-leave/server/leave.ts
  apps/meteor/app/slashcommands-me/server/me.ts
  apps/meteor/app/slashcommands-msg/server/server.ts
  apps/meteor/app/slashcommands-mute/server/mute.ts
  apps/meteor/app/slashcommands-mute/server/unmute.ts
  apps/meteor/app/slashcommands-open/client/client.ts
  apps/meteor/app/slashcommands-status/client/status.ts
  apps/meteor/app/slashcommands-status/server/status.ts
  apps/meteor/app/slashcommands-topic/client/topic.ts
  apps/meteor/app/slashcommands-topic/server/topic.ts
  apps/meteor/app/slashcommands-unarchiveroom/client/client.ts
  apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
  apps/meteor/app/utils/client/index.ts
  apps/meteor/app/utils/client/slashCommand.ts
  apps/meteor/app/utils/server/slashCommand.ts
  apps/meteor/client/hooks/useAppSlashCommands.ts
  apps/meteor/client/lib/errors/InvalidCommandUsage.ts
  apps/meteor/client/lib/errors/InvalidPreview.ts
  apps/meteor/client/lib/errors/index.ts
  apps/meteor/client/startup/slashCommands/federation.ts
  apps/meteor/client/views/room/composer/hooks/useComposerBoxPopupQueries.ts
Labels: stat: ready to merge, stat: QA assured

#33034 chore: promote roomUpdater to afterSaveMessage hook
  apps/meteor/app/autotranslate/server/autotranslate.ts
  apps/meteor/app/discussion/server/hooks/propagateDiscussionMetadata.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/federation/server/hooks/afterSaveMessage.js
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/lib/afterSaveMessage.ts
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.ts
  apps/meteor/app/lib/server/startup/mentionUserNotInChannel.ts
  apps/meteor/app/livechat/server/hooks/afterSaveOmnichannelMessage.ts
  apps/meteor/app/threads/server/hooks/aftersavemessage.ts
  apps/meteor/client/hooks/useAnalyticsEventTracking.ts
  apps/meteor/ee/app/message-read-receipt/server/hooks/afterSaveMessage.ts
  apps/meteor/ee/server/lib/engagementDashboard/messages.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/tests/unit/server/federation/infrastructure/rocket-chat/hooks/hooks.spec.ts
Labels: stat: needs testing

#32940 fix: File uploads should only be allowed for room members
  .changeset/gorgeous-hotels-attend.md
  apps/meteor/client/views/room/body/hooks/useFileUploadDropTarget.ts
  apps/meteor/tests/e2e/file-upload.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33042 chore!: removes view-history permission
  .changeset/lovely-trees-call.md
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v305.ts
  packages/i18n/src/locales/af.i18n.json
  packages/i18n/src/locales/ar.i18n.json
  packages/i18n/src/locales/az.i18n.json
  packages/i18n/src/locales/be-BY.i18n.json
  packages/i18n/src/locales/bg.i18n.json
  packages/i18n/src/locales/bs.i18n.json
  packages/i18n/src/locales/ca.i18n.json
  packages/i18n/src/locales/cs.i18n.json
  packages/i18n/src/locales/cy.i18n.json
  packages/i18n/src/locales/da.i18n.json
  packages/i18n/src/locales/de-AT.i18n.json
  packages/i18n/src/locales/de-IN.i18n.json
  packages/i18n/src/locales/de.i18n.json
  packages/i18n/src/locales/el.i18n.json
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/eo.i18n.json
  packages/i18n/src/locales/es.i18n.json
  packages/i18n/src/locales/fa.i18n.json
  packages/i18n/src/locales/fi.i18n.json
  packages/i18n/src/locales/fr.i18n.json
  packages/i18n/src/locales/hr.i18n.json
  packages/i18n/src/locales/hu.i18n.json
  packages/i18n/src/locales/id.i18n.json
  packages/i18n/src/locales/it.i18n.json
  packages/i18n/src/locales/ja.i18n.json
  packages/i18n/src/locales/ka-GE.i18n.json
  packages/i18n/src/locales/km.i18n.json
  packages/i18n/src/locales/ko.i18n.json
  packages/i18n/src/locales/ku.i18n.json
  packages/i18n/src/locales/lo.i18n.json
  packages/i18n/src/locales/lt.i18n.json
  packages/i18n/src/locales/lv.i18n.json
  packages/i18n/src/locales/mn.i18n.json
  packages/i18n/src/locales/ms-MY.i18n.json
  packages/i18n/src/locales/nl.i18n.json
  packages/i18n/src/locales/no.i18n.json
  packages/i18n/src/locales/pl.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/i18n/src/locales/pt.i18n.json
  packages/i18n/src/locales/ro.i18n.json
  packages/i18n/src/locales/ru.i18n.json
  packages/i18n/src/locales/sk-SK.i18n.json
  packages/i18n/src/locales/sl-SI.i18n.json
  packages/i18n/src/locales/sq.i18n.json
  packages/i18n/src/locales/sr.i18n.json
  packages/i18n/src/locales/sv.i18n.json
  packages/i18n/src/locales/ta-IN.i18n.json
  packages/i18n/src/locales/th-TH.i18n.json
  packages/i18n/src/locales/tr.i18n.json
  packages/i18n/src/locales/uk.i18n.json
  packages/i18n/src/locales/vi-VN.i18n.json
  packages/i18n/src/locales/zh-HK.i18n.json
  packages/i18n/src/locales/zh-TW.i18n.json
  packages/i18n/src/locales/zh.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32921 chore!: Remove unused `omnichannelExternalFrameGenerateKey`
  apps/meteor/app/livechat/client/externalFrame/generateNewKey.ts
  apps/meteor/app/livechat/client/externalFrame/index.ts
  apps/meteor/app/livechat/client/index.ts
  apps/meteor/app/livechat/server/externalFrame/generateNewKey.ts
  apps/meteor/app/livechat/server/externalFrame/index.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/server/settings/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#33033 fix: Missing department names on OC edit agent view
  .changeset/fast-lobsters-turn.md
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
Labels: stat: ready to merge, stat: QA assured

#33062 fix: imported fixes
  .changeset/perfect-dancers-grab.md
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/livechat/imports/server/rest/sms.ts
  apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx
  apps/meteor/ee/server/lib/audit/methods.ts
  apps/meteor/server/lib/ldap/Manager.ts
  apps/meteor/server/methods/reportMessage.ts
  apps/meteor/server/methods/sendConfirmationEmail.ts
  apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts
  apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts
  apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts
  apps/meteor/server/settings/message.ts
  apps/meteor/tests/end-to-end/api/methods.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  apps/meteor/tests/end-to-end/api/users.ts
  apps/meteor/tests/unit/server/services/omnichannel-integrations/providers/twilio.spec.ts
  packages/core-typings/package.json
  packages/core-typings/src/omnichannel/sms.ts
  packages/rest-typings/src/v1/rooms.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33035 chore: change 'Accounts_AvatarBlockUnauthenticatedAccess' default value from false to true
  apps/meteor/server/routes/avatar/middlewares/auth.js
  apps/meteor/server/settings/accounts.ts
Labels: stat: ready to merge, stat: QA assured

#33023 fix: Realtime Monitoring LineCharts not updating
  apps/meteor/client/views/omnichannel/realTimeMonitoring/RealTimeMonitoringPage.js
Labels: stat: ready to merge, stat: QA assured

#33058 fix: Avoid `processRoomAbandonment` callback from erroring when Business Hours config is missing for day
  .changeset/gentle-bugs-think.md
  apps/meteor/app/livechat/server/hooks/processRoomAbandonment.ts
Labels: stat: ready to merge, stat: QA assured

#32087 refactor(Livechat): transcript.js to TS
  packages/livechat/src/lib/transcript.ts
  packages/livechat/src/store/index.tsx
Labels: stat: ready to merge, stat: QA assured

#32648 chore!: remove deprecated meteor eraseRoom method
  .changeset/chilled-boats-sip.md
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/api/server/v1/teams.ts
  apps/meteor/server/lib/eraseRoom.ts
  apps/meteor/server/methods/index.ts
Labels: stat: ready to merge, stat: QA assured

#32533 chore!: Remove `meteor/check` from `cloud` endpoints
  apps/meteor/app/api/server/v1/cloud.ts
  apps/meteor/tests/end-to-end/api/cloud.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/cloud.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#32488 chore!: removed checkUsernameAvailability method
  apps/meteor/app/lib/server/index.ts
  apps/meteor/app/lib/server/methods/checkUsernameAvailability.ts
Labels: stat: ready to merge, stat: QA assured

#33028 fix: Missing retention's `ignoreThreads` param for old channels
  .changeset/gold-knives-sparkle.md
  apps/meteor/server/startup/migrations/index.ts
  apps/meteor/server/startup/migrations/v306.ts
Labels: stat: QA assured

#32532 chore!: Remove `meteor/check` from `chat` endpoints
  .changeset/tiny-rice-train.md
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/client/lib/lists/ThreadsList.ts
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
  apps/meteor/tests/end-to-end/api/chat.ts
  packages/rest-typings/src/v1/chat.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#32842 refactor: move system message calls from sendMessage to saveSystemMessage
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts
  apps/meteor/app/livechat/server/api/v1/pageVisited.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/server/services/messages/service.ts
  packages/core-services/src/types/IMessageService.ts
Labels: stat: needs testing

#33053 chore: apps-engine message converter cache by any obj
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/apps/server/converters/messages.js
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
Labels: stat: ready to merge, stat: QA assured

#33047 fix: customFields ignored in livechat room creation
  .changeset/twelve-windows-train.md
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewRoom.ts
  apps/meteor/lib/utils/isPlainObject.ts
  apps/meteor/tests/unit/server/livechat/hooks/beforeNewRoom.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32809 fix: deactivate federated internal users permanently with the external user
  .changeset/new-mayflies-wait.md
  apps/meteor/app/lib/server/functions/setUserActiveStatus.ts
  apps/meteor/ee/server/local-services/federation/service.ts
  apps/meteor/server/services/federation/domain/IFederationBridge.ts
  apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
  apps/meteor/server/services/federation/service.ts
  packages/core-services/src/types/IFederationService.ts
Labels: stat: ready to merge, stat: QA assured

#32981 fix: Following/unfollowing a message when the thread is closed does not update the UI
  .changeset/ten-bulldogs-clap.md
  apps/meteor/app/lib/server/lib/notifyListener.ts
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/tests/e2e/message-actions.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33091 test(Omnichannel): Fix department flaky test
  apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
Labels: stat: QA assured

#33036 fix: `processRoomAbandonment` callback not processing data correctly
  .changeset/spicy-kings-think.md
  apps/meteor/app/livechat/server/hooks/processRoomAbandonment.ts
  apps/meteor/tests/unit/app/livechat/server/hooks/processRoomAbandonment.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32897 chore: move ddp-client and api-client packages out of ee folder
  packages/api-client/.eslintrc.json
  packages/api-client/CHANGELOG.md
  packages/api-client/LICENSE
  packages/api-client/__tests__/2fahandling.spec.ts
  packages/api-client/jest.config.ts
  packages/api-client/package.json
  packages/api-client/src/Credentials.ts
  packages/api-client/src/RestClientInterface.ts
  packages/api-client/src/errors.ts
  packages/api-client/src/index.ts
  packages/api-client/tsconfig.json
  packages/ddp-client/.eslintrc.json
  packages/ddp-client/CHANGELOG.md
  packages/ddp-client/LICENSE
  packages/ddp-client/README.md
  packages/ddp-client/__examples__/simple.ts
  packages/ddp-client/__mocks__/ws.ts
  packages/ddp-client/__tests__/Account.spec.ts
  packages/ddp-client/__tests__/ClientStream.spec.ts
  packages/ddp-client/__tests__/Connection.spec.ts
  packages/ddp-client/__tests__/DDPDispatcher.spec.ts
  packages/ddp-client/__tests__/DDPSDK.spec.ts
  packages/ddp-client/__tests__/MinimalDDPClient.spec.ts
  packages/ddp-client/__tests__/Timeout.spec.ts
  packages/ddp-client/__tests__/helpers/index.ts
  packages/ddp-client/__tests__/wrapOnceEventIntoPromise.spec.ts
  packages/ddp-client/jest.config.ts
  packages/ddp-client/package.json
  packages/ddp-client/src/ClientStream.ts
  packages/ddp-client/src/Connection.ts
  packages/ddp-client/src/DDPDispatcher.ts
  packages/ddp-client/src/DDPSDK.ts
  packages/ddp-client/src/MinimalDDPClient.ts
  packages/ddp-client/src/TimeoutControl.ts
  packages/ddp-client/src/index.ts
  packages/ddp-client/src/legacy/RocketchatSDKLegacy.ts
  packages/ddp-client/src/legacy/types/SDKLegacy.ts
  packages/ddp-client/src/livechat/LivechatClientImpl.ts
  packages/ddp-client/src/livechat/types/LivechatSDK.ts
  packages/ddp-client/src/types/Account.ts
  packages/ddp-client/src/types/ClientStream.ts
  packages/ddp-client/src/types/DDPClient.ts
  packages/ddp-client/src/types/IncomingPayload.ts
  packages/ddp-client/src/types/OutgoingPayload.ts
  packages/ddp-client/src/types/RemoveListener.ts
  packages/ddp-client/src/types/SDK.ts
  packages/ddp-client/src/types/Subscription.ts
  packages/ddp-client/src/types/connectionPayloads.ts
  packages/ddp-client/src/types/heartbeatsPayloads.ts
  packages/ddp-client/src/types/methods.ts
  packages/ddp-client/src/types/methodsPayloads.ts
  packages/ddp-client/src/types/publicationPayloads.ts
  packages/ddp-client/src/types/streams.ts
  packages/ddp-client/src/wrapOnceEventIntoPromise.ts
  packages/ddp-client/tsconfig.json
  yarn.lock
Labels: stat: QA assured

#33117 ci: yarn login
  .github/actions/build-docker/action.yml
  .github/actions/meteor-build/action.yml
  .github/actions/setup-node/action.yml
  .github/workflows/ci-code-check.yml
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci-test-unit.yml
  .github/workflows/ci.yml
  .github/workflows/new-release.yml
  .github/workflows/pr-update-description.yml
  .github/workflows/publish-release.yml
Labels: stat: ready to merge, stat: QA assured

#33076 refactor: `Realtime Monitoring/Chart` component to TS
  apps/meteor/client/views/omnichannel/analytics/InterchangeableChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/AgentStatusChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/Chart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/Chart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatDurationChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsPerAgentChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsPerDepartmentChart.js
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ResponseTimesChart.js
Labels: stat: ready to merge, stat: QA assured

#32824 feat: proxy avatars for Accounts_AvatarExternalProviderUrl
  apps/meteor/client/providers/AvatarUrlProvider.tsx
  apps/meteor/server/routes/avatar/user.js
  packages/i18n/src/locales/de.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32709 feat: Added Creation Date col in Rooms Table in Admin Panel
  .changeset/rooms-table-ts.md
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/admin/rooms/EditRoomWithData.tsx
  apps/meteor/client/views/admin/rooms/RoomRow.tsx
  apps/meteor/client/views/admin/rooms/RoomsTable.tsx
  apps/meteor/lib/rooms/adminFields.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  packages/core-typings/src/IRoom.ts
Labels: stat: ready to merge, stat: QA assured

#32574 fix: Inconsistent Markdown Formatting in Custom Status Field
  .changeset/kind-drinks-joke.md
  apps/meteor/client/components/MarkdownText.tsx
Labels: stat: ready to merge, stat: QA tested, stat: QA assured

#32535 feat: verify federation configuration before processing any events
  .changeset/bright-humans-cross.md
  .changeset/six-beers-fry.md
  .gitignore
  apps/meteor/app/api/server/v1/federation.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomName.ts
  apps/meteor/app/channel-settings/server/functions/saveRoomTopic.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/lib/server/index.ts
  apps/meteor/app/lib/server/methods/checkFederationConfiguration.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/ee/server/local-services/federation/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/ee/server/local-services/federation/service.ts
  apps/meteor/ee/tests/unit/server/federation/server/infrastructure/rocket-chat/hooks/hooks.spec.ts
  apps/meteor/server/methods/addRoomModerator.ts
  apps/meteor/server/methods/addRoomOwner.ts
  apps/meteor/server/methods/removeUserFromRoom.ts
  apps/meteor/server/services/federation/domain/IFederationBridge.ts
  apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Settings.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/logger.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/hooks/index.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/well-known.ts
  apps/meteor/server/services/federation/service.ts
  apps/meteor/server/services/federation/utils.ts
  apps/meteor/server/services/messages/hooks/BeforeFederationActions.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/server/services/room/hooks/BeforeFederationActions.ts
  apps/meteor/server/services/room/service.ts
  apps/meteor/tests/end-to-end/api/federation.ts
  apps/meteor/tests/unit/server/federation/infrastructure/rocket-chat/hooks/hooks.spec.ts
  apps/meteor/tests/unit/server/federation/utils.spec.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeFederationActions.tests.ts
  apps/meteor/tests/unit/server/services/room/hooks/FederationActions.tests.ts
  packages/core-services/src/index.ts
  packages/core-services/src/types/IFederationService.ts
  packages/core-services/src/types/IMessageService.ts
  packages/core-services/src/types/IRoomService.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33001 feat: Allow apps to react/unreact to messages
  .changeset/nasty-windows-smile.md
  apps/meteor/app/apps/server/bridges/messages.ts
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33120 chore: allow using db watchers in localhost
  packages/core-services/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#33040 fix: Forget session on window close
  .changeset/two-bikes-crash.md
  apps/meteor/client/startup/accounts.ts
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/tests/e2e/account-forgetSessionOnWindowClose.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33121 chore: Remove `googleapis` package from codebase
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33109 fix: `ContextualbarHeader` expanded prop
  .changeset/rich-pillows-hang.md
  apps/meteor/client/components/Contextualbar/ContextualbarHeader.tsx
Labels: stat: ready to merge, stat: QA assured

#32743 fix: validate username before registering user
  .changeset/purple-dolls-serve.md
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/lib/server/functions/setUsername.ts
  apps/meteor/app/lib/server/functions/validateUsername.ts
  apps/meteor/tests/end-to-end/api/users.ts
  apps/meteor/tests/unit/app/lib/server/functions/validateUsername.spec.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/web-ui-registration/src/RegisterForm.tsx
Labels: stat: ready to merge, stat: QA assured

#33119 chore: bump rocketchat-icons
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-kit/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32846 fix: System messages are counted as agents' first responses in livechat rooms
  .changeset/rotten-camels-pretend.md
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/app/livechat/server/lib/AnalyticsTyped.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  packages/core-typings/src/IMessage/IMessage.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#32986 fix: Users without the "Manage OAuth Apps" permission can't log in with third-party apps
  .changeset/cool-rocks-remember.md
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/server/models/raw/OAuthApps.ts
  apps/meteor/tests/end-to-end/api/oauthapps.ts
  packages/model-typings/src/models/IOAuthAppsModel.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#32041 feat: New users page contextual bar user form
  apps/meteor/client/components/UserCard/UserCardInfo.tsx
  apps/meteor/client/views/admin/rooms/RoomsTableFilters.tsx
  apps/meteor/client/views/admin/users/AdminUserCreated.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/admin/users/AdminUserFormWithData.tsx
  apps/meteor/client/views/admin/users/AdminUserSetRandomPasswordContent.tsx
  apps/meteor/client/views/admin/users/AdminUserSetRandomPasswordRadios.tsx
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/client/views/admin/users/PasswordFieldSkeleton.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTableFilters.tsx
  apps/meteor/client/views/marketplace/components/CategoryFilter/CategoryDropDownList.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/admin-flextab-users.ts
  packages/core-typings/src/IUser.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/v1/users/UserCreateParamsPOST.ts
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomAnchor.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomList.tsx
  packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomListWrapper.tsx
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifier.tsx
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifierItem.tsx
Labels: stat: ready to merge, stat: QA assured

#33048 feat: add closedBy on apps-engine
  apps/meteor/app/apps/server/converters/rooms.js
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32896 chore: Update Omnichannel's room closing mechanism to use transactions.
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/utils/server/functions/getMongoInfo.ts
  apps/meteor/definition/externals/meteor/mongo.d.ts
  apps/meteor/server/database/utils.ts
  apps/meteor/server/models/raw/BaseRaw.ts
  apps/meteor/server/models/raw/LivechatInquiry.ts
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/server/models/raw/Rooms.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/server/models/raw/Users.js
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/model-typings/src/models/IRoomsModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA assured

#33054 fix: Livechat analytics in a given date range consider conversation data from the following day
  .changeset/strong-terms-love.md
  apps/meteor/server/models/raw/LivechatRooms.ts
  apps/meteor/server/services/omnichannel-analytics/AgentData.ts
  apps/meteor/server/services/omnichannel-analytics/ChartData.ts
  apps/meteor/server/services/omnichannel-analytics/OverviewData.ts
  apps/meteor/server/services/omnichannel-analytics/service.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/unit/server/services/omnichannel-analytics/OverviewData.tests.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
Labels: stat: ready to merge, squad: core, stat: QA assured

#24889 fix: Announcement modal horizontal scrollbar
  .changeset/giant-spiders-pay.md
  apps/meteor/client/views/room/Announcement/Announcement.tsx
Labels: stat: ready to merge, communityPR, stat: QA assured

#33127 Revert "fix: Inconsistent Markdown Formatting in Custom Status Field"
  .changeset/kind-drinks-joke.md
  apps/meteor/client/components/MarkdownText.tsx
Labels: stat: ready to merge, stat: QA assured

#33110 refactor: Replace proxy functions from `LivechatTyped` class with direct calls
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/api/v1/agent.ts
  apps/meteor/app/livechat/server/api/v1/config.ts
  apps/meteor/app/livechat/server/api/v1/transcript.ts
  apps/meteor/app/livechat/server/hooks/saveContactLastChat.ts
  apps/meteor/app/livechat/server/hooks/sendEmailTranscriptOnClose.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/methods/getNextAgent.ts
  apps/meteor/app/livechat/server/methods/sendTranscript.ts
  apps/meteor/server/models/raw/LivechatVisitors.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
Labels: stat: ready to merge, stat: QA assured

#33003 feat: Setting for enabling files encryption and fix whitelist media types stopping E2EE uploads
  .changeset/stupid-fishes-relate.md
  .changeset/violet-radios-begin.md
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
  apps/meteor/server/settings/e2e.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  apps/meteor/tests/mocks/files/diagram.drawio
  packages/core-typings/src/IUpload.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#31525 fix: show only relevant userInfoActions for mentioned non-members
  .changeset/ninety-hounds-exist.md
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/client/views/hooks/useMemberExists.ts
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersActions.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoActions.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useAddUserAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/useUserInfoActions.ts
  apps/meteor/client/views/room/lib/getRoomDirectives.ts
  apps/meteor/tests/e2e/user-card-info-actions-by-member.spec.ts
  apps/meteor/tests/e2e/user-card-info-actions-by-room-owner.spec.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#33039 chore: remove left streaming code
  apps/meteor/app/channel-settings/server/functions/saveStreamingOptions.ts
  apps/meteor/app/channel-settings/server/methods/saveRoomSettings.ts
  apps/meteor/app/models/client/models/CachedChatRoom.ts
  apps/meteor/app/models/client/models/CachedChatSubscription.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/client/hooks/roomActions/useStartCallRoomAction.ts
  apps/meteor/lib/publishFields.ts
  apps/meteor/server/models/raw/Rooms.ts
  packages/core-typings/src/IRoom.ts
  packages/core-typings/src/IStats.ts
  packages/model-typings/src/models/IRoomsModel.ts
  packages/ui-contexts/src/types/SubscriptionWithRoom.ts
Labels: stat: ready to merge, stat: QA assured

#32693 feat: create contact endpoint
  .changeset/sixty-spoons-own.md
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/lib/Contacts.ts
  apps/meteor/server/models/LivechatContacts.ts
  apps/meteor/server/models/raw/LivechatContacts.ts
  apps/meteor/server/models/startup.ts
  apps/meteor/tests/end-to-end/api/livechat/contacts.ts
  apps/meteor/tests/unit/app/livechat/server/lib/Contacts.spec.ts
  packages/core-typings/src/ILivechatContact.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/index.ts
  packages/model-typings/src/models/ILivechatContactsModel.ts
  packages/models/src/index.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#33136 fix: imported fixes
  .changeset/orange-clocks-wait.md
  apps/meteor/app/lib/server/functions/getModifiedHttpHeaders.ts
  apps/meteor/app/lib/server/lib/debug.js
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/tests/end-to-end/api/miscellaneous.ts
  apps/meteor/tests/unit/app/lib/server/functions/getModifiedHttpHeaders.tests.ts
Labels: stat: ready to merge, stat: QA assured

#33092 refactor: Realtime `Doughnout Charts` to TS
  apps/meteor/app/livechat/client/lib/chartHandler.ts
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/AgentStatusChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/useUpdateChartData.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA assured

#33137 chore: Revive Livechat Storybook
  packages/livechat/.storybook/main.ts
Labels: stat: ready to merge, stat: QA assured

#33133 regression: Handle live setting forget user session on window close update
  apps/meteor/client/startup/accounts.ts
Labels: stat: ready to merge, stat: QA assured

#33114 feat: add Advanced settings accordion to `EditRoomInfo`
  .changeset/stupid-pigs-share.md
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/retention-policy.spec.ts
  apps/meteor/tests/e2e/team-management.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33168 test: Add e2e tests for teams multi-step modals
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.tsx
  apps/meteor/client/views/teams/contextualBar/info/TeamsInfo.tsx
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-channels.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
  apps/meteor/tests/e2e/retention-policy.spec.ts
  apps/meteor/tests/e2e/team-management.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33118 refactor: Uses `source` instead of `room` to render the `OmnichannelRoomIcon`
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/OmnichannelAppSourceRoomIcon.tsx
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/OmnichannelCoreSourceRoomIcon.tsx
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/OmnichannelRoomIcon.tsx
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/lib/OmnichannelRoomIconManager.ts
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/provider/OmnichannelRoomIconProvider.tsx
  apps/meteor/client/components/RoomIcon/RoomIcon.tsx
  apps/meteor/client/views/omnichannel/directory/components/SourceField.tsx
  apps/meteor/client/views/room/Header/HeaderIconWithRoom.tsx
  apps/meteor/client/views/room/HeaderV2/HeaderIconWithRoom.tsx
  packages/core-typings/src/IRoom.ts
Labels: stat: ready to merge, stat: QA assured

#33166 refactor: Realtime Monitoring Counters to TS
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.stories.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterRow.tsx
Labels: stat: ready to merge, stat: QA assured

#33158 fix: Multi-step modals closing unexpectedly
  .changeset/wise-avocados-taste.md
  apps/meteor/client/components/GenericModal/GenericModal.tsx
  apps/meteor/client/components/GenericModal/GenericModalSkeleton.tsx
  apps/meteor/client/views/room/modals/ReadReceiptsModal/ReadReceiptsModal.tsx
  apps/meteor/client/views/teams/ConvertToChannelModal/ConvertToChannelModal.tsx
  apps/meteor/client/views/teams/contextualBar/info/DeleteTeam/DeleteTeamModalWithRooms.tsx
  apps/meteor/client/views/teams/contextualBar/info/LeaveTeam/LeaveTeamWithData.tsx
  apps/meteor/client/views/teams/contextualBar/members/RemoveUsersModal/RemoveUsersModal.js
  apps/meteor/tests/e2e/team-management.spec.ts
Labels: stat: ready to merge, stat: QA assured

#33169 regression: Encrypted file upload throws an error on mobile
  .changeset/smart-baboons-allow.md
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#33154 chore: remove notifyListener call that was causing startup issues
  apps/meteor/server/startup/cloudRegistration.ts
Labels: stat: ready to merge, stat: QA assured

#32891 test: Add unit test for RoomMenu options
  apps/meteor/client/sidebar/RoomMenu.spec.tsx
Labels: stat: ready to merge, stat: QA assured

#33174 fix: restore tooltips to units Multiselect
  .changeset/strong-rings-rush.md
  apps/meteor/client/omnichannel/units/UnitEdit.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-units.ts
  packages/ui-client/src/components/TooltipComponent.tsx
Labels: stat: ready to merge, stat: QA assured

#33182 refactor: Realtime Monitoring Counters to TS
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.stories.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.tsx
Labels: stat: ready to merge, stat: QA assured

#33186 regression: Retention policy warning not truncating text
  apps/meteor/client/views/room/body/RetentionPolicyWarning.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#33156 feat: add `sidepanelNavigation` to Feature preview list
  .changeset/brown-singers-appear.md
  apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.tsx
  packages/i18n/src/locales/en.i18n.json
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
Labels: stat: ready to merge, stat: QA assured
