Repository RocketChat/Rocket.Chat, pull requests merged in 2024-04, with the labels that each got.

#31926 chore: Remove references to EE code from the app events
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/methods/deleteUserOwnAccount.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/ee/server/apps/index.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/server/lib/moderation/reportMessage.ts
  apps/meteor/server/methods/deleteUser.ts
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/methods/logoutCleanUp.ts
  apps/meteor/server/methods/reportMessage.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/server/startup/migrations/v291.ts
  apps/meteor/server/startup/migrations/v292.ts
  apps/meteor/server/startup/migrations/v294.ts
  packages/apps/src/AppsEngine.ts
  packages/apps/src/IAppServerOrchestrator.ts
  packages/apps/src/bridges/IListenerBridge.ts
  packages/apps/src/index.ts
  packages/apps/src/orchestrator.ts
Labels: stat: ready to merge, stat: QA skipped

#32103 regression: DiscussionsList title missing style
  apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsList.tsx
Labels: stat: ready to merge, stat: QA tested

#31960 chore: Create/Edit room consistency
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/app/discussion/server/methods/createDiscussion.ts
  apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx
  apps/meteor/client/components/InfoPanel/InfoPanelActionGroup.tsx
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/client/sidebar/header/CreateDirectMessage.tsx
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomItems.tsx
  apps/meteor/client/sidebar/header/hooks/useEncryptedRoomDescription.tsx
  apps/meteor/client/views/hooks/roomActions/useDeleteRoom.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfo.tsx
  apps/meteor/client/views/teams/contextualBar/info/DeleteTeam/DeleteTeamConfirmation.tsx
  apps/meteor/client/views/teams/contextualBar/info/TeamsInfo.tsx
  apps/meteor/package.json
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/create-direct.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/home-discussion.ts
  apps/meteor/tests/e2e/page-objects/home-team.ts
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/v1/rooms.ts
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA tested

#32066 test: `InitialData.insertAdminUserFromEnv`
  apps/meteor/server/startup/initialData.js
  apps/meteor/tests/unit/server/startup/initialData.tests.ts
Labels: stat: ready to merge, stat: QA tested

#32090 chore: Move portals to the portals folder
  apps/meteor/client/components/ModalBackdrop.tsx
  apps/meteor/client/portals/ModalPortal.tsx
  apps/meteor/client/portals/TooltipPortal.tsx
  apps/meteor/client/providers/TooltipProvider.tsx
  apps/meteor/client/views/modal/ModalRegion.tsx
Labels: stat: ready to merge, stat: QA tested

#32116 test: allow csp for livechat tests
  apps/meteor/app/cors/server/cors.ts
  apps/meteor/packages/rocketchat-livechat/assets/demo.html
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-widget.spec.ts
Labels: stat: ready to merge, stat: QA tested

#32069 fix(livechat): registering guest multiple times cause message loss
  .changeset/nine-houses-reply.md
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  packages/livechat/src/lib/hooks.ts
Labels: stat: QA tested

#32094 test: contact center after hook calling wrong endpoint
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-center.spec.ts
Labels: stat: ready to merge, stat: QA tested

#32060 test(livechat): File upload settings
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-fileupload.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  packages/livechat/src/components/FilesDropTarget/index.tsx
Labels: stat: ready to merge, stat: QA assured

#32074 regression: multiSelect type settings not being saved by livechat/appearance endpoint
  apps/meteor/app/livechat/imports/server/rest/appearance.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-appearance.ts
  apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#32102 test(livechat): fix Department flaky test
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-department.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  packages/livechat/src/components/Modal/component.js
Labels: stat: ready to merge, stat: QA assured

#32063 fix: UI allowing to mark room as favorite despite room was not a `default` room
  .changeset/pink-ants-sing.md
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
Labels: stat: ready to merge, stat: QA assured

#32071 regression: missing message attributes for keyboard navigation
  apps/meteor/client/components/message/MessageContentBody.tsx
  apps/meteor/client/components/message/MessageHeader.tsx
  apps/meteor/client/components/message/content/DiscussionMetrics.tsx
  apps/meteor/client/components/message/content/Reactions.tsx
  apps/meteor/client/components/message/content/ThreadMetrics.tsx
  apps/meteor/client/components/message/content/reactions/Reaction.tsx
  apps/meteor/client/components/message/list/MessageListContext.tsx
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/SystemMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/views/room/MessageList/MessageListItem.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxFormattingToolbar/MessageBoxFormattingToolbar.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageItem.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useMessageListNavigation.ts
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/i18n/src/locales/en.i18n.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32121 test: fix `should edit name of targetChannel` flaky test
  apps/meteor/tests/e2e/channel-management.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32123 fix: search room not reactive after room name changes
  .changeset/sweet-books-trade.md
  apps/meteor/client/sidebar/search/SearchList.tsx
Labels: stat: ready to merge, stat: QA assured

#32134 chore: changes to SAML login in anticipation of meteor 3
  apps/meteor/client/views/root/SAMLLoginRoute.tsx
Labels: stat: ready to merge, stat: QA assured

#32135 fix: livechat room desync on different windows
  .changeset/wild-keys-obey.md
  packages/livechat/src/lib/room.js
Labels: stat: ready to merge, stat: QA assured

#32136 fix: Missing space between name and user name on system messages
  .changeset/smart-squids-begin.md
  apps/meteor/client/components/message/variants/SystemMessage.tsx
Labels: stat: ready to merge, stat: QA assured

#29461 feat: `Contextualbar` resizable
  .changeset/good-ghosts-doubt.md
  apps/meteor/client/components/Contextualbar/ContextualbarDialog.tsx
  apps/meteor/client/components/Contextualbar/ContextualbarResizable.tsx
  apps/meteor/client/views/omnichannel/directory/CallsContextualBarDirectory.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/package.json
  packages/i18n/src/locales/en.i18n.json
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32075 ci: fix services container not building in build step
  .github/actions/build-docker/action.yml
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA assured

#31976 feat: allowing forward to offline dep
  .changeset/strange-rivers-live.md
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/livechat/server/methods/saveDepartment.ts
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/tests/data/livechat/department.ts
  apps/meteor/tests/data/livechat/users.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  packages/core-typings/src/ILivechatDepartment.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32142 chore: move imported `Apps` to proxy
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createDirectRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/deleteMessage.ts
  apps/meteor/app/lib/server/functions/removeUserFromRoom.ts
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/methods/deleteUserOwnAccount.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/app/message-pin/server/pinMessage.ts
  apps/meteor/app/message-star/server/starMessage.ts
  apps/meteor/app/reactions/server/setReaction.ts
  apps/meteor/app/statistics/server/lib/getAppsStatistics.js
  apps/meteor/app/threads/server/methods/followMessage.ts
  apps/meteor/app/threads/server/methods/unfollowMessage.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/server/lib/moderation/reportMessage.ts
  apps/meteor/server/methods/deleteUser.ts
  apps/meteor/server/methods/eraseRoom.ts
  apps/meteor/server/methods/logoutCleanUp.ts
  apps/meteor/server/methods/reportMessage.ts
  apps/meteor/server/methods/saveUserProfile.ts
  apps/meteor/server/services/apps-engine/service.ts
  apps/meteor/server/services/video-conference/service.ts
  apps/meteor/server/startup/migrations/v291.ts
  apps/meteor/server/startup/migrations/v292.ts
  apps/meteor/server/startup/migrations/v294.ts
  packages/apps/src/orchestrator.ts
Labels: stat: ready to merge, stat: QA assured

#32105 regression(fuselage-ui-kit): Use default translation namespace for `-core` apps
  packages/fuselage-ui-kit/jest.config.ts
  packages/fuselage-ui-kit/package.json
  packages/fuselage-ui-kit/src/hooks/useAppTranslation.spec.tsx
  packages/fuselage-ui-kit/src/hooks/useAppTranslation.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32144 chore: Bump Apps-Engine version
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32150 chore: remove collections when db watcher is disabled
  apps/meteor/server/database/watchCollections.ts
Labels: stat: ready to merge, stat: QA assured

#32149 chore: remove unused onStartup function
  apps/meteor/server/lib/onStartup.ts
Labels: stat: ready to merge, stat: QA assured

#32062 fix: New messages export overwrites previous one from the same day when using Amazon S3
  .changeset/twelve-seas-battle.md
  apps/meteor/server/lib/dataExport/uploadZipFile.ts
  apps/meteor/tests/unit/server/lib/dataExport/uploadZipFile.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32145 chore(meteor/packages): apply code style
  apps/meteor/packages/autoupdate/autoupdate_client.js
  apps/meteor/packages/autoupdate/autoupdate_server.js
  apps/meteor/packages/autoupdate/client_versions.js
  apps/meteor/packages/autoupdate/package.js
  apps/meteor/packages/flow-router/client/_init.js
  apps/meteor/packages/flow-router/client/group.js
  apps/meteor/packages/flow-router/client/modules.js
  apps/meteor/packages/flow-router/client/route.js
  apps/meteor/packages/flow-router/client/router.js
  apps/meteor/packages/flow-router/client/triggers.js
  apps/meteor/packages/flow-router/lib/router.js
  apps/meteor/packages/flow-router/server/group.js
  apps/meteor/packages/flow-router/server/route.js
  apps/meteor/packages/flow-router/server/router.js
  apps/meteor/packages/linkedin-oauth/linkedin-server.js
  apps/meteor/packages/meteor-cookies/cookies.js
  apps/meteor/packages/meteor-cookies/package.js
  apps/meteor/packages/meteor-run-as-user/lib/collection.overwrites.js
  apps/meteor/packages/meteor-run-as-user/lib/common.js
  apps/meteor/packages/meteor-run-as-user/lib/pre.1.0.3.js
Labels: stat: ready to merge, stat: QA assured

#32158 test: Prevent playwright from unselecting options by mistake
  apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#32156 Revert "fix!: api login should not suggest which credential is wrong"
  .changeset/fuzzy-cherries-buy.md
  apps/meteor/app/lib/server/lib/loginErrorMessageOverride.js
  apps/meteor/app/lib/server/lib/loginErrorMessageOverride.ts
  apps/meteor/client/meteorOverrides/login/google.ts
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/tests/end-to-end/api/31-failed-login-attempts.ts
Labels: stat: ready to merge, stat: QA assured

#32159 fix!: api login should not suggest which credential is wrong
  .changeset/fuzzy-cherries-buy.md
  apps/meteor/app/lib/server/lib/loginErrorMessageOverride.js
  apps/meteor/app/lib/server/lib/loginErrorMessageOverride.ts
  apps/meteor/client/meteorOverrides/login/google.ts
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
  apps/meteor/tests/end-to-end/api/31-failed-login-attempts.ts
Labels: stat: ready to merge, stat: QA assured

#32048 chore: Fix some check/lint warnings
  apps/meteor/app/api/server/v1/settings.ts
  apps/meteor/app/apps/server/bridges/listeners.js
  apps/meteor/app/authorization/lib/AuthorizationUtils.ts
  apps/meteor/app/cors/server/cors.ts
  apps/meteor/app/lib/server/functions/getAvatarSuggestionForUser.ts
  packages/gazzodown/src/elements/Timestamp/ErrorBoundary.tsx
  packages/livechat/src/components/Composer/index.tsx
Labels: stat: ready to merge, stat: QA assured

#31990 fix(Omnichannel): Open expanded view (galery mode) for image attachments from livechat
  .changeset/green-ways-tie.md
  apps/meteor/app/livechat/server/methods/sendMessageLivechat.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/20-messages.ts
Labels: stat: ready to merge, stat: QA assured

#32141 chore: Deprecate `channels.images` in favor of `rooms.images`
  .changeset/slow-cows-dance.md
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/client/lib/lists/ImagesList.ts
  apps/meteor/client/views/room/ImageGallery/hooks/useImagesList.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/rest-typings/src/v1/channels/ChannelsImagesProps.ts
  packages/rest-typings/src/v1/channels/channels.ts
  packages/rest-typings/src/v1/channels/index.ts
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#31655 test: make chat api tests fully independent
  apps/meteor/tests/end-to-end/api/05-chat.js
Labels: stat: ready to merge, stat: QA assured

#31597 test: make api users tests fully independent
  apps/meteor/tests/data/rooms.helper.js
  apps/meteor/tests/data/users.helper.js
  apps/meteor/tests/end-to-end/api/01-users.js
Labels: stat: ready to merge, stat: QA assured

#32132 test: added e2e tests for Livechat's hide watermark setting
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-watermark.spec.ts
  apps/meteor/tests/e2e/page-objects/index.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-settings.ts
  packages/livechat/src/components/Footer/index.tsx
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#31969 fix: Don't streaming inquiries to client when routing algorithm is not manual selection
  .changeset/clever-guests-invent.md
  apps/meteor/server/modules/listeners/listeners.module.ts
Labels: stat: ready to merge, stat: QA assured

#32167 chore: bump fuselage packages
  apps/meteor/package.json
  ee/packages/pdf-worker/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32112 fix: Team mention triggering bot message for users not in room
  .changeset/lemon-schools-double.md
  apps/meteor/app/lib/server/startup/mentionUserNotInChannel.ts
  apps/meteor/tests/e2e/message-mentions.spec.ts
  apps/meteor/tests/e2e/utils/create-target-channel.ts
Labels: stat: ready to merge, stat: QA assured

#32007 fix: omnichannel department names overflowing
  .changeset/soft-shrimps-beg.md
  apps/meteor/client/components/AutoCompleteDepartment.tsx
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/analytics/AnalyticsPage.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/RealTimeMonitoringPage.js
  apps/meteor/ee/client/omnichannel/additionalForms/DepartmentForwarding.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx
  apps/meteor/ee/client/omnichannel/units/UnitEdit.tsx
  apps/meteor/tests/e2e/page-objects/omnichannel-transfer-chat-modal.ts
Labels: stat: ready to merge, stat: QA assured

#32185 test(Livechat): Fix RegisterGuest Flaky
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32181 test(Omnichannel): fix Livechat Appearance Flaky
  apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32104 test: forward messages with files
  apps/meteor/tests/e2e/fixtures/files/sample-audio.mp3
  apps/meteor/tests/e2e/fixtures/files/test_pdf_file.pdf
  apps/meteor/tests/e2e/fixtures/files/test_video.mp4
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA assured

#32188 test(e2e): prevent same api context for multiple suites
  apps/meteor/tests/e2e/utils/test.ts
Labels: stat: ready to merge, stat: QA assured

#32162 chore!: Removed Mongo 4.4. support and added 7.0
  .changeset/fair-seahorses-laugh.md
  .changeset/fluffy-knives-count.md
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
  apps/meteor/server/startup/serverRunning.js
  docker-compose-local.yml
Labels: stat: ready to merge, stat: QA assured

#32173 feat: Add "Enable Users" option to "Sync User Active State" LDAP setting
  .changeset/swift-readers-speak.md
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/settings/ldap.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA assured

#31808 chore: move applyLicense function to the license package
  apps/meteor/app/cloud/server/functions/saveRegistrationData.ts
  apps/meteor/ee/app/license/server/startup.ts
  ee/packages/license/src/applyLicense.ts
  ee/packages/license/src/index.ts
  ee/packages/license/src/licenseImp.ts
Labels: stat: ready to merge, stat: QA assured

#32052 chore: remove references to EE code in the stats collector
  apps/meteor/app/statistics/server/lib/getEEStatistics.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  packages/core-typings/src/IStats.ts
Labels: stat: ready to merge, stat: QA assured

#32202 fix: fingerprint auto accepted still asks for admin confirmation
  .changeset/shaggy-yaks-train.md
  apps/meteor/server/settings/misc.ts
Labels: stat: ready to merge, stat: QA assured

#32140 chore: Add `eslint-plugin-jsx-a11y` plugin
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
  apps/meteor/client/components/message/IgnoredContent.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentImage.tsx
  apps/meteor/client/components/message/content/urlPreviews/UrlVideoPreview.tsx
  apps/meteor/client/hooks/usePreventPropagation.ts
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/views/admin/moderation/helpers/ModerationFilter.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/client/views/e2e/EnterE2EPasswordModal.tsx
  apps/meteor/client/views/marketplace/IframeModal.js
  apps/meteor/client/views/meet/CallPage.tsx
  apps/meteor/client/views/omnichannel/ExternalFrameContainer.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/composer/ComposerBoxPopupPreview.tsx
  apps/meteor/client/views/root/MainLayout/LoginPage.tsx
  apps/meteor/ee/client/apps/gameCenter/GameCenterContainer.tsx
  ee/packages/pdf-worker/src/templates/ChatTranscript/components/Files.spec.tsx
  packages/eslint-config/package.json
  packages/eslint-config/react.js
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32199 chore: remove getDefaultSubscriptionPref from Subscription Model
  apps/meteor/app/lib/server/functions/addUserToDefaultChannels.ts
  apps/meteor/app/lib/server/functions/addUserToRoom.ts
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/server/methods/addAllUserToRoom.ts
  apps/meteor/server/models/raw/Subscriptions.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
Labels: stat: ready to merge, stat: QA assured

#32172 fix: `MessageReactions` misalignment when zooming out
  .changeset/thin-peaches-own.md
  apps/meteor/client/components/message/content/Reactions.tsx
Labels: stat: ready to merge, stat: QA assured

#32163 test: Added e2e tests for Livechat's avatar visibility
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-avatar-visibility.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#32211 test(Omnichannel): fix flaky `OC - Manager Monitors - Search`
  apps/meteor/tests/e2e/omnichannel/omnichannel-monitors.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32214 test: Flaky "expect add "user1" as agent" test
  apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
Labels: stat: ready to merge, stat: QA assured

#32187 fix: Focus being forced on last message when interacting with mouse
  .changeset/eleven-seas-explain.md
  apps/meteor/client/views/room/hooks/useMessageListNavigation.ts
  apps/meteor/tests/e2e/messaging.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32218 regression: Add prop on `FilterByText` to call auto focus conditionally
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/views/admin/moderation/helpers/ModerationFilter.tsx
  apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
Labels: stat: ready to merge, stat: QA assured

#32171 test: added e2e tests Livechat widget custom logo
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-logo.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-settings.ts
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#32166 test: added e2e tests for Livechat's bubble background color
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-message-bubble-color.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts
  packages/livechat/src/components/Messages/MessageBubble/index.js
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#32220 fix: supported versions not being updated
  .changeset/sharp-yaks-turn.md
  apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
Labels: stat: ready to merge, stat: QA assured

#32138 test(Livechat): Cross tab communication
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-tab-communication.spec.ts
Labels: stat: ready to merge, stat: QA assured

#31899 chore: function patches
  apps/meteor/app/api/server/helpers/getInstanceList.ts
  apps/meteor/app/api/server/v1/instances.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/ee/server/patches/getInstanceList.ts
  apps/meteor/ee/server/patches/index.ts
  apps/meteor/package.json
  packages/patch-injection/.eslintrc.json
  packages/patch-injection/jest.config.ts
  packages/patch-injection/package.json
  packages/patch-injection/src/addPatch.ts
  packages/patch-injection/src/data.ts
  packages/patch-injection/src/definition.ts
  packages/patch-injection/src/getFunctionPatches.ts
  packages/patch-injection/src/index.ts
  packages/patch-injection/src/makeFunction.ts
  packages/patch-injection/tests/patches.test.ts
  packages/patch-injection/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#32157 fix: Custom OAuth roles are not correctly synced on user creation
  .changeset/small-moons-matter.md
  apps/meteor/ee/server/configuration/oauth.ts
Labels: stat: ready to merge, stat: QA assured

#31996 fix: security tab visibility
  .changeset/afraid-poets-sparkle.md
  apps/meteor/client/views/account/security/AccountSecurityPage.tsx
  apps/meteor/client/views/account/security/AccountSecurityRoute.tsx
  apps/meteor/client/views/account/sidebarItems.tsx
  apps/meteor/tests/e2e/access-security-page.spec.ts
  apps/meteor/tests/e2e/page-objects/account-profile.ts
  apps/meteor/tests/e2e/page-objects/fragments/account-sidenav.ts
Labels: stat: ready to merge, stat: QA assured

#32226 test: Flaky "expect add "user1" as monitor" test
  apps/meteor/client/components/FilterByText.tsx
  apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-manager-role.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-manager.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-manager.ts
Labels: stat: ready to merge, stat: QA assured

#32228 chore: better instant to call `getCachedSupportedVersionsToken.reset()`
  apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
Labels: stat: ready to merge, stat: QA assured

#32196 test: ignore user messages
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
Labels: stat: ready to merge, stat: QA assured

#32115 feat: Improve sidebar keyboard navigation
  .changeset/good-ducks-vanish.md
  apps/meteor/client/sidebar/RoomList/RoomList.tsx
  apps/meteor/client/sidebar/RoomList/RoomListRowWrapper.tsx
  apps/meteor/client/sidebar/RoomList/RoomListWrapper.tsx
  apps/meteor/client/sidebar/RoomList/useSidebarListNavigation.ts
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/sidebar/Sidebar.tsx
  apps/meteor/client/sidebar/SidebarRegion.tsx
  apps/meteor/client/sidebar/header/UserAvatarWithStatus.tsx
  apps/meteor/tests/e2e/create-channel.spec.ts
  apps/meteor/tests/e2e/federation/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/saml.spec.ts
  apps/meteor/tests/e2e/sidebar-administration-menu.spec.ts
  apps/meteor/tests/e2e/sidebar.spec.ts
Labels: :accessibility: accessibility, stat: ready to merge, stat: QA assured

#32168 test: added e2e tests for Livechat's background setting
  apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-background.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-appearance.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts
  packages/livechat/src/components/Messages/MessageList/index.js
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#32180 test: `channel-management` e2e tests improvements
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
Labels: stat: ready to merge, stat: QA assured

#32004 chore: remove references to EE code from livechat departments features
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/isDepartmentCreationAvailable.ts
  apps/meteor/app/livechat/server/methods/saveDepartment.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/server/patches/index.ts
  apps/meteor/ee/server/patches/isDepartmentCreationAvailable.ts
Labels: stat: ready to merge, stat: QA assured

#32006 chore: remove references to EE code from livechat business hour feature
  apps/meteor/app/livechat/server/business-hour/BusinessHourManager.ts
  apps/meteor/app/livechat/server/business-hour/closeBusinessHour.ts
  apps/meteor/app/livechat/server/business-hour/getAgentIdsForBusinessHour.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
  apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
  apps/meteor/ee/server/patches/closeBusinessHour.ts
  apps/meteor/ee/server/patches/index.ts
Labels: stat: ready to merge, stat: QA assured

#32073 fix: Surface elements (Modals, Contextual Bars) fail to respond when triggered by app submit events
  .changeset/young-candles-explode.md
  apps/meteor/app/ui-message/client/ActionManager.ts
  apps/meteor/client/views/banners/UiKitBanner.tsx
  apps/meteor/client/views/modal/uikit/UiKitModal.tsx
  apps/meteor/client/views/room/contextualBar/uikit/UiKitContextualBar.tsx
  apps/meteor/tests/e2e/app-modal-interaction.spec.ts
  packages/ui-contexts/src/ActionManagerContext.ts
Labels: stat: ready to merge, stat: QA assured

#32249 fix: Remove trailing semicolon on workspace version card
  apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
Labels: stat: ready to merge, stat: QA assured

#32170 fix: Language priority order not respected when changing server setting
  .changeset/proud-experts-taste.md
  apps/meteor/client/views/admin/settings/GroupPage.tsx
  apps/meteor/server/settings/general.ts
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/translations.spec.ts
  apps/meteor/tests/e2e/utils/setUserPreferences.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32129 chore: new stats for statsCollector
  apps/meteor/app/statistics/server/lib/getServicesStatistics.ts
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/client/views/admin/workspace/DeploymentCard/DeploymentCard.stories.tsx
  apps/meteor/client/views/admin/workspace/MessagesRoomsCard/MessagesRoomsCard.stories.tsx
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Statistics.ts
  packages/core-typings/src/IMatrixFederationStatistics.ts
  packages/core-typings/src/IStats.ts
  packages/core-typings/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#32047 feat(omnichannel): add daylight saving time support for business hours
  apps/meteor/app/livechat/server/business-hour/BusinessHourManager.ts
  apps/meteor/client/views/omnichannel/businessHours/BusinessHoursForm.tsx
  apps/meteor/tests/unit/app/livechat/server/business-hour/BusinessHourManager.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32230 fix: OTR messages not working when running microservices
  .changeset/strange-countries-visit.md
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/otr/server/methods/updateOTRAck.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  packages/core-services/src/events/Events.ts
Labels: stat: ready to merge, stat: QA assured

#32248 fix: Last threads list item doesn't display completely
  .changeset/heavy-singers-retire.md
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
Labels: stat: ready to merge, stat: QA assured

#32224 feat(messages): Allow Custom Fields in Messages
  .changeset/four-eyes-sniff.md
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/lib/server/functions/processWebhookMessage.ts
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/app/lib/server/functions/updateMessage.ts
  apps/meteor/app/lib/server/lib/validateCustomMessageFields.ts
  apps/meteor/app/lib/server/methods/updateMessage.ts
  apps/meteor/server/settings/message.ts
  apps/meteor/tests/end-to-end/api/05-chat.js
  apps/meteor/tests/unit/app/lib/server/lib/validateCustomMessageFields.tests.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/v1/chat.ts
Labels: stat: ready to merge, stat: QA assured

#32223 test: remove test.fail from livechat fileupload
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-fileupload.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32221 fix: Client check `AutoTranslate_Enabled` setting before a server endpoint call
  .changeset/strange-comics-camp.md
  apps/meteor/app/autotranslate/client/lib/autotranslate.ts
Labels: stat: ready to merge, stat: QA assured

#32084 feat: Add setting to automatically disable users missing from LDAP search
  .changeset/nervous-elephants-jam.md
  apps/meteor/app/importer/server/classes/ImportDataConverter.ts
  apps/meteor/ee/server/lib/ldap/Manager.ts
  apps/meteor/ee/server/settings/ldap.ts
  apps/meteor/server/models/raw/Users.js
  packages/i18n/src/locales/en.i18n.json
  packages/model-typings/src/models/IUsersModel.ts
Labels: stat: ready to merge, stat: QA assured

#31989 fix: Invite link doesn't work when logging in via SAML
  .changeset/eleven-news-stare.md
  apps/meteor/.meteorMocks/index.ts
  apps/meteor/app/meteor-accounts-saml/server/definition/IServiceProviderOptions.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/Utils.ts
  apps/meteor/client/views/root/SAMLLoginRoute.tsx
  apps/meteor/jest.config.ts
  apps/meteor/tests/e2e/saml.spec.ts
  apps/meteor/tests/mocks/client/RouterContextMock.tsx
  apps/meteor/tests/unit/client/views/root/SAMLLoginRoute.spec.tsx
Labels: stat: ready to merge, stat: QA assured

#32164 chore: Change `deprecationVersion` prop in favor of new `deprecation` prop
  apps/meteor/app/api/server/api.helpers.ts
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/livechat/imports/server/rest/inquiries.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/ee/server/api/licenses.ts
  apps/meteor/tests/unit/app/api/server/v1/lib/checkPermissions.spec.ts
  apps/meteor/tests/unit/app/api/server/v1/lib/checkPermissionsForInvocation.spec.ts
Labels: stat: ready to merge, stat: QA assured

#31840 feat: Encrypt file descriptions on E2EE rooms
  .changeset/great-moles-rest.md
  apps/meteor/app/e2e/client/rocketchat.e2e.room.js
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/client/components/message/content/Attachments.tsx
  apps/meteor/client/components/message/content/attachments/contexts/AttachmentEncryptionContext.tsx
  apps/meteor/client/components/message/content/attachments/file/AudioAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/GenericFileAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/ImageAttachment.tsx
  apps/meteor/client/components/message/content/attachments/file/VideoAttachment.tsx
  apps/meteor/client/components/message/content/attachments/structure/AttachmentDescription.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.tsx
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
  apps/meteor/client/lib/chats/uploads.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#32080 chore: add descriptions to s3 accesskey and secretkey settings
  apps/meteor/server/settings/file-upload.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#31898 feat: Create back-end for the new users panel page
  .changeset/fifty-cups-sort.md
  .changeset/pink-parrots-end.md
  apps/meteor/app/api/server/lib/users.ts
  apps/meteor/app/api/server/v1/misc.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/utils/server/functions/isSMTPConfigured.ts
  apps/meteor/client/views/admin/users/UsersTable/UsersTableRow.tsx
  apps/meteor/server/lib/sendWelcomeEmail.ts
  apps/meteor/tests/end-to-end/api/01-users.js
  packages/rest-typings/src/v1/users.ts
  packages/rest-typings/src/v1/users/UsersListStatusParamsGET.ts
  packages/rest-typings/src/v1/users/UsersSendWelcomeEmailParamsPOST.ts
Labels: stat: ready to merge, stat: QA assured

#32272 feat(message): Support Message Custom Fields on upload API
  .changeset/tough-boats-beg.md
  apps/meteor/app/file-upload/server/methods/sendFileMessage.ts
  apps/meteor/tests/end-to-end/api/05-chat.js
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#31965 feat(federation-v2): serve well-known paths from rocket.chat
  .changeset/old-geckos-march.md
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Settings.ts
  apps/meteor/server/services/federation/infrastructure/rocket-chat/well-known.ts
  apps/meteor/server/services/federation/service.ts
  apps/meteor/tests/end-to-end/api/33-federation.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge

#32237 fix: settings-related statistics not being updated according to license changes
  .changeset/popular-fishes-lay.md
  apps/meteor/app/statistics/server/lib/statistics.ts
  apps/meteor/server/lib/statistics/getSettingsStatistics.ts
Labels: stat: ready to merge, stat: QA assured

#32291 chore: Force logout live clients on E2EE keys reset changes
  apps/meteor/ee/server/api/sessions.ts
  apps/meteor/server/lib/resetUserE2EKey.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/saml.spec.ts
  ee/apps/ddp-streamer/src/Client.ts
  ee/apps/ddp-streamer/src/DDPStreamer.ts
  packages/core-services/src/events/Events.ts
Labels: stat: ready to merge, stat: QA assured

#32287 fix: Wrong Business hours validations between different weeks
  .changeset/flat-socks-act.md
  apps/meteor/app/livechat/server/business-hour/Helper.ts
  apps/meteor/app/livechat/server/business-hour/filterBusinessHoursThatMustBeOpened.spec.ts
  apps/meteor/app/livechat/server/business-hour/filterBusinessHoursThatMustBeOpened.ts
  apps/meteor/jest.config.ts
Labels: stat: ready to merge, stat: QA assured

#31811 chore: Deprecate mute/unmute meteor methods and convert to endpoint
  .changeset/fifty-planets-rhyme.md
  .changeset/lovely-trainers-kiss.md
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useMuteUserAction.tsx
  apps/meteor/server/methods/muteUserInRoom.ts
  apps/meteor/server/methods/unmuteUserInRoom.ts
  apps/meteor/tests/end-to-end/api/09-rooms.js
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#32208 feat: node-gcm deprecation
  .changeset/silent-dodos-doubt.md
  apps/meteor/app/push/server/fcm.ts
  apps/meteor/app/push/server/gcm.ts
  apps/meteor/app/push/server/push.ts
  apps/meteor/server/settings/push.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32267 chore: including x.com hostname to Twitter oembed
  apps/meteor/app/oembed/server/providers.ts
Labels: stat: ready to merge, stat: QA assured

#32139 chore: change cloud timeouts
  apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/legacySyncWorkspace.ts
Labels: stat: ready to merge, stat: QA assured

#30309 fix: `afterCreateUser` callback being called before setting user's roles
  .changeset/tame-ducks-turn.md
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/lib/server/functions/saveUser.js
  apps/meteor/lib/callbacks.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, squad: omnichannel, stat: QA assured

#32286 chore: Add alpine indication to test jobs that use it
  .github/workflows/ci-test-e2e.yml
Labels: stat: ready to merge, stat: QA assured

#32213 test: Unit tests for `AutoCloseOnHold` scheduler
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoCloseOnHoldScheduler.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/lib/AutoCloseOnHold.tests.ts
Labels: stat: ready to merge, stat: QA assured

#32306 Bump rocket.chat to 6.9
  apps/meteor/app/utils/rocketchat.info
  apps/meteor/package.json
  package.json
  packages/core-typings/package.json
  packages/rest-typings/package.json
Labels: stat: ready to merge, stat: QA assured

#32284 fix: Engagement Dashboard and Device Management admin pages loading indefinitely
  .changeset/yellow-lies-judge.md
  apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
  apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx
  apps/meteor/tests/e2e/administration.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32289 fix: Server sending 2 notifications when `@all/@here` were used by a user without permissions
  .changeset/flat-starfishes-crash.md
  apps/meteor/app/lib/server/methods/sendMessage.ts
  apps/meteor/server/services/messages/hooks/BeforeSavePreventMention.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/e2e/message-mentions.spec.ts
Labels: stat: ready to merge, stat: QA assured

#32182 fix: `UserDataFiles` store uploads not proxied through server because of missing setting
  .changeset/lazy-gorilas-shop.md
  apps/meteor/server/settings/file-upload.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#32327 fix: Video Conf call joined translation param
  .changeset/shiny-crabs-peel.md
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
Labels: stat: ready to merge, stat: QA assured

#31533 refactor(client): Rewrite `AppMenu` to TypeScript
  apps/meteor/client/components/WarningModal.spec.tsx
  apps/meteor/client/components/WarningModal.tsx
  apps/meteor/client/contexts/AppsContext.tsx
  apps/meteor/client/providers/AppsProvider.tsx
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
  apps/meteor/client/views/marketplace/AppMenu.spec.tsx
  apps/meteor/client/views/marketplace/AppMenu.tsx
  apps/meteor/client/views/marketplace/IframeModal.tsx
  apps/meteor/client/views/marketplace/components/UninstallGrandfatheredAppModal/UninstallGrandfatheredAppModal.tsx
  apps/meteor/client/views/marketplace/hooks/useAppInstallationHandler.tsx
  apps/meteor/client/views/marketplace/hooks/useAppMenu.tsx
  apps/meteor/client/views/marketplace/hooks/useAppsCountQuery.ts
  apps/meteor/client/views/marketplace/hooks/useAppsOrchestration.ts
  apps/meteor/client/views/marketplace/hooks/useMarketplaceActions.ts
  apps/meteor/client/views/marketplace/hooks/useOpenIncompatibleModal.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomHide.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomLeave.tsx
  apps/meteor/ee/client/apps/orchestrator.ts
  apps/meteor/tests/mocks/client/marketplace.tsx
  apps/meteor/tests/mocks/data.ts
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/rest-typings/src/apps/index.ts
Labels: stat: QA assured

#32340 regression: move conversation closing tags field after the toggle that enables it
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
Labels: stat: ready to merge, stat: QA assured
