Repository RocketChat/Rocket.Chat, pull requests merged in 2024-02, with the labels that each got.

#31592 regression: empty attachments leads to a Moderation Console GUI crash
  apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx
Labels: stat: ready to merge, stat: QA skipped

#31570 regression: Fix reactions tooltip
  apps/meteor/client/components/message/content/Reactions.tsx
  apps/meteor/client/components/message/content/reactions/Reaction.tsx
Labels: stat: ready to merge, stat: QA tested

#31603 regression: UiKitMessage refreshing room
  apps/meteor/client/components/message/uikit/UiKitMessageBlock.tsx
Labels: stat: needs QA

#31594 fix: missing slashcommand permissions
  .changeset/polite-donkeys-cheer.md
  apps/meteor/app/slashcommands-archiveroom/server/server.ts
  apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
  apps/meteor/tests/end-to-end/api/16-commands.js
Labels: stat: needs QA

#31602 regression: Moderation console translations
  apps/meteor/client/views/admin/moderation/ModerationConsoleTable.tsx
  apps/meteor/client/views/admin/moderation/UserReports/ModConsoleUsersTable.tsx
  apps/meteor/client/views/admin/moderation/hooks/useDeactivateUserAction.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Labels: stat: ready to merge, stat: QA tested

#31605 ci: add back carryforward flag
  codecov.yml
Labels: stat: needs QA

#31596 ci: Improve release changelog by adding the PR to items as well as the username of the contributor
  .changeset/config.json
  packages/release-changelog/.eslintrc.json
  packages/release-changelog/package.json
  packages/release-changelog/src/getGitHubInfo.ts
  packages/release-changelog/src/index.ts
  packages/release-changelog/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31581 test: make autotranslate api tests fully independent
  apps/meteor/tests/end-to-end/api/00-autotranslate.js
Labels: type: improvement, stat: ready to merge, stat: QA skipped

#31554 fix: Favoriting room through rooms page
  .changeset/serious-cows-compete.md
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31585 test: make misc api tests fully independent
  apps/meteor/tests/data/teams.helper.ts
  apps/meteor/tests/end-to-end/api/00-miscellaneous.js
Labels: stat: ready to merge, stat: QA skipped

#31620 regression: Opening WrapUpCallModal crashes the GUI
  apps/meteor/ee/client/voip/components/modals/WrapUpCallModal.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31609 regression: report page's agents section not taking the full width
  apps/meteor/ee/client/omnichannel/reports/ReportsPage.tsx
  apps/meteor/ee/client/omnichannel/reports/sections/AgentsSection.tsx
Labels: stat: ready to merge, stat: QA tested, squad: omnichannel

#31606 test: make channels api tests fully independent
  apps/meteor/tests/data/api-data.js
  apps/meteor/tests/data/channel.ts
  apps/meteor/tests/data/uploads.helper.ts
  apps/meteor/tests/end-to-end/api/02-channels.js
  apps/meteor/tests/end-to-end/api/03-groups.js
  apps/meteor/tests/end-to-end/api/04-direct-message.js
Labels: stat: ready to merge, stat: QA skipped

#31626 feat: Freezes permissions table first column
  .changeset/five-dragons-joke.md
  apps/meteor/client/components/GenericTable/GenericTable.tsx
  apps/meteor/client/views/admin/permissions/PermissionsTable/PermissionsTable.tsx
  apps/meteor/client/views/admin/permissions/PermissionsTable/RoleHeader.tsx
Labels: stat: ready to merge, stat: QA skipped

#31600 fix: Looking at the user's permission before rendering the 'Start Call' button on UserInfo
  .changeset/small-beers-call.md
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useCallAction.tsx
Labels: stat: ready to merge, stat: QA tested, squad: team-collab

#31128 fix: Mentioning discussion displays its ID instead of name
  .changeset/perfect-books-listen.md
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
  packages/core-typings/src/IMessage/IMessage.ts
  packages/gazzodown/src/mentions/ChannelMentionElement.tsx
Labels: stat: ready to merge, stat: QA tested

#31658 fix: Messages not updating properly after pruning the room
  .changeset/twenty-yaks-grab.md
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
Labels: stat: ready to merge, stat: QA skipped

#31654 regression: Exclude clearRemovedRoomsHistory from L rooms
  apps/meteor/client/providers/UserProvider/hooks/useClearRemovedRoomsHistory.ts
  apps/meteor/server/modules/watchers/watchers.module.ts
  ee/packages/ddp-client/src/types/streams.ts
  packages/core-services/src/events/Events.ts
Labels: stat: ready to merge, stat: QA tested

#31625 fix: Login form GUI crash after closing 2FA modal
  .changeset/tall-bears-compete.md
  packages/web-ui-registration/src/LoginForm.tsx
Labels: stat: ready to merge, stat: QA skipped

#31621 feat: Improve 2fa modals and change resend email to button
  .changeset/thirty-beds-taste.md
  apps/meteor/client/components/TwoFactorModal/TwoFactorEmailModal.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorTotpModal.tsx
  apps/meteor/client/views/account/security/TwoFactorTOTP.tsx
  apps/meteor/packages/rocketchat-i18n/i18n/af.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/az.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/be-BY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bg.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/bs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/cy.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-AT.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/el.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/eo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fa.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/id.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/km.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ku.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lo.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/lv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/mn.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ms-MY.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pt.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ro.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sk-SK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sl-SI.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sq.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ta-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/th-TH.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/uk.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/vi-VN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-HK.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
Labels: stat: ready to merge, stat: QA skipped

#31681 test: make stats and license tests fully independent
  apps/meteor/tests/end-to-end/api/19-statistics.js
  apps/meteor/tests/end-to-end/api/20-licenses.js
Labels: stat: ready to merge, stat: QA skipped

#31659 test: make settings fully independent
  apps/meteor/tests/end-to-end/api/08-settings.js
Labels: stat: ready to merge, stat: QA skipped

#31675 test: make permission test fully independent
  apps/meteor/tests/end-to-end/api/11-permissions.js
Labels: stat: ready to merge, stat: QA skipped

#31622 chore: Introduce `UserCardProvider`
  apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/app/ui/client/lib/userCard.ts
  apps/meteor/client/components/GazzodownText.tsx
  apps/meteor/client/components/UserCard/UserCard.stories.tsx
  apps/meteor/client/components/UserCard/UserCard.tsx
  apps/meteor/client/components/UserCard/UserCardAction.tsx
  apps/meteor/client/components/UserCard/UserCardActions.tsx
  apps/meteor/client/components/UserCard/UserCardContainer.tsx
  apps/meteor/client/components/UserCard/UserCardSkeleton.tsx
  apps/meteor/client/components/UserCard/index.ts
  apps/meteor/client/components/UserInfo/UserInfo.tsx
  apps/meteor/client/components/UserInfo/UserInfoUsername.tsx
  apps/meteor/client/components/message/MessageHeader.tsx
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/SystemMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/views/admin/moderation/UserReports/UserReportInfo.tsx
  apps/meteor/client/views/admin/users/AdminUserInfoWithData.tsx
  apps/meteor/client/views/oauth/components/CurrentUserDisplay.tsx
  apps/meteor/client/views/omnichannel/components/Info.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
  apps/meteor/client/views/room/UserCardHolder.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/contexts/UserCardContext.ts
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoWithData.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useCallAction.tsx
  apps/meteor/client/views/room/modals/ReactionListModal/ReactionListModal.tsx
  apps/meteor/client/views/room/modals/ReactionListModal/ReactionUserTag.tsx
  apps/meteor/client/views/room/modals/ReactionListModal/Reactions.tsx
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/client/views/room/providers/UserCardProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useChatMessagesInstance.ts
  apps/meteor/client/views/room/providers/hooks/useUserCard.ts
Labels: stat: ready to merge, stat: QA skipped

#31674 test: make emoji custom test fully independent
  apps/meteor/tests/end-to-end/api/12-emoji-custom.js
Labels: stat: ready to merge, stat: QA skipped

#31677 test: make commands test fully independent
  apps/meteor/tests/end-to-end/api/16-commands.js
Labels: stat: ready to merge, stat: QA skipped

#31678 test: make custom sound tests fully independent
  apps/meteor/tests/end-to-end/api/17-custom-sounds.js
Labels: stat: ready to merge, stat: QA skipped

#31673 test: make subscription test fully independent
  apps/meteor/tests/end-to-end/api/10-subscriptions.js
Labels: stat: ready to merge, stat: QA skipped

#31676 test: make assets api tests fully independent
  apps/meteor/tests/end-to-end/api/14-assets.js
Labels: stat: ready to merge, stat: QA skipped

#31680 test: make oauthapps test fully independent
  apps/meteor/tests/end-to-end/api/18-oauthapps.js
Labels: stat: ready to merge, stat: QA skipped

#31700 fix: add group and section to homeserver domain setting
  .changeset/cyan-countries-impress.md
  .gitignore
  apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Settings.ts
Labels: stat: ready to merge, stat: QA skipped

#31703 fix: Reactions tooltip loader
  .changeset/rich-dingos-mix.md
  apps/meteor/client/components/message/content/reactions/ReactionTooltip.tsx
Labels: stat: ready to merge, stat: QA skipped

#31595 i18n: German translation switches 'conversation' and 'discussion'
  apps/meteor/packages/rocketchat-i18n/i18n/de-IN.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
Labels: stat: QA skipped

#31604 fix: ldap avatar sync background process never runs
  .changeset/ten-bobcats-occur.md
  apps/meteor/ee/server/configuration/ldap.ts
  apps/meteor/ee/server/settings/ldap.ts
Labels: stat: ready to merge, stat: QA tested

#31745 fix: #31722 roomName is not getting update
  .changeset/blue-files-deny.md
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
Labels: stat: ready to merge, communityPR, stat: QA skipped

#31713 fix: Admin can't change room name
  .changeset/curly-dodos-tan.md
  apps/meteor/client/views/admin/rooms/EditRoom.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA skipped

#31742 test: make api methods test fully independent
  apps/meteor/tests/end-to-end/api/24-methods.js
Labels: stat: needs QA

#31723 fix: User presence not updating
  .changeset/large-toys-matter.md
  apps/meteor/app/notifications/client/index.ts
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/client/importPackages.ts
Labels: stat: needs QA

#31752 fix: Blinking UI colors when finishing a Livechat conversation.
  .changeset/silver-chicken-learn.md
  packages/livechat/src/lib/room.js
Labels: stat: ready to merge, stat: QA tested

#31753 fix: Custom OAuth not working if other login services are also enabled
  .changeset/lucky-ducks-join.md
  apps/meteor/client/startup/customOAuth.ts
  apps/meteor/tests/e2e/config/global-setup.ts
  apps/meteor/tests/e2e/fixtures/addCustomOAuth.ts
  apps/meteor/tests/e2e/oauth.spec.ts
  apps/meteor/tests/e2e/page-objects/auth.ts
Labels: stat: ready to merge, stat: QA tested

#31711 test: make push api tests fully independent
  apps/meteor/tests/end-to-end/api/22-push.ts
Labels: stat: ready to merge, stat: QA skipped

#31754 feat: added hideGuestAvatar and hideAgentAvatar to Livechat API's setTheme
  packages/livechat/src/components/Messages/Message/index.js
  packages/livechat/src/components/Messages/MessageList/index.js
  packages/livechat/src/components/Screen/ScreenProvider.tsx
  packages/livechat/src/routes/Chat/component.js
  packages/livechat/src/routes/Chat/connector.tsx
  packages/livechat/src/routes/Chat/container.js
  packages/livechat/src/store/index.tsx
Labels: stat: needs QA, squad: omnichannel

#31789 ci: end-to-end tests breaking
  apps/meteor/tests/e2e/fixtures/userStates.ts
Labels: stat: ready to merge, stat: QA skipped

#31781 regression: Reactions loader skeleton color
  apps/meteor/client/components/message/content/reactions/ReactionTooltip.tsx
Labels: stat: ready to merge, stat: QA skipped

#31549 feat: Message keyboard navigability
  .changeset/spicy-wombats-shout.md
  apps/meteor/client/components/message/MessageHeader.tsx
  apps/meteor/client/components/message/toolbar/MessageToolbar.tsx
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/SystemMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiElement.tsx
  apps/meteor/client/views/room/Room.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useMessageListNavigation.ts
  apps/meteor/package.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31788 fix: some apps-engine bridges are receiving incompatible data
  .changeset/dirty-islands-mate.md
  apps/meteor/app/apps/server/bridges/messages.ts
  apps/meteor/app/apps/server/bridges/persistence.ts
  apps/meteor/app/apps/server/converters/threads.ts
Labels: stat: ready to merge, stat: QA skipped

#31797 chore: bump turbo
  package.json
  yarn.lock
Labels: stat: needs QA

#29469 chore: Replace dropdown in favor of `MenuV2` on message toolbar menu
  apps/meteor/app/reactions/client/init.ts
  apps/meteor/app/threads/client/messageAction/replyInThread.ts
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/client/components/message/MessageToolbarHolder.tsx
  apps/meteor/client/components/message/toolbar/DesktopToolbarDropdown.tsx
  apps/meteor/client/components/message/toolbar/MessageActionMenu.tsx
  apps/meteor/client/components/message/toolbar/MessageToolbar.tsx
  apps/meteor/client/components/message/toolbar/MobileToolbarDropdown.tsx
  apps/meteor/client/components/message/toolbar/ToolbarDropdown.tsx
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/threads.spec.ts
Labels: stat: ready to merge, stat: QA skipped

#31800 ci: change arg place to reuse cache
  .github/actions/meteor-build/action.yml
  apps/meteor/package.json
  turbo.json
Labels: stat: needs QA

#31759 fix: DM notifications when preference set to mentions
  .changeset/flat-fishes-sniff.md
  apps/meteor/app/lib/server/functions/notifications/desktop.ts
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.ts
Labels: stat: ready to merge, stat: QA tested

#31801 chore: add missing packages to ddp-client
  ee/packages/ddp-client/package.json
  yarn.lock
Labels: stat: needs QA

#31799 chore: bump meteor 2.15
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/release
  apps/meteor/.meteor/versions
Labels: stat: ready to merge, stat: QA skipped

#31701 fix: Correct display of discussion names in sidebar search
  .changeset/rude-avocados-notice.md
  apps/meteor/server/lib/spotlight.js
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/search-discussion.spec.ts
  apps/meteor/tests/e2e/utils/create-target-channel.ts
  apps/meteor/tests/e2e/utils/getSettingValueById.ts
Labels: stat: ready to merge, stat: QA tested

#31814 fix: slashcommand preview
  apps/meteor/app/apps/server/bridges/commands.ts
Labels: stat: needs QA

#31785 test: make calendar api tests fully independent
  apps/meteor/tests/end-to-end/api/30-calendar.ts
Labels: stat: needs QA

#31578 fix: deno runtime improvements
  apps/meteor/app/apps/server/bridges/commands.ts
  apps/meteor/app/apps/server/bridges/http.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/storage/AppRealLogStorage.ts
Labels: stat: needs QA

#31819 regression: Prevent storing lastFocused message by click event
  apps/meteor/client/views/room/hooks/useMessageListNavigation.ts
  apps/meteor/tests/e2e/messaging.spec.ts
Labels: stat: needs QA

#31823 fix: revert status websocket payload changes
  .changeset/strange-lamps-taste.md
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  ee/packages/ddp-client/src/types/streams.ts
Labels: stat: needs QA

#31835 ci: end-to-end tests breaking
  apps/meteor/tests/e2e/fixtures/userStates.ts
Labels: stat: ready to merge, stat: QA tested

#31832 fix: Omnichannel analytics page (productivity overview)
  .changeset/kind-lobsters-leave.md
  apps/meteor/app/livechat/server/lib/Analytics.js
Labels: stat: ready to merge, stat: QA tested

#31831 chore: `VideoConfPopup` keyboard navigability
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/StartCallPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/VideoConfPopupRoomInfo.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/hooks/useVideoConfRoomName.ts
  apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/no.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
  apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
  apps/meteor/tests/e2e/channel-management.spec.ts
  packages/ui-video-conf/src/VideoConfController.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooter.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooterButtons.tsx
Labels: stat: ready to merge, stat: QA skipped

#31830 test: saml login custom role
  apps/meteor/ee/server/configuration/saml.ts
  apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/authsources.php
  apps/meteor/tests/e2e/fixtures/userStates.ts
  apps/meteor/tests/e2e/saml.spec.ts
  apps/meteor/tests/e2e/utils/custom-role.ts
Labels: stat: needs QA

#31833 fix: client ignoring offline presence updates
  .changeset/young-doors-bathe.md
  apps/meteor/app/notifications/client/lib/Presence.ts
  ee/apps/ddp-streamer/package.json
Labels: stat: needs QA

#31844 fix: make lifecycle methods part of inherited class in federation services
  .changeset/shy-bananas-repeat.md
  apps/meteor/ee/server/local-services/federation/service.ts
  apps/meteor/server/services/federation/service.ts
Labels: stat: needs QA

#31846 chore: Sidebar toolbar keyboard navigation
  apps/meteor/client/sidebar/header/Header.tsx
  apps/meteor/client/sidebar/header/HeaderUnstable.tsx
  apps/meteor/client/sidebar/header/SidebarHeaderToolbar.tsx
  apps/meteor/client/sidebar/sections/OmnichannelSection.tsx
  apps/meteor/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/i18n/src/locales/en.i18n.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA skipped

#31849 Release 6.6.2
  .changeset/bump-patch-1709141264352.md
  .changeset/shy-bananas-repeat.md
  .changeset/strange-lamps-taste.md
  .changeset/young-doors-bathe.md
  apps/meteor/app/notifications/client/lib/Presence.ts
  apps/meteor/ee/server/local-services/federation/service.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  apps/meteor/server/services/federation/service.ts
  ee/apps/ddp-streamer/package.json
  ee/packages/ddp-client/src/types/streams.ts
  yarn.lock
Labels: stat: needs QA

#31843 chore: Upgrade `react-virtuoso`
  apps/meteor/client/components/CustomScrollbars/CustomScrollbars.tsx
  apps/meteor/client/components/CustomScrollbars/VirtuosoScrollbars.tsx
  apps/meteor/client/components/CustomScrollbars/index.ts
  apps/meteor/client/components/GenericTable/GenericTable.tsx
  apps/meteor/client/components/Page/PageScrollableContent.tsx
  apps/meteor/client/components/Sidebar/Content.tsx
  apps/meteor/client/sidebar/RoomList/RoomList.tsx
  apps/meteor/client/sidebar/RoomList/ScrollerWithCustomProps.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/FederatedRoomList.tsx
  apps/meteor/client/sidebar/search/ScrollerWithCustomProps.tsx
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/views/admin/integrations/outgoing/history/OutgoingWebhookHistoryPage.tsx
  apps/meteor/client/views/composer/EmojiPicker/CategoriesResult.tsx
  apps/meteor/client/views/composer/EmojiPicker/SearchingResult.tsx
  apps/meteor/client/views/omnichannel/contactHistory/ContactHistoryList.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessagesList.tsx
  apps/meteor/client/views/outlookCalendar/OutlookEventsList/OutlookEventsList.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsList.tsx
  apps/meteor/client/views/room/contextualBar/MessageListTab.tsx
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearch.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/RoomFiles.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfList.tsx
  apps/meteor/client/views/teams/contextualBar/channels/BaseTeamsChannels.tsx
  apps/meteor/ee/client/omnichannel/cannedResponses/contextualBar/CannedResponse/CannedResponseList.tsx
  apps/meteor/package.json
  packages/uikit-playground/package.json
  yarn.lock
Labels: stat: needs QA

#31804 fix: Login page breaking when handling not expected errors
  .changeset/quick-cheetahs-help.md
  packages/web-ui-registration/src/LoginForm.tsx
  packages/web-ui-registration/src/LoginServices.tsx
  packages/web-ui-registration/src/LoginServicesButton.tsx
Labels: stat: ready to merge, stat: QA tested

#31837 chore: `RoomHeader` keyboard navigability
  apps/meteor/client/views/room/Header/ParentRoom.tsx
  apps/meteor/client/views/room/Header/ParentTeam.tsx
  apps/meteor/client/views/room/Header/RoomTitle.tsx
  apps/meteor/client/views/room/Header/icons/Favorite.tsx
  apps/meteor/client/views/room/body/LeaderBar.tsx
  apps/meteor/tests/e2e/channel-management.spec.ts
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/team-management.spec.ts
  packages/ui-client/src/components/Header/HeaderTag/HeaderTag.tsx
  packages/ui-client/src/components/Header/HeaderTitleButton.tsx
  packages/ui-client/src/components/Header/index.ts
Labels: stat: needs QA

#31572 feat: show date on message's scroll
  .changeset/nine-ads-hide.md
  apps/meteor/client/views/room/MessageList/MessageList.tsx
  apps/meteor/client/views/room/MessageList/MessageListItem.tsx
  apps/meteor/client/views/room/Room.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/RoomForeword/RoomForeword.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageItem.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/hooks/useDateScroll.ts
  apps/meteor/client/views/room/hooks/useScrollMessageList.ts
  apps/meteor/client/views/room/providers/DateListProvider.tsx
Labels: stat: ready to merge, stat: QA skipped
