Repository RocketChat/Rocket.Chat, pull requests merged in 2025-02, with the labels that each got.

#35076 test: Wrong setting used on test as placebo
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/24-routing.ts
Labels: stat: ready to merge, stat: QA assured

#33816 feat: use Livechat Contacts as a reference for the MAC limit
  .changeset/slow-flies-hear.md
  apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/contacts/ContactMerger.ts
  apps/meteor/app/livechat/server/lib/contacts/registerContact.spec.ts
  apps/meteor/ee/app/license/server/startup.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/end-to-end/api/livechat/23-mac.ts
  apps/meteor/tests/unit/server/livechat/hooks/markRoomResponded.spec.ts
  packages/core-typings/src/ILivechatContact.ts
  packages/model-typings/src/models/ILivechatContactsModel.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
  packages/models/src/models/LivechatContacts.ts
  packages/models/src/models/LivechatRooms.ts
  packages/models/src/models/LivechatVisitors.ts
Labels: stat: ready to merge, stat: QA assured

#35082 fix: `LayoutProvider` rerendering
  .changeset/funny-ears-kick.md
  apps/meteor/client/providers/LayoutProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#35092 chore(deps): bump storybook dependencies
  apps/meteor/package.json
  ee/packages/pdf-worker/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/mock-providers/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35044 fix: Departments could be removed via API even with setting `Omnichannel_enable_department_removal` off
  .changeset/dry-jeans-thank.md
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/01-agents.ts
  apps/meteor/tests/end-to-end/api/livechat/07-queue.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
Labels: stat: ready to merge, stat: QA assured

#34995 refactor: remove meteor startup from livechat-enterprise
  apps/meteor/app/livechat-enterprise/client/index.ts
  apps/meteor/app/livechat-enterprise/client/startup.ts
  apps/meteor/app/livechat-enterprise/hooks/useLivechatEnterprise.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35089 fix: catch unhandled error when adding or refreshing oauth apps
  .changeset/twenty-camels-worry.md
  apps/meteor/server/services/meteor/service.ts
Labels: stat: ready to merge, stat: QA assured

#35093 chore(deps): remove PostCSS IE11 plugin
  packages/livechat/package.json
  postcss.config.js
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35047 refactor: Reduce `VideoConfContext` exhausting types
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.spec.tsx
  apps/meteor/tests/mocks/utils/video-conference.ts
  packages/mock-providers/package.json
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/ui-video-conf/src/VideoConfContext.ts
  packages/ui-video-conf/src/hooks/useVideoConfContext.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35060 refactor: Replace `useEndpointData` in VideoConf incoming popup
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/IncomingPopup.tsx
Labels: stat: ready to merge, stat: QA assured

#35079 fix: Use i18nTitle provided by the app in `ComposerBoxPopupPreview` component
  .changeset/cuddly-garlics-cover.md
  apps/meteor/client/views/room/composer/ComposerBoxPopupPreview.tsx
  apps/meteor/client/views/room/composer/hooks/useComposerBoxPopup.ts
  apps/meteor/client/views/room/composer/hooks/useMessageComposerMergedRefs.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/contexts/ComposerPopupContext.ts
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#35135 chore(deps): bump @slack/bolt dependency
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35128 chore: object containing `key` prop being spread into MenuItem
  apps/meteor/client/views/room/Header/RoomToolbox/hooks/useRoomToolboxActions.ts
  apps/meteor/client/views/room/HeaderV2/RoomToolbox/hooks/useRoomToolboxActions.ts
Labels: stat: ready to merge, stat: QA assured

#35117 fix: handle `shouldAddRateLimitToRoute` exception to prevent the server from crashing
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/v1/users.ts
Labels: stat: ready to merge, stat: QA assured

#34994 refactor: remove meteor from settingsOnLoadSiteUrl.ts
  apps/meteor/app/lib/client/index.ts
  apps/meteor/app/lib/client/startup/settingsOnLoadSiteUrl.ts
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/hooks/useSettingsOnLoadSiteUrl.ts
Labels: stat: ready to merge, stat: QA assured

#35141 test: waitFor dialog in `VideoConfPopups` unit test
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.spec.tsx
Labels: stat: ready to merge, stat: QA assured

#35136 chore(deps): bump cssnano
  packages/livechat/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35151 test: Mocked incoming call causing unit test intermittence
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.spec.tsx
  apps/meteor/tests/mocks/utils/video-conference.ts
Labels: stat: ready to merge, stat: QA assured

#35148 chore(deps): change apn to @parse/node-apn
  apps/meteor/app/push/server/apn.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35145 regression: desambiguate manually app routes
  apps/meteor/ee/server/apps/communication/rest.ts
Labels: stat: ready to merge, stat: QA assured

#35150 chore(deps): bump `vite` in the `uikit-playground` app
  apps/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35021 refactor: remove meteor from setupWizard
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/setupWizard.ts
  apps/meteor/client/startup/useRedirectToSetupWizard.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35020 chore: fix models path on codeowner
  .github/CODEOWNERS
Labels: stat: ready to merge, stat: QA assured

#35146 chore: `AudioMessageRecorder` mount effect
  apps/meteor/client/views/composer/AudioMessageRecorder/AudioMessageRecorder.tsx
  apps/meteor/playwright.config.ts
  apps/meteor/tests/e2e/message-composer.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35113 feat: Includes attachments metadata in JSON when exporting messages
  .changeset/proud-mayflies-invite.md
  apps/meteor/client/views/room/contextualBar/ExportMessages/useDownloadExportMutation.ts
Labels: stat: ready to merge, stat: QA assured

#35109 chore(deps): bump webpack
  packages/livechat/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34857 fix: "Status" column values in "Custom Status" page table not translated
  .changeset/seven-otters-worry.md
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusTable/CustomUserStatusRow.tsx
Labels: stat: ready to merge, stat: QA assured

#35164 chore(deps): bump `katex` version
  packages/gazzodown/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34993 refactor: remove meteor from gitlab auth
  apps/meteor/app/gitlab/client/hooks/useGitLabAuth.ts
  apps/meteor/app/gitlab/client/index.ts
  apps/meteor/app/gitlab/client/lib.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35100 fix: use correct start dates on omnichannel reports
  .changeset/kind-geckos-heal.md
  apps/meteor/client/components/dashboards/getClosedPeriod.spec.ts
  apps/meteor/client/components/dashboards/periods.ts
  apps/meteor/client/omnichannel/reports/utils/formatPeriodRange.ts
Labels: stat: ready to merge, stat: QA assured

#34199 refactor: Remove settings dependency on startup
  apps/meteor/app/assets/server/assets.ts
  apps/meteor/app/cors/server/cors.ts
  apps/meteor/app/federation/server/startup/index.ts
  apps/meteor/app/federation/server/startup/settings.ts
  apps/meteor/app/irc/server/index.ts
  apps/meteor/app/lib/server/lib/index.ts
  apps/meteor/app/lib/server/startup/index.ts
  apps/meteor/app/lib/server/startup/settingsOnLoadCdnPrefix.js
  apps/meteor/app/lib/server/startup/settingsOnLoadDirectReply.ts
  apps/meteor/app/lib/server/startup/settingsOnLoadSMTP.ts
  apps/meteor/app/lib/server/startup/settingsOnLoadSiteUrl.ts
  apps/meteor/server/configuration/cas.ts
  apps/meteor/server/configuration/configureAssets.ts
  apps/meteor/server/configuration/configureBoilerplate.ts
  apps/meteor/server/configuration/configureCDN.ts
  apps/meteor/server/configuration/configureCORS.ts
  apps/meteor/server/configuration/configureDirectReply.ts
  apps/meteor/server/configuration/configureIRC.ts
  apps/meteor/server/configuration/configureLogLevel.ts
  apps/meteor/server/configuration/configureSMTP.ts
  apps/meteor/server/configuration/federation.ts
  apps/meteor/server/configuration/index.ts
  apps/meteor/server/configuration/ldap.ts
  apps/meteor/server/configuration/oauth.ts
  apps/meteor/server/configuration/pushNotification.ts
  apps/meteor/server/configureLogLevel.ts
  apps/meteor/server/lib/logger/startup.ts
  apps/meteor/server/lib/pushConfig.ts
  apps/meteor/server/main.ts
Labels: stat: ready to merge, stat: QA assured

#35115 fix: url not being properly mounted
  .changeset/olive-stingrays-share.md
  packages/cas-validate/jest.config.ts
  packages/cas-validate/package.json
  packages/cas-validate/src/validate.spec.ts
  packages/cas-validate/src/validate.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35167 fix: `AssignExtensionButton` missing margin
  .changeset/thick-boats-shake.md
  apps/meteor/client/views/admin/users/voip/AssignExtensionButton.tsx
Labels: stat: ready to merge, stat: QA assured

#35059 chore: add validation layer to marketplace comms
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/marketplace/fetchMarketplaceApps.ts
  apps/meteor/ee/server/apps/marketplace/getMarketplaceHeaders.ts
  apps/meteor/ee/server/apps/marketplace/marketplaceErrors.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35127 fix: `EmojiPicker` not displaying active category properly
  apps/meteor/app/emoji/client/types.ts
  apps/meteor/client/contexts/EmojiPickerContext.ts
  apps/meteor/client/providers/EmojiPickerProvider/EmojiPickerProvider.tsx
  apps/meteor/client/views/composer/EmojiPicker/CategoriesResult.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiCategoryRow.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
  apps/meteor/tests/e2e/emojis.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA assured

#35085 chore(deps): replace oauth2-server
  apps/meteor/package.json
  apps/meteor/server/oauth2-server/model.ts
  apps/meteor/server/oauth2-server/oauth.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35154 chore: replace `suretype` with `zod`
  apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/announcementSync.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/fetchWorkspaceSyncPayload.ts
  apps/meteor/app/cloud/server/functions/syncWorkspace/legacySyncWorkspace.ts
  apps/meteor/ee/server/apps/marketplace/fetchMarketplaceApps.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35171 test: AutoTransferChats
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/lib/AutoTransferChatsScheduler.tests.ts
Labels: stat: ready to merge, stat: QA assured

#35176 chore(deps): bump `sanitize-html`
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35190 ci: update cache to v4 on docker build
  .github/actions/build-docker/action.yml
Labels: stat: ready to merge, stat: QA assured

#35186 feat: ui
  apps/meteor/client/components/AutoCompleteMultipleAgent.tsx
  apps/meteor/client/components/Omnichannel/hooks/useUnitsList.ts
  apps/meteor/client/omnichannel/additionalForms/AutoCompleteUnits.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatsFiltersContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatsTable/useChatsQuery.ts
  apps/meteor/client/views/omnichannel/directory/contexts/ChatsContext.ts
  apps/meteor/client/views/omnichannel/directory/hooks/useDisplayFilters.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/units.ts
  apps/meteor/ee/server/models/raw/LivechatUnit.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  packages/model-typings/src/models/ILivechatUnitModel.ts
Labels: stat: ready to merge, stat: QA assured

#35189 fix: empty "Apps_Error_" toast message when private app installation fails
  .changeset/brave-ties-shout.md
  apps/meteor/ee/server/apps/communication/rest.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35174 chore(deps): bump `esbuild`
  packages/apps-engine/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35108 chore(deps): bump nyc
  apps/meteor/package.json
  packages/apps-engine/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35121 fix: Restore room scroll for secondary navigation
  .changeset/lucky-birds-lie.md
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/RoomBodyV2.tsx
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.spec.ts
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
Labels: stat: ready to merge, stat: QA assured

#35198 chore: restore FOSS startup process
  apps/meteor/server/ee.ts
  apps/meteor/server/foss.ts
  apps/meteor/server/main.ts
  apps/meteor/startRocketChat.ts
  apps/meteor/startRocketChatFOSS.ts
  scripts/fossify.ts
Labels: stat: ready to merge, stat: QA assured

#35016 refactor: remove subscriptions method calls (server)
  apps/meteor/app/api/server/v1/subscriptions.ts
  apps/meteor/app/message-mark-as-unread/server/unreadMessages.ts
  apps/meteor/server/publications/subscription/index.ts
Labels: stat: ready to merge, stat: QA assured

#35140 fix: Notify user stream when enabling/disabling email2fa
  .changeset/new-ears-check.md
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/tests/e2e/account-profile.spec.ts
  apps/meteor/tests/e2e/fixtures/collections/users.ts
  apps/meteor/tests/e2e/page-objects/account-profile.ts
Labels: stat: ready to merge, stat: QA assured

#35170 fix: updating some apps via Marketplace ignores permissions
  .changeset/mean-elephants-boil.md
  apps/meteor/ee/server/apps/communication/rest.ts
Labels: stat: ready to merge, stat: QA assured

#34992 refactor: remove meteor from githubenterprise auth
  apps/meteor/app/github-enterprise/client/hooks/useGitHubEnterpriseAuth.ts
  apps/meteor/app/github-enterprise/client/index.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35153 chore: add a retry on get supported versions from cloud
  apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts
Labels: stat: ready to merge, stat: QA assured

#34204 refactor: remove Meteor calls for message history methods
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/app/lib/server/methods/getChannelHistory.ts
  apps/meteor/server/publications/messages.ts
  apps/meteor/tests/unit/server/publications/messages.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35124 fix: no highlighting of non-latin highlights
  .changeset/purple-laws-joke.md
  apps/meteor/app/lib/server/functions/notifications/messageContainsHighlight.ts
  apps/meteor/client/components/GazzodownText.spec.tsx
  apps/meteor/client/components/GazzodownText.tsx
  apps/meteor/tests/unit/app/lib/server/functions/notifications/messageContainsHighlight.tests.ts
Labels: stat: ready to merge, stat: QA assured

#35165 refactor: validate required custom fields on visitor creation
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/validateRequiredCustomFields.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/unit/app/livechat/server/lib/validateRequiredCustomFields.spec.ts
Labels: stat: ready to merge, stat: QA assured

#34991 refactor: remove meteor from drupal auth
  apps/meteor/app/drupal/client/hooks/useDrupal.ts
  apps/meteor/app/drupal/client/index.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35031 refactor: Moves `getUserDisplayName` outside from meteor app
  apps/meteor/app/lib/server/functions/attachMessage.ts
  apps/meteor/app/lib/server/startup/mentionUserNotInChannel.ts
  apps/meteor/client/NavBarV2/NavBarSettingsToolbar/UserMenu/UserMenuHeader.tsx
  apps/meteor/client/components/UserInfo/UserInfo.tsx
  apps/meteor/client/components/message/MessageHeader.tsx
  apps/meteor/client/components/message/variants/SystemMessage.tsx
  apps/meteor/client/hooks/useRoomName.ts
  apps/meteor/client/lib/getUserDisplayName.spec.ts
  apps/meteor/client/sidebar/header/UserMenuHeader.tsx
  apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx
  apps/meteor/client/views/conference/ConferencePage.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
  apps/meteor/client/views/outlookCalendar/hooks/useOutlookOpenCall.ts
  apps/meteor/client/views/room/UserCard/UserCardWithData.tsx
  apps/meteor/client/views/room/body/RoomForeword/RoomForewordUsernameList.tsx
  apps/meteor/client/views/room/body/RoomForeword/RoomForewordUsernameListItem.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxReplies.tsx
  apps/meteor/client/views/room/composer/messageBox/MessageBoxReply.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/hooks/useVideoConfRoomName.ts
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useReportUser.tsx
  apps/meteor/client/views/room/modals/ForwardMessageModal/ForwardMessageModal.tsx
  apps/meteor/client/views/room/modals/PinMessageModal/PinMessageModal.tsx
  apps/meteor/client/views/room/modals/ReadReceiptsModal/ReadReceiptRow.tsx
  apps/meteor/lib/createQuoteAttachment.ts
  apps/meteor/lib/getUserDisplayName.ts
  apps/meteor/server/lib/rooms/roomCoordinator.ts
  packages/core-typings/src/IUser.ts
  packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
  packages/ui-client/src/components/index.ts
  packages/ui-client/src/hooks/index.ts
  packages/ui-client/src/hooks/useUserDisplayName.spec.ts
  packages/ui-client/src/hooks/useUserDisplayName.ts
  packages/ui-client/src/index.ts
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageUserStack.tsx
Labels: stat: ready to merge, stat: QA assured

#35195 fix: ddp-streamer restart keeping opened connections
  _templates/service/new/service.ejs.t
  apps/meteor/ee/server/startup/index.ts
  ee/apps/account-service/src/service.ts
  ee/apps/authorization-service/src/service.ts
  ee/apps/ddp-streamer/src/service.ts
  ee/apps/omnichannel-transcript/src/service.ts
  ee/apps/presence-service/src/service.ts
  ee/apps/queue-worker/src/service.ts
  ee/apps/stream-hub-service/src/service.ts
  ee/packages/network-broker/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#35137 chore(deps): bump `cross-spawn` by adding resolutions
  package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34957 feat: Team collab VoIP config modal
  .changeset/light-yaks-drive.md
  apps/meteor/client/hooks/roomActions/useStartCallRoomAction/useStartCallRoomAction.tsx
  apps/meteor/client/hooks/roomActions/useStartCallRoomAction/useVoipMenuOptions.tsx
  apps/meteor/client/hooks/useVoipWarningModal.tsx
  apps/meteor/client/views/room/contextualBar/TeamsVoipConfigModal.tsx
  apps/meteor/public/images/teams-voip-config.svg
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#34208 feat: `rooms.hide` endpoint
  .changeset/chilly-sheep-cover.md
  apps/meteor/app/api/server/v1/rooms.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/models/src/models/Subscriptions.ts
  packages/rest-typings/src/v1/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#34990 refactor: remove meteor startup & autorun from dolphin auth
  apps/meteor/app/dolphin/client/hooks/useDolphin.ts
  apps/meteor/app/dolphin/client/index.ts
  apps/meteor/app/dolphin/client/lib.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35231 fix: imported fixes 2025-02-17
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/tests/end-to-end/api/channels.ts
Labels: stat: ready to merge, stat: QA assured

#35177 feat(apps): add IPostSystemMessageSent event
  .changeset/happy-nails-fry.md
  apps/meteor/app/apps/server/bridges/listeners.js
  apps/meteor/app/apps/server/converters/messages.js
  apps/meteor/app/lib/server/functions/sendMessage.ts
  apps/meteor/server/services/messages/service.ts
  apps/meteor/tests/unit/app/apps/server/messages.tests.js
  packages/apps-engine/src/definition/messages/IMessage.ts
  packages/apps-engine/src/definition/messages/IPostSystemMessageSent.ts
  packages/apps-engine/src/definition/messages/MessageType.ts
  packages/apps-engine/src/definition/messages/index.ts
  packages/apps-engine/src/definition/metadata/AppInterface.ts
  packages/apps-engine/src/definition/metadata/AppMethod.ts
  packages/apps-engine/src/server/managers/AppListenerManager.ts
  packages/apps/src/bridges/IListenerBridge.ts
Labels: stat: ready to merge, stat: QA assured

#34989 refactor: remove meteor startup & autorun from emojione
  apps/meteor/app/emoji-emojione/client/hooks/useEmojiOne.ts
  apps/meteor/app/emoji-emojione/client/index.ts
  apps/meteor/app/emoji-emojione/client/lib.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35029 fix: `Enabled when agent idle` setting not being respected by routing algorithms
  .changeset/cool-coins-agree.md
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/getOnlineAgents.ts
  apps/meteor/app/livechat/server/lib/routing/AutoSelection.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/routing/LoadBalancing.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/routing/LoadRotation.ts
  apps/meteor/tests/data/livechat/rooms.ts
  apps/meteor/tests/data/users.helper.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  apps/meteor/tests/end-to-end/api/livechat/24-routing.ts
  packages/model-typings/src/models/IUsersModel.ts
  packages/models/src/models/Users.js
Labels: stat: ready to merge, stat: QA assured

#35225 chore(deps): bump `DOMPurify`
  apps/meteor/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/ui-client/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35191 chore: adjust freeswitch service to not leave dangling promise on startup
  apps/meteor/ee/server/local-services/voip-freeswitch/service.ts
Labels: stat: ready to merge, stat: QA assured

#35168 fix: Livechat conversation not closing due to cross-tab interference
  .changeset/rude-llamas-pay.md
  packages/livechat/src/lib/room.js
  packages/livechat/src/routes/Chat/container.js
Labels: stat: ready to merge, stat: QA assured

#35210 refactor: Chat endpoints to use AJV schemas
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/tests/e2e/jump-to-thread-message.spec.ts
  apps/meteor/tests/end-to-end/api/chat.ts
  packages/rest-typings/src/v1/chat.ts
Labels: stat: ready to merge, stat: QA assured

#35204 fix: Rooms not working in embedded layout
  .changeset/six-deers-dress.md
  apps/meteor/client/views/room/RoomOpenerEmbedded.tsx
Labels: stat: ready to merge, stat: QA assured

#35175 chore: replace the kadira flow router with the ostrio flow router
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/versions
  apps/meteor/client/main.ts
  apps/meteor/client/providers/RouterProvider.tsx
  apps/meteor/definition/externals/meteor/ostrio-flow-router.d.ts
Labels: stat: ready to merge, stat: QA assured

#34890 refactor: remove personal access token method calls (server)
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/imports/personal-access-tokens/server/api/methods/generateToken.ts
  apps/meteor/imports/personal-access-tokens/server/api/methods/regenerateToken.ts
  apps/meteor/imports/personal-access-tokens/server/api/methods/removeToken.ts
Labels: stat: ready to merge, stat: QA assured

#35245 chore(deps): bump `express` from `4.21.1` to `4.21.2`
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35131 refactor: Use updater for saveCustomFields function
  apps/meteor/app/lib/server/functions/saveCustomFields.ts
  apps/meteor/app/lib/server/functions/saveCustomFieldsWithoutValidation.ts
Labels: stat: ready to merge, stat: QA assured

#34274 feat: Adds setting to ignore automatic messages on metrics
  .changeset/funny-turtles-hunt.md
  apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
  apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
  apps/meteor/app/livechat/server/lib/isMessageFromBot.ts
  apps/meteor/server/settings/omnichannel.ts
  apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
  apps/meteor/tests/unit/app/livechat/server/lib/isMessageFromBot.spec.ts
  apps/meteor/tests/unit/server/livechat/hooks/markRoomResponded.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35188 fix: Notify user stream when enabling/disabling TOTP 2FA
  .changeset/five-wolves-destroy.md
  apps/meteor/app/2fa/server/methods/disable.ts
  apps/meteor/app/2fa/server/methods/validateTempToken.ts
  apps/meteor/client/views/account/security/TwoFactorTOTP.tsx
Labels: stat: ready to merge, stat: QA assured

#35256 test: Separate dates a bit more on `replicateMongoSlice` tests
  apps/meteor/tests/unit/app/e2e/server/functions/resetRoomKey.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35255 ci: storybook build-preview breaking
  packages/fuselage-ui-kit/.storybook/main.ts
  packages/fuselage-ui-kit/.storybook/webpackAddon.ts
  packages/gazzodown/.storybook/main.ts
  packages/gazzodown/.storybook/webpackAddon.ts
  packages/ui-composer/.storybook/main.ts
  packages/ui-composer/.storybook/webpackAddon.ts
Labels: stat: ready to merge, stat: QA assured

#35183 regression: fix urlencoded hooks
  apps/meteor/app/api/server/router.ts
  apps/meteor/app/integrations/server/api/api.js
Labels: stat: ready to merge, stat: QA assured

#35260 feat: improve IM/DM messages sorting to support multiple parameters
  .changeset/ninety-apes-poke.md
  apps/meteor/app/api/server/v1/im.ts
  apps/meteor/tests/end-to-end/api/direct-message.ts
Labels: stat: ready to merge, stat: QA assured

#35233 feat: improve color contrast in image gallery for WCAG compliance
  .changeset/green-rules-cover.md
  apps/meteor/client/components/ImageGallery/ImageGallery.tsx
Labels: stat: ready to merge, stat: QA assured

#35249 chore: endpoint change in channels.members test
  apps/meteor/tests/end-to-end/api/channels.ts
Labels: stat: ready to merge, stat: QA assured

#35147 feat: New filters on `livechat/rooms`
  .changeset/dull-hounds-agree.md
  apps/meteor/app/livechat/imports/server/rest/rooms.ts
  apps/meteor/app/livechat/server/api/lib/rooms.ts
  apps/meteor/client/components/AutoCompleteMultipleAgent.tsx
  apps/meteor/client/components/Omnichannel/hooks/useAgentsList.ts
  apps/meteor/client/components/Omnichannel/hooks/useUnitsList.ts
  apps/meteor/client/omnichannel/additionalForms/AutoCompleteUnits.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatsFiltersContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatsTable/useChatsQuery.ts
  apps/meteor/client/views/omnichannel/directory/contexts/ChatsContext.ts
  apps/meteor/client/views/omnichannel/directory/hooks/useDisplayFilters.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applyRoomRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/getUnitsFromUserRoles.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/tests/data/livechat/units.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/end-to-end/api/livechat/14-units.ts
  packages/models/src/models/LivechatRooms.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#35264 regression: downgrade `slack/bolt` version to prevent `SlackBridge` from breaking
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35143 chore: remove `node-gcm` library and features due to deprecation
  .changeset/sweet-timers-divide.md
  apps/meteor/app/push/server/gcm.ts
  apps/meteor/app/push/server/push.ts
  apps/meteor/package.json
  apps/meteor/server/configuration/pushNotification.ts
  apps/meteor/server/settings/push.ts
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/se.i18n.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35199 feat(apps): enable configuring which hidden settings are available for the apps
  .changeset/tough-eggs-camp.md
  apps/meteor/app/apps/server/bridges/settings.ts
  apps/meteor/app/apps/server/converters/settings.js
  apps/meteor/server/settings/setup-wizard.ts
  packages/apps-engine/src/definition/permissions/IPermission.ts
  packages/apps-engine/src/server/permissions/AppPermissions.ts
Labels: stat: ready to merge, stat: QA assured

#35068 chore: create handler to fetch categories from marketplace
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/marketplace/fetchMarketplaceCategories.ts
  packages/core-typings/src/Apps.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/apps/index.ts
Labels: stat: ready to merge, stat: QA assured

#35235 regression: Fix issue where marketplace would not fetch the apps
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/marketplace/fetchMarketplaceApps.ts
Labels: stat: ready to merge, stat: QA assured

#35265 fix: App event `IPostLivechatAgentAssigned` receiving old data
  .changeset/lazy-cheetahs-learn.md
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
Labels: stat: ready to merge, stat: QA assured

#35215 fix: Omnichannel transcript filename breaking links on some storages
  .changeset/popular-boats-poke.md
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  ee/packages/pdf-worker/src/worker.fixtures.ts
Labels: stat: ready to merge, stat: QA assured

#35120 fix(apps): prevent greedy update via apps
  .changeset/five-cherries-hang.md
  apps/meteor/app/apps/server/bridges/messages.ts
  apps/meteor/app/apps/server/bridges/rooms.ts
  apps/meteor/app/apps/server/converters/messages.js
  apps/meteor/app/apps/server/converters/rooms.js
  apps/meteor/tests/unit/app/apps/server/messages.tests.js
  apps/meteor/tests/unit/app/apps/server/mocks/data/messages.data.js
  apps/meteor/tests/unit/app/apps/server/mocks/models/Rooms.mock.js
  apps/meteor/tests/unit/app/apps/server/rooms.tests.ts
  packages/apps-engine/deno-runtime/lib/accessors/builders/MessageBuilder.ts
  packages/apps-engine/deno-runtime/lib/accessors/builders/RoomBuilder.ts
  packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyUpdater.ts
  packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyUpdater.test.ts
  packages/apps/src/converters/IAppMessagesConverter.ts
  packages/apps/src/converters/IAppRoomsConverter.ts
Labels: stat: ready to merge, stat: QA assured

#35208 feat: display leader role group in rooms' members list
  .changeset/rotten-peaches-cry.md
  .changeset/weak-kangaroos-admire.md
  apps/meteor/app/lib/server/functions/createRoom.ts
  apps/meteor/app/lib/server/functions/syncRolePrioritiesForRoomIfRequired.ts
  apps/meteor/client/views/hooks/useMemberList.spec.tsx
  apps/meteor/client/views/hooks/useMembersList.ts
  apps/meteor/client/views/room/body/LeaderBar.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/lib/roles/calculateRoomRolePriorityFromRoles.ts
  apps/meteor/server/lib/roles/syncRoomRolePriority.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  packages/core-typings/src/IRoom.ts
  packages/i18n/src/locales/en.i18n.json
  packages/model-typings/src/models/IRoomsModel.ts
  packages/models/src/models/Rooms.ts
Labels: stat: ready to merge, stat: QA assured

#35032 fix: Validate duplicated omnichannel contact email and phone
  .changeset/sour-rabbits-flow.md
  apps/meteor/client/views/omnichannel/contactInfo/EditContactInfo.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-center.spec.ts
Labels: stat: ready to merge, stat: QA assured

#34985 chore: add dependency control on local and network brokers
  ee/packages/network-broker/src/NetworkBroker.ts
  packages/core-services/src/LocalBroker.ts
  packages/core-services/src/types/ServiceClass.ts
  packages/core-services/tests/LocalBroker.test.ts
Labels: stat: ready to merge, stat: QA assured

#35194 fix: Users without preview permission possibility of subscribe to public channel stream
  .changeset/lemon-lions-learn.md
  apps/meteor/app/lib/server/methods/getChannelHistory.ts
  apps/meteor/server/modules/notifications/notifications.module.ts
  apps/meteor/server/services/authorization/canReadRoom.ts
  apps/meteor/server/services/authorization/service.ts
  packages/core-services/src/types/IAuthorization.ts
Labels: stat: ready to merge, stat: QA assured

#35269 fix: Switching from DM to channel throws an error
  .changeset/two-flowers-bake.md
  apps/meteor/client/lib/rooms/roomCoordinator.tsx
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  apps/meteor/server/publications/room/index.ts
  apps/meteor/tests/end-to-end/api/methods.ts
Labels: stat: ready to merge, stat: QA assured

#35279 regression: Preserve backend sort for `units` list
  apps/meteor/client/components/Omnichannel/hooks/useUnitsList.ts
Labels: stat: ready to merge, stat: QA assured

#35267 chore: Update Deno version on CI and dep cache
  .changeset/fresh-suns-boil.md
  .github/actions/setup-node/action.yml
  .github/workflows/ci-deploy-gh-pages.yml
  .github/workflows/ci.yml
  .github/workflows/new-release.yml
  .github/workflows/pr-update-description.yml
  .github/workflows/publish-release.yml
  .github/workflows/release-candidate.yml
  .tool-versions
  packages/apps-engine/deno-runtime/deno.jsonc
  packages/apps-engine/deno-runtime/deno.lock
  packages/apps-engine/deno-runtime/lib/parseArgs.ts
Labels: stat: ready to merge, stat: QA assured

#35297 regression: Old stored query conflicting with new filters applied
  apps/meteor/client/views/omnichannel/directory/providers/ChatsProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#35287 chore: Add `CodeSnippet` to `BackupCodesModal`
  apps/meteor/client/views/account/security/BackupCodesModal.tsx
Labels: stat: ready to merge, stat: QA assured

#35316 docs: Review README.md
  README.md
Labels: stat: QA assured

#33882 feat: Add unicode character support for default avatar
  .changeset/nervous-eels-march.md
  apps/meteor/server/routes/avatar/utils.spec.ts
  apps/meteor/server/routes/avatar/utils.ts
Labels: stat: ready to merge, communityPR, stat: QA assured

#35298 fix: Regenerate TOTP backup codes not opening modal
  .changeset/flat-balloons-draw.md
  apps/meteor/client/components/GenericModal/GenericModal.spec.tsx
  apps/meteor/client/components/TwoFactorModal/TwoFactorTotpModal.tsx
  apps/meteor/client/views/account/security/TwoFactorTOTP.tsx
Labels: stat: ready to merge, stat: QA assured

#35295 chore: remove ISubscription type casting on RoomOpenerEmbedded
  apps/meteor/client/lib/utils/mapSubscriptionFromApi.ts
  apps/meteor/client/views/room/RoomOpenerEmbedded.tsx
Labels: stat: ready to merge, stat: QA assured

#35324 refactor: Break big `livechatTyped` into smaller files
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/lib/server/functions/closeLivechatRoom.ts
  apps/meteor/app/lib/server/functions/closeOmnichannelConversations.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/api/v1/transcript.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/closeRoom.ts
  apps/meteor/app/livechat/server/lib/sendTranscript.ts
  apps/meteor/app/livechat/server/lib/stream/agentStatus.ts
  apps/meteor/app/livechat/server/methods/closeRoom.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/contacts.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/AutoCloseOnHoldScheduler.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/lib/AutoCloseOnHold.tests.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/QueueInactivityMonitor.spec.ts
  apps/meteor/tests/unit/app/lib/server/functions/closeLivechatRoom.tests.ts
Labels: stat: ready to merge, stat: QA assured

#35311 fix: sidebar behavior in lower screen size
  .changeset/itchy-teachers-jam.md
  apps/meteor/client/sidebar/header/UserMenu.tsx
  apps/meteor/client/sidebar/header/actions/Administration.tsx
  apps/meteor/client/sidebar/header/actions/CreateRoom.tsx
  apps/meteor/client/sidebar/header/actions/Sort.tsx
Labels: stat: ready to merge, stat: QA assured

#35347 regression: fix regex error when sending multi-line code
  apps/meteor/package.json
  packages/gazzodown/package.json
Labels: stat: ready to merge, stat: QA assured

#35333 refactor: Break down `LivechatTyped` into smaller components
  apps/meteor/app/apps/server/bridges/livechat.ts
  apps/meteor/app/livechat/server/api/v1/message.ts
  apps/meteor/app/livechat/server/hooks/offlineMessage.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/logger.ts
  apps/meteor/app/livechat/server/lib/messages.ts
  apps/meteor/app/livechat/server/lib/tracking.ts
  apps/meteor/app/livechat/server/lib/webhooks.ts
  apps/meteor/tests/unit/app/livechat/server/hooks/sendToCRM.tests.ts
Labels: stat: ready to merge, stat: QA assured

#35350 regression: show message asking for updating workspace when unsupported version
  apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/marketplace/fetchMarketplaceApps.ts
  apps/meteor/ee/server/apps/marketplace/fetchMarketplaceCategories.ts
  apps/meteor/ee/server/apps/marketplace/marketplaceErrors.ts
Labels: stat: ready to merge, stat: QA assured

#35361 fix: Some EE features not available after changing plans
  .changeset/eighty-meals-rule.md
  apps/meteor/client/lib/onToggledFeature.ts
Labels: stat: ready to merge, stat: QA assured
