Repository RocketChat/Rocket.Chat, pull requests merged in 2025-01, with the labels that each got.

#34858 fix: decoder error preventing succesfull app subprocess restart
  .changeset/cool-planes-protect.md
  packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
  packages/apps-engine/src/server/runtime/deno/LivenessManager.ts
  packages/apps-engine/src/server/runtime/deno/ProcessMessenger.ts
  packages/apps-engine/src/server/runtime/deno/codec.ts
Labels: stat: ready to merge, stat: QA assured

#34871 refactor: Correct call of `setModal`
  apps/meteor/client/apps/gameCenter/GameCenterList.tsx
  apps/meteor/client/providers/CallProvider/CallProvider.tsx
  apps/meteor/client/sidebar/header/hooks/useCreateRoomModal.tsx
  apps/meteor/client/sidebarv2/header/hooks/useCreateRoomModal.tsx
  apps/meteor/client/views/account/profile/AccountProfilePage.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx
  apps/meteor/client/views/admin/customSounds/EditSound.tsx
  apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
  apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeModeratorAction.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeOwnerAction.tsx
Labels: stat: ready to merge, stat: QA assured

#34881 chore: fix lint
  packages/apps-engine/src/server/ProxiedApp.ts
  packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
Labels: stat: ready to merge, stat: QA assured

#34894 regression: interval for metrics kept subprocess alive
  packages/apps-engine/deno-runtime/lib/metricsCollector.ts
  packages/apps-engine/deno-runtime/main.ts
Labels: stat: ready to merge, stat: QA assured

#34836 refactor: Replace `Menu` in favor of `GenericMenu` in DeviceManagement
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminRow.tsx
Labels: stat: ready to merge, stat: QA assured

#34887 fix: system throws GUI Application error while enabling, disabling and uninstalling an app.
  .changeset/giant-bottles-impress.md
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppRequests/AppRequests.tsx
  packages/core-typings/src/AppRequests.ts
Labels: stat: ready to merge, stat: QA assured

#34906 fix: Apps-engine reliability fixes
  .changeset/silent-numbers-love.md
  .changeset/silent-numbers-love2.md
  .changeset/silent-numbers-love3.md
  .changeset/silent-numbers-love4.md
  .changeset/silent-numbers-love5.md
  .changeset/silent-numbers-love6.md
  .changeset/silent-numbers-love7.md
  .changeset/silent-numbers-love8.md
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  ee/apps/ddp-streamer/package.json
  ee/packages/presence/package.json
  packages/apps/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/rest-typings/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34839 fix: app actions showing in room toolbar without icon
  .changeset/kind-ducks-thank.md
  apps/meteor/client/views/room/Header/RoomToolbox/RoomToolbox.tsx
  apps/meteor/client/views/room/Header/RoomToolbox/hooks/useRoomToolboxActions.spec.ts
  apps/meteor/client/views/room/Header/RoomToolbox/hooks/useRoomToolboxActions.ts
  apps/meteor/client/views/room/HeaderV2/RoomToolbox/RoomToolbox.tsx
  apps/meteor/client/views/room/HeaderV2/RoomToolbox/hooks/useRoomToolboxActions.spec.ts
  apps/meteor/client/views/room/HeaderV2/RoomToolbox/hooks/useRoomToolboxActions.ts
Labels: stat: ready to merge, stat: QA assured

#34904 fix: imported fixes 25-01-07
  .changeset/breezy-horses-marry.md
  apps/meteor/app/cors/server/cors.ts
  apps/meteor/app/oauth2-server-config/server/index.ts
  apps/meteor/app/oauth2-server-config/server/oauth/default-services.ts
  apps/meteor/client/components/FingerprintChangeModal.tsx
  apps/meteor/client/components/FingerprintChangeModalConfirmation.tsx
  apps/meteor/client/components/RawText.tsx
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/provider/OmnichannelRoomIconProvider.tsx
  apps/meteor/client/components/UrlChangeModal.tsx
  apps/meteor/client/lib/utils/createToken.ts
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
  apps/meteor/client/sidebar/footer/SidebarFooterDefault.tsx
  apps/meteor/client/sidebarv2/footer/SidebarFooterDefault.tsx
  apps/meteor/client/views/account/preferences/PreferencesMyDataSection.tsx
  apps/meteor/client/views/account/security/EndToEnd.tsx
  apps/meteor/client/views/account/tokens/AccountTokensTable/AccountTokensTable.tsx
  apps/meteor/client/views/account/tokens/AccountTokensTable/AddToken.tsx
  apps/meteor/client/views/admin/integrations/NewBot.tsx
  apps/meteor/client/views/admin/integrations/NewZapier.tsx
  apps/meteor/client/views/admin/integrations/incoming/IncomingWebhookForm.tsx
  apps/meteor/client/views/admin/integrations/outgoing/OutgoingWebhookForm.tsx
  apps/meteor/client/views/admin/integrations/outgoing/history/HistoryItem.tsx
  apps/meteor/client/views/admin/mailer/MailerPage.tsx
  apps/meteor/client/views/admin/settings/Setting/Setting.tsx
  apps/meteor/client/views/admin/settings/groups/OAuthGroupPage/OAuthGroupPage.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/admin/users/AdminUserSetRandomPasswordRadios.tsx
  apps/meteor/client/views/banners/LegacyBanner.tsx
  apps/meteor/client/views/composer/EmojiPicker/EmojiElement.tsx
  apps/meteor/client/views/composer/EmojiPicker/ToneSelector/ToneItem.tsx
  apps/meteor/client/views/e2e/EnterE2EPasswordModal.tsx
  apps/meteor/client/views/e2e/SaveE2EPasswordModal.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogsItemEntry.tsx
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearchForm.tsx
  apps/meteor/tests/end-to-end/api/oauthapps.ts
  packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyCreator.ts
  packages/apps-engine/src/server/accessors/LivechatCreator.ts
  packages/i18n/src/locales/en.i18n.json
  packages/ui-client/package.json
  packages/ui-client/src/components/EmojiPicker/EmojiPickerPreview.tsx
  packages/web-ui-registration/package.json
  packages/web-ui-registration/src/components/LoginTerms.tsx
Labels: stat: ready to merge, stat: QA assured

#34892 fix: Rocket.cat complains about mongo version
  .changeset/loud-islands-explode.md
  apps/meteor/server/startup/serverRunning.js
Labels: stat: ready to merge, stat: QA assured

#34901 refactor: Invalid values as React nodes
  apps/meteor/client/components/SidebarToggler/SidebarToggler.tsx
  apps/meteor/client/components/SidebarToggler/SidebarTogglerBadge.tsx
  apps/meteor/client/components/SidebarToggler/SidebarTogglerButton.tsx
  apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx
  apps/meteor/client/lib/utils/timeAgo.ts
  apps/meteor/client/omnichannel/additionalForms/BusinessHoursMultiple.tsx
  apps/meteor/client/omnichannel/additionalForms/CustomFieldsAdditionalForm.tsx
  apps/meteor/client/omnichannel/cannedResponses/CannedResponseEdit.tsx
  apps/meteor/client/omnichannel/cannedResponses/components/CannedResponseForm.tsx
  apps/meteor/client/omnichannel/cannedResponses/modals/CreateCannedResponse/CreateCannedResponseModal.tsx
  apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
  apps/meteor/client/sidebar/sections/AirGappedRestrictionBanner/AirGappedRestrictionWarning.tsx
  apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx
  apps/meteor/client/sidebarv2/sections/AirGappedRestrictionBanner/AirGappedRestrictionWarning.tsx
  apps/meteor/client/views/admin/integrations/incoming/EditIncomingWebhook.tsx
  apps/meteor/client/views/admin/integrations/incoming/IncomingWebhookForm.tsx
  apps/meteor/client/views/admin/permissions/EditRolePage.tsx
  apps/meteor/client/views/admin/permissions/RoleForm.tsx
  apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/admin/users/AdminUserFormWithData.tsx
  apps/meteor/client/views/admin/users/AdminUsersPage.tsx
  apps/meteor/client/views/directory/RoomTags.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTable.tsx
  apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTableRow.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTable.tsx
  apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTableRow.tsx
  apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx
  apps/meteor/client/views/omnichannel/customFields/EditCustomFields.tsx
  apps/meteor/client/views/room/Header/DirectRoomHeader.tsx
  apps/meteor/client/views/room/Header/Omnichannel/OmnichannelRoomHeader.tsx
  apps/meteor/client/views/room/Header/RoomHeader.tsx
  apps/meteor/client/views/room/HeaderV2/Omnichannel/OmnichannelRoomHeader.tsx
  apps/meteor/client/views/room/HeaderV2/RoomHeader.tsx
  apps/meteor/client/views/root/MainLayout/LoginPage.tsx
  apps/meteor/definition/IRoomTypeConfig.ts
  packages/i18n/src/locales/en.i18n.json
  packages/livechat/src/routes/Register/index.tsx
  packages/livechat/src/routes/SwitchDepartment/index.tsx
  packages/livechat/tsconfig.json
  packages/web-ui-registration/src/components/LoginSwitchLanguageFooter.tsx
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34849 fix: Inactive Clients Not Refreshing Action Buttons After App Deployment
  .changeset/eleven-pugs-help.md
  apps/meteor/client/hooks/useAppActionButtons.ts
Labels: stat: ready to merge, stat: QA assured

#34864 fix: Allow users to fetch the `packageValue` of settings on `/settings` endpoint
  .changeset/friendly-kings-poke.md
  apps/meteor/app/api/server/v1/settings.ts
  apps/meteor/tests/end-to-end/api/settings.ts
  packages/rest-typings/src/v1/settings.ts
Labels: stat: ready to merge, stat: QA assured

#34900 fix: Room not loading history
  .changeset/good-clouds-brush.md
  apps/meteor/client/views/room/body/hooks/useGetMore.spec.ts
  apps/meteor/client/views/room/body/hooks/useGetMore.ts
Labels: stat: ready to merge, stat: QA assured

#34908 fix: Restore room scroll position
  .changeset/gentle-moons-unite.md
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.spec.ts
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
Labels: stat: ready to merge, stat: QA assured

#34933 fix: Slack Bridge when using multiple slack workspaces
  .changeset/thirty-vans-fry.md
  apps/meteor/package.json
Labels: stat: ready to merge, stat: QA assured

#34931 chore: Change how cron jobs start
  apps/meteor/server/cron/federation.ts
  apps/meteor/server/cron/nps.ts
  apps/meteor/server/cron/oembed.ts
  apps/meteor/server/cron/temporaryUploadsCleanup.ts
  apps/meteor/server/cron/usageReport.ts
  apps/meteor/server/cron/videoConferences.ts
  apps/meteor/server/startup/cron.ts
Labels: stat: ready to merge, stat: QA assured

#34949 regression: Voice Call History not being recorded
  apps/meteor/server/models.ts
  packages/models/src/modelClasses.ts
Labels: stat: ready to merge, stat: QA assured

#34873 fix: SAML login redirects to incorrect room when using an invite
  .changeset/itchy-pumas-laugh.md
  apps/meteor/app/meteor-accounts-saml/server/definition/IServiceProviderOptions.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/ServiceProvider.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/Utils.ts
  apps/meteor/app/meteor-accounts-saml/server/lib/generators/AuthorizeRequest.ts
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/views/invite/InvitePage.tsx
  apps/meteor/client/views/invite/hooks/useSamlInviteToken.ts
  apps/meteor/client/views/root/SAMLLoginRoute.spec.tsx
  apps/meteor/client/views/root/SAMLLoginRoute.tsx
  apps/meteor/tests/e2e/saml.spec.ts
  apps/meteor/tests/unit/app/meteor-accounts-saml/server.tests.ts
Labels: stat: ready to merge, stat: QA assured

#34940 feat: Allow users to force close Omnichannel rooms
  .changeset/eight-humans-sip.md
  apps/meteor/app/lib/server/functions/closeLivechatRoom.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/localTypes.ts
  apps/meteor/server/settings/omnichannel.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/unit/app/lib/server/functions/closeLivechatRoom.tests.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#34927 refactor: Replace `Menu` in favor of `GenericMenu` in RoomMenu
  apps/meteor/client/hooks/menuActions/useLeaveRoom.tsx
  apps/meteor/client/hooks/menuActions/useToggleFavoriteAction.ts
  apps/meteor/client/hooks/menuActions/useToggleReadAction.ts
  apps/meteor/client/hooks/useRoomMenuActions.ts
  apps/meteor/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx
  apps/meteor/client/omnichannel/priorities/PriorityIcon.tsx
  apps/meteor/client/sidebar/Item/Condensed.tsx
  apps/meteor/client/sidebar/Item/Extended.tsx
  apps/meteor/client/sidebar/Item/Medium.tsx
  apps/meteor/client/sidebar/RoomMenu.spec.tsx
  apps/meteor/client/sidebar/RoomMenu.tsx
  apps/meteor/client/sidebarv2/Item/Condensed.tsx
  apps/meteor/client/sidebarv2/Item/Extended.tsx
  apps/meteor/client/sidebarv2/Item/Medium.tsx
  apps/meteor/client/sidebarv2/RoomMenu.tsx
  apps/meteor/client/views/account/profile/ActionConfirmModal.tsx
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/fragments/sidebar.ts
  packages/ui-client/src/components/GenericMenu/GenericMenuItem.tsx
Labels: stat: ready to merge, stat: QA assured

#34891 refactor: remove getReadReceipts method calls (server)
  apps/meteor/ee/server/api/chat.ts
  apps/meteor/ee/server/methods/getReadReceipts.ts
Labels: stat: ready to merge, stat: QA assured

#34850 feat: Room roles visibility in members panel
  .changeset/chilled-beers-run.md
  apps/meteor/client/views/hooks/useMembersList.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/MembersListDivider.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersItem.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#34922 fix: Users without preview permission subscribing to public channel stream
  .changeset/metal-pets-promise.md
  apps/meteor/client/hooks/useJoinRoom.ts
  apps/meteor/client/lib/errors/NotSubscribedToRoomError.ts
  apps/meteor/client/views/room/NotSubscribedRoom.tsx
  apps/meteor/client/views/room/RoomOpener.tsx
  apps/meteor/client/views/room/RoomOpenerEmbedded.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Info/hooks/actions/useRoomLeave.tsx
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  packages/i18n/src/locales/en.i18n.json
Labels: type: bug, stat: ready to merge, stat: QA assured

#34948 feat: add Voice Calls data to statistics
  .changeset/eleven-mails-sort.md
  apps/meteor/app/statistics/server/lib/getEEStatistics.ts
  apps/meteor/app/statistics/server/lib/getVoIPStatistics.ts
  apps/meteor/ee/server/local-services/voip-freeswitch/service.ts
  packages/core-typings/src/IStats.ts
  packages/core-typings/src/voip/IFreeSwitchCall.ts
  packages/model-typings/src/models/IFreeSwitchCallModel.ts
  packages/models/src/models/FreeSwitchCall.ts
Labels: stat: ready to merge, stat: QA assured

#34058 refactor: remove autotranslate internal Meteor methods calls
  apps/meteor/app/api/server/v1/autotranslate.ts
  apps/meteor/app/autotranslate/server/functions/getSupportedLanguages.ts
  apps/meteor/app/autotranslate/server/functions/saveSettings.ts
  apps/meteor/app/autotranslate/server/functions/translateMessage.ts
  apps/meteor/app/autotranslate/server/methods/getSupportedLanguages.ts
  apps/meteor/app/autotranslate/server/methods/saveSettings.ts
  apps/meteor/app/autotranslate/server/methods/translateMessage.ts
Labels: stat: ready to merge, stat: QA assured

#34191 feat: Allow granting the `mobile-upload-file` permission to guests
  .changeset/shiny-singers-cheer.md
  apps/meteor/app/authorization/client/restrictedRoles.ts
  apps/meteor/app/authorization/lib/AuthorizationUtils.ts
  apps/meteor/app/authorization/server/constant/permissions.ts
  apps/meteor/app/authorization/server/methods/addPermissionToRole.ts
  apps/meteor/ee/app/authorization/lib/guestPermissions.ts
  apps/meteor/tests/end-to-end/api/guest-permissions.ts
Labels: stat: ready to merge, stat: QA assured

#34860 fix: Files contextual bar reactivity
  .changeset/nasty-shirts-rule.md
  apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useFilesList.ts
Labels: stat: ready to merge, stat: QA assured

#34920 chore: Improve Transcript service call chain
  apps/meteor/ee/app/livechat-enterprise/server/api/transcript.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/sendPdfTranscriptOnClose.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/requestPdfTranscript.ts
  apps/meteor/tests/unit/server/livechat/lib/requestPdfTranscript.spec.ts
  ee/packages/omnichannel-services/package.json
  ee/packages/omnichannel-services/src/OmnichannelTranscript.spec.ts
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  packages/core-services/src/types/IOmnichannelTranscriptService.ts
Labels: stat: ready to merge, stat: QA assured

#34486 refactor: remove Meteor.call for addAllUserToRoom method (server)
  apps/meteor/app/api/server/v1/channels.ts
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/server/methods/addAllUserToRoom.ts
Labels: stat: ready to merge, stat: QA assured

#34192 refactor: Omnichannel queue processing
  apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
  apps/meteor/server/services/omnichannel/queue.ts
  apps/meteor/tests/unit/server/services/omnichannel/queue.tests.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
  packages/models/src/models/LivechatInquiry.ts
Labels: stat: ready to merge, stat: QA assured

#34935 fix: Retention policy settings migration not running
  .changeset/sour-frogs-return.md
  apps/meteor/server/settings/retention-policy.ts
  apps/meteor/server/startup/migrations/v319.ts
  apps/meteor/server/startup/migrations/xrun.ts
Labels: stat: ready to merge, stat: QA assured

#34939 feat: improve permissions search
  .changeset/popular-stingrays-trade.md
  apps/meteor/client/views/admin/permissions/helpers/mapPermissionKeys.spec.ts
  apps/meteor/client/views/admin/permissions/helpers/mapPermissionKeys.ts
  apps/meteor/client/views/admin/permissions/hooks/useFilteredPermissions.ts
  apps/meteor/client/views/admin/permissions/hooks/usePermissionsAndRoles.ts
Labels: stat: ready to merge, stat: QA assured

#34950 chore: Move `VideoconfContext` to `ui-video-conf`
  apps/meteor/client/contexts/VideoConfContext.ts
  apps/meteor/client/hooks/roomActions/useStartCallRoomAction/useVideoConfMenuOptions.tsx
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/sidebar/RoomList/RoomListRow.tsx
  apps/meteor/client/sidebar/hooks/useRoomList.ts
  apps/meteor/client/sidebarv2/RoomList/RoomListRow.tsx
  apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx
  apps/meteor/client/sidebarv2/hooks/useRoomList.ts
  apps/meteor/client/uikit/hooks/useMessageBlockContextValue.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/IncomingPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/OutgoingPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/StartCallPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/TimedVideoConfPopup.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useVideoCallAction.tsx
  packages/core-typings/src/IVideoConference.ts
  packages/ui-video-conf/package.json
  packages/ui-video-conf/src/VideoConfContext.ts
  packages/ui-video-conf/src/hooks/index.ts
  packages/ui-video-conf/src/hooks/useVideoConfContext.ts
  packages/ui-video-conf/src/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34980 fix: Delete OTR messages on session end
  .changeset/chilled-shirts-smile.md
  apps/meteor/app/otr/client/OTRRoom.ts
Labels: stat: ready to merge, stat: QA assured

#35002 chore(deps): bump `fastxml`-related dependencies
  apps/meteor/package.json
  apps/meteor/server/services/image/service.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35001 chore(deps): bump vite from 5.4.11 to 5.4.14
  apps/uikit-playground/package.json
Labels: stat: ready to merge, stat: QA assured

#35008 refactor: Update `UploadProgressIndicator` styles
  apps/meteor/app/theme/client/imports/general/base_old.css
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/client/views/room/body/ErroredUploadProgressIndicator.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/RoomBodyV2.tsx
  apps/meteor/client/views/room/body/UploadProgress/UploadProgressContainer.tsx
  apps/meteor/client/views/room/body/UploadProgress/UploadProgressIndicator.tsx
  apps/meteor/client/views/room/body/UploadProgress/index.ts
  apps/meteor/client/views/room/body/UploadProgressIndicator.tsx
Labels: stat: ready to merge, stat: QA assured

#35011 fix: increase RSA key size in `FederationKeys.ts`
  packages/models/src/models/FederationKeys.ts
Labels: stat: ready to merge, stat: QA assured

#34958 feat: Make Omnichannel room opening transactional
  .changeset/many-badgers-jam.md
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
Labels: stat: ready to merge, stat: QA assured

#34988 fix: Allow pagination params on `channels.list`
  .changeset/silly-shiny-kiwis.md
  apps/meteor/tests/end-to-end/api/channels.ts
  packages/rest-typings/src/v1/channels/ChannelsListProps.ts
Labels: stat: ready to merge, stat: QA assured

#35010 fix: Prevent invalid sessions update
  .changeset/four-pugs-move.md
  apps/meteor/app/statistics/server/lib/SAUMonitor.ts
  packages/model-typings/src/models/ISessionsModel.ts
  packages/models/src/models/Sessions.ts
Labels: stat: ready to merge, stat: QA assured

#35018 chore: adjust Accessibility page form id
  apps/meteor/client/views/account/accessibility/AccessibilityPage.tsx
Labels: stat: ready to merge, stat: QA assured

#35007 chore(deps): bump dependencies with known issues
  apps/meteor/app/mailer/server/api.ts
  apps/meteor/package.json
  apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
  apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts
  package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34975 fix: stop invalid `Accounts_CustomFieldsToShowInUserInfo` value from breaking the ui
  .changeset/violet-bikes-brake.md
  apps/meteor/client/hooks/useUserCustomFields.spec.tsx
  apps/meteor/client/hooks/useUserCustomFields.ts
  apps/meteor/server/settings/accounts.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#34960 test: flaky feature-preview
  apps/meteor/tests/e2e/feature-preview.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-channels.ts
Labels: stat: ready to merge, stat: QA assured

#35025 test: Wait for hook mutation
  apps/meteor/client/hooks/usePruneWarningMessage.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35026 chore: `GenericModal` dismissing strategy
  apps/meteor/client/components/GenericModal/GenericModal.tsx
  apps/meteor/client/lib/imperativeModal.tsx
  apps/meteor/client/views/admin/subscription/components/cards/AppsUsageCard/AppsUsageCard.spec.tsx
  apps/meteor/client/views/modal/ModalRegion.tsx
Labels: stat: ready to merge, stat: QA assured

#34997 regression: Mentioning users with no messages in room
  apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx
  apps/meteor/client/views/room/composer/hooks/useComposerBoxPopupQueries.ts
  apps/meteor/tests/e2e/message-composer.spec.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
Labels: stat: ready to merge, stat: QA assured

#35004 regression: sorting irregularities in new members list
  apps/meteor/client/views/hooks/useMemberList.spec.tsx
  apps/meteor/client/views/hooks/useMembersList.ts
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx
  apps/meteor/server/lib/findUsersOfRoomOrderedByRole.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
Labels: stat: ready to merge, stat: QA assured

#35043 regression: SVG sanitization of Omnichannel rooms' icons
  apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/provider/OmnichannelRoomIconProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#33992 chore: bump `react-aria`
  apps/meteor/client/sidebar/RoomList/useSidebarListNavigation.ts
  apps/meteor/client/sidebarv2/RoomList/useSidebarListNavigation.ts
  apps/meteor/client/sidebarv2/header/SearchSection.tsx
  apps/meteor/client/views/room/hooks/useMessageListNavigation.ts
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#34978 refactor: remove canned responses method calls (server)
  apps/meteor/ee/app/api-enterprise/server/canned-responses.ts
  apps/meteor/ee/app/canned-responses/server/methods/removeCannedResponse.ts
  apps/meteor/ee/app/canned-responses/server/methods/saveCannedResponse.ts
Labels: stat: ready to merge, stat: QA assured

#35049 test: Minor E2E test adjustments
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/threads.spec.ts
Labels: stat: ready to merge, stat: QA assured

#34987 fix: Allow bot agents to skip the queue
  .changeset/silly-emus-remain.md
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/tests/end-to-end/api/livechat/24-routing.ts
Labels: stat: ready to merge, stat: QA assured

#34996 refactor: remove nexcloud meteor startup & tracker
  apps/meteor/app/nextcloud/client/index.ts
  apps/meteor/app/nextcloud/client/lib.ts
  apps/meteor/app/nextcloud/client/useNextcloud.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35013 feat: filter thread messages in room message query
  .changeset/stupid-rats-work.md
  apps/meteor/app/apps/server/bridges/rooms.ts
  apps/meteor/app/apps/server/converters/messages.js
  packages/apps-engine/src/definition/accessors/IRoomRead.ts
  packages/apps-engine/src/server/accessors/RoomRead.ts
  packages/apps-engine/src/server/bridges/RoomBridge.ts
Labels: stat: ready to merge, stat: QA assured

#34944 chore: Update types of `e2e.room` file
  apps/meteor/app/e2e/client/helper.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.room.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/client/lib/chats/flows/uploadFiles.ts
Labels: stat: ready to merge, stat: QA assured

#33885 chore: prune the token whenever we receieve a 403
  .changeset/rude-adults-shout.md
  apps/meteor/app/push/server/fcm.ts
Labels: stat: ready to merge, stat: QA assured

#35057 chore: Add missing deno-cache directory to output of apps-engine to turbo
  packages/apps-engine/turbo.json
Labels: stat: ready to merge, stat: QA assured

#35009 fix: Wrong marketplaceInfo value being stored in the database
  .changeset/grumpy-lemons-pull.md
  apps/meteor/ee/app/license/server/canEnableApp.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/marketplace/appInfo.ts
  apps/meteor/tests/unit/app/license/server/canEnableApp.spec.ts
  packages/apps-engine/src/server/AppManager.ts
  packages/apps-engine/src/server/managers/AppLicenseManager.ts
  packages/apps-engine/src/server/storage/IAppStorageItem.ts
Labels: stat: ready to merge, stat: QA assured

#35038 fix: encode error messages
  .changeset/small-waves-press.md
  apps/meteor/ee/server/services/ecdh-proxy/lib/server.ts
  packages/livechat/package.json
  packages/livechat/src/components/Composer/index.tsx
Labels: stat: ready to merge, stat: QA assured

#35030 chore: Removes unnecessary query invalidation in `ChatsFilters`
  apps/meteor/client/views/omnichannel/directory/chats/ChatsFiltersContextualBar.tsx
Labels: stat: ready to merge, stat: QA assured

#34889 refactor: remove calls for setEmail Meteor method (server)
  apps/meteor/app/lib/server/methods/setEmail.ts
  apps/meteor/server/methods/saveUserProfile.ts
Labels: stat: ready to merge, stat: QA assured

#34979 refactor: remove messageSearch method calls (server)
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/search/server/methods.ts
  apps/meteor/app/search/server/model/SearchProvider.ts
  apps/meteor/app/search/server/provider/DefaultProvider.ts
  apps/meteor/server/methods/messageSearch.ts
Labels: stat: ready to merge, stat: QA assured

#35065 chore(deps): remove `stylelint-config-rational-order`
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35064 chore(deps): bump meteor http
  apps/meteor/.meteor/versions
Labels: stat: ready to merge, stat: QA assured

#35052 chore(deps): Bump turborepo
  package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35062 chore: Better error messages when failing to install an app from the marketplace
  apps/meteor/ee/server/apps/communication/rest.ts
Labels: stat: ready to merge, stat: QA assured

#35073 test: OmnichannelQueueInactivityMonitor
  apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/QueueInactivityMonitor.spec.ts
Labels: stat: ready to merge, stat: QA assured

#34941 test: Video conference volume setting
  apps/meteor/client/views/account/preferences/PreferencesSoundSection.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/IncomingPopup.tsx
  apps/meteor/tests/e2e/page-objects/account-profile.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
  apps/meteor/tests/e2e/video-conference-ring.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: QA assured
