Repository RocketChat/Rocket.Chat, pull requests merged in 2025-05, with the labels that each got.

#35819 refactor: Convert integrations (api and triggerHandler) to typescript
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/integrations/server/api/api.ts
  apps/meteor/app/integrations/server/lib/ScriptEngine.ts
  apps/meteor/app/integrations/server/lib/definition.ts
  apps/meteor/app/integrations/server/lib/triggerHandler.ts
  apps/meteor/app/integrations/server/methods/outgoing/replayOutgoingIntegration.ts
  apps/meteor/app/integrations/server/startup.ts
  apps/meteor/server/services/meteor/service.ts
  packages/core-typings/src/IIntegrationHistory.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/integrations/hooks/IntegrationHooksAddProps.ts
  packages/rest-typings/src/v1/integrations/hooks/IntegrationHooksRemoveProps.ts
  packages/rest-typings/src/v1/integrations/hooks/index.ts
  packages/rest-typings/src/v1/integrations/index.ts
Labels: stat: ready to merge, stat: QA assured

#35918 regression: jump to message
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/app/ui/client/views/app/lib/scrolling.ts
  apps/meteor/client/lib/utils/legacyJumpToMessage.ts
  apps/meteor/client/views/room/MessageList/hooks/useJumpToMessage.ts
  apps/meteor/client/views/room/MessageList/hooks/useLoadSurroundingMessages.ts
  apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/RoomBodyV2.tsx
  apps/meteor/client/views/room/body/hooks/useGetMore.spec.ts
  apps/meteor/client/views/room/body/hooks/useGetMore.spec.tsx
  apps/meteor/client/views/room/body/hooks/useGetMore.ts
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.spec.ts
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.spec.tsx
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessages.ts
Labels: stat: ready to merge, stat: QA assured

#35930 chore: Change incorrect label tag in `MessageComposerInput`
  packages/ui-composer/src/MessageComposer/MessageComposerInput.tsx
Labels: :accessibility: accessibility, stat: ready to merge, stat: QA assured

#35920 regression: API endpoints query parameter validation not working for nested properties
  apps/meteor/app/api/server/router.spec.ts
  apps/meteor/app/api/server/router.ts
Labels: stat: ready to merge, stat: QA assured

#35933 test: Enhance router tests for request and response validation
  apps/meteor/app/api/server/router.spec.ts
  apps/meteor/app/api/server/router.ts
  apps/meteor/jest.config.ts
Labels: stat: ready to merge, stat: QA assured

#35928 regression: Admin settings with `enableQuery` and `displayQuery` do not react to changes
  apps/meteor/client/views/admin/EditableSettingsContext.spec.tsx
  apps/meteor/client/views/admin/EditableSettingsContext.ts
  apps/meteor/client/views/admin/settings/EditableSettingsProvider.tsx
  apps/meteor/client/views/admin/settings/Setting/Setting.tsx
Labels: stat: ready to merge, stat: QA assured

#35935 regression: Passing `servedBy` instead of `servedBy.id` to `findOne` call when converting a room from app
  apps/meteor/app/apps/server/converters/rooms.js
Labels: stat: ready to merge, stat: QA assured

#35931 chore: meteor to 3.2.2 and node to 22.14
  .github/workflows/ci-deploy-gh-pages.yml
  .github/workflows/ci.yml
  .github/workflows/new-release.yml
  .github/workflows/pr-update-description.yml
  .github/workflows/publish-release.yml
  .github/workflows/release-candidate.yml
  .github/workflows/update-version-durability.yml
  apps/meteor/.docker-mongo/Dockerfile
  apps/meteor/.docker/Dockerfile.alpine
  apps/meteor/.docker/Dockerfile.debian
  apps/meteor/.meteor/packages
  apps/meteor/.meteor/release
  apps/meteor/.meteor/versions
  apps/meteor/ee/server/services/Dockerfile
  ee/apps/account-service/Dockerfile
  ee/apps/authorization-service/Dockerfile
  ee/apps/ddp-streamer/Dockerfile
  ee/apps/omnichannel-transcript/Dockerfile
  ee/apps/presence-service/Dockerfile
  ee/apps/queue-worker/Dockerfile
  ee/apps/stream-hub-service/Dockerfile
  package.json
Labels: stat: ready to merge, stat: QA assured

#35937 chore: fix enhance forwarded IPs in `getRemoteAddress` function
  apps/meteor/app/api/server/middlewares/remoteAddressMiddleware.spec.ts
  apps/meteor/app/api/server/middlewares/remoteAddressMiddleware.ts
Labels: stat: ready to merge, stat: QA assured

#35854 chore: Remove some omnichannel tech debt -2
  apps/meteor/app/livechat/imports/server/rest/departments.ts
  apps/meteor/app/livechat/server/api/lib/livechat.ts
  apps/meteor/app/livechat/server/api/v1/config.ts
  apps/meteor/app/livechat/server/api/v1/room.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/departmentsLib.ts
  apps/meteor/app/livechat/server/lib/omni-users.ts
  apps/meteor/app/livechat/server/methods/saveAgentInfo.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onCheckRoomParamsApi.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadConfigApi.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/query.helper.js
  apps/meteor/ee/app/livechat-enterprise/server/methods/addMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/removeMonitor.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/removeTag.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/removeUnit.ts
  apps/meteor/ee/app/livechat-enterprise/server/methods/saveTag.ts
  apps/meteor/ee/app/livechat-enterprise/server/startup.ts
  apps/meteor/ee/server/models/raw/LivechatDepartment.ts
  apps/meteor/ee/server/models/raw/LivechatTag.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/server/services/omnichannel-analytics/AgentData.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
  packages/model-typings/src/models/ILivechatTagModel.ts
  packages/model-typings/src/models/IUsersModel.ts
  packages/models/src/models/LivechatDepartment.ts
  packages/models/src/models/Users.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#35809 chore: Improve PDF Transcript request lock mechanism
  apps/meteor/app/statistics/server/lib/getEEStatistics.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/transcript.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/requestPdfTranscript.ts
  apps/meteor/ee/server/models/raw/LivechatRooms.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  apps/meteor/tests/unit/server/livechat/lib/requestPdfTranscript.spec.ts
  ee/packages/omnichannel-services/src/OmnichannelTranscript.spec.ts
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  packages/core-typings/src/IRoom.ts
  packages/model-typings/src/models/ILivechatRoomsModel.ts
  packages/models/src/models/LivechatRooms.ts
Labels: stat: ready to merge, stat: QA assured

#35932 test: Adopt jest testing in `ui-composer`
  packages/ui-composer/.storybook/main.ts
  packages/ui-composer/jest.config.ts
  packages/ui-composer/package.json
  packages/ui-composer/src/MessageComposer/MessageComposer.spec.tsx
  packages/ui-composer/src/MessageComposer/MessageComposer.stories.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerHint.spec.tsx
  packages/ui-composer/src/MessageComposer/MessageComposerHint.stories.tsx
  packages/ui-composer/src/MessageComposer/__snapshots__/MessageComposer.spec.tsx.snap
  packages/ui-composer/src/MessageComposer/__snapshots__/MessageComposerHint.spec.tsx.snap
  packages/ui-composer/src/MessageFooterCallout/MessageFooterCallout.spec.tsx
  packages/ui-composer/src/MessageFooterCallout/MessageFooterCallout.stories.tsx
  packages/ui-composer/src/MessageFooterCallout/__snapshots__/MessageFooterCallout.spec.tsx.snap
  packages/ui-composer/tsconfig.build.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35944 refactor: Use patch functions for `checkDefaultAgentOnNewroom` callback
  apps/meteor/app/livechat/server/lib/hooks.ts
  apps/meteor/app/livechat/server/lib/rooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA assured

#35948 regression: `Cannot read properties of undefined` when running `request.route.includes`
  apps/meteor/app/api/server/helpers/parseJsonQuery.ts
Labels: stat: ready to merge, stat: QA assured

#35950 regression: solve restore position on same room types
  apps/meteor/client/hooks/useMergedRefsV2.ts
  apps/meteor/client/views/room/MessageList/hooks/useJumpToMessage.ts
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/RoomBodyV2.tsx
  apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
Labels: stat: ready to merge, stat: QA assured

#35864 fix: OAuth login buttons not showing up
  .changeset/shy-dolls-protect.md
  apps/meteor/app/apple/client/index.ts
  apps/meteor/app/custom-oauth/client/CustomOAuth.ts
  apps/meteor/app/dolphin/client/hooks/useDolphin.ts
  apps/meteor/app/drupal/client/hooks/useDrupal.ts
  apps/meteor/app/github-enterprise/client/hooks/useGitHubEnterpriseAuth.ts
  apps/meteor/app/gitlab/client/hooks/useGitLabAuth.ts
  apps/meteor/app/nextcloud/client/useNextcloud.ts
  apps/meteor/app/tokenpass/client/hooks/useTokenPassAuth.tsx
  apps/meteor/client/lib/loginServices.ts
  apps/meteor/client/sidebar/hooks/useCustomOAuth.ts
  apps/meteor/client/views/root/hooks/useWordPressOAuth.ts
  apps/meteor/definition/externals/meteor/accounts-base.d.ts
Labels: stat: QA assured

#35839 fix: upload of malformed jpegs with Message_Attachments_Strip_Exif disabled fails silently
  .changeset/rare-mails-whisper.md
  apps/meteor/client/lib/chats/uploads.ts
  apps/meteor/client/views/room/body/UploadProgress/UploadProgressIndicator.tsx
  apps/meteor/tests/e2e/fixtures/files/bad-orientation.jpeg
  apps/meteor/tests/e2e/image-upload.spec.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35828 fix: new user not moving from Pending to Deactivated tab in admin UI
  .changeset/fuzzy-gifts-move.md
  apps/meteor/client/views/admin/users/hooks/useFilteredUsers.ts
  apps/meteor/tests/e2e/admin-users.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35921 refactor: remove add oauth service meteor call
  apps/meteor/app/api/server/v1/settings.ts
  apps/meteor/app/lib/server/methods/addOAuthService.ts
Labels: stat: ready to merge, stat: QA assured

#35949 refactor: Remove `beforeDelegateAgent` callback
  apps/meteor/app/livechat/server/hooks/beforeDelegateAgent.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/livechat/server/lib/hooks.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA assured

#35957 refactor: Remove `beforeRoom` callback
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/hooks.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewRoom.ts
  apps/meteor/lib/callbacks.ts
  apps/meteor/tests/unit/server/livechat/hooks/beforeNewRoom.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35958 refactor: Remove `livechat.newRoom` callback
  apps/meteor/app/livechat/server/hooks/saveContactLastChat.ts
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/index.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/hooks.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/addDepartmentAncestors.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA assured

#35953 chore: Removed unnecessary aria props in `CreateChannelModal`
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
Labels: :accessibility: accessibility, stat: ready to merge, stat: QA assured

#35600 fix: Don't allow OTR message editing
  .changeset/hungry-games-smoke.md
  apps/meteor/app/ui/client/lib/ChatMessages.ts
  apps/meteor/client/components/message/toolbar/useEditMessageAction.ts
  apps/meteor/client/components/message/variants/RoomMessage.tsx
  apps/meteor/client/components/message/variants/ThreadMessagePreview.tsx
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/lib/chats/data.ts
  apps/meteor/client/lib/chats/flows/sendMessage.ts
  apps/meteor/client/lib/onClientBeforeSendMessage.ts
  apps/meteor/client/views/root/hooks/useOTRMessaging.ts
  apps/meteor/tests/e2e/otr.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35815 fix: Owner change modal not showing content as expected
  .changeset/loud-chairs-accept.md
  apps/meteor/client/components/ConfirmOwnerChangeModal.tsx
  apps/meteor/tests/e2e/administration.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/admin-flextab-users.ts
  packages/i18n/src/locales/ar.i18n.json
  packages/i18n/src/locales/bn-IN.i18n.json
  packages/i18n/src/locales/ca.i18n.json
  packages/i18n/src/locales/cs.i18n.json
  packages/i18n/src/locales/da.i18n.json
  packages/i18n/src/locales/de.i18n.json
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/es.i18n.json
  packages/i18n/src/locales/fi.i18n.json
  packages/i18n/src/locales/fr.i18n.json
  packages/i18n/src/locales/gl.i18n.json
  packages/i18n/src/locales/hi-IN.i18n.json
  packages/i18n/src/locales/hu.i18n.json
  packages/i18n/src/locales/it.i18n.json
  packages/i18n/src/locales/ja.i18n.json
  packages/i18n/src/locales/ka-GE.i18n.json
  packages/i18n/src/locales/km.i18n.json
  packages/i18n/src/locales/ko.i18n.json
  packages/i18n/src/locales/lo.i18n.json
  packages/i18n/src/locales/lt.i18n.json
  packages/i18n/src/locales/nb.i18n.json
  packages/i18n/src/locales/nl.i18n.json
  packages/i18n/src/locales/nn.i18n.json
  packages/i18n/src/locales/pa-IN.i18n.json
  packages/i18n/src/locales/pl.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
  packages/i18n/src/locales/pt.i18n.json
  packages/i18n/src/locales/ru.i18n.json
  packages/i18n/src/locales/sv.i18n.json
  packages/i18n/src/locales/uk.i18n.json
  packages/i18n/src/locales/vi-VN.i18n.json
  packages/i18n/src/locales/zh-TW.i18n.json
  packages/i18n/src/locales/zh.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35970 refactor: Remove `afterTakeInquiry` callback
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
  apps/meteor/app/livechat/server/lib/hooks.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTakeInquiry.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/autoCloseQueued.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA assured

#35973 refactor: Remove `afterInquiryQueued` callback
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/hooks.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/afterInquiryQueued.ts
  apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/hooks/afterInquiryQueued.spec.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA assured

#35990 refactor: Remove `livechat.roomQueued` callback
  apps/meteor/app/livechat/server/hooks/sendToCRM.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/app/livechat/server/lib/hooks.ts
  apps/meteor/lib/callbacks.ts
Labels: stat: ready to merge, stat: QA assured

#35956 chore: Update API to use 'route' instead of 'path'
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/api/server/helpers/parseJsonQuery.ts
  apps/meteor/app/api/server/router.ts
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/app/api/server/v1/roles.ts
  apps/meteor/ee/server/api/engagementDashboard/channels.ts
  apps/meteor/ee/server/apps/communication/rest.ts
Labels: stat: ready to merge, stat: QA assured

#35976 fix: change site url breaks `meteor_runtime_config`
  .changeset/curly-teachers-sort.md
  apps/meteor/app/cors/server/cors.ts
  apps/meteor/server/configuration/configureBoilerplate.ts
  apps/meteor/tests/end-to-end/api/cors.ts
Labels: stat: ready to merge, stat: QA assured

#35981 chore: deprecates dbWatchers and set default value to false
  .changeset/cuddly-feet-clap.md
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
  packages/models/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#35961 chore!: remove mongo 5/6 support
  .changeset/gold-keys-compare.md
  .github/workflows/ci-test-e2e.yml
  .github/workflows/ci.yml
  apps/meteor/server/startup/serverRunning.js
Labels: stat: ready to merge, stat: QA assured

#35996 feat: differentiate between pruning messages and files
  .changeset/khaki-donkeys-wink.md
  apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.tsx
  apps/meteor/tests/e2e/prune-messages.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35959 fix: Air-gapped warning period ignored during daily checks
  .changeset/tender-goats-cross.md
  apps/meteor/jest.config.ts
  apps/meteor/server/cron/usageReport.spec.ts
  apps/meteor/server/cron/usageReport.ts
Labels: stat: ready to merge, stat: QA assured

#35946 fix: message search fails for file descriptions or title containing non-ASCII characters
  .changeset/popular-cameras-guess.md
  apps/meteor/server/lib/parseMessageSearchQuery.ts
  apps/meteor/tests/unit/server/lib/parseMessageSearchQuery.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35797 fix: cleanRoomHistory with filesOnly=true removes all attachments including quotes
  .changeset/thirty-carrots-decide.md
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/tests/end-to-end/api/rooms.ts
  packages/model-typings/src/models/IMessagesModel.ts
  packages/models/src/models/Messages.ts
Labels: stat: ready to merge, stat: QA assured

#36009 fix: buffer as response from API
  .changeset/polite-islands-try.md
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/api/server/middlewares/honoAdapter.ts
  apps/meteor/app/api/server/router.spec.ts
  apps/meteor/ee/server/apps/communication/rest.ts
Labels: stat: ready to merge, stat: QA assured

#36006 fix: Add loading state recovery over `RoomHistoryManager.getMore`
  .changeset/old-rats-ring.md
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
Labels: stat: ready to merge, stat: QA assured

#35991 i18n: Rephrased Current Chat's page deprecation warning
  apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
  packages/i18n/src/locales/en.i18n.json
  packages/i18n/src/locales/nb.i18n.json
  packages/i18n/src/locales/nn.i18n.json
  packages/i18n/src/locales/pt-BR.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35927 fix: character escaping in channel description notifications
  .changeset/selfish-bulldogs-fold.md
  apps/meteor/app/livechat/lib/messageTypes.ts
  apps/meteor/client/components/message/variants/SystemMessage.spec.tsx
  apps/meteor/client/startup/messageTypes.ts
  ee/packages/omnichannel-services/src/livechatSystemMessages.ts
Labels: stat: ready to merge, stat: QA assured

#32917 fix: External links without target not being modified
  .changeset/serious-trees-whisper.md
  apps/meteor/client/components/MarkdownText.spec.tsx
  apps/meteor/client/components/MarkdownText.tsx
  apps/meteor/client/views/admin/settings/Setting/Setting.tsx
Labels: stat: ready to merge, stat: QA assured

#35963 fix: Parsing emojis inside code blocks in attachment content using `chat.postMessage` API call
  .changeset/curly-weeks-talk.md
  apps/meteor/app/emoji/client/emojiParser.ts
  apps/meteor/client/components/message/content/attachments/structure/AttachmentText.tsx
  apps/meteor/tests/e2e/messaging.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35873 refactor: Omnichannel's agent autocompletes to useInfiniteQuery
  apps/meteor/client/components/AutoCompleteAgent.tsx
  apps/meteor/client/components/AutoCompleteAgentWithoutExtension.tsx
  apps/meteor/client/components/AutoCompleteMultipleAgent.tsx
  apps/meteor/client/components/Omnichannel/hooks/useAgentsList.spec.ts
  apps/meteor/client/components/Omnichannel/hooks/useAgentsList.ts
  apps/meteor/client/components/Omnichannel/hooks/useAvailableAgentsList.spec.ts
  apps/meteor/client/components/Omnichannel/hooks/useAvailableAgentsList.ts
  apps/meteor/tests/mocks/data.ts
Labels: stat: ready to merge, stat: QA assured

#36014 fix: Restore native scrollbar color
  .changeset/famous-shirts-run.md
  apps/meteor/app/theme/client/imports/general/theme_old.css
  apps/meteor/app/theme/client/imports/general/variables.css
Labels: stat: ready to merge, stat: QA assured

#35874 refactor: Omnichannel's tag autocompletes to useInfiniteQuery
  apps/meteor/client/components/Omnichannel/hooks/useTagsList.spec.ts
  apps/meteor/client/components/Omnichannel/hooks/useTagsList.ts
  apps/meteor/client/hooks/useTagsList.ts
  apps/meteor/client/omnichannel/tags/AutoCompleteTagsMultiple.tsx
  apps/meteor/tests/mocks/data.ts
Labels: stat: QA assured

#35875 refactor: Omnichannel's unit autocompletes to useInfiniteQuery
  apps/meteor/client/components/Omnichannel/hooks/useUnitsList.spec.ts
  apps/meteor/client/components/Omnichannel/hooks/useUnitsList.ts
  apps/meteor/client/omnichannel/additionalForms/AutoCompleteUnit.tsx
  apps/meteor/client/omnichannel/additionalForms/AutoCompleteUnits.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/tests/mocks/data.ts
Labels: stat: QA assured

#35871 refactor: Omnichannel's department autocompletes to useInfiniteQuery
  apps/meteor/client/components/AutoCompleteDepartment.tsx
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx
  apps/meteor/client/components/Omnichannel/hooks/useDepartmentsList.spec.ts
  apps/meteor/client/components/Omnichannel/hooks/useDepartmentsList.ts
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/components/Omnichannel/utils/normalizeDepartments.ts
  apps/meteor/client/omnichannel/additionalForms/BusinessHoursMultiple.tsx
  apps/meteor/client/omnichannel/additionalForms/DepartmentForwarding.tsx
  apps/meteor/client/omnichannel/units/UnitEdit.tsx
  apps/meteor/client/views/hooks/useDepartmentsByUnitsList.ts
  apps/meteor/client/views/omnichannel/additionalForms.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-business-hours.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-tags.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-business-hours.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-tags.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-units.ts
  apps/meteor/tests/mocks/data.ts
Labels: stat: ready to merge, stat: QA assured

#35876 refactor: Omnichannel's monitor autocompletes to useInfiniteQuery
  apps/meteor/client/components/AutoCompleteMonitors.tsx
  apps/meteor/client/components/Omnichannel/hooks/useMonitorsList.spec.ts
  apps/meteor/client/components/Omnichannel/hooks/useMonitorsList.ts
  apps/meteor/client/omnichannel/units/UnitEdit.tsx
  apps/meteor/client/views/hooks/useMonitorsList.ts
  apps/meteor/tests/mocks/data.ts
Labels: stat: ready to merge, stat: QA assured

#36008 chore: bump fuselage packages
  apps/meteor/ee/server/services/package.json
  apps/meteor/package.json
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/page-objects/fragments/navbar.ts
  apps/uikit-playground/package.json
  ee/packages/ui-theming/package.json
  packages/core-services/package.json
  packages/core-typings/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-kit/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35905 fix: file deletion called twice and ignoring errors with FileSystem storage type
  .changeset/young-ants-applaud.md
  apps/meteor/.mocharc.js
  apps/meteor/server/ufs/ufs-local.spec.ts
  apps/meteor/server/ufs/ufs-local.ts
  apps/meteor/server/ufs/ufs-store.ts
Labels: stat: ready to merge, stat: QA assured

#36027 fix: `audit.settings` endpoint filtering by actor returning empty results
  .changeset/pink-balloons-glow.md
  apps/meteor/ee/server/api/audit.ts
  apps/meteor/tests/end-to-end/api/settings.ts
Labels: stat: ready to merge, stat: QA assured

#35994 refactor: Change composer height `oninput` instead of using a shadow element
  apps/meteor/client/views/room/composer/RoomComposer/hooks/useAutoGrow.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
Labels: stat: ready to merge, stat: QA assured

#36019 fix: Contact conflict resolution
  .changeset/wise-jokes-deliver.md
  apps/meteor/app/livechat/server/api/v1/contact.ts
  apps/meteor/app/livechat/server/lib/contacts/resolveContactConflicts.spec.ts
  apps/meteor/app/livechat/server/lib/contacts/resolveContactConflicts.ts
  apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ReviewContactModal.tsx
  apps/meteor/client/views/omnichannel/contactInfo/hooks/useReviewContact.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-conflict-review.spec.ts
  apps/meteor/tests/end-to-end/api/livechat/contacts.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#36007 fix: remove apps-engine dependency on internal package
  .changeset/stale-walls-move.md
  apps/meteor/ee/server/apps/storage/AppRealStorage.ts
  packages/apps-engine/package.json
  packages/apps-engine/src/server/AppManager.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#36017 refactor: Remove dependency on translation service from transcript service
  apps/meteor/server/services/startup.ts
  ee/apps/omnichannel-transcript/Dockerfile
  ee/apps/omnichannel-transcript/package.json
  ee/apps/omnichannel-transcript/src/i18n.ts
  ee/apps/omnichannel-transcript/src/service.ts
  ee/packages/omnichannel-services/jest.config.ts
  ee/packages/omnichannel-services/package.json
  ee/packages/omnichannel-services/src/OmnichannelTranscript.fixtures.ts
  ee/packages/omnichannel-services/src/OmnichannelTranscript.spec.ts
  ee/packages/omnichannel-services/src/OmnichannelTranscript.ts
  ee/packages/omnichannel-services/src/localTypes.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35416 feat: improve apps logs
  .changeset/rich-peas-worry.md
  .changeset/short-mayflies-sing.md
  apps/meteor/client/views/marketplace/hooks/useLogs.ts
  apps/meteor/ee/server/apps/communication/endpoints/actionButtonsHandler.ts
  apps/meteor/ee/server/apps/communication/endpoints/appGeneralLogsHandler.ts
  apps/meteor/ee/server/apps/communication/endpoints/appLogsHandler.ts
  apps/meteor/ee/server/apps/communication/endpoints/appsCountHandler.ts
  apps/meteor/ee/server/apps/communication/endpoints/lib/makeAppLogsQuery.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/storage/AppRealLogStorage.ts
  apps/meteor/ee/tests/unit/server/apps/endpoints/lib/makeAppLogsQuery.spec.ts
  apps/meteor/tests/end-to-end/apps/app-logs.ts
  packages/apps-engine/src/server/storage/AppLogStorage.ts
  packages/apps-engine/tests/test-data/storage/logStorage.ts
  packages/models/src/models/AppLogsModel.ts
  packages/rest-typings/src/apps/appLogsProps.ts
  packages/rest-typings/src/apps/index.ts
  packages/rest-typings/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#35468 fix: Composer Popup doesn't scroll results
  .changeset/calm-jobs-relax.md
  apps/meteor/client/views/room/composer/ComposerBoxPopup.tsx
Labels: stat: ready to merge, stat: QA assured

#35929 fix: Made the tags in aria describedby to be consistent with rendered tags.
  apps/meteor/client/views/account/security/ChangePassword.tsx
  packages/ui-client/src/components/PasswordVerifier/PasswordVerifier.tsx
Labels: stat: ready to merge, stat: QA assured

#36045 test(e2e-encryption): dismiss toast to prevent slow run
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
Labels: stat: ready to merge, stat: QA assured

#36004 fix: threadList showing errors as `[object, object]`
  .changeset/sour-pianos-glow.md
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.spec.tsx
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
Labels: stat: ready to merge, stat: QA assured

#36029 fix: AutoCompleteDepartmentMultiple `withCheckbox` property not working
  .changeset/rotten-pianos-serve.md
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.spec.tsx
  apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx
  apps/meteor/client/omnichannel/additionalForms/BusinessHoursMultiple.tsx
  apps/meteor/client/omnichannel/tags/TagEdit.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatsFiltersContextualBar.tsx
Labels: stat: ready to merge, stat: QA assured

#36036 fix: add notification on setting changes for Deployment FingerPrint
  apps/meteor/server/services/settings/service.ts
  apps/meteor/server/settings/misc.ts
Labels: stat: ready to merge, stat: QA assured

#36056 refactor: Remove translation service
  apps/meteor/server/services/startup.ts
  apps/meteor/server/services/translation/service.ts
  packages/core-services/src/index.ts
  packages/core-services/src/types/ITranslationService.ts
Labels: stat: ready to merge, stat: QA assured

#36061 chore(deps): bump `turbo` from `2.3.4` to `2.5.3`
  package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#36063 regression: Broken links in the UI when multiple links are used
  apps/meteor/client/components/MarkdownText.spec.tsx
  apps/meteor/client/components/MarkdownText.tsx
Labels: stat: ready to merge, stat: QA assured

#36068 fix: `x-www-form-urlencoded` support on bodyParams
  .changeset/odd-beds-dream.md
  apps/meteor/app/api/server/router.ts
  apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
Labels: stat: ready to merge, stat: QA assured

#36070 fix: prometheus' REST API metrics
  .changeset/silent-shoes-repeat.md
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/middlewares/metrics.spec.ts
  apps/meteor/app/api/server/middlewares/metrics.ts
Labels: stat: ready to merge, stat: QA assured

#36001 refactor: remove `unread` from Meteor
  apps/meteor/client/hooks/useUnread.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/unread.ts
  apps/meteor/client/views/root/MainLayout/LoggedInArea.tsx
Labels: stat: ready to merge, stat: QA assured

#35945 refactor: remove `rootUrlChange` from meteor
  apps/meteor/client/components/FingerprintChangeModalConfirmation.tsx
  apps/meteor/client/hooks/useFingerprintChange.tsx
  apps/meteor/client/hooks/useRootUrlChange.tsx
  apps/meteor/client/hooks/useTwoFactorAuthSetupCheck.tsx
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/rootUrlChange.ts
  apps/meteor/client/views/root/MainLayout/LoggedInArea.tsx
  apps/meteor/client/views/root/MainLayout/TwoFactorAuthSetupCheck.tsx
  packages/i18n/src/locales/en.i18n.json
Labels: stat: QA assured

#36077 regression: Twilio failing signature check
  apps/meteor/app/livechat/imports/server/rest/sms.ts
  apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts
  apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts
  apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts
  apps/meteor/tests/unit/server/services/omnichannel-integrations/providers/twilio.spec.ts
  packages/core-typings/src/omnichannel/sms.ts
Labels: stat: ready to merge, stat: QA assured

#36085 fix: CORS headers incorrectly set for GET
  .changeset/fuzzy-bottles-unite.md
  apps/meteor/app/api/server/middlewares/cors.spec.ts
  apps/meteor/app/api/server/middlewares/cors.ts
Labels: stat: ready to merge, stat: QA assured

#36086 regression: Dragging the VoIP popup handle with right click keeps moving the element after release
  packages/ui-voip/src/components/VoipPopupDraggable/DraggableCore.ts
  packages/ui-voip/src/components/VoipPopupDraggable/useDraggable.stories.tsx
Labels: stat: QA assured

#36038 fix: AgentEdit departments field not being paginated
  .changeset/chilled-windows-divide.md
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEditWithData.tsx
  apps/meteor/client/views/omnichannel/agents/hooks/useRemoveAgent.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
Labels: stat: ready to merge, stat: QA assured

#36096 chore: Replace outdated `Link` in `LoginPoweredBy`
  packages/web-ui-registration/src/components/LoginPoweredBy.tsx
Labels: stat: ready to merge, stat: QA assured

#36107 ci: merge release branch to master on "cut" action
  packages/release-action/src/publishRelease.ts
Labels: stat: ready to merge, stat: QA assured

#36097 fix: `contact.conflictingFields` being updated with nullish values
  .changeset/four-parents-hide.md
  apps/meteor/app/livechat/server/lib/custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
  apps/meteor/tests/unit/app/livechat/server/lib/custom-fields.spec.ts
Labels: stat: ready to merge, stat: QA assured

#36067 feat: Add Pagination to App logs page
  .changeset/red-cherries-grin.md
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogs.tsx
  apps/meteor/client/views/marketplace/hooks/useLogs.ts
Labels: stat: ready to merge, stat: QA assured
