Repository RocketChat/Rocket.Chat, pull requests merged in 2025-07, with the labels that each got.

#36135 refactor: remove computation from LegacyRoomManager
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/client/lib/RoomManager.ts
  apps/meteor/client/lib/chats/readStateManager.ts
  apps/meteor/client/views/room/RoomOpenerEmbedded.tsx
  apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
  apps/meteor/client/views/room/composer/ComposerMessage.tsx
Labels: stat: ready to merge, stat: QA assured

#36331 regression: unread banner appears for thread messages after channel creation
  apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
  apps/meteor/tests/e2e/threads.spec.ts
Labels: stat: ready to merge, stat: QA assured

#36347 refactor: GenericUpsellModal to use GenericModal
  apps/meteor/client/components/GenericModal/GenericModal.tsx
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.spec.tsx
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.stories.tsx
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.tsx
  apps/meteor/client/components/GenericUpsellModal/__snapshots__/GenericUpsellModal.spec.tsx.snap
  apps/meteor/client/components/UpsellModal.stories.tsx
Labels: stat: ready to merge, stat: QA assured

#36311 test: improve the current tests for embedded layout
  apps/meteor/tests/e2e/embedded-layout.spec.ts
Labels: stat: ready to merge, stat: QA assured

#36338 fix: stale data after login expired
  .changeset/spotty-days-complain.md
  apps/meteor/client/lib/userData.ts
  apps/meteor/tests/e2e/account-login.spec.ts
Labels: stat: ready to merge, stat: QA assured

#36346 fix: properly throw error objects to apps on runtime
  .changeset/weak-cobras-fry.md
  packages/apps-engine/deno-runtime/lib/accessors/formatResponseErrorHandler.ts
  packages/apps-engine/deno-runtime/lib/accessors/http.ts
  packages/apps-engine/deno-runtime/lib/accessors/mod.ts
  packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyCreator.ts
  packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyExtender.ts
  packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyUpdater.ts
  packages/apps-engine/deno-runtime/lib/accessors/notifier.ts
  packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyCreator.test.ts
  packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyExtender.test.ts
  packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyUpdater.test.ts
  packages/apps-engine/deno-runtime/lib/accessors/tests/formatResponseErrorHandler.test.ts
  packages/apps-engine/deno-runtime/lib/accessors/tests/http.test.ts
  packages/apps-engine/deno-runtime/lib/roomFactory.ts
Labels: stat: ready to merge, stat: QA assured

#36358 chore: remove index name to prevent warnings
  packages/models/src/models/AppLogsModel.ts
Labels: stat: ready to merge, stat: QA assured

#36345 fix: Contact custom fields not being updated properly
  .changeset/mean-roses-shout.md
  apps/meteor/app/livechat/server/api/v1/customField.ts
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
  apps/meteor/tests/unit/app/livechat/server/lib/custom-fields.spec.ts
  packages/model-typings/src/models/ILivechatVisitorsModel.ts
  packages/models/src/models/LivechatVisitors.ts
Labels: stat: ready to merge, stat: QA assured

#36357 refactor: Set multiple visitor custom fields at once instead of one by one on `custom.fields` endpoint
  apps/meteor/app/livechat/server/api/v1/customField.ts
  apps/meteor/app/livechat/server/api/v1/visitor.ts
  apps/meteor/app/livechat/server/lib/custom-fields.ts
  apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
Labels: stat: ready to merge, stat: QA assured

#36333 feat: Added imgAlt, imgWidth and imgHeight props to GenericUpsellModal
  .changeset/hot-guests-itch.md
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.spec.tsx
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.stories.tsx
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.tsx
  apps/meteor/client/components/GenericUpsellModal/__snapshots__/GenericUpsellModal.spec.tsx.snap
Labels: stat: ready to merge, stat: QA assured

#36382 chore(eslint): Relax naming convention for Storybook's `Story` parameter
  apps/meteor/.eslintrc.json
  apps/meteor/client/views/audit/components/AppInfoField.spec.tsx
  apps/meteor/client/views/audit/components/SecurityLogDisplayModal.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogsItem.spec.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.spec.tsx
  ee/packages/pdf-worker/.storybook/preview.tsx
  packages/eslint-config/standard/index.js
  packages/gazzodown/src/Markup.stories.tsx
  packages/storybook-config/src/preview.tsx
  packages/ui-composer/.storybook/preview.tsx
  packages/ui-video-conf/.storybook/preview.tsx
  packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.stories.tsx
  packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.stories.tsx
  packages/ui-voip/src/components/VoipActionButton/VoipActionButton.stories.tsx
  packages/ui-voip/src/components/VoipActions/VoipActions.stories.tsx
  packages/ui-voip/src/components/VoipContactId/VoipContactId.stories.tsx
  packages/ui-voip/src/components/VoipDialPad/VoipDialPad.stories.tsx
  packages/ui-voip/src/components/VoipPopup/VoipPopup.stories.tsx
Labels: stat: ready to merge, stat: QA assured

#36385 fix: `executeSaveUserProfile` does not trigger username stream
  .changeset/angry-years-learn.md
  apps/meteor/app/lib/server/functions/setUsername.ts
  apps/meteor/server/methods/saveUserProfile.ts
Labels: stat: ready to merge, stat: QA assured

#36377 feat: Outbound Comms endpoints
  .changeset/new-mails-rhyme.md
  apps/meteor/client/views/omnichannel/contactInfo/tabs/ContactInfoDetails/ContactInfoDetailsGroup.tsx
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/outbound.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/outbound.ts
  apps/meteor/ee/app/livechat-enterprise/server/outboundcomms/rest.ts
  apps/meteor/server/lib/OutboundMessageProvider.ts
  apps/meteor/tests/unit/app/livechat/server/outbound/outbound.spec.ts
  apps/meteor/tests/unit/server/lib/OutboundMessageProvider.spec.ts
  packages/apps-engine/src/definition/outboundComunication/IOutboundCommsProvider.ts
  packages/core-typings/src/omnichannel/outbound.ts
Labels: stat: ready to merge, stat: QA assured

#36381 fix: redirect on required password change
  .changeset/stupid-fishes-turn.md
  apps/meteor/server/methods/setUserPassword.ts
  apps/meteor/tests/e2e/user-required-password-change.spec.ts
  apps/meteor/tests/e2e/utils/user-helpers.ts
  packages/ui-contexts/src/hooks/useMethod.ts
Labels: stat: ready to merge, stat: QA assured

#36388 refactor: Enhance API type definitions for route extraction
  apps/meteor/app/api/server/ApiClass.ts
  apps/meteor/app/api/server/definition.ts
Labels: stat: ready to merge, stat: QA assured

#36351 test: automate various quote operations
  apps/meteor/client/views/room/composer/messageBox/MessageBoxReply.tsx
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/quote-messages.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#36396 chore: Remove references to deprecated `Modal.*` components
  apps/meteor/app/livechat-enterprise/client/components/modals/PlaceChatOnHoldModal.tsx
  apps/meteor/client/NavBarV2/NavBarPagesGroup/actions/CreateChannelModal.tsx
  apps/meteor/client/NavBarV2/NavBarPagesGroup/actions/CreateDirectMessage.tsx
  apps/meteor/client/NavBarV2/NavBarPagesGroup/actions/CreateTeamModal.tsx
  apps/meteor/client/NavBarV2/NavBarSettingsToolbar/UserMenu/EditStatusModal.tsx
  apps/meteor/client/components/Backdrop.tsx
  apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx
  apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.tsx
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/EnterpriseDepartmentsModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
  apps/meteor/client/components/Omnichannel/modals/ReturnChatQueueModal.tsx
  apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx
  apps/meteor/client/components/WarningModal.tsx
  apps/meteor/client/sidebar/header/CreateChannel/CreateChannelModal.tsx
  apps/meteor/client/sidebar/header/CreateDirectMessage.tsx
  apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx
  apps/meteor/client/sidebar/header/EditStatusModal.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationManageServerModal.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/MatrixFederationSearch.tsx
  apps/meteor/client/sidebarv2/header/MatrixFederationSearch/MatrixFederationManageServerModal.tsx
  apps/meteor/client/sidebarv2/header/MatrixFederationSearch/MatrixFederationSearch.tsx
  apps/meteor/client/views/account/preferences/MyDataModal.tsx
  apps/meteor/client/views/admin/settings/groups/VoipGroupPage/AssignAgentModal.tsx
  apps/meteor/client/views/admin/users/voip/AssignExtensionModal.tsx
  apps/meteor/client/views/admin/users/voip/RemoveExtensionModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepOneModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceSetupModal/RegisterWorkspaceSetupStepTwoModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisterWorkspaceTokenModal.tsx
  apps/meteor/client/views/admin/workspace/VersionCard/modals/RegisteredWorkspaceModal.tsx
  apps/meteor/client/views/marketplace/AppExemptModal.tsx
  apps/meteor/client/views/marketplace/AppUpdateModal.tsx
  apps/meteor/client/views/marketplace/AppsList/AddonRequiredModal.tsx
  apps/meteor/client/views/marketplace/components/AppInstallModal/AppInstallModal.tsx
  apps/meteor/client/views/marketplace/components/PrivateAppInstallModal/PrivateAppInstallModal.tsx
  apps/meteor/client/views/marketplace/components/UninstallGrandfatheredAppModal/UninstallGrandfatheredAppModal.tsx
  apps/meteor/client/views/modal/uikit/ModalBlock.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddMatrixUsers/AddMatrixUsersModal.tsx
  apps/meteor/client/views/room/contextualBar/Threads/Thread.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfConfigModal.tsx
  apps/meteor/client/views/room/modals/E2EEModals/ResetKeysE2EEModal.tsx
  apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
  apps/meteor/client/views/room/modals/ForwardMessageModal/ForwardMessageModal.tsx
  apps/meteor/client/views/room/webdav/AddWebdavAccountModal.tsx
  apps/meteor/client/views/room/webdav/SaveToWebdavModal.tsx
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerModal.tsx
  apps/meteor/client/views/teams/contextualBar/channels/AddExistingModal/AddExistingModal.tsx
  apps/meteor/client/voip/components/modals/WrapUpCallModal.tsx
  apps/meteor/client/voip/modal/DialPad/DialPadModal.tsx
  apps/meteor/client/voip/modals/DeviceSettingsModal.tsx
  packages/ui-client/src/components/Modal/GenericModal/GenericModal.tsx
  packages/ui-voip/src/components/VoipTransferModal/VoipTransferModal.tsx
Labels: stat: ready to merge, stat: QA assured

#36306 chore: remove gc-stats package
  apps/meteor/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/omnichannel-transcript/package.json
  ee/apps/presence-service/package.json
  ee/apps/queue-worker/package.json
  ee/apps/stream-hub-service/package.json
Labels: stat: ready to merge, stat: QA assured

#36398 fix: [Enhanced navigation] Missing burger menu in embedded layout
  .changeset/hot-crabs-invite.md
  apps/meteor/client/components/Page/PageHeaderNoShadow.tsx
  apps/meteor/tests/e2e/feature-preview.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA assured

#36405 feat: Add AJV schema support for invites and update related API endpo…
  apps/meteor/app/api/server/ajv.ts
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/v1/custom-sounds.ts
  apps/meteor/app/api/server/v1/invites.ts
  apps/meteor/app/livechat/server/index.ts
  packages/core-typings/src/Ajv.ts
  packages/http-router/src/Router.spec.ts
  packages/http-router/src/Router.ts
  packages/rest-typings/src/v1/invites.ts
Labels: stat: ready to merge, stat: QA assured

#36423 chore(outbound): Endpoint not being imported by code
  apps/meteor/ee/app/livechat-enterprise/server/api/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/outbound.ts
Labels: stat: ready to merge, stat: QA assured

#36426 ci: skip PR preview on forks
  .github/workflows/ci.yml
Labels: stat: ready to merge, stat: QA assured

#36427 chore: add missing volta fields and fix wrong extends
  apps/meteor/ee/server/services/package.json
  ee/apps/account-service/package.json
  ee/apps/authorization-service/package.json
  ee/apps/ddp-streamer/package.json
  ee/apps/stream-hub-service/package.json
  package.json
  packages/account-utils/package.json
  packages/agenda/package.json
  packages/api-client/package.json
  packages/apps/package.json
  packages/cas-validate/package.json
  packages/cron/package.json
  packages/ddp-client/package.json
  packages/eslint-config/package.json
  packages/favicon/package.json
  packages/freeswitch/package.json
  packages/instance-status/package.json
  packages/logger/package.json
  packages/model-typings/package.json
  packages/models/package.json
  packages/mongo-adapter/package.json
  packages/node-poplib/package.json
  packages/password-policies/package.json
  packages/patch-injection/package.json
  packages/release-action/package.json
  packages/release-changelog/package.json
  packages/tools/package.json
  packages/tsconfig/package.json
Labels: stat: ready to merge, stat: QA assured

#36425 test: Flaky `useDecryptedMessage` - should handle E2EE messages with attachments but no description
  apps/meteor/client/hooks/useDecryptedMessage.spec.ts
Labels: stat: QA assured

#36438 chore: add date sorting functionality to pipe
  apps/meteor/client/lib/cachedCollections/pipe.spec.ts
  apps/meteor/client/lib/cachedCollections/pipe.ts
Labels: stat: ready to merge, stat: QA assured

#36439 chore: Rooms store
  apps/meteor/app/e2e/client/rocketchat.e2e.room.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/lib/client/methods/sendMessage.ts
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/app/models/client/models/CachedChatRoom.ts
  apps/meteor/app/models/client/models/CachedChatSubscription.ts
  apps/meteor/app/models/client/models/Rooms.ts
  apps/meteor/app/reactions/client/methods/setReaction.ts
  apps/meteor/app/slashcommands-topic/client/topic.ts
  apps/meteor/app/webrtc/client/actionLink.tsx
  apps/meteor/client/apps/RealAppsEngineUIHost.ts
  apps/meteor/client/components/UserAndRoomAutoCompleteMultiple/UserAndRoomAutoCompleteMultiple.tsx
  apps/meteor/client/components/message/toolbar/items/actions/ReactionMessageAction.tsx
  apps/meteor/client/hooks/roomActions/useRoomInfoRoomAction.ts
  apps/meteor/client/hooks/useRoomInfoEndpoint.ts
  apps/meteor/client/lib/cachedCollections/CachedCollection.ts
  apps/meteor/client/lib/cachedCollections/CachedCollectionManager.ts
  apps/meteor/client/lib/cachedCollections/index.ts
  apps/meteor/client/lib/cachedCollections/utils.ts
  apps/meteor/client/lib/chats/data.ts
  apps/meteor/client/lib/getPermaLink.ts
  apps/meteor/client/lib/queryKeys.ts
  apps/meteor/client/lib/rooms/roomCoordinator.tsx
  apps/meteor/client/lib/rooms/roomTypes/direct.ts
  apps/meteor/client/lib/rooms/roomTypes/livechat.ts
  apps/meteor/client/lib/rooms/roomTypes/private.ts
  apps/meteor/client/lib/rooms/roomTypes/public.ts
  apps/meteor/client/lib/rooms/roomTypes/voip.ts
  apps/meteor/client/lib/utils/getUidDirectMessage.ts
  apps/meteor/client/lib/utils/legacyJumpToMessage.ts
  apps/meteor/client/lib/utils/waitUntilFind.ts
  apps/meteor/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx
  apps/meteor/client/omnichannel/priorities/PriorityEditForm.tsx
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/startup/e2e.ts
  apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/ChatInfo.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/ChatsContextualBar.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/RoomEdit/RoomEditWithData.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/useOmnichannelRoomInfo.tsx
  apps/meteor/client/views/omnichannel/directory/hooks/usePriorityInfo.tsx
  apps/meteor/client/views/omnichannel/directory/utils/formatQueuedAt.ts
  apps/meteor/client/views/room/body/hooks/useFileUploadDropTarget.ts
  apps/meteor/client/views/room/composer/ComposerContainer.tsx
  apps/meteor/client/views/room/composer/hooks/useMessageComposerIsArchived.ts
  apps/meteor/client/views/room/composer/hooks/useMessageComposerIsReadOnly.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useRoomQuery.ts
  apps/meteor/definition/IRoomTypeConfig.ts
  apps/meteor/tests/e2e/message-actions.spec.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/threads.spec.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/v1/omnichannel.ts
  packages/ui-contexts/src/UserContext.ts
  packages/ui-contexts/src/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#36445 chore(ui-contexts): Deprecate `useTranslation` in favor of `react-i18next` alternative
  packages/ui-contexts/src/hooks/useTranslation.ts
Labels: stat: ready to merge, stat: QA assured

#36448 chore: Don't use deprecated `Modal` reference
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/DateTimeModal.tsx
Labels: stat: ready to merge, stat: QA assured

#36099 fix: ui does not update after pruning only files
  .changeset/cold-insects-guess.md
  apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/client/hooks/lists/useStreamUpdatesForMessageList.ts
  apps/meteor/client/lib/utils/modifyMessageOnFilesDelete.spec.ts
  apps/meteor/client/lib/utils/modifyMessageOnFilesDelete.ts
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/prune-messages.spec.ts
  packages/core-services/src/events/Events.ts
  packages/ddp-client/src/types/streams.ts
Labels: stat: ready to merge, stat: QA assured

#36403 feat: App Logs Export
  .changeset/serious-apricots-compare.md
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogs.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogsItem.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilter.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilterCompact.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilterContextualBar.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilterExpanded.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppsLogsFilterOptionsCompact.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/DateTimeModal.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.stories.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/__snapshots__/AppLogsFilterCompact.spec.tsx.snap
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/__snapshots__/AppLogsFilterExpanded.spec.tsx.snap
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/__snapshots__/ExportLogsModal.spec.tsx.snap
  apps/meteor/ee/server/apps/communication/endpoints/appGeneralLogsHandler.ts
  apps/meteor/ee/server/apps/communication/endpoints/appLogsExportHandler.ts
  apps/meteor/ee/server/apps/communication/endpoints/appLogsHandler.ts
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/ee/server/apps/storage/AppRealLogStorage.ts
  apps/meteor/package.json
  apps/meteor/tests/end-to-end/apps/app-logs-export.ts
  packages/apps-engine/src/server/storage/AppLogStorage.ts
  packages/apps-engine/tests/test-data/storage/logStorage.ts
  packages/i18n/src/locales/en.i18n.json
  packages/rest-typings/src/apps/appLogsExportProps.ts
  packages/rest-typings/src/apps/index.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#36386 feat: add `separateResponse` param to incoming webhooks for optional per-channel responses markdown
  .changeset/nice-mice-pump.md
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/integrations/server/api/api.ts
  apps/meteor/app/integrations/server/lib/triggerHandler.ts
  apps/meteor/app/lib/server/functions/processWebhookMessage.ts
  apps/meteor/server/modules/core-apps/mention.module.ts
  apps/meteor/tests/data/users.helper.ts
  apps/meteor/tests/end-to-end/api/incoming-integrations.ts
Labels: stat: ready to merge, stat: QA assured

#36319 regression: Remove pdf option in export messages as file
  apps/meteor/client/views/room/contextualBar/ExportMessages/ExportMessages.tsx
  apps/meteor/tests/e2e/e2e-encryption.spec.ts
  apps/meteor/tests/e2e/export-messages.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/export-messages-tab.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab-exportMessages.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts
  apps/meteor/tests/e2e/page-objects/login.ts
Labels: stat: ready to merge, stat: QA assured

#36459 fix: do not resub router on message
  apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
Labels: stat: ready to merge, stat: QA assured

#36451 feat: use change streams to monitor instances
  apps/meteor/ee/server/local-services/instance/service.ts
  packages/model-typings/src/models/IInstanceStatusModel.ts
  packages/models/src/models/InstanceStatus.ts
Labels: stat: ready to merge, stat: QA assured

#36468 chore: Remove `useEndpointData`
  apps/meteor/client/components/deviceManagement/DeviceManagementTable/DeviceManagementTable.tsx
  apps/meteor/client/hooks/useEndpointData.ts
  apps/meteor/client/lib/queryKeys.ts
  apps/meteor/client/omnichannel/cannedResponses/CannedResponseEditWithDepartmentData.tsx
  apps/meteor/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountTable.tsx
  apps/meteor/client/views/account/tokens/AccountTokensTable/AccountTokensTable.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfoWithData.tsx
  apps/meteor/client/views/admin/settings/Setting/inputs/LookupSettingInput.tsx
  apps/meteor/client/views/admin/settings/groups/VoipGroupPage/AssignAgentModal.tsx
  apps/meteor/client/views/omnichannel/appearance/AppearancePageContainer.tsx
  apps/meteor/client/views/omnichannel/directory/CallsContextualBarDirectory.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/ChatInfo.tsx
  apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/VisitorClientInfo.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/RealTimeMonitoringPage.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/AgentStatusChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatDurationChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsPerAgentChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ChatsPerDepartmentChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/charts/ResponseTimesChart.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.stories.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/AgentsOverview.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/ChatsOverview.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/ConversationOverview.tsx
  apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/ProductivityOverview.tsx
  apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslateWithData.tsx
  apps/meteor/client/views/room/contextualBar/UserInfo/UserInfoWithData.tsx
  apps/meteor/client/views/teams/contextualBar/info/ConvertToChannelModal/ConvertToChannelModal.tsx
  apps/meteor/client/views/teams/contextualBar/members/RemoveUsersModal/RemoveUsersModal.tsx
Labels: stat: ready to merge, stat: QA assured

#36413 feat: New reload and expand all buttons in App Logs view
  .changeset/silent-zoos-notice.md
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogs.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogsItem.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilter.stories.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilter.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppsLogsFilterOptionsCompact.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/CompactFilterOptions.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/__snapshots__/AppLogsFilterExpanded.spec.tsx.snap
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/__snapshots__/AppLogsItem.spec.tsx.snap
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#36449 fix: Missing notifiers for priorities & some inquiry changes
  .changeset/sweet-dingos-decide.md
  apps/meteor/app/lib/server/lib/notifyListener.ts
  apps/meteor/app/livechat/server/lib/Helper.ts
  apps/meteor/app/livechat/server/lib/closeRoom.ts
  apps/meteor/app/livechat/server/lib/rooms.ts
  apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/priorities.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/sla.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/SlaHelper.ts
  apps/meteor/server/services/omnichannel/queue.ts
  packages/model-typings/src/models/ILivechatInquiryModel.ts
  packages/models/src/models/LivechatInquiry.ts
Labels: stat: ready to merge, stat: QA assured

#36390 feat(outbound): Apps engine bridge
  apps/meteor/app/apps/server/bridges/bridges.js
  apps/meteor/app/apps/server/bridges/outboundCommunication.ts
  apps/meteor/app/livechat/server/lib/outboundcommunication.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/lib/outbound.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/outbound.ts
  apps/meteor/server/lib/OutboundMessageProvider.ts
  packages/apps-engine/deno-runtime/handlers/outboundcomms-handler.ts
  packages/apps-engine/deno-runtime/lib/accessors/mod.ts
  packages/apps-engine/deno-runtime/main.ts
  packages/apps-engine/src/definition/accessors/IConfigurationExtend.ts
  packages/apps-engine/src/definition/accessors/IOutboundCommunicationProviderExtend.ts
  packages/apps-engine/src/definition/accessors/index.ts
  packages/apps-engine/src/definition/outboundComunication/IOutboundCommsProvider.ts
  packages/apps-engine/src/server/AppManager.ts
  packages/apps-engine/src/server/accessors/ConfigurationExtend.ts
  packages/apps-engine/src/server/accessors/OutboundCommunicationProviderExtend.ts
  packages/apps-engine/src/server/accessors/index.ts
  packages/apps-engine/src/server/bridges/AppBridges.ts
  packages/apps-engine/src/server/bridges/OutboundMessagesBridge.ts
  packages/apps-engine/src/server/bridges/index.ts
  packages/apps-engine/src/server/managers/AppAccessorManager.ts
  packages/apps-engine/src/server/managers/AppOutboundCommunicationProvider.ts
  packages/apps-engine/src/server/managers/AppOutboundCommunicationProviderManager.ts
  packages/apps-engine/src/server/managers/index.ts
  packages/apps-engine/src/server/permissions/AppPermissions.ts
  packages/apps-engine/tests/server/AppManager.spec.ts
  packages/apps-engine/tests/server/accessors/AppAccessors.spec.ts
  packages/apps-engine/tests/server/managers/AppAccessorManager.spec.ts
  packages/apps-engine/tests/test-data/bridges/appBridges.ts
  packages/apps-engine/tests/test-data/bridges/outboundComms.ts
  packages/apps-engine/tests/test-data/utilities.ts
  packages/core-typings/src/omnichannel/outbound.ts
Labels: stat: ready to merge, stat: QA assured

#36485 regression: add missing check for 'all' in app logs export
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilter.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.stories.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.tsx
Labels: stat: ready to merge, stat: QA assured

#36497 chore: Missing accessor types on definition of app handlers
  packages/apps-engine/src/definition/outboundComunication/IOutboundCommsProvider.ts
Labels: stat: ready to merge, stat: QA assured

#36493 regression: missing font color in App Status Tag
  apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
Labels: stat: ready to merge, stat: QA assured

#36476 chore: Remove deprecated flag of `MessageActionConfig`
  apps/meteor/app/ui-utils/client/lib/MessageAction.ts
  apps/meteor/client/components/message/toolbar/MessageToolbarActionMenu.tsx
  apps/meteor/client/components/message/toolbar/MessageToolbarStarsActionMenu.tsx
  apps/meteor/client/components/message/toolbar/useDeleteMessageAction.ts
  apps/meteor/client/components/message/toolbar/useReportMessageAction.tsx
Labels: stat: ready to merge, stat: QA assured

#36478 chore: Consume from the `ToastMessageContext`
  apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
  apps/meteor/client/hooks/roomActions/useE2EERoomAction.spec.ts
  apps/meteor/client/hooks/roomActions/useE2EERoomAction.ts
  apps/meteor/client/hooks/useDialModal.tsx
  apps/meteor/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx
  apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslateWithData.tsx
  apps/meteor/client/views/room/modals/E2EEModals/ResetKeysE2EEModal.tsx
  apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
Labels: stat: ready to merge, stat: QA assured

#36498 feat(message-parser): Make timestamp accept ISO time
  packages/message-parser/src/grammar.pegjs
  packages/message-parser/src/utils.ts
  packages/message-parser/tests/timestamp.test.ts
Labels: stat: ready to merge, stat: QA assured

#36522 chore: bump `fuselage` and add `fuselage-forms`
  apps/meteor/package.json
  apps/uikit-playground/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/storybook-config/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#36473 chore: Expose mutation API in `useEndpoint*` hooks
  apps/meteor/client/hooks/useDeviceLogout.tsx
  apps/meteor/client/hooks/useEndpointAction.ts
  apps/meteor/client/hooks/useEndpointMutation.ts
  apps/meteor/client/hooks/useEndpointUpload.ts
  apps/meteor/client/hooks/useEndpointUploadMutation.ts
  apps/meteor/client/hooks/useUpdateAvatar.ts
  apps/meteor/client/lib/queryKeys.ts
  apps/meteor/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountRow.tsx
  apps/meteor/client/views/account/deviceManagement/DeviceManagementAccountTable/DeviceManagementAccountTable.tsx
  apps/meteor/client/views/account/security/TwoFactorEmail.tsx
  apps/meteor/client/views/admin/customEmoji/AddCustomEmoji.tsx
  apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementAdminPage.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminRow.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfo.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfoWithData.tsx
  apps/meteor/client/views/admin/users/AdminUserForm.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
  apps/meteor/client/views/omnichannel/agents/AgentEditWithData.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AddAgent.tsx
  apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
  apps/meteor/client/views/omnichannel/agents/hooks/useAgentsQuery.ts
  apps/meteor/client/views/omnichannel/agents/hooks/useRemoveAgent.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/AddAgent.tsx
  apps/meteor/client/views/omnichannel/managers/AddManager.tsx
  apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
  apps/meteor/client/views/omnichannel/managers/RemoveManagerButton.tsx
  apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslateWithData.tsx
  apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useRemoveUserAction.tsx
  apps/meteor/client/views/teams/contextualBar/info/useConvertToChannel.tsx
  apps/meteor/client/views/teams/contextualBar/info/useLeaveTeam.tsx
Labels: stat: ready to merge, stat: QA assured

#36315 feat: Wizard component
  .changeset/thirty-experts-thank.md
  apps/meteor/client/components/Wizard/WizardActions.tsx
  packages/ui-client/src/components/Wizard/Wizard.spec.tsx
  packages/ui-client/src/components/Wizard/Wizard.stories.tsx
  packages/ui-client/src/components/Wizard/Wizard.tsx
  packages/ui-client/src/components/Wizard/WizardActions.tsx
  packages/ui-client/src/components/Wizard/WizardBackButton.spec.tsx
  packages/ui-client/src/components/Wizard/WizardBackButton.tsx
  packages/ui-client/src/components/Wizard/WizardContent.tsx
  packages/ui-client/src/components/Wizard/WizardContext.tsx
  packages/ui-client/src/components/Wizard/WizardNextButton.spec.tsx
  packages/ui-client/src/components/Wizard/WizardNextButton.tsx
  packages/ui-client/src/components/Wizard/WizardTabs.tsx
  packages/ui-client/src/components/Wizard/__snapshots__/Wizard.spec.tsx.snap
  packages/ui-client/src/components/Wizard/index.ts
  packages/ui-client/src/components/Wizard/lib/StepNode.spec.ts
  packages/ui-client/src/components/Wizard/lib/StepNode.ts
  packages/ui-client/src/components/Wizard/lib/StepsLinkedList.spec.ts
  packages/ui-client/src/components/Wizard/lib/StepsLinkedList.ts
  packages/ui-client/src/components/Wizard/mocks/createMockWizardApi.ts
  packages/ui-client/src/components/Wizard/useWizard.spec.tsx
  packages/ui-client/src/components/Wizard/useWizard.tsx
  packages/ui-client/src/components/Wizard/useWizardContext.tsx
  packages/ui-client/src/components/Wizard/useWizardSteps.spec.ts
  packages/ui-client/src/components/Wizard/useWizardSteps.tsx
  packages/ui-client/src/components/index.ts
Labels: stat: ready to merge, stat: QA assured

#36540 regression: logs export endpoint limited to 100 records
  apps/meteor/ee/server/apps/communication/endpoints/appLogsExportHandler.ts
Labels: stat: ready to merge, stat: QA assured

#36503 fix: desktop notifications implementing privacy settings
  .changeset/selfish-students-drum.md
  apps/meteor/.mocharc.js
  apps/meteor/app/lib/server/functions/notifications/desktop.spec.ts
  apps/meteor/app/lib/server/functions/notifications/desktop.ts
  apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.ts
  apps/meteor/client/hooks/notification/useNotification.ts
  apps/meteor/definition/IRoomTypeConfig.ts
  apps/meteor/server/lib/rooms/buildNotificationDetails.spec.ts
  apps/meteor/server/lib/rooms/buildNotificationDetails.ts
  apps/meteor/server/lib/rooms/roomCoordinator.ts
  apps/meteor/server/lib/rooms/roomTypes/direct.ts
  apps/meteor/server/lib/rooms/roomTypes/livechat.ts
  apps/meteor/server/lib/rooms/roomTypes/voip.ts
Labels: stat: ready to merge, stat: QA assured

#36535 fix: update error type for invalid parameters in Router class
  .changeset/silly-laws-act.md
  packages/http-router/src/Router.spec.ts
  packages/http-router/src/Router.ts
Labels: gsoc-project, stat: ready to merge, stat: QA assured

#36422 chore: `Subscriptions` store
  apps/meteor/app/autotranslate/client/lib/autotranslate.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.room.ts
  apps/meteor/app/e2e/client/rocketchat.e2e.ts
  apps/meteor/app/reactions/client/methods/setReaction.ts
  apps/meteor/app/slashcommands-open/client/client.ts
  apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/app/webrtc/client/WebRTCClass.ts
  apps/meteor/client/components/message/toolbar/useReplyInDMAction.ts
  apps/meteor/client/hooks/useRoomMenuActions.ts
  apps/meteor/client/lib/chats/data.ts
  apps/meteor/client/lib/getPermaLink.ts
  apps/meteor/client/lib/mutationEffects/room.ts
  apps/meteor/client/lib/mutationEffects/updateSubscription.ts
  apps/meteor/client/lib/rooms/roomCoordinator.tsx
  apps/meteor/client/lib/rooms/roomTypes/direct.ts
  apps/meteor/client/lib/rooms/roomTypes/livechat.ts
  apps/meteor/client/lib/utils/goToRoomById.ts
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/views/room/RoomSidepanel/hooks/useTeamslistChildren.ts
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
  apps/meteor/client/views/room/providers/hooks/useUsersNameChanged.ts
  apps/meteor/client/views/root/hooks/useClearUnreadAllMessagesMutation.ts
  apps/meteor/client/views/root/hooks/useLoadMissedMessages.ts
  packages/ui-contexts/src/UserContext.ts
  packages/ui-contexts/src/hooks/useUserSubscription.ts
  packages/ui-contexts/src/hooks/useUserSubscriptionByName.ts
Labels: stat: ready to merge, stat: QA assured

#36554 test: new tests for `isDepartmentCreationAvailable`
  ee/packages/omni-core-ee/jest.config.ts
  ee/packages/omni-core-ee/src/isDepartmentCreationAvailable.spec.ts
  packages/omni-core/jest.config.ts
  packages/omni-core/src/isDepartmentCreationAvailable.spec.ts
Labels: stat: ready to merge, stat: QA assured

#36020 feat: Add OpenAPI Support to chat.pinMessage API
  .changeset/fast-walls-turn.md
  apps/meteor/app/api/server/v1/chat.ts
  packages/core-typings/src/Ajv.ts
  packages/core-typings/src/IMessage/IMessage.ts
  packages/rest-typings/src/v1/chat.ts
Labels: gsoc-project, stat: ready to merge, stat: QA assured

#36562 refactor: query `ParentTeam` data from reusable hooks
  apps/meteor/client/hooks/useTeamInfoQuery.ts
  apps/meteor/client/lib/queryKeys.ts
  apps/meteor/client/views/hooks/roomActions/useDeleteRoom.tsx
  apps/meteor/client/views/room/Header/ParentTeam.tsx
  apps/meteor/client/views/room/HeaderV2/ParentRoom/ParentTeam.tsx
  apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/useEditRoomPermissions.ts
  apps/meteor/client/views/room/hooks/useUserTeamsQuery.ts
Labels: stat: ready to merge, stat: QA assured

#36541 feat: adds new model function for aggregated agents by department
  .changeset/fluffy-cats-crash.md
  apps/meteor/app/livechat/server/api/lib/departments.ts
  apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
  packages/model-typings/src/models/ILivechatDepartmentAgentsModel.ts
  packages/models/src/models/LivechatDepartmentAgents.ts
Labels: stat: ready to merge, stat: QA assured

#36289 chore: `Users` store
  apps/meteor/app/authorization/client/hasPermission.ts
  apps/meteor/app/authorization/client/hasRole.ts
  apps/meteor/app/authorization/client/index.ts
  apps/meteor/app/authorization/client/watch.ts
  apps/meteor/app/models/client/models/Roles.ts
  apps/meteor/app/models/client/models/Subscriptions.ts
  apps/meteor/app/models/client/models/Users.ts
  apps/meteor/app/ui/client/lib/UserAction.ts
  apps/meteor/app/utils/client/lib/getUserPreference.ts
  apps/meteor/app/webrtc/client/WebRTCClass.ts
  apps/meteor/client/lib/cachedCollections/DiffSequence.ts
  apps/meteor/client/lib/cachedCollections/common.ts
  apps/meteor/client/lib/cachedCollections/index.ts
  apps/meteor/client/lib/normalizeThreadTitle.ts
  apps/meteor/client/lib/objectUtils.ts
  apps/meteor/client/lib/rooms/roomTypes/direct.ts
  apps/meteor/client/lib/userData.ts
  apps/meteor/client/meteorOverrides/userAndUsers.ts
  apps/meteor/client/providers/AuthorizationProvider.tsx
  apps/meteor/client/providers/UserProvider/UserProvider.tsx
  apps/meteor/client/providers/UserProvider/hooks/useUpdateAvatar.ts
  packages/core-typings/src/IUser.ts
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/ui-contexts/src/AuthorizationContext.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#36577 fix: Remove room assignment before queueing the conversation again when transfering
  .changeset/eleven-buses-return.md
  apps/meteor/app/livechat/server/lib/RoutingManager.ts
Labels: stat: ready to merge, stat: QA assured

#36564 test: export messages with hide contextual bar preference
  apps/meteor/tests/e2e/export-messages.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/export-messages-tab.ts
Labels: stat: ready to merge, stat: QA assured

#36574 refactor: enhance API error response validation and accessibility
  apps/meteor/app/api/server/v1/chat.ts
  apps/meteor/app/api/server/v1/oauthapps.ts
  apps/meteor/app/api/server/v1/webdav.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/Ajv.ts
Labels: gsoc-project, stat: ready to merge, stat: QA assured

#36527 fix: empty thread preview
  .changeset/pretty-geckos-lick.md
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.spec.tsx
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.stories.tsx
  apps/meteor/client/components/message/variants/threadPreview/ThreadMessagePreviewBody.tsx
  apps/meteor/client/components/message/variants/threadPreview/__snapshots__/ThreadMessagePreviewBody.spec.tsx.snap
Labels: stat: ready to merge, stat: QA assured

#36591 fix: missing featured RoomToolBoxAction order
  .changeset/seven-gorillas-sell.md
  apps/meteor/client/hooks/roomActions/useAppsRoomStarActions.tsx
  apps/meteor/client/hooks/roomActions/useVideoCallRoomAction.tsx
  apps/meteor/client/hooks/roomActions/useVoiceCallRoomAction.tsx
Labels: stat: ready to merge, stat: QA assured
