Repository RocketChat/Rocket.Chat, pull requests merged in 2025-03, with the labels that each got.

#35388 regression: not allowing apps with default permissions to read settings
  apps/meteor/app/apps/server/bridges/settings.ts
Labels: stat: ready to merge, stat: QA assured

#35331 chore: improve messaging in videoconf client side debug logs
  apps/meteor/client/lib/VideoConfManager.ts
Labels: stat: ready to merge, stat: QA assured

#35330 fix: videoconf ringer not working after a temporary disconnection
  .changeset/angry-colts-worry.md
  apps/meteor/client/lib/VideoConfManager.ts
Labels: stat: ready to merge, stat: QA assured

#33796 feat: Replace `rc-scrollbars` in favor of `overlayscrollbars`
  .changeset/weak-turtles-exercise.md
  apps/meteor/app/theme/client/imports/general/base.css
  apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
  apps/meteor/client/components/CustomScrollbars/BaseScrollbars.tsx
  apps/meteor/client/components/CustomScrollbars/CustomScrollbars.tsx
  apps/meteor/client/components/CustomScrollbars/VirtualizedScrollbars.tsx
  apps/meteor/client/components/CustomScrollbars/VirtuosoScrollbars.tsx
  apps/meteor/client/components/CustomScrollbars/index.ts
  apps/meteor/client/components/Page/PageScrollableContent.tsx
  apps/meteor/client/components/Page/PageScrollableContentWithShadow.tsx
  apps/meteor/client/omnichannel/cannedResponses/contextualBar/CannedResponse/CannedResponseList.tsx
  apps/meteor/client/sidebar/RoomList/RoomList.tsx
  apps/meteor/client/sidebar/header/MatrixFederationSearch/FederatedRoomList.tsx
  apps/meteor/client/sidebar/search/SearchList.tsx
  apps/meteor/client/sidebarv2/RoomList/RoomList.tsx
  apps/meteor/client/sidebarv2/header/MatrixFederationSearch/FederatedRoomList.tsx
  apps/meteor/client/sidebarv2/header/SearchList.tsx
  apps/meteor/client/views/composer/EmojiPicker/CategoriesResult.tsx
  apps/meteor/client/views/composer/EmojiPicker/SearchingResult.tsx
  apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessagesList.tsx
  apps/meteor/client/views/omnichannel/contactInfo/tabs/ContactInfoChannels/ContactInfoChannels.tsx
  apps/meteor/client/views/omnichannel/contactInfo/tabs/ContactInfoHistory/ContactInfoHistory.tsx
  apps/meteor/client/views/omnichannel/contactInfo/tabs/ContactInfoHistory/ContactInfoHistoryMessages.tsx
  apps/meteor/client/views/outlookCalendar/OutlookEventsList/OutlookEventsList.tsx
  apps/meteor/client/views/room/Sidepanel/RoomSidepanel.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsList.tsx
  apps/meteor/client/views/room/contextualBar/MessageListTab.tsx
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearch.tsx
  apps/meteor/client/views/room/contextualBar/RoomFiles/RoomFiles.tsx
  apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembers.tsx
  apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageListScrolling.ts
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfList.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35172 fix: message parser mixing emoticons with bold/italic symbols
  .changeset/lucky-jokes-protect.md
  packages/message-parser/src/grammar.pegjs
  packages/message-parser/tests/emoji.test.ts
  packages/message-parser/tests/emoticons.test.ts
  packages/message-parser/tests/emphasis.test.ts
  packages/message-parser/tests/emphasisWithEmoticons.test.ts
  packages/message-parser/tests/orderedList.test.ts
  packages/message-parser/tests/tasks.test.ts
  packages/message-parser/tests/unorderedList.test.ts
Labels: stat: ready to merge, stat: QA assured

#35205 fix: adds contact manager check before assigning to agent
  .changeset/calm-rabbits-sin.md
  apps/meteor/app/livechat/server/lib/LivechatTyped.ts
  apps/meteor/app/livechat/server/lib/Visitors.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  packages/core-typings/src/ILivechatVisitor.ts
  packages/livechat/src/routes/Register/index.tsx
  packages/model-typings/src/models/ILivechatContactsModel.ts
  packages/models/src/models/LivechatContacts.ts
Labels: stat: ready to merge, stat: QA assured

#35369 fix: inner attachment empty when quoting multiple times
  .changeset/good-singers-allow.md
  apps/meteor/server/services/messages/hooks/BeforeSaveJumpToMessage.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveJumpToMessage.tests.ts
Labels: stat: ready to merge, stat: QA assured

#35326 fix: NavBar in embedded layout
  .changeset/dull-onions-visit.md
  apps/meteor/client/views/root/MainLayout/LayoutWithSidebarV2.tsx
  apps/meteor/tests/e2e/feature-preview.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35450 test: create tests for embedded layout
  apps/meteor/tests/e2e/embedded-layout.spec.ts
  apps/meteor/tests/e2e/page-objects/home-channel.ts
Labels: stat: ready to merge, stat: QA assured

#35454 regression: room list not using full sidebar width in new navigation
  apps/meteor/client/sidebarv2/RoomList/RoomList.tsx
Labels: stat: ready to merge, stat: QA assured

#35371 fix: 'room-changed' event race condition
  .changeset/odd-squids-repeat.md
  apps/meteor/client/hooks/useFireGlobalEvent.spec.ts
  apps/meteor/client/hooks/useFireGlobalEvent.ts
  apps/meteor/client/lib/utils/fireGlobalEvent.ts
  apps/meteor/client/lib/utils/fireGlobalEventBase.spec.ts
  apps/meteor/client/lib/utils/fireGlobalEventBase.ts
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#35301 chore: remove startup & tracker from CORS
  apps/meteor/app/cors/client/index.ts
  apps/meteor/app/cors/client/useCorsSSLConfig.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35303 chore: remove meteor from oauth
  apps/meteor/client/sidebar/hooks/useCustomOAuth.ts
  apps/meteor/client/startup/customOAuth.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35257 fix: Unexpected error when loading webdav files
  .changeset/four-houses-doubt.md
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/lib/getNodeIconType.spec.ts
  apps/meteor/client/views/room/webdav/WebdavFilePickerModal/lib/getNodeIconType.ts
Labels: stat: ready to merge, stat: QA assured

#35286 chore: Bump fuselage
  .changeset/bright-snakes-punch.md
  apps/meteor/package.json
  apps/uikit-playground/package.json
  ee/packages/ui-theming/package.json
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/livechat/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-composer/package.json
  packages/ui-contexts/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35022 refactor: Remove meteor from OTR (startup)
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/otr.ts
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/hooks/useOTRMessaging.ts
Labels: stat: ready to merge, stat: QA assured

#35300 chore: remove meteor from TokenPassAuth
  apps/meteor/app/tokenpass/client/hooks/useTokenPassAuth.tsx
  apps/meteor/app/tokenpass/client/index.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: QA assured

#35481 chore: Deduplicate keyboard event in MessageBox
  apps/meteor/client/hooks/useSafeRefCallback.spec.tsx
  apps/meteor/client/hooks/useSafeRefCallback.ts
  apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
Labels: stat: ready to merge, stat: QA assured

#35482 chore: Add isLoggingIn to ConnectionStatusContext
  apps/meteor/client/components/connectionStatus/ConnectionStatusBar.stories.tsx
  apps/meteor/client/providers/ConnectionStatusProvider.tsx
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/ui-contexts/src/ConnectionStatusContext.ts
Labels: stat: ready to merge, stat: QA assured

#35483 chore: Remove `navigationBar` feature preview
  apps/meteor/client/components/Navbar/Navbar.stories.tsx
  apps/meteor/client/components/Navbar/Navbar.tsx
  apps/meteor/client/components/Navbar/NavbarAction.tsx
  apps/meteor/client/components/Navbar/NavbarBadge.tsx
  apps/meteor/client/components/Navbar/index.ts
  apps/meteor/client/navbar/Navbar.tsx
  apps/meteor/client/navbar/actions/NavbarAdministrationAction.tsx
  apps/meteor/client/navbar/actions/NavbarAuditAction.tsx
  apps/meteor/client/navbar/actions/NavbarHomeAction.tsx
  apps/meteor/client/navbar/actions/NavbarMarketplaceAction.tsx
  apps/meteor/client/navbar/actions/NavbarUserAction.tsx
  apps/meteor/client/navbar/index.ts
  apps/meteor/client/sidebar/SidebarRegion.tsx
  apps/meteor/client/sidebar/header/Header.tsx
  apps/meteor/client/sidebar/header/HeaderUnstable.tsx
  apps/meteor/client/sidebar/header/UserAvatarWithStatus.tsx
  apps/meteor/client/sidebar/header/UserAvatarWithStatusUnstable.tsx
  apps/meteor/client/sidebar/header/UserMenu.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAppsItems.tsx
  apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.tsx
  apps/meteor/client/sidebar/header/index.tsx
  packages/ui-client/src/hooks/useFeaturePreview.spec.tsx
  packages/ui-client/src/hooks/useFeaturePreviewList.ts
Labels: stat: ready to merge, stat: QA assured

#35467 fix: Default preference value for `receiveLoginDetectionEmail`
  .changeset/five-planes-nail.md
  apps/meteor/client/views/account/preferences/useAccountPreferencesValues.ts
Labels: stat: ready to merge, stat: QA assured

#35492 test: Intermittent sidebar e2e test
  apps/meteor/tests/e2e/sidebar.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35339 fix: Client application memory leaks
  .changeset/kind-peas-camp.md
  apps/meteor/app/analytics/client/loadScript.ts
  apps/meteor/client/views/room/body/hooks/useListIsAtBottom.ts
  apps/meteor/client/views/room/hooks/useIsVisible.ts
Labels: stat: ready to merge, stat: QA assured

#35494 fix: Duplicate `PermissionStatus` event
  .changeset/neat-dingos-smoke.md
  apps/meteor/client/views/room/composer/messageBox/hooks/useMediaPermissions.ts
Labels: stat: ready to merge, stat: QA assured

#35495 chore: ensure `useComposerBoxPopupQueries` returns valid value
  apps/meteor/client/views/room/composer/hooks/useComposerBoxPopupQueries.ts
Labels: stat: ready to merge, stat: QA assured

#35420 fix: VoIP calls one-way audio issues
  .changeset/real-mayflies-provide.md
  packages/ui-voip/src/lib/VoipClient.ts
  packages/ui-voip/src/providers/VoipProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#35484 refactor: Remove userStatusManuallySet and meteor functions
  apps/meteor/client/NavBarV2/NavBarSettingsToolbar/UserMenu/hooks/useStatusItems.tsx
  apps/meteor/client/sidebar/header/hooks/useStatusItems.tsx
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/userStatusManuallySet.ts
Labels: stat: ready to merge, stat: QA assured

#35473 refactor: Remove meteor functions from VideoConfManager
  apps/meteor/client/lib/VideoConfManager.ts
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/hooks/useUpdateVideoConfUser.ts
Labels: stat: ready to merge, stat: QA assured

#35503 chore: fix healthy logic when db watchers are disabled
  apps/meteor/server/startup/watchDb.ts
Labels: stat: ready to merge, stat: QA assured

#35414 fix: don't allow omnichannel agents to join closed rooms
  .changeset/gold-cougars-stare.md
  apps/meteor/app/lib/server/methods/joinRoom.ts
  apps/meteor/client/views/room/hooks/useOpenRoom.ts
  apps/meteor/server/services/room/service.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-chat-history.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-info.ts
  apps/meteor/tests/end-to-end/api/methods.ts
Labels: stat: ready to merge, stat: QA assured

#34986 refactor: remove authorization method calls (server)
  apps/meteor/app/api/server/v1/roles.ts
  apps/meteor/app/authorization/server/methods/addUserToRole.ts
  apps/meteor/app/authorization/server/methods/removeUserFromRole.ts
  apps/meteor/app/bot-helpers/server/index.ts
  apps/meteor/app/lib/server/methods/setAdminStatus.ts
Labels: stat: ready to merge, stat: QA assured

#35510 chore: add instructions about open api + deprecations
  apps/meteor/app/api/README.md
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/definition.ts
Labels: stat: ready to merge, stat: QA assured

#35537 chore: accept `ReactNode` as toast message
  apps/meteor/client/lib/toast.ts
  apps/meteor/client/providers/ToastMessagesProvider.tsx
  apps/meteor/package.json
  apps/uikit-playground/package.json
  packages/ui-contexts/src/ToastMessagesContext.ts
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35203 chore: Use transaction for saveUser function
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/file-upload/server/lib/FileUpload.ts
  apps/meteor/app/lib/server/functions/saveCustomFields.ts
  apps/meteor/app/lib/server/functions/saveCustomFieldsWithoutValidation.ts
  apps/meteor/app/lib/server/functions/saveUser/saveUser.ts
  apps/meteor/app/lib/server/functions/saveUser/setPasswordUpdater.ts
  apps/meteor/app/lib/server/functions/saveUserIdentity.ts
  apps/meteor/app/lib/server/functions/setEmail.ts
  apps/meteor/app/lib/server/functions/setRealName.ts
  apps/meteor/app/lib/server/functions/setStatusText.ts
  apps/meteor/app/lib/server/functions/setUserAvatar.ts
  apps/meteor/app/lib/server/functions/setUsername.ts
  apps/meteor/app/lib/server/functions/updateGroupDMsName.ts
  apps/meteor/server/database/utils.ts
  apps/meteor/server/lib/shouldBreakInVersion.ts
  apps/meteor/server/ufs/ufs-local.ts
  apps/meteor/server/ufs/ufs-methods.ts
  apps/meteor/server/ufs/ufs-store.ts
  apps/meteor/tests/unit/app/lib/server/functions/setUsername.spec.ts
  apps/meteor/tests/unit/server/users/saveUserIdentity.spec.ts
  packages/model-typings/src/models/IBaseModel.ts
  packages/model-typings/src/models/IBaseUploadsModel.ts
  packages/model-typings/src/models/ISubscriptionsModel.ts
  packages/model-typings/src/models/IUsersModel.ts
  packages/models/src/models/BaseRaw.ts
  packages/models/src/models/BaseUploadModel.ts
  packages/models/src/models/Subscriptions.ts
  packages/models/src/models/Users.js
Labels: stat: ready to merge, stat: QA assured

#35536 regression: `EmojiPicker` not displaying scrollbar properly
  apps/meteor/client/views/composer/EmojiPicker/CategoriesResult.tsx
  apps/meteor/tests/e2e/emojis.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Labels: stat: ready to merge, stat: QA assured

#35533 chore: Remove unnecessary slash command initialization function
  apps/meteor/client/startup/slashCommands/index.ts
  apps/meteor/client/startup/slashCommands/list.ts
Labels: stat: ready to merge, stat: QA assured

#35535 refactor: `useAppSlashCommands` recursive strategy
  apps/meteor/client/hooks/useAppSlashCommands.ts
Labels: stat: ready to merge, stat: QA assured

#35540 fix: OAuth not syncing user roles on their first login
  .changeset/perfect-sloths-marry.md
  apps/meteor/app/custom-oauth/server/custom_oauth_server.js
Labels: stat: ready to merge, stat: QA assured

#35426 feat: memoize app getStatus calls
  .changeset/modern-wolves-jog.md
  packages/apps-engine/src/server/ProxiedApp.ts
  packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
  packages/apps-engine/tests/server/compiler/AppFabricationFulfillment.spec.ts
  packages/apps-engine/tests/test-data/utilities.ts
Labels: stat: ready to merge, stat: QA assured

#35258 feat: `audit.settings` endpoint
  .changeset/spicy-kangaroos-hear.md
  apps/meteor/app/api/server/index.ts
  apps/meteor/app/api/server/v1/server-events.ts
  apps/meteor/tests/end-to-end/api/settings.ts
  packages/rest-typings/src/index.ts
  packages/rest-typings/src/v1/server-events/ServerEventsAuditSettingsParamsGET.ts
  packages/rest-typings/src/v1/server-events/index.ts
  packages/rest-typings/src/v1/server-events/server-events.ts
Labels: stat: ready to merge, stat: QA assured

#35531 chore(deps): bump `xml-crypto` dependencies
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35418 fix: Filtering non ascii bad words
  .changeset/witty-ads-visit.md
  apps/meteor/server/services/messages/hooks/BeforeSaveBadWords.ts
  apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveBadWords.tests.ts
Labels: stat: ready to merge, stat: QA assured

#35545 fix: Video conference call again not working properly
  .changeset/chilly-schools-guess.md
  apps/meteor/client/hooks/roomActions/useStartCallRoomAction/useVideoConfMenuOptions.tsx
  apps/meteor/client/providers/VideoConfProvider.tsx
  apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopup/OutgoingPopup.tsx
  apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useVideoCallAction.tsx
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/video-conference-ring.spec.ts
  packages/i18n/src/locales/en.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35539 refactor: Remove meteor from "FileUploadHandler"
  apps/meteor/app/file-upload/client/index.ts
  apps/meteor/app/file-upload/client/lib/fileUploadHandler.ts
  apps/meteor/client/importPackages.ts
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/hooks/useStoreCookiesOnLogin.ts
Labels: stat: ready to merge, stat: QA assured

#35417 fix: leader banner visible in new navigation
  .changeset/lovely-walls-itch.md
  apps/meteor/client/views/room/HeaderV2/RoomLeader.tsx
  apps/meteor/client/views/room/body/RoomBody.tsx
  apps/meteor/client/views/room/body/RoomBodyV2.tsx
  apps/meteor/client/views/room/body/RoomTopic.tsx
  apps/meteor/client/views/room/body/hooks/useBannerSection.ts
  apps/meteor/client/views/room/body/hooks/useLeaderBanner.ts
Labels: stat: ready to merge, stat: QA assured

#34087 fix: Ensure apps-engine only starts after license is ready
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/startup.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/ee/server/startup/apps.ts
  apps/meteor/ee/server/startup/index.ts
  apps/meteor/server/main.ts
Labels: stat: ready to merge, stat: QA assured

#35551 fix: setDepartment now sets guest department logically
  .changeset/short-garlics-attack.md
  packages/livechat/src/lib/hooks.ts
Labels: stat: ready to merge, stat: QA assured

#35555 fix: Calling registerGuest multiple times causes loss of communication
  .changeset/selfish-toes-lay.md
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
  packages/livechat/src/lib/hooks.ts
Labels: stat: ready to merge, stat: QA assured

#35328 fix: ensure correct inquiry routing to manager queue when manual routing is enabled
  .changeset/dull-horses-matter.md
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/app/livechat/server/api/lib/inquiries.ts
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts
  apps/meteor/server/modules/listeners/listeners.module.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-queue-management.spec.ts
  packages/ddp-client/src/types/streams.ts
Labels: stat: ready to merge, stat: QA assured

#35493 fix: Ensure Translations Work in Offline Registration Setup Wizard
  .changeset/popular-donuts-notice.md
  apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
Labels: stat: ready to merge, stat: QA assured

#35538 chore: Eliminate inconsistencies in Norwegian Language
  apps/meteor/client/providers/TranslationProvider.tsx
  packages/i18n/src/locales/nb-NO.i18n.json
  packages/i18n/src/locales/nb.i18n.json
  packages/i18n/src/locales/se.i18n.json
Labels: stat: ready to merge, stat: QA assured

#35559 fix: apps endpoint not returning app's data
  .changeset/sour-spiders-pay.md
  apps/meteor/ee/server/apps/communication/rest.ts
  apps/meteor/tests/data/apps/apps-data.ts
  apps/meteor/tests/e2e/fixtures/insert-apps.ts
  apps/meteor/tests/end-to-end/apps/installation.ts
Labels: stat: ready to merge, stat: QA assured

#35479 chore: Update Deno version on CI and dep cache (#35283)
  .changeset/fresh-suns-boil.md
  .github/actions/setup-node/action.yml
  .github/workflows/ci-deploy-gh-pages.yml
  .github/workflows/ci.yml
  .github/workflows/new-release.yml
  .github/workflows/pr-update-description.yml
  .github/workflows/publish-release.yml
  .github/workflows/release-candidate.yml
  .tool-versions
  packages/apps-engine/deno-runtime/deno.jsonc
  packages/apps-engine/deno-runtime/deno.lock
  packages/apps-engine/deno-runtime/lib/parseArgs.ts
Labels: stat: ready to merge, stat: QA assured

#35415 fix: button to enable app not being displayed when app is migrated
  .changeset/spotty-crabs-rhyme.md
  apps/meteor/client/views/marketplace/hooks/useAppMenu.tsx
Labels: stat: ready to merge, stat: QA assured

#35342 fix: IPreRoomCreateModify not persisting changes made by apps
  .changeset/pretty-dragons-remain.md
  packages/apps-engine/src/server/managers/AppListenerManager.ts
Labels: stat: ready to merge, stat: QA assured

#35480 fix: Omnichannel continuous sound notification not being played
  .changeset/perfect-oranges-judge.md
  apps/meteor/client/hooks/useOmnichannelContinuousSoundNotification.ts
Labels: stat: ready to merge, stat: QA assured

#35370 feat: Added business unit field to edit department page
  .changeset/large-islands-behave.md
  apps/meteor/client/components/Omnichannel/hooks/useUnitsList.ts
  apps/meteor/client/omnichannel/additionalForms/AutoCompleteUnit.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/AddAgent.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/AgentRow.tsx
  apps/meteor/client/views/omnichannel/departments/DepartmentAgentsTable/DepartmentAgentsTable.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/client/views/omnichannel/departments/definitions/index.ts
  apps/meteor/client/views/omnichannel/departments/utils/formatAgentListPayload.ts
  apps/meteor/client/views/omnichannel/departments/utils/formatEditDepartmentPayload.ts
  apps/meteor/client/views/omnichannel/departments/utils/getFormInititalValues.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-monitor-department.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts
  packages/core-typings/src/ILivechatDepartment.ts
  packages/i18n/src/locales/en.i18n.json
  packages/model-typings/src/models/ILivechatDepartmentModel.ts
  packages/models/src/models/LivechatDepartment.ts
  packages/rest-typings/src/v1/omnichannel.ts
Labels: stat: ready to merge, stat: QA assured

#35374 refactor: grandfather apps installed before 7.0.0 while handling license downgrades
  .changeset/clean-dryers-hug.md
  apps/meteor/ee/server/apps/orchestrator.js
  apps/meteor/ee/server/apps/startup.ts
  packages/model-typings/src/models/IStatisticsModel.ts
  packages/models/src/models/Statistics.ts
Labels: stat: ready to merge, stat: QA assured

#35486 feat(apps-engine): adds executeLivechatRoomCreatePrevent event
  .changeset/sour-ghosts-count.md
  apps/meteor/app/apps/server/bridges/listeners.js
  apps/meteor/app/livechat/server/lib/QueueManager.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
  packages/apps-engine/src/definition/livechat/IPreLivechatRoomCreatePrevent.ts
  packages/apps-engine/src/definition/livechat/index.ts
  packages/apps-engine/src/definition/metadata/AppInterface.ts
  packages/apps-engine/src/definition/metadata/AppMethod.ts
  packages/apps-engine/src/server/managers/AppListenerManager.ts
  packages/apps/src/bridges/IListenerBridge.ts
Labels: stat: ready to merge, stat: QA assured

#35332 fix: Apps preventing join actions not showing any error
  .changeset/rich-hounds-wave.md
  apps/meteor/client/hooks/useJoinRoom.ts
  apps/meteor/client/views/room/NotSubscribedRoom.tsx
  apps/meteor/client/views/room/composer/ComposerReadOnly.tsx
  apps/meteor/tests/e2e/fixtures/inject-initial-data.ts
  apps/meteor/tests/e2e/fixtures/userStates.ts
  apps/meteor/tests/e2e/page-objects/directory.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  apps/meteor/tests/e2e/preview-public-channel.spec.ts
  apps/meteor/tests/e2e/utils/create-target-channel.ts
Labels: stat: ready to merge, stat: QA assured

#35546 fix: brings back `roomName` on GET `/groups.messages` endpoint
  .changeset/chatty-berries-compare.md
  apps/meteor/app/api/server/v1/groups.ts
  apps/meteor/tests/end-to-end/api/groups.ts
  packages/rest-typings/src/v1/groups/GroupsMessagesProps.ts
Labels: stat: ready to merge, stat: QA assured

#35550 regression: Wrong scrollbar being used with virtuoso
  apps/meteor/client/views/room/Sidepanel/RoomSidepanel.tsx
  apps/meteor/client/views/room/contextualBar/MessageListTab.tsx
  apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearch.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.spec.tsx
  apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.tsx
Labels: stat: ready to merge, stat: QA assured

#35554 chore: improve-mocked-provider-settings
  packages/mock-providers/jest.config.ts
  packages/mock-providers/package.json
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/mock-providers/src/tests/useSetting.spec.tsx
  packages/mock-providers/src/tests/useSettings.spec.tsx
  packages/mock-providers/tsconfig.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35280 feat: Livechat department removed/disabled events for apps
  .changeset/big-tips-greet.md
  apps/meteor/app/apps/server/bridges/listeners.js
  apps/meteor/app/livechat/server/lib/departmentsLib.ts
  packages/apps-engine/src/definition/livechat/ILivechatEventContext.ts
  packages/apps-engine/src/definition/livechat/IPostLivechatDepartmentDisabled.ts
  packages/apps-engine/src/definition/livechat/IPostLivechatDepartmentRemoved.ts
  packages/apps-engine/src/definition/livechat/index.ts
  packages/apps-engine/src/definition/metadata/AppInterface.ts
  packages/apps-engine/src/definition/metadata/AppMethod.ts
  packages/apps-engine/src/server/managers/AppListenerManager.ts
  packages/apps/src/bridges/IListenerBridge.ts
Labels: stat: ready to merge, stat: QA assured

#35567 refactor: remove KonchatNotification `newRoom` from meteor
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/client/hooks/useNotifyNewRoom.ts
  apps/meteor/client/hooks/useNotifyUser.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#35340 fix: 2FA check flashing for mandatory roles
  .changeset/chatty-kids-compare.md
  apps/meteor/app/authentication/server/startup/index.js
  apps/meteor/app/utils/server/functions/getBaseUserFields.ts
  apps/meteor/app/utils/server/functions/getDefaultUserFields.ts
  apps/meteor/server/startup/initialData.js
  apps/meteor/tests/e2e/enforce-2FA.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
  ee/apps/ddp-streamer/src/DDPStreamer.ts
Labels: stat: ready to merge, stat: QA assured

#35570 refactor: remove KonchatNotification `newMessage` from meteor
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/client/hooks/notification/useNewMessageNotification.ts
  apps/meteor/client/hooks/notification/useNewRoomNotification.ts
  apps/meteor/client/hooks/notification/useNotifyUser.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35532 fix: urlencoded webhook payload parsing
  .changeset/real-badgers-clap.md
  apps/meteor/app/integrations/server/api/api.js
  apps/meteor/tests/end-to-end/api/incoming-integrations.ts
Labels: stat: ready to merge, stat: QA assured

#35569 chore: Helper script to replace sprintf tokens `%s` on translation strings
  apps/meteor/.scripts/replaceTranslationSprintfParams.ts
  apps/meteor/package.json
Labels: stat: ready to merge, stat: QA assured

#35474 feat: set busy status on calendar appointments
  .changeset/lovely-ways-move.md
  apps/meteor/app/api/server/v1/calendar.ts
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/ee/server/settings/outlookCalendar.ts
  apps/meteor/server/services/calendar/service.ts
  apps/meteor/server/services/calendar/statusEvents/applyStatusChange.ts
  apps/meteor/server/services/calendar/statusEvents/cancelUpcomingStatusChanges.ts
  apps/meteor/server/services/calendar/statusEvents/generateCronJobId.ts
  apps/meteor/server/services/calendar/statusEvents/handleOverlappingEvents.ts
  apps/meteor/server/services/calendar/statusEvents/index.ts
  apps/meteor/server/services/calendar/statusEvents/removeCronJobs.ts
  apps/meteor/server/services/calendar/statusEvents/setupAppointmentStatusChange.ts
  apps/meteor/server/services/calendar/utils/getShiftedTime.ts
  apps/meteor/tests/e2e/presence.spec.ts
  apps/meteor/tests/unit/server/services/calendar/mocks/cronJobs.ts
  apps/meteor/tests/unit/server/services/calendar/service.tests.ts
  apps/meteor/tests/unit/server/services/calendar/statusEvents/applyStatusChange.ts
  apps/meteor/tests/unit/server/services/calendar/statusEvents/cancelUpcomingStatusChanges.tests.ts
  apps/meteor/tests/unit/server/services/calendar/statusEvents/generateCronJobId.tests.ts
  apps/meteor/tests/unit/server/services/calendar/statusEvents/handleOverlappingEvents.ts
  apps/meteor/tests/unit/server/services/calendar/statusEvents/removeCronJobs.tests.ts
  apps/meteor/tests/unit/server/services/calendar/statusEvents/setupAppointmentStatusChange.ts
  apps/meteor/tests/unit/server/services/calendar/utils/getShiftedTime.tests.ts
  apps/meteor/tests/unit/server/services/utils.ts
  packages/core-services/src/types/ICalendarService.ts
  packages/core-typings/src/ICalendarEvent.ts
  packages/model-typings/src/models/ICalendarEventModel.ts
  packages/model-typings/src/models/IUsersModel.ts
  packages/models/src/models/CalendarEvent.ts
  packages/models/src/models/Users.ts
  packages/rest-typings/src/v1/calendar/CalendarEventCreateProps.ts
  packages/rest-typings/src/v1/calendar/CalendarEventImportProps.ts
  packages/rest-typings/src/v1/calendar/CalendarEventUpdateProps.ts
Labels: stat: ready to merge, stat: QA assured

#35576 refactor: remove KonchatNotification `showDesktop` from meteor
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/client/hooks/notification/useDesktopNotification.ts
  apps/meteor/client/hooks/notification/useNotifyUser.ts
Labels: stat: ready to merge, stat: QA assured

#35397 fix(federation-v2): can not assign to readonly property #name
  .changeset/odd-waves-destroy.md
  apps/meteor/server/services/federation/application/AbstractFederationApplicationService.ts
  apps/meteor/server/services/federation/domain/FederatedUser.ts
  packages/core-typings/package.json
  packages/core-typings/src/IUser.ts
Labels: stat: ready to merge, stat: QA assured

#35497 fix: Add Apps log TTL index
  .changeset/fifty-moles-boil.md
  apps/meteor/ee/server/apps/startup.ts
  packages/model-typings/src/models/IAppLogsModel.ts
  packages/models/src/models/AppLogsModel.ts
  packages/models/src/models/BaseRaw.ts
Labels: stat: ready to merge, stat: QA assured

#35273 fix: CodeSettingInput renders duplicate code text box
  .changeset/honest-toys-guess.md
  apps/meteor/client/views/admin/settings/Setting/inputs/CodeMirror/CodeMirror.tsx
  apps/meteor/tests/e2e/administration-settings.spec.ts
  apps/meteor/tests/e2e/page-objects/admin.ts
Labels: stat: ready to merge, stat: QA assured

#35464 feat(federation-v2): allow federated user deletion if the user doesn't exist remotely
  .changeset/strong-shoes-end.md
  apps/meteor/app/lib/server/functions/deleteUser.ts
Labels: stat: ready to merge, stat: QA assured

#35581 regression: Department's unit field becomes disabled after selecting a unit
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-monitor-department.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35583 regression: Department's unit field missing error state
  apps/meteor/client/omnichannel/additionalForms/AutoCompleteUnit.tsx
  apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-monitor-department.spec.ts
  apps/meteor/tests/e2e/utils/omnichannel/units.ts
Labels: stat: ready to merge, stat: QA assured

#35582 chore: Move `UserPresenceContext` to `ui-contexts`
  apps/meteor/app/otr/client/OTRRoom.ts
  apps/meteor/client/components/UserStatus/ReactiveUserStatus.tsx
  apps/meteor/client/components/message/MessageHeader.tsx
  apps/meteor/client/components/message/variants/SystemMessage.tsx
  apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
  apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
  apps/meteor/client/contexts/UserPresenceContext.ts
  apps/meteor/client/hooks/usePresence.ts
  apps/meteor/client/lib/chats/ChatAPI.ts
  apps/meteor/client/lib/presence.ts
  apps/meteor/client/providers/UserPresenceProvider.tsx
  apps/meteor/client/views/admin/deviceManagement/DeviceManagementInfo/DeviceManagementInfo.tsx
  apps/meteor/client/views/room/Header/DirectRoomHeader.tsx
  apps/meteor/client/views/room/body/RoomTopic.tsx
  apps/meteor/client/views/room/contextualBar/OTR/OTRWithData.tsx
  packages/core-typings/src/IUser.ts
  packages/core-typings/src/Subscribable.ts
  packages/core-typings/src/index.ts
  packages/mock-providers/jest.config.ts
  packages/mock-providers/src/MockedAppRootBuilder.tsx
  packages/mock-providers/src/tests/useSetting.spec.tsx
  packages/mock-providers/src/tests/useSettings.spec.tsx
  packages/mock-providers/src/tests/useUserPresence.spec.tsx
  packages/ui-contexts/src/UserPresenceContext.ts
  packages/ui-contexts/src/hooks/useUserPresence.ts
  packages/ui-contexts/src/index.ts
Labels: stat: ready to merge, stat: QA assured

#35299 fix: changing email to verified not working on admin > users
  .changeset/bright-forks-drop.md
  apps/meteor/app/lib/server/functions/saveUser/saveUser.ts
  apps/meteor/tests/end-to-end/api/users.ts
Labels: stat: ready to merge, stat: QA assured

#35553 regression: topic rendering in DMs in new navigation
  apps/meteor/client/views/room/body/RoomTopic.spec.tsx
  apps/meteor/client/views/room/body/RoomTopic.tsx
Labels: stat: ready to merge, stat: QA assured

#35597 chore: Replace collection with Zustand store in `EditableSettingsProvider`
  apps/meteor/client/views/admin/EditableSettingsContext.ts
  apps/meteor/client/views/admin/settings/EditableSettingsProvider.tsx
  apps/meteor/client/views/admin/settings/SettingsRoute.tsx
  apps/meteor/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35585 refactor: remove KonchatNotification `notify` from meteor
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/client/hooks/notification/useDesktopNotification.ts
  apps/meteor/client/hooks/notification/useNotification.ts
  apps/meteor/client/views/account/preferences/PreferencesNotificationsSection.tsx
Labels: stat: ready to merge, stat: QA assured

#35587 chore: Prevent `useEmojiOne` operations from running every render
  apps/meteor/app/emoji-emojione/client/hooks/useEmojiOne.ts
Labels: stat: ready to merge, stat: QA assured

#35604 regression: Empty topic being displayed in direct messages
  apps/meteor/client/views/room/body/RoomTopic.tsx
  apps/meteor/tests/e2e/feature-preview.spec.ts
Labels: stat: ready to merge, stat: QA assured

#34494 feat: Audit users.update API endpoint
  .changeset/slow-ravens-tie.md
  apps/meteor/app/api/server/v1/users.ts
  apps/meteor/app/lib/server/functions/saveUser/saveUser.ts
  apps/meteor/jest.config.ts
  apps/meteor/server/lib/auditServerEvents/userChanged.spec.ts
  apps/meteor/server/lib/auditServerEvents/userChanged.ts
  packages/core-typings/src/ServerAudit/IAuditUserChangedEvent.ts
  packages/core-typings/src/index.ts
  packages/model-typings/src/updater.ts
  packages/models/src/updater.ts
Labels: stat: ready to merge, stat: QA assured

#35603 fix: adding blocks from block builder to the changes field
  .changeset/three-olives-explain.md
  packages/apps-engine/deno-runtime/lib/accessors/builders/MessageBuilder.ts
Labels: stat: ready to merge, stat: QA assured

#35612 chore: `HeaderState` receiving invalid prop
  apps/meteor/client/views/room/Header/RoomTitle.tsx
  apps/meteor/client/views/room/Header/icons/Favorite.tsx
  apps/meteor/client/views/room/HeaderV2/RoomTitle.tsx
  apps/meteor/client/views/room/HeaderV2/icons/Encrypted.tsx
  apps/meteor/client/views/room/HeaderV2/icons/Favorite.tsx
  apps/meteor/tests/e2e/channel-management.spec.ts
  packages/ui-client/src/components/Header/HeaderState.tsx
  packages/ui-client/src/components/HeaderV2/HeaderState.tsx
Labels: stat: ready to merge, stat: QA assured

#35615 feat: Remove room header avatar
  .changeset/hungry-wasps-remember.md
  apps/meteor/client/views/room/HeaderV2/HeaderSkeleton.tsx
  apps/meteor/client/views/room/HeaderV2/RoomHeader.tsx
  apps/meteor/tests/e2e/feature-preview.spec.ts
  packages/ui-client/src/components/HeaderV2/Header.tsx
Labels: stat: ready to merge, stat: QA assured

#35623 chore: expose `LicenseManagerInterface`
  ee/packages/license/src/index.ts
  ee/packages/license/src/license.ts
  ee/packages/license/src/licenseImp.ts
Labels: stat: ready to merge, stat: QA assured

#35589 refactor: remove deprecated `KonchatNotification`
  apps/meteor/app/ui/client/lib/KonchatNotification.ts
  apps/meteor/client/definitions/global.d.ts
  apps/meteor/client/hooks/notification/useNotification.ts
  apps/meteor/client/hooks/notification/useNotificationAllowed.ts
  apps/meteor/client/hooks/notification/useNotificationPermission.ts
  apps/meteor/client/lib/notificationManager.ts
  apps/meteor/client/views/account/preferences/PreferencesNotificationsSection.tsx
  apps/meteor/client/views/home/HomePage.tsx
  apps/meteor/client/views/root/AppLayout.tsx
Labels: stat: ready to merge, stat: QA assured

#35599 chore: Replace `RoomRoles` and `UserRoles`
  apps/meteor/app/models/client/index.ts
  apps/meteor/app/models/client/models/RoomRoles.ts
  apps/meteor/app/models/client/models/UserRoles.ts
  apps/meteor/client/components/message/header/hooks/useMessageRoles.ts
  apps/meteor/client/hooks/useRoomRolesQuery.ts
  apps/meteor/client/hooks/useUserRolesQuery.ts
  apps/meteor/client/lib/federation/Federation.spec.ts
  apps/meteor/client/lib/federation/Federation.ts
  apps/meteor/client/lib/queryKeys.ts
  apps/meteor/client/startup/index.ts
  apps/meteor/client/startup/userRoles.ts
  apps/meteor/client/views/room/body/hooks/useRoomRolesManagement.ts
  apps/meteor/client/views/room/hooks/useUserHasRoomRole.ts
  apps/meteor/client/views/room/providers/RoomProvider.tsx
Labels: stat: ready to merge, stat: QA assured

#35625 chore: implement middleware for handling EE endpoints
  apps/meteor/app/api/server/api.ts
  apps/meteor/app/api/server/definition.ts
  apps/meteor/app/api/server/router.ts
  apps/meteor/ee/app/api-enterprise/server/canned-responses.ts
  apps/meteor/ee/app/api-enterprise/server/index.ts
  apps/meteor/ee/app/api-enterprise/server/middlewares/license.ts
  apps/meteor/ee/app/api-enterprise/server/voip-freeswitch.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/agents.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/business-hours.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/contacts.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/departments.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/inquiries.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/monitors.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/priorities.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/reports.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/rooms.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/sla.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/tags.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/transcript.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/triggers.ts
  apps/meteor/ee/app/livechat-enterprise/server/api/units.ts
  apps/meteor/ee/app/livechat-enterprise/server/hooks/applyRoomRestrictions.ts
  apps/meteor/ee/app/livechat-enterprise/server/index.ts
  apps/meteor/ee/app/livechat-enterprise/server/lib/restrictQuery.ts
  apps/meteor/ee/server/api/audit.ts
  apps/meteor/ee/server/api/chat.ts
  apps/meteor/ee/server/api/engagementDashboard/channels.ts
  apps/meteor/ee/server/api/engagementDashboard/messages.ts
  apps/meteor/ee/server/api/engagementDashboard/users.ts
  apps/meteor/ee/server/api/federation/rooms.ts
  apps/meteor/ee/server/api/ldap.ts
  apps/meteor/ee/server/api/roles.ts
  apps/meteor/ee/server/api/sessions.ts
  apps/meteor/ee/server/index.ts
  apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
Labels: stat: ready to merge, stat: QA assured

#35624 regression: GUI crashing when editing a OC room
  apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/RoomEdit/RoomEdit.tsx
  apps/meteor/tests/e2e/omnichannel/omnichannel-chat-history.spec.ts
  apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts
  apps/meteor/tests/e2e/page-objects/home-omnichannel.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-room-info.ts
Labels: stat: ready to merge, stat: QA assured

#35630 refactor: replace `useCallback` with `useEffectEvent`
  apps/meteor/client/hooks/notification/useDesktopNotification.ts
  apps/meteor/client/hooks/notification/useNewMessageNotification.ts
  apps/meteor/client/hooks/notification/useNewRoomNotification.ts
  apps/meteor/client/hooks/notification/useNotification.ts
  apps/meteor/client/hooks/notification/useNotificationPermission.ts
Labels: stat: ready to merge, stat: QA assured

#35530 refactor: Remove Meteor.startup and Tracker.autorun from WordPress OAuth
  apps/meteor/app/wordpress/client/index.ts
  apps/meteor/app/wordpress/client/lib.ts
  apps/meteor/client/views/root/AppLayout.tsx
  apps/meteor/client/views/root/hooks/useWordPressOAuth.ts
Labels: stat: ready to merge, stat: QA assured

#35394 fix: Save button remains in loading state after saving app settings
  .changeset/fuzzy-eyes-clean.md
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.spec.tsx
  apps/meteor/client/views/marketplace/AppDetailsPage/AppDetailsPage.tsx
Labels: stat: ready to merge, communityPR, stat: QA assured

#35616 fix: Chat filtering breaks when "From" and "To" have the same date
  .changeset/tidy-cups-smoke.md
  apps/meteor/client/views/omnichannel/directory/chats/ChatsTable/useChatsQuery.ts
  apps/meteor/tests/e2e/omnichannel/omnichannel-contact-center-chats-filters.spec.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-contact-center-chats-filters.ts
  apps/meteor/tests/e2e/page-objects/omnichannel-contact-center-chats.ts
Labels: stat: ready to merge, stat: QA assured

#35614 fix: Missing margin in E2EE room header toolbox items
  .changeset/sweet-ravens-refuse.md
  apps/meteor/client/views/room/Header/RoomToolbox/RoomToolboxE2EESetup.tsx
  apps/meteor/client/views/room/HeaderV2/RoomToolbox/RoomToolboxE2EESetup.tsx
Labels: stat: ready to merge, stat: QA assured

#35635 chore: remove unreadMessages method usage
  apps/meteor/app/api/server/v1/subscriptions.ts
  apps/meteor/app/message-mark-as-unread/server/unreadMessages.ts
  apps/meteor/client/components/message/hooks/useMarkAsUnreadMutation.tsx
  apps/meteor/client/hooks/menuActions/useToggleReadAction.ts
Labels: stat: ready to merge, stat: QA assured

#35629 chore: Add `darkMode` configuration to `ui-client` storybook
  packages/ui-client/.storybook/DocsContainer.tsx
  packages/ui-client/.storybook/logo.svg
  packages/ui-client/.storybook/logo.svg.d.ts
  packages/ui-client/.storybook/main.ts
  packages/ui-client/.storybook/preview.tsx
  packages/ui-client/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35636 chore: remove `useLegacyThreadMessageJump`
  apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
  apps/meteor/client/views/room/contextualBar/Threads/hooks/useLegacyThreadMessageJump.ts
Labels: stat: ready to merge, stat: QA assured

#35641 chore: Replace `LivechatInquiry` collection
  apps/meteor/app/livechat/client/collections/LivechatInquiry.ts
  apps/meteor/app/livechat/client/lib/stream/queueManager.ts
  apps/meteor/client/hooks/useLivechatInquiryStore.ts
  apps/meteor/client/providers/OmnichannelProvider.tsx
  apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
  apps/meteor/client/views/room/HeaderV2/Omnichannel/QuickActions/hooks/useQuickActions.tsx
Labels: stat: ready to merge, stat: QA assured

#35646 test: flaky - stop closing page before sending the message
  apps/meteor/tests/e2e/mark-unread.spec.ts
  apps/meteor/tests/e2e/utils/create-target-channel.ts
Labels: stat: ready to merge, stat: QA assured

#35645 test: Replace invalid `imageLink` in image-gallery
  apps/meteor/tests/e2e/image-gallery.spec.ts
Labels: stat: ready to merge, stat: QA assured

#35631 feat: Place the room topic next to the room title
  .changeset/plenty-baboons-kneel.md
  apps/meteor/client/views/room/HeaderV2/RoomHeader.tsx
  apps/meteor/client/views/room/HeaderV2/RoomTitle.tsx
  apps/meteor/client/views/room/HeaderV2/RoomTopic.spec.tsx
  apps/meteor/client/views/room/HeaderV2/RoomTopic.tsx
  apps/meteor/client/views/room/body/RoomBodyV2.tsx
  packages/ui-client/src/components/HeaderV2/Header.tsx
  packages/ui-client/src/components/HeaderV2/HeaderTitle.tsx
Labels: stat: ready to merge, stat: QA assured

#35621 chore(deps): bump `vite` to 6.1.2
  apps/uikit-playground/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured

#35302 chore: don't use versions for internal deps
  packages/fuselage-ui-kit/package.json
  packages/gazzodown/package.json
  packages/ui-avatar/package.json
  packages/ui-client/package.json
  packages/ui-video-conf/package.json
  packages/ui-voip/package.json
  packages/web-ui-registration/package.json
  yarn.lock
Labels: stat: ready to merge, stat: QA assured
